import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-var',
  title: '01. Variables & Constants',
  explanation: `## Variables & Constants\n\nZig is explicit about everything. There are no hidden allocations, no hidden control flow, and no implicit type conversions.\n\n### const vs var\n\n\`\`\`zig\nconst name = "Zan";           // immutable (preferred)\nvar count: u32 = 0;            // mutable (only when needed)\ncount += 1;\n\`\`\`\n\nZig prefers \`const\` over \`var\`. If you don't need to mutate, use \`const\`. The compiler will warn if you use \`var\` but never mutate.\n\n### comptime\n\nValues known at compile time can be declared with \`comptime\`:\n\n\`\`\`zig\nconst max_size = comptime 1024 * 1024;\ncomptime var x: u32 = 0;\n\`\`\`\n\n### Naming Conventions\n\nZig uses \`snake_case\` for variables and functions, \`PascalCase\` for types. The \`_\` identifier discards a value.\n\n\`\`\`zig\nconst _ = unused_value;       // explicitly discard\nfor (items) |_| count += 1;   // discard loop variable\n\`\`\`\n\n### Shadowing & Scope\n\nZig does NOT allow shadowing. Blocks create new scopes:\n\n\`\`\`zig\nconst x: u32 = 10;\n// const x: u32 = 20;  // ERROR: redefinition\n{\n    const y: u32 = 20;  // y exists only in this block\n}\n// y is not accessible here\n\`\`\`\n\n### pub Visibility\n\n\`pub\` makes a declaration visible outside the current file:\n\n\`\`\`zig\npub const VERSION = 1;\npub fn init() void { }\n\`\`\``,
  exercises: [
    {
      id: 'zig-var-1',
      title: 'Declare an Immutable Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare an immutable variable greeting with the value "Hello, Zig!".',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    ___ greeting = "Hello, Zig!";\n    std.debug.print("{s}\\n", .{greeting});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const greeting = "Hello, Zig!";\n    std.debug.print("{s}\\n", .{greeting});\n}`,
      hints: ['Zig uses a keyword meaning "constant" for immutable bindings.', 'The keyword is `const` -- it declares a value that cannot be reassigned.', 'const greeting = "Hello, Zig!";'],
      concepts: ['const', 'string-literal', 'std.debug.print'],
    },
    {
      id: 'zig-var-2',
      title: 'Declare a Mutable Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare a mutable variable count of type u32 starting at 0, then increment it.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    ___ count: ___ = 0;\n    count += 1;\n    std.debug.print("count = {d}\\n", .{count});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var count: u32 = 0;\n    count += 1;\n    std.debug.print("count = {d}\\n", .{count});\n}`,
      hints: ['You need a mutable binding so you can increment.', 'Use `var` for mutable variables and specify the type after a colon.', 'var count: u32 = 0;'],
      concepts: ['var', 'u32', 'mutation'],
    },
    {
      id: 'zig-var-3',
      title: 'Type Annotations',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Add the correct type annotations for each variable.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const age: ___ = 25;\n    const pi: ___ = 3.14;\n    const active: ___ = true;\n    const letter: ___ = 'Z';\n    std.debug.print("{d} {d:.2} {} {c}\\n", .{ age, pi, active, letter });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const age: u32 = 25;\n    const pi: f64 = 3.14;\n    const active: bool = true;\n    const letter: u8 = 'Z';\n    std.debug.print("{d} {d:.2} {} {c}\\n", .{ age, pi, active, letter });\n}`,
      hints: ['Unsigned integers use u followed by bit width. Floats use f followed by bit width.', 'Characters in Zig are just u8 values. Booleans are `bool`.', 'u32, f64, bool, u8'],
      concepts: ['u32', 'f64', 'bool', 'u8', 'type-annotation'],
    },
    {
      id: 'zig-var-4',
      title: 'Comptime Constants',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare compile-time constants using comptime.',
      skeleton: `const std = @import("std");\n\nconst BUFFER_SIZE = ___ 1024 * 4;\nconst MAGIC: u32 = ___ 0xDEADBEEF;\n\npub fn main() void {\n    std.debug.print("buffer: {d}, magic: {x}\\n", .{ BUFFER_SIZE, MAGIC });\n}`,
      solution: `const std = @import("std");\n\nconst BUFFER_SIZE = comptime 1024 * 4;\nconst MAGIC: u32 = comptime 0xDEADBEEF;\n\npub fn main() void {\n    std.debug.print("buffer: {d}, magic: {x}\\n", .{ BUFFER_SIZE, MAGIC });\n}`,
      hints: ['Zig has a keyword to force compile-time evaluation.', 'The keyword `comptime` ensures the expression is evaluated at compile time.', 'comptime 1024 * 4'],
      concepts: ['comptime', 'compile-time-evaluation', 'hex-literals'],
    },
    {
      id: 'zig-var-5',
      title: 'Discarding Values with _',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use _ to discard unused values. Zig errors on unused variables.',
      skeleton: `const std = @import("std");\n\nfn getTwo() struct { a: u32, b: u32 } {\n    return .{ .a = 10, .b = 20 };\n}\n\npub fn main() void {\n    const result = getTwo();\n    // We only need .b, discard .a\n    const ___ = result.a;\n    std.debug.print("b = {d}\\n", .{result.b});\n}`,
      solution: `const std = @import("std");\n\nfn getTwo() struct { a: u32, b: u32 } {\n    return .{ .a = 10, .b = 20 };\n}\n\npub fn main() void {\n    const result = getTwo();\n    const _ = result.a;\n    std.debug.print("b = {d}\\n", .{result.b});\n}`,
      hints: ['Zig does not allow unused variables -- you must use them or explicitly discard.', 'The underscore _ is a special identifier that discards a value.', 'const _ = result.a;'],
      concepts: ['discard', 'underscore', 'unused-variable'],
    },
    {
      id: 'zig-var-6',
      title: 'Pub Visibility',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Make the constant and function visible outside this module using pub.',
      skeleton: `const std = @import("std");\n\n___ const VERSION: u32 = 3;\n\n___ fn getVersion() u32 {\n    return VERSION;\n}\n\npub fn main() void {\n    std.debug.print("v{d}\\n", .{getVersion()});\n}`,
      solution: `const std = @import("std");\n\npub const VERSION: u32 = 3;\n\npub fn getVersion() u32 {\n    return VERSION;\n}\n\npub fn main() void {\n    std.debug.print("v{d}\\n", .{getVersion()});\n}`,
      hints: ['To export a declaration from a file, prefix it with a visibility keyword.', 'The keyword `pub` makes declarations accessible outside the current module.', 'pub const VERSION: u32 = 3;'],
      concepts: ['pub', 'visibility', 'module-exports'],
    },
    {
      id: 'zig-var-7',
      title: 'Write a Swap Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function swap that takes two *u32 pointers and swaps their values using a temporary variable.',
      skeleton: `const std = @import("std");\n\n// Write swap here\n// fn swap(a: *u32, b: *u32) void\n\npub fn main() void {\n    var x: u32 = 10;\n    var y: u32 = 20;\n    swap(&x, &y);\n    std.debug.print("x={d} y={d}\\n", .{ x, y });\n    // Expected: x=20 y=10\n}`,
      solution: `const std = @import("std");\n\nfn swap(a: *u32, b: *u32) void {\n    const tmp = a.*;\n    a.* = b.*;\n    b.* = tmp;\n}\n\npub fn main() void {\n    var x: u32 = 10;\n    var y: u32 = 20;\n    swap(&x, &y);\n    std.debug.print("x={d} y={d}\\n", .{ x, y });\n}`,
      hints: ['Pointers are dereferenced with .* in Zig, not * like C.', 'Save a.* into a const tmp, then assign a.* = b.*, then b.* = tmp.', 'fn swap(a: *u32, b: *u32) void { const tmp = a.*; a.* = b.*; b.* = tmp; }'],
      concepts: ['pointers', 'dereference', 'mutable-parameters', 'tmp-variable'],
    },
    {
      id: 'zig-var-8',
      title: 'Write a Max Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function maxVal that takes two i32 values and returns the larger one.',
      skeleton: `const std = @import("std");\n\n// Write maxVal here\n// fn maxVal(a: i32, b: i32) i32\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{maxVal(10, 20)});\n    std.debug.print("{d}\\n", .{maxVal(-5, -10)});\n    // Expected: 20, -5\n}`,
      solution: `const std = @import("std");\n\nfn maxVal(a: i32, b: i32) i32 {\n    return if (a > b) a else b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{maxVal(10, 20)});\n    std.debug.print("{d}\\n", .{maxVal(-5, -10)});\n}`,
      hints: ['Zig if is an expression that returns a value.', 'return if (a > b) a else b; works as a ternary.', 'fn maxVal(a: i32, b: i32) i32 { return if (a > b) a else b; }'],
      concepts: ['if-expression', 'return-type', 'i32', 'comparison'],
    },
    {
      id: 'zig-var-9',
      title: 'Write a Clamp Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function clamp that takes a value, min, and max (all i32) and returns the value clamped to [min, max].',
      skeleton: `const std = @import("std");\n\n// Write clamp here\n// fn clamp(val: i32, min_val: i32, max_val: i32) i32\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{clamp(15, 0, 10)});  // 10\n    std.debug.print("{d}\\n", .{clamp(-5, 0, 10)});  // 0\n    std.debug.print("{d}\\n", .{clamp(5, 0, 10)});   // 5\n}`,
      solution: `const std = @import("std");\n\nfn clamp(val: i32, min_val: i32, max_val: i32) i32 {\n    if (val < min_val) return min_val;\n    if (val > max_val) return max_val;\n    return val;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{clamp(15, 0, 10)});\n    std.debug.print("{d}\\n", .{clamp(-5, 0, 10)});\n    std.debug.print("{d}\\n", .{clamp(5, 0, 10)});\n}`,
      hints: ['Check if the value is below min first, then check if above max.', 'Use early returns: if (val < min_val) return min_val;', 'Three cases: below min, above max, or in range (return val).'],
      concepts: ['if-statement', 'early-return', 'range-check', 'i32'],
    },
    {
      id: 'zig-var-10',
      title: 'Write an Absolute Value Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function absVal that takes an i32 and returns the absolute value as u32.',
      skeleton: `const std = @import("std");\n\n// Write absVal here\n// fn absVal(x: i32) u32\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{absVal(-42)});  // 42\n    std.debug.print("{d}\\n", .{absVal(10)});   // 10\n    std.debug.print("{d}\\n", .{absVal(0)});    // 0\n}`,
      solution: `const std = @import("std");\n\nfn absVal(x: i32) u32 {\n    if (x < 0) {\n        return @intCast(-x);\n    }\n    return @intCast(x);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{absVal(-42)});\n    std.debug.print("{d}\\n", .{absVal(10)});\n    std.debug.print("{d}\\n", .{absVal(0)});\n}`,
      hints: ['Negate a negative i32 to make it positive, then cast to u32.', 'Use @intCast to convert between i32 and u32 -- Zig requires explicit casts.', 'if (x < 0) return @intCast(-x); else return @intCast(x);'],
      concepts: ['@intCast', 'signed-unsigned', 'negation', 'explicit-cast'],
    },
    {
      id: 'zig-var-11',
      title: 'Write an isEven Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function isEven that takes a u32 and returns true if it is even.',
      skeleton: `const std = @import("std");\n\n// Write isEven here\n// fn isEven(n: u32) bool\n\npub fn main() void {\n    std.debug.print("{} {} {}\\n", .{ isEven(4), isEven(7), isEven(0) });\n    // Expected: true false true\n}`,
      solution: `const std = @import("std");\n\nfn isEven(n: u32) bool {\n    return n % 2 == 0;\n}\n\npub fn main() void {\n    std.debug.print("{} {} {}\\n", .{ isEven(4), isEven(7), isEven(0) });\n}`,
      hints: ['A number is even if dividing by 2 has no remainder.', 'Use the modulo operator % to check divisibility.', 'return n % 2 == 0;'],
      concepts: ['modulo', 'bool-return', 'comparison-expression'],
    },
    {
      id: 'zig-var-12',
      title: 'Fix the Unused Variable Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Zig does not allow unused variables. Fix the code so it compiles.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x: u32 = 10;\n    const y: u32 = 20;\n    const z: u32 = 30;\n    std.debug.print("{d}\\n", .{y});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const _ = @as(u32, 10);\n    const y: u32 = 20;\n    const _ = @as(u32, 30);\n    std.debug.print("{d}\\n", .{y});\n}`,
      hints: ['Zig errors on variables that are declared but never used.', 'Assign unused values to _ to explicitly discard them.', 'Replace `const x` and `const z` with `const _`.'],
      concepts: ['unused-variable-error', 'discard', 'underscore'],
    },
    {
      id: 'zig-var-13',
      title: 'Fix the Shadowing Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Zig does not allow variable shadowing. Fix the code by renaming the inner variable.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const value: u32 = 10;\n    {\n        const value: u32 = 20;\n        std.debug.print("inner: {d}\\n", .{value});\n    }\n    std.debug.print("outer: {d}\\n", .{value});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const value: u32 = 10;\n    {\n        const inner_value: u32 = 20;\n        std.debug.print("inner: {d}\\n", .{inner_value});\n    }\n    std.debug.print("outer: {d}\\n", .{value});\n}`,
      hints: ['Unlike Rust or JavaScript, Zig does NOT allow shadowing -- even in inner scopes.', 'Rename the inner declaration to a different name like inner_value.', 'const inner_value: u32 = 20;'],
      concepts: ['no-shadowing', 'scoping', 'block-scope'],
    },
    {
      id: 'zig-var-14',
      title: 'Fix the Const Mutation Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the code so the counter can be incremented.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const counter: u32 = 0;\n    counter += 1;\n    counter += 1;\n    std.debug.print("counter = {d}\\n", .{counter});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var counter: u32 = 0;\n    counter += 1;\n    counter += 1;\n    std.debug.print("counter = {d}\\n", .{counter});\n}`,
      hints: ['You cannot mutate a value declared with const.', 'Change const to var to allow reassignment.', 'var counter: u32 = 0;'],
      concepts: ['const-vs-var', 'mutation', 'compile-error'],
    },
    {
      id: 'zig-var-15',
      title: 'Predict const Behavior',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict what this code prints.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var a: u32 = 5;\n    const b: u32 = a;\n    a = 10;\n    std.debug.print("a={d} b={d}\\n", .{ a, b });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var a: u32 = 5;\n    const b: u32 = a;\n    a = 10;\n    std.debug.print("a={d} b={d}\\n", .{ a, b });\n}\n\n// Output: a=10 b=5`,
      hints: ['const b copies the value of a at the time of assignment.', 'Changing a afterwards does not affect b -- it is a copy, not a reference.', 'a=10 b=5'],
      concepts: ['value-copy', 'const-binding', 'independence'],
    },
    {
      id: 'zig-var-16',
      title: 'Predict Block Scope',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what this code prints. Think about block scope and labeled blocks.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x: u32 = blk: {\n        const a: u32 = 3;\n        const b: u32 = 7;\n        break :blk a + b;\n    };\n    std.debug.print("x={d}\\n", .{x});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const x: u32 = blk: {\n        const a: u32 = 3;\n        const b: u32 = 7;\n        break :blk a + b;\n    };\n    std.debug.print("x={d}\\n", .{x});\n}\n\n// Output: x=10`,
      hints: ['Labeled blocks return a value via break :label value.', 'a + b = 3 + 7 = 10, which is assigned to x.', 'x=10'],
      concepts: ['labeled-block', 'break-value', 'block-expression'],
    },
    {
      id: 'zig-var-17',
      title: 'Predict Comptime Evaluation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what this code prints.',
      skeleton: `const std = @import("std");\n\nfn square(x: u32) u32 {\n    return x * x;\n}\n\npub fn main() void {\n    const a = comptime square(5);\n    const b = comptime square(3);\n    const c = a + b;\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\nfn square(x: u32) u32 {\n    return x * x;\n}\n\npub fn main() void {\n    const a = comptime square(5);\n    const b = comptime square(3);\n    const c = a + b;\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}\n\n// Output: 25 9 34`,
      hints: ['square(5) = 25, square(3) = 9.', 'Both are evaluated at compile time. c = 25 + 9 = 34.', '25 9 34'],
      concepts: ['comptime', 'compile-time-function', 'constant-folding'],
    },
    {
      id: 'zig-var-18',
      title: 'Refactor Magic Numbers',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Extract the magic numbers into named constants for clarity.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var health: i32 = 100;\n    health -= 25;\n    if (health < 30) {\n        std.debug.print("critical!\\n", .{});\n    }\n    health += 50;\n    if (health > 100) {\n        health = 100;\n    }\n    std.debug.print("health: {d}\\n", .{health});\n}`,
      solution: `const std = @import("std");\n\nconst MAX_HEALTH: i32 = 100;\nconst CRITICAL_THRESHOLD: i32 = 30;\nconst DAMAGE: i32 = 25;\nconst HEAL_AMOUNT: i32 = 50;\n\npub fn main() void {\n    var health: i32 = MAX_HEALTH;\n    health -= DAMAGE;\n    if (health < CRITICAL_THRESHOLD) {\n        std.debug.print("critical!\\n", .{});\n    }\n    health += HEAL_AMOUNT;\n    if (health > MAX_HEALTH) {\n        health = MAX_HEALTH;\n    }\n    std.debug.print("health: {d}\\n", .{health});\n}`,
      hints: ['Replace each magic number with a descriptive const at module level.', 'Use SCREAMING_SNAKE_CASE for constants: MAX_HEALTH, CRITICAL_THRESHOLD, etc.', 'Declare const MAX_HEALTH: i32 = 100; and similar for each value.'],
      concepts: ['named-constants', 'readability', 'magic-numbers'],
    },
    {
      id: 'zig-var-19',
      title: 'Refactor to Use Labeled Block',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the if/else chain into a labeled block expression to initialize the constant.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const score: u32 = 85;\n    var grade: []const u8 = undefined;\n    if (score >= 90) {\n        grade = "A";\n    } else if (score >= 80) {\n        grade = "B";\n    } else if (score >= 70) {\n        grade = "C";\n    } else {\n        grade = "F";\n    }\n    std.debug.print("grade: {s}\\n", .{grade});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const score: u32 = 85;\n    const grade: []const u8 = blk: {\n        if (score >= 90) break :blk "A";\n        if (score >= 80) break :blk "B";\n        if (score >= 70) break :blk "C";\n        break :blk "F";\n    };\n    std.debug.print("grade: {s}\\n", .{grade});\n}`,
      hints: ['A labeled block can return a value with break :label value.', 'Use blk: { ... break :blk value; } to compute grade as a const.', 'This avoids var and undefined by using a block expression.'],
      concepts: ['labeled-block', 'block-expression', 'const-initialization', 'refactor-var-to-const'],
    },
    {
      id: 'zig-var-20',
      title: 'Comptime Variable Loop',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function computeSum that takes a comptime u32 n and returns the sum 1 + 2 + ... + n using a comptime var loop.',
      skeleton: `const std = @import("std");\n\n// Write computeSum here\n// fn computeSum(comptime n: u32) u32\n\npub fn main() void {\n    const result = comptime computeSum(10);\n    std.debug.print("sum 1..10 = {d}\\n", .{result});\n    // Expected: sum 1..10 = 55\n}`,
      solution: `const std = @import("std");\n\nfn computeSum(comptime n: u32) u32 {\n    comptime var sum: u32 = 0;\n    comptime var i: u32 = 1;\n    inline while (i <= n) : (i += 1) {\n        sum += i;\n    }\n    return sum;\n}\n\npub fn main() void {\n    const result = comptime computeSum(10);\n    std.debug.print("sum 1..10 = {d}\\n", .{result});\n}`,
      hints: ['Use comptime var to declare mutable compile-time variables.', 'An inline while loop with comptime vars evaluates entirely at compile time.', 'inline while (i <= n) : (i += 1) { sum += i; }'],
      concepts: ['comptime-var', 'inline-while', 'compile-time-loop', 'comptime-function'],
    },
  ],
};
