import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-types',
  title: '02. Primitive Types',
  explanation: `## Primitive Types\n\nZig has a rich set of primitive types with explicit sizes.\n\n### Integer Types\n\nUnsigned: \`u8\`, \`u16\`, \`u32\`, \`u64\`, \`u128\`\nSigned: \`i8\`, \`i16\`, \`i32\`, \`i64\`, \`i128\`\n\n\`\`\`zig\nconst byte: u8 = 255;       // 0 to 255\nconst big: u128 = 999999;   // up to 2^128 - 1\nconst neg: i8 = -128;       // -128 to 127\n\`\`\`\n\n### Float Types\n\n\`f16\`, \`f32\`, \`f64\`, \`f80\`, \`f128\`:\n\n\`\`\`zig\nconst pi: f64 = 3.14159265358979;\nconst half: f16 = 0.5;\n\`\`\`\n\n### Special Types\n\n- \`bool\` -- \`true\` or \`false\`\n- \`void\` -- zero-sized type, used for functions that return nothing\n- \`noreturn\` -- function never returns (e.g., exits or loops forever)\n- \`comptime_int\` -- arbitrary-precision integer known at comptime\n- \`comptime_float\` -- arbitrary-precision float known at comptime\n\n\`\`\`zig\nconst x = 42;           // comptime_int (no fixed size yet)\nconst y: u8 = x;        // coerced to u8 at comptime\n\`\`\`\n\n### Type Coercion\n\nZig allows safe comptime coercions but NEVER implicit runtime coercions:\n\n\`\`\`zig\nconst a: u8 = 10;\nconst b: u32 = @intCast(a);    // explicit widening\nconst c: u8 = @truncate(b);    // explicit narrowing\nconst d: f64 = @floatFromInt(a); // int to float\nconst e: u32 = @intFromFloat(3.0); // float to int\n\`\`\`\n\n### Sentinel Values\n\nTypes can have sentinel terminators:\n\n\`\`\`zig\nconst str: [:0]const u8 = "hello"; // null-terminated\nconst arr: [3:0]u8 = .{ 1, 2, 3 }; // sentinel 0 after index 2\n\`\`\``,
  exercises: [
    {
      id: 'zig-types-1',
      title: 'Integer Type Sizes',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Choose the correct integer types for each variable.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const byte: ___ = 255;         // max value 255\n    const big: ___ = 100000;       // needs > 16 bits\n    const signed: ___ = -50;       // negative, small range\n    const huge: ___ = 99999999999; // needs > 32 bits\n    std.debug.print("{d} {d} {d} {d}\\n", .{ byte, big, signed, huge });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const byte: u8 = 255;\n    const big: u32 = 100000;\n    const signed: i8 = -50;\n    const huge: u64 = 99999999999;\n    std.debug.print("{d} {d} {d} {d}\\n", .{ byte, big, signed, huge });\n}`,
      hints: ['u8 holds 0-255. u16 holds 0-65535. u32 holds up to ~4 billion.', 'For negative values, use signed types (i8, i16, etc). i8 holds -128 to 127.', 'u8, u32, i8, u64'],
      concepts: ['u8', 'u32', 'i8', 'u64', 'integer-ranges'],
    },
    {
      id: 'zig-types-2',
      title: 'Float Types',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Choose the correct float types.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const pi: ___ = 3.14159265358979;\n    const half: ___ = 0.5;\n    std.debug.print("{d:.6} {d:.1}\\n", .{ pi, half });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const pi: f64 = 3.14159265358979;\n    const half: f32 = 0.5;\n    std.debug.print("{d:.6} {d:.1}\\n", .{ pi, half });\n}`,
      hints: ['f64 gives double precision for precise values like pi.', 'f32 is sufficient for simple values like 0.5.', 'f64 and f32'],
      concepts: ['f64', 'f32', 'float-precision'],
    },
    {
      id: 'zig-types-3',
      title: 'Bool and Void Types',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fill in the correct special types.',
      skeleton: `const std = @import("std");\n\nfn logMessage(msg: []const u8) ___ {\n    std.debug.print("[LOG] {s}\\n", .{msg});\n}\n\npub fn main() void {\n    const enabled: ___ = true;\n    if (enabled) {\n        logMessage("system started");\n    }\n}`,
      solution: `const std = @import("std");\n\nfn logMessage(msg: []const u8) void {\n    std.debug.print("[LOG] {s}\\n", .{msg});\n}\n\npub fn main() void {\n    const enabled: bool = true;\n    if (enabled) {\n        logMessage("system started");\n    }\n}`,
      hints: ['Functions that return nothing use void as the return type.', 'true and false are values of type bool.', 'void and bool'],
      concepts: ['void', 'bool', 'return-type'],
    },
    {
      id: 'zig-types-4',
      title: 'Explicit Integer Cast with @intCast',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use @intCast to convert between integer types.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const small: u8 = 42;\n    const wide: u32 = ___;\n    const narrow: u8 = ___;\n    std.debug.print("{d} {d}\\n", .{ wide, narrow });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const small: u8 = 42;\n    const wide: u32 = @intCast(small);\n    const narrow: u8 = @truncate(wide);\n    std.debug.print("{d} {d}\\n", .{ wide, narrow });\n}`,
      hints: ['Widening uses @intCast to go from u8 to u32.', 'Narrowing uses @truncate to go from u32 to u8.', '@intCast(small) and @truncate(wide)'],
      concepts: ['@intCast', '@truncate', 'widening', 'narrowing'],
    },
    {
      id: 'zig-types-5',
      title: 'Float-Int Conversion',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Convert between float and integer types explicitly.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const count: u32 = 7;\n    const total: u32 = 2;\n    const ratio: f64 = ___(count) / ___(total);\n    const rounded: u32 = ___(@as(f64, 3.7));\n    std.debug.print("{d:.2} {d}\\n", .{ ratio, rounded });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const count: u32 = 7;\n    const total: u32 = 2;\n    const ratio: f64 = @floatFromInt(count) / @floatFromInt(total);\n    const rounded: u32 = @intFromFloat(@as(f64, 3.7));\n    std.debug.print("{d:.2} {d}\\n", .{ ratio, rounded });\n}`,
      hints: ['Use @floatFromInt to convert an integer to a float for division.', '@intFromFloat converts a float to an integer (truncates toward zero).', '@floatFromInt and @intFromFloat'],
      concepts: ['@floatFromInt', '@intFromFloat', '@as', 'type-conversion'],
    },
    {
      id: 'zig-types-6',
      title: 'Comptime Integer Type',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Understand how comptime_int works with type coercion.',
      skeleton: `const std = @import("std");\n\n// This is comptime_int -- no fixed size\nconst MAGIC = 42;\n\npub fn main() void {\n    // comptime_int coerces to the target type\n    const a: ___ = MAGIC;   // becomes u8\n    const b: ___ = MAGIC;   // becomes u64\n    const c: ___ = MAGIC;   // becomes i32\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}`,
      solution: `const std = @import("std");\n\nconst MAGIC = 42;\n\npub fn main() void {\n    const a: u8 = MAGIC;\n    const b: u64 = MAGIC;\n    const c: i32 = MAGIC;\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}`,
      hints: ['comptime_int has no fixed size -- it coerces to any integer type at comptime.', 'The value 42 fits in u8, u64, and i32, so all are valid.', 'u8, u64, i32'],
      concepts: ['comptime_int', 'type-coercion', 'comptime-to-runtime'],
    },
    {
      id: 'zig-types-7',
      title: 'Write a safeAdd Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function safeAdd that takes two u8 values and returns a u16 to avoid overflow.',
      skeleton: `const std = @import("std");\n\n// Write safeAdd here\n// fn safeAdd(a: u8, b: u8) u16\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{safeAdd(200, 200)});  // 400\n    std.debug.print("{d}\\n", .{safeAdd(255, 255)});  // 510\n}`,
      solution: `const std = @import("std");\n\nfn safeAdd(a: u8, b: u8) u16 {\n    const wa: u16 = @intCast(a);\n    const wb: u16 = @intCast(b);\n    return wa + wb;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{safeAdd(200, 200)});\n    std.debug.print("{d}\\n", .{safeAdd(255, 255)});\n}`,
      hints: ['You cannot add two u8 values if the result exceeds 255.', 'Cast both to u16 with @intCast before adding.', 'Widen first, then add: @intCast(a) + @intCast(b).'],
      concepts: ['@intCast', 'overflow-prevention', 'widening'],
    },
    {
      id: 'zig-types-8',
      title: 'Write a toFahrenheit Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function toFahrenheit that converts a Celsius f64 to Fahrenheit: F = C * 9/5 + 32.',
      skeleton: `const std = @import("std");\n\n// Write toFahrenheit here\n// fn toFahrenheit(celsius: f64) f64\n\npub fn main() void {\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(0.0)});    // 32.0\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(100.0)});  // 212.0\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(37.0)});   // 98.6\n}`,
      solution: `const std = @import("std");\n\nfn toFahrenheit(celsius: f64) f64 {\n    return celsius * 9.0 / 5.0 + 32.0;\n}\n\npub fn main() void {\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(0.0)});\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(100.0)});\n    std.debug.print("{d:.1}\\n", .{toFahrenheit(37.0)});\n}`,
      hints: ['The formula is F = C * 9/5 + 32.', 'Use float literals: 9.0, 5.0, 32.0 to stay in f64.', 'return celsius * 9.0 / 5.0 + 32.0;'],
      concepts: ['f64', 'float-arithmetic', 'formula'],
    },
    {
      id: 'zig-types-9',
      title: 'Write a bitCount Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function bitCount that takes a u32 and returns the number of set bits (1s) as u32.',
      skeleton: `const std = @import("std");\n\n// Write bitCount here\n// fn bitCount(val: u32) u32\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{bitCount(0b1010_1010)});  // 4\n    std.debug.print("{d}\\n", .{bitCount(0xFF)});          // 8\n    std.debug.print("{d}\\n", .{bitCount(0)});             // 0\n}`,
      solution: `const std = @import("std");\n\nfn bitCount(val: u32) u32 {\n    var count: u32 = 0;\n    var v = val;\n    while (v != 0) {\n        count += v & 1;\n        v >>= 1;\n    }\n    return count;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{bitCount(0b1010_1010)});\n    std.debug.print("{d}\\n", .{bitCount(0xFF)});\n    std.debug.print("{d}\\n", .{bitCount(0)});\n}`,
      hints: ['Check the lowest bit with v & 1, then shift right with v >>= 1.', 'Loop while v != 0, counting each set bit.', 'Use a var copy of val since parameters are immutable in Zig.'],
      concepts: ['bitwise-and', 'right-shift', 'bit-counting', 'while-loop'],
    },
    {
      id: 'zig-types-10',
      title: 'Write a toU8Clamped Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function toU8Clamped that takes an i32 and returns a u8, clamping to [0, 255].',
      skeleton: `const std = @import("std");\n\n// Write toU8Clamped here\n// fn toU8Clamped(val: i32) u8\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{toU8Clamped(300)});   // 255\n    std.debug.print("{d}\\n", .{toU8Clamped(-10)});   // 0\n    std.debug.print("{d}\\n", .{toU8Clamped(128)});   // 128\n}`,
      solution: `const std = @import("std");\n\nfn toU8Clamped(val: i32) u8 {\n    if (val < 0) return 0;\n    if (val > 255) return 255;\n    return @intCast(val);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{toU8Clamped(300)});\n    std.debug.print("{d}\\n", .{toU8Clamped(-10)});\n    std.debug.print("{d}\\n", .{toU8Clamped(128)});\n}`,
      hints: ['Check bounds before casting: < 0 returns 0, > 255 returns 255.', 'Only use @intCast when you know the value fits in u8.', 'if (val < 0) return 0; if (val > 255) return 255; return @intCast(val);'],
      concepts: ['clamping', '@intCast', 'range-checking', 'safe-narrowing'],
    },
    {
      id: 'zig-types-11',
      title: 'Write a byteToHex Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function byteToHex that takes a u8 and returns a [2]u8 array with the hex characters.',
      skeleton: `const std = @import("std");\n\n// Write byteToHex here\n// fn byteToHex(byte: u8) [2]u8\n// Hint: "0123456789abcdef" is a lookup table\n\npub fn main() void {\n    const r1 = byteToHex(0xFF);\n    const r2 = byteToHex(0x0A);\n    const r3 = byteToHex(0x00);\n    std.debug.print("{c}{c} {c}{c} {c}{c}\\n", .{ r1[0], r1[1], r2[0], r2[1], r3[0], r3[1] });\n    // Expected: ff 0a 00\n}`,
      solution: `const std = @import("std");\n\nfn byteToHex(byte: u8) [2]u8 {\n    const hex = "0123456789abcdef";\n    return .{ hex[byte >> 4], hex[byte & 0x0F] };\n}\n\npub fn main() void {\n    const r1 = byteToHex(0xFF);\n    const r2 = byteToHex(0x0A);\n    const r3 = byteToHex(0x00);\n    std.debug.print("{c}{c} {c}{c} {c}{c}\\n", .{ r1[0], r1[1], r2[0], r2[1], r3[0], r3[1] });\n}`,
      hints: ['The high nibble is byte >> 4, the low nibble is byte & 0x0F.', 'Index into the hex lookup string with each nibble.', 'return .{ hex[byte >> 4], hex[byte & 0x0F] };'],
      concepts: ['bit-shifting', 'bitwise-and', 'lookup-table', 'array-return'],
    },
    {
      id: 'zig-types-12',
      title: 'Fix the Type Mismatch Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the implicit type conversion errors. Zig never converts types implicitly at runtime.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u32 = a;              // BUG\n    const c: f64 = b;              // BUG\n    const d: u8 = b;               // BUG\n    std.debug.print("{d} {d:.1} {d}\\n", .{ b, c, d });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u32 = @intCast(a);\n    const c: f64 = @floatFromInt(b);\n    const d: u8 = @truncate(b);\n    std.debug.print("{d} {d:.1} {d}\\n", .{ b, c, d });\n}`,
      hints: ['Zig requires explicit casts even for safe widenings.', '@intCast for integer widening, @floatFromInt for int-to-float, @truncate for narrowing.', '@intCast(a), @floatFromInt(b), @truncate(b)'],
      concepts: ['@intCast', '@floatFromInt', '@truncate', 'no-implicit-coercion'],
    },
    {
      id: 'zig-types-13',
      title: 'Fix the Float Division Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the integer division to produce a float result.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const numerator: u32 = 7;\n    const denominator: u32 = 2;\n    // BUG: This performs integer division\n    const result: f64 = numerator / denominator;\n    std.debug.print("{d:.2}\\n", .{result});\n    // Expected: 3.50\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const numerator: u32 = 7;\n    const denominator: u32 = 2;\n    const result: f64 = @as(f64, @floatFromInt(numerator)) / @as(f64, @floatFromInt(denominator));\n    std.debug.print("{d:.2}\\n", .{result});\n}`,
      hints: ['Integer division truncates. You need to convert to float before dividing.', 'Use @floatFromInt on both operands to perform float division.', '@floatFromInt(numerator) / @floatFromInt(denominator)'],
      concepts: ['@floatFromInt', 'float-division', 'integer-division-truncation'],
    },
    {
      id: 'zig-types-14',
      title: 'Fix the Overflow Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the overflow: adding two u8 values that exceed 255.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = 100;\n    // BUG: 200 + 100 = 300, which overflows u8\n    const sum: u8 = a + b;\n    std.debug.print("{d}\\n", .{sum});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = 100;\n    const sum: u16 = @as(u16, @intCast(a)) + @as(u16, @intCast(b));\n    std.debug.print("{d}\\n", .{sum});\n}`,
      hints: ['u8 can only hold 0-255. The sum 300 overflows.', 'Widen both operands to u16 before adding.', 'Cast both to u16 with @intCast, then add.'],
      concepts: ['overflow', '@intCast', 'widening', 'u16'],
    },
    {
      id: 'zig-types-15',
      title: 'Predict Integer Truncation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output when truncating a u32 to u8.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const val: u32 = 258;\n    const trunc: u8 = @truncate(val);\n    std.debug.print("{d}\\n", .{trunc});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const val: u32 = 258;\n    const trunc: u8 = @truncate(val);\n    std.debug.print("{d}\\n", .{trunc});\n}\n\n// Output: 2`,
      hints: ['@truncate keeps only the low bits that fit in the target type.', '258 in binary is 100000010. u8 keeps only the low 8 bits: 00000010.', '258 % 256 = 2'],
      concepts: ['@truncate', 'bit-truncation', 'modular-arithmetic'],
    },
    {
      id: 'zig-types-16',
      title: 'Predict comptime_int Behavior',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict how comptime_int coerces to different types.',
      skeleton: `const std = @import("std");\n\nconst X = 200;\n\npub fn main() void {\n    const a: u8 = X;\n    const b: i16 = X;\n    const c: f32 = X;\n    std.debug.print("{d} {d} {d:.0}\\n", .{ a, b, c });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\nconst X = 200;\n\npub fn main() void {\n    const a: u8 = X;\n    const b: i16 = X;\n    const c: f32 = X;\n    std.debug.print("{d} {d} {d:.0}\\n", .{ a, b, c });\n}\n\n// Output: 200 200 200`,
      hints: ['comptime_int values coerce freely to any numeric type at compile time.', '200 fits in u8 (0-255), i16 (-32768 to 32767), and f32.', '200 200 200'],
      concepts: ['comptime_int', 'comptime-coercion', 'numeric-types'],
    },
    {
      id: 'zig-types-17',
      title: 'Predict @intFromFloat',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the result of converting floats to integers.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u32 = @intFromFloat(@as(f64, 3.9));\n    const b: u32 = @intFromFloat(@as(f64, 7.1));\n    const c: u32 = @intFromFloat(@as(f64, 0.999));\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u32 = @intFromFloat(@as(f64, 3.9));\n    const b: u32 = @intFromFloat(@as(f64, 7.1));\n    const c: u32 = @intFromFloat(@as(f64, 0.999));\n    std.debug.print("{d} {d} {d}\\n", .{ a, b, c });\n}\n\n// Output: 3 7 0`,
      hints: ['@intFromFloat truncates toward zero (drops the fractional part).', '3.9 becomes 3, 7.1 becomes 7, 0.999 becomes 0.', '3 7 0'],
      concepts: ['@intFromFloat', 'truncation-toward-zero', 'float-to-int'],
    },
    {
      id: 'zig-types-18',
      title: 'Refactor Repeated Casts',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the repeated @intCast calls into a helper function.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const vals = [_]u8{ 10, 20, 30, 40 };\n    var sum: u32 = 0;\n    sum += @as(u32, @intCast(vals[0]));\n    sum += @as(u32, @intCast(vals[1]));\n    sum += @as(u32, @intCast(vals[2]));\n    sum += @as(u32, @intCast(vals[3]));\n    std.debug.print("sum = {d}\\n", .{sum});\n}`,
      solution: `const std = @import("std");\n\nfn sumBytes(bytes: []const u8) u32 {\n    var sum: u32 = 0;\n    for (bytes) |b| {\n        sum += @intCast(b);\n    }\n    return sum;\n}\n\npub fn main() void {\n    const vals = [_]u8{ 10, 20, 30, 40 };\n    const sum = sumBytes(&vals);\n    std.debug.print("sum = {d}\\n", .{sum});\n}`,
      hints: ['Extract a function that takes a []const u8 and sums into a u32.', 'Use a for loop over the slice instead of manual indexing.', 'fn sumBytes(bytes: []const u8) u32 with a for loop.'],
      concepts: ['function-extraction', 'loop-over-slice', 'DRY-principle'],
    },
    {
      id: 'zig-types-19',
      title: 'Refactor @as Usage',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the verbose @as casts to use type annotations instead where possible.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = @as(u32, 100);\n    const b = @as(f64, 3.14);\n    const c = @as(bool, true);\n    const d = @as(u8, 65);\n    std.debug.print("{d} {d:.2} {} {c}\\n", .{ a, b, c, d });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u32 = 100;\n    const b: f64 = 3.14;\n    const c: bool = true;\n    const d: u8 = 65;\n    std.debug.print("{d} {d:.2} {} {c}\\n", .{ a, b, c, d });\n}`,
      hints: ['When declaring a const with a comptime-known value, a type annotation is simpler than @as.', 'const a: u32 = 100 is equivalent to const a = @as(u32, 100) but more readable.', 'Replace each @as(Type, val) with const name: Type = val.'],
      concepts: ['@as', 'type-annotation', 'idiomatic-zig', 'readability'],
    },
    {
      id: 'zig-types-20',
      title: 'Sentinel-Terminated Arrays',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function cStrLen that takes a [*:0]const u8 (null-terminated C string pointer) and returns the length (not including the sentinel).',
      skeleton: `const std = @import("std");\n\n// Write cStrLen here\n// fn cStrLen(s: [*:0]const u8) usize\n\npub fn main() void {\n    const s1: [:0]const u8 = "hello";\n    const s2: [:0]const u8 = "";\n    const s3: [:0]const u8 = "zig";\n    std.debug.print("{d} {d} {d}\\n", .{ cStrLen(s1.ptr), cStrLen(s2.ptr), cStrLen(s3.ptr) });\n    // Expected: 5 0 3\n}`,
      solution: `const std = @import("std");\n\nfn cStrLen(s: [*:0]const u8) usize {\n    var len: usize = 0;\n    while (s[len] != 0) {\n        len += 1;\n    }\n    return len;\n}\n\npub fn main() void {\n    const s1: [:0]const u8 = "hello";\n    const s2: [:0]const u8 = "";\n    const s3: [:0]const u8 = "zig";\n    std.debug.print("{d} {d} {d}\\n", .{ cStrLen(s1.ptr), cStrLen(s2.ptr), cStrLen(s3.ptr) });\n}`,
      hints: ['[*:0]const u8 is a many-item pointer with a sentinel of 0.', 'Walk through the pointer incrementing a counter until you hit the sentinel.', 'while (s[len] != 0) { len += 1; }'],
      concepts: ['sentinel-terminated', '[*:0]const u8', 'C-string', 'pointer-indexing'],
    },
  ],
};
