import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-ops',
  title: '03. Operators',
  explanation: `## Operators\n\nZig has standard operators plus unique overflow-aware and saturating variants.\n\n### Arithmetic\n\n\`\`\`zig\nconst a: u32 = 10 + 3;    // 13\nconst b: u32 = 10 - 3;    // 7\nconst c: u32 = 10 * 3;    // 30\nconst d: u32 = 10 / 3;    // 3 (integer division)\nconst e: u32 = 10 % 3;    // 1 (modulo)\n\`\`\`\n\n### Overflow Operators (+%, -%, *%)\n\nWrapping arithmetic -- wraps on overflow instead of causing safety panic:\n\n\`\`\`zig\nconst x: u8 = 255;\nconst y: u8 = x +% 1;  // wraps to 0\n\`\`\`\n\n### Saturating Operators (+|, -|, *|)\n\nClamp at the type's min/max instead of wrapping:\n\n\`\`\`zig\nconst x: u8 = 250;\nconst y: u8 = x +| 20;   // saturates at 255\nconst z: u8 = 5;\nconst w: u8 = z -| 10;   // saturates at 0\n\`\`\`\n\n### Bitwise\n\n\`\`\`zig\nconst a: u8 = 0b1010 & 0b1100;  // AND: 0b1000\nconst b: u8 = 0b1010 | 0b1100;  // OR:  0b1110\nconst c: u8 = 0b1010 ^ 0b1100;  // XOR: 0b0110\nconst d: u8 = ~@as(u8, 0b1010); // NOT: 0b11110101\nconst e: u8 = 1 << 3;           // shift left: 8\nconst f: u8 = 16 >> 2;          // shift right: 4\n\`\`\`\n\n### Comparison & Boolean\n\n\`\`\`zig\nconst eq = (a == b);   // equal\nconst ne = (a != b);   // not equal\nconst lt = (a < b);    // less than\nconst ok = (x and y);  // boolean AND\nconst any = (x or y);  // boolean OR\nconst neg = !flag;     // boolean NOT\n\`\`\`\n\n### Special Operators\n\n- \`orelse\` -- unwrap optional or use default: \`opt orelse 0\`\n- \`catch\` -- unwrap error union or handle: \`val catch 0\`\n- \`++\` -- comptime array concatenation: \`"hello" ++ " world"\`\n- \`**\` -- comptime array repetition: \`"ab" ** 3\` = \`"ababab"\``,
  exercises: [
    {
      id: 'zig-ops-1',
      title: 'Basic Arithmetic',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fill in the arithmetic operators.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u32 = 15 ___ 4;   // 19\n    const b: u32 = 15 ___ 4;   // 11\n    const c: u32 = 15 ___ 4;   // 60\n    const d: u32 = 15 ___ 4;   // 3\n    const e: u32 = 15 ___ 4;   // 3 (remainder)\n    std.debug.print("{d} {d} {d} {d} {d}\\n", .{ a, b, c, d, e });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u32 = 15 + 4;\n    const b: u32 = 15 - 4;\n    const c: u32 = 15 * 4;\n    const d: u32 = 15 / 4;\n    const e: u32 = 15 % 4;\n    std.debug.print("{d} {d} {d} {d} {d}\\n", .{ a, b, c, d, e });\n}`,
      hints: ['Standard math operators: +, -, *, /, %.', '/ performs integer division (truncates). % gives the remainder.', '+ - * / %'],
      concepts: ['addition', 'subtraction', 'multiplication', 'integer-division', 'modulo'],
    },
    {
      id: 'zig-ops-2',
      title: 'Wrapping Overflow Operators',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use wrapping operators to avoid overflow panics.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 255;\n    const b: u8 = a ___  1;    // wraps to 0\n    const c: u8 = 0;\n    const d: u8 = c ___  1;    // wraps to 255\n    const e: u8 = 200;\n    const f: u8 = e ___  2;    // wraps: 400 -> 144\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 255;\n    const b: u8 = a +% 1;\n    const c: u8 = 0;\n    const d: u8 = c -% 1;\n    const e: u8 = 200;\n    const f: u8 = e *% 2;\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}`,
      hints: ['Wrapping operators use the % suffix: +%, -%, *%.', 'They wrap around instead of panicking on overflow.', '+%, -%, *%'],
      concepts: ['wrapping-add', 'wrapping-sub', 'wrapping-mul', 'overflow'],
    },
    {
      id: 'zig-ops-3',
      title: 'Saturating Operators',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use saturating operators to clamp at type boundaries.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 250;\n    const b: u8 = a ___  20;    // clamps to 255\n    const c: u8 = 5;\n    const d: u8 = c ___  100;   // clamps to 0\n    const e: u8 = 200;\n    const f: u8 = e ___  2;     // clamps to 255 (400 > 255)\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 250;\n    const b: u8 = a +| 20;\n    const c: u8 = 5;\n    const d: u8 = c -| 100;\n    const e: u8 = 200;\n    const f: u8 = e *| 2;\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}`,
      hints: ['Saturating operators use the | suffix: +|, -|, *|.', 'They clamp at the min/max of the type instead of wrapping.', '+|, -|, *|'],
      concepts: ['saturating-add', 'saturating-sub', 'saturating-mul', 'clamping'],
    },
    {
      id: 'zig-ops-4',
      title: 'Bitwise Operators',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fill in the bitwise operators.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 0b1100;\n    const b: u8 = 0b1010;\n    const c: u8 = a ___ b;   // AND: 0b1000 = 8\n    const d: u8 = a ___ b;   // OR:  0b1110 = 14\n    const e: u8 = a ___ b;   // XOR: 0b0110 = 6\n    const f: u8 = 1 ___ 4;   // shift left: 16\n    std.debug.print("{d} {d} {d} {d}\\n", .{ c, d, e, f });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 0b1100;\n    const b: u8 = 0b1010;\n    const c: u8 = a & b;\n    const d: u8 = a | b;\n    const e: u8 = a ^ b;\n    const f: u8 = 1 << 4;\n    std.debug.print("{d} {d} {d} {d}\\n", .{ c, d, e, f });\n}`,
      hints: ['& is AND, | is OR, ^ is XOR, << is left shift.', '0b1100 & 0b1010 = 0b1000 (both bits must be 1).', '&, |, ^, <<'],
      concepts: ['bitwise-and', 'bitwise-or', 'bitwise-xor', 'shift-left'],
    },
    {
      id: 'zig-ops-5',
      title: 'Boolean Operators',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fill in the boolean operators. Zig uses and/or keywords, not && / ||.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = true;\n    const b = false;\n    const c = a ___ b;    // logical AND: false\n    const d = a ___ b;    // logical OR: true\n    const e = ___a;       // logical NOT: false\n    std.debug.print("{} {} {}\\n", .{ c, d, e });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a = true;\n    const b = false;\n    const c = a and b;\n    const d = a or b;\n    const e = !a;\n    std.debug.print("{} {} {}\\n", .{ c, d, e });\n}`,
      hints: ['Zig uses keywords `and` and `or` instead of && and ||.', 'Boolean NOT is still the ! prefix operator.', 'and, or, !'],
      concepts: ['boolean-and', 'boolean-or', 'boolean-not', 'keywords'],
    },
    {
      id: 'zig-ops-6',
      title: 'Array Concatenation and Repetition',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use ++ for comptime concatenation and ** for repetition.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const hello = "Hello" ___ " " ___ "World";\n    const dots = "." ___ 5;\n    std.debug.print("{s}{s}\\n", .{ hello, dots });\n    // Expected: Hello World.....\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const hello = "Hello" ++ " " ++ "World";\n    const dots = "." ** 5;\n    std.debug.print("{s}{s}\\n", .{ hello, dots });\n}`,
      hints: ['++ concatenates arrays/strings at compile time.', '** repeats an array/string a compile-time number of times.', '++ for concat, ** for repeat'],
      concepts: ['array-concat', 'array-repeat', 'comptime-operators'],
    },
    {
      id: 'zig-ops-7',
      title: 'Write a Power of Two Check',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function isPowerOfTwo that takes a u32 and returns true if it is a power of two. A power of two has exactly one bit set.',
      skeleton: `const std = @import("std");\n\n// Write isPowerOfTwo here\n// fn isPowerOfTwo(n: u32) bool\n\npub fn main() void {\n    std.debug.print("{} {} {} {} {}\\n", .{\n        isPowerOfTwo(1), isPowerOfTwo(2), isPowerOfTwo(3),\n        isPowerOfTwo(16), isPowerOfTwo(0),\n    });\n    // Expected: true true false true false\n}`,
      solution: `const std = @import("std");\n\nfn isPowerOfTwo(n: u32) bool {\n    return n != 0 and (n & (n - 1)) == 0;\n}\n\npub fn main() void {\n    std.debug.print("{} {} {} {} {}\\n", .{\n        isPowerOfTwo(1), isPowerOfTwo(2), isPowerOfTwo(3),\n        isPowerOfTwo(16), isPowerOfTwo(0),\n    });\n}`,
      hints: ['A power of two in binary has exactly one bit set: 1, 10, 100, 1000...', 'n & (n - 1) clears the lowest set bit. If the result is 0, only one bit was set.', 'return n != 0 and (n & (n - 1)) == 0;'],
      concepts: ['bitwise-and', 'power-of-two', 'bit-trick'],
    },
    {
      id: 'zig-ops-8',
      title: 'Write a setBit Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function setBit that takes a u32 value and a u5 bit position, and returns the value with that bit set to 1.',
      skeleton: `const std = @import("std");\n\n// Write setBit here\n// fn setBit(val: u32, pos: u5) u32\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{setBit(0, 0)});   // 1\n    std.debug.print("{d}\\n", .{setBit(0, 3)});   // 8\n    std.debug.print("{d}\\n", .{setBit(5, 1)});   // 7 (5 = 101, set bit 1 = 111 = 7)\n}`,
      solution: `const std = @import("std");\n\nfn setBit(val: u32, pos: u5) u32 {\n    return val | (@as(u32, 1) << pos);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{setBit(0, 0)});\n    std.debug.print("{d}\\n", .{setBit(0, 3)});\n    std.debug.print("{d}\\n", .{setBit(5, 1)});\n}`,
      hints: ['To set a bit, OR the value with a mask that has a 1 at the target position.', 'Create the mask by shifting 1 left by the position: @as(u32, 1) << pos.', 'return val | (@as(u32, 1) << pos);'],
      concepts: ['bitwise-or', 'shift-left', 'bit-manipulation', 'u5'],
    },
    {
      id: 'zig-ops-9',
      title: 'Write a toggleBits Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function toggleBits that takes a u8 and a u8 mask, and toggles (flips) all bits specified by the mask.',
      skeleton: `const std = @import("std");\n\n// Write toggleBits here\n// fn toggleBits(val: u8, mask: u8) u8\n\npub fn main() void {\n    std.debug.print("{b:0>8}\\n", .{toggleBits(0b1010_0101, 0b1111_0000)});\n    // Expected: 01010101\n    std.debug.print("{b:0>8}\\n", .{toggleBits(0b0000_0000, 0b1010_1010)});\n    // Expected: 10101010\n}`,
      solution: `const std = @import("std");\n\nfn toggleBits(val: u8, mask: u8) u8 {\n    return val ^ mask;\n}\n\npub fn main() void {\n    std.debug.print("{b:0>8}\\n", .{toggleBits(0b1010_0101, 0b1111_0000)});\n    std.debug.print("{b:0>8}\\n", .{toggleBits(0b0000_0000, 0b1010_1010)});\n}`,
      hints: ['XOR flips bits where the mask has 1s and leaves others unchanged.', 'The ^ operator is bitwise XOR.', 'return val ^ mask;'],
      concepts: ['bitwise-xor', 'bit-toggle', 'binary-format'],
    },
    {
      id: 'zig-ops-10',
      title: 'Write a saturatingAdd Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function saturatingAddU16 that adds two u16 values with saturation (clamping at 65535).',
      skeleton: `const std = @import("std");\n\n// Write saturatingAddU16 here\n// fn saturatingAddU16(a: u16, b: u16) u16\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{saturatingAddU16(60000, 10000)});  // 65535\n    std.debug.print("{d}\\n", .{saturatingAddU16(100, 200)});      // 300\n    std.debug.print("{d}\\n", .{saturatingAddU16(65535, 1)});      // 65535\n}`,
      solution: `const std = @import("std");\n\nfn saturatingAddU16(a: u16, b: u16) u16 {\n    return a +| b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{saturatingAddU16(60000, 10000)});\n    std.debug.print("{d}\\n", .{saturatingAddU16(100, 200)});\n    std.debug.print("{d}\\n", .{saturatingAddU16(65535, 1)});\n}`,
      hints: ['Zig has a built-in saturating add operator.', 'The +| operator clamps at the type maximum instead of wrapping.', 'return a +| b;'],
      concepts: ['saturating-add', '+|', 'u16'],
    },
    {
      id: 'zig-ops-11',
      title: 'Write a wrappingMul Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function wrappingMul that multiplies two u8 values with wrapping semantics.',
      skeleton: `const std = @import("std");\n\n// Write wrappingMul here\n// fn wrappingMul(a: u8, b: u8) u8\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{wrappingMul(16, 16)});  // 0 (256 wraps to 0)\n    std.debug.print("{d}\\n", .{wrappingMul(5, 10)});   // 50\n    std.debug.print("{d}\\n", .{wrappingMul(200, 2)});  // 144 (400 mod 256)\n}`,
      solution: `const std = @import("std");\n\nfn wrappingMul(a: u8, b: u8) u8 {\n    return a *% b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{wrappingMul(16, 16)});\n    std.debug.print("{d}\\n", .{wrappingMul(5, 10)});\n    std.debug.print("{d}\\n", .{wrappingMul(200, 2)});\n}`,
      hints: ['Zig has a wrapping multiplication operator.', 'The *% operator wraps on overflow instead of panicking.', 'return a *% b;'],
      concepts: ['wrapping-mul', '*%', 'overflow-wrapping'],
    },
    {
      id: 'zig-ops-12',
      title: 'Fix the Comparison Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the boolean operator usage. Zig uses and/or keywords, not && / ||.',
      skeleton: `const std = @import("std");\n\nfn isInRange(val: i32, lo: i32, hi: i32) bool {\n    return val >= lo && val <= hi;\n}\n\nfn isExtreme(val: i32) bool {\n    return val < -100 || val > 100;\n}\n\npub fn main() void {\n    std.debug.print("{} {}\\n", .{ isInRange(5, 0, 10), isExtreme(200) });\n}`,
      solution: `const std = @import("std");\n\nfn isInRange(val: i32, lo: i32, hi: i32) bool {\n    return val >= lo and val <= hi;\n}\n\nfn isExtreme(val: i32) bool {\n    return val < -100 or val > 100;\n}\n\npub fn main() void {\n    std.debug.print("{} {}\\n", .{ isInRange(5, 0, 10), isExtreme(200) });\n}`,
      hints: ['Zig does not use && or || for boolean logic.', 'Use the keywords `and` and `or` instead.', 'Replace && with `and` and || with `or`.'],
      concepts: ['boolean-and', 'boolean-or', 'zig-keywords'],
    },
    {
      id: 'zig-ops-13',
      title: 'Fix the Overflow Panic',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the code that panics due to overflow. Use appropriate overflow-safe operators.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var brightness: u8 = 230;\n    // BUG: Adding 50 to 230 overflows u8 (280 > 255)\n    brightness = brightness + 50;\n    std.debug.print("brightness: {d}\\n", .{brightness});\n    // Should clamp to 255\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var brightness: u8 = 230;\n    brightness = brightness +| 50;\n    std.debug.print("brightness: {d}\\n", .{brightness});\n}`,
      hints: ['Standard + panics on overflow in Zig (safety-checked).', 'For brightness, clamping at 255 makes more sense than wrapping.', 'Use +| for saturating addition.'],
      concepts: ['overflow-panic', 'saturating-add', '+|'],
    },
    {
      id: 'zig-ops-14',
      title: 'Fix the Shift Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the shift operation that uses the wrong type for the shift amount.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const val: u32 = 1;\n    const shift: u32 = 8;\n    // BUG: Shift amount must be a u5 for u32\n    const result = val << shift;\n    std.debug.print("{d}\\n", .{result});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const val: u32 = 1;\n    const shift: u5 = 8;\n    const result = val << shift;\n    std.debug.print("{d}\\n", .{result});\n}`,
      hints: ['In Zig, the shift amount must be a log2-sized type of the value type.', 'For u32, the shift amount must be u5 (log2(32) = 5 bits).', 'Change shift to u5.'],
      concepts: ['shift-amount-type', 'u5', 'log2-sizing'],
    },
    {
      id: 'zig-ops-15',
      title: 'Predict Wrapping Arithmetic',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of wrapping arithmetic.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 250;\n    const b: u8 = a +% 10;   // 260 mod 256\n    const c: u8 = 3;\n    const d: u8 = c -% 5;    // wraps unsigned\n    std.debug.print("{d} {d}\\n", .{ b, d });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 250;\n    const b: u8 = a +% 10;\n    const c: u8 = 3;\n    const d: u8 = c -% 5;\n    std.debug.print("{d} {d}\\n", .{ b, d });\n}\n\n// Output: 4 254`,
      hints: ['250 + 10 = 260, mod 256 = 4.', '3 - 5 unsigned wraps: 256 + (3 - 5) = 254.', '4 254'],
      concepts: ['wrapping-add', 'wrapping-sub', 'modular-arithmetic'],
    },
    {
      id: 'zig-ops-16',
      title: 'Predict Saturating Arithmetic',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of saturating arithmetic.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = a +| 100;\n    const c: u8 = 10;\n    const d: u8 = c -| 50;\n    const e: u8 = 128;\n    const f: u8 = e *| 3;\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = a +| 100;\n    const c: u8 = 10;\n    const d: u8 = c -| 50;\n    const e: u8 = 128;\n    const f: u8 = e *| 3;\n    std.debug.print("{d} {d} {d}\\n", .{ b, d, f });\n}\n\n// Output: 255 0 255`,
      hints: ['200 + 100 = 300, saturates to 255.', '10 - 50 would be negative for unsigned, saturates to 0.', '128 * 3 = 384, saturates to 255.'],
      concepts: ['saturating-add', 'saturating-sub', 'saturating-mul'],
    },
    {
      id: 'zig-ops-17',
      title: 'Predict Bitwise Operations',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the bitwise operation results.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 0b1111_0000;\n    const b: u8 = 0b1010_1010;\n    std.debug.print("{d} {d} {d}\\n", .{ a & b, a | b, a ^ b });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 0b1111_0000;\n    const b: u8 = 0b1010_1010;\n    std.debug.print("{d} {d} {d}\\n", .{ a & b, a | b, a ^ b });\n}\n\n// Output: 160 250 90`,
      hints: ['AND: 11110000 & 10101010 = 10100000 = 160.', 'OR: 11110000 | 10101010 = 11111010 = 250.', 'XOR: 11110000 ^ 10101010 = 01011010 = 90.'],
      concepts: ['bitwise-and', 'bitwise-or', 'bitwise-xor', 'binary-math'],
    },
    {
      id: 'zig-ops-18',
      title: 'Refactor to Use Saturating Ops',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Replace the manual clamping logic with saturating operators.',
      skeleton: `const std = @import("std");\n\nfn adjustBrightness(current: u8, delta: i16) u8 {\n    const result: i16 = @as(i16, @intCast(current)) + delta;\n    if (result > 255) return 255;\n    if (result < 0) return 0;\n    return @intCast(result);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{adjustBrightness(200, 100)});  // 255\n    std.debug.print("{d}\\n", .{adjustBrightness(10, -20)});   // 0\n    std.debug.print("{d}\\n", .{adjustBrightness(100, 50)});   // 150\n}`,
      solution: `const std = @import("std");\n\nfn adjustBrightness(current: u8, delta: i16) u8 {\n    if (delta >= 0) {\n        return current +| @as(u8, @intCast(delta));\n    } else {\n        return current -| @as(u8, @intCast(-delta));\n    }\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{adjustBrightness(200, 100)});\n    std.debug.print("{d}\\n", .{adjustBrightness(10, -20)});\n    std.debug.print("{d}\\n", .{adjustBrightness(100, 50)});\n}`,
      hints: ['Saturating operators handle the clamping automatically.', 'Split into positive (use +|) and negative (use -|) delta cases.', '+| and -| eliminate the manual bounds checking.'],
      concepts: ['saturating-operators', 'refactor', 'clamping'],
    },
    {
      id: 'zig-ops-19',
      title: 'Refactor Bit Flags to Named Constants',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Replace magic bit positions with named constants for a permission system.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var perms: u8 = 0;\n    perms |= (1 << 0);  // read\n    perms |= (1 << 1);  // write\n    perms |= (1 << 2);  // execute\n    \n    const can_read = (perms & (1 << 0)) != 0;\n    const can_write = (perms & (1 << 1)) != 0;\n    const can_exec = (perms & (1 << 2)) != 0;\n    std.debug.print("r={} w={} x={}\\n", .{ can_read, can_write, can_exec });\n}`,
      solution: `const std = @import("std");\n\nconst PERM_READ: u8 = 1 << 0;\nconst PERM_WRITE: u8 = 1 << 1;\nconst PERM_EXEC: u8 = 1 << 2;\n\npub fn main() void {\n    var perms: u8 = 0;\n    perms |= PERM_READ;\n    perms |= PERM_WRITE;\n    perms |= PERM_EXEC;\n    \n    const can_read = (perms & PERM_READ) != 0;\n    const can_write = (perms & PERM_WRITE) != 0;\n    const can_exec = (perms & PERM_EXEC) != 0;\n    std.debug.print("r={} w={} x={}\\n", .{ can_read, can_write, can_exec });\n}`,
      hints: ['Define each permission as a named constant with the bit already shifted.', 'const PERM_READ: u8 = 1 << 0; makes the code self-documenting.', 'Replace all (1 << N) with the named constants.'],
      concepts: ['named-constants', 'bit-flags', 'readability', 'bitwise-or'],
    },
    {
      id: 'zig-ops-20',
      title: 'Write a Bitfield Extract Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function extractBits that takes a u32 value, a u5 start position, and a u5 width, and returns the extracted bits as a u32.',
      skeleton: `const std = @import("std");\n\n// Write extractBits here\n// fn extractBits(val: u32, start: u5, width: u5) u32\n// Example: extractBits(0b1101_0110, 2, 4) extracts bits [5:2] = 0b0101 = 5\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{extractBits(0b1101_0110, 2, 4)});  // 5\n    std.debug.print("{d}\\n", .{extractBits(0xFF, 4, 4)});          // 15\n    std.debug.print("{d}\\n", .{extractBits(0b1010, 0, 2)});        // 2\n}`,
      solution: `const std = @import("std");\n\nfn extractBits(val: u32, start: u5, width: u5) u32 {\n    const mask: u32 = (@as(u32, 1) << width) - 1;\n    return (val >> start) & mask;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{extractBits(0b1101_0110, 2, 4)});\n    std.debug.print("{d}\\n", .{extractBits(0xFF, 4, 4)});\n    std.debug.print("{d}\\n", .{extractBits(0b1010, 0, 2)});\n}`,
      hints: ['Shift right by start to move the target bits to position 0.', 'Create a mask with width 1-bits: (1 << width) - 1.', '(val >> start) & mask extracts the bit field.'],
      concepts: ['bit-extraction', 'mask-generation', 'shift-and-mask'],
    },
  ],
};
