import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-flow',
  title: '04. Control Flow',
  explanation: `## Control Flow\n\nZig's control flow is explicit with no hidden behavior.\n\n### if / else\n\n\`if\` is an expression in Zig:\n\n\`\`\`zig\nconst abs_val = if (x < 0) -x else x;\n\`\`\`\n\n### while\n\n\`\`\`zig\nvar i: u32 = 0;\nwhile (i < 10) : (i += 1) {\n    std.debug.print("{d} ", .{i});\n}\n\`\`\`\n\nThe continue expression \`: (i += 1)\` runs after each iteration (like C's for increment).\n\n### for\n\nFor iterates over slices and ranges:\n\n\`\`\`zig\nfor (items) |item| { ... }\nfor (items, 0..) |item, index| { ... }\n\`\`\`\n\n### switch\n\nSwitch is exhaustive and is an expression:\n\n\`\`\`zig\nconst msg = switch (code) {\n    200 => "OK",\n    404 => "Not Found",\n    500...599 => "Server Error",\n    else => "Unknown",\n};\n\`\`\`\n\n### Labeled Blocks & Loops\n\n\`\`\`zig\nconst val = blk: {\n    break :blk 42;\n};\n\nouter: for (matrix) |row| {\n    for (row) |cell| {\n        if (cell == target) break :outer;\n    }\n}\n\`\`\`\n\n### unreachable\n\nMarks code that should never execute:\n\n\`\`\`zig\nelse => unreachable,\n\`\`\`\n\nIn safe mode this is a panic. In release mode it is undefined behavior (optimization hint).`,
  exercises: [
    {
      id: 'zig-flow-1',
      title: 'If as Expression',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use if as an expression to compute a value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x: i32 = -7;\n    const abs_x = ___ (x < 0) ___ else ___;\n    std.debug.print("abs: {d}\\n", .{abs_x});\n    // Expected: abs: 7\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const x: i32 = -7;\n    const abs_x = if (x < 0) -x else x;\n    std.debug.print("abs: {d}\\n", .{abs_x});\n}`,
      hints: ['In Zig, if is an expression that returns a value.', 'if (condition) value_when_true else value_when_false.', 'if (x < 0) -x else x'],
      concepts: ['if-expression', 'ternary', 'const-initialization'],
    },
    {
      id: 'zig-flow-2',
      title: 'While Loop with Continue Expression',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Complete the while loop using the continue expression syntax.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var sum: u32 = 0;\n    var i: u32 = 1;\n    ___  (i <= 10) ___ (i += 1) {\n        sum += i;\n    }\n    std.debug.print("sum 1..10 = {d}\\n", .{sum});\n    // Expected: sum 1..10 = 55\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var sum: u32 = 0;\n    var i: u32 = 1;\n    while (i <= 10) : (i += 1) {\n        sum += i;\n    }\n    std.debug.print("sum 1..10 = {d}\\n", .{sum});\n}`,
      hints: ['Zig while loops have an optional continue expression after a colon.', 'The syntax is: while (condition) : (continue_expr) { body }', 'while (i <= 10) : (i += 1)'],
      concepts: ['while-loop', 'continue-expression', 'loop-counter'],
    },
    {
      id: 'zig-flow-3',
      title: 'For Loop with Index',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Iterate over an array with both value and index.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const names = [_][]const u8{ "Alice", "Bob", "Charlie" };\n    ___ (names, ___) |name, i| {\n        std.debug.print("[{d}] {s}\\n", .{ i, name });\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const names = [_][]const u8{ "Alice", "Bob", "Charlie" };\n    for (names, 0..) |name, i| {\n        std.debug.print("[{d}] {s}\\n", .{ i, name });\n    }\n}`,
      hints: ['Zig for loops get an index by adding a counter range as a second argument.', 'The syntax is: for (array, 0..) |item, index| { ... }', 'for (names, 0..) |name, i|'],
      concepts: ['for-loop', 'index-capture', 'range-counter'],
    },
    {
      id: 'zig-flow-4',
      title: 'Switch Expression',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Complete the switch expression.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const code: u16 = 404;\n    const msg = ___ (code) {\n        200 => "OK",\n        301 => "Moved",\n        404 => "Not Found",\n        500___599 => "Server Error",\n        ___ => "Unknown",\n    };\n    std.debug.print("{d}: {s}\\n", .{ code, msg });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const code: u16 = 404;\n    const msg = switch (code) {\n        200 => "OK",\n        301 => "Moved",\n        404 => "Not Found",\n        500...599 => "Server Error",\n        else => "Unknown",\n    };\n    std.debug.print("{d}: {s}\\n", .{ code, msg });\n}`,
      hints: ['switch is an expression in Zig. Range matching uses ... (three dots).', 'Use else for the default case.', 'switch, ..., else'],
      concepts: ['switch-expression', 'range-match', 'else-branch', 'exhaustive-switch'],
    },
    {
      id: 'zig-flow-5',
      title: 'Break and Continue',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use break and continue to control loop flow.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 7, 0, 5, -2, 8 };\n    var sum: i32 = 0;\n    for (data) |val| {\n        if (val < 0) ___;     // skip negatives\n        if (val == 0) ___;    // stop at zero\n        sum += val;\n    }\n    std.debug.print("sum: {d}\\n", .{sum});\n    // Expected: sum: 10 (3 + 7)\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 7, 0, 5, -2, 8 };\n    var sum: i32 = 0;\n    for (data) |val| {\n        if (val < 0) continue;\n        if (val == 0) break;\n        sum += val;\n    }\n    std.debug.print("sum: {d}\\n", .{sum});\n}`,
      hints: ['continue skips to the next iteration. break exits the loop.', 'Negatives are skipped, and 0 terminates the loop early.', 'continue and break'],
      concepts: ['break', 'continue', 'early-exit', 'loop-control'],
    },
    {
      id: 'zig-flow-6',
      title: 'Labeled Block Expression',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use a labeled block to compute a value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const items = [_]i32{ 5, 12, 3, 8, 15 };\n    const first_big = ___: {\n        for (items) |item| {\n            if (item > 10) ___ :blk item;\n        }\n        ___ :blk @as(i32, -1);\n    };\n    std.debug.print("first big: {d}\\n", .{first_big});\n    // Expected: first big: 12\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const items = [_]i32{ 5, 12, 3, 8, 15 };\n    const first_big = blk: {\n        for (items) |item| {\n            if (item > 10) break :blk item;\n        }\n        break :blk @as(i32, -1);\n    };\n    std.debug.print("first big: {d}\\n", .{first_big});\n}`,
      hints: ['Labeled blocks use label: { ... break :label value; } to return a value.', 'break :blk item returns the item from the labeled block.', 'blk:, break :blk item, break :blk -1'],
      concepts: ['labeled-block', 'break-with-value', 'block-expression'],
    },
    {
      id: 'zig-flow-7',
      title: 'Write a FizzBuzz Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function fizzBuzz that takes a u32 and returns "FizzBuzz", "Fizz", "Buzz", or "other".',
      skeleton: `const std = @import("std");\n\n// Write fizzBuzz here\n// fn fizzBuzz(n: u32) []const u8\n\npub fn main() void {\n    const cases = [_]u32{ 15, 9, 10, 7 };\n    for (cases) |n| {\n        std.debug.print("{d}: {s}\\n", .{ n, fizzBuzz(n) });\n    }\n    // 15: FizzBuzz, 9: Fizz, 10: Buzz, 7: other\n}`,
      solution: `const std = @import("std");\n\nfn fizzBuzz(n: u32) []const u8 {\n    if (n % 15 == 0) return "FizzBuzz";\n    if (n % 3 == 0) return "Fizz";\n    if (n % 5 == 0) return "Buzz";\n    return "other";\n}\n\npub fn main() void {\n    const cases = [_]u32{ 15, 9, 10, 7 };\n    for (cases) |n| {\n        std.debug.print("{d}: {s}\\n", .{ n, fizzBuzz(n) });\n    }\n}`,
      hints: ['Check divisible by 15 first (both 3 and 5), then 3, then 5.', 'Use modulo: n % 15 == 0, n % 3 == 0, etc.', 'Return string literals directly.'],
      concepts: ['if-chain', 'modulo', 'string-return'],
    },
    {
      id: 'zig-flow-8',
      title: 'Write a Countdown Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function countdown that takes a u32 and prints numbers from n down to 1, then "Go!".',
      skeleton: `const std = @import("std");\n\n// Write countdown here\n// fn countdown(n: u32) void\n\npub fn main() void {\n    countdown(5);\n    // Expected: 5 4 3 2 1 Go!\n}`,
      solution: `const std = @import("std");\n\nfn countdown(n: u32) void {\n    var i: u32 = n;\n    while (i > 0) : (i -= 1) {\n        std.debug.print("{d} ", .{i});\n    }\n    std.debug.print("Go!\\n", .{});\n}\n\npub fn main() void {\n    countdown(5);\n}`,
      hints: ['Use a while loop counting down from n to 1.', 'while (i > 0) : (i -= 1) decrements after each iteration.', 'Print each number, then "Go!" after the loop.'],
      concepts: ['while-loop', 'decrement', 'countdown'],
    },
    {
      id: 'zig-flow-9',
      title: 'Write a sumEvens Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function sumEvens that takes a []const i32 slice and returns the sum of only the even values.',
      skeleton: `const std = @import("std");\n\n// Write sumEvens here\n// fn sumEvens(values: []const i32) i32\n\npub fn main() void {\n    const data = [_]i32{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };\n    std.debug.print("sum of evens: {d}\\n", .{sumEvens(&data)});\n    // Expected: sum of evens: 30\n}`,
      solution: `const std = @import("std");\n\nfn sumEvens(values: []const i32) i32 {\n    var sum: i32 = 0;\n    for (values) |v| {\n        if (@mod(v, 2) == 0) sum += v;\n    }\n    return sum;\n}\n\npub fn main() void {\n    const data = [_]i32{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };\n    std.debug.print("sum of evens: {d}\\n", .{sumEvens(&data)});\n}`,
      hints: ['Use a for loop with a continue to skip odd numbers.', 'Check even with @mod(v, 2) == 0 for signed integers.', 'Accumulate into a var sum: i32 = 0.'],
      concepts: ['for-loop', 'continue', '@mod', 'accumulator'],
    },
    {
      id: 'zig-flow-10',
      title: 'Write a findFirst Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function findFirst that takes a []const u32 slice and a u32 target, returning an optional ?usize index of the first occurrence.',
      skeleton: `const std = @import("std");\n\n// Write findFirst here\n// fn findFirst(items: []const u32, target: u32) ?usize\n\npub fn main() void {\n    const data = [_]u32{ 5, 10, 15, 20, 25 };\n    if (findFirst(&data, 15)) |idx| {\n        std.debug.print("found at {d}\\n", .{idx});\n    } else {\n        std.debug.print("not found\\n", .{});\n    }\n    if (findFirst(&data, 99)) |idx| {\n        std.debug.print("found at {d}\\n", .{idx});\n    } else {\n        std.debug.print("not found\\n", .{});\n    }\n    // Expected: found at 2, not found\n}`,
      solution: `const std = @import("std");\n\nfn findFirst(items: []const u32, target: u32) ?usize {\n    for (items, 0..) |item, i| {\n        if (item == target) return i;\n    }\n    return null;\n}\n\npub fn main() void {\n    const data = [_]u32{ 5, 10, 15, 20, 25 };\n    if (findFirst(&data, 15)) |idx| {\n        std.debug.print("found at {d}\\n", .{idx});\n    } else {\n        std.debug.print("not found\\n", .{});\n    }\n    if (findFirst(&data, 99)) |idx| {\n        std.debug.print("found at {d}\\n", .{idx});\n    } else {\n        std.debug.print("not found\\n", .{});\n    }\n}`,
      hints: ['Return ?usize -- an optional index. Return null if not found.', 'Use for (items, 0..) |item, i| to get both value and index.', 'Return i when found, null after the loop.'],
      concepts: ['optional-return', 'for-with-index', 'null', 'linear-search'],
    },
    {
      id: 'zig-flow-11',
      title: 'Write a Switch Categorizer',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function categorize that takes a u8 character and returns a string: "digit" for 0-9, "lower" for a-z, "upper" for A-Z, "space" for spaces/tabs/newlines, or "other".',
      skeleton: `const std = @import("std");\n\n// Write categorize here\n// fn categorize(c: u8) []const u8\n\npub fn main() void {\n    const chars = [_]u8{ 'A', 'z', '5', ' ', '#' };\n    for (chars) |c| {\n        std.debug.print("'{c}': {s}\\n", .{ c, categorize(c) });\n    }\n}`,
      solution: `const std = @import("std");\n\nfn categorize(c: u8) []const u8 {\n    return switch (c) {\n        '0'...'9' => "digit",\n        'a'...'z' => "lower",\n        'A'...'Z' => "upper",\n        ' ', '\\t', '\\n' => "space",\n        else => "other",\n    };\n}\n\npub fn main() void {\n    const chars = [_]u8{ 'A', 'z', '5', ' ', '#' };\n    for (chars) |c| {\n        std.debug.print("'{c}': {s}\\n", .{ c, categorize(c) });\n    }\n}`,
      hints: ['Use switch with range matching: \'0\'...\'9\' covers all digits.', 'Multiple values in one arm: \' \', \'\\t\', \'\\n\' => "space".', 'switch is an expression -- return the result directly.'],
      concepts: ['switch', 'range-match', 'multiple-match', 'character-classification'],
    },
    {
      id: 'zig-flow-12',
      title: 'Write a Labeled Loop Search',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function findInMatrix that searches a 2D array for a target value and returns true if found, using a labeled outer loop to break early.',
      skeleton: `const std = @import("std");\n\n// Write findInMatrix here\n// fn findInMatrix(matrix: []const []const i32, target: i32) bool\n\npub fn main() void {\n    const row1 = [_]i32{ 1, 2, 3 };\n    const row2 = [_]i32{ 4, 5, 6 };\n    const row3 = [_]i32{ 7, 8, 9 };\n    const matrix = [_][]const i32{ &row1, &row2, &row3 };\n    std.debug.print("has 5: {}\\n", .{findInMatrix(&matrix, 5)});\n    std.debug.print("has 10: {}\\n", .{findInMatrix(&matrix, 10)});\n    // Expected: has 5: true, has 10: false\n}`,
      solution: `const std = @import("std");\n\nfn findInMatrix(matrix: []const []const i32, target: i32) bool {\n    return outer: {\n        for (matrix) |row| {\n            for (row) |cell| {\n                if (cell == target) break :outer true;\n            }\n        }\n        break :outer false;\n    };\n}\n\npub fn main() void {\n    const row1 = [_]i32{ 1, 2, 3 };\n    const row2 = [_]i32{ 4, 5, 6 };\n    const row3 = [_]i32{ 7, 8, 9 };\n    const matrix = [_][]const i32{ &row1, &row2, &row3 };\n    std.debug.print("has 5: {}\\n", .{findInMatrix(&matrix, 5)});\n    std.debug.print("has 10: {}\\n", .{findInMatrix(&matrix, 10)});\n}`,
      hints: ['Use a labeled block to return a bool from nested loops.', 'break :outer true exits both loops and returns true.', 'The outer block returns false if the loops complete without finding the target.'],
      concepts: ['labeled-loop', 'nested-for', 'break-with-value', '2d-search'],
    },
    {
      id: 'zig-flow-13',
      title: 'Fix the While Loop Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the infinite loop caused by incorrect while syntax.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var i: u32 = 0;\n    var sum: u32 = 0;\n    // BUG: Missing continue expression, i never increments\n    while (i < 5) {\n        sum += i;\n    }\n    std.debug.print("sum: {d}\\n", .{sum});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var i: u32 = 0;\n    var sum: u32 = 0;\n    while (i < 5) : (i += 1) {\n        sum += i;\n    }\n    std.debug.print("sum: {d}\\n", .{sum});\n}`,
      hints: ['The loop never increments i, so the condition is always true.', 'Add a continue expression: while (i < 5) : (i += 1).', ': (i += 1) after the condition.'],
      concepts: ['while-loop', 'continue-expression', 'infinite-loop-bug'],
    },
    {
      id: 'zig-flow-14',
      title: 'Fix the Switch Exhaustiveness Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the non-exhaustive switch that fails to compile.',
      skeleton: `const std = @import("std");\n\nconst Direction = enum { north, south, east, west };\n\nfn describe(dir: Direction) []const u8 {\n    return switch (dir) {\n        .north => "up",\n        .south => "down",\n        // BUG: Missing east and west -- switch must be exhaustive\n    };\n}\n\npub fn main() void {\n    std.debug.print("{s}\\n", .{describe(.north)});\n}`,
      solution: `const std = @import("std");\n\nconst Direction = enum { north, south, east, west };\n\nfn describe(dir: Direction) []const u8 {\n    return switch (dir) {\n        .north => "up",\n        .south => "down",\n        .east => "right",\n        .west => "left",\n    };\n}\n\npub fn main() void {\n    std.debug.print("{s}\\n", .{describe(.north)});\n}`,
      hints: ['Zig switch on enums must cover all variants.', 'Add arms for .east and .west with appropriate return values.', '.east => "right", .west => "left"'],
      concepts: ['exhaustive-switch', 'enum-switch', 'compile-error'],
    },
    {
      id: 'zig-flow-15',
      title: 'Fix the For Loop Mutation Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the code that tries to mutate loop capture values (which are immutable).',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var data = [_]u32{ 1, 2, 3, 4, 5 };\n    // BUG: Loop captures are immutable copies\n    for (data) |item| {\n        item *= 2;\n    }\n    for (data) |item| {\n        std.debug.print("{d} ", .{item});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var data = [_]u32{ 1, 2, 3, 4, 5 };\n    for (&data) |*item| {\n        item.* *= 2;\n    }\n    for (data) |item| {\n        std.debug.print("{d} ", .{item});\n    }\n}`,
      hints: ['Loop captures are immutable copies. You need pointer access to mutate.', 'Use for (&data) |*item| to get mutable pointers to elements.', 'Dereference with item.* to modify: item.* *= 2.'],
      concepts: ['pointer-capture', 'mutable-iteration', 'dereference'],
    },
    {
      id: 'zig-flow-16',
      title: 'Predict For Loop Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the output of this for loop.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const vals = [_]u32{ 10, 20, 30 };\n    var total: u32 = 0;\n    for (vals, 0..) |v, i| {\n        total += v * @as(u32, @intCast(i));\n    }\n    std.debug.print("{d}\\n", .{total});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const vals = [_]u32{ 10, 20, 30 };\n    var total: u32 = 0;\n    for (vals, 0..) |v, i| {\n        total += v * @as(u32, @intCast(i));\n    }\n    std.debug.print("{d}\\n", .{total});\n}\n\n// Output: 80`,
      hints: ['i=0: 10*0=0. i=1: 20*1=20. i=2: 30*2=60.', 'total = 0 + 20 + 60 = 80.', '80'],
      concepts: ['for-with-index', 'multiplication', 'accumulator'],
    },
    {
      id: 'zig-flow-17',
      title: 'Predict Switch Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what the switch expression evaluates to.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const scores = [_]u32{ 95, 72, 88, 45, 100 };\n    var grades: [5]u8 = undefined;\n    for (scores, 0..) |s, i| {\n        grades[i] = switch (s / 10) {\n            10, 9 => 'A',\n            8 => 'B',\n            7 => 'C',\n            else => 'F',\n        };\n    }\n    std.debug.print("{s}\\n", .{&grades});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const scores = [_]u32{ 95, 72, 88, 45, 100 };\n    var grades: [5]u8 = undefined;\n    for (scores, 0..) |s, i| {\n        grades[i] = switch (s / 10) {\n            10, 9 => 'A',\n            8 => 'B',\n            7 => 'C',\n            else => 'F',\n        };\n    }\n    std.debug.print("{s}\\n", .{&grades});\n}\n\n// Output: ACBFA`,
      hints: ['95/10=9->A, 72/10=7->C, 88/10=8->B, 45/10=4->F, 100/10=10->A.', 'Integer division truncates. 10 and 9 both map to A.', 'ACBFA'],
      concepts: ['switch-expression', 'integer-division', 'array-mutation'],
    },
    {
      id: 'zig-flow-18',
      title: 'Predict Labeled Block',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the result of the labeled block expression.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 4, -2, 7 };\n    const result = blk: {\n        var sum: i32 = 0;\n        for (data) |v| {\n            sum += v;\n            if (sum > 5) break :blk sum;\n        }\n        break :blk sum;\n    };\n    std.debug.print("{d}\\n", .{result});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 4, -2, 7 };\n    const result = blk: {\n        var sum: i32 = 0;\n        for (data) |v| {\n            sum += v;\n            if (sum > 5) break :blk sum;\n        }\n        break :blk sum;\n    };\n    std.debug.print("{d}\\n", .{result});\n}\n\n// Output: 11`,
      hints: ['sum: 3, 2, 6 (>5, breaks). Wait -- 6 > 5 so it breaks after adding 4.', 'Actually: 0+3=3, 3+(-1)=2, 2+4=6. 6 > 5, so break with 6.', 'Wait, let me recompute: 0+3=3, 3-1=2, 2+4=6 > 5, break :blk 6. The answer is 6.'],
      concepts: ['labeled-block', 'break-with-value', 'running-sum'],
    },
    {
      id: 'zig-flow-19',
      title: 'Refactor If Chain to Switch',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the if/else chain into a switch expression.',
      skeleton: `const std = @import("std");\n\nfn httpStatus(code: u16) []const u8 {\n    if (code == 200) return "OK";\n    if (code == 201) return "Created";\n    if (code == 301) return "Moved";\n    if (code == 400) return "Bad Request";\n    if (code == 404) return "Not Found";\n    if (code >= 500 and code <= 599) return "Server Error";\n    return "Unknown";\n}\n\npub fn main() void {\n    const codes = [_]u16{ 200, 404, 503, 999 };\n    for (codes) |c| {\n        std.debug.print("{d}: {s}\\n", .{ c, httpStatus(c) });\n    }\n}`,
      solution: `const std = @import("std");\n\nfn httpStatus(code: u16) []const u8 {\n    return switch (code) {\n        200 => "OK",\n        201 => "Created",\n        301 => "Moved",\n        400 => "Bad Request",\n        404 => "Not Found",\n        500...599 => "Server Error",\n        else => "Unknown",\n    };\n}\n\npub fn main() void {\n    const codes = [_]u16{ 200, 404, 503, 999 };\n    for (codes) |c| {\n        std.debug.print("{d}: {s}\\n", .{ c, httpStatus(c) });\n    }\n}`,
      hints: ['switch expressions are more idiomatic for mapping values in Zig.', 'Use range matching 500...599 for the server error range.', 'Each arm returns a string: 200 => "OK", etc.'],
      concepts: ['switch-expression', 'refactor', 'range-match', 'idiomatic-zig'],
    },
    {
      id: 'zig-flow-20',
      title: 'Refactor Nested Loops',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the flag-based nested loop exit into a labeled loop with break.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const grid = [3][3]u32{\n        .{ 1, 2, 3 },\n        .{ 4, 5, 6 },\n        .{ 7, 8, 9 },\n    };\n    const target: u32 = 5;\n    var found = false;\n    var found_row: usize = 0;\n    var found_col: usize = 0;\n    for (grid, 0..) |row, r| {\n        if (found) break;\n        for (row, 0..) |cell, c| {\n            if (cell == target) {\n                found = true;\n                found_row = r;\n                found_col = c;\n                break;\n            }\n        }\n    }\n    if (found) {\n        std.debug.print("found at [{d}][{d}]\\n", .{ found_row, found_col });\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const grid = [3][3]u32{\n        .{ 1, 2, 3 },\n        .{ 4, 5, 6 },\n        .{ 7, 8, 9 },\n    };\n    const target: u32 = 5;\n    const result = search: {\n        for (grid, 0..) |row, r| {\n            for (row, 0..) |cell, c| {\n                if (cell == target) break :search .{ r, c };\n            }\n        }\n        break :search null;\n    };\n    if (result) |pos| {\n        std.debug.print("found at [{d}][{d}]\\n", .{ pos[0], pos[1] });\n    }\n}`,
      hints: ['Use a labeled block to return coordinates or null from nested loops.', 'break :search .{ r, c } exits both loops with the position.', 'The result is an optional that can be unwrapped with if.'],
      concepts: ['labeled-loop', 'break-with-value', 'optional', 'nested-loop-refactor'],
    },
  ],
};
