import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-fn',
  title: '05. Functions',
  explanation: `## Functions in Zig\n\nZig functions are first-class and type-safe. Every function has explicit parameter types and a return type.\n\n### Basic Syntax\n\n\`\`\`zig\nfn add(a: i32, b: i32) i32 {\n    return a + b;\n}\n\n// Void return type\nfn greet(name: []const u8) void {\n    std.debug.print("Hello, {s}\\n", .{name});\n}\n\`\`\`\n\n### inline fn\n\n\`\`\`zig\ninline fn square(x: i32) i32 {\n    return x * x;\n}\n\`\`\`\n\n### anytype Parameters\n\n\`\`\`zig\nfn printAny(value: anytype) void {\n    std.debug.print("{}\\n", .{value});\n}\n// Works with any type: printAny(42), printAny(3.14)\n\`\`\`\n\n### Function Pointers\n\n\`\`\`zig\nconst fn_ptr: *const fn (i32) i32 = &square;\nconst result = fn_ptr(5);   // 25\n\`\`\`\n\n### Multiple Returns via Structs\n\n\`\`\`zig\nfn divmod(a: u32, b: u32) struct { q: u32, r: u32 } {\n    return .{ .q = a / b, .r = a % b };\n}\nconst result = divmod(17, 5);  // .q = 3, .r = 2\n\`\`\``,
  exercises: [
    {
      id: 'zig-fn-1',
      title: 'Basic Function Declaration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write the return type and return statement for a multiply function.',
      skeleton: `const std = @import("std");\n\nfn multiply(a: i32, b: i32) ___ {\n    ___ a * b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{multiply(6, 7)});\n}`,
      solution: `const std = @import("std");\n\nfn multiply(a: i32, b: i32) i32 {\n    return a * b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{multiply(6, 7)});\n}`,
      hints: ['The return type comes after the parameter list.', 'Use return to return a value.', 'i32 return and return a * b;'],
      concepts: ['fn', 'return-type', 'return'],
    },
    {
      id: 'zig-fn-2',
      title: 'void Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Complete a function that prints a greeting without returning a value.',
      skeleton: `const std = @import("std");\n\nfn greet(name: []const u8) ___ {\n    std.debug.print("Hello, {s}!\\n", .{name});\n}\n\npub fn main() void {\n    greet("Zig");\n}`,
      solution: `const std = @import("std");\n\nfn greet(name: []const u8) void {\n    std.debug.print("Hello, {s}!\\n", .{name});\n}\n\npub fn main() void {\n    greet("Zig");\n}`,
      hints: ['Use void when a function returns nothing.', 'void functions do not use return with a value.', 'void'],
      concepts: ['void', 'function-declaration'],
    },
    {
      id: 'zig-fn-3',
      title: 'inline Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare an inline function for a performance-critical small computation.',
      skeleton: `const std = @import("std");\n\n___ fn cube(x: i32) i32 {\n    return x * x * x;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{cube(4)});\n}`,
      solution: `const std = @import("std");\n\ninline fn cube(x: i32) i32 {\n    return x * x * x;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{cube(4)});\n}`,
      hints: ['inline suggests the compiler inlines the function at call sites.', 'Place inline before fn.', 'inline fn'],
      concepts: ['inline', 'fn'],
    },
    {
      id: 'zig-fn-4',
      title: 'Multiple Return via Struct',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Complete the function that returns both quotient and remainder.',
      skeleton: `const std = @import("std");\n\nfn divmod(a: u32, b: u32) struct { q: u32, r: u32 } {\n    return .___ .q = a / b, .r = a % b ___;\n}\n\npub fn main() void {\n    const result = divmod(17, 5);\n    std.debug.print("q={d} r={d}\\n", .{ result.q, result.r });\n}`,
      solution: `const std = @import("std");\n\nfn divmod(a: u32, b: u32) struct { q: u32, r: u32 } {\n    return .{ .q = a / b, .r = a % b };\n}\n\npub fn main() void {\n    const result = divmod(17, 5);\n    std.debug.print("q={d} r={d}\\n", .{ result.q, result.r });\n}`,
      hints: ['Anonymous struct literals use .{ .field = value } syntax.', 'Return both fields at once.', '.{ .q = a / b, .r = a % b }'],
      concepts: ['multiple-return', 'anonymous-struct', 'struct-literal'],
    },
    {
      id: 'zig-fn-5',
      title: 'anytype Parameter',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that prints any value using anytype.',
      skeleton: `const std = @import("std");\n\nfn display(value: ___) void {\n    std.debug.print("{}\\n", .{value});\n}\n\npub fn main() void {\n    display(42);\n    display(3.14);\n    display(true);\n}`,
      solution: `const std = @import("std");\n\nfn display(value: anytype) void {\n    std.debug.print("{}\\n", .{value});\n}\n\npub fn main() void {\n    display(42);\n    display(3.14);\n    display(true);\n}`,
      hints: ['anytype is a comptime type parameter that accepts any type.', 'The function becomes generic over the type at compile time.', 'anytype'],
      concepts: ['anytype', 'generic-function', 'comptime'],
    },
    {
      id: 'zig-fn-6',
      title: 'Function Pointer',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Declare a function pointer type and call it.',
      skeleton: `const std = @import("std");\n\nfn double(x: i32) i32 { return x * 2; }\n\npub fn main() void {\n    const fn_ptr: ___fn (i32) i32 = &double;\n    std.debug.print("{d}\\n", .{fn_ptr(21)});\n}`,
      solution: `const std = @import("std");\n\nfn double(x: i32) i32 { return x * 2; }\n\npub fn main() void {\n    const fn_ptr: *const fn (i32) i32 = &double;\n    std.debug.print("{d}\\n", .{fn_ptr(21)});\n}`,
      hints: ['Function pointers in Zig are *const fn(params) RetType.', '*const means the pointer itself is constant.', '*const fn (i32) i32'],
      concepts: ['function-pointer', '*const-fn'],
    },
    {
      id: 'zig-fn-7',
      title: 'Write a Higher-Order Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function apply that takes a function pointer and a value, and returns the result of calling fn(value).',
      skeleton: `const std = @import("std");\n\n// Write apply here\n// fn apply(func: *const fn(i32) i32, x: i32) i32\n\nfn negate(x: i32) i32 { return -x; }\nfn triple(x: i32) i32 { return x * 3; }\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{apply(&negate, 10)});  // -10\n    std.debug.print("{d}\\n", .{apply(&triple, 7)});   // 21\n}`,
      solution: `const std = @import("std");\n\nfn apply(func: *const fn (i32) i32, x: i32) i32 {\n    return func(x);\n}\n\nfn negate(x: i32) i32 { return -x; }\nfn triple(x: i32) i32 { return x * 3; }\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{apply(&negate, 10)});\n    std.debug.print("{d}\\n", .{apply(&triple, 7)});\n}`,
      hints: ['The parameter type for a function pointer is *const fn(i32) i32.', 'Call the function pointer with func(x).', 'Pass functions as &functionName.'],
      concepts: ['function-pointer', 'higher-order', '*const-fn'],
    },
    {
      id: 'zig-fn-8',
      title: 'Write a Generic Min Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a generic function minVal using anytype that returns the smaller of two values.',
      skeleton: `const std = @import("std");\n\n// Write minVal using anytype\n// fn minVal(a: anytype, b: anytype) @TypeOf(a)\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{minVal(10, 20)});  // 10\n    std.debug.print("{d}\\n", .{minVal(3.14, 2.71)});  // 2.71\n}`,
      solution: `const std = @import("std");\n\nfn minVal(a: anytype, b: anytype) @TypeOf(a) {\n    return if (a < b) a else b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{minVal(10, 20)});\n    std.debug.print("{d:.2}\\n", .{minVal(3.14, 2.71)});\n}`,
      hints: ['Use @TypeOf(a) as the return type for generic functions.', 'if (a < b) a else b works for any numeric type.', 'anytype makes the function work for any comparable type.'],
      concepts: ['anytype', '@TypeOf', 'generic-function'],
    },
    {
      id: 'zig-fn-9',
      title: 'Write a Recursive Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a recursive function factorial that computes n! for u32 input.',
      skeleton: `const std = @import("std");\n\n// Write factorial here\n// fn factorial(n: u32) u64\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{factorial(0)});   // 1\n    std.debug.print("{d}\\n", .{factorial(5)});   // 120\n    std.debug.print("{d}\\n", .{factorial(10)});  // 3628800\n}`,
      solution: `const std = @import("std");\n\nfn factorial(n: u32) u64 {\n    if (n <= 1) return 1;\n    return @as(u64, n) * factorial(n - 1);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{factorial(0)});\n    std.debug.print("{d}\\n", .{factorial(5)});\n    std.debug.print("{d}\\n", .{factorial(10)});\n}`,
      hints: ['Base case: if n <= 1, return 1.', 'Recursive case: n * factorial(n - 1).', 'Use u64 for the return type to hold large values.'],
      concepts: ['recursion', 'factorial', 'u64'],
    },
    {
      id: 'zig-fn-10',
      title: 'Write a comptime Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function that generates a fixed-size array of the first N Fibonacci numbers.',
      skeleton: `const std = @import("std");\n\n// Write fibArray(comptime n: usize) [n]u64\n\npub fn main() void {\n    const fibs = fibArray(8);\n    std.debug.print("{any}\\n", .{fibs});\n    // Expected: { 0, 1, 1, 2, 3, 5, 8, 13 }\n}`,
      solution: `const std = @import("std");\n\nfn fibArray(comptime n: usize) [n]u64 {\n    var arr: [n]u64 = undefined;\n    if (n > 0) arr[0] = 0;\n    if (n > 1) arr[1] = 1;\n    var i: usize = 2;\n    while (i < n) : (i += 1) {\n        arr[i] = arr[i - 1] + arr[i - 2];\n    }\n    return arr;\n}\n\npub fn main() void {\n    const fibs = fibArray(8);\n    std.debug.print("{any}\\n", .{fibs});\n}`,
      hints: ['comptime n means the array size is known at compile time.', 'Return type [n]u64 uses the comptime n.', 'Initialize arr[0] = 0, arr[1] = 1, then fill the rest.'],
      concepts: ['comptime', 'array-generation', 'fibonacci'],
    },
    {
      id: 'zig-fn-11',
      title: 'Write a Map Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function mapSlice that applies a function to each element of a slice and returns the modified slice.',
      skeleton: `const std = @import("std");\n\n// Write mapSlice(slice: []i32, func: *const fn(i32) i32) void\n// Modifies slice in-place\n\nfn square(x: i32) i32 { return x * x; }\n\npub fn main() void {\n    var data = [_]i32{ 1, 2, 3, 4, 5 };\n    mapSlice(&data, &square);\n    std.debug.print("{any}\\n", .{data});\n    // Expected: { 1, 4, 9, 16, 25 }\n}`,
      solution: `const std = @import("std");\n\nfn mapSlice(slice: []i32, func: *const fn (i32) i32) void {\n    for (slice) |*elem| {\n        elem.* = func(elem.*);\n    }\n}\n\nfn square(x: i32) i32 { return x * x; }\n\npub fn main() void {\n    var data = [_]i32{ 1, 2, 3, 4, 5 };\n    mapSlice(&data, &square);\n    std.debug.print("{any}\\n", .{data});\n}`,
      hints: ['Use for (slice) |*elem| for mutable pointer access.', 'elem.* dereferences to get/set the value.', 'func(elem.*) calls the function on the value.'],
      concepts: ['function-pointer', 'map', 'mutable-slice', 'pointer-capture'],
    },
    {
      id: 'zig-fn-12',
      title: 'Fix Missing Return Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the function that is missing its return type annotation.',
      skeleton: `const std = @import("std");\n\nfn add(a: i32, b: i32) {\n    return a + b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{add(3, 4)});\n}`,
      solution: `const std = @import("std");\n\nfn add(a: i32, b: i32) i32 {\n    return a + b;\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{add(3, 4)});\n}`,
      hints: ['Zig requires explicit return types.', 'Add the return type between ) and {.', 'i32 is the return type here.'],
      concepts: ['return-type', 'function-declaration'],
    },
    {
      id: 'zig-fn-13',
      title: 'Fix Wrong anytype Return',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the anytype function that uses the wrong return type.',
      skeleton: `const std = @import("std");\n\nfn identity(x: anytype) anytype {\n    return x;\n}\n\npub fn main() void {\n    std.debug.print("{}\\n", .{identity(42)});\n}`,
      solution: `const std = @import("std");\n\nfn identity(x: anytype) @TypeOf(x) {\n    return x;\n}\n\npub fn main() void {\n    std.debug.print("{}\\n", .{identity(42)});\n}`,
      hints: ['anytype as a return type is not valid -- you must use @TypeOf.', '@TypeOf(x) gives the actual type of the parameter.', '@TypeOf(x)'],
      concepts: ['anytype', '@TypeOf', 'return-type'],
    },
    {
      id: 'zig-fn-14',
      title: 'Predict Function Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the output of this function chain.',
      skeleton: `const std = @import("std");\n\nfn double(x: i32) i32 { return x * 2; }\nfn addOne(x: i32) i32 { return x + 1; }\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{addOne(double(5))});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\nfn double(x: i32) i32 { return x * 2; }\nfn addOne(x: i32) i32 { return x + 1; }\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{addOne(double(5))});\n}\n\n// Output: 11`,
      hints: ['double(5) = 10.', 'addOne(10) = 11.', '11'],
      concepts: ['function-composition', 'evaluation-order'],
    },
    {
      id: 'zig-fn-15',
      title: 'Predict Recursive Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of this recursive function.',
      skeleton: `const std = @import("std");\n\nfn sum(n: u32) u32 {\n    if (n == 0) return 0;\n    return n + sum(n - 1);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{sum(5)});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\nfn sum(n: u32) u32 {\n    if (n == 0) return 0;\n    return n + sum(n - 1);\n}\n\npub fn main() void {\n    std.debug.print("{d}\\n", .{sum(5)});\n}\n\n// Output: 15`,
      hints: ['sum(5) = 5 + sum(4) = 5 + 4 + 3 + 2 + 1 + 0 = 15.', 'This is the sum of 1..5.', '15'],
      concepts: ['recursion', 'sum', 'base-case'],
    },
    {
      id: 'zig-fn-16',
      title: 'Predict Multiple Return',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the fields of the returned struct.',
      skeleton: `const std = @import("std");\n\nfn minmax(a: i32, b: i32) struct { min: i32, max: i32 } {\n    return if (a < b) .{ .min = a, .max = b } else .{ .min = b, .max = a };\n}\n\npub fn main() void {\n    const r = minmax(7, 3);\n    std.debug.print("{d} {d}\\n", .{ r.min, r.max });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\nfn minmax(a: i32, b: i32) struct { min: i32, max: i32 } {\n    return if (a < b) .{ .min = a, .max = b } else .{ .min = b, .max = a };\n}\n\npub fn main() void {\n    const r = minmax(7, 3);\n    std.debug.print("{d} {d}\\n", .{ r.min, r.max });\n}\n\n// Output: 3 7`,
      hints: ['minmax(7, 3): 7 < 3 is false, so min=3, max=7.', 'r.min=3, r.max=7.', '3 7'],
      concepts: ['multiple-return', 'struct', 'if-expression'],
    },
    {
      id: 'zig-fn-17',
      title: 'Refactor to Generic Function',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor two separate typed functions into one generic anytype function.',
      skeleton: `const std = @import("std");\n\nfn absI32(x: i32) i32 {\n    return if (x < 0) -x else x;\n}\n\nfn absF64(x: f64) f64 {\n    return if (x < 0) -x else x;\n}\n\npub fn main() void {\n    std.debug.print("{d} {d:.2}\\n", .{ absI32(-5), absF64(-3.14) });\n}`,
      solution: `const std = @import("std");\n\nfn abs(x: anytype) @TypeOf(x) {\n    return if (x < 0) -x else x;\n}\n\npub fn main() void {\n    std.debug.print("{d} {d:.2}\\n", .{ abs(@as(i32, -5)), abs(@as(f64, -3.14)) });\n}`,
      hints: ['Replace both functions with a single abs using anytype.', 'Use @TypeOf(x) as the return type.', 'The if expression works for any numeric type.'],
      concepts: ['anytype', 'generic-function', 'refactoring'],
    },
    {
      id: 'zig-fn-18',
      title: 'Write a Function Table',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write code that creates an array of function pointers and calls each in a loop.',
      skeleton: `const std = @import("std");\n\n// Write: create array of 3 function pointers and apply each to 10\n// Functions: double, triple, square`,
      solution: `const std = @import("std");\n\nfn double(x: i32) i32 { return x * 2; }\nfn triple(x: i32) i32 { return x * 3; }\nfn square(x: i32) i32 { return x * x; }\n\npub fn main() void {\n    const fns = [_]*const fn (i32) i32{ &double, &triple, &square };\n    for (fns) |f| {\n        std.debug.print("{d}\\n", .{f(10)});\n    }\n    // 20, 30, 100\n}`,
      hints: ['Array of function pointers: [_]*const fn(i32) i32.', 'Each entry is &functionName.', 'Call with f(10) in the loop.'],
      concepts: ['function-pointer', 'array', 'dispatch-table'],
    },
    {
      id: 'zig-fn-19',
      title: 'Refactor to comptime Function',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor a runtime power function to a comptime version that generates a compile-time constant.',
      skeleton: `const std = @import("std");\n\nfn power(base: u64, exp: u32) u64 {\n    var result: u64 = 1;\n    var i: u32 = 0;\n    while (i < exp) : (i += 1) {\n        result *= base;\n    }\n    return result;\n}\n\npub fn main() void {\n    const p = power(2, 32);\n    std.debug.print("{d}\\n", .{p});\n}`,
      solution: `const std = @import("std");\n\nfn power(comptime base: u64, comptime exp: u32) u64 {\n    comptime var result: u64 = 1;\n    comptime var i: u32 = 0;\n    inline while (i < exp) : (i += 1) {\n        result *= base;\n    }\n    return result;\n}\n\npub fn main() void {\n    const p = comptime power(2, 32);\n    std.debug.print("{d}\\n", .{p});\n}`,
      hints: ['Mark parameters as comptime to enable compile-time evaluation.', 'Use comptime var for loop variables.', 'inline while runs at compile time when variables are comptime.'],
      concepts: ['comptime', 'comptime-function', 'inline-while'],
    },
    {
      id: 'zig-fn-20',
      title: 'Write a Reduce Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a reduce function that takes a slice, initial value, and function pointer, applying the function cumulatively.',
      skeleton: `const std = @import("std");\n\n// Write reduce(slice: []const i32, init: i32, func: *const fn(i32, i32) i32) i32\n\nfn add(a: i32, b: i32) i32 { return a + b; }\nfn multiply(a: i32, b: i32) i32 { return a * b; }\n\npub fn main() void {\n    const data = [_]i32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{reduce(&data, 0, &add)});       // 15\n    std.debug.print("{d}\\n", .{reduce(&data, 1, &multiply)});  // 120\n}`,
      solution: `const std = @import("std");\n\nfn reduce(slice: []const i32, init: i32, func: *const fn (i32, i32) i32) i32 {\n    var acc = init;\n    for (slice) |elem| {\n        acc = func(acc, elem);\n    }\n    return acc;\n}\n\nfn add(a: i32, b: i32) i32 { return a + b; }\nfn multiply(a: i32, b: i32) i32 { return a * b; }\n\npub fn main() void {\n    const data = [_]i32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{reduce(&data, 0, &add)});\n    std.debug.print("{d}\\n", .{reduce(&data, 1, &multiply)});\n}`,
      hints: ['Start with acc = init and update acc = func(acc, elem).', 'The function pointer type is *const fn(i32, i32) i32.', 'Loop with for (slice) |elem|.'],
      concepts: ['reduce', 'function-pointer', 'accumulator', 'higher-order'],
    },
  ],
};
