import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-arr',
  title: '06. Arrays',
  explanation: `## Arrays in Zig\n\nArrays in Zig have a fixed size known at compile time. The type is [N]T.\n\n### Declarations\n\n\`\`\`zig\nconst nums = [5]u32{ 1, 2, 3, 4, 5 };\nconst inferred = [_]u32{ 1, 2, 3, 4, 5 };  // size inferred\nvar mutable: [3]i32 = .{ 10, 20, 30 };\n\`\`\`\n\n### Indexing and Length\n\n\`\`\`zig\nconst first = nums[0];       // 1\nconst last = nums[4];        // 5\nconst len = nums.len;        // 5 (compile-time constant)\n\`\`\`\n\n### Iteration\n\n\`\`\`zig\nfor (nums) |n| {\n    std.debug.print("{d} ", .{n});\n}\n\nfor (nums, 0..) |n, i| {\n    std.debug.print("[{d}]={d} ", .{ i, n });\n}\n\`\`\`\n\n### Concatenation\n\n\`\`\`zig\nconst a = [_]u32{ 1, 2, 3 };\nconst b = [_]u32{ 4, 5, 6 };\nconst c = a ++ b;  // [6]u32{ 1,2,3,4,5,6 } -- comptime only\n\`\`\`\n\n### Multi-dimensional\n\n\`\`\`zig\nconst matrix = [2][3]i32{\n    .{ 1, 2, 3 },\n    .{ 4, 5, 6 },\n};\nconst val = matrix[1][2];   // 6\n\`\`\``,
  exercises: [
    {
      id: 'zig-arr-1',
      title: 'Declare an Array',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare a fixed-size array of 5 integers using type inference.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const nums = [___]u32{ 10, 20, 30, 40, 50 };\n    std.debug.print("len={d}\\n", .{nums.len});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const nums = [_]u32{ 10, 20, 30, 40, 50 };\n    std.debug.print("len={d}\\n", .{nums.len});\n}`,
      hints: ['[_] lets Zig infer the array size from the literal.', 'Alternatively write [5]u32.', '[_]'],
      concepts: ['array', 'type-inference', 'array-literal'],
    },
    {
      id: 'zig-arr-2',
      title: 'Access Array Elements',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Access the first and last elements of an array.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 5, 10, 15, 20, 25 };\n    const first = data[___];\n    const last = data[data.len - ___];\n    std.debug.print("{d} {d}\\n", .{ first, last });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const data = [_]i32{ 5, 10, 15, 20, 25 };\n    const first = data[0];\n    const last = data[data.len - 1];\n    std.debug.print("{d} {d}\\n", .{ first, last });\n}`,
      hints: ['Arrays are zero-indexed.', 'Last element is at index data.len - 1.', '0 and 1'],
      concepts: ['array-index', 'zero-indexing', 'array-len'],
    },
    {
      id: 'zig-arr-3',
      title: 'Iterate with for',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Iterate over an array and sum its elements.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const vals = [_]u32{ 3, 1, 4, 1, 5, 9, 2, 6 };\n    var sum: u32 = 0;\n    for (___) |v| {\n        sum += v;\n    }\n    std.debug.print("sum={d}\\n", .{sum});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const vals = [_]u32{ 3, 1, 4, 1, 5, 9, 2, 6 };\n    var sum: u32 = 0;\n    for (vals) |v| {\n        sum += v;\n    }\n    std.debug.print("sum={d}\\n", .{sum});\n}`,
      hints: ['for (array) |element| iterates over each element.', 'The capture |v| gets each value.', 'vals'],
      concepts: ['for-loop', 'array-iteration', 'accumulator'],
    },
    {
      id: 'zig-arr-4',
      title: 'Iterate with Index',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Iterate with both value and index.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const colors = [_][]const u8{ "red", "green", "blue" };\n    for (colors, ___) |c, i| {\n        std.debug.print("[{d}]={s}\\n", .{ i, c });\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const colors = [_][]const u8{ "red", "green", "blue" };\n    for (colors, 0..) |c, i| {\n        std.debug.print("[{d}]={s}\\n", .{ i, c });\n    }\n}`,
      hints: ['0.. is an infinite counter range paired with the array.', 'for (array, 0..) |item, index| gives both.', '0..'],
      concepts: ['for-with-index', '0..', 'indexed-iteration'],
    },
    {
      id: 'zig-arr-5',
      title: 'Mutable Array Element',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Modify elements of a mutable array using pointer captures.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var nums = [_]i32{ 1, 2, 3, 4, 5 };\n    for (___) |*n| {\n        n.* *= 2;\n    }\n    std.debug.print("{any}\\n", .{nums});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var nums = [_]i32{ 1, 2, 3, 4, 5 };\n    for (&nums) |*n| {\n        n.* *= 2;\n    }\n    std.debug.print("{any}\\n", .{nums});\n}`,
      hints: ['Use &nums to get a mutable reference.', '|*n| captures a pointer to each element.', 'n.* dereferences to access the value.'],
      concepts: ['mutable-array', 'pointer-capture', 'dereference'],
    },
    {
      id: 'zig-arr-6',
      title: 'Array Concatenation',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Concatenate two arrays at compile time using ++.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = [_]u8{ 1, 2, 3 };\n    const b = [_]u8{ 4, 5, 6 };\n    const c = a ___ b;\n    std.debug.print("len={d} first={d} last={d}\\n", .{ c.len, c[0], c[5] });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a = [_]u8{ 1, 2, 3 };\n    const b = [_]u8{ 4, 5, 6 };\n    const c = a ++ b;\n    std.debug.print("len={d} first={d} last={d}\\n", .{ c.len, c[0], c[5] });\n}`,
      hints: ['++ concatenates arrays at compile time.', 'Both arrays must be comptime-known.', '++'],
      concepts: ['++', 'array-concat', 'comptime'],
    },
    {
      id: 'zig-arr-7',
      title: 'Write a Sum Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function sumArray that takes a slice and returns the sum of all elements.',
      skeleton: `const std = @import("std");\n\n// Write sumArray here\n// fn sumArray(data: []const i32) i32\n\npub fn main() void {\n    const nums = [_]i32{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };\n    std.debug.print("sum={d}\\n", .{sumArray(&nums)});\n    // Expected: 55\n}`,
      solution: `const std = @import("std");\n\nfn sumArray(data: []const i32) i32 {\n    var sum: i32 = 0;\n    for (data) |v| sum += v;\n    return sum;\n}\n\npub fn main() void {\n    const nums = [_]i32{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };\n    std.debug.print("sum={d}\\n", .{sumArray(&nums)});\n}`,
      hints: ['Use []const i32 for a read-only slice parameter.', 'Loop with for (data) |v| and accumulate.', 'Pass arrays as slices with &nums.'],
      concepts: ['slice', 'sum', 'for-loop'],
    },
    {
      id: 'zig-arr-8',
      title: 'Write a Reverse Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function reverseArray that reverses a slice of i32 in place.',
      skeleton: `const std = @import("std");\n\n// Write reverseArray here\n// fn reverseArray(data: []i32) void\n\npub fn main() void {\n    var nums = [_]i32{ 1, 2, 3, 4, 5 };\n    reverseArray(&nums);\n    std.debug.print("{any}\\n", .{nums});\n    // Expected: { 5, 4, 3, 2, 1 }\n}`,
      solution: `const std = @import("std");\n\nfn reverseArray(data: []i32) void {\n    var left: usize = 0;\n    var right: usize = data.len - 1;\n    while (left < right) : ({ left += 1; right -= 1; }) {\n        const tmp = data[left];\n        data[left] = data[right];\n        data[right] = tmp;\n    }\n}\n\npub fn main() void {\n    var nums = [_]i32{ 1, 2, 3, 4, 5 };\n    reverseArray(&nums);\n    std.debug.print("{any}\\n", .{nums});\n}`,
      hints: ['Use two indices: left and right, moving inward.', 'Swap data[left] and data[right] each iteration.', 'Stop when left >= right.'],
      concepts: ['in-place-reverse', 'two-pointer', 'swap'],
    },
    {
      id: 'zig-arr-9',
      title: 'Write a 2D Array Accessor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that creates a 3x3 identity matrix and prints it.',
      skeleton: `const std = @import("std");\n\n// Write and print a 3x3 identity matrix\n\npub fn main() void {\n    // Create a 3x3 identity matrix and print each row\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var matrix = [3][3]u32{\n        .{ 1, 0, 0 },\n        .{ 0, 1, 0 },\n        .{ 0, 0, 1 },\n    };\n    for (matrix) |row| {\n        for (row) |cell| {\n            std.debug.print("{d} ", .{cell});\n        }\n        std.debug.print("\\n", .{});\n    }\n    _ = matrix;\n}`,
      hints: ['Type is [3][3]u32.', 'Each row is initialized with .{ a, b, c }.', 'Nested for loops for printing.'],
      concepts: ['2d-array', 'matrix', 'nested-for'],
    },
    {
      id: 'zig-arr-10',
      title: 'Predict Array Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the output of this array operation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = [_]u32{ 10, 20, 30 };\n    const b = [_]u32{ 40, 50 };\n    const c = a ++ b;\n    std.debug.print("{d} {d}\\n", .{ c.len, c[3] });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a = [_]u32{ 10, 20, 30 };\n    const b = [_]u32{ 40, 50 };\n    const c = a ++ b;\n    std.debug.print("{d} {d}\\n", .{ c.len, c[3] });\n}\n\n// Output: 5 40`,
      hints: ['a has 3 elements, b has 2, c has 5.', 'c[3] is the 4th element (0-indexed): 40.', '5 40'],
      concepts: ['++', 'array-concat', 'indexing'],
    },
    {
      id: 'zig-arr-11',
      title: 'Predict Mutable Array',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the array contents after mutation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3, 4, 5 };\n    for (&arr) |*x| x.* *= x.*;\n    std.debug.print("{any}\\n", .{arr});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3, 4, 5 };\n    for (&arr) |*x| x.* *= x.*;\n    std.debug.print("{any}\\n", .{arr});\n}\n\n// Output: { 1, 4, 9, 16, 25 }`,
      hints: ['Each element is squared: x.* *= x.* squares it.', '1^2=1, 2^2=4, 3^2=9, 4^2=16, 5^2=25.', '{ 1, 4, 9, 16, 25 }'],
      concepts: ['mutable-array', 'pointer-capture', 'squaring'],
    },
    {
      id: 'zig-arr-12',
      title: 'Fix Out-of-Bounds',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the array access that goes out of bounds.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30 };\n    // BUG: index 3 is out of bounds for a 3-element array\n    std.debug.print("{d}\\n", .{arr[3]});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30 };\n    std.debug.print("{d}\\n", .{arr[2]});\n}`,
      hints: ['A 3-element array has valid indices 0, 1, 2.', 'Index 3 is out of bounds.', 'Use arr[2] for the last element.'],
      concepts: ['out-of-bounds', 'array-index', 'zero-indexing'],
    },
    {
      id: 'zig-arr-13',
      title: 'Fix const Array Mutation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the code that tries to mutate a const array.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]i32{ 1, 2, 3 };\n    // BUG: cannot mutate const\n    for (&arr) |*x| x.* += 1;\n    std.debug.print("{any}\\n", .{arr});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3 };\n    for (&arr) |*x| x.* += 1;\n    std.debug.print("{any}\\n", .{arr});\n}`,
      hints: ['You cannot take a mutable reference to a const array.', 'Change const to var to allow mutation.', 'var arr'],
      concepts: ['const-vs-var', 'mutation', 'mutable-array'],
    },
    {
      id: 'zig-arr-14',
      title: 'Write a Max Finder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function maxInSlice that returns the maximum value in a slice of i32.',
      skeleton: `const std = @import("std");\n\n// Write maxInSlice here\n// fn maxInSlice(data: []const i32) i32\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 4, 1, 5, -9, 2, 6 };\n    std.debug.print("max={d}\\n", .{maxInSlice(&data)});\n    // Expected: 6\n}`,
      solution: `const std = @import("std");\n\nfn maxInSlice(data: []const i32) i32 {\n    var max = data[0];\n    for (data[1..]) |v| {\n        if (v > max) max = v;\n    }\n    return max;\n}\n\npub fn main() void {\n    const data = [_]i32{ 3, -1, 4, 1, 5, -9, 2, 6 };\n    std.debug.print("max={d}\\n", .{maxInSlice(&data)});\n}`,
      hints: ['Initialize max with the first element.', 'Iterate from index 1 with data[1..].', 'Update max if current value is greater.'],
      concepts: ['max', 'slice', 'iteration'],
    },
    {
      id: 'zig-arr-15',
      title: 'Write a Count Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function countEqual that counts how many elements in a slice equal a target value.',
      skeleton: `const std = @import("std");\n\n// Write countEqual here\n// fn countEqual(data: []const i32, target: i32) usize\n\npub fn main() void {\n    const data = [_]i32{ 1, 3, 3, 2, 3, 1, 3 };\n    std.debug.print("{d}\\n", .{countEqual(&data, 3)});\n    // Expected: 4\n}`,
      solution: `const std = @import("std");\n\nfn countEqual(data: []const i32, target: i32) usize {\n    var count: usize = 0;\n    for (data) |v| if (v == target) { count += 1; };\n    return count;\n}\n\npub fn main() void {\n    const data = [_]i32{ 1, 3, 3, 2, 3, 1, 3 };\n    std.debug.print("{d}\\n", .{countEqual(&data, 3)});\n}`,
      hints: ['Loop over data and compare each element to target.', 'Increment a usize counter on match.', 'Return the count.'],
      concepts: ['count', 'slice', 'comparison'],
    },
    {
      id: 'zig-arr-16',
      title: 'Predict 2D Array Access',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the value accessed from this 2D array.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const m = [3][3]u32{\n        .{ 1, 2, 3 },\n        .{ 4, 5, 6 },\n        .{ 7, 8, 9 },\n    };\n    std.debug.print("{d}\\n", .{m[2][0] + m[0][2]});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const m = [3][3]u32{\n        .{ 1, 2, 3 },\n        .{ 4, 5, 6 },\n        .{ 7, 8, 9 },\n    };\n    std.debug.print("{d}\\n", .{m[2][0] + m[0][2]});\n}\n\n// Output: 10`,
      hints: ['m[2][0] is row 2, col 0 = 7.', 'm[0][2] is row 0, col 2 = 3.', '7 + 3 = 10.'],
      concepts: ['2d-array', 'row-col-indexing'],
    },
    {
      id: 'zig-arr-17',
      title: 'Write an Array Filter',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that copies positive elements from a source slice into a fixed-size result array.',
      skeleton: `const std = @import("std");\n\n// Write filterPositive: copies positives from src into result buf,\n// returns count of how many were copied\n// fn filterPositive(src: []const i32, result: []i32) usize\n\npub fn main() void {\n    const data = [_]i32{ -3, 5, -1, 7, 0, 4, -2 };\n    var out: [10]i32 = undefined;\n    const n = filterPositive(&data, &out);\n    std.debug.print("{any}\\n", .{out[0..n]});\n    // Expected: { 5, 7, 4 }\n}`,
      solution: `const std = @import("std");\n\nfn filterPositive(src: []const i32, result: []i32) usize {\n    var count: usize = 0;\n    for (src) |v| {\n        if (v > 0 and count < result.len) {\n            result[count] = v;\n            count += 1;\n        }\n    }\n    return count;\n}\n\npub fn main() void {\n    const data = [_]i32{ -3, 5, -1, 7, 0, 4, -2 };\n    var out: [10]i32 = undefined;\n    const n = filterPositive(&data, &out);\n    std.debug.print("{any}\\n", .{out[0..n]});\n}`,
      hints: ['Write to result[count] and increment count.', 'Check count < result.len to avoid overflow.', 'Return the number of elements written.'],
      concepts: ['filter', 'output-buffer', 'slice'],
    },
    {
      id: 'zig-arr-18',
      title: 'Refactor to use .len',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Refactor the hardcoded array size to use .len for safety.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30, 40, 50 };\n    var i: usize = 0;\n    while (i < 5) : (i += 1) {\n        std.debug.print("{d} ", .{arr[i]});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30, 40, 50 };\n    var i: usize = 0;\n    while (i < arr.len) : (i += 1) {\n        std.debug.print("{d} ", .{arr[i]});\n    }\n}`,
      hints: ['Replace 5 with arr.len.', 'arr.len is a comptime-known constant.', 'arr.len adapts automatically if the array changes.'],
      concepts: ['.len', 'refactoring', 'maintainability'],
    },
    {
      id: 'zig-arr-19',
      title: 'Refactor to for Loop',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Refactor the while loop to a more idiomatic for loop.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]i32{ 2, 4, 6, 8 };\n    var i: usize = 0;\n    while (i < arr.len) : (i += 1) {\n        std.debug.print("{d}\\n", .{arr[i]});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]i32{ 2, 4, 6, 8 };\n    for (arr) |v| {\n        std.debug.print("{d}\\n", .{v});\n    }\n}`,
      hints: ['for (arr) |v| is more idiomatic than while with index.', 'The capture |v| gets each value directly.', 'No manual index needed.'],
      concepts: ['for-loop', 'idiomatic-zig', 'refactoring'],
    },
    {
      id: 'zig-arr-20',
      title: 'Write a comptime Array Builder',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function that generates an array of squares from 1 to N.',
      skeleton: `const std = @import("std");\n\n// Write squares(comptime n: usize) [n]u32\n// Returns { 1, 4, 9, 16, ... }\n\npub fn main() void {\n    const sq = squares(6);\n    std.debug.print("{any}\\n", .{sq});\n    // Expected: { 1, 4, 9, 16, 25, 36 }\n}`,
      solution: `const std = @import("std");\n\nfn squares(comptime n: usize) [n]u32 {\n    var arr: [n]u32 = undefined;\n    comptime var i: usize = 0;\n    inline while (i < n) : (i += 1) {\n        arr[i] = @as(u32, (i + 1) * (i + 1));\n    }\n    return arr;\n}\n\npub fn main() void {\n    const sq = squares(6);\n    std.debug.print("{any}\\n", .{sq});\n}`,
      hints: ['comptime n enables [n]u32 as return type.', 'comptime var + inline while runs at compile time.', 'arr[i] = (i+1)*(i+1) gives 1, 4, 9...'],
      concepts: ['comptime', 'array-generation', 'inline-while'],
    },
  ],
};
