import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-slice',
  title: '07. Slices',
  explanation: `## Slices in Zig\n\nA slice is a pointer + length pair: \`[]T\`. Unlike arrays, slices are runtime-sized.\n\n### Creating Slices\n\n\`\`\`zig\nconst arr = [_]u32{ 1, 2, 3, 4, 5 };\nconst all: []const u32 = &arr;         // entire array as slice\nconst mid = arr[1..4];                 // elements 1, 2, 3\nconst tail = arr[2..];                 // from index 2 to end\n\`\`\`\n\n### Slice Fields\n\n\`\`\`zig\nconst s = arr[1..4];\nstd.debug.print("{d}\\n", .{s.len});  // 3\nstd.debug.print("{d}\\n", .{s.ptr[0]});  // first element\n\`\`\`\n\n### Functions Taking Slices\n\n\`\`\`zig\nfn sum(data: []const u32) u32 {\n    var total: u32 = 0;\n    for (data) |v| total += v;\n    return total;\n}\n// Call: sum(&arr) or sum(arr[0..3])\n\`\`\`\n\n### Mutable Slices\n\n\`\`\`zig\nfn scaleBy2(data: []u32) void {\n    for (data) |*v| v.* *= 2;\n}\n\`\`\``,
  exercises: [
    {
      id: 'zig-slice-1',
      title: 'Create a Slice',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Create a slice from an array covering elements 1 through 3.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]i32{ 10, 20, 30, 40, 50 };\n    const s = arr[___];\n    std.debug.print("len={d} first={d}\\n", .{ s.len, s[0] });\n    // Expected: len=3 first=20\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]i32{ 10, 20, 30, 40, 50 };\n    const s = arr[1..4];\n    std.debug.print("len={d} first={d}\\n", .{ s.len, s[0] });\n}`,
      hints: ['arr[start..end] creates a slice from start (inclusive) to end (exclusive).', 'arr[1..4] gives elements at indices 1, 2, 3.', '1..4'],
      concepts: ['slice', 'slice-syntax', 'range'],
    },
    {
      id: 'zig-slice-2',
      title: 'Slice Length and Pointer',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Access slice length and its underlying pointer.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u8{ 'H', 'e', 'l', 'l', 'o' };\n    const s: []const u8 = &arr;\n    std.debug.print("len={d} ptr_first={d}\\n", .{ s.___, s.___[0] });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u8{ 'H', 'e', 'l', 'l', 'o' };\n    const s: []const u8 = &arr;\n    std.debug.print("len={d} ptr_first={d}\\n", .{ s.len, s.ptr[0] });\n}`,
      hints: ['s.len gives the number of elements.', 's.ptr is the underlying pointer.', 'len and ptr'],
      concepts: ['slice-len', 'slice-ptr'],
    },
    {
      id: 'zig-slice-3',
      title: 'Pass Slice to Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Pass an array as a slice to a function.',
      skeleton: `const std = @import("std");\n\nfn sum(data: []const u32) u32 {\n    var total: u32 = 0;\n    for (data) |v| total += v;\n    return total;\n}\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{sum(___arr)});\n}`,
      solution: `const std = @import("std");\n\nfn sum(data: []const u32) u32 {\n    var total: u32 = 0;\n    for (data) |v| total += v;\n    return total;\n}\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{sum(&arr)});\n}`,
      hints: ['Use & to coerce an array to a slice.', '&arr converts [5]u32 to []const u32.', '&arr'],
      concepts: ['slice', 'coerce', 'function-argument'],
    },
    {
      id: 'zig-slice-4',
      title: 'Open-Ended Slice',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Create a slice from index 2 to the end of the array.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    const tail = arr[___];\n    std.debug.print("{d}\\n", .{tail.len});\n    // Expected: 3\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    const tail = arr[2..];\n    std.debug.print("{d}\\n", .{tail.len});\n}`,
      hints: ['arr[start..] creates a slice from start to the end.', 'arr[2..] gives elements at indices 2, 3, 4.', '2..'],
      concepts: ['open-ended-slice', 'slice-syntax'],
    },
    {
      id: 'zig-slice-5',
      title: 'Mutable Slice',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Take a mutable slice and modify elements through it.',
      skeleton: `const std = @import("std");\n\nfn doubleAll(data: ___u32) void {\n    for (data) |*v| v.* *= 2;\n}\n\npub fn main() void {\n    var arr = [_]u32{ 1, 2, 3 };\n    doubleAll(&arr);\n    std.debug.print("{any}\\n", .{arr});\n}`,
      solution: `const std = @import("std");\n\nfn doubleAll(data: []u32) void {\n    for (data) |*v| v.* *= 2;\n}\n\npub fn main() void {\n    var arr = [_]u32{ 1, 2, 3 };\n    doubleAll(&arr);\n    std.debug.print("{any}\\n", .{arr});\n}`,
      hints: ['[]u32 is a mutable slice (no const).', '[]const u32 is read-only.', '[]u32'],
      concepts: ['mutable-slice', '[]T', 'modification'],
    },
    {
      id: 'zig-slice-6',
      title: 'Write a Contains Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function sliceContains that returns true if a slice contains a target element.',
      skeleton: `const std = @import("std");\n\n// Write sliceContains here\n// fn sliceContains(data: []const i32, target: i32) bool\n\npub fn main() void {\n    const data = [_]i32{ 3, 7, 2, 9, 4 };\n    std.debug.print("{} {}\\n", .{ sliceContains(&data, 9), sliceContains(&data, 5) });\n    // true false\n}`,
      solution: `const std = @import("std");\n\nfn sliceContains(data: []const i32, target: i32) bool {\n    for (data) |v| if (v == target) return true;\n    return false;\n}\n\npub fn main() void {\n    const data = [_]i32{ 3, 7, 2, 9, 4 };\n    std.debug.print("{} {}\\n", .{ sliceContains(&data, 9), sliceContains(&data, 5) });\n}`,
      hints: ['Loop and return true as soon as a match is found.', 'Return false after the loop if not found.', 'for (data) |v| if (v == target) return true;'],
      concepts: ['linear-search', 'slice', 'bool-return'],
    },
    {
      id: 'zig-slice-7',
      title: 'Write a Copy Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function copySlice that copies elements from src into dst, returning the number of elements copied.',
      skeleton: `const std = @import("std");\n\n// Write copySlice(dst: []i32, src: []const i32) usize\n\npub fn main() void {\n    const src = [_]i32{ 1, 2, 3, 4, 5 };\n    var dst: [3]i32 = undefined;\n    const n = copySlice(&dst, &src);\n    std.debug.print("{d} {any}\\n", .{ n, dst });\n    // 3 { 1, 2, 3 }\n}`,
      solution: `const std = @import("std");\n\nfn copySlice(dst: []i32, src: []const i32) usize {\n    const n = @min(dst.len, src.len);\n    for (0..n) |i| dst[i] = src[i];\n    return n;\n}\n\npub fn main() void {\n    const src = [_]i32{ 1, 2, 3, 4, 5 };\n    var dst: [3]i32 = undefined;\n    const n = copySlice(&dst, &src);\n    std.debug.print("{d} {any}\\n", .{ n, dst });\n}`,
      hints: ['Copy min(dst.len, src.len) elements.', 'Use @min for the safe minimum.', 'for (0..n) |i| dst[i] = src[i];'],
      concepts: ['copy', 'slice', '@min'],
    },
    {
      id: 'zig-slice-8',
      title: 'Predict Slice Mutation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the original array after the slice is modified.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3, 4, 5 };\n    const s = arr[1..4];\n    for (@as([]const i32, s), 0..) |_, i| arr[1 + i] = @as(i32, @intCast(i * 10));\n    std.debug.print("{any}\\n", .{arr});\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3, 4, 5 };\n    const s = arr[1..4];\n    for (@as([]const i32, s), 0..) |_, i| arr[1 + i] = @as(i32, @intCast(i * 10));\n    std.debug.print("{any}\\n", .{arr});\n}\n\n// Output: { 1, 0, 10, 20, 5 }`,
      hints: ['Slice s points into arr[1..4].', 'i=0: arr[1]=0, i=1: arr[2]=10, i=2: arr[3]=20.', '{ 1, 0, 10, 20, 5 }'],
      concepts: ['slice-aliasing', 'mutation', 'pointer'],
    },
    {
      id: 'zig-slice-9',
      title: 'Predict Slice Length',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the length of these slices.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5, 6, 7, 8 };\n    std.debug.print("{d} {d} {d}\\n", .{\n        arr[2..6].len,\n        arr[0..].len,\n        arr[5..8].len,\n    });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5, 6, 7, 8 };\n    std.debug.print("{d} {d} {d}\\n", .{\n        arr[2..6].len,\n        arr[0..].len,\n        arr[5..8].len,\n    });\n}\n\n// Output: 4 8 3`,
      hints: ['arr[2..6] has 6-2=4 elements.', 'arr[0..] is the full array: 8 elements.', 'arr[5..8] has 8-5=3 elements.'],
      concepts: ['slice-length', 'range'],
    },
    {
      id: 'zig-slice-10',
      title: 'Fix Slice Out of Range',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the slice range that goes beyond the array bounds.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3 };\n    // BUG: arr only has 3 elements\n    const s = arr[1..5];\n    std.debug.print("{d}\\n", .{s.len});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3 };\n    const s = arr[1..3];\n    std.debug.print("{d}\\n", .{s.len});\n}`,
      hints: ['The end index cannot exceed arr.len (3).', 'arr[1..3] is valid: indices 1, 2.', 'Change 5 to arr.len or 3.'],
      concepts: ['slice-bounds', 'range', 'safety'],
    },
    {
      id: 'zig-slice-11',
      title: 'Write a Trim Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function trimZeros that returns a sub-slice with leading and trailing zero elements removed.',
      skeleton: `const std = @import("std");\n\n// Write trimZeros(data: []const i32) []const i32\n\npub fn main() void {\n    const data = [_]i32{ 0, 0, 3, 4, 0, 5, 0, 0 };\n    const trimmed = trimZeros(&data);\n    std.debug.print("{any}\\n", .{trimmed});\n    // Expected: { 3, 4, 0, 5 }\n}`,
      solution: `const std = @import("std");\n\nfn trimZeros(data: []const i32) []const i32 {\n    var start: usize = 0;\n    while (start < data.len and data[start] == 0) : (start += 1) {}\n    var end: usize = data.len;\n    while (end > start and data[end - 1] == 0) : (end -= 1) {}\n    return data[start..end];\n}\n\npub fn main() void {\n    const data = [_]i32{ 0, 0, 3, 4, 0, 5, 0, 0 };\n    const trimmed = trimZeros(&data);\n    std.debug.print("{any}\\n", .{trimmed});\n}`,
      hints: ['Find the first non-zero from the start.', 'Find the last non-zero from the end.', 'Return data[start..end].'],
      concepts: ['trim', 'sub-slice', 'two-pointer'],
    },
    {
      id: 'zig-slice-12',
      title: 'Refactor Array Index to Slice',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the function to take a []const u32 slice instead of a fixed-size [5]u32 array.',
      skeleton: `const std = @import("std");\n\nfn sumFive(data: [5]u32) u32 {\n    var s: u32 = 0;\n    for (data) |v| s += v;\n    return s;\n}\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{sumFive(arr)});\n}`,
      solution: `const std = @import("std");\n\nfn sumFive(data: []const u32) u32 {\n    var s: u32 = 0;\n    for (data) |v| s += v;\n    return s;\n}\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5 };\n    std.debug.print("{d}\\n", .{sumFive(&arr)});\n}`,
      hints: ['Change [5]u32 to []const u32 for flexibility.', 'Pass &arr instead of arr to provide a slice.', 'The function now works with any size slice.'],
      concepts: ['slice', 'refactoring', 'flexibility'],
    },
    {
      id: 'zig-slice-13',
      title: 'Write a Split-at Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function splitAt that returns two slices split at a given index.',
      skeleton: `const std = @import("std");\n\n// Write splitAt(data: []const u32, mid: usize)\n// Returns a struct { left: []const u32, right: []const u32 }\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5, 6 };\n    const parts = splitAt(&arr, 3);\n    std.debug.print("{any} {any}\\n", .{ parts.left, parts.right });\n    // { 1, 2, 3 } { 4, 5, 6 }\n}`,
      solution: `const std = @import("std");\n\nfn splitAt(data: []const u32, mid: usize) struct { left: []const u32, right: []const u32 } {\n    const safe_mid = @min(mid, data.len);\n    return .{ .left = data[0..safe_mid], .right = data[safe_mid..] };\n}\n\npub fn main() void {\n    const arr = [_]u32{ 1, 2, 3, 4, 5, 6 };\n    const parts = splitAt(&arr, 3);\n    std.debug.print("{any} {any}\\n", .{ parts.left, parts.right });\n}`,
      hints: ['Return an anonymous struct with two slice fields.', 'data[0..mid] is the left, data[mid..] is the right.', 'Use @min to clamp mid to data.len.'],
      concepts: ['split', 'sub-slice', 'multiple-return'],
    },
    {
      id: 'zig-slice-14',
      title: 'Predict Coercion',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the type and length after array-to-slice coercion.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u8{ 1, 2, 3, 4, 5 };\n    const s: []const u8 = &arr;\n    std.debug.print("{d} {d}\\n", .{ s.len, s[4] });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u8{ 1, 2, 3, 4, 5 };\n    const s: []const u8 = &arr;\n    std.debug.print("{d} {d}\\n", .{ s.len, s[4] });\n}\n\n// Output: 5 5`,
      hints: ['The slice has the same length as the array.', 's.len = 5, s[4] = 5.', '5 5'],
      concepts: ['array-to-slice', 'coercion'],
    },
    {
      id: 'zig-slice-15',
      title: 'Write an Index-Of',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function indexOf that returns the index of the first occurrence of target, or null if not found.',
      skeleton: `const std = @import("std");\n\n// Write indexOf(data: []const i32, target: i32) ?usize\n\npub fn main() void {\n    const data = [_]i32{ 10, 20, 30, 20, 40 };\n    if (indexOf(&data, 20)) |i| {\n        std.debug.print("found at {d}\\n", .{i});\n    }\n    if (indexOf(&data, 99) == null) {\n        std.debug.print("not found\\n", .{});\n    }\n}`,
      solution: `const std = @import("std");\n\nfn indexOf(data: []const i32, target: i32) ?usize {\n    for (data, 0..) |v, i| {\n        if (v == target) return i;\n    }\n    return null;\n}\n\npub fn main() void {\n    const data = [_]i32{ 10, 20, 30, 20, 40 };\n    if (indexOf(&data, 20)) |i| {\n        std.debug.print("found at {d}\\n", .{i});\n    }\n    if (indexOf(&data, 99) == null) {\n        std.debug.print("not found\\n", .{});\n    }\n}`,
      hints: ['Return ?usize (optional index).', 'Use for (data, 0..) |v, i| to get both value and index.', 'Return null after the loop if not found.'],
      concepts: ['optional', 'index-of', 'linear-search'],
    },
    {
      id: 'zig-slice-16',
      title: 'Fix const Slice Mutation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the function that tries to mutate through a const slice.',
      skeleton: `const std = @import("std");\n\nfn increment(data: []const i32) void {\n    // BUG: cannot mutate through const slice\n    for (data) |*v| v.* += 1;\n}\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3 };\n    increment(&arr);\n    std.debug.print("{any}\\n", .{arr});\n}`,
      solution: `const std = @import("std");\n\nfn increment(data: []i32) void {\n    for (data) |*v| v.* += 1;\n}\n\npub fn main() void {\n    var arr = [_]i32{ 1, 2, 3 };\n    increment(&arr);\n    std.debug.print("{any}\\n", .{arr});\n}`,
      hints: ['[]const i32 is read-only -- remove const to allow mutation.', 'Change []const i32 to []i32.', 'Mutable slices are []T (without const).'],
      concepts: ['const-slice', 'mutable-slice', '[]T'],
    },
    {
      id: 'zig-slice-17',
      title: 'Write a Join Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that copies two slices end-to-end into a destination buffer.',
      skeleton: `const std = @import("std");\n\n// Write joinInto(a: []const u32, b: []const u32, dst: []u32) usize\n\npub fn main() void {\n    const a = [_]u32{ 1, 2, 3 };\n    const b = [_]u32{ 4, 5 };\n    var buf: [10]u32 = undefined;\n    const n = joinInto(&a, &b, &buf);\n    std.debug.print("{any}\\n", .{buf[0..n]});\n    // { 1, 2, 3, 4, 5 }\n}`,
      solution: `const std = @import("std");\n\nfn joinInto(a: []const u32, b: []const u32, dst: []u32) usize {\n    const total = @min(a.len + b.len, dst.len);\n    for (0..@min(a.len, total)) |i| dst[i] = a[i];\n    const offset = @min(a.len, total);\n    for (0..@min(b.len, total - offset)) |i| dst[offset + i] = b[i];\n    return total;\n}\n\npub fn main() void {\n    const a = [_]u32{ 1, 2, 3 };\n    const b = [_]u32{ 4, 5 };\n    var buf: [10]u32 = undefined;\n    const n = joinInto(&a, &b, &buf);\n    std.debug.print("{any}\\n", .{buf[0..n]});\n}`,
      hints: ['Copy a first, then b starting at offset a.len.', 'Use @min to handle buffer overflow.', 'Return total number of elements written.'],
      concepts: ['join', 'copy', 'buffer'],
    },
    {
      id: 'zig-slice-18',
      title: 'Refactor to Sentinel-Terminated',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor a loop over a C-style null-terminated u8 array to use a proper slice.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const msg = "Hello".*;\n    var i: usize = 0;\n    while (msg[i] != 0) : (i += 1) {\n        std.debug.print("{c}", .{msg[i]});\n    }\n    std.debug.print("\\n", .{});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const msg = "Hello";\n    for (msg) |c| {\n        std.debug.print("{c}", .{c});\n    }\n    std.debug.print("\\n", .{});\n}`,
      hints: ['String literals are []const u8 slices in Zig.', 'for (msg) |c| iterates each byte.', 'No manual null check needed.'],
      concepts: ['string-slice', 'for-loop', 'refactoring'],
    },
    {
      id: 'zig-slice-19',
      title: 'Predict Open-Ended Slice',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what arr[3..] produces.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30, 40, 50 };\n    const s = arr[3..];\n    std.debug.print("{d} {d}\\n", .{ s.len, s[1] });\n}\n\n// Output: ???`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const arr = [_]u32{ 10, 20, 30, 40, 50 };\n    const s = arr[3..];\n    std.debug.print("{d} {d}\\n", .{ s.len, s[1] });\n}\n\n// Output: 2 50`,
      hints: ['arr[3..] gives elements at index 3 and 4: { 40, 50 }.', 's.len = 2, s[1] = 50.', '2 50'],
      concepts: ['open-ended-slice', 'slice-length'],
    },
    {
      id: 'zig-slice-20',
      title: 'Write a Slice-Based Sort',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function bubbleSort that sorts a mutable slice of i32 in ascending order.',
      skeleton: `const std = @import("std");\n\n// Write bubbleSort here\n// fn bubbleSort(data: []i32) void\n\npub fn main() void {\n    var data = [_]i32{ 5, 3, 8, 1, 9, 2 };\n    bubbleSort(&data);\n    std.debug.print("{any}\\n", .{data});\n    // { 1, 2, 3, 5, 8, 9 }\n}`,
      solution: `const std = @import("std");\n\nfn bubbleSort(data: []i32) void {\n    var n = data.len;\n    while (n > 1) : (n -= 1) {\n        for (0..n - 1) |i| {\n            if (data[i] > data[i + 1]) {\n                const tmp = data[i];\n                data[i] = data[i + 1];\n                data[i + 1] = tmp;\n            }\n        }\n    }\n}\n\npub fn main() void {\n    var data = [_]i32{ 5, 3, 8, 1, 9, 2 };\n    bubbleSort(&data);\n    std.debug.print("{any}\\n", .{data});\n}`,
      hints: ['Bubble sort: pass through the array swapping adjacent elements if out of order.', 'Reduce n each pass since the largest is now at the end.', 'Use a tmp variable for the swap.'],
      concepts: ['bubble-sort', 'mutable-slice', 'swap'],
    },
  ],
};
