import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-build',
  title: '26. Build System',
  explanation: `## Build System

Zig's build system is written in Zig itself via \`build.zig\`. It uses a graph-based step system to declare build artifacts, dependencies, and install rules.

### Basic build.zig
\`\`\`zig
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "myapp",
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });

    b.installArtifact(exe);
}
\`\`\`

### Build Steps
\`\`\`zig
const run_cmd = b.addRunArtifact(exe);
run_cmd.step.dependOn(b.getInstallStep());

const run_step = b.step("run", "Run the application");
run_step.dependOn(&run_cmd.step);
\`\`\`

### Libraries and Modules
\`\`\`zig
const lib = b.addStaticLibrary(.{
    .name = "mylib",
    .root_source_file = b.path("src/lib.zig"),
    .target = target,
    .optimize = optimize,
});

exe.addModule("utils", b.createModule(.{
    .root_source_file = b.path("src/utils.zig"),
}));
\`\`\`

### Cross-Compilation
\`\`\`zig
const target = b.resolveTargetQuery(.{
    .cpu_arch = .aarch64,
    .os_tag = .linux,
});
\`\`\``,
  exercises: [
    { id: 'zig-build-1', title: 'Import std in build.zig', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Complete the standard import in build.zig.', skeleton: `const std = @___("std");\n\npub fn build(b: *std.Build) void {\n    _ = b;\n}`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    _ = b;\n}`, hints: ['The builtin to import modules is @import.', 'build.zig uses std just like normal Zig code.', '@import takes a string literal.'], concepts: ['import', 'build-zig'] },
    { id: 'zig-build-2', title: 'Standard Target Options', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Get default target options from the build system.', skeleton: `pub fn build(b: *std.Build) void {\n    const target = b.___(.{});\n    _ = target;\n}`, solution: `pub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    _ = target;\n}`, hints: ['The method name starts with "standard" and ends with "TargetOptions".', 'It accepts an anonymous struct with defaults.', 'This allows the user to override the target via CLI.'], concepts: ['target-options', 'build-api'] },
    { id: 'zig-build-3', title: 'Add Executable', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Declare an executable artifact in build.zig.', skeleton: `pub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.___(. {\n        .name = "hello",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(exe);\n}`, solution: `pub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.addExecutable(.{\n        .name = "hello",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(exe);\n}`, hints: ['The method to add an executable is addExecutable.', 'It takes an anonymous struct with build configuration.', 'installArtifact registers it for zig build.'], concepts: ['addExecutable', 'installArtifact'] },
    { id: 'zig-build-4', title: 'Add Static Library', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Declare a static library artifact.', skeleton: `const lib = b.___(. {\n    .name = "mathlib",\n    .root_source_file = b.path("src/math.zig"),\n    .target = target,\n    .optimize = optimize,\n});\n\nb.installArtifact(lib);`, solution: `const lib = b.addStaticLibrary(.{\n    .name = "mathlib",\n    .root_source_file = b.path("src/math.zig"),\n    .target = target,\n    .optimize = optimize,\n});\n\nb.installArtifact(lib);`, hints: ['Static libraries are added with addStaticLibrary.', 'The API is the same shape as addExecutable.', 'Static libraries produce .a or .lib files.'], concepts: ['addStaticLibrary', 'library-artifacts'] },
    { id: 'zig-build-5', title: 'Optimize Option', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Get the standard optimization option.', skeleton: `const optimize = b.___(.{});`, solution: `const optimize = b.standardOptimizeOption(.{});`, hints: ['Similar to standardTargetOptions but for optimization.', 'Allows user to pass -Doptimize=ReleaseFast etc.', 'The method is standardOptimizeOption.'], concepts: ['optimization', 'build-options'] },
    { id: 'zig-build-6', title: 'Build Step Dependencies', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Set up a run step that depends on install.', skeleton: `const run_cmd = b.addRunArtifact(exe);\nrun_cmd.step.___(b.getInstallStep());\n\nconst run_step = b.step("run", "Run the app");\nrun_step.dependOn(&run_cmd.step);`, solution: `const run_cmd = b.addRunArtifact(exe);\nrun_cmd.step.dependOn(b.getInstallStep());\n\nconst run_step = b.step("run", "Run the app");\nrun_step.dependOn(&run_cmd.step);`, hints: ['dependOn establishes ordering between steps.', 'The run must happen after install completes.', 'dependOn takes a *Step pointer.'], concepts: ['build-steps', 'dependOn'] },
    { id: 'zig-build-7', title: 'Write a Complete build.zig', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a build.zig that builds an executable and a test step.', skeleton: `// Write a complete build.zig that:\n// 1. Imports std\n// 2. Declares pub fn build(b: *std.Build) void\n// 3. Gets standard target and optimize options\n// 4. Adds an executable named "app" from "src/main.zig"\n// 5. Installs the artifact\n// 6. Adds unit tests from "src/main.zig"\n// 7. Creates a "test" step that runs the tests`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(exe);\n\n    const unit_tests = b.addTest(.{\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    const run_tests = b.addRunArtifact(unit_tests);\n    const test_step = b.step("test", "Run unit tests");\n    test_step.dependOn(&run_tests.step);\n}`, hints: ['b.addTest creates a test compilation.', 'addRunArtifact creates a step that runs the compiled tests.', 'b.step creates a named step accessible via zig build test.'], concepts: ['build-zig', 'test-step', 'addTest'] },
    { id: 'zig-build-8', title: 'Write build.zig with Shared Library', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write build.zig that produces both a shared library and an executable linking to it.', skeleton: `// Write a build.zig that:\n// 1. Creates a shared library "mylib" from "src/lib.zig"\n// 2. Creates an executable "app" from "src/main.zig"\n// 3. Links the executable against the shared library\n// 4. Installs both artifacts`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const lib = b.addSharedLibrary(.{\n        .name = "mylib",\n        .root_source_file = b.path("src/lib.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(lib);\n\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    exe.linkLibrary(lib);\n    b.installArtifact(exe);\n}`, hints: ['addSharedLibrary creates a .so/.dll/.dylib.', 'linkLibrary connects the executable to the library.', 'Both artifacts need installArtifact.'], concepts: ['addSharedLibrary', 'linkLibrary'] },
    { id: 'zig-build-9', title: 'Write Cross-Compilation Target', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write build.zig that cross-compiles for ARM64 Linux.', skeleton: `// Write a build.zig that:\n// 1. Resolves a target query for aarch64 linux\n// 2. Uses ReleaseSafe optimization\n// 3. Builds an executable "server" from "src/main.zig"\n// 4. Installs the artifact`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.resolveTargetQuery(.{\n        .cpu_arch = .aarch64,\n        .os_tag = .linux,\n    });\n\n    const exe = b.addExecutable(.{\n        .name = "server",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = .ReleaseSafe,\n    });\n\n    b.installArtifact(exe);\n}`, hints: ['resolveTargetQuery takes a CrossTarget query struct.', 'cpu_arch = .aarch64 selects ARM64.', 'os_tag = .linux selects Linux.'], concepts: ['cross-compilation', 'resolveTargetQuery'] },
    { id: 'zig-build-10', title: 'Write Build Options', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write build.zig with a custom boolean build option.', skeleton: `// Write a build.zig that:\n// 1. Declares a boolean option "enable-logging" with default false\n// 2. Creates an executable "app" from "src/main.zig"\n// 3. Passes the option as a build-time define to the code\n// 4. Installs the artifact`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const enable_logging = b.option(bool, "enable-logging", "Enable debug logging") orelse false;\n\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    const options = b.addOptions();\n    options.addOption(bool, "enable_logging", enable_logging);\n    exe.root_module.addOptions("config", options);\n\n    b.installArtifact(exe);\n}`, hints: ['b.option declares a CLI-settable option.', 'b.addOptions creates an options module.', 'addOptions on root_module exposes it as an importable module.'], concepts: ['build-options', 'addOptions', 'compile-time-config'] },
    { id: 'zig-build-11', title: 'Write Run Step with Args', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a run step that passes command-line arguments.', skeleton: `// Write code that:\n// 1. Creates a run artifact from an exe\n// 2. Passes args from build system CLI (b.args)\n// 3. Falls back to default args ["--port", "8080"]\n// 4. Creates a named "run" step`, solution: `const run_cmd = b.addRunArtifact(exe);\nrun_cmd.step.dependOn(b.getInstallStep());\n\nif (b.args) |args| {\n    run_cmd.addArgs(args);\n} else {\n    run_cmd.addArgs(&.{ "--port", "8080" });\n}\n\nconst run_step = b.step("run", "Run the application");\nrun_step.dependOn(&run_cmd.step);`, hints: ['b.args captures arguments after -- on CLI.', 'addArgs passes arguments to the run command.', 'Use if on b.args since it is optional.'], concepts: ['addRunArtifact', 'addArgs', 'build-step'] },
    { id: 'zig-build-12', title: 'Write Module Dependency', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write build.zig that creates and adds a module dependency.', skeleton: `// Write code that:\n// 1. Creates a module named "utils" from "src/utils.zig"\n// 2. Creates an executable from "src/main.zig"\n// 3. Adds the module as an import so main can @import("utils")\n// 4. Installs the executable`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const utils_mod = b.createModule(.{\n        .root_source_file = b.path("src/utils.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    exe.root_module.addImport("utils", utils_mod);\n    b.installArtifact(exe);\n}`, hints: ['createModule defines a separate compilation module.', 'addImport on root_module makes it available via @import.', 'The string name must match what the code uses in @import.'], concepts: ['createModule', 'addImport', 'module-dependencies'] },
    { id: 'zig-build-13', title: 'Fix Missing Install', type: 'fix-bug', difficulty: 'beginner', language: 'zig', goal: 'Fix a build.zig where the artifact is not installed.', skeleton: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.addExecutable(.{\n        .name = "myapp",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n    // Running zig build produces nothing in zig-out/\n}`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.addExecutable(.{\n        .name = "myapp",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(exe);\n}`, hints: ['Without installArtifact, nothing is copied to zig-out.', 'installArtifact registers the exe for the install step.', 'zig build runs the default install step.'], concepts: ['installArtifact', 'build-output'] },
    { id: 'zig-build-14', title: 'Fix Test Step Dependency', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix a test step that does not actually run the tests.', skeleton: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const unit_tests = b.addTest(.{\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    // Bug: test step compiles but never runs\n    const test_step = b.step("test", "Run unit tests");\n    test_step.dependOn(&unit_tests.step);\n}`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const unit_tests = b.addTest(.{\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    const run_unit_tests = b.addRunArtifact(unit_tests);\n    const test_step = b.step("test", "Run unit tests");\n    test_step.dependOn(&run_unit_tests.step);\n}`, hints: ['addTest only compiles the tests, it does not run them.', 'You need addRunArtifact to create a step that executes.', 'The test_step should depend on the run step, not the compile step.'], concepts: ['addTest', 'addRunArtifact', 'test-execution'] },
    { id: 'zig-build-15', title: 'Fix Circular Step Dependency', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix a build.zig with a circular step dependency.', skeleton: `pub fn build(b: *std.Build) void {\n    const step_a = b.step("a", "Step A");\n    const step_b = b.step("b", "Step B");\n    const step_c = b.step("c", "Step C");\n\n    // Bug: circular dependency a -> b -> c -> a\n    step_a.dependOn(step_b);\n    step_b.dependOn(step_c);\n    step_c.dependOn(step_a);\n}`, solution: `pub fn build(b: *std.Build) void {\n    const step_a = b.step("a", "Step A");\n    const step_b = b.step("b", "Step B");\n    const step_c = b.step("c", "Step C");\n\n    // Fixed: linear dependency chain a -> b -> c\n    step_a.dependOn(step_b);\n    step_b.dependOn(step_c);\n}`, hints: ['A circular dependency means no step can start first.', 'Remove the dependency from step_c back to step_a.', 'Dependencies must form a directed acyclic graph (DAG).'], concepts: ['dependency-graph', 'DAG', 'circular-dependency'] },
    { id: 'zig-build-16', title: 'Predict Build Step Order', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the order build steps execute.', skeleton: `// Given these step dependencies:\n// "run" depends on "install"\n// "install" depends on "compile"\n// \n// When user runs: zig build run\n// In what order do steps execute?\n// A) run, install, compile\n// B) compile, install, run\n// C) install, compile, run`, solution: `B) compile, install, run`, hints: ['Dependencies execute before dependents.', 'run depends on install, install depends on compile.', 'Execution order is leaf-to-root.'], concepts: ['build-step-order', 'dependency-resolution'] },
    { id: 'zig-build-17', title: 'Predict Default Step', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict what happens with plain zig build.', skeleton: `// Given this build.zig:\n// const exe = b.addExecutable(...);\n// b.installArtifact(exe);\n// const run_step = b.step("run", "Run app");\n// run_step.dependOn(&b.addRunArtifact(exe).step);\n//\n// What happens when user runs just: zig build\n// A) The app is compiled and run\n// B) The app is compiled and installed to zig-out/\n// C) Nothing happens`, solution: `B) The app is compiled and installed to zig-out/`, hints: ['The default step is the install step.', 'zig build without arguments runs the install step.', 'The run step is only triggered by zig build run.'], concepts: ['default-step', 'install-step'] },
    { id: 'zig-build-18', title: 'Predict Option Behavior', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict what happens with a missing build option.', skeleton: `// build.zig:\n// const verbose = b.option(bool, "verbose", "Enable verbose") orelse false;\n//\n// User runs: zig build\n// What is the value of verbose?\n// A) true\n// B) false\n// C) Compile error\n// D) null`, solution: `B) false`, hints: ['b.option returns ?bool when no argument given.', 'orelse false provides the default when null.', 'The user did not pass -Dverbose=true.'], concepts: ['build-options', 'orelse', 'defaults'] },
    { id: 'zig-build-19', title: 'Refactor Duplicate Build Config', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor duplicated target/optimize options into shared variables.', skeleton: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = b.standardTargetOptions(.{}),\n        .optimize = b.standardOptimizeOption(.{}),\n    });\n\n    const tests = b.addTest(.{\n        .root_source_file = b.path("src/main.zig"),\n        .target = b.standardTargetOptions(.{}),\n        .optimize = b.standardOptimizeOption(.{}),\n    });\n\n    b.installArtifact(exe);\n    const test_step = b.step("test", "Run tests");\n    test_step.dependOn(&b.addRunArtifact(tests).step);\n}`, solution: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const exe = b.addExecutable(.{\n        .name = "app",\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    const tests = b.addTest(.{\n        .root_source_file = b.path("src/main.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n\n    b.installArtifact(exe);\n    const test_step = b.step("test", "Run tests");\n    test_step.dependOn(&b.addRunArtifact(tests).step);\n}`, hints: ['Extract standardTargetOptions and standardOptimizeOption into local consts.', 'Calling them multiple times may yield different results if CLI args change.', 'Shared variables ensure consistent configuration.'], concepts: ['DRY', 'build-configuration'] },
    { id: 'zig-build-20', title: 'Refactor to Helper Function', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor repeated addExecutable calls into a helper.', skeleton: `const std = @import("std");\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    const server = b.addExecutable(.{\n        .name = "server",\n        .root_source_file = b.path("src/server.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n    b.installArtifact(server);\n\n    const client = b.addExecutable(.{\n        .name = "client",\n        .root_source_file = b.path("src/client.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n    b.installArtifact(client);\n\n    const admin = b.addExecutable(.{\n        .name = "admin",\n        .root_source_file = b.path("src/admin.zig"),\n        .target = target,\n        .optimize = optimize,\n    });\n    b.installArtifact(admin);\n}`, solution: `const std = @import("std");\n\nfn addApp(\n    b: *std.Build,\n    name: []const u8,\n    src: []const u8,\n    target: std.Build.ResolvedTarget,\n    optimize: std.builtin.OptimizeMode,\n) void {\n    const exe = b.addExecutable(.{\n        .name = name,\n        .root_source_file = b.path(src),\n        .target = target,\n        .optimize = optimize,\n    });\n    b.installArtifact(exe);\n}\n\npub fn build(b: *std.Build) void {\n    const target = b.standardTargetOptions(.{});\n    const optimize = b.standardOptimizeOption(.{});\n\n    addApp(b, "server", "src/server.zig", target, optimize);\n    addApp(b, "client", "src/client.zig", target, optimize);\n    addApp(b, "admin", "src/admin.zig", target, optimize);\n}`, hints: ['Extract common addExecutable + installArtifact into a function.', 'The helper takes the build, name, source path, target, and optimize.', 'build.zig is just Zig code - normal functions work.'], concepts: ['helper-functions', 'DRY', 'build-refactoring'] },
  ],
};
