import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-packed',
  title: '27. Packed Structs',
  explanation: `## Packed Structs

Packed structs give precise control over memory layout at the bit level. Fields are packed tightly without padding, making them ideal for hardware registers, protocol headers, and binary formats.

### Declaration
\`\`\`zig
const Flags = packed struct {
    read: bool,     // 1 bit
    write: bool,    // 1 bit
    exec: bool,     // 1 bit
    _reserved: u5,  // 5 bits padding
};
// Total: exactly 1 byte (8 bits)
\`\`\`

### @bitCast
\`\`\`zig
const raw: u8 = 0b00000101;
const flags: Flags = @bitCast(raw);
// flags.read == true, flags.write == false, flags.exec == true
\`\`\`

### @bitSizeOf
\`\`\`zig
@bitSizeOf(Flags) // 8
@sizeOf(Flags)    // 1 (rounded to bytes)
\`\`\`

### Packed Unions
\`\`\`zig
const Register = packed union {
    full: u16,
    halves: packed struct { lo: u8, hi: u8 },
};
\`\`\`

### Endianness
\`\`\`zig
const Header = packed struct(u32) {
    version: u4,
    ihl: u4,
    dscp: u6,
    ecn: u2,
    total_length: u16,
};
\`\`\``,
  exercises: [
    { id: 'zig-packed-1', title: 'Declare Packed Struct', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Declare a basic packed struct with bit fields.', skeleton: `const Flags = ___ struct {\n    enabled: bool,\n    priority: u3,\n    mode: u4,\n};`, solution: `const Flags = packed struct {\n    enabled: bool,\n    priority: u3,\n    mode: u4,\n};`, hints: ['The keyword packed before struct removes padding.', 'bool occupies 1 bit in a packed struct.', 'u3 occupies exactly 3 bits.'], concepts: ['packed-struct', 'bit-fields'] },
    { id: 'zig-packed-2', title: '@bitCast to Packed', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Convert a raw integer to a packed struct.', skeleton: `const Nibbles = packed struct {\n    lo: u4,\n    hi: u4,\n};\n\nconst raw: u8 = 0xAB;\nconst n: Nibbles = ___(raw);`, solution: `const Nibbles = packed struct {\n    lo: u4,\n    hi: u4,\n};\n\nconst raw: u8 = 0xAB;\nconst n: Nibbles = @bitCast(raw);`, hints: ['@bitCast reinterprets bits without conversion.', 'The source and destination must have the same bit size.', 'u8 and a packed struct of 8 bits are compatible.'], concepts: ['bitCast', 'type-punning'] },
    { id: 'zig-packed-3', title: '@bitSizeOf Packed Struct', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Get the bit size of a packed struct.', skeleton: `const Color = packed struct {\n    r: u5,\n    g: u6,\n    b: u5,\n};\n\nconst bits = @___(Color); // 16`, solution: `const Color = packed struct {\n    r: u5,\n    g: u6,\n    b: u5,\n};\n\nconst bits = @bitSizeOf(Color); // 16`, hints: ['@bitSizeOf returns size in bits, not bytes.', '5 + 6 + 5 = 16 bits.', '@sizeOf would return 2 (bytes).'], concepts: ['bitSizeOf', 'size-calculation'] },
    { id: 'zig-packed-4', title: 'Packed Struct Backing Integer', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Specify the backing integer type for a packed struct.', skeleton: `const IpFlags = packed struct(___) {\n    reserved: u1,\n    dont_fragment: u1,\n    more_fragments: u1,\n    fragment_offset: u13,\n};`, solution: `const IpFlags = packed struct(u16) {\n    reserved: u1,\n    dont_fragment: u1,\n    more_fragments: u1,\n    fragment_offset: u13,\n};`, hints: ['The backing integer specifies the total bit width.', '1 + 1 + 1 + 13 = 16 bits = u16.', 'This enables direct @bitCast from u16.'], concepts: ['backing-integer', 'packed-struct'] },
    { id: 'zig-packed-5', title: '@bitCast Packed to Int', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Convert a packed struct back to an integer.', skeleton: `const Perm = packed struct {\n    read: bool,\n    write: bool,\n    exec: bool,\n    _pad: u5,\n};\n\nconst p = Perm{ .read = true, .write = true, .exec = false, ._pad = 0 };\nconst raw: u8 = ___(p);`, solution: `const Perm = packed struct {\n    read: bool,\n    write: bool,\n    exec: bool,\n    _pad: u5,\n};\n\nconst p = Perm{ .read = true, .write = true, .exec = false, ._pad = 0 };\nconst raw: u8 = @bitCast(p);`, hints: ['@bitCast works in both directions.', 'Packed struct to integer reinterprets the bits.', 'The integer type must match the bit size.'], concepts: ['bitCast', 'serialization'] },
    { id: 'zig-packed-6', title: 'Packed with Reserved Bits', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Use underscore-prefixed fields for reserved bits.', skeleton: `const StatusReg = packed struct(u8) {\n    carry: bool,\n    zero: bool,\n    negative: bool,\n    overflow: bool,\n    ___: u4,  // reserved, must fill to 8 bits\n};`, solution: `const StatusReg = packed struct(u8) {\n    carry: bool,\n    zero: bool,\n    negative: bool,\n    overflow: bool,\n    _reserved: u4,  // reserved, must fill to 8 bits\n};`, hints: ['Reserved fields are conventionally prefixed with underscore.', 'They still occupy bits in the packed layout.', 'The total must match the backing integer size.'], concepts: ['reserved-bits', 'hardware-registers'] },
    { id: 'zig-packed-7', title: 'Write Hardware Register', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a packed struct modeling an 8-bit UART control register.', skeleton: `// Write a packed struct UartControl (u8 backing) with fields:\n// - baud_select: u3 (bits 0-2)\n// - parity_enable: bool (bit 3)\n// - parity_odd: bool (bit 4)\n// - stop_bits: u1 (bit 5)\n// - break_ctrl: bool (bit 6)\n// - dlab: bool (bit 7)\n// Then write fn fromByte(byte: u8) UartControl that converts.`, solution: `const UartControl = packed struct(u8) {\n    baud_select: u3,\n    parity_enable: bool,\n    parity_odd: bool,\n    stop_bits: u1,\n    break_ctrl: bool,\n    dlab: bool,\n};\n\nfn fromByte(byte: u8) UartControl {\n    return @bitCast(byte);\n}`, hints: ['Fields are ordered from LSB to MSB.', '3 + 1 + 1 + 1 + 1 + 1 = 8 bits.', '@bitCast converts the raw byte to the struct.'], concepts: ['hardware-register', 'UART', 'bitCast'] },
    { id: 'zig-packed-8', title: 'Write Protocol Header', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a packed struct for a network protocol header.', skeleton: `// Write a packed struct PacketHeader (u32 backing) with:\n// - version: u4\n// - header_len: u4\n// - service_type: u8\n// - total_len: u16\n// Write fn parse(raw: u32) PacketHeader\n// Write fn serialize(hdr: PacketHeader) u32`, solution: `const PacketHeader = packed struct(u32) {\n    version: u4,\n    header_len: u4,\n    service_type: u8,\n    total_len: u16,\n};\n\nfn parse(raw: u32) PacketHeader {\n    return @bitCast(raw);\n}\n\nfn serialize(hdr: PacketHeader) u32 {\n    return @bitCast(hdr);\n}`, hints: ['4 + 4 + 8 + 16 = 32 bits.', '@bitCast works for both parse and serialize.', 'The backing integer u32 ensures the correct total size.'], concepts: ['protocol-header', 'serialization', 'bitCast'] },
    { id: 'zig-packed-9', title: 'Write Packed RGB Color', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write packed struct and conversion functions for RGB565 color format.', skeleton: `// Write a packed struct Rgb565 (u16 backing) with:\n// - r: u5, g: u6, b: u5\n// Write fn fromU16(val: u16) Rgb565\n// Write fn toU16(c: Rgb565) u16\n// Write fn toRgb8(c: Rgb565) struct { r: u8, g: u8, b: u8 }\n//   that scales each channel to 0-255`, solution: `const Rgb565 = packed struct(u16) {\n    r: u5,\n    g: u6,\n    b: u5,\n};\n\nfn fromU16(val: u16) Rgb565 {\n    return @bitCast(val);\n}\n\nfn toU16(c: Rgb565) u16 {\n    return @bitCast(c);\n}\n\nfn toRgb8(c: Rgb565) struct { r: u8, g: u8, b: u8 } {\n    return .{\n        .r = @as(u8, c.r) << 3 | @as(u8, c.r) >> 2,\n        .g = @as(u8, c.g) << 2 | @as(u8, c.g) >> 4,\n        .b = @as(u8, c.b) << 3 | @as(u8, c.b) >> 2,\n    };\n}`, hints: ['RGB565 is a common display color format.', 'Scaling u5 to u8: shift left 3 and fill low bits.', 'Scaling u6 to u8: shift left 2 and fill low bits.'], concepts: ['color-format', 'bit-manipulation', 'packed-struct'] },
    { id: 'zig-packed-10', title: 'Write Bit Field Extraction', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a function that extracts fields from a packed instruction.', skeleton: `// Given this RISC-V-like packed instruction:\nconst Instruction = packed struct(u32) {\n    opcode: u7,\n    rd: u5,\n    funct3: u3,\n    rs1: u5,\n    rs2: u5,\n    funct7: u7,\n};\n// Write fn decode(raw: u32) Instruction\n// Write fn isAdd(inst: Instruction) bool\n//   returns true if opcode==0x33, funct3==0, funct7==0`, solution: `const Instruction = packed struct(u32) {\n    opcode: u7,\n    rd: u5,\n    funct3: u3,\n    rs1: u5,\n    rs2: u5,\n    funct7: u7,\n};\n\nfn decode(raw: u32) Instruction {\n    return @bitCast(raw);\n}\n\nfn isAdd(inst: Instruction) bool {\n    return inst.opcode == 0x33 and inst.funct3 == 0 and inst.funct7 == 0;\n}`, hints: ['@bitCast splits the u32 into fields.', 'Fields in packed structs can be compared directly.', 'and is the boolean operator in Zig.'], concepts: ['instruction-decoding', 'RISC-V', 'packed-struct'] },
    { id: 'zig-packed-11', title: 'Write Packed Union', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a packed union for accessing a 16-bit value as bytes.', skeleton: `// Write a packed union Word that overlays:\n// - full: u16 (the whole value)\n// - bytes: packed struct { lo: u8, hi: u8 }\n// Write fn splitWord(val: u16) struct { lo: u8, hi: u8 }\n//   using the union`, solution: `const Word = packed union {\n    full: u16,\n    bytes: packed struct { lo: u8, hi: u8 },\n};\n\nfn splitWord(val: u16) struct { lo: u8, hi: u8 } {\n    const w = Word{ .full = val };\n    return .{ .lo = w.bytes.lo, .hi = w.bytes.hi };\n}`, hints: ['Packed unions overlay fields at the same bit position.', 'Setting .full and reading .bytes reinterprets the bits.', 'This is similar to type punning in C.'], concepts: ['packed-union', 'type-punning', 'byte-splitting'] },
    { id: 'zig-packed-12', title: 'Write Endian-Aware Struct', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write functions that handle network byte order with packed structs.', skeleton: `const std = @import("std");\n\nconst NetHeader = packed struct(u32) {\n    src_port: u16,\n    dst_port: u16,\n};\n\n// Write fn fromNetwork(raw: u32) NetHeader\n//   converts from big-endian network order to native\n// Write fn toNetwork(hdr: NetHeader) u32\n//   converts from native to big-endian`, solution: `const std = @import("std");\n\nconst NetHeader = packed struct(u32) {\n    src_port: u16,\n    dst_port: u16,\n};\n\nfn fromNetwork(raw: u32) NetHeader {\n    const native = std.mem.bigToNative(u32, raw);\n    return @bitCast(native);\n}\n\nfn toNetwork(hdr: NetHeader) u32 {\n    const native: u32 = @bitCast(hdr);\n    return std.mem.nativeToBig(u32, native);\n}`, hints: ['Network byte order is big-endian.', 'std.mem.bigToNative converts big-endian to host order.', 'Convert endianness before/after @bitCast.'], concepts: ['endianness', 'network-byte-order', 'std.mem'] },
    { id: 'zig-packed-13', title: 'Fix Packed Struct Size', type: 'fix-bug', difficulty: 'beginner', language: 'zig', goal: 'Fix a packed struct whose fields do not sum to the backing integer.', skeleton: `const Register = packed struct(u8) {\n    mode: u3,\n    enable: bool,\n    irq: bool,\n    // Bug: total is 5 bits, not 8\n};`, solution: `const Register = packed struct(u8) {\n    mode: u3,\n    enable: bool,\n    irq: bool,\n    _reserved: u3,\n};`, hints: ['3 + 1 + 1 = 5 bits, but u8 needs 8.', 'Add a reserved field to fill the remaining 3 bits.', 'Use _reserved: u3 for the padding.'], concepts: ['packed-struct-size', 'padding', 'reserved-bits'] },
    { id: 'zig-packed-14', title: 'Fix @bitCast Type Mismatch', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix a bitCast between mismatched sizes.', skeleton: `const Flags = packed struct {\n    a: bool,\n    b: bool,\n    c: bool,\n};\n\nfn toFlags(val: u8) Flags {\n    // Bug: Flags is 3 bits, not 8\n    return @bitCast(val);\n}`, solution: `const Flags = packed struct {\n    a: bool,\n    b: bool,\n    c: bool,\n};\n\nfn toFlags(val: u8) Flags {\n    const truncated: u3 = @truncate(val);\n    return @bitCast(truncated);\n}`, hints: ['Flags is only 3 bits but val is 8 bits.', '@truncate narrows the integer first.', '@bitCast requires matching bit sizes.'], concepts: ['bitCast', 'truncate', 'size-mismatch'] },
    { id: 'zig-packed-15', title: 'Fix Packed Pointer Alignment', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix taking a pointer to a packed struct field.', skeleton: `const Data = packed struct {\n    x: u4,\n    y: u4,\n    z: u8,\n};\n\nfn getZ(d: *Data) *u8 {\n    // Bug: cannot take address of packed struct field\n    return &d.z;\n}`, solution: `const Data = packed struct {\n    x: u4,\n    y: u4,\n    z: u8,\n};\n\nfn getZ(d: *Data) u8 {\n    return d.z;\n}`, hints: ['You cannot take the address of a field in a packed struct.', 'Packed fields may not be byte-aligned.', 'Return the value directly instead of a pointer.'], concepts: ['packed-pointer-restriction', 'alignment'] },
    { id: 'zig-packed-16', title: 'Predict Packed Bits', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the integer value of a packed struct.', skeleton: `const Bits = packed struct(u8) {\n    a: u4,\n    b: u4,\n};\n\nconst v = Bits{ .a = 0xA, .b = 0x5 };\nconst raw: u8 = @bitCast(v);\n// What is raw in hex?`, solution: `0x5A`, hints: ['Field a occupies the low 4 bits.', 'Field b occupies the high 4 bits.', '0xA in low nibble, 0x5 in high nibble = 0x5A.'], concepts: ['bit-layout', 'bitCast'] },
    { id: 'zig-packed-17', title: 'Predict Packed Bool Layout', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the byte value of packed booleans.', skeleton: `const Flags = packed struct(u8) {\n    a: bool,\n    b: bool,\n    c: bool,\n    d: bool,\n    e: bool,\n    f: bool,\n    g: bool,\n    h: bool,\n};\n\nconst f = Flags{ .a = true, .b = false, .c = true, .d = false, .e = false, .f = false, .g = false, .h = false };\nconst val: u8 = @bitCast(f);\n// What is val?`, solution: `5`, hints: ['Bit 0 (a) = 1, bit 1 (b) = 0, bit 2 (c) = 1.', 'All other bits are 0.', '0b00000101 = 5.'], concepts: ['bool-to-bit', 'packed-layout'] },
    { id: 'zig-packed-18', title: 'Predict @bitSizeOf', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the bit size of a packed struct.', skeleton: `const Mixed = packed struct {\n    flag: bool,\n    count: u7,\n    tag: u3,\n    value: u13,\n};\n\n// What is @bitSizeOf(Mixed)?`, solution: `24`, hints: ['1 + 7 + 3 + 13 = 24 bits.', 'Each field contributes exactly its declared bit width.', '@sizeOf would return 3 (bytes).'], concepts: ['bitSizeOf', 'size-calculation'] },
    { id: 'zig-packed-19', title: 'Refactor Bitmask to Packed', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor manual bitmask operations to use a packed struct.', skeleton: `fn getPermissions(raw: u8) struct { read: bool, write: bool, exec: bool } {\n    return .{\n        .read = (raw & 0x01) != 0,\n        .write = (raw & 0x02) != 0,\n        .exec = (raw & 0x04) != 0,\n    };\n}\n\nfn setPermissions(read: bool, write: bool, exec: bool) u8 {\n    var result: u8 = 0;\n    if (read) result |= 0x01;\n    if (write) result |= 0x02;\n    if (exec) result |= 0x04;\n    return result;\n}`, solution: `const Permissions = packed struct(u8) {\n    read: bool,\n    write: bool,\n    exec: bool,\n    _reserved: u5,\n};\n\nfn getPermissions(raw: u8) Permissions {\n    return @bitCast(raw);\n}\n\nfn setPermissions(read: bool, write: bool, exec: bool) u8 {\n    return @bitCast(Permissions{\n        .read = read,\n        .write = write,\n        .exec = exec,\n        ._reserved = 0,\n    });\n}`, hints: ['A packed struct replaces manual bit manipulation.', '@bitCast handles the conversion in both directions.', 'Named fields are more readable than bitmasks.'], concepts: ['bitmask-to-packed', 'refactoring', 'readability'] },
    { id: 'zig-packed-20', title: 'Refactor Separate Fields to Packed', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor separate u8 fields to a single packed u32 for cache efficiency.', skeleton: `const Particle = struct {\n    x: u8,\n    y: u8,\n    r: u8,\n    g: u8,\n    b: u8,\n    alpha: u8,\n    flags: u8,\n    layer: u8,\n};\n\nfn createParticle(x: u8, y: u8, r: u8, g: u8) Particle {\n    return Particle{\n        .x = x, .y = y,\n        .r = r, .g = g,\n        .b = 255, .alpha = 255,\n        .flags = 0, .layer = 0,\n    };\n}`, solution: `const Particle = packed struct(u64) {\n    x: u8,\n    y: u8,\n    r: u8,\n    g: u8,\n    b: u8,\n    alpha: u8,\n    flags: u8,\n    layer: u8,\n};\n\nfn createParticle(x: u8, y: u8, r: u8, g: u8) Particle {\n    return Particle{\n        .x = x, .y = y,\n        .r = r, .g = g,\n        .b = 255, .alpha = 255,\n        .flags = 0, .layer = 0,\n    };\n}`, hints: ['Eight u8 fields = 64 bits = u64 backing.', 'Packed struct eliminates any struct padding.', 'A single u64 fits in one cache line read.'], concepts: ['cache-efficiency', 'packed-layout', 'data-oriented'] },
  ],
};
