import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-vec',
  title: '28. SIMD Vectors',
  explanation: `## SIMD Vectors

Zig has first-class SIMD vector types via \`@Vector\`. These map directly to hardware SIMD instructions (SSE, AVX, NEON) for high-performance parallel computation.

### Declaration
\`\`\`zig
const Vec4f = @Vector(4, f32);
const a = Vec4f{ 1.0, 2.0, 3.0, 4.0 };
const b = Vec4f{ 5.0, 6.0, 7.0, 8.0 };
const c = a + b; // { 6.0, 8.0, 10.0, 12.0 }
\`\`\`

### @splat
\`\`\`zig
const scale: Vec4f = @splat(2.0);
const result = a * scale; // { 2.0, 4.0, 6.0, 8.0 }
\`\`\`

### @reduce
\`\`\`zig
const sum = @reduce(.Add, a); // 1.0 + 2.0 + 3.0 + 4.0 = 10.0
const max = @reduce(.Max, a); // 4.0
\`\`\`

### @shuffle
\`\`\`zig
const v = Vec4f{ 1.0, 2.0, 3.0, 4.0 };
const reversed = @shuffle(f32, v, undefined, [4]i32{ 3, 2, 1, 0 });
// { 4.0, 3.0, 2.0, 1.0 }
\`\`\`

### Loading from Arrays
\`\`\`zig
const arr = [8]f32{ 1, 2, 3, 4, 5, 6, 7, 8 };
const vec: @Vector(4, f32) = arr[0..4].*;
\`\`\``,
  exercises: [
    { id: 'zig-vec-1', title: 'Declare a Vector', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Declare a SIMD vector type.', skeleton: `const Vec4i = @___(4, i32);`, solution: `const Vec4i = @Vector(4, i32);`, hints: ['@Vector takes a lane count and element type.', 'The first argument is the number of lanes.', 'The second argument is the scalar type.'], concepts: ['Vector', 'SIMD-type'] },
    { id: 'zig-vec-2', title: 'Vector Addition', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Add two vectors element-wise.', skeleton: `const Vec = @Vector(4, f32);\nconst a = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst b = Vec{ 10.0, 20.0, 30.0, 40.0 };\nconst c = a ___ b;`, solution: `const Vec = @Vector(4, f32);\nconst a = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst b = Vec{ 10.0, 20.0, 30.0, 40.0 };\nconst c = a + b;`, hints: ['Vectors support all arithmetic operators.', 'Addition is element-wise.', 'c = { 11.0, 22.0, 33.0, 44.0 }.'], concepts: ['vector-arithmetic', 'element-wise'] },
    { id: 'zig-vec-3', title: '@splat a Scalar', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Broadcast a scalar to all vector lanes.', skeleton: `const Vec = @Vector(4, f32);\nconst v = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst scale: Vec = @___(3.0);\nconst result = v * scale;`, solution: `const Vec = @Vector(4, f32);\nconst v = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst scale: Vec = @splat(3.0);\nconst result = v * scale;`, hints: ['@splat fills all lanes with the same value.', 'The result type is inferred from context.', 'result = { 3.0, 6.0, 9.0, 12.0 }.'], concepts: ['splat', 'broadcast'] },
    { id: 'zig-vec-4', title: '@reduce Sum', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Reduce a vector to a single sum.', skeleton: `const Vec = @Vector(4, i32);\nconst v = Vec{ 10, 20, 30, 40 };\nconst total = @reduce(.___, v);`, solution: `const Vec = @Vector(4, i32);\nconst v = Vec{ 10, 20, 30, 40 };\nconst total = @reduce(.Add, v);`, hints: ['@reduce with .Add sums all lanes.', 'total = 10 + 20 + 30 + 40 = 100.', 'Other options include .Min, .Max, .Mul.'], concepts: ['reduce', 'horizontal-sum'] },
    { id: 'zig-vec-5', title: '@shuffle Reverse', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Reverse vector elements using @shuffle.', skeleton: `const Vec = @Vector(4, f32);\nconst v = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst rev = @shuffle(f32, v, undefined, [4]i32{ ___, ___, ___, ___ });`, solution: `const Vec = @Vector(4, f32);\nconst v = Vec{ 1.0, 2.0, 3.0, 4.0 };\nconst rev = @shuffle(f32, v, undefined, [4]i32{ 3, 2, 1, 0 });`, hints: ['@shuffle indices select from the source vector.', 'Index 3 selects the last element.', 'Reversed indices: 3, 2, 1, 0.'], concepts: ['shuffle', 'permutation'] },
    { id: 'zig-vec-6', title: 'Vector Comparison', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Compare vectors to get a boolean mask.', skeleton: `const Vec = @Vector(4, i32);\nconst a = Vec{ 1, 5, 3, 8 };\nconst threshold: Vec = @splat(4);\nconst mask = a ___ threshold; // true where a > threshold`, solution: `const Vec = @Vector(4, i32);\nconst a = Vec{ 1, 5, 3, 8 };\nconst threshold: Vec = @splat(4);\nconst mask = a > threshold; // true where a > threshold`, hints: ['Vector comparisons produce a @Vector(N, bool).', 'Each lane is compared independently.', 'mask = { false, true, false, true }.'], concepts: ['vector-comparison', 'mask'] },
    { id: 'zig-vec-7', title: 'Write Vector Dot Product', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a dot product function using SIMD vectors.', skeleton: `// Write fn dot(a: @Vector(4, f32), b: @Vector(4, f32)) f32\n// that computes the dot product: sum of element-wise products`, solution: `fn dot(a: @Vector(4, f32), b: @Vector(4, f32)) f32 {\n    return @reduce(.Add, a * b);\n}`, hints: ['Multiply element-wise first.', 'Then reduce with .Add to sum all lanes.', 'a * b gives element-wise products.'], concepts: ['dot-product', 'reduce', 'vector-multiply'] },
    { id: 'zig-vec-8', title: 'Write Vector Clamp', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a function that clamps vector values between min and max.', skeleton: `// Write fn clamp(v: @Vector(4, f32), lo: f32, hi: f32) @Vector(4, f32)\n// that clamps each lane to [lo, hi]`, solution: `fn clamp(v: @Vector(4, f32), lo: f32, hi: f32) @Vector(4, f32) {\n    const lo_vec: @Vector(4, f32) = @splat(lo);\n    const hi_vec: @Vector(4, f32) = @splat(hi);\n    return @min(@max(v, lo_vec), hi_vec);\n}`, hints: ['@splat broadcasts min/max to vectors.', '@max clamps the lower bound.', '@min clamps the upper bound.'], concepts: ['clamp', 'splat', 'min-max'] },
    { id: 'zig-vec-9', title: 'Write Vector Normalize', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a function that normalizes a 4D vector to unit length.', skeleton: `const std = @import("std");\n\n// Write fn normalize(v: @Vector(4, f32)) @Vector(4, f32)\n// Compute length = sqrt(dot(v, v)), divide each component by length`, solution: `fn normalize(v: @Vector(4, f32)) @Vector(4, f32) {\n    const dot_val = @reduce(.Add, v * v);\n    const len: @Vector(4, f32) = @splat(@sqrt(dot_val));\n    return v / len;\n}`, hints: ['Dot product with itself gives squared length.', '@sqrt computes the square root.', '@splat the length to divide all lanes.'], concepts: ['normalization', 'vector-math', 'sqrt'] },
    { id: 'zig-vec-10', title: 'Write Array to Vector Load', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a function that loads a vector from an array slice.', skeleton: `// Write fn loadVec(arr: []const f32) @Vector(4, f32)\n// Load first 4 elements from the array into a vector\n// Assume arr.len >= 4`, solution: `fn loadVec(arr: []const f32) @Vector(4, f32) {\n    return arr[0..4].*;\n}`, hints: ['Array slicing with .* dereferences to a fixed-size array.', 'arr[0..4] gets a *[4]f32 pointer.', 'Vectors can be initialized from fixed-size arrays.'], concepts: ['vector-load', 'array-to-vector'] },
    { id: 'zig-vec-11', title: 'Write Vector Store to Array', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a function that stores a vector back into an array.', skeleton: `// Write fn storeVec(vec: @Vector(4, f32), arr: []f32) void\n// Store the 4 vector lanes into arr[0..4]`, solution: `fn storeVec(vec: @Vector(4, f32), arr: []f32) void {\n    arr[0..4].* = vec;\n}`, hints: ['Assigning a vector to arr[0..4].* stores the elements.', 'The slice must have at least 4 elements.', 'This is the inverse of loading.'], concepts: ['vector-store', 'vector-to-array'] },
    { id: 'zig-vec-12', title: 'Write SIMD Sum of Array', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a function that sums an array using SIMD vectors.', skeleton: `// Write fn simdSum(data: []const f32) f32\n// Process 4 elements at a time using @Vector(4, f32)\n// Handle the remainder with scalar addition\n// Assume data.len may not be a multiple of 4`, solution: `fn simdSum(data: []const f32) f32 {\n    const Vec4 = @Vector(4, f32);\n    var acc: Vec4 = @splat(0.0);\n    var i: usize = 0;\n\n    while (i + 4 <= data.len) : (i += 4) {\n        const chunk: Vec4 = data[i..][0..4].*;\n        acc += chunk;\n    }\n\n    var total = @reduce(.Add, acc);\n\n    while (i < data.len) : (i += 1) {\n        total += data[i];\n    }\n\n    return total;\n}`, hints: ['Process chunks of 4 with vector ops.', 'Accumulate into a vector, then reduce at the end.', 'Handle remaining elements with scalar loop.'], concepts: ['SIMD-loop', 'vectorized-sum', 'remainder-handling'] },
    { id: 'zig-vec-13', title: 'Fix Vector Type Mismatch', type: 'fix-bug', difficulty: 'beginner', language: 'zig', goal: 'Fix a vector operation with mismatched types.', skeleton: `const Vec4f = @Vector(4, f32);\nconst Vec4i = @Vector(4, i32);\n\nfn scale(v: Vec4f) Vec4f {\n    const factor = Vec4i{ 2, 2, 2, 2 };\n    // Bug: cannot multiply f32 vector by i32 vector\n    return v * factor;\n}`, solution: `const Vec4f = @Vector(4, f32);\n\nfn scale(v: Vec4f) Vec4f {\n    const factor: Vec4f = @splat(2.0);\n    return v * factor;\n}`, hints: ['Vector operations require matching element types.', 'Use @splat with a float literal instead.', 'f32 vector * f32 vector is valid.'], concepts: ['type-mismatch', 'vector-types'] },
    { id: 'zig-vec-14', title: 'Fix @reduce Operation', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix an incorrect reduce operation.', skeleton: `const Vec = @Vector(4, f32);\nconst v = Vec{ 3.0, 1.0, 4.0, 2.0 };\n\n// Bug: wants the minimum value but gets the sum\nconst min_val = @reduce(.Add, v);`, solution: `const Vec = @Vector(4, f32);\nconst v = Vec{ 3.0, 1.0, 4.0, 2.0 };\n\nconst min_val = @reduce(.Min, v);`, hints: ['.Add sums all elements, not finds minimum.', 'Use .Min to find the minimum value.', 'min_val should be 1.0.'], concepts: ['reduce-operations', 'Min-vs-Add'] },
    { id: 'zig-vec-15', title: 'Fix Shuffle Indices', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix out-of-bounds shuffle indices.', skeleton: `const Vec = @Vector(4, i32);\nconst v = Vec{ 10, 20, 30, 40 };\n\n// Bug: index 4 is out of bounds for a 4-element vector\nconst swapped = @shuffle(i32, v, undefined, [4]i32{ 2, 3, 4, 1 });`, solution: `const Vec = @Vector(4, i32);\nconst v = Vec{ 10, 20, 30, 40 };\n\nconst swapped = @shuffle(i32, v, undefined, [4]i32{ 2, 3, 0, 1 });`, hints: ['Valid indices for a 4-element vector are 0-3.', 'Index 4 is out of bounds.', 'Use index 0 instead of 4.'], concepts: ['shuffle-indices', 'bounds'] },
    { id: 'zig-vec-16', title: 'Predict Vector Result', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the result of vector operations.', skeleton: `const Vec = @Vector(4, i32);\nconst a = Vec{ 1, 2, 3, 4 };\nconst b = Vec{ 4, 3, 2, 1 };\nconst c = a + b;\n// What is @reduce(.Add, c)?`, solution: `20`, hints: ['c = { 5, 5, 5, 5 }.', 'Sum of all lanes: 5 + 5 + 5 + 5 = 20.', '@reduce(.Add, ...) sums all elements.'], concepts: ['vector-add', 'reduce'] },
    { id: 'zig-vec-17', title: 'Predict @splat Multiply', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the result of splat and multiply.', skeleton: `const Vec = @Vector(4, i32);\nconst v = Vec{ 2, 4, 6, 8 };\nconst s: Vec = @splat(3);\nconst r = v * s;\n// What is @reduce(.Max, r)?`, solution: `24`, hints: ['r = { 6, 12, 18, 24 }.', '@reduce(.Max, ...) finds the maximum.', 'Max of { 6, 12, 18, 24 } = 24.'], concepts: ['splat', 'reduce-max'] },
    { id: 'zig-vec-18', title: 'Predict @shuffle Result', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the result of a shuffle operation.', skeleton: `const Vec = @Vector(4, i32);\nconst v = Vec{ 10, 20, 30, 40 };\nconst s = @shuffle(i32, v, undefined, [4]i32{ 1, 1, 3, 3 });\n// What are the elements of s?`, solution: `{ 20, 20, 40, 40 }`, hints: ['Index 1 selects the second element (20).', 'Index 3 selects the fourth element (40).', 'Repeated indices duplicate elements.'], concepts: ['shuffle', 'duplication'] },
    { id: 'zig-vec-19', title: 'Refactor Scalar to SIMD', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor a scalar distance calculation to use SIMD.', skeleton: `fn distance(ax: f32, ay: f32, az: f32, aw: f32, bx: f32, by: f32, bz: f32, bw: f32) f32 {\n    const dx = ax - bx;\n    const dy = ay - by;\n    const dz = az - bz;\n    const dw = aw - bw;\n    return @sqrt(dx * dx + dy * dy + dz * dz + dw * dw);\n}`, solution: `fn distance(a: @Vector(4, f32), b: @Vector(4, f32)) f32 {\n    const d = a - b;\n    return @sqrt(@reduce(.Add, d * d));\n}`, hints: ['Pack 4 components into vectors.', 'Subtract vectors, then compute dot product with self.', '@reduce(.Add, d * d) gives the squared distance.'], concepts: ['SIMD-refactor', 'distance', 'dot-product'] },
    { id: 'zig-vec-20', title: 'Refactor Loop to SIMD', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor a scalar multiply-add loop to use SIMD.', skeleton: `fn multiplyAdd(a: []const f32, b: []const f32, c: f32, out: []f32) void {\n    for (a, b, out) |av, bv, *ov| {\n        ov.* = av * bv + c;\n    }\n}`, solution: `fn multiplyAdd(a: []const f32, b: []const f32, c: f32, out: []f32) void {\n    const Vec4 = @Vector(4, f32);\n    const cv: Vec4 = @splat(c);\n    var i: usize = 0;\n\n    while (i + 4 <= a.len) : (i += 4) {\n        const av: Vec4 = a[i..][0..4].*;\n        const bv: Vec4 = b[i..][0..4].*;\n        out[i..][0..4].* = av * bv + cv;\n    }\n\n    while (i < a.len) : (i += 1) {\n        out[i] = a[i] * b[i] + c;\n    }\n}`, hints: ['Process 4 elements at a time.', '@splat the scalar c to a vector.', 'Handle remaining elements with a scalar loop.'], concepts: ['SIMD-loop', 'multiply-add', 'vectorization'] },
  ],
};
