import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-async',
  title: '29. Async',
  explanation: `## Async

Zig's async model is based on suspend/resume semantics. Async functions can suspend execution and be resumed later, enabling cooperative multitasking without OS threads. Note: async is being reworked in Zig; this covers the design principles and patterns.

### Async Functions
\`\`\`zig
fn fetchData(url: []const u8) ![]u8 {
    // When called with 'async', this function can suspend
    const socket = try openSocket(url);
    defer socket.close();

    suspend {} // yield control back to caller

    return try socket.read();
}
\`\`\`

### Async Frames
\`\`\`zig
var frame = async fetchData("http://example.com");
// ... do other work ...
const result = try await frame;
\`\`\`

### nosuspend
\`\`\`zig
// Assert that a function will not actually suspend
const result = nosuspend fetchData("cached://local");
\`\`\`

### Event Loop Integration
\`\`\`zig
const loop = std.event.Loop.instance orelse return;
loop.run();
\`\`\`

### Key Concepts
- Async functions allocate their frame on the caller's stack
- \`suspend\` yields control; \`resume\` continues execution
- \`await\` blocks until an async operation completes
- No hidden allocations or system threads involved`,
  exercises: [
    { id: 'zig-async-1', title: 'Suspend Point', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Use suspend to yield execution.', skeleton: `fn generator() void {\n    // Yield control to the caller\n    ___ {}\n    // Execution resumes here\n}`, solution: `fn generator() void {\n    // Yield control to the caller\n    suspend {}\n    // Execution resumes here\n}`, hints: ['suspend yields control back.', 'The empty block {} means no cleanup on suspend.', 'resume will continue from after the suspend.'], concepts: ['suspend', 'cooperative-multitasking'] },
    { id: 'zig-async-2', title: 'Resume an Async Frame', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Resume a suspended async frame.', skeleton: `fn work() void {\n    suspend {}\n}\n\nfn driver() void {\n    var frame = async work();\n    // Continue the suspended function\n    ___(frame);\n}`, solution: `fn work() void {\n    suspend {}\n}\n\nfn driver() void {\n    var frame = async work();\n    // Continue the suspended function\n    resume(frame);\n}`, hints: ['resume continues a suspended frame.', 'The frame was created with async.', 'resume takes the frame as its argument.'], concepts: ['resume', 'async-frame'] },
    { id: 'zig-async-3', title: 'Await an Async Result', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Await the result of an async function.', skeleton: `fn compute() i32 {\n    suspend {}\n    return 42;\n}\n\nfn caller() i32 {\n    var frame = async compute();\n    // Get the return value\n    return ___ frame;\n}`, solution: `fn compute() i32 {\n    suspend {}\n    return 42;\n}\n\nfn caller() i32 {\n    var frame = async compute();\n    // Get the return value\n    return await frame;\n}`, hints: ['await waits for and returns the result.', 'It blocks until the async function completes.', 'The return type matches the async function.'], concepts: ['await', 'async-result'] },
    { id: 'zig-async-4', title: 'nosuspend Assertion', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Use nosuspend to assert no suspension occurs.', skeleton: `fn maybeAsync(cached: bool) i32 {\n    if (!cached) {\n        suspend {}\n    }\n    return 42;\n}\n\nfn caller() i32 {\n    // We know it wont suspend because cached=true\n    return ___ maybeAsync(true);\n}`, solution: `fn maybeAsync(cached: bool) i32 {\n    if (!cached) {\n        suspend {}\n    }\n    return 42;\n}\n\nfn caller() i32 {\n    // We know it wont suspend because cached=true\n    return nosuspend maybeAsync(true);\n}`, hints: ['nosuspend asserts the function will not suspend.', 'If it does suspend, it is safety-checked undefined behavior.', 'Use when you know the async path will not be taken.'], concepts: ['nosuspend', 'safety-assertion'] },
    { id: 'zig-async-5', title: 'Async with Error Union', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Handle errors from an async function.', skeleton: `fn fetchData() ![]const u8 {\n    suspend {}\n    return error.NetworkError;\n}\n\nfn caller() void {\n    var frame = async fetchData();\n    const result = ___ frame catch |err| {\n        _ = err;\n        return;\n    };\n    _ = result;\n}`, solution: `fn fetchData() ![]const u8 {\n    suspend {}\n    return error.NetworkError;\n}\n\nfn caller() void {\n    var frame = async fetchData();\n    const result = await frame catch |err| {\n        _ = err;\n        return;\n    };\n    _ = result;\n}`, hints: ['await returns the error union.', 'catch handles the error case.', 'The pattern is: await frame catch |err| { ... }.'], concepts: ['async-errors', 'await-catch'] },
    { id: 'zig-async-6', title: 'Suspend with Cleanup', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Perform work in a suspend block.', skeleton: `fn asyncOp(handle: *anyframe) void {\n    ___ {\n        // Register this frame for later resumption\n        handle.* = @frame();\n    }\n    // Continues when resumed\n}`, solution: `fn asyncOp(handle: *anyframe) void {\n    suspend {\n        // Register this frame for later resumption\n        handle.* = @frame();\n    }\n    // Continues when resumed\n}`, hints: ['The suspend block executes before yielding.', '@frame() gets the current async frame.', 'Store the frame so someone else can resume it.'], concepts: ['suspend-block', 'frame-registration'] },
    { id: 'zig-async-7', title: 'Write Async Producer', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write an async function that produces values via suspend points.', skeleton: `// Write fn producer(output: *i32) void that:\n// 1. Sets output to 1, then suspends\n// 2. Sets output to 2, then suspends\n// 3. Sets output to 3`, solution: `fn producer(output: *i32) void {\n    output.* = 1;\n    suspend {}\n    output.* = 2;\n    suspend {}\n    output.* = 3;\n}`, hints: ['Each suspend point yields to the caller.', 'The caller resumes to get the next value.', 'output is modified between suspensions.'], concepts: ['generator-pattern', 'suspend-resume'] },
    { id: 'zig-async-8', title: 'Write Async Channel Pattern', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a simple one-shot channel using async.', skeleton: `// Write a Channel struct that:\n// 1. Has value: ?i32 and frame: ?anyframe fields\n// 2. fn send(self: *Channel, val: i32) void - stores value and resumes waiter\n// 3. fn recv(self: *Channel) i32 - suspends until value available`, solution: `const Channel = struct {\n    value: ?i32 = null,\n    frame: ?anyframe = null,\n\n    fn send(self: *Channel, val: i32) void {\n        self.value = val;\n        if (self.frame) |f| {\n            resume f;\n        }\n    }\n\n    fn recv(self: *Channel) i32 {\n        if (self.value) |v| return v;\n        suspend {\n            self.frame = @frame();\n        }\n        return self.value.?;\n    }\n};`, hints: ['recv suspends if no value is available.', 'send stores the value and resumes the waiter.', 'Store @frame() in the suspend block.'], concepts: ['channel', 'async-coordination'] },
    { id: 'zig-async-9', title: 'Write Async Timer Pattern', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write an async function that models a timer callback pattern.', skeleton: `// Write a Timer struct with:\n// 1. callback: ?*const fn() void field\n// 2. fn schedule(self: *Timer, cb: *const fn() void) void - stores callback, suspends\n// 3. fn fire(self: *Timer) void - calls callback if set`, solution: `const Timer = struct {\n    callback: ?*const fn () void = null,\n    waiting_frame: ?anyframe = null,\n\n    fn schedule(self: *Timer, cb: *const fn () void) void {\n        self.callback = cb;\n        suspend {\n            self.waiting_frame = @frame();\n        }\n    }\n\n    fn fire(self: *Timer) void {\n        if (self.callback) |cb| {\n            cb();\n        }\n        if (self.waiting_frame) |f| {\n            resume f;\n        }\n    }\n};`, hints: ['schedule stores the callback and suspends.', 'fire calls the callback and resumes the waiter.', 'Store @frame() so fire can resume.'], concepts: ['timer-pattern', 'callback', 'async'] },
    { id: 'zig-async-10', title: 'Write Async Fan-Out', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a pattern that launches multiple async operations.', skeleton: `// Write fn fanOut(a: *i32, b: *i32) void that:\n// 1. Starts two async computations in parallel\n// 2. fn taskA(out: *i32) void sets out to 10 after suspend\n// 3. fn taskB(out: *i32) void sets out to 20 after suspend\n// 4. Awaits both results`, solution: `fn taskA(out: *i32) void {\n    suspend {}\n    out.* = 10;\n}\n\nfn taskB(out: *i32) void {\n    suspend {}\n    out.* = 20;\n}\n\nfn fanOut(a: *i32, b: *i32) void {\n    var frame_a = async taskA(a);\n    var frame_b = async taskB(b);\n    await frame_a;\n    await frame_b;\n}`, hints: ['Start both tasks with async.', 'Each task suspends independently.', 'await both frames to collect results.'], concepts: ['fan-out', 'parallel-async', 'await'] },
    { id: 'zig-async-11', title: 'Write Async Pipeline', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a two-stage async pipeline.', skeleton: `// Write:\n// fn stage1(input: i32) i32 - suspends then returns input * 2\n// fn stage2(input: i32) i32 - suspends then returns input + 10\n// fn pipeline(val: i32) i32 - chains stage1 into stage2 using async/await`, solution: `fn stage1(input: i32) i32 {\n    suspend {}\n    return input * 2;\n}\n\nfn stage2(input: i32) i32 {\n    suspend {}\n    return input + 10;\n}\n\nfn pipeline(val: i32) i32 {\n    var frame1 = async stage1(val);\n    const mid = await frame1;\n    var frame2 = async stage2(mid);\n    return await frame2;\n}`, hints: ['Start stage1, await its result.', 'Pass the result to stage2.', 'The pipeline chains async operations sequentially.'], concepts: ['pipeline', 'async-chaining'] },
    { id: 'zig-async-12', title: 'Write Cancellable Async', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write an async pattern with cancellation support.', skeleton: `// Write a CancellableTask struct with:\n// 1. cancelled: bool field\n// 2. result: ?i32 field\n// 3. fn run(self: *CancellableTask) void - checks cancelled at each suspend\n// 4. fn cancel(self: *CancellableTask) void - sets cancelled`, solution: `const CancellableTask = struct {\n    cancelled: bool = false,\n    result: ?i32 = null,\n    frame: ?anyframe = null,\n\n    fn run(self: *CancellableTask) void {\n        suspend {\n            self.frame = @frame();\n        }\n        if (self.cancelled) return;\n\n        // Do some work\n        self.result = 42;\n\n        suspend {\n            self.frame = @frame();\n        }\n        if (self.cancelled) return;\n\n        self.result = 84;\n    }\n\n    fn cancel(self: *CancellableTask) void {\n        self.cancelled = true;\n        if (self.frame) |f| {\n            resume f;\n        }\n    }\n};`, hints: ['Check cancelled after each resume.', 'Return early if cancelled.', 'cancel sets the flag and resumes to trigger the check.'], concepts: ['cancellation', 'cooperative-cancel'] },
    { id: 'zig-async-13', title: 'Fix Missing Await', type: 'fix-bug', difficulty: 'beginner', language: 'zig', goal: 'Fix code that forgets to await an async result.', skeleton: `fn compute() i32 {\n    suspend {}\n    return 42;\n}\n\nfn main() void {\n    // Bug: frame is never awaited, result is lost\n    var frame = async compute();\n    _ = frame;\n}`, solution: `fn compute() i32 {\n    suspend {}\n    return 42;\n}\n\nfn main() void {\n    var frame = async compute();\n    const result = await frame;\n    _ = result;\n}`, hints: ['An async frame must be awaited to get its result.', 'Without await, the result is discarded.', 'await also ensures the function completes.'], concepts: ['await', 'resource-leak'] },
    { id: 'zig-async-14', title: 'Fix Double Resume', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix code that resumes an already completed frame.', skeleton: `fn task(flag: *bool) void {\n    suspend {}\n    flag.* = true;\n}\n\nfn driver() void {\n    var done = false;\n    var frame = async task(&done);\n    resume frame; // First resume - OK\n    // Bug: frame already completed, second resume is UB\n    resume frame;\n}`, solution: `fn task(flag: *bool) void {\n    suspend {}\n    flag.* = true;\n}\n\nfn driver() void {\n    var done = false;\n    var frame = async task(&done);\n    resume frame; // First resume - OK\n    // Frame is done after resume, do not resume again\n}`, hints: ['A completed frame cannot be resumed.', 'Resuming a completed frame is undefined behavior.', 'Remove the second resume call.'], concepts: ['double-resume', 'undefined-behavior'] },
    { id: 'zig-async-15', title: 'Fix Async Frame Lifetime', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix an async frame that outlives its stack.', skeleton: `fn startTask() anyframe {\n    // Bug: frame is on this function's stack\n    var frame = async longRunningTask();\n    return &frame; // Dangling pointer when startTask returns\n}\n\nfn longRunningTask() void {\n    suspend {}\n}`, solution: `var global_frame: @Frame(longRunningTask) = undefined;\n\nfn startTask() *anyframe {\n    global_frame = async longRunningTask();\n    return &global_frame;\n}\n\nfn longRunningTask() void {\n    suspend {}\n}`, hints: ['Async frames live on the stack of the calling function.', 'When startTask returns, its stack is gone.', 'Store the frame in longer-lived storage.'], concepts: ['frame-lifetime', 'stack-safety'] },
    { id: 'zig-async-16', title: 'Predict Suspend Order', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the order of operations with suspend/resume.', skeleton: `const std = @import("std");\n\nvar log: [4]u8 = undefined;\nvar idx: usize = 0;\n\nfn task() void {\n    log[idx] = 'B'; idx += 1;\n    suspend {}\n    log[idx] = 'D'; idx += 1;\n}\n\nfn main() void {\n    log[idx] = 'A'; idx += 1;\n    var frame = async task();\n    log[idx] = 'C'; idx += 1;\n    resume frame;\n    // What is log?\n}`, solution: `ABCD`, hints: ['A runs first, then task starts with B.', 'Task suspends, main continues with C.', 'resume continues task with D.'], concepts: ['execution-order', 'suspend-resume'] },
    { id: 'zig-async-17', title: 'Predict nosuspend Behavior', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict what happens with nosuspend on a non-suspending path.', skeleton: `fn conditional(do_suspend: bool) i32 {\n    if (do_suspend) suspend {}\n    return 42;\n}\n\nfn main() void {\n    const a = nosuspend conditional(false);\n    // What is a?\n    // Does this crash?`, solution: `a = 42, no crash`, hints: ['nosuspend is safe if the function does not actually suspend.', 'do_suspend is false, so the suspend is skipped.', 'The function returns 42 normally.'], concepts: ['nosuspend', 'conditional-suspend'] },
    { id: 'zig-async-18', title: 'Predict Multiple Suspends', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict values produced by multiple suspend points.', skeleton: `fn counter(out: *i32) void {\n    out.* = 1;\n    suspend {}\n    out.* = 2;\n    suspend {}\n    out.* = 3;\n}\n\n// After async start, out = ?\n// After first resume, out = ?\n// After second resume, out = ?`, solution: `After async start: 1\nAfter first resume: 2\nAfter second resume: 3`, hints: ['The function runs to the first suspend, setting 1.', 'First resume continues to second suspend, setting 2.', 'Second resume runs to completion, setting 3.'], concepts: ['multi-suspend', 'generator'] },
    { id: 'zig-async-19', title: 'Refactor Callback to Async', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor a callback-based API to async/await.', skeleton: `const Callback = *const fn (result: i32) void;\n\nfn fetchWithCallback(id: i32, cb: Callback) void {\n    // Simulate async: immediately call callback\n    cb(id * 10);\n}\n\nfn handleResult(result: i32) void {\n    _ = result;\n}\n\nfn main() void {\n    fetchWithCallback(5, handleResult);\n}`, solution: `fn fetch(id: i32) i32 {\n    suspend {}\n    return id * 10;\n}\n\nfn main() void {\n    var frame = async fetch(5);\n    const result = await frame;\n    _ = result;\n}`, hints: ['Replace the callback parameter with a return value.', 'Use suspend where the async work would happen.', 'await replaces the callback invocation.'], concepts: ['callback-to-async', 'refactoring'] },
    { id: 'zig-async-20', title: 'Refactor Sequential to Parallel Async', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor sequential async calls to run in parallel.', skeleton: `fn fetchUser(id: i32) i32 {\n    suspend {}\n    return id;\n}\n\nfn fetchPosts(user_id: i32) i32 {\n    suspend {}\n    return user_id * 10;\n}\n\n// Sequential: total time = time(user) + time(posts)\nfn loadPage(id: i32) struct { user: i32, posts: i32 } {\n    var frame1 = async fetchUser(id);\n    const user = await frame1;\n    var frame2 = async fetchPosts(id);\n    const posts = await frame2;\n    return .{ .user = user, .posts = posts };\n}`, solution: `fn fetchUser(id: i32) i32 {\n    suspend {}\n    return id;\n}\n\nfn fetchPosts(user_id: i32) i32 {\n    suspend {}\n    return user_id * 10;\n}\n\n// Parallel: total time = max(time(user), time(posts))\nfn loadPage(id: i32) struct { user: i32, posts: i32 } {\n    var frame1 = async fetchUser(id);\n    var frame2 = async fetchPosts(id);\n    const user = await frame1;\n    const posts = await frame2;\n    return .{ .user = user, .posts = posts };\n}`, hints: ['Start both async operations before awaiting either.', 'Launch both with async, then await both.', 'This allows them to run concurrently.'], concepts: ['parallel-async', 'concurrency', 'refactoring'] },
  ],
};
