import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-thread',
  title: '30. Threads',
  explanation: `## Threads

Zig provides OS-level threading via \`std.Thread\`. Threads enable true parallelism on multi-core systems, unlike async which is cooperative.

### Spawning Threads
\`\`\`zig
const std = @import("std");

fn worker(id: usize) void {
    std.debug.print("Worker {d} running\\n", .{id});
}

pub fn main() !void {
    const handle = try std.Thread.spawn(.{}, worker, .{1});
    handle.join();
}
\`\`\`

### Thread Configuration
\`\`\`zig
const handle = try std.Thread.spawn(.{
    .stack_size = 1024 * 1024, // 1MB stack
}, worker, .{1});
\`\`\`

### Thread Pool
\`\`\`zig
var pool: std.Thread.Pool = undefined;
try pool.init(.{ .allocator = allocator, .n_jobs = 4 });
defer pool.deinit();

pool.spawn(worker, .{1});
\`\`\`

### Mutexes
\`\`\`zig
var mutex = std.Thread.Mutex{};
mutex.lock();
defer mutex.unlock();
// critical section
\`\`\`

### Thread-Local Storage
\`\`\`zig
threadlocal var counter: u32 = 0;
\`\`\``,
  exercises: [
    { id: 'zig-thread-1', title: 'Spawn a Thread', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Spawn a thread using std.Thread.', skeleton: `const std = @import("std");\n\nfn worker() void {\n    std.debug.print("Hello from thread\\n", .{});\n}\n\npub fn main() !void {\n    const handle = try std.Thread.___(. {}, worker, .{});\n    handle.join();\n}`, solution: `const std = @import("std");\n\nfn worker() void {\n    std.debug.print("Hello from thread\\n", .{});\n}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{}, worker, .{});\n    handle.join();\n}`, hints: ['std.Thread.spawn creates a new OS thread.', 'First arg is config, second is function, third is args tuple.', 'join() waits for the thread to complete.'], concepts: ['Thread.spawn', 'join'] },
    { id: 'zig-thread-2', title: 'Join a Thread', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Wait for a thread to finish.', skeleton: `const std = @import("std");\n\nfn work() void {}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{}, work, .{});\n    handle.___();\n}`, solution: `const std = @import("std");\n\nfn work() void {}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{}, work, .{});\n    handle.join();\n}`, hints: ['join() blocks until the thread completes.', 'Without join, main might exit before the thread finishes.', 'join also cleans up thread resources.'], concepts: ['join', 'thread-lifecycle'] },
    { id: 'zig-thread-3', title: 'Thread with Arguments', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Pass arguments to a thread function.', skeleton: `const std = @import("std");\n\nfn worker(id: usize, multiplier: u32) void {\n    _ = id;\n    _ = multiplier;\n}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{}, worker, .{ 1, ___ });\n    handle.join();\n}`, solution: `const std = @import("std");\n\nfn worker(id: usize, multiplier: u32) void {\n    _ = id;\n    _ = multiplier;\n}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{}, worker, .{ 1, 10 });\n    handle.join();\n}`, hints: ['Arguments are passed as a tuple in the third parameter.', 'The tuple must match the function signature.', 'Any u32 value works for the multiplier.'], concepts: ['thread-arguments', 'spawn-tuple'] },
    { id: 'zig-thread-4', title: 'Mutex Lock/Unlock', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Use a mutex to protect a critical section.', skeleton: `const std = @import("std");\n\nvar mutex = std.Thread.Mutex{};\nvar counter: u64 = 0;\n\nfn increment() void {\n    mutex.___();\n    defer mutex.___();\n    counter += 1;\n}`, solution: `const std = @import("std");\n\nvar mutex = std.Thread.Mutex{};\nvar counter: u64 = 0;\n\nfn increment() void {\n    mutex.lock();\n    defer mutex.unlock();\n    counter += 1;\n}`, hints: ['lock() acquires the mutex.', 'unlock() releases it.', 'defer ensures unlock happens even on error.'], concepts: ['mutex', 'critical-section', 'defer'] },
    { id: 'zig-thread-5', title: 'Thread-Local Storage', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Declare a thread-local variable.', skeleton: `___ var tls_counter: u32 = 0;\n\nfn threadWork() void {\n    tls_counter += 1; // Each thread has its own copy\n}`, solution: `threadlocal var tls_counter: u32 = 0;\n\nfn threadWork() void {\n    tls_counter += 1; // Each thread has its own copy\n}`, hints: ['threadlocal makes each thread get its own copy.', 'Changes in one thread do not affect others.', 'threadlocal replaces var for the declaration.'], concepts: ['threadlocal', 'thread-local-storage'] },
    { id: 'zig-thread-6', title: 'Custom Stack Size', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Spawn a thread with a custom stack size.', skeleton: `const std = @import("std");\n\nfn worker() void {}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{\n        .___ = 4 * 1024 * 1024, // 4MB\n    }, worker, .{});\n    handle.join();\n}`, solution: `const std = @import("std");\n\nfn worker() void {}\n\npub fn main() !void {\n    const handle = try std.Thread.spawn(.{\n        .stack_size = 4 * 1024 * 1024, // 4MB\n    }, worker, .{});\n    handle.join();\n}`, hints: ['stack_size sets the thread stack size in bytes.', 'The default is usually the OS default (often 8MB).', 'Increase for deeply recursive functions.'], concepts: ['stack-size', 'thread-config'] },
    { id: 'zig-thread-7', title: 'Write Thread Pool Work', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write code that spawns multiple threads to process work items.', skeleton: `const std = @import("std");\n\n// Write fn processItems(items: []const i32, results: []i32) !void\n// Spawns one thread per item, each computes item * item\n// Joins all threads when done`, solution: `const std = @import("std");\n\nfn processItems(items: []const i32, results: []i32) !void {\n    var handles: [64]std.Thread = undefined;\n    const n = items.len;\n\n    for (0..n) |i| {\n        handles[i] = try std.Thread.spawn(.{}, struct {\n            fn work(res: []i32, idx: usize, val: i32) void {\n                res[idx] = val * val;\n            }\n        }.work, .{ results, i, items[i] });\n    }\n\n    for (0..n) |i| {\n        handles[i].join();\n    }\n}`, hints: ['Spawn one thread per work item.', 'Store handles to join later.', 'Each thread writes to its own index - no mutex needed.'], concepts: ['thread-pool', 'parallel-processing'] },
    { id: 'zig-thread-8', title: 'Write Mutex-Protected Counter', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a thread-safe counter using a mutex.', skeleton: `const std = @import("std");\n\n// Write a Counter struct with:\n// - value: u64 field\n// - mutex: std.Thread.Mutex field\n// - fn increment(self: *Counter) void - thread-safe increment\n// - fn get(self: *Counter) u64 - thread-safe read`, solution: `const std = @import("std");\n\nconst Counter = struct {\n    value: u64 = 0,\n    mutex: std.Thread.Mutex = .{},\n\n    fn increment(self: *Counter) void {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        self.value += 1;\n    }\n\n    fn get(self: *Counter) u64 {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        return self.value;\n    }\n};`, hints: ['Both read and write need mutex protection.', 'Use defer for unlock to ensure it always runs.', 'Initialize mutex with .{} for default.'], concepts: ['mutex', 'thread-safe-counter'] },
    { id: 'zig-thread-9', title: 'Write Condition Variable', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a producer-consumer pattern using condition variables.', skeleton: `const std = @import("std");\n\n// Write a SharedQueue struct with:\n// - items: [16]i32 buffer\n// - count: usize\n// - mutex: std.Thread.Mutex\n// - cond: std.Thread.Condition\n// - fn push(self: *SharedQueue, val: i32) void\n// - fn pop(self: *SharedQueue) i32`, solution: `const std = @import("std");\n\nconst SharedQueue = struct {\n    items: [16]i32 = undefined,\n    count: usize = 0,\n    mutex: std.Thread.Mutex = .{},\n    cond: std.Thread.Condition = .{},\n\n    fn push(self: *SharedQueue, val: i32) void {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        self.items[self.count] = val;\n        self.count += 1;\n        self.cond.signal();\n    }\n\n    fn pop(self: *SharedQueue) i32 {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        while (self.count == 0) {\n            self.cond.wait(&self.mutex);\n        }\n        self.count -= 1;\n        return self.items[self.count];\n    }\n};`, hints: ['push signals the condition after adding.', 'pop waits on condition when empty.', 'cond.wait releases the mutex while waiting.'], concepts: ['condition-variable', 'producer-consumer'] },
    { id: 'zig-thread-10', title: 'Write Thread-Safe ArrayList', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a thread-safe wrapper around ArrayList.', skeleton: `const std = @import("std");\n\n// Write a ThreadSafeList(T) that wraps std.ArrayList(T) with:\n// - inner: std.ArrayList(T)\n// - mutex: std.Thread.Mutex\n// - fn append(self: *@This(), item: T) !void\n// - fn len(self: *@This()) usize\n// - fn init(allocator: std.mem.Allocator) @This()`, solution: `const std = @import("std");\n\nfn ThreadSafeList(comptime T: type) type {\n    return struct {\n        inner: std.ArrayList(T),\n        mutex: std.Thread.Mutex = .{},\n\n        const Self = @This();\n\n        fn init(allocator: std.mem.Allocator) Self {\n            return .{\n                .inner = std.ArrayList(T).init(allocator),\n            };\n        }\n\n        fn append(self: *Self, item: T) !void {\n            self.mutex.lock();\n            defer self.mutex.unlock();\n            try self.inner.append(item);\n        }\n\n        fn len(self: *Self) usize {\n            self.mutex.lock();\n            defer self.mutex.unlock();\n            return self.inner.items.len;\n        }\n    };\n}`, hints: ['Wrap each operation with lock/unlock.', 'Use comptime T for generic type parameter.', '@This() refers to the current struct type.'], concepts: ['generic-thread-safe', 'wrapper-pattern'] },
    { id: 'zig-thread-11', title: 'Write Parallel Map', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a function that applies a transformation in parallel.', skeleton: `const std = @import("std");\n\n// Write fn parallelMap(input: []const i32, output: []i32, n_threads: usize) !void\n// Divides work evenly across n_threads threads\n// Each thread applies: output[i] = input[i] * 2 + 1`, solution: `const std = @import("std");\n\nfn parallelMap(input: []const i32, output: []i32, n_threads: usize) !void {\n    var handles: [32]std.Thread = undefined;\n    const chunk_size = input.len / n_threads;\n\n    for (0..n_threads) |t| {\n        const start = t * chunk_size;\n        const end = if (t == n_threads - 1) input.len else start + chunk_size;\n        handles[t] = try std.Thread.spawn(.{}, struct {\n            fn work(inp: []const i32, out: []i32, s: usize, e: usize) void {\n                for (s..e) |i| {\n                    out[i] = inp[i] * 2 + 1;\n                }\n            }\n        }.work, .{ input, output, start, end });\n    }\n\n    for (0..n_threads) |t| {\n        handles[t].join();\n    }\n}`, hints: ['Divide the array into chunks per thread.', 'The last thread handles any remainder.', 'No mutex needed since threads write to disjoint regions.'], concepts: ['parallel-map', 'work-partitioning'] },
    { id: 'zig-thread-12', title: 'Write Detached Thread', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write code that spawns a detached background thread.', skeleton: `const std = @import("std");\n\n// Write fn startBackground(flag: *bool) !void\n// Spawns a thread that sets flag to true then detaches\n// The thread runs independently of the caller`, solution: `const std = @import("std");\n\nfn startBackground(flag: *bool) !void {\n    const handle = try std.Thread.spawn(.{}, struct {\n        fn work(f: *bool) void {\n            f.* = true;\n        }\n    }.work, .{flag});\n    handle.detach();\n}`, hints: ['detach() releases the handle without waiting.', 'The thread continues running independently.', 'Be careful with lifetimes of shared data.'], concepts: ['detach', 'background-thread'] },
    { id: 'zig-thread-13', title: 'Fix Data Race', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix a data race on a shared variable.', skeleton: `const std = @import("std");\n\nvar total: u64 = 0;\n\nfn addMany() void {\n    var i: u32 = 0;\n    while (i < 1000) : (i += 1) {\n        // Bug: data race - multiple threads writing without sync\n        total += 1;\n    }\n}\n\npub fn main() !void {\n    var threads: [4]std.Thread = undefined;\n    for (&threads) |*t| {\n        t.* = try std.Thread.spawn(.{}, addMany, .{});\n    }\n    for (threads) |t| t.join();\n}`, solution: `const std = @import("std");\n\nvar total: u64 = 0;\nvar mutex = std.Thread.Mutex{};\n\nfn addMany() void {\n    var i: u32 = 0;\n    while (i < 1000) : (i += 1) {\n        mutex.lock();\n        total += 1;\n        mutex.unlock();\n    }\n}\n\npub fn main() !void {\n    var threads: [4]std.Thread = undefined;\n    for (&threads) |*t| {\n        t.* = try std.Thread.spawn(.{}, addMany, .{});\n    }\n    for (threads) |t| t.join();\n}`, hints: ['Multiple threads modifying total without synchronization.', 'Add a mutex to protect the shared variable.', 'Lock before write, unlock after.'], concepts: ['data-race', 'mutex-fix'] },
    { id: 'zig-thread-14', title: 'Fix Missing Join', type: 'fix-bug', difficulty: 'beginner', language: 'zig', goal: 'Fix a program that exits before threads complete.', skeleton: `const std = @import("std");\n\nvar results: [4]i32 = undefined;\n\nfn compute(idx: usize) void {\n    results[idx] = @intCast(idx * 10);\n}\n\npub fn main() !void {\n    var threads: [4]std.Thread = undefined;\n    for (0..4) |i| {\n        threads[i] = try std.Thread.spawn(.{}, compute, .{i});\n    }\n    // Bug: main exits without joining threads\n    // results may be incomplete\n}`, solution: `const std = @import("std");\n\nvar results: [4]i32 = undefined;\n\nfn compute(idx: usize) void {\n    results[idx] = @intCast(idx * 10);\n}\n\npub fn main() !void {\n    var threads: [4]std.Thread = undefined;\n    for (0..4) |i| {\n        threads[i] = try std.Thread.spawn(.{}, compute, .{i});\n    }\n    for (threads) |t| {\n        t.join();\n    }\n}`, hints: ['Without join, main exits and kills threads.', 'Join all threads to ensure completion.', 'Join blocks until each thread finishes.'], concepts: ['join', 'thread-completion'] },
    { id: 'zig-thread-15', title: 'Fix Deadlock', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix a deadlock caused by lock ordering.', skeleton: `const std = @import("std");\n\nvar mutex_a = std.Thread.Mutex{};\nvar mutex_b = std.Thread.Mutex{};\n\nfn thread1() void {\n    mutex_a.lock();\n    // ... some work ...\n    mutex_b.lock();\n    defer mutex_b.unlock();\n    defer mutex_a.unlock();\n}\n\nfn thread2() void {\n    // Bug: opposite lock order causes deadlock\n    mutex_b.lock();\n    // ... some work ...\n    mutex_a.lock();\n    defer mutex_a.unlock();\n    defer mutex_b.unlock();\n}`, solution: `const std = @import("std");\n\nvar mutex_a = std.Thread.Mutex{};\nvar mutex_b = std.Thread.Mutex{};\n\nfn thread1() void {\n    mutex_a.lock();\n    defer mutex_a.unlock();\n    mutex_b.lock();\n    defer mutex_b.unlock();\n}\n\nfn thread2() void {\n    // Fixed: same lock order as thread1\n    mutex_a.lock();\n    defer mutex_a.unlock();\n    mutex_b.lock();\n    defer mutex_b.unlock();\n}`, hints: ['Deadlock occurs when two threads lock in opposite order.', 'Always acquire locks in the same global order.', 'Both threads should lock A first, then B.'], concepts: ['deadlock', 'lock-ordering'] },
    { id: 'zig-thread-16', title: 'Predict Thread Output', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the final value of a properly synchronized counter.', skeleton: `const std = @import("std");\n\nvar counter: u32 = 0;\nvar mutex = std.Thread.Mutex{};\n\nfn inc() void {\n    mutex.lock();\n    counter += 1;\n    mutex.unlock();\n}\n\n// 3 threads each call inc() once.\n// After all join, what is counter?`, solution: `3`, hints: ['Each thread increments counter by 1.', 'The mutex ensures no data race.', '3 threads * 1 increment = 3.'], concepts: ['synchronized-counter', 'mutex'] },
    { id: 'zig-thread-17', title: 'Predict threadlocal Behavior', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict values with thread-local storage.', skeleton: `threadlocal var x: u32 = 0;\n\nfn threadWork() void {\n    x += 1;\n    x += 1;\n}\n\n// Main thread: x = 0\n// Thread A calls threadWork()\n// Thread B calls threadWork()\n// After both join, what is main's x?`, solution: `0`, hints: ['threadlocal means each thread has its own copy.', 'Thread A and B modify their own copies.', 'Main thread x is unchanged.'], concepts: ['threadlocal', 'isolation'] },
    { id: 'zig-thread-18', title: 'Predict Join Order', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the guaranteed state after join.', skeleton: `var a: bool = false;\nvar b: bool = false;\n\nfn setA() void { a = true; }\nfn setB() void { b = true; }\n\n// Thread 1 runs setA, thread 2 runs setB\n// After joining both threads, what are a and b?`, solution: `a = true, b = true`, hints: ['join guarantees the thread has completed.', 'After join, all side effects are visible.', 'Both a and b will be set to true.'], concepts: ['join-guarantees', 'memory-visibility'] },
    { id: 'zig-thread-19', title: 'Refactor Global Mutex to Struct', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor global variables and mutex into a struct.', skeleton: `const std = @import("std");\n\nvar data: [100]i32 = undefined;\nvar data_len: usize = 0;\nvar data_mutex = std.Thread.Mutex{};\n\nfn addItem(val: i32) void {\n    data_mutex.lock();\n    defer data_mutex.unlock();\n    data[data_len] = val;\n    data_len += 1;\n}\n\nfn getLen() usize {\n    data_mutex.lock();\n    defer data_mutex.unlock();\n    return data_len;\n}`, solution: `const std = @import("std");\n\nconst SafeBuffer = struct {\n    data: [100]i32 = undefined,\n    len: usize = 0,\n    mutex: std.Thread.Mutex = .{},\n\n    fn addItem(self: *SafeBuffer, val: i32) void {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        self.data[self.len] = val;\n        self.len += 1;\n    }\n\n    fn getLen(self: *SafeBuffer) usize {\n        self.mutex.lock();\n        defer self.mutex.unlock();\n        return self.len;\n    }\n};`, hints: ['Encapsulate data, length, and mutex in a struct.', 'Methods take *SafeBuffer as self parameter.', 'This allows multiple independent instances.'], concepts: ['encapsulation', 'struct-methods'] },
    { id: 'zig-thread-20', title: 'Refactor Busy-Wait to Condition', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor a busy-wait loop to use a condition variable.', skeleton: `const std = @import("std");\n\nvar ready = false;\nvar mutex = std.Thread.Mutex{};\n\nfn waiter() void {\n    // Busy-wait wastes CPU\n    while (true) {\n        mutex.lock();\n        if (ready) {\n            mutex.unlock();\n            break;\n        }\n        mutex.unlock();\n        // Spins here burning CPU cycles\n    }\n}\n\nfn signaler() void {\n    mutex.lock();\n    ready = true;\n    mutex.unlock();\n}`, solution: `const std = @import("std");\n\nvar ready = false;\nvar mutex = std.Thread.Mutex{};\nvar cond = std.Thread.Condition{};\n\nfn waiter() void {\n    mutex.lock();\n    defer mutex.unlock();\n    while (!ready) {\n        cond.wait(&mutex);\n    }\n}\n\nfn signaler() void {\n    mutex.lock();\n    ready = true;\n    mutex.unlock();\n    cond.signal();\n}`, hints: ['Condition variables sleep instead of spinning.', 'wait() releases the mutex and blocks.', 'signal() wakes one waiting thread.'], concepts: ['condition-variable', 'busy-wait-elimination'] },
  ],
};
