import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-atomic',
  title: '31. Atomics',
  explanation: `## Atomics

Zig provides atomic operations via builtins for lock-free concurrent programming. Atomics guarantee that operations on shared variables are indivisible and properly ordered across threads.

### Atomic Load and Store
\`\`\`zig
var shared: u32 = 0;
const val = @atomicLoad(u32, &shared, .seq_cst);
@atomicStore(u32, &shared, 42, .seq_cst);
\`\`\`

### Atomic Read-Modify-Write
\`\`\`zig
const old = @atomicRmw(u32, &counter, .Add, 1, .seq_cst);
\`\`\`

### Compare and Exchange
\`\`\`zig
// Strong: may fail only if value != expected
const result = @cmpxchgStrong(u32, &val, expected, new_val, .seq_cst, .seq_cst);
// result is ?u32: null on success, actual value on failure
\`\`\`

### Memory Orderings
- \`.seq_cst\` - Sequential consistency (strongest, safest)
- \`.acquire\` - Loads: see all writes before the paired release
- \`.release\` - Stores: make all prior writes visible
- \`.monotonic\` - No ordering guarantees (weakest)
- \`.unordered\` - No atomicity guarantees

### Fence
\`\`\`zig
@fence(.acquire);  // Prevents reordering of subsequent loads
@fence(.release);  // Prevents reordering of prior stores
\`\`\``,
  exercises: [
    { id: 'zig-atomic-1', title: 'Atomic Load', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Read a shared variable atomically.', skeleton: `var shared: u32 = 42;\nconst val = @___(u32, &shared, .seq_cst);`, solution: `var shared: u32 = 42;\nconst val = @atomicLoad(u32, &shared, .seq_cst);`, hints: ['@atomicLoad reads a value atomically.', 'It takes the type, pointer, and memory ordering.', '.seq_cst is the safest ordering.'], concepts: ['atomicLoad', 'seq_cst'] },
    { id: 'zig-atomic-2', title: 'Atomic Store', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Write to a shared variable atomically.', skeleton: `var shared: u32 = 0;\n@___(u32, &shared, 100, .seq_cst);`, solution: `var shared: u32 = 0;\n@atomicStore(u32, &shared, 100, .seq_cst);`, hints: ['@atomicStore writes a value atomically.', 'Parameters: type, pointer, value, ordering.', 'This ensures the write is visible to other threads.'], concepts: ['atomicStore', 'atomic-write'] },
    { id: 'zig-atomic-3', title: 'Atomic Increment', type: 'fill-blank', difficulty: 'beginner', language: 'zig', goal: 'Atomically increment a counter.', skeleton: `var counter: u32 = 0;\nconst old = @atomicRmw(u32, &counter, .___, 1, .seq_cst);`, solution: `var counter: u32 = 0;\nconst old = @atomicRmw(u32, &counter, .Add, 1, .seq_cst);`, hints: ['@atomicRmw does read-modify-write atomically.', '.Add adds the value to the current value.', 'It returns the old value before the operation.'], concepts: ['atomicRmw', 'Add'] },
    { id: 'zig-atomic-4', title: 'Compare and Swap', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Use compare-and-swap to conditionally update a value.', skeleton: `var val: u32 = 10;\nconst result = @___(u32, &val, 10, 20, .seq_cst, .seq_cst);\n// result is null if swap succeeded`, solution: `var val: u32 = 10;\nconst result = @cmpxchgStrong(u32, &val, 10, 20, .seq_cst, .seq_cst);\n// result is null if swap succeeded`, hints: ['@cmpxchgStrong does an atomic compare-and-exchange.', 'If val == expected (10), it sets val to new (20).', 'Returns null on success, old value on failure.'], concepts: ['cmpxchgStrong', 'compare-and-swap'] },
    { id: 'zig-atomic-5', title: 'Acquire/Release Ordering', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Use acquire/release semantics for a flag.', skeleton: `var ready: bool = false;\nvar data: u32 = 0;\n\n// Writer thread:\ndata = 42;\n@atomicStore(bool, &ready, true, .___); // make data visible\n\n// Reader thread:\nif (@atomicLoad(bool, &ready, .___)) { // see the data write\n    const d = data; // guaranteed to see 42\n    _ = d;\n}`, solution: `var ready: bool = false;\nvar data: u32 = 0;\n\n// Writer thread:\ndata = 42;\n@atomicStore(bool, &ready, true, .release); // make data visible\n\n// Reader thread:\nif (@atomicLoad(bool, &ready, .acquire)) { // see the data write\n    const d = data; // guaranteed to see 42\n    _ = d;\n}`, hints: ['.release on store makes prior writes visible.', '.acquire on load sees all writes before the release.', 'This forms an acquire-release pair.'], concepts: ['acquire-release', 'memory-ordering'] },
    { id: 'zig-atomic-6', title: 'Atomic Fence', type: 'fill-blank', difficulty: 'intermediate', language: 'zig', goal: 'Insert a memory fence.', skeleton: `var a: u32 = 0;\nvar b: u32 = 0;\n\n// Ensure all writes before fence are visible\na = 1;\nb = 2;\n@___(.___);\n// Writes to a and b are now visible to acquiring threads`, solution: `var a: u32 = 0;\nvar b: u32 = 0;\n\n// Ensure all writes before fence are visible\na = 1;\nb = 2;\n@fence(.release);\n// Writes to a and b are now visible to acquiring threads`, hints: ['@fence creates a memory barrier.', '.release ensures prior writes are published.', 'Paired with .acquire fence on the reader side.'], concepts: ['fence', 'memory-barrier'] },
    { id: 'zig-atomic-7', title: 'Write Atomic Counter', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a lock-free atomic counter.', skeleton: `// Write an AtomicCounter struct with:\n// - value: u64 field\n// - fn increment(self: *AtomicCounter) void - atomic add 1\n// - fn decrement(self: *AtomicCounter) void - atomic sub 1\n// - fn get(self: *AtomicCounter) u64 - atomic read`, solution: `const AtomicCounter = struct {\n    value: u64 = 0,\n\n    fn increment(self: *AtomicCounter) void {\n        _ = @atomicRmw(u64, &self.value, .Add, 1, .seq_cst);\n    }\n\n    fn decrement(self: *AtomicCounter) void {\n        _ = @atomicRmw(u64, &self.value, .Sub, 1, .seq_cst);\n    }\n\n    fn get(self: *AtomicCounter) u64 {\n        return @atomicLoad(u64, &self.value, .seq_cst);\n    }\n};`, hints: ['@atomicRmw with .Add for increment.', '@atomicRmw with .Sub for decrement.', '@atomicLoad for reading the current value.'], concepts: ['atomic-counter', 'lock-free'] },
    { id: 'zig-atomic-8', title: 'Write Spinlock', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Implement a simple spinlock using atomics.', skeleton: `// Write a Spinlock struct with:\n// - locked: bool field (default false)\n// - fn lock(self: *Spinlock) void - spin until acquired\n// - fn unlock(self: *Spinlock) void - release the lock`, solution: `const Spinlock = struct {\n    locked: bool = false,\n\n    fn lock(self: *Spinlock) void {\n        while (@cmpxchgWeak(bool, &self.locked, false, true, .acquire, .monotonic) != null) {\n            // spin\n        }\n    }\n\n    fn unlock(self: *Spinlock) void {\n        @atomicStore(bool, &self.locked, false, .release);\n    }\n};`, hints: ['cmpxchgWeak tries to swap false->true atomically.', 'Loop until the swap succeeds (returns null).', 'Release ordering on unlock makes critical section visible.'], concepts: ['spinlock', 'cmpxchgWeak', 'acquire-release'] },
    { id: 'zig-atomic-9', title: 'Write Lock-Free Stack Push', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a lock-free push operation for a stack.', skeleton: `const Node = struct {\n    value: i32,\n    next: ?*Node,\n};\n\n// Write a LockFreeStack struct with:\n// - head: ?*Node field\n// - fn push(self: *LockFreeStack, node: *Node) void\n//   Uses CAS loop to atomically push onto the stack`, solution: `const Node = struct {\n    value: i32,\n    next: ?*Node,\n};\n\nconst LockFreeStack = struct {\n    head: ?*Node = null,\n\n    fn push(self: *LockFreeStack, node: *Node) void {\n        while (true) {\n            const current_head = @atomicLoad(?*Node, &self.head, .acquire);\n            node.next = current_head;\n            if (@cmpxchgWeak(?*Node, &self.head, current_head, node, .release, .monotonic) == null) {\n                break;\n            }\n        }\n    }\n};`, hints: ['Read current head, set node.next to it.', 'CAS: if head is still current_head, set it to node.', 'Retry if another thread modified head first.'], concepts: ['lock-free-stack', 'CAS-loop', 'ABA'] },
    { id: 'zig-atomic-10', title: 'Write Atomic Flag', type: 'write-function', difficulty: 'intermediate', language: 'zig', goal: 'Write a one-shot atomic flag for signaling between threads.', skeleton: `// Write an AtomicFlag struct with:\n// - flag: bool field (default false)\n// - fn set(self: *AtomicFlag) void - atomically set to true\n// - fn isSet(self: *AtomicFlag) bool - atomically read\n// - fn wait(self: *AtomicFlag) void - spin until set`, solution: `const AtomicFlag = struct {\n    flag: bool = false,\n\n    fn set(self: *AtomicFlag) void {\n        @atomicStore(bool, &self.flag, true, .release);\n    }\n\n    fn isSet(self: *AtomicFlag) bool {\n        return @atomicLoad(bool, &self.flag, .acquire);\n    }\n\n    fn wait(self: *AtomicFlag) void {\n        while (!@atomicLoad(bool, &self.flag, .acquire)) {\n            // spin\n        }\n    }\n};`, hints: ['Store with .release to publish.', 'Load with .acquire to observe.', 'wait spins on atomicLoad until true.'], concepts: ['atomic-flag', 'signal', 'spin-wait'] },
    { id: 'zig-atomic-11', title: 'Write Atomic Max', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write a function that atomically updates a max value.', skeleton: `// Write fn atomicMax(ptr: *u32, val: u32) u32\n// Atomically sets *ptr = max(*ptr, val)\n// Returns the previous value\n// Use a CAS loop`, solution: `fn atomicMax(ptr: *u32, val: u32) u32 {\n    while (true) {\n        const current = @atomicLoad(u32, ptr, .seq_cst);\n        if (val <= current) return current;\n        if (@cmpxchgWeak(u32, ptr, current, val, .seq_cst, .seq_cst) == null) {\n            return current;\n        }\n    }\n}`, hints: ['Load current value, compare with val.', 'If val is greater, try to swap it in.', 'Retry if another thread changed the value.'], concepts: ['CAS-loop', 'atomic-max'] },
    { id: 'zig-atomic-12', title: 'Write Reference Counter', type: 'write-function', difficulty: 'advanced', language: 'zig', goal: 'Write an atomic reference counter with release semantics.', skeleton: `const std = @import("std");\n\n// Write a RefCounted struct with:\n// - ref_count: u32 (starts at 1)\n// - fn retain(self: *RefCounted) void - atomic increment\n// - fn release(self: *RefCounted) bool - atomic decrement, returns true if last ref`, solution: `const RefCounted = struct {\n    ref_count: u32 = 1,\n\n    fn retain(self: *RefCounted) void {\n        _ = @atomicRmw(u32, &self.ref_count, .Add, 1, .monotonic);\n    }\n\n    fn release(self: *RefCounted) bool {\n        const prev = @atomicRmw(u32, &self.ref_count, .Sub, 1, .release);\n        if (prev == 1) {\n            @fence(.acquire);\n            return true;\n        }\n        return false;\n    }\n};`, hints: ['Retain uses .monotonic since it only needs atomicity.', 'Release uses .release to publish all prior writes.', 'The final release needs an acquire fence before cleanup.'], concepts: ['reference-counting', 'release-semantics', 'fence'] },
    { id: 'zig-atomic-13', title: 'Fix Wrong Atomic Ordering', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix incorrect memory ordering in a producer-consumer pattern.', skeleton: `var data: u32 = 0;\nvar flag: bool = false;\n\nfn producer() void {\n    data = 42;\n    // Bug: monotonic does not guarantee data is visible\n    @atomicStore(bool, &flag, true, .monotonic);\n}\n\nfn consumer() void {\n    // Bug: monotonic does not see the data write\n    while (!@atomicLoad(bool, &flag, .monotonic)) {}\n    const d = data; // May not see 42!\n    _ = d;\n}`, solution: `var data: u32 = 0;\nvar flag: bool = false;\n\nfn producer() void {\n    data = 42;\n    @atomicStore(bool, &flag, true, .release);\n}\n\nfn consumer() void {\n    while (!@atomicLoad(bool, &flag, .acquire)) {}\n    const d = data; // Guaranteed to see 42\n    _ = d;\n}`, hints: ['.monotonic provides no ordering guarantees.', 'Producer needs .release to publish data.', 'Consumer needs .acquire to observe data.'], concepts: ['memory-ordering-bug', 'acquire-release'] },
    { id: 'zig-atomic-14', title: 'Fix CAS Loop', type: 'fix-bug', difficulty: 'advanced', language: 'zig', goal: 'Fix a CAS loop that never terminates.', skeleton: `fn atomicAdd(ptr: *u32, val: u32) u32 {\n    var expected: u32 = 0; // Bug: never updates expected on failure\n    while (true) {\n        if (@cmpxchgStrong(u32, ptr, expected, expected + val, .seq_cst, .seq_cst) == null) {\n            return expected;\n        }\n    }\n}`, solution: `fn atomicAdd(ptr: *u32, val: u32) u32 {\n    while (true) {\n        const expected = @atomicLoad(u32, ptr, .seq_cst);\n        if (@cmpxchgStrong(u32, ptr, expected, expected + val, .seq_cst, .seq_cst) == null) {\n            return expected;\n        }\n    }\n}`, hints: ['Expected must be the actual current value.', 'Re-read the value each iteration with @atomicLoad.', 'If expected is wrong, cmpxchg always fails.'], concepts: ['CAS-loop-bug', 'atomicLoad'] },
    { id: 'zig-atomic-15', title: 'Fix Double Increment', type: 'fix-bug', difficulty: 'intermediate', language: 'zig', goal: 'Fix a non-atomic increment that causes lost updates.', skeleton: `var counter: u32 = 0;\n\nfn increment() void {\n    // Bug: read-modify-write is not atomic\n    const val = @atomicLoad(u32, &counter, .seq_cst);\n    @atomicStore(u32, &counter, val + 1, .seq_cst);\n}`, solution: `var counter: u32 = 0;\n\nfn increment() void {\n    _ = @atomicRmw(u32, &counter, .Add, 1, .seq_cst);\n}`, hints: ['Separate load and store is not atomic.', 'Another thread can modify counter between load and store.', '@atomicRmw makes the whole operation atomic.'], concepts: ['lost-update', 'atomicRmw'] },
    { id: 'zig-atomic-16', title: 'Predict atomicRmw Return', type: 'predict-output', difficulty: 'beginner', language: 'zig', goal: 'Predict the return value of atomicRmw.', skeleton: `var x: u32 = 10;\nconst old = @atomicRmw(u32, &x, .Add, 5, .seq_cst);\n// What is old? What is x now?`, solution: `old = 10, x = 15`, hints: ['@atomicRmw returns the value before the operation.', 'It then adds 5 to the value.', 'old = 10 (before), x = 15 (after).'], concepts: ['atomicRmw-return', 'old-value'] },
    { id: 'zig-atomic-17', title: 'Predict cmpxchg Result', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the result of a compare-and-exchange.', skeleton: `var val: u32 = 10;\nconst r1 = @cmpxchgStrong(u32, &val, 10, 20, .seq_cst, .seq_cst);\n// What is r1? What is val?\nconst r2 = @cmpxchgStrong(u32, &val, 10, 30, .seq_cst, .seq_cst);\n// What is r2? What is val?`, solution: `r1 = null, val = 20\nr2 = 20, val = 20`, hints: ['First CAS: val==10==expected, so swap to 20, return null.', 'Second CAS: val==20!=10, so fail.', 'On failure, returns the actual value (20).'], concepts: ['cmpxchg-result', 'success-failure'] },
    { id: 'zig-atomic-18', title: 'Predict Atomic Xor', type: 'predict-output', difficulty: 'intermediate', language: 'zig', goal: 'Predict the result of atomic XOR.', skeleton: `var flags: u8 = 0b11001010;\nconst old = @atomicRmw(u8, &flags, .Xor, 0b11110000, .seq_cst);\n// What is old? What is flags now?`, solution: `old = 0b11001010 (202), flags = 0b00111010 (58)`, hints: ['XOR flips bits where the mask has 1s.', '11001010 XOR 11110000 = 00111010.', 'old is the value before XOR.'], concepts: ['atomicRmw', 'Xor'] },
    { id: 'zig-atomic-19', title: 'Refactor Mutex to Atomics', type: 'refactor', difficulty: 'intermediate', language: 'zig', goal: 'Refactor a mutex-protected counter to use atomics.', skeleton: `const std = @import("std");\n\nvar counter: u64 = 0;\nvar mutex = std.Thread.Mutex{};\n\nfn add(val: u64) void {\n    mutex.lock();\n    defer mutex.unlock();\n    counter += val;\n}\n\nfn get() u64 {\n    mutex.lock();\n    defer mutex.unlock();\n    return counter;\n}`, solution: `var counter: u64 = 0;\n\nfn add(val: u64) void {\n    _ = @atomicRmw(u64, &counter, .Add, val, .seq_cst);\n}\n\nfn get() u64 {\n    return @atomicLoad(u64, &counter, .seq_cst);\n}`, hints: ['A simple counter does not need a mutex.', '@atomicRmw(.Add) replaces lock + add + unlock.', '@atomicLoad replaces lock + read + unlock.'], concepts: ['mutex-to-atomic', 'lock-free'] },
    { id: 'zig-atomic-20', title: 'Refactor Flag to Acquire-Release', type: 'refactor', difficulty: 'advanced', language: 'zig', goal: 'Refactor seq_cst atomics to acquire-release for better performance.', skeleton: `var data: [4]u32 = .{ 0, 0, 0, 0 };\nvar published: bool = false;\n\nfn writer() void {\n    data = .{ 1, 2, 3, 4 };\n    @atomicStore(bool, &published, true, .seq_cst);\n}\n\nfn reader() [4]u32 {\n    while (!@atomicLoad(bool, &published, .seq_cst)) {}\n    return data;\n}`, solution: `var data: [4]u32 = .{ 0, 0, 0, 0 };\nvar published: bool = false;\n\nfn writer() void {\n    data = .{ 1, 2, 3, 4 };\n    @atomicStore(bool, &published, true, .release);\n}\n\nfn reader() [4]u32 {\n    while (!@atomicLoad(bool, &published, .acquire)) {}\n    return data;\n}`, hints: ['seq_cst is stronger than needed here.', 'Writer needs .release to publish data.', 'Reader needs .acquire to see published data.'], concepts: ['ordering-relaxation', 'acquire-release', 'performance'] },
  ],
};
