import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-tuple',
  title: '39. Tuples',
  explanation: `## Tuples in Zig\n\nZig doesn't have a dedicated tuple type. Instead, **anonymous structs with numbered fields** serve as tuples. You access elements with \`.@"0"\`, \`.@"1"\`, etc.\n\n\`\`\`zig\nconst tuple = .{ 42, "hello", true };\nconst first = tuple.@"0";   // 42\nconst second = tuple.@"1";  // "hello"\n\`\`\`\n\nYou can destructure tuples in for loops and pass them to functions:\n\n\`\`\`zig\nconst pair = .{ 10, 20 };\n\n// Iteration over tuple fields at comptime\ninline for (pair) |val| {\n    std.debug.print("{} ", .{val});\n}\n\`\`\`\n\nTuples are anonymous struct literals -- \`@TypeOf(.{ 1, "hi" })\` is \`struct { comptime_int, *const [2:0]u8 }\`. You can use \`@typeInfo\` to inspect their fields at comptime.\n\n\`\`\`zig\nfn sum(args: anytype) i32 {\n    var total: i32 = 0;\n    inline for (args) |v| total += v;\n    return total;\n}\n\nconst result = sum(.{ 1, 2, 3 }); // 6\n\`\`\`\n\nTuples are a cornerstone of comptime metaprogramming in Zig, enabling variadic arguments, format strings, and more.`,
  exercises: [
    {
      id: 'zig-tuple-1',
      title: 'Create a Simple Tuple',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Create an anonymous struct tuple containing 10, 20, and 30.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const tuple = ___.{ 10, 20, 30 };\n    std.debug.print("{}", .{tuple.@"0"});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const tuple = .{ 10, 20, 30 };\n    std.debug.print("{}", .{tuple.@"0"});\n}`,
      hints: ['Tuples in Zig are anonymous struct literals.', 'The syntax for an anonymous struct is .{ ... }.', 'Remove the underscores and just use the dot.'],
      concepts: ['anonymous-structs', 'tuples'],
    },
    {
      id: 'zig-tuple-2',
      title: 'Access Tuple Element',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Access the second element (index 1) of the tuple.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ "hello", "world" };\n    const second = t.___;\n    std.debug.print("{s}", .{second});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ "hello", "world" };\n    const second = t.@"1";\n    std.debug.print("{s}", .{second});\n}`,
      hints: ['Tuple fields are accessed by stringified index.', 'Use the @"N" syntax for numbered fields.', 't.@"1" accesses the second element.'],
      concepts: ['tuple-access', 'field-syntax'],
    },
    {
      id: 'zig-tuple-3',
      title: 'Predict Tuple Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict what this code prints.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 5, 10, 15 };\n    std.debug.print("{}", .{t.@"0" + t.@"2"});\n}`,
      solution: `20`,
      hints: ['t.@"0" is 5 and t.@"2" is 15.', '5 + 15 = 20.', 'The print format "{}" prints the integer result.'],
      concepts: ['tuple-access', 'arithmetic'],
    },
    {
      id: 'zig-tuple-4',
      title: 'Tuple as Function Argument',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function that takes an anytype tuple and returns the sum of its first two i32 elements.',
      skeleton: `const std = @import("std");\n\n// Write a function sumFirst2 that takes an anytype parameter\n// and returns the sum of its .@"0" and .@"1" fields as i32\n`,
      solution: `const std = @import("std");\n\nfn sumFirst2(args: anytype) i32 {\n    return args.@"0" + args.@"1";\n}`,
      hints: ['Use anytype as the parameter type.', 'Access fields with .@"0" and .@"1".', 'Return type should be i32.'],
      concepts: ['anytype', 'tuple-access', 'functions'],
    },
    {
      id: 'zig-tuple-5',
      title: 'Tuple Iteration with Inline For',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Iterate over a tuple using inline for to print each element.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 1, 2, 3 };\n    ___ for (t) |val| {\n        std.debug.print("{} ", .{val});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 1, 2, 3 };\n    inline for (t) |val| {\n        std.debug.print("{} ", .{val});\n    }\n}`,
      hints: ['Tuples require comptime-known iteration.', 'Use inline for to unroll the loop at comptime.', 'inline for (t) |val| { ... }'],
      concepts: ['inline-for', 'tuple-iteration'],
    },
    {
      id: 'zig-tuple-6',
      title: 'Fix Tuple Access Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the syntax error in tuple field access.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 100, 200 };\n    const val = t.0;\n    std.debug.print("{}", .{val});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 100, 200 };\n    const val = t.@"0";\n    std.debug.print("{}", .{val});\n}`,
      hints: ['Numeric field access requires special syntax in Zig.', 'Use .@"N" to access numbered fields.', 'Change t.0 to t.@"0".'],
      concepts: ['tuple-access', 'syntax'],
    },
    {
      id: 'zig-tuple-7',
      title: 'Comptime Tuple Length',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that returns the number of fields in a tuple using @typeInfo.',
      skeleton: `const std = @import("std");\n\n// Write tupleLen that takes anytype and returns the number of fields\n`,
      solution: `const std = @import("std");\n\nfn tupleLen(tuple: anytype) usize {\n    const fields = @typeInfo(@TypeOf(tuple)).@"struct".fields;\n    return fields.len;\n}`,
      hints: ['Use @TypeOf to get the type of the tuple.', '@typeInfo returns a union with a .@"struct" field for structs.', 'The .fields array has a .len property.'],
      concepts: ['@typeInfo', '@TypeOf', 'comptime'],
    },
    {
      id: 'zig-tuple-8',
      title: 'Predict Tuple Type',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what the field count is.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ true, @as(u8, 42), "zig" };\n    const info = @typeInfo(@TypeOf(t)).@"struct";\n    std.debug.print("{}", .{info.fields.len});\n}`,
      solution: `3`,
      hints: ['Count the elements in the tuple literal.', 'true, 42, and "zig" are three elements.', 'fields.len gives the number of fields.'],
      concepts: ['@typeInfo', 'tuple-fields'],
    },
    {
      id: 'zig-tuple-9',
      title: 'Tuple Concatenation at Comptime',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a comptime function that concatenates two tuples into one using ++ operator.',
      skeleton: `const std = @import("std");\n\n// Write concatTuples that takes two anytype tuples\n// and returns a concatenated tuple using ++\n`,
      solution: `const std = @import("std");\n\nfn concatTuples(a: anytype, b: anytype) @TypeOf(a ++ b) {\n    return a ++ b;\n}`,
      hints: ['Zig supports ++ for tuple concatenation at comptime.', 'The return type can use @TypeOf(a ++ b).', 'Simply return a ++ b.'],
      concepts: ['tuple-concatenation', 'comptime', '@TypeOf'],
    },
    {
      id: 'zig-tuple-10',
      title: 'Fill Blank: Tuple in Format String',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Pass values as a tuple to std.debug.print.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const name = "Zig";\n    const version = 13;\n    std.debug.print("{s} version {}", ___{ name, version });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const name = "Zig";\n    const version = 13;\n    std.debug.print("{s} version {}", .{ name, version });\n}`,
      hints: ['Format arguments are passed as anonymous struct literals.', 'The syntax is .{ val1, val2 }.', 'This is the standard way to pass format args in Zig.'],
      concepts: ['format-strings', 'tuples'],
    },
    {
      id: 'zig-tuple-11',
      title: 'Fix Missing Inline',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the error: tuple iteration requires inline for.',
      skeleton: `const std = @import("std");\n\nfn printAll(t: anytype) void {\n    for (t) |val| {\n        std.debug.print("{} ", .{val});\n    }\n}\n\npub fn main() void {\n    printAll(.{ 1, 2, 3 });\n}`,
      solution: `const std = @import("std");\n\nfn printAll(t: anytype) void {\n    inline for (t) |val| {\n        std.debug.print("{} ", .{val});\n    }\n}\n\npub fn main() void {\n    printAll(.{ 1, 2, 3 });\n}`,
      hints: ['Tuples have heterogeneous types at comptime.', 'Regular for cannot iterate over comptime-known tuples.', 'Add the inline keyword before for.'],
      concepts: ['inline-for', 'tuple-iteration', 'comptime'],
    },
    {
      id: 'zig-tuple-12',
      title: 'Write Tuple Map Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function that doubles each i32 element in a tuple and returns a new tuple.',
      skeleton: `const std = @import("std");\n\n// Write doubleTuple that takes a tuple of i32 values\n// and returns a new tuple with each value doubled\n// Hint: build result with inline for and ++\n`,
      solution: `const std = @import("std");\n\nfn doubleTuple(t: anytype) @TypeOf(t) {\n    var result: @TypeOf(t) = undefined;\n    inline for (@typeInfo(@TypeOf(t)).@"struct".fields, 0..) |field, i| {\n        @field(result, field.name) = @field(t, field.name) * 2;\n        _ = i;\n    }\n    return result;\n}`,
      hints: ['Use inline for with @typeInfo to iterate fields.', 'Use @field(result, field.name) to set each field.', 'The return type is the same as the input type.'],
      concepts: ['comptime', '@typeInfo', '@field', 'tuple-transform'],
    },
    {
      id: 'zig-tuple-13',
      title: 'Fill Blank: @TypeOf a Tuple',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Get the type of a tuple using the correct builtin.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 1, 2, 3 };\n    const T = ___(t);\n    const fields = @typeInfo(T).@"struct".fields;\n    std.debug.print("{}", .{fields.len});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 1, 2, 3 };\n    const T = @TypeOf(t);\n    const fields = @typeInfo(T).@"struct".fields;\n    std.debug.print("{}", .{fields.len});\n}`,
      hints: ['You need a builtin that returns the type of a value.', '@TypeOf returns the compile-time type.', 'Replace ___ with @TypeOf.'],
      concepts: ['@TypeOf', 'comptime'],
    },
    {
      id: 'zig-tuple-14',
      title: 'Predict Concatenated Tuple',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of tuple concatenation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = .{ 1, 2 };\n    const b = .{ 3, 4 };\n    const c = a ++ b;\n    std.debug.print("{}", .{c.@"2"});\n}`,
      solution: `3`,
      hints: ['a has indices 0,1 and b has indices 0,1.', 'After concatenation c has indices 0,1,2,3.', 'c.@"2" is the first element of b, which is 3.'],
      concepts: ['tuple-concatenation', 'tuple-access'],
    },
    {
      id: 'zig-tuple-15',
      title: 'Variadic Sum with Tuples',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a variadic sum function that accepts a tuple of integers and returns their sum.',
      skeleton: `const std = @import("std");\n\n// Write variadicSum that takes anytype tuple\n// and returns the sum as i64\n`,
      solution: `const std = @import("std");\n\nfn variadicSum(args: anytype) i64 {\n    var total: i64 = 0;\n    inline for (args) |val| {\n        total += @as(i64, val);\n    }\n    return total;\n}`,
      hints: ['Use inline for to iterate the tuple.', 'Cast each value to i64 with @as.', 'Accumulate into a var total.'],
      concepts: ['inline-for', 'anytype', 'variadic'],
    },
    {
      id: 'zig-tuple-16',
      title: 'Refactor: Struct to Tuple',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor the named struct to use an anonymous tuple instead.',
      skeleton: `const std = @import("std");\n\nconst Point = struct {\n    x: i32,\n    y: i32,\n};\n\npub fn main() void {\n    const p = Point{ .x = 10, .y = 20 };\n    std.debug.print("{} {}", .{ p.x, p.y });\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const p = .{ @as(i32, 10), @as(i32, 20) };\n    std.debug.print("{} {}", .{ p.@"0", p.@"1" });\n}`,
      hints: ['Replace the named struct with .{ val1, val2 }.', 'Access fields with .@"0" and .@"1" instead of .x and .y.', 'Use @as(i32, ...) to ensure the correct type.'],
      concepts: ['tuples', 'anonymous-structs', 'refactoring'],
    },
    {
      id: 'zig-tuple-17',
      title: 'Tuple Field Inspection',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that returns the name of the Nth field in a tuple as a comptime string.',
      skeleton: `const std = @import("std");\n\n// Write fieldName that takes a type T and comptime index n\n// and returns the field name string\n`,
      solution: `const std = @import("std");\n\nfn fieldName(comptime T: type, comptime n: usize) []const u8 {\n    const fields = @typeInfo(T).@"struct".fields;\n    return fields[n].name;\n}`,
      hints: ['Use @typeInfo(T).@"struct".fields to get the fields array.', 'Index into the fields array with n.', 'Return the .name property of the field.'],
      concepts: ['@typeInfo', 'comptime', 'reflection'],
    },
    {
      id: 'zig-tuple-18',
      title: 'Fix Bug: Wrong Tuple Index',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the off-by-one error accessing the last tuple element.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 10, 20, 30 };\n    const last = t.@"3";\n    std.debug.print("{}", .{last});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const t = .{ 10, 20, 30 };\n    const last = t.@"2";\n    std.debug.print("{}", .{last});\n}`,
      hints: ['Tuple indices are 0-based.', 'A 3-element tuple has indices 0, 1, 2.', 'Change @"3" to @"2" for the last element.'],
      concepts: ['tuple-access', 'zero-indexing'],
    },
    {
      id: 'zig-tuple-19',
      title: 'Refactor: Multiple Returns to Tuple',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the function to return a tuple instead of using out parameters.',
      skeleton: `const std = @import("std");\n\nfn divmod(a: i32, b: i32, quot: *i32, rem: *i32) void {\n    quot.* = @divTrunc(a, b);\n    rem.* = @rem(a, b);\n}\n\npub fn main() void {\n    var q: i32 = undefined;\n    var r: i32 = undefined;\n    divmod(17, 5, &q, &r);\n    std.debug.print("{} {}", .{ q, r });\n}`,
      solution: `const std = @import("std");\n\nfn divmod(a: i32, b: i32) struct { i32, i32 } {\n    return .{ @divTrunc(a, b), @rem(a, b) };\n}\n\npub fn main() void {\n    const result = divmod(17, 5);\n    std.debug.print("{} {}", .{ result.@"0", result.@"1" });\n}`,
      hints: ['Return a struct { i32, i32 } as the tuple type.', 'Return .{ quotient, remainder }.', 'Access with .@"0" and .@"1" at the call site.'],
      concepts: ['tuple-return', 'refactoring', 'anonymous-structs'],
    },
    {
      id: 'zig-tuple-20',
      title: 'Comptime Tuple Builder',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function that builds a tuple of squares from 1 to N.',
      skeleton: `const std = @import("std");\n\n// Write squares(comptime N: usize) that returns\n// a tuple .{ 1, 4, 9, ..., N*N }\n`,
      solution: `const std = @import("std");\n\nfn squares(comptime N: usize) [N]i64 {\n    var result: [N]i64 = undefined;\n    for (0..N) |i| {\n        result[i] = @as(i64, @intCast(i + 1)) * @as(i64, @intCast(i + 1));\n    }\n    return result;\n}`,
      hints: ['Use a comptime loop to build the array.', 'Each element is (i+1) * (i+1).', 'Return an array [N]i64 which acts like a tuple of known size.'],
      concepts: ['comptime', 'arrays', 'metaprogramming'],
    },
  ]
};
