import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-blocks',
  title: '40. Labelled Blocks & Loops',
  explanation: `## Labelled Blocks & Loops\n\nZig supports **labelled blocks** and **labelled loops** that let you break out of or continue specific scopes.\n\n### Blocks as Expressions\n\nA block can produce a value using \`break\`:\n\n\`\`\`zig\nconst value = blk: {\n    const x = 10;\n    const y = 20;\n    break :blk x + y;\n};\n// value == 30\n\`\`\`\n\n### Labelled Loops\n\nLabels let you break or continue outer loops from inner loops:\n\n\`\`\`zig\nouter: for (matrix) |row| {\n    for (row) |cell| {\n        if (cell == target) break :outer;\n    }\n}\n\`\`\`\n\n### Labelled While\n\n\`\`\`zig\nouter: while (condition1) {\n    while (condition2) {\n        if (done) break :outer;\n        if (skip) continue :outer;\n    }\n}\n\`\`\`\n\nLabelled blocks are particularly useful for:\n- Computing values in a block scope\n- Breaking out of nested loops\n- Early returns from complex initialization\n- Comptime block evaluation`,
  exercises: [
    {
      id: 'zig-blocks-1',
      title: 'Block as Expression',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use a labelled block to compute a value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const val = ___: {\n        const a = 5;\n        const b = 10;\n        break :blk a * b;\n    };\n    std.debug.print("{}", .{val});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const val = blk: {\n        const a = 5;\n        const b = 10;\n        break :blk a * b;\n    };\n    std.debug.print("{}", .{val});\n}`,
      hints: ['The block needs a label that matches the break target.', 'Labels are identifiers followed by a colon.', 'Use blk: { ... break :blk value; }'],
      concepts: ['labelled-blocks', 'block-expressions'],
    },
    {
      id: 'zig-blocks-2',
      title: 'Predict Block Value',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the value produced by this labelled block.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x = calc: {\n        if (true) break :calc @as(i32, 42);\n        break :calc @as(i32, 0);\n    };\n    std.debug.print("{}", .{x});\n}`,
      solution: `42`,
      hints: ['The condition is true, so the first break executes.', 'break :calc 42 returns 42 from the block.', 'The second break is unreachable.'],
      concepts: ['labelled-blocks', 'break-with-value'],
    },
    {
      id: 'zig-blocks-3',
      title: 'Break from Nested Loop',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Break out of the outer loop from inside the inner loop.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const matrix = [_][3]u8{ .{ 1, 2, 3 }, .{ 4, 5, 6 } };\n    var found: u8 = 0;\n    ___: for (matrix) |row| {\n        for (row) |cell| {\n            if (cell == 5) {\n                found = cell;\n                break :outer;\n            }\n        }\n    }\n    std.debug.print("{}", .{found});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const matrix = [_][3]u8{ .{ 1, 2, 3 }, .{ 4, 5, 6 } };\n    var found: u8 = 0;\n    outer: for (matrix) |row| {\n        for (row) |cell| {\n            if (cell == 5) {\n                found = cell;\n                break :outer;\n            }\n        }\n    }\n    std.debug.print("{}", .{found});\n}`,
      hints: ['Label the outer for loop.', 'The label name must match what break references.', 'outer: for (matrix) |row| { ... }'],
      concepts: ['labelled-loops', 'nested-break'],
    },
    {
      id: 'zig-blocks-4',
      title: 'Labelled Continue',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use labelled continue to skip to the next iteration of the outer loop.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const data = [_][2]i32{ .{ 1, -1 }, .{ 2, 3 }, .{ -5, 4 } };\n    var sum: i32 = 0;\n    outer: for (data) |row| {\n        for (row) |val| {\n            if (val < 0) continue ___;\n            sum += val;\n        }\n    }\n    std.debug.print("{}", .{sum});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const data = [_][2]i32{ .{ 1, -1 }, .{ 2, 3 }, .{ -5, 4 } };\n    var sum: i32 = 0;\n    outer: for (data) |row| {\n        for (row) |val| {\n            if (val < 0) continue :outer;\n            sum += val;\n        }\n    }\n    std.debug.print("{}", .{sum});\n}`,
      hints: ['continue :label skips to the next iteration of that loop.', 'The label is outer.', 'continue :outer skips the rest of the inner AND outer loop body.'],
      concepts: ['labelled-continue', 'nested-loops'],
    },
    {
      id: 'zig-blocks-5',
      title: 'Write Function: Find in Matrix',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that finds a target value in a 2D array and returns its row index using a labelled loop.',
      skeleton: `const std = @import("std");\n\n// Write findRow that takes a [3][3]i32 matrix and target i32\n// Returns ?usize (the row index, or null if not found)\n// Use a labelled for loop\n`,
      solution: `const std = @import("std");\n\nfn findRow(matrix: [3][3]i32, target: i32) ?usize {\n    for (matrix, 0..) |row, i| {\n        for (row) |cell| {\n            if (cell == target) return i;\n        }\n    }\n    return null;\n}`,
      hints: ['Use for with index: for (matrix, 0..) |row, i|.', 'Check each cell in the row for the target.', 'Return null if the target is not found.'],
      concepts: ['labelled-loops', 'optionals', 'matrix-search'],
    },
    {
      id: 'zig-blocks-6',
      title: 'Fix Missing Label',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Fix the mismatched label error.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const result = calc: {\n        const x = 7;\n        break :compute x * x;\n    };\n    std.debug.print("{}", .{result});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const result = calc: {\n        const x = 7;\n        break :calc x * x;\n    };\n    std.debug.print("{}", .{result});\n}`,
      hints: ['The block label and break label must match.', 'The block is labelled calc: but break uses :compute.', 'Change break :compute to break :calc.'],
      concepts: ['labelled-blocks', 'label-matching'],
    },
    {
      id: 'zig-blocks-7',
      title: 'Labelled While Loop',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function using a labelled while that finds the first pair (i, j) where i * j == target.',
      skeleton: `const std = @import("std");\n\n// Write findPair(target: i32) that searches i in 1..10, j in 1..10\n// Returns a struct { i32, i32 } tuple or null\n`,
      solution: `const std = @import("std");\n\nfn findPair(target: i32) ?struct { i32, i32 } {\n    var i: i32 = 1;\n    outer: while (i <= 10) : (i += 1) {\n        var j: i32 = 1;\n        while (j <= 10) : (j += 1) {\n            if (i * j == target) return .{ i, j };\n            if (i * j > target) continue :outer;\n        }\n    }\n    return null;\n}`,
      hints: ['Label the outer while as outer:.', 'Use continue :outer to skip to next i when product exceeds target.', 'Return .{ i, j } when found, null otherwise.'],
      concepts: ['labelled-while', 'nested-loops', 'early-exit'],
    },
    {
      id: 'zig-blocks-8',
      title: 'Block Scope Variables',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output considering block scope.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var x: i32 = 1;\n    {\n        var x_inner: i32 = 10;\n        x_inner += 1;\n        x = x_inner;\n    }\n    std.debug.print("{}", .{x});\n}`,
      solution: `11`,
      hints: ['x_inner is set to 10, then incremented to 11.', 'x is assigned the value of x_inner (11).', 'x_inner goes out of scope but x retains the value.'],
      concepts: ['block-scope', 'variable-lifetime'],
    },
    {
      id: 'zig-blocks-9',
      title: 'Comptime Block with Label',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use a comptime labelled block to compute a value at compile time.',
      skeleton: `const std = @import("std");\n\nconst factorial_5 = ___ blk: {\n    var result: i64 = 1;\n    var i: i64 = 1;\n    while (i <= 5) : (i += 1) {\n        result *= i;\n    }\n    break :blk result;\n};\n\npub fn main() void {\n    std.debug.print("{}", .{factorial_5});\n}`,
      solution: `const std = @import("std");\n\nconst factorial_5 = comptime blk: {\n    var result: i64 = 1;\n    var i: i64 = 1;\n    while (i <= 5) : (i += 1) {\n        result *= i;\n    }\n    break :blk result;\n};\n\npub fn main() void {\n    std.debug.print("{}", .{factorial_5});\n}`,
      hints: ['To force compile-time evaluation, use the comptime keyword.', 'comptime blk: { ... } evaluates the block at compile time.', 'The result is a compile-time constant.'],
      concepts: ['comptime', 'labelled-blocks'],
    },
    {
      id: 'zig-blocks-10',
      title: 'Early Return from Block',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that uses a labelled block to validate input and compute a result.',
      skeleton: `const std = @import("std");\n\n// Write validate that takes an i32 and returns an i32:\n// If input < 0, the block should break with 0\n// If input > 100, the block should break with 100\n// Otherwise, break with input * 2\n`,
      solution: `const std = @import("std");\n\nfn validate(input: i32) i32 {\n    return blk: {\n        if (input < 0) break :blk 0;\n        if (input > 100) break :blk 100;\n        break :blk input * 2;\n    };\n}`,
      hints: ['Use return blk: { ... } to return a block expression.', 'Use break :blk value for early exit with a value.', 'Each condition breaks with a different value.'],
      concepts: ['labelled-blocks', 'early-return', 'validation'],
    },
    {
      id: 'zig-blocks-11',
      title: 'Fix: Break Without Label',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the error where break needs a label to return a value from a block.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const val = {\n        const x = 42;\n        break x;\n    };\n    std.debug.print("{}", .{val});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const val = blk: {\n        const x = 42;\n        break :blk x;\n    };\n    std.debug.print("{}", .{val});\n}`,
      hints: ['Blocks that return values need labels.', 'Add a label to the block and use break :label.', 'blk: { break :blk x; }'],
      concepts: ['labelled-blocks', 'break-with-value'],
    },
    {
      id: 'zig-blocks-12',
      title: 'Nested Labelled For',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that counts how many rows in a matrix contain a negative number, using labelled continue.',
      skeleton: `const std = @import("std");\n\n// Write countNegativeRows that takes a [][3]i32 slice\n// Returns usize count of rows containing at least one negative\n`,
      solution: `const std = @import("std");\n\nfn countNegativeRows(matrix: []const [3]i32) usize {\n    var count: usize = 0;\n    outer: for (matrix) |row| {\n        for (row) |val| {\n            if (val < 0) {\n                count += 1;\n                continue :outer;\n            }\n        }\n    }\n    return count;\n}`,
      hints: ['Label the outer for loop.', 'When a negative is found, increment count and continue :outer.', 'This avoids double-counting rows with multiple negatives.'],
      concepts: ['labelled-continue', 'nested-loops', 'counting'],
    },
    {
      id: 'zig-blocks-13',
      title: 'Predict Labelled Loop Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of this nested labelled loop.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var count: u32 = 0;\n    outer: for (0..3) |_| {\n        for (0..3) |j| {\n            if (j == 1) continue :outer;\n            count += 1;\n        }\n    }\n    std.debug.print("{}", .{count});\n}`,
      solution: `3`,
      hints: ['The outer loop runs 3 times (i = 0, 1, 2).', 'Each time, the inner loop starts with j=0 (count++) then j=1 triggers continue :outer.', '3 iterations of the outer loop, each adding 1 = 3 total.'],
      concepts: ['labelled-continue', 'loop-counting'],
    },
    {
      id: 'zig-blocks-14',
      title: 'Fill Blank: For with Value',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use a for loop with an else clause to provide a default value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const haystack = [_]i32{ 1, 3, 5, 7, 9 };\n    const found = for (haystack) |val| {\n        if (val == 5) break val;\n    } ___ 0;\n    std.debug.print("{}", .{found});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const haystack = [_]i32{ 1, 3, 5, 7, 9 };\n    const found = for (haystack) |val| {\n        if (val == 5) break val;\n    } else 0;\n    std.debug.print("{}", .{found});\n}`,
      hints: ['For loops as expressions use else for the default case.', 'If no break is hit, the else branch provides the value.', 'Replace ___ with else.'],
      concepts: ['for-else', 'loop-expression'],
    },
    {
      id: 'zig-blocks-15',
      title: 'Refactor: Flatten Nested Ifs',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor nested if-else chains into a labelled block with early breaks.',
      skeleton: `const std = @import("std");\n\nfn classify(x: i32) []const u8 {\n    if (x < 0) {\n        return "negative";\n    } else {\n        if (x == 0) {\n            return "zero";\n        } else {\n            if (x <= 10) {\n                return "small";\n            } else {\n                return "large";\n            }\n        }\n    }\n}`,
      solution: `const std = @import("std");\n\nfn classify(x: i32) []const u8 {\n    return blk: {\n        if (x < 0) break :blk "negative";\n        if (x == 0) break :blk "zero";\n        if (x <= 10) break :blk "small";\n        break :blk "large";\n    };\n}`,
      hints: ['Use a labelled block to flatten the nesting.', 'Each condition uses break :blk with its value.', 'The last break is the default case.'],
      concepts: ['labelled-blocks', 'refactoring', 'early-return'],
    },
    {
      id: 'zig-blocks-16',
      title: 'Write: While with Block Value',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that uses a while loop as an expression to find the first power of 2 greater than n.',
      skeleton: `const std = @import("std");\n\n// Write firstPow2Above(n: u32) -> u32\n// Use a while loop as an expression\n`,
      solution: `const std = @import("std");\n\nfn firstPow2Above(n: u32) u32 {\n    var p: u32 = 1;\n    return while (p <= n) {\n        p *= 2;\n    } else p;\n}`,
      hints: ['A while loop can be used as an expression with else.', 'The else clause executes when the condition becomes false.', 'while (p <= n) { p *= 2; } else p returns p when p > n.'],
      concepts: ['while-expression', 'while-else'],
    },
    {
      id: 'zig-blocks-17',
      title: 'Fix: Label Scope Error',
      type: 'fix-bug',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Fix the code where a break references a label that is not in scope.',
      skeleton: `const std = @import("std");\n\nfn compute(x: i32) i32 {\n    const a = blk_a: {\n        break :blk_a x + 1;\n    };\n    const b = blk_b: {\n        if (a > 10) break :blk_a a;\n        break :blk_b a * 2;\n    };\n    return b;\n}`,
      solution: `const std = @import("std");\n\nfn compute(x: i32) i32 {\n    const a = blk_a: {\n        break :blk_a x + 1;\n    };\n    const b = blk_b: {\n        if (a > 10) break :blk_b a;\n        break :blk_b a * 2;\n    };\n    return b;\n}`,
      hints: ['break :blk_a inside blk_b is invalid -- blk_a is not in scope.', 'Each block can only break to its own label.', 'Change break :blk_a to break :blk_b inside the second block.'],
      concepts: ['label-scope', 'labelled-blocks'],
    },
    {
      id: 'zig-blocks-18',
      title: 'Refactor: Replace Flag with Block',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the code to eliminate the boolean flag by using a labelled block expression.',
      skeleton: `const std = @import("std");\n\nfn findFirst(items: []const i32) i32 {\n    var found = false;\n    var result: i32 = -1;\n    for (items) |val| {\n        if (val > 0 and !found) {\n            result = val;\n            found = true;\n        }\n    }\n    return result;\n}`,
      solution: `const std = @import("std");\n\nfn findFirst(items: []const i32) i32 {\n    return for (items) |val| {\n        if (val > 0) break val;\n    } else -1;\n}`,
      hints: ['Use a for loop as an expression with break and else.', 'break val exits with the first positive value.', 'else -1 provides the default when nothing is found.'],
      concepts: ['for-expression', 'refactoring', 'labelled-blocks'],
    },
    {
      id: 'zig-blocks-19',
      title: 'Comptime Block: String Table',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime block that builds a lookup array mapping digits 0-9 to their string names.',
      skeleton: `const std = @import("std");\n\n// Write a const digit_names using a comptime block\n// that produces [10][]const u8 = .{ "zero", "one", ... "nine" }\n`,
      solution: `const std = @import("std");\n\nconst digit_names = comptime blk: {\n    const names = [10][]const u8{\n        "zero", "one", "two", "three", "four",\n        "five", "six", "seven", "eight", "nine",\n    };\n    break :blk names;\n};`,
      hints: ['Use comptime blk: { ... break :blk value; }.', 'Build the array of string literals inside the block.', 'Break with the completed array.'],
      concepts: ['comptime', 'labelled-blocks', 'lookup-tables'],
    },
    {
      id: 'zig-blocks-20',
      title: 'Predict: For-Else Expression',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict the output of this for-else loop expression.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const items = [_]i32{ 2, 4, 6, 8 };\n    const odd = for (items) |val| {\n        if (val % 2 != 0) break val;\n    } else @as(i32, -1);\n    std.debug.print("{}", .{odd});\n}`,
      solution: `-1`,
      hints: ['All items are even (2, 4, 6, 8).', 'No item satisfies val % 2 != 0.', 'The else clause returns -1.'],
      concepts: ['for-else', 'loop-expression'],
    },
  ]
};
