import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-errtrace',
  title: '41. Error Tracing',
  explanation: `## Error Tracing in Zig\n\nZig provides **error return traces** -- automatic stack-trace-like output when errors propagate through the call stack.\n\n### Error Return Traces\n\nWhen an error propagates through multiple functions via \`try\`, Zig records each return point:\n\n\`\`\`zig\nfn inner() !void {\n    return error.Oops;\n}\n\nfn middle() !void {\n    try inner();\n}\n\nfn outer() !void {\n    try middle();\n}\n\`\`\`\n\nIn debug builds, if an error reaches \`main\`, Zig prints the full trace showing where each \`try\` propagated the error.\n\n### @errorReturnTrace\n\nYou can access the current error return trace programmatically:\n\n\`\`\`zig\nconst trace = @errorReturnTrace();\nif (trace) |t| {\n    std.debug.dumpStackTrace(t.*);\n}\n\`\`\`\n\n### Error Context Patterns\n\nSince Zig errors are just enum values (no payloads), context is added through logging or wrapper patterns:\n\n\`\`\`zig\nfn openConfig(path: []const u8) !File {\n    return std.fs.cwd().openFile(path, .{}) catch |err| {\n        std.log.err("Failed to open config: {s}: {}", .{ path, err });\n        return err;\n    };\n}\n\`\`\`\n\n### Release Mode Behavior\n\nError return traces are available in **Debug** and **ReleaseSafe** builds, but stripped in **ReleaseFast** and **ReleaseSmall** for performance.`,
  exercises: [
    {
      id: 'zig-errtrace-1',
      title: 'Return an Error',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Return an error from a function.',
      skeleton: `const std = @import("std");\n\nfn failHere() !void {\n    return ___.NotFound;\n}\n\npub fn main() void {\n    failHere() catch |err| {\n        std.debug.print("{}", .{err});\n    };\n}`,
      solution: `const std = @import("std");\n\nfn failHere() !void {\n    return error.NotFound;\n}\n\npub fn main() void {\n    failHere() catch |err| {\n        std.debug.print("{}", .{err});\n    };\n}`,
      hints: ['Errors are returned with the error keyword.', 'The syntax is return error.ErrorName.', 'Replace ___ with error.'],
      concepts: ['error-return', 'error-values'],
    },
    {
      id: 'zig-errtrace-2',
      title: 'Propagate with try',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use try to propagate an error up the call stack.',
      skeleton: `const std = @import("std");\n\nfn inner() !u32 {\n    return error.Invalid;\n}\n\nfn outer() !u32 {\n    const val = ___ inner();\n    return val + 1;\n}`,
      solution: `const std = @import("std");\n\nfn inner() !u32 {\n    return error.Invalid;\n}\n\nfn outer() !u32 {\n    const val = try inner();\n    return val + 1;\n}`,
      hints: ['try unwraps the result or returns the error.', 'It automatically propagates errors to the caller.', 'Replace ___ with try.'],
      concepts: ['try', 'error-propagation'],
    },
    {
      id: 'zig-errtrace-3',
      title: 'Predict Error Catch',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict which error is caught.',
      skeleton: `const std = @import("std");\n\nfn step1() !void {\n    return error.StepOneFailed;\n}\n\nfn step2() !void {\n    try step1();\n}\n\npub fn main() void {\n    step2() catch |err| {\n        std.debug.print("{s}", .{@errorName(err)});\n    };\n}`,
      solution: `StepOneFailed`,
      hints: ['step1 returns error.StepOneFailed.', 'step2 propagates it with try.', '@errorName returns the error name as a string.'],
      concepts: ['error-propagation', '@errorName'],
    },
    {
      id: 'zig-errtrace-4',
      title: 'Error Logging Pattern',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that catches an error, logs it, and re-returns it.',
      skeleton: `const std = @import("std");\n\n// Write wrapError that calls a function fn() !void\n// On error, logs via std.log.err and re-returns the error\n`,
      solution: `const std = @import("std");\n\nfn wrapError(func: *const fn () anyerror!void) !void {\n    return func() catch |err| {\n        std.log.err("operation failed: {s}", .{@errorName(err)});\n        return err;\n    };\n}`,
      hints: ['Use catch |err| to capture the error.', 'Log with std.log.err and @errorName.', 'Re-return the error with return err.'],
      concepts: ['catch', 'error-logging', 're-return'],
    },
    {
      id: 'zig-errtrace-5',
      title: 'Fill Blank: @errorName',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Get the string name of an error value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const err = error.OutOfMemory;\n    const name = ___(@TypeOf(err), err);\n    std.debug.print("{s}", .{name});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const err = error.OutOfMemory;\n    const name = @errorName(err);\n    std.debug.print("{s}", .{name});\n}`,
      hints: ['There is a builtin that converts an error to its name.', '@errorName returns a []const u8.', 'Replace ___ with @errorName and fix the call.'],
      concepts: ['@errorName'],
    },
    {
      id: 'zig-errtrace-6',
      title: 'Fix: Missing Error in Union',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the function so it can return the error from readFile.',
      skeleton: `const std = @import("std");\n\nconst AppError = error{ ConfigMissing, ParseFailed };\n\nfn loadConfig() AppError![]const u8 {\n    const data = std.fs.cwd().openFile("config.txt", .{}) catch {\n        return error.ConfigMissing;\n    };\n    _ = data;\n    return "ok";\n}`,
      solution: `const std = @import("std");\n\nconst AppError = error{ ConfigMissing, ParseFailed };\n\nfn loadConfig() AppError![]const u8 {\n    const file = std.fs.cwd().openFile("config.txt", .{}) catch {\n        return error.ConfigMissing;\n    };\n    defer file.close();\n    return "ok";\n}`,
      hints: ['The file handle should be closed with defer.', 'The catch block correctly maps to ConfigMissing.', 'Add defer file.close() after opening.'],
      concepts: ['error-sets', 'defer', 'resource-management'],
    },
    {
      id: 'zig-errtrace-7',
      title: 'Error Context Wrapper',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that wraps an error with additional context by logging before re-raising.',
      skeleton: `const std = @import("std");\n\n// Write parseNumber(s: []const u8) !i32\n// Uses std.fmt.parseInt. On error, log the bad input string\n// and return error.ParseFailed\n`,
      solution: `const std = @import("std");\n\nconst ParseError = error{ParseFailed};\n\nfn parseNumber(s: []const u8) ParseError!i32 {\n    return std.fmt.parseInt(i32, s, 10) catch {\n        std.log.err("failed to parse: {s}", .{s});\n        return error.ParseFailed;\n    };\n}`,
      hints: ['Use std.fmt.parseInt(i32, s, 10) to parse.', 'Catch the error and log the input string.', 'Return a custom error instead of the original.'],
      concepts: ['error-wrapping', 'logging', 'catch'],
    },
    {
      id: 'zig-errtrace-8',
      title: 'Predict: Nested Error Propagation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict which error surfaces from nested try calls.',
      skeleton: `const std = @import("std");\n\nfn a() !i32 { return error.Alpha; }\nfn b() !i32 { return error.Beta; }\n\nfn combined() !i32 {\n    const x = a() catch @as(i32, 10);\n    const y = try b();\n    return x + y;\n}\n\npub fn main() void {\n    combined() catch |err| {\n        std.debug.print("{s}", .{@errorName(err)});\n    };\n}`,
      solution: `Beta`,
      hints: ['a() returns error.Alpha but is caught with a default of 10.', 'b() returns error.Beta and is propagated with try.', 'Only Beta reaches the caller.'],
      concepts: ['catch-default', 'try', 'error-propagation'],
    },
    {
      id: 'zig-errtrace-9',
      title: 'Error Set Coercion',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Coerce a specific error set to anyerror.',
      skeleton: `const std = @import("std");\n\nconst MyError = error{ Foo, Bar };\n\nfn doWork() MyError!void {\n    return error.Foo;\n}\n\nfn wrapper() ___!void {\n    try doWork();\n}`,
      solution: `const std = @import("std");\n\nconst MyError = error{ Foo, Bar };\n\nfn doWork() MyError!void {\n    return error.Foo;\n}\n\nfn wrapper() anyerror!void {\n    try doWork();\n}`,
      hints: ['anyerror is the superset of all error sets.', 'Specific error sets coerce to anyerror.', 'Replace ___ with anyerror.'],
      concepts: ['anyerror', 'error-set-coercion'],
    },
    {
      id: 'zig-errtrace-10',
      title: 'Write: Error Chain Logger',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that attempts multiple operations and collects the first error.',
      skeleton: `const std = @import("std");\n\n// Write tryAll that takes a slice of function pointers\n// Calls each one. Returns the first error encountered, or void on success.\n`,
      solution: `const std = @import("std");\n\nfn tryAll(funcs: []const *const fn () anyerror!void) anyerror!void {\n    for (funcs) |func| {\n        try func();\n    }\n}`,
      hints: ['Iterate over the function slice.', 'Use try to propagate the first error.', 'If all succeed, the function returns void.'],
      concepts: ['function-pointers', 'try', 'error-propagation'],
    },
    {
      id: 'zig-errtrace-11',
      title: 'Fix: Catch Without Error Capture',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the code to properly capture and use the error value.',
      skeleton: `const std = @import("std");\n\nfn riskyOp() !i32 {\n    return error.Broken;\n}\n\npub fn main() void {\n    const result = riskyOp() catch {\n        std.debug.print("got error: {s}", .{@errorName(err)});\n        return;\n    };\n    _ = result;\n}`,
      solution: `const std = @import("std");\n\nfn riskyOp() !i32 {\n    return error.Broken;\n}\n\npub fn main() void {\n    const result = riskyOp() catch |err| {\n        std.debug.print("got error: {s}", .{@errorName(err)});\n        return;\n    };\n    _ = result;\n}`,
      hints: ['The catch block references err but does not capture it.', 'Use catch |err| to capture the error value.', 'Add |err| after catch.'],
      concepts: ['catch', 'error-capture'],
    },
    {
      id: 'zig-errtrace-12',
      title: 'Errdefer for Cleanup',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use errdefer to clean up a resource only when an error occurs.',
      skeleton: `const std = @import("std");\n\nfn allocAndInit(allocator: std.mem.Allocator) ![]u8 {\n    const buf = try allocator.alloc(u8, 1024);\n    ___ allocator.free(buf);\n    // Simulate possible failure during init\n    if (buf[0] != 0) return error.BadInit;\n    return buf;\n}`,
      solution: `const std = @import("std");\n\nfn allocAndInit(allocator: std.mem.Allocator) ![]u8 {\n    const buf = try allocator.alloc(u8, 1024);\n    errdefer allocator.free(buf);\n    // Simulate possible failure during init\n    if (buf[0] != 0) return error.BadInit;\n    return buf;\n}`,
      hints: ['errdefer runs its expression only if the function returns an error.', 'This ensures buf is freed on error but not on success.', 'Replace ___ with errdefer.'],
      concepts: ['errdefer', 'resource-cleanup'],
    },
    {
      id: 'zig-errtrace-13',
      title: 'Write: Retry on Error',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a retry function that attempts an operation up to N times before giving up.',
      skeleton: `const std = @import("std");\n\n// Write retry(comptime n: usize, func: fn() anyerror!void) anyerror!void\n// Tries func() up to n times. Returns success or the last error.\n`,
      solution: `const std = @import("std");\n\nfn retry(comptime n: usize, func: *const fn () anyerror!void) anyerror!void {\n    var last_err: anyerror = error.Unexpected;\n    for (0..n) |_| {\n        func() catch |err| {\n            last_err = err;\n            continue;\n        };\n        return;\n    }\n    return last_err;\n}`,
      hints: ['Loop n times, calling func each time.', 'On error, save it and continue to the next attempt.', 'On success, return immediately. After all attempts, return last error.'],
      concepts: ['retry-pattern', 'error-handling', 'loops'],
    },
    {
      id: 'zig-errtrace-14',
      title: 'Predict: Errdefer Order',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict the order of errdefer execution.',
      skeleton: `const std = @import("std");\n\nfn failing() !void {\n    std.debug.print("A", .{});\n    errdefer std.debug.print("B", .{});\n    std.debug.print("C", .{});\n    errdefer std.debug.print("D", .{});\n    return error.Fail;\n}\n\npub fn main() void {\n    failing() catch {};\n}`,
      solution: `ACDB`,
      hints: ['A prints first, then C prints.', 'errdefers execute in reverse order on error.', 'D was registered last so runs first, then B.'],
      concepts: ['errdefer', 'execution-order'],
    },
    {
      id: 'zig-errtrace-15',
      title: 'Write: Error Map Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that maps one error to another (error translation).',
      skeleton: `const std = @import("std");\n\n// Write mapError that takes a function returning !void\n// If it returns error.FileNotFound, translate to error.ConfigMissing\n// All other errors pass through unchanged\n`,
      solution: `const std = @import("std");\n\nconst MappedError = error{ConfigMissing} || anyerror;\n\nfn mapError(func: *const fn () anyerror!void) anyerror!void {\n    return func() catch |err| {\n        if (err == error.FileNotFound) return error.ConfigMissing;\n        return err;\n    };\n}`,
      hints: ['Catch the error and check its value.', 'If it matches FileNotFound, return ConfigMissing.', 'Otherwise return the original error.'],
      concepts: ['error-mapping', 'catch', 'error-translation'],
    },
    {
      id: 'zig-errtrace-16',
      title: 'Fill Blank: Error Union Type',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Declare a specific error union return type.',
      skeleton: `const std = @import("std");\n\nconst FileError = error{ NotFound, PermissionDenied };\n\nfn openSafe(path: []const u8) ___!std.fs.File {\n    return std.fs.cwd().openFile(path, .{}) catch return error.NotFound;\n}`,
      solution: `const std = @import("std");\n\nconst FileError = error{ NotFound, PermissionDenied };\n\nfn openSafe(path: []const u8) FileError!std.fs.File {\n    return std.fs.cwd().openFile(path, .{}) catch return error.NotFound;\n}`,
      hints: ['The error set name goes before the !.', 'FileError is the specific error set defined above.', 'Replace ___ with FileError.'],
      concepts: ['error-unions', 'error-sets'],
    },
    {
      id: 'zig-errtrace-17',
      title: 'Refactor: Remove Redundant Catch',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor to simplify the redundant catch-and-return pattern.',
      skeleton: `const std = @import("std");\n\nfn readData() ![]const u8 {\n    return error.ReadFailed;\n}\n\nfn process() ![]const u8 {\n    const data = readData() catch |err| {\n        return err;\n    };\n    return data;\n}`,
      solution: `const std = @import("std");\n\nfn readData() ![]const u8 {\n    return error.ReadFailed;\n}\n\nfn process() ![]const u8 {\n    const data = try readData();\n    return data;\n}`,
      hints: ['catch |err| { return err; } is exactly what try does.', 'Replace the catch block with try.', 'try is syntactic sugar for this pattern.'],
      concepts: ['try', 'refactoring', 'error-propagation'],
    },
    {
      id: 'zig-errtrace-18',
      title: 'Refactor: Consolidate Error Handling',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Consolidate multiple error checks into a cleaner pattern.',
      skeleton: `const std = @import("std");\n\nfn step1() !i32 { return 10; }\nfn step2(x: i32) !i32 { return x + 5; }\nfn step3(x: i32) !i32 { return x * 2; }\n\nfn pipeline() !i32 {\n    const a = step1() catch |err| return err;\n    const b = step2(a) catch |err| return err;\n    const c = step3(b) catch |err| return err;\n    return c;\n}`,
      solution: `const std = @import("std");\n\nfn step1() !i32 { return 10; }\nfn step2(x: i32) !i32 { return x + 5; }\nfn step3(x: i32) !i32 { return x * 2; }\n\nfn pipeline() !i32 {\n    const a = try step1();\n    const b = try step2(a);\n    return try step3(b);\n}`,
      hints: ['Each catch |err| return err is just try.', 'Replace all three catch blocks with try.', 'The last one can be return try step3(b).'],
      concepts: ['try', 'refactoring', 'pipeline'],
    },
    {
      id: 'zig-errtrace-19',
      title: 'Write: Error Accumulator',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that runs all operations and counts how many failed.',
      skeleton: `const std = @import("std");\n\n// Write countErrors(funcs: []const *const fn() anyerror!void) usize\n// Call each function, count how many return errors\n`,
      solution: `const std = @import("std");\n\nfn countErrors(funcs: []const *const fn () anyerror!void) usize {\n    var errors: usize = 0;\n    for (funcs) |func| {\n        func() catch {\n            errors += 1;\n        };\n    }\n    return errors;\n}`,
      hints: ['Iterate over each function pointer.', 'Use catch to detect errors without propagating.', 'Increment a counter on each error.'],
      concepts: ['catch', 'function-pointers', 'error-counting'],
    },
    {
      id: 'zig-errtrace-20',
      title: 'Predict: Error Set Merge',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict the behavior of merged error sets.',
      skeleton: `const std = @import("std");\n\nconst A = error{ X, Y };\nconst B = error{ Y, Z };\nconst C = A || B;\n\npub fn main() void {\n    const err: C = error.Z;\n    std.debug.print("{s}", .{@errorName(err)});\n}`,
      solution: `Z`,
      hints: ['A || B merges the error sets: { X, Y, Z }.', 'error.Z is in the merged set C.', '@errorName returns "Z".'],
      concepts: ['error-set-merge', '@errorName'],
    },
  ]
};
