import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-safety',
  title: '42. Safety Features',
  explanation: `## Safety Features in Zig\n\nZig provides **runtime safety checks** in debug and safe builds to catch undefined behavior before it causes silent corruption.\n\n### Runtime Safety Checks\n\n- **Integer overflow detection**: Arithmetic operations trap on overflow\n- **Bounds checking**: Array/slice access is bounds-checked\n- **Null pointer detection**: Dereferencing optional pointers checks for null\n- **Alignment checks**: Pointer alignment is verified\n- **Use-after-free detection**: Debug allocator detects freed memory access\n\n\`\`\`zig\nvar x: u8 = 255;\nx += 1; // In Debug: panic! integer overflow\n        // In ReleaseFast: wraps to 0 (undefined behavior allowed)\n\`\`\`\n\n### Build Modes\n\n| Mode | Safety | Optimizations |\n|------|--------|---------------|\n| Debug | Full | None |\n| ReleaseSafe | Full | Yes |\n| ReleaseFast | None | Max |\n| ReleaseSmall | None | Size |\n\n### @setRuntimeSafety\n\nYou can override safety per-scope:\n\n\`\`\`zig\n{\n    @setRuntimeSafety(false);\n    var x: u8 = 255;\n    x +%= 1; // wrapping add, always defined\n}\n\`\`\`\n\n### Debug Allocator\n\n\`std.heap.GeneralPurposeAllocator\` detects memory bugs:\n\n\`\`\`zig\nvar gpa = std.heap.GeneralPurposeAllocator(.{}){};\ndefer _ = gpa.deinit(); // Reports leaks!\nconst alloc = gpa.allocator();\n\`\`\``,
  exercises: [
    {
      id: 'zig-safety-1',
      title: 'Wrapping Addition',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use wrapping addition to safely handle overflow.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var x: u8 = 255;\n    x ___= 1; // wrapping add\n    std.debug.print("{}", .{x});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var x: u8 = 255;\n    x +%= 1; // wrapping add\n    std.debug.print("{}", .{x});\n}`,
      hints: ['Wrapping arithmetic uses the % modifier.', '+%= is wrapping addition assignment.', 'This wraps 255 + 1 to 0 for u8.'],
      concepts: ['wrapping-arithmetic', 'overflow'],
    },
    {
      id: 'zig-safety-2',
      title: 'Predict Wrapping Result',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the result of wrapping arithmetic.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x: u8 = 200;\n    const y: u8 = 100;\n    const result = x +% y;\n    std.debug.print("{}", .{result});\n}`,
      solution: `44`,
      hints: ['200 + 100 = 300.', 'u8 max is 255, so 300 wraps around.', '300 - 256 = 44.'],
      concepts: ['wrapping-arithmetic', 'overflow'],
    },
    {
      id: 'zig-safety-3',
      title: 'Saturating Arithmetic',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use saturating addition to clamp at the maximum value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const x: u8 = 250;\n    const y: u8 = 20;\n    const result = x ___| y;\n    std.debug.print("{}", .{result});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const x: u8 = 250;\n    const y: u8 = 20;\n    const result = x +| y;\n    std.debug.print("{}", .{result});\n}`,
      hints: ['Saturating arithmetic uses the | modifier.', '+| is saturating addition.', '250 + 20 saturates to 255 for u8.'],
      concepts: ['saturating-arithmetic'],
    },
    {
      id: 'zig-safety-4',
      title: 'Bounds-Safe Array Access',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a function that safely accesses an array element, returning null for out-of-bounds.',
      skeleton: `const std = @import("std");\n\n// Write safeGet that takes a []const i32 and usize index\n// Returns ?i32 - the value or null if out of bounds\n`,
      solution: `const std = @import("std");\n\nfn safeGet(slice: []const i32, index: usize) ?i32 {\n    if (index >= slice.len) return null;\n    return slice[index];\n}`,
      hints: ['Check if index >= slice.len first.', 'Return null for out-of-bounds access.', 'Return the value if in bounds.'],
      concepts: ['bounds-checking', 'optionals'],
    },
    {
      id: 'zig-safety-5',
      title: 'Debug Allocator Setup',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Set up the GeneralPurposeAllocator with leak detection.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.___(.{}){};\n    defer _ = gpa.deinit();\n    const allocator = gpa.allocator();\n    const ptr = allocator.alloc(u8, 100) catch return;\n    allocator.free(ptr);\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    const allocator = gpa.allocator();\n    const ptr = allocator.alloc(u8, 100) catch return;\n    allocator.free(ptr);\n}`,
      hints: ['The debug-friendly allocator is GeneralPurposeAllocator.', 'It takes a config struct as a comptime parameter.', 'std.heap.GeneralPurposeAllocator(.{}){}'],
      concepts: ['GeneralPurposeAllocator', 'leak-detection'],
    },
    {
      id: 'zig-safety-6',
      title: 'Fix: Integer Overflow Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the integer overflow that would panic in debug mode.',
      skeleton: `const std = @import("std");\n\nfn addClamped(a: u8, b: u8) u8 {\n    return a + b; // panics if a + b > 255\n}`,
      solution: `const std = @import("std");\n\nfn addClamped(a: u8, b: u8) u8 {\n    return a +| b; // saturates at 255\n}`,
      hints: ['Regular + panics on overflow in safe builds.', 'Use saturating arithmetic to clamp at max.', 'Replace + with +| for saturating addition.'],
      concepts: ['saturating-arithmetic', 'overflow-safety'],
    },
    {
      id: 'zig-safety-7',
      title: 'Write: Safe Cast Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that safely casts an i64 to u32, returning null if the value is negative or too large.',
      skeleton: `const std = @import("std");\n\n// Write safeCast(value: i64) -> ?u32\n// Returns null if value < 0 or value > std.math.maxInt(u32)\n`,
      solution: `const std = @import("std");\n\nfn safeCast(value: i64) ?u32 {\n    if (value < 0 or value > std.math.maxInt(u32)) return null;\n    return @intCast(value);\n}`,
      hints: ['Check for negative values and values above u32 max.', 'Use std.math.maxInt(u32) for the upper bound.', 'Use @intCast for the actual conversion.'],
      concepts: ['safe-casting', '@intCast', 'optionals'],
    },
    {
      id: 'zig-safety-8',
      title: 'Predict: Saturating Subtraction',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the result of saturating subtraction on unsigned types.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 10;\n    const b: u8 = 50;\n    const result = a -| b;\n    std.debug.print("{}", .{result});\n}`,
      solution: `0`,
      hints: ['10 - 50 would be -40, but u8 cannot be negative.', 'Saturating subtraction clamps at the minimum.', 'For unsigned types, the minimum is 0.'],
      concepts: ['saturating-arithmetic', 'unsigned'],
    },
    {
      id: 'zig-safety-9',
      title: 'Overflow Detection with @addWithOverflow',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use @addWithOverflow to detect overflow explicitly.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = 100;\n    const result = @addWithOverflow(a, b);\n    if (result.___) {\n        std.debug.print("overflow!", .{});\n    } else {\n        std.debug.print("{}", .{result.@"0"});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 200;\n    const b: u8 = 100;\n    const result = @addWithOverflow(a, b);\n    if (result.@"1" != 0) {\n        std.debug.print("overflow!", .{});\n    } else {\n        std.debug.print("{}", .{result.@"0"});\n    }\n}`,
      hints: ['@addWithOverflow returns a tuple of (result, overflow_bit).', 'The second element is 1 if overflow occurred.', 'Check result.@"1" != 0 for overflow.'],
      concepts: ['@addWithOverflow', 'overflow-detection'],
    },
    {
      id: 'zig-safety-10',
      title: 'Write: Checked Multiply',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that multiplies two u32 values and returns null on overflow.',
      skeleton: `const std = @import("std");\n\n// Write checkedMul(a: u32, b: u32) -> ?u32\n// Returns null if the multiplication overflows\n`,
      solution: `const std = @import("std");\n\nfn checkedMul(a: u32, b: u32) ?u32 {\n    const result = @mulWithOverflow(a, b);\n    if (result.@"1" != 0) return null;\n    return result.@"0";\n}`,
      hints: ['Use @mulWithOverflow(a, b) for checked multiplication.', 'Check the overflow bit (second element).', 'Return null on overflow, the value otherwise.'],
      concepts: ['@mulWithOverflow', 'checked-arithmetic'],
    },
    {
      id: 'zig-safety-11',
      title: 'Fix: Slice Bounds Error',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the out-of-bounds slice operation.',
      skeleton: `const std = @import("std");\n\nfn lastThree(data: []const u8) []const u8 {\n    return data[data.len - 3..];\n}\n\npub fn main() void {\n    const short = [_]u8{ 1, 2 };\n    const result = lastThree(&short);\n    std.debug.print("{}", .{result.len});\n}`,
      solution: `const std = @import("std");\n\nfn lastThree(data: []const u8) []const u8 {\n    if (data.len < 3) return data;\n    return data[data.len - 3..];\n}\n\npub fn main() void {\n    const short = [_]u8{ 1, 2 };\n    const result = lastThree(&short);\n    std.debug.print("{}", .{result.len});\n}`,
      hints: ['data.len - 3 underflows for slices shorter than 3.', 'Add a bounds check before slicing.', 'If data.len < 3, return the entire slice.'],
      concepts: ['bounds-checking', 'underflow'],
    },
    {
      id: 'zig-safety-12',
      title: 'Write: Safe Division',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a safe division function that returns null on division by zero.',
      skeleton: `const std = @import("std");\n\n// Write safeDiv(a: i32, b: i32) -> ?i32\n// Returns null if b is 0\n`,
      solution: `const std = @import("std");\n\nfn safeDiv(a: i32, b: i32) ?i32 {\n    if (b == 0) return null;\n    return @divTrunc(a, b);\n}`,
      hints: ['Check for zero divisor first.', 'Return null on division by zero.', 'Use @divTrunc for integer division.'],
      concepts: ['division-safety', '@divTrunc', 'optionals'],
    },
    {
      id: 'zig-safety-13',
      title: '@setRuntimeSafety',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Disable runtime safety for a performance-critical block.',
      skeleton: `const std = @import("std");\n\nfn fastUncheckedAdd(a: u8, b: u8) u8 {\n    @___(false);\n    return a + b; // no overflow check\n}`,
      solution: `const std = @import("std");\n\nfn fastUncheckedAdd(a: u8, b: u8) u8 {\n    @setRuntimeSafety(false);\n    return a + b; // no overflow check\n}`,
      hints: ['There is a builtin to control runtime safety per scope.', '@setRuntimeSafety(false) disables checks.', 'This is useful for hot loops where you have proven correctness.'],
      concepts: ['@setRuntimeSafety', 'performance'],
    },
    {
      id: 'zig-safety-14',
      title: 'Predict: Wrapping vs Saturating',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the difference between wrapping and saturating subtraction.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a: u8 = 5;\n    const b: u8 = 10;\n    const wrap = a -% b;\n    const sat = a -| b;\n    std.debug.print("{} {}", .{ wrap, sat });\n}`,
      solution: `251 0`,
      hints: ['5 - 10 = -5 as a mathematical result.', 'Wrapping: u8 wraps -5 to 256 - 5 = 251.', 'Saturating: clamps to minimum 0 for unsigned.'],
      concepts: ['wrapping-arithmetic', 'saturating-arithmetic'],
    },
    {
      id: 'zig-safety-15',
      title: 'Write: Alignment-Safe Pointer Cast',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that safely reinterprets a byte slice as a u32 slice, checking alignment.',
      skeleton: `const std = @import("std");\n\n// Write asU32Slice(bytes: []const u8) -> ?[]const u32\n// Returns null if bytes.ptr is not aligned to @alignOf(u32)\n// or if bytes.len is not a multiple of 4\n`,
      solution: `const std = @import("std");\n\nfn asU32Slice(bytes: []const u8) ?[]const u32 {\n    if (bytes.len % @sizeOf(u32) != 0) return null;\n    if (@intFromPtr(bytes.ptr) % @alignOf(u32) != 0) return null;\n    const ptr: [*]const u32 = @ptrCast(@alignCast(bytes.ptr));\n    return ptr[0 .. bytes.len / @sizeOf(u32)];\n}`,
      hints: ['Check length is a multiple of @sizeOf(u32).', 'Check alignment with @intFromPtr and @alignOf.', 'Use @ptrCast and @alignCast for the conversion.'],
      concepts: ['alignment', 'pointer-casting', 'safety-checks'],
    },
    {
      id: 'zig-safety-16',
      title: 'Fill Blank: Detect Memory Leak',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Use GPA deinit to detect a memory leak.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer {\n        const check = gpa.___();\n        if (check == .leak) {\n            std.debug.print("leak detected!", .{});\n        }\n    }\n    const alloc = gpa.allocator();\n    _ = alloc.alloc(u8, 64) catch return;\n    // Intentionally not freeing!\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer {\n        const check = gpa.deinit();\n        if (check == .leak) {\n            std.debug.print("leak detected!", .{});\n        }\n    }\n    const alloc = gpa.allocator();\n    _ = alloc.alloc(u8, 64) catch return;\n    // Intentionally not freeing!\n}`,
      hints: ['The GPA has a method that checks for leaks on cleanup.', 'deinit() returns a status indicating leaks.', 'Replace ___ with deinit.'],
      concepts: ['GeneralPurposeAllocator', 'leak-detection'],
    },
    {
      id: 'zig-safety-17',
      title: 'Refactor: Replace Unsafe Cast',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the unsafe truncation to use a safe checked cast.',
      skeleton: `const std = @import("std");\n\nfn toU8(value: u32) u8 {\n    return @truncate(value); // silently loses data\n}`,
      solution: `const std = @import("std");\n\nfn toU8(value: u32) ?u8 {\n    if (value > std.math.maxInt(u8)) return null;\n    return @intCast(value);\n}`,
      hints: ['@truncate silently discards high bits.', 'Return ?u8 and check the range first.', 'Use std.math.maxInt(u8) to check the upper bound.'],
      concepts: ['safe-casting', '@intCast', 'truncation'],
    },
    {
      id: 'zig-safety-18',
      title: 'Write: Safe Index Wrapper',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a generic safe indexing function that works with any slice type.',
      skeleton: `const std = @import("std");\n\n// Write safeIndex(comptime T: type, slice: []const T, idx: usize) -> ?T\n`,
      solution: `const std = @import("std");\n\nfn safeIndex(comptime T: type, slice: []const T, idx: usize) ?T {\n    if (idx >= slice.len) return null;\n    return slice[idx];\n}`,
      hints: ['Check bounds before indexing.', 'Use comptime T to make it generic.', 'Return ?T to indicate possible absence.'],
      concepts: ['generics', 'bounds-checking', 'optionals'],
    },
    {
      id: 'zig-safety-19',
      title: 'Refactor: Use Checked Arithmetic',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the function to return an error instead of potentially panicking.',
      skeleton: `const std = @import("std");\n\nfn computeArea(width: u32, height: u32) u32 {\n    return width * height;\n}\n\nfn computeVolume(w: u32, h: u32, d: u32) u32 {\n    return computeArea(w, h) * d;\n}`,
      solution: `const std = @import("std");\n\nfn computeArea(width: u32, height: u32) ?u32 {\n    const result = @mulWithOverflow(width, height);\n    if (result.@"1" != 0) return null;\n    return result.@"0";\n}\n\nfn computeVolume(w: u32, h: u32, d: u32) ?u32 {\n    const area = computeArea(w, h) orelse return null;\n    const result = @mulWithOverflow(area, d);\n    if (result.@"1" != 0) return null;\n    return result.@"0";\n}`,
      hints: ['Use @mulWithOverflow to detect overflow.', 'Return ?u32 instead of u32.', 'Chain the checks with orelse return null.'],
      concepts: ['@mulWithOverflow', 'checked-arithmetic', 'optionals'],
    },
    {
      id: 'zig-safety-20',
      title: 'Predict: GPA Leak Report',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict whether this code leaks memory.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    const alloc = gpa.allocator();\n    const a = alloc.alloc(u8, 10) catch return;\n    const b = alloc.alloc(u8, 20) catch return;\n    alloc.free(a);\n    alloc.free(b);\n    const status = gpa.deinit();\n    std.debug.print("{s}", .{if (status == .ok) "no leak" else "leak"});\n}`,
      solution: `no leak`,
      hints: ['Both allocations a and b are freed.', 'a is freed, then b is freed.', 'GPA deinit reports .ok when all memory is freed.'],
      concepts: ['GeneralPurposeAllocator', 'leak-detection'],
    },
  ]
};
