import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-perf',
  title: '43. Performance',
  explanation: `## Performance in Zig\n\nZig is designed for high-performance systems programming. It gives you fine-grained control over memory layout, SIMD, caching, and branch prediction.\n\n### Benchmarking\n\nUse \`std.time.Timer\` for measuring performance:\n\n\`\`\`zig\nvar timer = try std.time.Timer.start();\n// ... work ...\nconst elapsed = timer.read(); // nanoseconds\n\`\`\`\n\n### Data-Oriented Design\n\nZig encourages **Structure of Arrays (SoA)** over **Array of Structures (AoS)** for cache efficiency:\n\n\`\`\`zig\n// AoS - poor cache locality for position-only iteration\nconst Entity = struct { x: f32, y: f32, health: u32, name: []const u8 };\nvar entities: [1000]Entity = undefined;\n\n// SoA - excellent cache locality for position-only iteration\nconst Entities = struct {\n    x: [1000]f32,\n    y: [1000]f32,\n    health: [1000]u32,\n};\n\`\`\`\n\n### SIMD\n\nZig has first-class SIMD vector types:\n\n\`\`\`zig\nconst Vec4 = @Vector(4, f32);\nconst a = Vec4{ 1.0, 2.0, 3.0, 4.0 };\nconst b = Vec4{ 5.0, 6.0, 7.0, 8.0 };\nconst c = a + b; // SIMD addition\n\`\`\`\n\n### Branch Hints\n\n\`\`\`zig\nif (condition) {\n    @branchHint(.unlikely);\n    handleRareCase();\n}\n\`\`\`\n\n### @prefetch\n\nPrefetch data into cache before it's needed:\n\n\`\`\`zig\n@prefetch(ptr, .{ .locality = 3 });\n\`\`\``,
  exercises: [
    {
      id: 'zig-perf-1',
      title: 'Create SIMD Vector',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Declare a SIMD vector type with 4 f32 elements.',
      skeleton: `const std = @import("std");\n\nconst Vec4 = ___(4, f32);\n\npub fn main() void {\n    const v = Vec4{ 1.0, 2.0, 3.0, 4.0 };\n    std.debug.print("{d}", .{v[0]});\n}`,
      solution: `const std = @import("std");\n\nconst Vec4 = @Vector(4, f32);\n\npub fn main() void {\n    const v = Vec4{ 1.0, 2.0, 3.0, 4.0 };\n    std.debug.print("{d}", .{v[0]});\n}`,
      hints: ['SIMD vectors are created with a builtin.', '@Vector(N, T) creates an N-element vector of type T.', 'Replace ___ with @Vector.'],
      concepts: ['@Vector', 'SIMD'],
    },
    {
      id: 'zig-perf-2',
      title: 'SIMD Vector Addition',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the result of SIMD vector addition.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const V = @Vector(4, i32);\n    const a = V{ 1, 2, 3, 4 };\n    const b = V{ 10, 20, 30, 40 };\n    const c = a + b;\n    std.debug.print("{} {} {} {}", .{ c[0], c[1], c[2], c[3] });\n}`,
      solution: `11 22 33 44`,
      hints: ['SIMD addition is element-wise.', '1+10=11, 2+20=22, 3+30=33, 4+40=44.', 'Each lane is added independently.'],
      concepts: ['SIMD', 'vector-arithmetic'],
    },
    {
      id: 'zig-perf-3',
      title: 'SIMD Dot Product',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a dot product function using SIMD vectors.',
      skeleton: `const std = @import("std");\n\n// Write dotProduct that takes two @Vector(4, f32) and returns f32\n// Use SIMD multiply then @reduce(.Add, ...)\n`,
      solution: `const std = @import("std");\n\nfn dotProduct(a: @Vector(4, f32), b: @Vector(4, f32)) f32 {\n    const product = a * b;\n    return @reduce(.Add, product);\n}`,
      hints: ['First multiply the vectors element-wise.', 'Then use @reduce(.Add, ...) to sum all elements.', '@reduce collapses a vector to a scalar.'],
      concepts: ['SIMD', '@reduce', 'dot-product'],
    },
    {
      id: 'zig-perf-4',
      title: 'SoA Data Layout',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Convert AoS to SoA for better cache performance.',
      skeleton: `const std = @import("std");\n\n// SoA layout for particles\nconst Particles = ___{\n    x: [1000]f32,\n    y: [1000]f32,\n    vx: [1000]f32,\n    vy: [1000]f32,\n};`,
      solution: `const std = @import("std");\n\n// SoA layout for particles\nconst Particles = struct {\n    x: [1000]f32,\n    y: [1000]f32,\n    vx: [1000]f32,\n    vy: [1000]f32,\n};`,
      hints: ['SoA groups each field into its own array.', 'Use a struct to hold the parallel arrays.', 'Replace ___ with struct.'],
      concepts: ['SoA', 'data-oriented-design'],
    },
    {
      id: 'zig-perf-5',
      title: 'Write: SoA Update Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that updates positions using velocities in SoA layout.',
      skeleton: `const std = @import("std");\n\nconst N = 1000;\nconst Particles = struct {\n    x: [N]f32,\n    y: [N]f32,\n    vx: [N]f32,\n    vy: [N]f32,\n};\n\n// Write updatePositions(p: *Particles, dt: f32) void\n// x[i] += vx[i] * dt, y[i] += vy[i] * dt\n`,
      solution: `const std = @import("std");\n\nconst N = 1000;\nconst Particles = struct {\n    x: [N]f32,\n    y: [N]f32,\n    vx: [N]f32,\n    vy: [N]f32,\n};\n\nfn updatePositions(p: *Particles, dt: f32) void {\n    for (0..N) |i| {\n        p.x[i] += p.vx[i] * dt;\n        p.y[i] += p.vy[i] * dt;\n    }\n}`,
      hints: ['Iterate with for (0..N) |i|.', 'Update x[i] += vx[i] * dt for each particle.', 'SoA layout means sequential memory access for each field.'],
      concepts: ['SoA', 'cache-locality', 'particle-systems'],
    },
    {
      id: 'zig-perf-6',
      title: 'Fix: SIMD Type Mismatch',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the type mismatch in the SIMD operation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const a = @Vector(4, f32){ 1.0, 2.0, 3.0, 4.0 };\n    const b = @Vector(4, i32){ 5, 6, 7, 8 };\n    const c = a + b;\n    std.debug.print("{d}", .{c[0]});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const a = @Vector(4, f32){ 1.0, 2.0, 3.0, 4.0 };\n    const b = @Vector(4, f32){ 5.0, 6.0, 7.0, 8.0 };\n    const c = a + b;\n    std.debug.print("{d}", .{c[0]});\n}`,
      hints: ['SIMD operations require matching types.', 'a is f32 but b is i32.', 'Change b to @Vector(4, f32) with float literals.'],
      concepts: ['SIMD', 'type-matching'],
    },
    {
      id: 'zig-perf-7',
      title: 'Branch Hint: Unlikely',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Add a branch hint for an unlikely error path.',
      skeleton: `const std = @import("std");\n\nfn process(data: []const u8) !void {\n    if (data.len == 0) {\n        @___(.___);\n        return error.Empty;\n    }\n    // hot path continues...\n}`,
      solution: `const std = @import("std");\n\nfn process(data: []const u8) !void {\n    if (data.len == 0) {\n        @branchHint(.unlikely);\n        return error.Empty;\n    }\n    // hot path continues...\n}`,
      hints: ['Error paths are typically unlikely.', '@branchHint tells the optimizer about branch probability.', 'Use @branchHint(.unlikely) for rare branches.'],
      concepts: ['@branchHint', 'branch-prediction'],
    },
    {
      id: 'zig-perf-8',
      title: 'Predict: @reduce',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the result of @reduce on a SIMD vector.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const v = @Vector(4, i32){ 3, 7, 2, 8 };\n    const max = @reduce(.Max, v);\n    std.debug.print("{}", .{max});\n}`,
      solution: `8`,
      hints: ['@reduce(.Max, v) finds the maximum element.', 'The elements are 3, 7, 2, 8.', 'The maximum is 8.'],
      concepts: ['@reduce', 'SIMD'],
    },
    {
      id: 'zig-perf-9',
      title: 'Write: SIMD Min/Max Clamp',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a SIMD clamp function that clamps each element between min and max.',
      skeleton: `const std = @import("std");\n\n// Write simdClamp that takes @Vector(4, f32) val, f32 min_val, f32 max_val\n// Returns @Vector(4, f32) with each element clamped\n`,
      solution: `const std = @import("std");\n\nfn simdClamp(val: @Vector(4, f32), min_val: f32, max_val: f32) @Vector(4, f32) {\n    const min_v: @Vector(4, f32) = @splat(min_val);\n    const max_v: @Vector(4, f32) = @splat(max_val);\n    return @min(@max(val, min_v), max_v);\n}`,
      hints: ['Use @splat to broadcast a scalar to a vector.', 'Use @min and @max for element-wise clamping.', 'Clamp: @min(@max(val, min_v), max_v).'],
      concepts: ['@splat', '@min', '@max', 'SIMD'],
    },
    {
      id: 'zig-perf-10',
      title: 'noinline Function',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Mark a function as noinline to prevent inlining.',
      skeleton: `const std = @import("std");\n\n___ fn coldErrorHandler(err: anyerror) void {\n    std.log.err("error: {s}", .{@errorName(err)});\n}`,
      solution: `const std = @import("std");\n\nnoinline fn coldErrorHandler(err: anyerror) void {\n    std.log.err("error: {s}", .{@errorName(err)});\n}`,
      hints: ['noinline prevents the optimizer from inlining a function.', 'This is useful for cold paths to reduce code size.', 'Place noinline before fn.'],
      concepts: ['noinline', 'cold-functions'],
    },
    {
      id: 'zig-perf-11',
      title: 'Write: AoS to SoA Conversion',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that converts an array of structs to a struct of arrays.',
      skeleton: `const std = @import("std");\n\nconst Point = struct { x: f32, y: f32 };\nconst PointSoA = struct { x: [4]f32, y: [4]f32 };\n\n// Write aosToSoa that takes [4]Point and returns PointSoA\n`,
      solution: `const std = @import("std");\n\nconst Point = struct { x: f32, y: f32 };\nconst PointSoA = struct { x: [4]f32, y: [4]f32 };\n\nfn aosToSoa(points: [4]Point) PointSoA {\n    var result: PointSoA = undefined;\n    for (0..4) |i| {\n        result.x[i] = points[i].x;\n        result.y[i] = points[i].y;\n    }\n    return result;\n}`,
      hints: ['Iterate over the AoS array.', 'Copy each field into the corresponding SoA array.', 'result.x[i] = points[i].x for each index.'],
      concepts: ['AoS-to-SoA', 'data-layout'],
    },
    {
      id: 'zig-perf-12',
      title: 'Fix: Vector Splat Syntax',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the incorrect way of creating a vector filled with one value.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const V = @Vector(4, f32);\n    const ones = V{ 1.0, 1.0, 1.0, 1.0 };\n    const scaled = ones * V{ 5.0, 5.0, 5.0, 5.0 };\n    std.debug.print("{d}", .{@reduce(.Add, scaled)});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const V = @Vector(4, f32);\n    const ones: V = @splat(1.0);\n    const scaled = ones * @as(V, @splat(5.0));\n    std.debug.print("{d}", .{@reduce(.Add, scaled)});\n}`,
      hints: ['While the original works, @splat is more idiomatic.', 'Use @splat(value) to fill a vector with a single value.', '@splat(1.0) creates a vector of all 1.0s.'],
      concepts: ['@splat', 'SIMD'],
    },
    {
      id: 'zig-perf-13',
      title: 'Predict: SIMD Multiply Reduce',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the result of multiplying and reducing a SIMD vector.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const v = @Vector(4, i32){ 1, 2, 3, 4 };\n    const result = @reduce(.Mul, v);\n    std.debug.print("{}", .{result});\n}`,
      solution: `24`,
      hints: ['@reduce(.Mul, ...) multiplies all elements together.', '1 * 2 * 3 * 4 = 24.', 'This is the product of all vector elements.'],
      concepts: ['@reduce', 'SIMD'],
    },
    {
      id: 'zig-perf-14',
      title: 'Write: SIMD Array Sum',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that sums a slice of f32 values using SIMD 4-wide vectors.',
      skeleton: `const std = @import("std");\n\n// Write simdSum(data: []const f32) -> f32\n// Process 4 elements at a time with SIMD, handle remainder\n`,
      solution: `const std = @import("std");\n\nfn simdSum(data: []const f32) f32 {\n    const V = @Vector(4, f32);\n    var acc: V = @splat(0.0);\n    var i: usize = 0;\n    while (i + 4 <= data.len) : (i += 4) {\n        const chunk: V = data[i..][0..4].*;\n        acc += chunk;\n    }\n    var total = @reduce(.Add, acc);\n    while (i < data.len) : (i += 1) {\n        total += data[i];\n    }\n    return total;\n}`,
      hints: ['Process 4 elements at a time using @Vector(4, f32).', 'Accumulate in a SIMD register, then reduce.', 'Handle the remaining elements with a scalar loop.'],
      concepts: ['SIMD', 'vectorized-loop', '@reduce'],
    },
    {
      id: 'zig-perf-15',
      title: 'Refactor: AoS to SoA',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor this AoS struct to SoA for better cache performance when iterating positions.',
      skeleton: `const std = @import("std");\n\nconst Entity = struct {\n    x: f32,\n    y: f32,\n    health: u32,\n    armor: u32,\n};\n\nfn sumX(entities: []const Entity) f32 {\n    var total: f32 = 0;\n    for (entities) |e| {\n        total += e.x;\n    }\n    return total;\n}`,
      solution: `const std = @import("std");\n\nconst Entities = struct {\n    x: []f32,\n    y: []f32,\n    health: []u32,\n    armor: []u32,\n};\n\nfn sumX(entities: Entities) f32 {\n    var total: f32 = 0;\n    for (entities.x) |x| {\n        total += x;\n    }\n    return total;\n}`,
      hints: ['SoA stores each field in its own contiguous array.', 'This gives perfect cache locality when iterating one field.', 'Change the struct to hold slices for each field.'],
      concepts: ['SoA', 'cache-locality', 'refactoring'],
    },
    {
      id: 'zig-perf-16',
      title: 'Fill Blank: @prefetch',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Use @prefetch to pre-load data into cache.',
      skeleton: `const std = @import("std");\n\nfn processArray(data: []const f32) f32 {\n    var sum: f32 = 0;\n    for (data, 0..) |val, i| {\n        if (i + 16 < data.len) {\n            ___(data.ptr + i + 16, .{ .locality = 3 });\n        }\n        sum += val;\n    }\n    return sum;\n}`,
      solution: `const std = @import("std");\n\nfn processArray(data: []const f32) f32 {\n    var sum: f32 = 0;\n    for (data, 0..) |val, i| {\n        if (i + 16 < data.len) {\n            @prefetch(data.ptr + i + 16, .{ .locality = 3 });\n        }\n        sum += val;\n    }\n    return sum;\n}`,
      hints: ['@prefetch hints the CPU to load data into cache.', 'Locality 3 means high temporal locality (keep in cache).', 'Replace ___ with @prefetch.'],
      concepts: ['@prefetch', 'cache-optimization'],
    },
    {
      id: 'zig-perf-17',
      title: 'Write: SIMD Distance',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a SIMD-accelerated function to compute Euclidean distance between two 4D vectors.',
      skeleton: `const std = @import("std");\n\n// Write distance4D that takes two @Vector(4, f32)\n// Returns f32 Euclidean distance: sqrt(sum of (a-b)^2)\n`,
      solution: `const std = @import("std");\n\nfn distance4D(a: @Vector(4, f32), b: @Vector(4, f32)) f32 {\n    const diff = a - b;\n    const squared = diff * diff;\n    const sum = @reduce(.Add, squared);\n    return @sqrt(sum);\n}`,
      hints: ['Subtract the vectors element-wise.', 'Square the differences, then reduce with Add.', 'Use @sqrt for the final square root.'],
      concepts: ['SIMD', '@reduce', '@sqrt', 'distance'],
    },
    {
      id: 'zig-perf-18',
      title: 'Predict: Splat and Multiply',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict the result of a splat-multiply operation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const V = @Vector(4, i32);\n    const v = V{ 2, 4, 6, 8 };\n    const scale: V = @splat(3);\n    const result = v * scale;\n    std.debug.print("{}", .{@reduce(.Add, result)});\n}`,
      solution: `60`,
      hints: ['v * scale = {6, 12, 18, 24}.', '@reduce(.Add, ...) sums: 6 + 12 + 18 + 24.', '6 + 12 + 18 + 24 = 60.'],
      concepts: ['@splat', '@reduce', 'SIMD'],
    },
    {
      id: 'zig-perf-19',
      title: 'Refactor: Eliminate Branch',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor to remove the branch using branchless arithmetic.',
      skeleton: `const std = @import("std");\n\nfn absValue(x: i32) i32 {\n    if (x < 0) {\n        return -x;\n    } else {\n        return x;\n    }\n}`,
      solution: `const std = @import("std");\n\nfn absValue(x: i32) i32 {\n    return @as(i32, @intCast(std.math.absCast(x)));\n}`,
      hints: ['std.math.absCast computes absolute value.', 'This avoids a branch in the hot path.', 'Alternatively use @abs for unsigned result.'],
      concepts: ['branchless', 'std.math', 'performance'],
    },
    {
      id: 'zig-perf-20',
      title: 'Write: Cache-Friendly Matrix Transpose',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a cache-friendly in-place matrix transpose for a 4x4 f32 matrix.',
      skeleton: `const std = @import("std");\n\n// Write transpose4x4(m: *[4][4]f32) void\n// In-place transpose using swap\n`,
      solution: `const std = @import("std");\n\nfn transpose4x4(m: *[4][4]f32) void {\n    for (0..4) |i| {\n        for (i + 1..4) |j| {\n            const tmp = m[i][j];\n            m[i][j] = m[j][i];\n            m[j][i] = tmp;\n        }\n    }\n}`,
      hints: ['Swap elements across the diagonal.', 'Only iterate the upper triangle (j > i).', 'Swap m[i][j] with m[j][i].'],
      concepts: ['matrix-transpose', 'cache-friendly', 'in-place'],
    },
  ]
};
