import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-patterns',
  title: '44. Design Patterns',
  explanation: `## Design Patterns in Zig\n\nZig's comptime metaprogramming and explicit resource management enable unique approaches to classic design patterns.\n\n### Comptime Interfaces\n\nInstead of runtime vtables, Zig uses comptime duck typing:\n\n\`\`\`zig\nfn serialize(writer: anytype, value: anytype) !void {\n    // writer just needs a .write method\n    try writer.write(value);\n}\n\`\`\`\n\n### Virtual Dispatch via Function Pointers\n\nFor runtime polymorphism, Zig uses explicit function pointer tables:\n\n\`\`\`zig\nconst Drawable = struct {\n    ptr: *anyopaque,\n    drawFn: *const fn (*anyopaque) void,\n\n    fn draw(self: Drawable) void {\n        self.drawFn(self.ptr);\n    }\n};\n\`\`\`\n\n### RAII via defer\n\nZig's \`defer\` serves the same purpose as RAII destructors:\n\n\`\`\`zig\nconst file = try std.fs.cwd().openFile("data.txt", .{});\ndefer file.close();\n// file is guaranteed to be closed\n\`\`\`\n\n### Builder Pattern\n\n\`\`\`zig\nconst Config = struct {\n    width: u32 = 800,\n    height: u32 = 600,\n    title: []const u8 = "App",\n\n    fn setWidth(self: *Config, w: u32) *Config {\n        self.width = w;\n        return self;\n    }\n};\n\`\`\`\n\nZig favors explicitness, composition over inheritance, and compile-time polymorphism where possible.`,
  exercises: [
    {
      id: 'zig-patterns-1',
      title: 'Builder Pattern: Default Config',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Create a struct with default values as a builder pattern.',
      skeleton: `const std = @import("std");\n\nconst Config = struct {\n    width: u32 ___ 800,\n    height: u32 = 600,\n    fullscreen: bool = false,\n};\n\npub fn main() void {\n    const cfg = Config{};\n    std.debug.print("{}x{}", .{ cfg.width, cfg.height });\n}`,
      solution: `const std = @import("std");\n\nconst Config = struct {\n    width: u32 = 800,\n    height: u32 = 600,\n    fullscreen: bool = false,\n};\n\npub fn main() void {\n    const cfg = Config{};\n    std.debug.print("{}x{}", .{ cfg.width, cfg.height });\n}`,
      hints: ['Default values use = in struct field declarations.', 'Config{} creates an instance with all defaults.', 'Replace ___ with =.'],
      concepts: ['default-values', 'builder-pattern'],
    },
    {
      id: 'zig-patterns-2',
      title: 'RAII with Defer',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use defer for automatic resource cleanup.',
      skeleton: `const std = @import("std");\n\nfn processFile(path: []const u8) !void {\n    const file = try std.fs.cwd().openFile(path, .{});\n    ___ file.close();\n    // use file...\n}`,
      solution: `const std = @import("std");\n\nfn processFile(path: []const u8) !void {\n    const file = try std.fs.cwd().openFile(path, .{});\n    defer file.close();\n    // use file...\n}`,
      hints: ['defer ensures cleanup runs when the scope exits.', 'This is Zig equivalent of RAII.', 'Replace ___ with defer.'],
      concepts: ['defer', 'RAII', 'resource-management'],
    },
    {
      id: 'zig-patterns-3',
      title: 'Predict: Default Override',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the output when overriding a default field.',
      skeleton: `const std = @import("std");\n\nconst Opts = struct {\n    retries: u32 = 3,\n    timeout: u32 = 30,\n};\n\npub fn main() void {\n    const o = Opts{ .timeout = 60 };\n    std.debug.print("{} {}", .{ o.retries, o.timeout });\n}`,
      solution: `3 60`,
      hints: ['retries keeps its default value of 3.', 'timeout is overridden to 60.', 'Only the specified fields are changed.'],
      concepts: ['default-values', 'partial-initialization'],
    },
    {
      id: 'zig-patterns-4',
      title: 'Function Pointer Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a Logger interface using function pointers for runtime polymorphism.',
      skeleton: `const std = @import("std");\n\n// Define a Logger struct with:\n// - ptr: *anyopaque\n// - logFn: function pointer that takes *anyopaque and []const u8\n// - a log() method that dispatches to logFn\n`,
      solution: `const std = @import("std");\n\nconst Logger = struct {\n    ptr: *anyopaque,\n    logFn: *const fn (*anyopaque, []const u8) void,\n\n    fn log(self: Logger, msg: []const u8) void {\n        self.logFn(self.ptr, msg);\n    }\n};`,
      hints: ['Use *anyopaque for type-erased pointer.', 'The function pointer takes the erased pointer and message.', 'The log method just forwards to logFn.'],
      concepts: ['function-pointers', 'vtable', 'type-erasure'],
    },
    {
      id: 'zig-patterns-5',
      title: 'Comptime Interface: Serializable',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a comptime-checked serialize function using anytype.',
      skeleton: `const std = @import("std");\n\n// Write serialize(value: anytype) []const u8\n// At comptime, check that the type has a .toBytes() method\n// Call it and return the result\n`,
      solution: `const std = @import("std");\n\nfn serialize(value: anytype) []const u8 {\n    if (!@hasDecl(@TypeOf(value), "toBytes")) {\n        @compileError("Type must implement toBytes()");\n    }\n    return value.toBytes();\n}`,
      hints: ['Use @hasDecl to check for method existence at comptime.', '@compileError produces a clear error message.', 'Then just call value.toBytes().'],
      concepts: ['comptime-interfaces', '@hasDecl', '@compileError'],
    },
    {
      id: 'zig-patterns-6',
      title: 'Fix: Builder Method Chain',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the builder so methods can be chained.',
      skeleton: `const std = @import("std");\n\nconst Builder = struct {\n    width: u32 = 0,\n    height: u32 = 0,\n\n    fn setWidth(self: *Builder, w: u32) void {\n        self.width = w;\n    }\n\n    fn setHeight(self: *Builder, h: u32) void {\n        self.height = h;\n    }\n};\n\npub fn main() void {\n    var b = Builder{};\n    b.setWidth(100).setHeight(200);\n}`,
      solution: `const std = @import("std");\n\nconst Builder = struct {\n    width: u32 = 0,\n    height: u32 = 0,\n\n    fn setWidth(self: *Builder, w: u32) *Builder {\n        self.width = w;\n        return self;\n    }\n\n    fn setHeight(self: *Builder, h: u32) *Builder {\n        self.height = h;\n        return self;\n    }\n};\n\npub fn main() void {\n    var b = Builder{};\n    _ = b.setWidth(100).setHeight(200);\n}`,
      hints: ['Builder methods must return *Builder for chaining.', 'Change void return to *Builder.', 'Return self at the end of each method.'],
      concepts: ['builder-pattern', 'method-chaining'],
    },
    {
      id: 'zig-patterns-7',
      title: 'State Machine',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a simple state machine using an enum and switch.',
      skeleton: `const std = @import("std");\n\n// Define a State enum: Idle, Running, Paused, Stopped\n// Write a transition function that takes current State and Event\n// Events: Start, Pause, Resume, Stop\n// Returns the new State\n`,
      solution: `const std = @import("std");\n\nconst State = enum { idle, running, paused, stopped };\nconst Event = enum { start, pause, resume, stop };\n\nfn transition(state: State, event: Event) State {\n    return switch (state) {\n        .idle => switch (event) {\n            .start => .running,\n            else => state,\n        },\n        .running => switch (event) {\n            .pause => .paused,\n            .stop => .stopped,\n            else => state,\n        },\n        .paused => switch (event) {\n            .resume => .running,\n            .stop => .stopped,\n            else => state,\n        },\n        .stopped => state,\n    };\n}`,
      hints: ['Use nested switch for state/event combinations.', 'Each state handles specific events.', 'Invalid transitions return the current state.'],
      concepts: ['state-machine', 'enum', 'switch'],
    },
    {
      id: 'zig-patterns-8',
      title: 'Strategy Pattern',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Implement the strategy pattern using function pointers.',
      skeleton: `const std = @import("std");\n\nconst SortStrategy = ___ fn ([]i32) void;\n\nfn bubbleSort(data: []i32) void {\n    for (0..data.len) |_| {\n        for (0..data.len - 1) |j| {\n            if (data[j] > data[j + 1]) {\n                const tmp = data[j];\n                data[j] = data[j + 1];\n                data[j + 1] = tmp;\n            }\n        }\n    }\n}\n\nfn sortWith(data: []i32, strategy: SortStrategy) void {\n    strategy(data);\n}`,
      solution: `const std = @import("std");\n\nconst SortStrategy = *const fn ([]i32) void;\n\nfn bubbleSort(data: []i32) void {\n    for (0..data.len) |_| {\n        for (0..data.len - 1) |j| {\n            if (data[j] > data[j + 1]) {\n                const tmp = data[j];\n                data[j] = data[j + 1];\n                data[j + 1] = tmp;\n            }\n        }\n    }\n}\n\nfn sortWith(data: []i32, strategy: SortStrategy) void {\n    strategy(data);\n}`,
      hints: ['A strategy is a function pointer type.', 'Function pointer syntax is *const fn (args) ret.', 'Replace ___ with *const.'],
      concepts: ['strategy-pattern', 'function-pointers'],
    },
    {
      id: 'zig-patterns-9',
      title: 'Predict: Defer Order in Builder',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the order of defer execution.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    std.debug.print("1", .{});\n    defer std.debug.print("2", .{});\n    std.debug.print("3", .{});\n    defer std.debug.print("4", .{});\n    std.debug.print("5", .{});\n}`,
      solution: `13542`,
      hints: ['Defers execute in reverse order at scope exit.', 'First 1, 3, 5 print normally.', 'Then defers: 4 (last defer), then 2 (first defer).'],
      concepts: ['defer', 'execution-order'],
    },
    {
      id: 'zig-patterns-10',
      title: 'Observer Pattern',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Implement a simple observer/event emitter pattern.',
      skeleton: `const std = @import("std");\n\n// Define EventEmitter with:\n// - listeners: array of function pointers (max 8)\n// - count: number of registered listeners\n// - subscribe(callback) method\n// - emit() method that calls all listeners\n`,
      solution: `const std = @import("std");\n\nconst Callback = *const fn () void;\n\nconst EventEmitter = struct {\n    listeners: [8]?Callback = [_]?Callback{null} ** 8,\n    count: usize = 0,\n\n    fn subscribe(self: *EventEmitter, cb: Callback) void {\n        if (self.count < 8) {\n            self.listeners[self.count] = cb;\n            self.count += 1;\n        }\n    }\n\n    fn emit(self: *const EventEmitter) void {\n        for (self.listeners[0..self.count]) |maybe_cb| {\n            if (maybe_cb) |cb| cb();\n        }\n    }\n};`,
      hints: ['Store callbacks in a fixed-size array of optionals.', 'subscribe adds a callback and increments count.', 'emit iterates and calls each registered callback.'],
      concepts: ['observer-pattern', 'function-pointers', 'optionals'],
    },
    {
      id: 'zig-patterns-11',
      title: 'Factory Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a factory function that creates different shape types based on an enum.',
      skeleton: `const std = @import("std");\n\nconst ShapeKind = enum { circle, rectangle, triangle };\n\nconst Shape = struct {\n    kind: ShapeKind,\n    area: f64,\n};\n\n// Write createShape(kind: ShapeKind, param: f64) Shape\n// circle: area = pi * param^2\n// rectangle: area = param * param (square)\n// triangle: area = param * param * 0.5\n`,
      solution: `const std = @import("std");\n\nconst ShapeKind = enum { circle, rectangle, triangle };\n\nconst Shape = struct {\n    kind: ShapeKind,\n    area: f64,\n};\n\nfn createShape(kind: ShapeKind, param: f64) Shape {\n    const area = switch (kind) {\n        .circle => std.math.pi * param * param,\n        .rectangle => param * param,\n        .triangle => param * param * 0.5,\n    };\n    return Shape{ .kind = kind, .area = area };\n}`,
      hints: ['Use switch on the kind enum.', 'Calculate area differently for each shape.', 'Return a Shape struct with the kind and computed area.'],
      concepts: ['factory-pattern', 'switch', 'enum'],
    },
    {
      id: 'zig-patterns-12',
      title: 'Fix: Missing Errdefer Cleanup',
      type: 'fix-bug',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Fix the resource leak when the second allocation fails.',
      skeleton: `const std = @import("std");\n\nfn initPair(alloc: std.mem.Allocator) !struct { a: []u8, b: []u8 } {\n    const a = try alloc.alloc(u8, 100);\n    const b = try alloc.alloc(u8, 200); // if this fails, a leaks!\n    return .{ .a = a, .b = b };\n}`,
      solution: `const std = @import("std");\n\nfn initPair(alloc: std.mem.Allocator) !struct { a: []u8, b: []u8 } {\n    const a = try alloc.alloc(u8, 100);\n    errdefer alloc.free(a);\n    const b = try alloc.alloc(u8, 200);\n    return .{ .a = a, .b = b };\n}`,
      hints: ['If the second alloc fails, the first allocation leaks.', 'Use errdefer to free a if b allocation fails.', 'Add errdefer alloc.free(a) after allocating a.'],
      concepts: ['errdefer', 'resource-management', 'RAII'],
    },
    {
      id: 'zig-patterns-13',
      title: 'Mixin via usingnamespace',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Use a comptime mixin to add methods to a struct.',
      skeleton: `const std = @import("std");\n\nfn Printable(comptime Self: type) type {\n    return struct {\n        pub fn print(self: Self) void {\n            std.debug.print("{}", .{self.value});\n        }\n    };\n}\n\nconst MyNum = struct {\n    value: i32,\n    pub ___ Printable(MyNum);\n};`,
      solution: `const std = @import("std");\n\nfn Printable(comptime Self: type) type {\n    return struct {\n        pub fn print(self: Self) void {\n            std.debug.print("{}", .{self.value});\n        }\n    };\n}\n\nconst MyNum = struct {\n    value: i32,\n    pub usingnamespace Printable(MyNum);\n};`,
      hints: ['usingnamespace imports declarations into the current scope.', 'This is how Zig achieves mixin-like composition.', 'Replace ___ with usingnamespace.'],
      concepts: ['usingnamespace', 'mixin-pattern', 'comptime'],
    },
    {
      id: 'zig-patterns-14',
      title: 'Dependency Injection',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that takes an allocator and logger as injected dependencies.',
      skeleton: `const std = @import("std");\n\n// Write processData that takes:\n// - allocator: std.mem.Allocator (injected)\n// - log_fn: *const fn([]const u8) void (injected logger)\n// - input: []const u8\n// Allocates a copy of input, logs a message, returns the copy\n`,
      solution: `const std = @import("std");\n\nfn processData(\n    allocator: std.mem.Allocator,\n    log_fn: *const fn ([]const u8) void,\n    input: []const u8,\n) ![]u8 {\n    log_fn("processing data");\n    const copy = try allocator.alloc(u8, input.len);\n    @memcpy(copy, input);\n    return copy;\n}`,
      hints: ['Accept dependencies as parameters instead of globals.', 'The allocator and logger are passed in.', 'This makes the function testable and flexible.'],
      concepts: ['dependency-injection', 'allocator-pattern'],
    },
    {
      id: 'zig-patterns-15',
      title: 'Predict: Comptime Interface Check',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict whether the comptime check passes or fails.',
      skeleton: `const std = @import("std");\n\nconst Foo = struct {\n    value: i32,\n    pub fn getValue(self: Foo) i32 { return self.value; }\n};\n\nfn extract(obj: anytype) i32 {\n    if (!@hasDecl(@TypeOf(obj), "getValue")) @compileError("missing getValue");\n    return obj.getValue();\n}\n\npub fn main() void {\n    const f = Foo{ .value = 42 };\n    std.debug.print("{}", .{extract(f)});\n}`,
      solution: `42`,
      hints: ['Foo has a getValue declaration.', '@hasDecl returns true.', 'extract calls getValue which returns 42.'],
      concepts: ['comptime-interfaces', '@hasDecl'],
    },
    {
      id: 'zig-patterns-16',
      title: 'Refactor: Replace Switch with Vtable',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor the switch-based dispatch to use a vtable pattern.',
      skeleton: `const std = @import("std");\n\nconst Kind = enum { dog, cat };\n\nfn speak(kind: Kind) []const u8 {\n    return switch (kind) {\n        .dog => "woof",\n        .cat => "meow",\n    };\n}`,
      solution: `const std = @import("std");\n\nconst Animal = struct {\n    speakFn: *const fn () []const u8,\n\n    fn speak(self: Animal) []const u8 {\n        return self.speakFn();\n    }\n};\n\nfn dogSpeak() []const u8 { return "woof"; }\nfn catSpeak() []const u8 { return "meow"; }\n\nconst dog = Animal{ .speakFn = dogSpeak };\nconst cat = Animal{ .speakFn = catSpeak };`,
      hints: ['Replace the enum switch with a function pointer.', 'Each animal type provides its own speak function.', 'The Animal struct holds the function pointer.'],
      concepts: ['vtable', 'function-pointers', 'refactoring'],
    },
    {
      id: 'zig-patterns-17',
      title: 'Write: Generic Pool',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime generic object pool using a fixed-size array.',
      skeleton: `const std = @import("std");\n\n// Write Pool(comptime T: type, comptime size: usize) type\n// Has: items: [size]T, used: [size]bool\n// Methods: acquire() -> ?*T, release(*T) -> void\n`,
      solution: `const std = @import("std");\n\nfn Pool(comptime T: type, comptime size: usize) type {\n    return struct {\n        items: [size]T = undefined,\n        used: [size]bool = [_]bool{false} ** size,\n\n        const Self = @This();\n\n        fn acquire(self: *Self) ?*T {\n            for (&self.used, 0..) |*u, i| {\n                if (!u.*) {\n                    u.* = true;\n                    return &self.items[i];\n                }\n            }\n            return null;\n        }\n\n        fn release(self: *Self, ptr: *T) void {\n            const addr = @intFromPtr(ptr);\n            const base = @intFromPtr(&self.items);\n            const idx = (addr - base) / @sizeOf(T);\n            if (idx < size) self.used[idx] = false;\n        }\n    };\n}`,
      hints: ['Use a comptime function that returns a type.', 'Track availability with a bool array.', 'acquire finds the first unused slot, release marks it free.'],
      concepts: ['comptime-generics', 'object-pool', 'type-functions'],
    },
    {
      id: 'zig-patterns-18',
      title: 'Refactor: Use Comptime Interface',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor runtime type checking to comptime with anytype.',
      skeleton: `const std = @import("std");\n\nconst Writer = struct {\n    writeFn: *const fn ([]const u8) void,\n    fn write(self: Writer, data: []const u8) void {\n        self.writeFn(data);\n    }\n};\n\nfn output(w: Writer, msg: []const u8) void {\n    w.write(msg);\n}`,
      solution: `const std = @import("std");\n\nfn output(w: anytype, msg: []const u8) void {\n    w.write(msg);\n}`,
      hints: ['anytype lets Zig check the interface at comptime.', 'No need for explicit function pointer wrapping.', 'The function works with any type that has a write method.'],
      concepts: ['comptime-interfaces', 'anytype', 'refactoring'],
    },
    {
      id: 'zig-patterns-19',
      title: 'Fill Blank: Comptime Type Check',
      type: 'fill-blank',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Check if a type has a specific field at compile time.',
      skeleton: `const std = @import("std");\n\nfn hasField(comptime T: type, comptime name: []const u8) bool {\n    const fields = @typeInfo(T).@"struct".fields;\n    for (fields) |f| {\n        if (std.mem.eql(u8, f.___, name)) return true;\n    }\n    return false;\n}`,
      solution: `const std = @import("std");\n\nfn hasField(comptime T: type, comptime name: []const u8) bool {\n    const fields = @typeInfo(T).@"struct".fields;\n    for (fields) |f| {\n        if (std.mem.eql(u8, f.name, name)) return true;\n    }\n    return false;\n}`,
      hints: ['Each field in @typeInfo has a .name property.', 'Compare the field name with the target name.', 'Replace ___ with name.'],
      concepts: ['@typeInfo', 'comptime-reflection'],
    },
    {
      id: 'zig-patterns-20',
      title: 'Write: Comptime Dispatch Table',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a comptime function that generates a dispatch table from an enum.',
      skeleton: `const std = @import("std");\n\n// Write DispatchTable(comptime E: type, comptime RetT: type) type\n// Returns a struct with a handlers: array of ?*const fn() RetT\n// indexed by @intFromEnum, and a dispatch(E) -> ?RetT method\n`,
      solution: `const std = @import("std");\n\nfn DispatchTable(comptime E: type, comptime RetT: type) type {\n    const count = @typeInfo(E).@"enum".fields.len;\n    return struct {\n        handlers: [count]?*const fn () RetT = [_]?*const fn () RetT{null} ** count,\n\n        const Self = @This();\n\n        fn register(self: *Self, key: E, handler: *const fn () RetT) void {\n            self.handlers[@intFromEnum(key)] = handler;\n        }\n\n        fn dispatch(self: *const Self, key: E) ?RetT {\n            if (self.handlers[@intFromEnum(key)]) |handler| {\n                return handler();\n            }\n            return null;\n        }\n    };\n}`,
      hints: ['Use @typeInfo(E).@"enum".fields.len for array size.', 'Index with @intFromEnum(key).', 'Return a struct type with register and dispatch methods.'],
      concepts: ['comptime-generics', 'dispatch-table', '@intFromEnum'],
    },
  ]
};
