import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-mempat',
  title: '45. Memory Patterns',
  explanation: `## Memory Patterns in Zig\n\nZig gives you full control over memory allocation. The standard library provides several allocator implementations, and you can build your own.\n\n### Arena Allocator\n\nAllocates from a large buffer; frees everything at once:\n\n\`\`\`zig\nvar arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\ndefer arena.deinit(); // frees everything\nconst alloc = arena.allocator();\n\`\`\`\n\n### Fixed Buffer Allocator\n\nAllocates from a stack buffer with no heap:\n\n\`\`\`zig\nvar buf: [4096]u8 = undefined;\nvar fba = std.heap.FixedBufferAllocator.init(&buf);\nconst alloc = fba.allocator();\n\`\`\`\n\n### Page Allocator\n\nDirect OS page allocation:\n\n\`\`\`zig\nconst alloc = std.heap.page_allocator;\n\`\`\`\n\n### Custom Allocators\n\nImplement the \`std.mem.Allocator\` interface:\n\n\`\`\`zig\nconst MyAllocator = struct {\n    fn alloc(ctx: *anyopaque, len: usize, ...) ?[*]u8 {\n        // ...\n    }\n    fn resize(...) bool { ... }\n    fn free(ctx: *anyopaque, buf: []u8, ...) void { ... }\n};\n\`\`\`\n\n### Allocation Strategies\n\n- **Arena**: Fast, bulk-free. Great for request handling.\n- **Pool**: Fixed-size objects. O(1) alloc/free.\n- **Bump/Stack**: Linear allocation, no individual free.\n- **Free List**: Reuse freed blocks. Good for variable-size objects.`,
  exercises: [
    {
      id: 'zig-mempat-1',
      title: 'Arena Allocator Setup',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Set up an arena allocator with proper cleanup.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var arena = std.heap.ArenaAllocator.___(std.heap.page_allocator);\n    defer arena.deinit();\n    const alloc = arena.allocator();\n    _ = alloc;\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\n    defer arena.deinit();\n    const alloc = arena.allocator();\n    _ = alloc;\n}`,
      hints: ['ArenaAllocator is initialized with a backing allocator.', 'The init function takes the backing allocator.', 'Replace ___ with init.'],
      concepts: ['ArenaAllocator', 'allocator-pattern'],
    },
    {
      id: 'zig-mempat-2',
      title: 'Fixed Buffer Allocator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Create a stack-based allocator using a fixed buffer.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var buf: [1024]u8 = undefined;\n    var fba = std.heap.FixedBufferAllocator.___(&buf);\n    const alloc = fba.allocator();\n    const data = alloc.alloc(u8, 100) catch return;\n    _ = data;\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var buf: [1024]u8 = undefined;\n    var fba = std.heap.FixedBufferAllocator.init(&buf);\n    const alloc = fba.allocator();\n    const data = alloc.alloc(u8, 100) catch return;\n    _ = data;\n}`,
      hints: ['FixedBufferAllocator also uses init.', 'Pass a pointer to the buffer.', 'Replace ___ with init.'],
      concepts: ['FixedBufferAllocator', 'stack-allocation'],
    },
    {
      id: 'zig-mempat-3',
      title: 'Predict: Arena Bulk Free',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict what happens when an arena is deinitialized.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\n    const alloc = arena.allocator();\n    _ = alloc.alloc(u8, 100) catch return;\n    _ = alloc.alloc(u8, 200) catch return;\n    _ = alloc.alloc(u8, 300) catch return;\n    arena.deinit();\n    std.debug.print("done", .{});\n}`,
      solution: `done`,
      hints: ['Arena deinit frees all allocations at once.', 'No individual free calls are needed.', 'The program prints "done" after cleanup.'],
      concepts: ['ArenaAllocator', 'bulk-free'],
    },
    {
      id: 'zig-mempat-4',
      title: 'Write: Bump Allocator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a simple bump allocator that allocates linearly from a buffer.',
      skeleton: `const std = @import("std");\n\n// Write BumpAllocator struct with:\n// - buffer: []u8\n// - offset: usize = 0\n// - alloc(self: *BumpAllocator, size: usize) -> ?[]u8\n// - reset(self: *BumpAllocator) -> void\n`,
      solution: `const std = @import("std");\n\nconst BumpAllocator = struct {\n    buffer: []u8,\n    offset: usize = 0,\n\n    fn alloc(self: *BumpAllocator, size: usize) ?[]u8 {\n        if (self.offset + size > self.buffer.len) return null;\n        const start = self.offset;\n        self.offset += size;\n        return self.buffer[start..self.offset];\n    }\n\n    fn reset(self: *BumpAllocator) void {\n        self.offset = 0;\n    }\n};`,
      hints: ['Track the current offset into the buffer.', 'Allocate by advancing the offset.', 'Return null if not enough space remains.'],
      concepts: ['bump-allocator', 'linear-allocation'],
    },
    {
      id: 'zig-mempat-5',
      title: 'Pool Allocator Concept',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a fixed-size pool allocator for objects of a specific type.',
      skeleton: `const std = @import("std");\n\n// Write PoolAlloc(comptime T: type, comptime N: usize) type\n// Fixed pool of N items of type T\n// acquire() -> ?*T, release(*T) -> void\n`,
      solution: `const std = @import("std");\n\nfn PoolAlloc(comptime T: type, comptime N: usize) type {\n    return struct {\n        slots: [N]T = undefined,\n        free: [N]bool = [_]bool{true} ** N,\n\n        const Self = @This();\n\n        fn acquire(self: *Self) ?*T {\n            for (&self.free, 0..) |*f, i| {\n                if (f.*) {\n                    f.* = false;\n                    return &self.slots[i];\n                }\n            }\n            return null;\n        }\n\n        fn release(self: *Self, ptr: *T) void {\n            const idx = (@intFromPtr(ptr) - @intFromPtr(&self.slots)) / @sizeOf(T);\n            if (idx < N) self.free[idx] = true;\n        }\n    };\n}`,
      hints: ['Use a bool array to track which slots are free.', 'acquire finds the first free slot.', 'release computes the index from the pointer address.'],
      concepts: ['pool-allocator', 'comptime-generics'],
    },
    {
      id: 'zig-mempat-6',
      title: 'Fix: Double Free',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the double-free bug in this code.',
      skeleton: `const std = @import("std");\n\nfn process(alloc: std.mem.Allocator) !void {\n    const data = try alloc.alloc(u8, 100);\n    defer alloc.free(data);\n    // ... use data ...\n    alloc.free(data); // BUG: double free!\n}`,
      solution: `const std = @import("std");\n\nfn process(alloc: std.mem.Allocator) !void {\n    const data = try alloc.alloc(u8, 100);\n    defer alloc.free(data);\n    // ... use data ...\n}`,
      hints: ['defer already frees data when the function returns.', 'The explicit free call creates a double free.', 'Remove the redundant alloc.free(data) call.'],
      concepts: ['double-free', 'defer', 'resource-management'],
    },
    {
      id: 'zig-mempat-7',
      title: 'Arena for Request Handling',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a function that uses an arena for per-request allocation.',
      skeleton: `const std = @import("std");\n\n// Write handleRequest that:\n// - Creates an arena from page_allocator\n// - Allocates a response buffer\n// - Fills it with data\n// - Returns the arena (caller manages lifetime)\n`,
      solution: `const std = @import("std");\n\nconst RequestContext = struct {\n    arena: std.heap.ArenaAllocator,\n    response: []u8,\n};\n\nfn handleRequest(body: []const u8) !RequestContext {\n    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\n    errdefer arena.deinit();\n    const alloc = arena.allocator();\n    const response = try alloc.alloc(u8, body.len);\n    @memcpy(response, body);\n    return .{ .arena = arena, .response = response };\n}`,
      hints: ['Create an arena per request.', 'Use errdefer to clean up on failure.', 'Return the arena so the caller can deinit when done.'],
      concepts: ['ArenaAllocator', 'per-request-allocation', 'errdefer'],
    },
    {
      id: 'zig-mempat-8',
      title: 'Fill Blank: Page Allocator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Use the page allocator for direct OS memory allocation.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const alloc = std.heap.___;\n    const mem = alloc.alloc(u8, 4096) catch return;\n    defer alloc.free(mem);\n    std.debug.print("{}", .{mem.len});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const alloc = std.heap.page_allocator;\n    const mem = alloc.alloc(u8, 4096) catch return;\n    defer alloc.free(mem);\n    std.debug.print("{}", .{mem.len});\n}`,
      hints: ['The simplest allocator that goes directly to the OS.', 'std.heap.page_allocator allocates whole pages.', 'Replace ___ with page_allocator.'],
      concepts: ['page_allocator'],
    },
    {
      id: 'zig-mempat-9',
      title: 'Predict: FixedBuffer Exhaustion',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict what happens when a FixedBufferAllocator runs out of space.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var buf: [10]u8 = undefined;\n    var fba = std.heap.FixedBufferAllocator.init(&buf);\n    const alloc = fba.allocator();\n    const a = alloc.alloc(u8, 8) catch "fail1";\n    const b = alloc.alloc(u8, 8) catch "fail2";\n    if (@TypeOf(a) == @TypeOf(b)) {\n        std.debug.print("same", .{});\n    } else {\n        std.debug.print("diff", .{});\n    }\n}`,
      solution: `same`,
      hints: ['First alloc of 8 bytes succeeds (8 <= 10).', 'Second alloc of 8 bytes fails (only 2 left), caught as "fail2".', 'Both a and b are []const u8 after catch, so same type.'],
      concepts: ['FixedBufferAllocator', 'allocation-failure'],
    },
    {
      id: 'zig-mempat-10',
      title: 'Write: Free List',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a simple free list that reuses freed fixed-size blocks.',
      skeleton: `const std = @import("std");\n\n// Write FreeList(comptime block_size: usize, comptime max_blocks: usize) type\n// Maintains a stack of freed blocks for reuse\n// alloc() -> ?[*]u8, free([*]u8) -> void\n`,
      solution: `const std = @import("std");\n\nfn FreeList(comptime block_size: usize, comptime max_blocks: usize) type {\n    return struct {\n        storage: [max_blocks * block_size]u8 = undefined,\n        free_stack: [max_blocks]usize = undefined,\n        free_count: usize = max_blocks,\n\n        const Self = @This();\n\n        fn init() Self {\n            var self = Self{};\n            for (0..max_blocks) |i| {\n                self.free_stack[i] = i;\n            }\n            return self;\n        }\n\n        fn alloc(self: *Self) ?[]u8 {\n            if (self.free_count == 0) return null;\n            self.free_count -= 1;\n            const idx = self.free_stack[self.free_count];\n            const start = idx * block_size;\n            return self.storage[start .. start + block_size];\n        }\n\n        fn free(self: *Self, block: []u8) void {\n            const offset = @intFromPtr(block.ptr) - @intFromPtr(&self.storage);\n            const idx = offset / block_size;\n            self.free_stack[self.free_count] = idx;\n            self.free_count += 1;\n        }\n    };\n}`,
      hints: ['Maintain a stack of free block indices.', 'Alloc pops from the free stack.', 'Free pushes the block index back onto the stack.'],
      concepts: ['free-list', 'memory-reuse'],
    },
    {
      id: 'zig-mempat-11',
      title: 'Fix: Use After Free',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the use-after-free bug.',
      skeleton: `const std = @import("std");\n\nfn makeGreeting(alloc: std.mem.Allocator) ![]const u8 {\n    const buf = try alloc.alloc(u8, 5);\n    @memcpy(buf, "hello");\n    alloc.free(buf);\n    return buf; // BUG: returning freed memory!\n}`,
      solution: `const std = @import("std");\n\nfn makeGreeting(alloc: std.mem.Allocator) ![]u8 {\n    const buf = try alloc.alloc(u8, 5);\n    @memcpy(buf, "hello");\n    return buf;\n}`,
      hints: ['The buffer is freed before being returned.', 'Remove the free call -- the caller owns the memory.', 'The caller is responsible for freeing the returned buffer.'],
      concepts: ['use-after-free', 'ownership'],
    },
    {
      id: 'zig-mempat-12',
      title: 'Arena Reset Pattern',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use arena reset to reuse memory across iterations.',
      skeleton: `const std = @import("std");\n\nfn processLoop() !void {\n    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\n    defer arena.deinit();\n    \n    for (0..10) |_| {\n        _ = arena.___(.retain_capacity);\n        const alloc = arena.allocator();\n        const data = try alloc.alloc(u8, 1024);\n        _ = data;\n    }\n}`,
      solution: `const std = @import("std");\n\nfn processLoop() !void {\n    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);\n    defer arena.deinit();\n    \n    for (0..10) |_| {\n        _ = arena.reset(.retain_capacity);\n        const alloc = arena.allocator();\n        const data = try alloc.alloc(u8, 1024);\n        _ = data;\n    }\n}`,
      hints: ['Arena has a reset method to reuse memory.', '.retain_capacity keeps the underlying pages.', 'Replace ___ with reset.'],
      concepts: ['arena-reset', 'memory-reuse'],
    },
    {
      id: 'zig-mempat-13',
      title: 'Write: Stack Fallback Allocator',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Create a pattern that tries stack allocation first, then falls back to heap.',
      skeleton: `const std = @import("std");\n\n// Write a function that uses FixedBufferAllocator with fallback\n// If stack buffer is full, fall back to GPA\n// Return the allocator interface\n`,
      solution: `const std = @import("std");\n\nfn createFallbackAllocator(\n    buf: []u8,\n    gpa: *std.heap.GeneralPurposeAllocator(.{}),\n) std.heap.StackFallbackAllocator(4096) {\n    return std.heap.stackFallback(4096, gpa.allocator());\n}`,
      hints: ['std.heap.stackFallback creates a stack+heap allocator.', 'It tries the stack buffer first.', 'Falls back to the backing allocator when full.'],
      concepts: ['stack-fallback', 'allocator-composition'],
    },
    {
      id: 'zig-mempat-14',
      title: 'Predict: Allocation Size',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the size of the allocated slice.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var buf: [100]u8 = undefined;\n    var fba = std.heap.FixedBufferAllocator.init(&buf);\n    const alloc = fba.allocator();\n    const a = alloc.alloc(u8, 30) catch return;\n    const b = alloc.alloc(u8, 30) catch return;\n    std.debug.print("{} {}", .{ a.len, b.len });\n}`,
      solution: `30 30`,
      hints: ['First allocation gets 30 bytes.', 'Second allocation gets another 30 bytes.', 'Both fit within the 100-byte buffer.'],
      concepts: ['FixedBufferAllocator', 'allocation'],
    },
    {
      id: 'zig-mempat-15',
      title: 'Write: Memory-Mapped Buffer',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a function that creates a large allocation using page_allocator and maps it for use.',
      skeleton: `const std = @import("std");\n\n// Write createMappedBuffer(size: usize) -> ![]align(std.mem.page_size) u8\n// Use page_allocator to allocate page-aligned memory\n`,
      solution: `const std = @import("std");\n\nfn createMappedBuffer(size: usize) ![]align(std.mem.page_size) u8 {\n    const aligned_size = std.mem.alignForward(usize, size, std.mem.page_size);\n    const slice = try std.heap.page_allocator.alignedAlloc(u8, std.mem.page_size, aligned_size);\n    return slice;\n}`,
      hints: ['Use std.heap.page_allocator.alignedAlloc.', 'Align the size up to page boundaries.', 'std.mem.alignForward rounds up to alignment.'],
      concepts: ['page_allocator', 'aligned-allocation'],
    },
    {
      id: 'zig-mempat-16',
      title: 'Fix: Errdefer Missing in Chain',
      type: 'fix-bug',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Fix the memory leak when the third allocation fails.',
      skeleton: `const std = @import("std");\n\nfn initThree(alloc: std.mem.Allocator) !struct { a: []u8, b: []u8, c: []u8 } {\n    const a = try alloc.alloc(u8, 100);\n    const b = try alloc.alloc(u8, 200);\n    const c = try alloc.alloc(u8, 300);\n    return .{ .a = a, .b = b, .c = c };\n}`,
      solution: `const std = @import("std");\n\nfn initThree(alloc: std.mem.Allocator) !struct { a: []u8, b: []u8, c: []u8 } {\n    const a = try alloc.alloc(u8, 100);\n    errdefer alloc.free(a);\n    const b = try alloc.alloc(u8, 200);\n    errdefer alloc.free(b);\n    const c = try alloc.alloc(u8, 300);\n    return .{ .a = a, .b = b, .c = c };\n}`,
      hints: ['Each allocation after the first needs an errdefer.', 'If b fails, a leaks. If c fails, both a and b leak.', 'Add errdefer alloc.free(a) and errdefer alloc.free(b).'],
      concepts: ['errdefer', 'chained-allocation'],
    },
    {
      id: 'zig-mempat-17',
      title: 'Refactor: Replace Global with Injected Allocator',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor to inject the allocator instead of using a global.',
      skeleton: `const std = @import("std");\n\nvar global_alloc = std.heap.page_allocator;\n\nfn createBuffer(size: usize) ![]u8 {\n    return global_alloc.alloc(u8, size);\n}\n\nfn freeBuffer(buf: []u8) void {\n    global_alloc.free(buf);\n}`,
      solution: `const std = @import("std");\n\nfn createBuffer(alloc: std.mem.Allocator, size: usize) ![]u8 {\n    return alloc.alloc(u8, size);\n}\n\nfn freeBuffer(alloc: std.mem.Allocator, buf: []u8) void {\n    alloc.free(buf);\n}`,
      hints: ['Pass the allocator as a parameter.', 'Remove the global variable.', 'This is the idiomatic Zig pattern for allocation.'],
      concepts: ['allocator-injection', 'dependency-injection'],
    },
    {
      id: 'zig-mempat-18',
      title: 'Refactor: Consolidate Cleanup',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor individual allocations to use an arena for simpler cleanup.',
      skeleton: `const std = @import("std");\n\nfn buildReport(alloc: std.mem.Allocator) !void {\n    const header = try alloc.alloc(u8, 100);\n    defer alloc.free(header);\n    const body = try alloc.alloc(u8, 500);\n    defer alloc.free(body);\n    const footer = try alloc.alloc(u8, 50);\n    defer alloc.free(footer);\n    // use header, body, footer...\n}`,
      solution: `const std = @import("std");\n\nfn buildReport(backing: std.mem.Allocator) !void {\n    var arena = std.heap.ArenaAllocator.init(backing);\n    defer arena.deinit();\n    const alloc = arena.allocator();\n    const header = try alloc.alloc(u8, 100);\n    const body = try alloc.alloc(u8, 500);\n    const footer = try alloc.alloc(u8, 50);\n    _ = .{ header, body, footer };\n    // use header, body, footer...\n    // arena.deinit() frees everything\n}`,
      hints: ['An arena frees all allocations at once on deinit.', 'Replace individual defer free calls with one arena deinit.', 'This simplifies cleanup and is less error-prone.'],
      concepts: ['ArenaAllocator', 'bulk-free', 'refactoring'],
    },
    {
      id: 'zig-mempat-19',
      title: 'Write: Slab Allocator',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a slab allocator that manages fixed-size chunks from a larger buffer.',
      skeleton: `const std = @import("std");\n\n// Write SlabAllocator(comptime chunk_size: usize) type\n// Manages slabs from a provided buffer\n// init(buf), alloc() -> ?[]u8, free([]u8) -> void\n`,
      solution: `const std = @import("std");\n\nfn SlabAllocator(comptime chunk_size: usize) type {\n    return struct {\n        buf: []u8,\n        bitmap: [256]bool = [_]bool{false} ** 256,\n        num_chunks: usize,\n\n        const Self = @This();\n\n        fn init(buf: []u8) Self {\n            return .{\n                .buf = buf,\n                .num_chunks = buf.len / chunk_size,\n            };\n        }\n\n        fn alloc(self: *Self) ?[]u8 {\n            for (0..self.num_chunks) |i| {\n                if (!self.bitmap[i]) {\n                    self.bitmap[i] = true;\n                    const start = i * chunk_size;\n                    return self.buf[start .. start + chunk_size];\n                }\n            }\n            return null;\n        }\n\n        fn free(self: *Self, chunk: []u8) void {\n            const offset = @intFromPtr(chunk.ptr) - @intFromPtr(self.buf.ptr);\n            const idx = offset / chunk_size;\n            if (idx < self.num_chunks) self.bitmap[idx] = false;\n        }\n    };\n}`,
      hints: ['Divide the buffer into fixed-size chunks.', 'Use a bitmap to track which chunks are in use.', 'Alloc finds a free chunk, free marks it available.'],
      concepts: ['slab-allocator', 'bitmap', 'memory-management'],
    },
    {
      id: 'zig-mempat-20',
      title: 'Predict: Arena vs GPA Leak',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Predict whether the arena-based code leaks.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    var arena = std.heap.ArenaAllocator.init(gpa.allocator());\n    const alloc = arena.allocator();\n    _ = alloc.alloc(u8, 100) catch return;\n    _ = alloc.alloc(u8, 200) catch return;\n    arena.deinit();\n    const check = gpa.deinit();\n    std.debug.print("{s}", .{if (check == .ok) "clean" else "leak"});\n}`,
      solution: `clean`,
      hints: ['Arena deinit frees all memory back to the backing allocator.', 'The GPA is the backing allocator here.', 'After arena deinit, the GPA sees no leaks.'],
      concepts: ['ArenaAllocator', 'GeneralPurposeAllocator', 'leak-detection'],
    },
  ]
};
