import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'zig-ds',
  title: '46. Data Structures',
  explanation: `## Data Structures in Zig\n\nZig's standard library provides several fundamental data structures, and the language's comptime generics make it straightforward to build your own.\n\n### Standard Library Data Structures\n\n\`\`\`zig\n// Dynamic array\nvar list = std.ArrayList(i32).init(allocator);\ntry list.append(42);\n\n// Hash map\nvar map = std.AutoHashMap([]const u8, i32).init(allocator);\ntry map.put("key", 42);\n\n// Linked list\nvar ll = std.SinglyLinkedList(i32){};\n\`\`\`\n\n### Building Custom Data Structures\n\nZig's comptime generics let you build type-safe containers:\n\n\`\`\`zig\nfn Stack(comptime T: type) type {\n    return struct {\n        items: std.ArrayList(T),\n        \n        fn push(self: *@This(), val: T) !void {\n            try self.items.append(val);\n        }\n        \n        fn pop(self: *@This()) ?T {\n            return self.items.popOrNull();\n        }\n    };\n}\n\`\`\`\n\n### Key Principles\n\n- **Allocator injection**: All heap-using structures accept an allocator\n- **Comptime generics**: Type safety without runtime cost\n- **Manual memory management**: You control allocation and deallocation\n- **No hidden allocations**: Every allocation is explicit`,
  exercises: [
    {
      id: 'zig-ds-1',
      title: 'ArrayList Init',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Initialize an ArrayList of i32.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var list = std.ArrayList(i32).___(gpa.allocator());\n    defer list.deinit();\n    list.append(42) catch return;\n    std.debug.print("{}", .{list.items[0]});\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var list = std.ArrayList(i32).init(gpa.allocator());\n    defer list.deinit();\n    list.append(42) catch return;\n    std.debug.print("{}", .{list.items[0]});\n}`,
      hints: ['ArrayList is initialized with an allocator.', 'Use .init(allocator) to create the list.', 'Replace ___ with init.'],
      concepts: ['ArrayList', 'initialization'],
    },
    {
      id: 'zig-ds-2',
      title: 'Predict: ArrayList Length',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Predict the number of items after appending.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var list = std.ArrayList(i32).init(gpa.allocator());\n    defer list.deinit();\n    list.append(1) catch return;\n    list.append(2) catch return;\n    list.append(3) catch return;\n    std.debug.print("{}", .{list.items.len});\n}`,
      solution: `3`,
      hints: ['Three items are appended.', 'list.items.len reflects the current count.', 'The answer is 3.'],
      concepts: ['ArrayList', 'length'],
    },
    {
      id: 'zig-ds-3',
      title: 'Write: Generic Stack',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Write a generic stack type using ArrayList.',
      skeleton: `const std = @import("std");\n\n// Write Stack(comptime T: type) type\n// Methods: init(allocator), deinit(), push(T) !void, pop() ?T, peek() ?T\n`,
      solution: `const std = @import("std");\n\nfn Stack(comptime T: type) type {\n    return struct {\n        items: std.ArrayList(T),\n\n        const Self = @This();\n\n        fn init(allocator: std.mem.Allocator) Self {\n            return .{ .items = std.ArrayList(T).init(allocator) };\n        }\n\n        fn deinit(self: *Self) void {\n            self.items.deinit();\n        }\n\n        fn push(self: *Self, val: T) !void {\n            try self.items.append(val);\n        }\n\n        fn pop(self: *Self) ?T {\n            return self.items.popOrNull();\n        }\n\n        fn peek(self: *Self) ?T {\n            if (self.items.items.len == 0) return null;\n            return self.items.items[self.items.items.len - 1];\n        }\n    };\n}`,
      hints: ['Wrap ArrayList as the backing store.', 'push appends, pop uses popOrNull.', 'peek returns the last item without removing.'],
      concepts: ['stack', 'comptime-generics', 'ArrayList'],
    },
    {
      id: 'zig-ds-4',
      title: 'HashMap Lookup',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'zig',
      goal: 'Look up a value in an AutoHashMap.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var map = std.AutoHashMap(i32, []const u8).init(gpa.allocator());\n    defer map.deinit();\n    map.put(1, "one") catch return;\n    if (map.___(1)) |val| {\n        std.debug.print("{s}", .{val});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var map = std.AutoHashMap(i32, []const u8).init(gpa.allocator());\n    defer map.deinit();\n    map.put(1, "one") catch return;\n    if (map.get(1)) |val| {\n        std.debug.print("{s}", .{val});\n    }\n}`,
      hints: ['Use .get(key) to look up values in a HashMap.', 'It returns an optional.', 'Replace ___ with get.'],
      concepts: ['AutoHashMap', 'lookup'],
    },
    {
      id: 'zig-ds-5',
      title: 'Write: Queue using ArrayList',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a generic FIFO queue type.',
      skeleton: `const std = @import("std");\n\n// Write Queue(comptime T: type) type\n// Methods: init(allocator), deinit(), enqueue(T) !void, dequeue() ?T\n`,
      solution: `const std = @import("std");\n\nfn Queue(comptime T: type) type {\n    return struct {\n        items: std.ArrayList(T),\n\n        const Self = @This();\n\n        fn init(allocator: std.mem.Allocator) Self {\n            return .{ .items = std.ArrayList(T).init(allocator) };\n        }\n\n        fn deinit(self: *Self) void {\n            self.items.deinit();\n        }\n\n        fn enqueue(self: *Self, val: T) !void {\n            try self.items.append(val);\n        }\n\n        fn dequeue(self: *Self) ?T {\n            if (self.items.items.len == 0) return null;\n            return self.items.orderedRemove(0);\n        }\n    };\n}`,
      hints: ['enqueue appends to the end.', 'dequeue removes from the front (index 0).', 'Use orderedRemove(0) for FIFO behavior.'],
      concepts: ['queue', 'FIFO', 'comptime-generics'],
    },
    {
      id: 'zig-ds-6',
      title: 'Fix: HashMap Missing Deinit',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the memory leak by adding proper cleanup.',
      skeleton: `const std = @import("std");\n\nfn countWords(alloc: std.mem.Allocator, words: []const []const u8) !std.AutoHashMap([]const u8, u32) {\n    var map = std.AutoHashMap([]const u8, u32).init(alloc);\n    for (words) |word| {\n        const entry = try map.getOrPutValue(word, 0);\n        entry.value_ptr.* += 1;\n    }\n    return map;\n}`,
      solution: `const std = @import("std");\n\nfn countWords(alloc: std.mem.Allocator, words: []const []const u8) !std.AutoHashMap([]const u8, u32) {\n    var map = std.AutoHashMap([]const u8, u32).init(alloc);\n    errdefer map.deinit();\n    for (words) |word| {\n        const entry = try map.getOrPutValue(word, 0);\n        entry.value_ptr.* += 1;\n    }\n    return map;\n}`,
      hints: ['If an operation inside the loop fails, the map leaks.', 'Add errdefer map.deinit() for cleanup on error.', 'The caller is responsible for deinit on success.'],
      concepts: ['errdefer', 'HashMap', 'resource-management'],
    },
    {
      id: 'zig-ds-7',
      title: 'Write: Ring Buffer',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Write a fixed-size ring buffer (circular buffer).',
      skeleton: `const std = @import("std");\n\n// Write RingBuffer(comptime T: type, comptime N: usize) type\n// Methods: push(T), pop() ?T, len() usize\n// Overwrites oldest when full\n`,
      solution: `const std = @import("std");\n\nfn RingBuffer(comptime T: type, comptime N: usize) type {\n    return struct {\n        buf: [N]T = undefined,\n        head: usize = 0,\n        tail: usize = 0,\n        count: usize = 0,\n\n        const Self = @This();\n\n        fn push(self: *Self, val: T) void {\n            self.buf[self.head] = val;\n            self.head = (self.head + 1) % N;\n            if (self.count == N) {\n                self.tail = (self.tail + 1) % N;\n            } else {\n                self.count += 1;\n            }\n        }\n\n        fn pop(self: *Self) ?T {\n            if (self.count == 0) return null;\n            const val = self.buf[self.tail];\n            self.tail = (self.tail + 1) % N;\n            self.count -= 1;\n            return val;\n        }\n\n        fn len(self: *const Self) usize {\n            return self.count;\n        }\n    };\n}`,
      hints: ['Use head and tail indices with modulo N.', 'When full, advance tail to overwrite oldest.', 'Pop from tail, push at head.'],
      concepts: ['ring-buffer', 'circular-buffer', 'modular-arithmetic'],
    },
    {
      id: 'zig-ds-8',
      title: 'Predict: Stack Operations',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output of stack push/pop operations.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var list = std.ArrayList(i32).init(gpa.allocator());\n    defer list.deinit();\n    list.append(10) catch return;\n    list.append(20) catch return;\n    list.append(30) catch return;\n    const a = list.popOrNull() orelse 0;\n    const b = list.popOrNull() orelse 0;\n    std.debug.print("{} {}", .{ a, b });\n}`,
      solution: `30 20`,
      hints: ['Items are pushed: 10, 20, 30.', 'Pop returns last-in: 30, then 20.', 'This is LIFO (stack) behavior.'],
      concepts: ['stack', 'LIFO', 'ArrayList'],
    },
    {
      id: 'zig-ds-9',
      title: 'Write: Binary Search Tree',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a basic binary search tree with insert and contains operations.',
      skeleton: `const std = @import("std");\n\n// Write BST(comptime T: type) type\n// Node has: value: T, left: ?*Node, right: ?*Node\n// Methods: init(allocator), insert(T) !void, contains(T) bool\n`,
      solution: `const std = @import("std");\n\nfn BST(comptime T: type) type {\n    return struct {\n        const Node = struct {\n            value: T,\n            left: ?*Node = null,\n            right: ?*Node = null,\n        };\n\n        root: ?*Node = null,\n        allocator: std.mem.Allocator,\n\n        const Self = @This();\n\n        fn init(allocator: std.mem.Allocator) Self {\n            return .{ .allocator = allocator };\n        }\n\n        fn insert(self: *Self, value: T) !void {\n            try self.insertAt(&self.root, value);\n        }\n\n        fn insertAt(self: *Self, node_ptr: *?*Node, value: T) !void {\n            if (node_ptr.*) |node| {\n                if (value < node.value) {\n                    try self.insertAt(&node.left, value);\n                } else if (value > node.value) {\n                    try self.insertAt(&node.right, value);\n                }\n            } else {\n                const new = try self.allocator.create(Node);\n                new.* = .{ .value = value };\n                node_ptr.* = new;\n            }\n        }\n\n        fn contains(self: *const Self, value: T) bool {\n            var current = self.root;\n            while (current) |node| {\n                if (value == node.value) return true;\n                current = if (value < node.value) node.left else node.right;\n            }\n            return false;\n        }\n    };\n}`,
      hints: ['Each node has left and right optional pointers.', 'Insert recursively finds the correct position.', 'Contains traverses comparing values.'],
      concepts: ['binary-search-tree', 'recursive-data-structure'],
    },
    {
      id: 'zig-ds-10',
      title: 'Fill Blank: SinglyLinkedList',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Use the standard library SinglyLinkedList.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    const L = std.SinglyLinkedList(i32);\n    var list = L{};\n    var node1 = L.Node{ .data = 10 };\n    var node2 = L.Node{ .data = 20 };\n    list.___(& node2);\n    list.prepend(&node1);\n    if (list.first) |n| {\n        std.debug.print("{}", .{n.data});\n    }\n}`,
      solution: `const std = @import("std");\n\npub fn main() void {\n    const L = std.SinglyLinkedList(i32);\n    var list = L{};\n    var node1 = L.Node{ .data = 10 };\n    var node2 = L.Node{ .data = 20 };\n    list.prepend(&node2);\n    list.prepend(&node1);\n    if (list.first) |n| {\n        std.debug.print("{}", .{n.data});\n    }\n}`,
      hints: ['SinglyLinkedList has a prepend method.', 'Prepend adds to the front of the list.', 'Replace ___ with prepend.'],
      concepts: ['SinglyLinkedList', 'linked-list'],
    },
    {
      id: 'zig-ds-11',
      title: 'Write: Priority Queue',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a min-heap priority queue using an ArrayList.',
      skeleton: `const std = @import("std");\n\n// Write MinHeap(comptime T: type) type\n// Methods: init(allocator), insert(T) !void, extractMin() ?T\n`,
      solution: `const std = @import("std");\n\nfn MinHeap(comptime T: type) type {\n    return struct {\n        items: std.ArrayList(T),\n\n        const Self = @This();\n\n        fn init(allocator: std.mem.Allocator) Self {\n            return .{ .items = std.ArrayList(T).init(allocator) };\n        }\n\n        fn deinit(self: *Self) void {\n            self.items.deinit();\n        }\n\n        fn insert(self: *Self, val: T) !void {\n            try self.items.append(val);\n            self.siftUp(self.items.items.len - 1);\n        }\n\n        fn extractMin(self: *Self) ?T {\n            if (self.items.items.len == 0) return null;\n            const min = self.items.items[0];\n            const last = self.items.pop();\n            if (self.items.items.len > 0) {\n                self.items.items[0] = last;\n                self.siftDown(0);\n            }\n            return min;\n        }\n\n        fn siftUp(self: *Self, idx: usize) void {\n            var i = idx;\n            while (i > 0) {\n                const parent = (i - 1) / 2;\n                if (self.items.items[i] < self.items.items[parent]) {\n                    const tmp = self.items.items[i];\n                    self.items.items[i] = self.items.items[parent];\n                    self.items.items[parent] = tmp;\n                    i = parent;\n                } else break;\n            }\n        }\n\n        fn siftDown(self: *Self, idx: usize) void {\n            var i = idx;\n            const len = self.items.items.len;\n            while (2 * i + 1 < len) {\n                var smallest = 2 * i + 1;\n                if (smallest + 1 < len and self.items.items[smallest + 1] < self.items.items[smallest]) {\n                    smallest += 1;\n                }\n                if (self.items.items[i] > self.items.items[smallest]) {\n                    const tmp = self.items.items[i];\n                    self.items.items[i] = self.items.items[smallest];\n                    self.items.items[smallest] = tmp;\n                    i = smallest;\n                } else break;\n            }\n        }\n    };\n}`,
      hints: ['Use an ArrayList as the backing array for the heap.', 'Insert appends then sifts up.', 'Extract swaps root with last, pops, then sifts down.'],
      concepts: ['priority-queue', 'min-heap', 'sift-up-down'],
    },
    {
      id: 'zig-ds-12',
      title: 'Fix: Linked List Traversal',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Fix the infinite loop in linked list traversal.',
      skeleton: `const std = @import("std");\n\nconst Node = struct {\n    value: i32,\n    next: ?*Node = null,\n};\n\nfn sum(head: ?*Node) i32 {\n    var total: i32 = 0;\n    var current = head;\n    while (current) |node| {\n        total += node.value;\n        // BUG: missing advance!\n    }\n    return total;\n}`,
      solution: `const std = @import("std");\n\nconst Node = struct {\n    value: i32,\n    next: ?*Node = null,\n};\n\nfn sum(head: ?*Node) i32 {\n    var total: i32 = 0;\n    var current = head;\n    while (current) |node| {\n        total += node.value;\n        current = node.next;\n    }\n    return total;\n}`,
      hints: ['The loop never advances to the next node.', 'Add current = node.next to advance the pointer.', 'Without this, current always points to the same node.'],
      concepts: ['linked-list', 'traversal', 'infinite-loop'],
    },
    {
      id: 'zig-ds-13',
      title: 'Predict: Ring Buffer Wrap',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the state of a ring buffer after wrapping.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    // Ring buffer of size 3\n    var buf: [3]i32 = undefined;\n    var head: usize = 0;\n    // Push 1, 2, 3, 4\n    for ([_]i32{ 1, 2, 3, 4 }) |val| {\n        buf[head % 3] = val;\n        head += 1;\n    }\n    // Read all 3 slots\n    std.debug.print("{} {} {}", .{ buf[0], buf[1], buf[2] });\n}`,
      solution: `4 2 3`,
      hints: ['Push 1 at [0], 2 at [1], 3 at [2].', 'Push 4: head=3, 3%3=0, overwrites buf[0].', 'Final state: buf = {4, 2, 3}.'],
      concepts: ['ring-buffer', 'modular-arithmetic'],
    },
    {
      id: 'zig-ds-14',
      title: 'Write: Trie (Prefix Tree)',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a basic trie that stores lowercase ASCII strings.',
      skeleton: `const std = @import("std");\n\n// Write TrieNode with:\n// - children: [26]?*TrieNode\n// - is_end: bool\n// And Trie with: init(allocator), insert([]const u8), search([]const u8) bool\n`,
      solution: `const std = @import("std");\n\nconst TrieNode = struct {\n    children: [26]?*TrieNode = [_]?*TrieNode{null} ** 26,\n    is_end: bool = false,\n};\n\nconst Trie = struct {\n    root: *TrieNode,\n    allocator: std.mem.Allocator,\n\n    fn init(allocator: std.mem.Allocator) !Trie {\n        const root = try allocator.create(TrieNode);\n        root.* = .{};\n        return .{ .root = root, .allocator = allocator };\n    }\n\n    fn insert(self: *Trie, word: []const u8) !void {\n        var node = self.root;\n        for (word) |ch| {\n            const idx = ch - 'a';\n            if (node.children[idx] == null) {\n                const new = try self.allocator.create(TrieNode);\n                new.* = .{};\n                node.children[idx] = new;\n            }\n            node = node.children[idx].?;\n        }\n        node.is_end = true;\n    }\n\n    fn search(self: *const Trie, word: []const u8) bool {\n        var node = self.root;\n        for (word) |ch| {\n            const idx = ch - 'a';\n            if (node.children[idx]) |child| {\n                node = child;\n            } else return false;\n        }\n        return node.is_end;\n    }\n};`,
      hints: ['Each node has 26 children for lowercase letters.', 'Insert creates nodes along the path.', 'Search follows the path and checks is_end.'],
      concepts: ['trie', 'prefix-tree', 'string-data-structure'],
    },
    {
      id: 'zig-ds-15',
      title: 'Fill Blank: HashMap Contains',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Check if a key exists in a HashMap.',
      skeleton: `const std = @import("std");\n\nfn hasKey(map: *std.AutoHashMap(i32, []const u8), key: i32) bool {\n    return map.___(key) != null;\n}`,
      solution: `const std = @import("std");\n\nfn hasKey(map: *std.AutoHashMap(i32, []const u8), key: i32) bool {\n    return map.get(key) != null;\n}`,
      hints: ['.get(key) returns ?V -- null if key not found.', 'Compare against null to check existence.', 'Replace ___ with get.'],
      concepts: ['AutoHashMap', 'contains-check'],
    },
    {
      id: 'zig-ds-16',
      title: 'Write: Union-Find',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a Union-Find (disjoint set) data structure with path compression.',
      skeleton: `const std = @import("std");\n\n// Write UnionFind with:\n// - parent: [N]usize, rank: [N]usize\n// - init(N), find(x) usize, union(x, y) void\n`,
      solution: `const std = @import("std");\n\nfn UnionFind(comptime N: usize) type {\n    return struct {\n        parent: [N]usize = blk: {\n            var p: [N]usize = undefined;\n            for (0..N) |i| p[i] = i;\n            break :blk p;\n        },\n        rank: [N]usize = [_]usize{0} ** N,\n\n        const Self = @This();\n\n        fn find(self: *Self, x: usize) usize {\n            if (self.parent[x] != x) {\n                self.parent[x] = self.find(self.parent[x]);\n            }\n            return self.parent[x];\n        }\n\n        fn merge(self: *Self, x: usize, y: usize) void {\n            const rx = self.find(x);\n            const ry = self.find(y);\n            if (rx == ry) return;\n            if (self.rank[rx] < self.rank[ry]) {\n                self.parent[rx] = ry;\n            } else if (self.rank[rx] > self.rank[ry]) {\n                self.parent[ry] = rx;\n            } else {\n                self.parent[ry] = rx;\n                self.rank[rx] += 1;\n            }\n        }\n    };\n}`,
      hints: ['Path compression: during find, point nodes directly to root.', 'Union by rank: attach smaller tree under larger.', 'Initialize parent[i] = i for each element.'],
      concepts: ['union-find', 'disjoint-set', 'path-compression'],
    },
    {
      id: 'zig-ds-17',
      title: 'Refactor: Array to ArrayList',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Refactor from a fixed-size array to a dynamic ArrayList.',
      skeleton: `const std = @import("std");\n\nconst MAX = 100;\nvar items: [MAX]i32 = undefined;\nvar count: usize = 0;\n\nfn add(val: i32) void {\n    if (count < MAX) {\n        items[count] = val;\n        count += 1;\n    }\n}\n\nfn getItems() []const i32 {\n    return items[0..count];\n}`,
      solution: `const std = @import("std");\n\nconst ItemList = struct {\n    items: std.ArrayList(i32),\n\n    fn init(allocator: std.mem.Allocator) ItemList {\n        return .{ .items = std.ArrayList(i32).init(allocator) };\n    }\n\n    fn deinit(self: *ItemList) void {\n        self.items.deinit();\n    }\n\n    fn add(self: *ItemList, val: i32) !void {\n        try self.items.append(val);\n    }\n\n    fn getItems(self: *const ItemList) []const i32 {\n        return self.items.items;\n    }\n};`,
      hints: ['Replace the fixed array with std.ArrayList.', 'add becomes append (which can fail).', 'Remove the global state and use a struct.'],
      concepts: ['ArrayList', 'refactoring', 'dynamic-allocation'],
    },
    {
      id: 'zig-ds-18',
      title: 'Refactor: Separate Storage from Logic',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Refactor to separate the data structure from the business logic.',
      skeleton: `const std = @import("std");\n\nvar scores: [100]i32 = undefined;\nvar count: usize = 0;\n\nfn addScore(s: i32) void {\n    if (count < 100) { scores[count] = s; count += 1; }\n}\n\nfn average() f64 {\n    if (count == 0) return 0;\n    var sum: i64 = 0;\n    for (scores[0..count]) |s| sum += s;\n    return @as(f64, @floatFromInt(sum)) / @as(f64, @floatFromInt(count));\n}`,
      solution: `const std = @import("std");\n\nconst ScoreTracker = struct {\n    scores: std.ArrayList(i32),\n\n    fn init(allocator: std.mem.Allocator) ScoreTracker {\n        return .{ .scores = std.ArrayList(i32).init(allocator) };\n    }\n\n    fn deinit(self: *ScoreTracker) void {\n        self.scores.deinit();\n    }\n\n    fn addScore(self: *ScoreTracker, s: i32) !void {\n        try self.scores.append(s);\n    }\n\n    fn average(self: *const ScoreTracker) f64 {\n        if (self.scores.items.len == 0) return 0;\n        var sum: i64 = 0;\n        for (self.scores.items) |s| sum += s;\n        return @as(f64, @floatFromInt(sum)) / @as(f64, @floatFromInt(self.scores.items.len));\n    }\n};`,
      hints: ['Encapsulate the data and logic in a struct.', 'Use ArrayList instead of fixed array.', 'Accept allocator for memory management.'],
      concepts: ['encapsulation', 'refactoring', 'ArrayList'],
    },
    {
      id: 'zig-ds-19',
      title: 'Predict: HashMap Overwrite',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'zig',
      goal: 'Predict the output after overwriting a HashMap entry.',
      skeleton: `const std = @import("std");\n\npub fn main() void {\n    var gpa = std.heap.GeneralPurposeAllocator(.{}){};\n    defer _ = gpa.deinit();\n    var map = std.AutoHashMap(i32, i32).init(gpa.allocator());\n    defer map.deinit();\n    map.put(1, 100) catch return;\n    map.put(1, 200) catch return;\n    std.debug.print("{}", .{map.get(1) orelse 0});\n}`,
      solution: `200`,
      hints: ['put with the same key overwrites the value.', 'First put: 1 -> 100. Second put: 1 -> 200.', 'get(1) returns 200.'],
      concepts: ['AutoHashMap', 'overwrite'],
    },
    {
      id: 'zig-ds-20',
      title: 'Write: Bloom Filter',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'zig',
      goal: 'Write a simple bloom filter for approximate set membership.',
      skeleton: `const std = @import("std");\n\n// Write BloomFilter(comptime N: usize) type\n// Uses a [N]bool bit array\n// Methods: insert([]const u8), mightContain([]const u8) bool\n// Use two hash functions for the positions\n`,
      solution: `const std = @import("std");\n\nfn BloomFilter(comptime N: usize) type {\n    return struct {\n        bits: [N]bool = [_]bool{false} ** N,\n\n        const Self = @This();\n\n        fn hash1(data: []const u8) usize {\n            var h: usize = 0;\n            for (data) |b| h = h *% 31 +% b;\n            return h % N;\n        }\n\n        fn hash2(data: []const u8) usize {\n            var h: usize = 5381;\n            for (data) |b| h = ((h << 5) +% h) +% b;\n            return h % N;\n        }\n\n        fn insert(self: *Self, key: []const u8) void {\n            self.bits[hash1(key)] = true;\n            self.bits[hash2(key)] = true;\n        }\n\n        fn mightContain(self: *const Self, key: []const u8) bool {\n            return self.bits[hash1(key)] and self.bits[hash2(key)];\n        }\n    };\n}`,
      hints: ['Use two different hash functions for two positions.', 'Insert sets both bit positions to true.', 'Contains checks both positions -- false positives are possible.'],
      concepts: ['bloom-filter', 'probabilistic-data-structure', 'hashing'],
    },
  ]
};
