import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rs-pin',
  title: '43. Pin and Unpin',
  explanation: `## Pin and Unpin

\`Pin<P>\` is a wrapper that prevents a value from being moved in memory. This is critical for self-referential types and async futures.

### Why Pin?
Self-referential structs contain pointers to their own fields. Moving the struct invalidates those pointers:
\`\`\`rust
struct SelfRef {
    data: String,
    ptr: *const String, // points to self.data - breaks if moved!
}
\`\`\`

### Pin<&mut T>
\`\`\`rust
use std::pin::Pin;

let mut val = 42;
let pinned: Pin<&mut i32> = Pin::new(&mut val);
// Cannot move val out through pinned
\`\`\`

### The Unpin Trait
- Most types implement \`Unpin\` automatically (safe to move even when pinned)
- Types that are \`!Unpin\` truly cannot be moved once pinned
- Futures generated by async blocks are \`!Unpin\`

### Pin in Practice
\`\`\`rust
use std::pin::pin;

let future = pin!(async { 42 });
// future is now pinned to the stack
\`\`\`

### Key Rules
| Type | Unpin? | Can move when pinned? |
|------|--------|-----------------------|
| i32, String, Vec | Yes | Yes |
| async block futures | No | No |
| Most user types | Yes | Yes |

### Box::pin
\`\`\`rust
let pinned: Pin<Box<dyn Future<Output = i32>>> = Box::pin(async { 42 });
\`\`\`
`,
  exercises: [
    {
      id: 'rs-pin-1',
      title: 'Create a Pin',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Create a pinned reference using Pin::new.',
      skeleton: `use std::pin::Pin;

fn main() {
    let mut value = 42;
    let pinned = __BLANK__(&mut value);
    println!("{}", *pinned);
}`,
      solution: `use std::pin::Pin;

fn main() {
    let mut value = 42;
    let pinned = Pin::new(&mut value);
    println!("{}", *pinned);
}`,
      hints: [
        'Pin::new wraps a mutable reference in a Pin.',
        'This works because i32 implements Unpin.',
        'Pin::new(&mut value)'
      ],
      concepts: ['pin', 'pin-new', 'unpin']
    },
    {
      id: 'rs-pin-2',
      title: 'Pin with Box',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Create a pinned Box using Box::pin.',
      skeleton: `use std::pin::Pin;

fn main() {
    let pinned: Pin<Box<String>> = __BLANK__(String::from("hello"));
    println!("{}", pinned);
}`,
      solution: `use std::pin::Pin;

fn main() {
    let pinned: Pin<Box<String>> = Box::pin(String::from("hello"));
    println!("{}", pinned);
}`,
      hints: [
        'Box::pin allocates on the heap and pins the value.',
        'The result is Pin<Box<T>>.',
        'Box::pin(String::from("hello"))'
      ],
      concepts: ['pin', 'box-pin', 'heap-allocation']
    },
    {
      id: 'rs-pin-3',
      title: 'Check Unpin',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Verify that a type implements Unpin.',
      skeleton: `fn requires_unpin<T: __BLANK__>(_: &T) {
    println!("This type can be safely moved when pinned");
}

fn main() {
    let x = 42;
    requires_unpin(&x);
    let s = String::from("hello");
    requires_unpin(&s);
}`,
      solution: `fn requires_unpin<T: Unpin>(_: &T) {
    println!("This type can be safely moved when pinned");
}

fn main() {
    let x = 42;
    requires_unpin(&x);
    let s = String::from("hello");
    requires_unpin(&s);
}`,
      hints: [
        'Unpin is an auto trait for most standard types.',
        'The bound T: Unpin ensures the type can be moved safely.',
        'Both i32 and String implement Unpin.'
      ],
      concepts: ['unpin', 'trait-bounds', 'auto-trait']
    },
    {
      id: 'rs-pin-4',
      title: 'Predict Pin Deref',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Predict the output when reading through a Pin.',
      skeleton: `use std::pin::Pin;

fn main() {
    let mut x = vec![1, 2, 3];
    let pinned = Pin::new(&mut x);
    println!("{}", pinned.len());
}`,
      solution: '3',
      hints: [
        'Pin<&mut Vec<i32>> auto-derefs to access Vec methods.',
        'len() returns 3 for a 3-element vector.',
        'Pin allows reading through Deref.'
      ],
      concepts: ['pin', 'deref', 'transparent-access']
    },
    {
      id: 'rs-pin-5',
      title: 'Pin::as_ref',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Convert a Pin<&mut T> to Pin<&T> using as_ref.',
      skeleton: `use std::pin::Pin;

fn read_pinned(p: Pin<&String>) {
    println!("{p}");
}

fn main() {
    let mut s = String::from("pinned");
    let mut pinned = Pin::new(&mut s);
    read_pinned(pinned.__BLANK__());
}`,
      solution: `use std::pin::Pin;

fn read_pinned(p: Pin<&String>) {
    println!("{p}");
}

fn main() {
    let mut s = String::from("pinned");
    let mut pinned = Pin::new(&mut s);
    read_pinned(pinned.as_ref());
}`,
      hints: [
        'as_ref() converts Pin<&mut T> to Pin<&T>.',
        'This borrows the pinned value immutably.',
        'pinned.as_ref()'
      ],
      concepts: ['pin', 'as-ref', 'reborrow']
    },
    {
      id: 'rs-pin-6',
      title: 'Write Pinned Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Write a function that accepts a Pin<&T> and reads the value.',
      skeleton: `use std::pin::Pin;

// todo: write fn peek(pinned: Pin<&i32>) -> i32 that returns the pinned value

fn main() {
    let mut x = 99;
    let pinned = Pin::new(&mut x);
    println!("{}", peek(pinned.as_ref()));
}`,
      solution: `use std::pin::Pin;

fn peek(pinned: Pin<&i32>) -> i32 {
    *pinned
}

fn main() {
    let mut x = 99;
    let pinned = Pin::new(&mut x);
    println!("{}", peek(pinned.as_ref()));
}`,
      hints: [
        'Pin<&i32> can be dereferenced since i32: Unpin.',
        'Use *pinned to access the inner value.',
        'The function signature takes Pin<&i32> and returns i32.'
      ],
      concepts: ['pin', 'deref', 'reading-pinned']
    },
    {
      id: 'rs-pin-7',
      title: 'Predict Unpin Auto-Impl',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'rust',
      goal: 'Predict whether common types implement Unpin.',
      skeleton: `fn is_unpin<T: Unpin>() -> bool { true }

fn main() {
    print!("{} ", is_unpin::<i32>());
    print!("{} ", is_unpin::<String>());
    print!("{}", is_unpin::<Vec<u8>>());
}`,
      solution: 'true true true',
      hints: [
        'Most standard types implement Unpin automatically.',
        'i32, String, and Vec<u8> are all Unpin.',
        'Only certain async/self-referential types are !Unpin.'
      ],
      concepts: ['unpin', 'auto-trait', 'standard-types']
    },
    {
      id: 'rs-pin-8',
      title: 'Fix Pin Move Error',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Fix the code that tries to move a value out of a Pin.',
      skeleton: `use std::pin::Pin;

fn take_string(s: String) -> usize {
    s.len()
}

fn main() {
    let s = String::from("hello");
    let pinned = Box::pin(s);
    let len = take_string(*pinned);
    println!("{len}");
}`,
      solution: `use std::pin::Pin;

fn take_string(s: &str) -> usize {
    s.len()
}

fn main() {
    let s = String::from("hello");
    let pinned = Box::pin(s);
    let len = take_string(&pinned);
    println!("{len}");
}`,
      hints: [
        'You cannot move out of a Pin<Box<T>> directly.',
        'Change the function to accept a reference instead.',
        'Use &pinned which auto-derefs through Pin and Box.'
      ],
      concepts: ['pin', 'move-prevention', 'reference']
    },
    {
      id: 'rs-pin-9',
      title: 'Pin::get_mut for Unpin',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Write a function that modifies a pinned value using get_mut (only works for Unpin types).',
      skeleton: `use std::pin::Pin;

fn double_in_place(mut pinned: Pin<&mut i32>) {
    // todo: use get_mut to get &mut i32 and double the value
}`,
      solution: `use std::pin::Pin;

fn double_in_place(mut pinned: Pin<&mut i32>) {
    let val = pinned.as_mut().get_mut();
    *val *= 2;
}`,
      hints: [
        'get_mut() is only available when T: Unpin.',
        'It returns &mut T from Pin<&mut T>.',
        'Call as_mut().get_mut() to get the mutable reference.'
      ],
      concepts: ['pin', 'get-mut', 'unpin', 'mutation']
    },
    {
      id: 'rs-pin-10',
      title: 'Fix Missing Unpin Bound',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Fix the generic function that needs an Unpin bound to work with Pin.',
      skeleton: `use std::pin::Pin;

fn swap_pinned<T>(a: Pin<&mut T>, b: Pin<&mut T>) {
    let a_ref = a.get_mut();
    let b_ref = b.get_mut();
    std::mem::swap(a_ref, b_ref);
}

fn main() {
    let mut x = 1;
    let mut y = 2;
    swap_pinned(Pin::new(&mut x), Pin::new(&mut y));
    println!("{x} {y}");
}`,
      solution: `use std::pin::Pin;

fn swap_pinned<T: Unpin>(mut a: Pin<&mut T>, mut b: Pin<&mut T>) {
    let a_ref = a.as_mut().get_mut();
    let b_ref = b.as_mut().get_mut();
    std::mem::swap(a_ref, b_ref);
}

fn main() {
    let mut x = 1;
    let mut y = 2;
    swap_pinned(Pin::new(&mut x), Pin::new(&mut y));
    println!("{x} {y}");
}`,
      hints: [
        'get_mut() requires T: Unpin.',
        'Add the Unpin bound to the generic parameter.',
        'Also add mut to the parameters for as_mut().'
      ],
      concepts: ['pin', 'unpin', 'trait-bounds', 'get-mut']
    },
    {
      id: 'rs-pin-11',
      title: 'Predict Pin Behavior',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Predict whether the code compiles and what it outputs.',
      skeleton: `use std::pin::Pin;

fn main() {
    let mut v = vec![1, 2, 3];
    let mut pinned = Pin::new(&mut v);
    // Vec is Unpin, so we can get &mut
    pinned.as_mut().get_mut().push(4);
    println!("{}", pinned.len());
}`,
      solution: '4',
      hints: [
        'Vec<i32> implements Unpin, so get_mut() works.',
        'push(4) adds an element, making len 4.',
        'Compiles and outputs 4.'
      ],
      concepts: ['pin', 'unpin', 'mutation', 'vec']
    },
    {
      id: 'rs-pin-12',
      title: 'Write Box::pin Wrapper',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Write a function that creates a pinned boxed value and returns it.',
      skeleton: `use std::pin::Pin;

fn pinned_vec(items: Vec<i32>) -> Pin<Box<Vec<i32>>> {
    // todo: pin the vec on the heap
}

fn sum_pinned(data: &Pin<Box<Vec<i32>>>) -> i32 {
    // todo: sum all elements
}`,
      solution: `use std::pin::Pin;

fn pinned_vec(items: Vec<i32>) -> Pin<Box<Vec<i32>>> {
    Box::pin(items)
}

fn sum_pinned(data: &Pin<Box<Vec<i32>>>) -> i32 {
    data.iter().sum()
}`,
      hints: [
        'Box::pin(items) creates Pin<Box<Vec<i32>>>.',
        'Pin auto-derefs so you can call .iter() directly.',
        'sum() adds all elements.'
      ],
      concepts: ['pin', 'box-pin', 'deref', 'iterator']
    },
    {
      id: 'rs-pin-13',
      title: 'PhantomPinned Marker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'rust',
      goal: 'Create a struct that opts out of Unpin using PhantomPinned.',
      skeleton: `use std::marker::PhantomPinned;

struct Unmovable {
    data: String,
    _pin: PhantomPinned,
}

impl Unmovable {
    fn new(data: &str) -> Self {
        // todo: create an Unmovable
    }

    fn data(self: std::pin::Pin<&Self>) -> &str {
        // todo: access data through Pin
    }
}`,
      solution: `use std::marker::PhantomPinned;

struct Unmovable {
    data: String,
    _pin: PhantomPinned,
}

impl Unmovable {
    fn new(data: &str) -> Self {
        Unmovable {
            data: data.to_string(),
            _pin: PhantomPinned,
        }
    }

    fn data(self: std::pin::Pin<&Self>) -> &str {
        &self.data
    }
}`,
      hints: [
        'PhantomPinned makes the struct !Unpin.',
        'Methods use Pin<&Self> as the receiver.',
        'Access fields normally through the pinned reference.'
      ],
      concepts: ['phantom-pinned', 'unpin-opt-out', 'pin-projection']
    },
    {
      id: 'rs-pin-14',
      title: 'Predict PhantomPinned',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Predict whether a struct with PhantomPinned can use Pin::new.',
      skeleton: `use std::marker::PhantomPinned;
use std::pin::Pin;

struct Fixed {
    value: i32,
    _pin: PhantomPinned,
}

fn main() {
    let f = Fixed { value: 42, _pin: PhantomPinned };
    let pinned = Box::pin(f);
    println!("{}", pinned.value);
}`,
      solution: '42',
      hints: [
        'Box::pin works with !Unpin types (unlike Pin::new).',
        'pinned auto-derefs to access .value.',
        'Output: 42.'
      ],
      concepts: ['phantom-pinned', 'box-pin', 'not-unpin']
    },
    {
      id: 'rs-pin-15',
      title: 'Fix PhantomPinned Pin::new',
      type: 'fix-bug',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Fix the code that tries to use Pin::new with a !Unpin type.',
      skeleton: `use std::marker::PhantomPinned;
use std::pin::Pin;

struct NeverMove {
    data: i32,
    _pin: PhantomPinned,
}

fn main() {
    let mut nm = NeverMove { data: 7, _pin: PhantomPinned };
    let pinned = Pin::new(&mut nm);
    println!("{}", pinned.data);
}`,
      solution: `use std::marker::PhantomPinned;
use std::pin::Pin;

struct NeverMove {
    data: i32,
    _pin: PhantomPinned,
}

fn main() {
    let nm = NeverMove { data: 7, _pin: PhantomPinned };
    let pinned = Box::pin(nm);
    println!("{}", pinned.data);
}`,
      hints: [
        'Pin::new requires T: Unpin, but PhantomPinned makes it !Unpin.',
        'Use Box::pin instead, which works with any type.',
        'Box::pin allocates on the heap and pins in place.'
      ],
      concepts: ['pin', 'phantom-pinned', 'box-pin', 'not-unpin']
    },
    {
      id: 'rs-pin-16',
      title: 'Write Pin-Safe API',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Write a struct with both pinned and unpinned access methods.',
      skeleton: `use std::pin::Pin;
use std::marker::PhantomPinned;

struct Sensor {
    name: String,
    reading: f64,
    _pin: PhantomPinned,
}

impl Sensor {
    fn new(name: &str) -> Pin<Box<Self>> {
        // todo: create pinned sensor
    }

    fn name(self: Pin<&Self>) -> &str {
        // todo
    }

    fn reading(self: Pin<&Self>) -> f64 {
        // todo
    }
}`,
      solution: `use std::pin::Pin;
use std::marker::PhantomPinned;

struct Sensor {
    name: String,
    reading: f64,
    _pin: PhantomPinned,
}

impl Sensor {
    fn new(name: &str) -> Pin<Box<Self>> {
        Box::pin(Sensor {
            name: name.to_string(),
            reading: 0.0,
            _pin: PhantomPinned,
        })
    }

    fn name(self: Pin<&Self>) -> &str {
        &self.name
    }

    fn reading(self: Pin<&Self>) -> f64 {
        self.reading
    }
}`,
      hints: [
        'Use Box::pin in the constructor since Sensor is !Unpin.',
        'Methods take self: Pin<&Self> for pinned access.',
        'Field access works normally through Pin projections.'
      ],
      concepts: ['pin', 'api-design', 'phantom-pinned', 'pin-projection']
    },
    {
      id: 'rs-pin-17',
      title: 'Write Pin-Safe Mutation',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Write a safe mutation method for a pinned Unpin field within a !Unpin struct.',
      skeleton: `use std::pin::Pin;
use std::marker::PhantomPinned;

struct Counter {
    count: u32,  // this field is Unpin
    _pin: PhantomPinned,
}

impl Counter {
    fn new() -> Pin<Box<Self>> {
        // todo
    }

    fn increment(self: Pin<&mut Self>) {
        // todo: safely increment count
        // Hint: use unsafe Pin::get_unchecked_mut since the struct is !Unpin
        // but we know mutating count is safe
    }

    fn get(self: Pin<&Self>) -> u32 {
        // todo
    }
}`,
      solution: `use std::pin::Pin;
use std::marker::PhantomPinned;

struct Counter {
    count: u32,
    _pin: PhantomPinned,
}

impl Counter {
    fn new() -> Pin<Box<Self>> {
        Box::pin(Counter { count: 0, _pin: PhantomPinned })
    }

    fn increment(self: Pin<&mut Self>) {
        unsafe {
            let this = self.get_unchecked_mut();
            this.count += 1;
        }
    }

    fn get(self: Pin<&Self>) -> u32 {
        self.count
    }
}`,
      hints: [
        'get_unchecked_mut is unsafe but needed for !Unpin types.',
        'Mutating a simple u32 field is safe even if the struct is pinned.',
        'This is safe because we are not moving the struct, just changing a field.'
      ],
      concepts: ['pin', 'get-unchecked-mut', 'unsafe', 'pin-projection']
    },
    {
      id: 'rs-pin-18',
      title: 'Predict Pin Projection Safety',
      type: 'predict-output',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Predict the output of safe pin operations.',
      skeleton: `use std::pin::Pin;

fn main() {
    let mut data = String::from("abc");
    let mut pinned = Pin::new(&mut data);
    // String is Unpin, so get_mut works
    pinned.as_mut().get_mut().push_str("def");
    println!("{}", pinned);
}`,
      solution: 'abcdef',
      hints: [
        'String is Unpin, so get_mut() is safe.',
        'push_str adds "def" to "abc" = "abcdef".',
        'Output: abcdef.'
      ],
      concepts: ['pin', 'unpin', 'get-mut', 'string-mutation']
    },
    {
      id: 'rs-pin-19',
      title: 'Refactor to Pinned API',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Refactor a movable struct to be pinned with PhantomPinned.',
      skeleton: `struct Node {
    value: i32,
    label: String,
}

impl Node {
    fn new(value: i32, label: &str) -> Self {
        Node { value, label: label.to_string() }
    }

    fn value(&self) -> i32 { self.value }
    fn label(&self) -> &str { &self.label }
}

fn main() {
    let n = Node::new(42, "root");
    println!("{}: {}", n.label(), n.value());
}`,
      solution: `use std::pin::Pin;
use std::marker::PhantomPinned;

struct Node {
    value: i32,
    label: String,
    _pin: PhantomPinned,
}

impl Node {
    fn new(value: i32, label: &str) -> Pin<Box<Self>> {
        Box::pin(Node { value, label: label.to_string(), _pin: PhantomPinned })
    }

    fn value(self: Pin<&Self>) -> i32 { self.value }
    fn label(self: Pin<&Self>) -> &str { &self.label }
}

fn main() {
    let n = Node::new(42, "root");
    println!("{}: {}", n.as_ref().label(), n.as_ref().value());
}`,
      hints: [
        'Add PhantomPinned field to make Node !Unpin.',
        'Constructor returns Pin<Box<Self>> using Box::pin.',
        'Methods take self: Pin<&Self> and use as_ref() to call.'
      ],
      concepts: ['pin', 'phantom-pinned', 'refactoring', 'api-design']
    },
    {
      id: 'rs-pin-20',
      title: 'Refactor Future Pinning',
      type: 'refactor',
      difficulty: 'advanced',
      language: 'rust',
      goal: 'Refactor code to properly pin an async future for polling.',
      skeleton: `use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll};

struct SimpleFuture {
    done: bool,
}

impl Future for SimpleFuture {
    type Output = i32;
    fn poll(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<i32> {
        if self.done {
            Poll::Ready(42)
        } else {
            // Can't set done = true without unsafe since we might be !Unpin
            Poll::Pending
        }
    }
}`,
      solution: `use std::future::Future;
use std::pin::Pin;
use std::task::{Context, Poll};

struct SimpleFuture {
    done: bool,
}

impl Unpin for SimpleFuture {}

impl Future for SimpleFuture {
    type Output = i32;
    fn poll(mut self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<i32> {
        if self.done {
            Poll::Ready(42)
        } else {
            self.as_mut().get_mut().done = true;
            Poll::Pending
        }
    }
}`,
      hints: [
        'Implement Unpin explicitly since SimpleFuture has no self-references.',
        'With Unpin, get_mut() becomes available.',
        'Use self.as_mut().get_mut().done = true to modify state.'
      ],
      concepts: ['pin', 'future', 'unpin', 'poll', 'refactoring']
    }
  ]
};
