import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-factory',
  title: '42. Factory',
  explanation: `## Factory Pattern in Ruby

The Factory pattern provides an interface for creating objects without specifying their exact class.

### Factory Method

\`\`\`ruby
class Vehicle
  def self.create(type)
    case type
    when :car then Car.new
    when :truck then Truck.new
    when :bike then Bike.new
    else raise "Unknown: \#{type}"
    end
  end
end
\`\`\`

### Registration Pattern

\`\`\`ruby
class Parser
  @registry = {}

  def self.register(format, klass)
    @registry[format] = klass
  end

  def self.for(format)
    @registry.fetch(format) { raise "Unknown format" }.new
  end
end
\`\`\`

### Abstract Factory

\`\`\`ruby
class UIFactory
  def create_button; raise NotImplementedError; end
  def create_input; raise NotImplementedError; end
end

class DarkFactory < UIFactory
  def create_button = DarkButton.new
  def create_input = DarkInput.new
end
\`\`\``,
  exercises: [
    { id: 'rb-factory-1', title: 'Basic Factory Method', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Create a factory method.', skeleton: `class Shape\n  def self.___(type)\n    case type\n    when :circle then Circle.new\n    when :square then Square.new\n    end\n  end\nend`, solution: `class Shape\n  def self.create(type)\n    case type\n    when :circle then Circle.new\n    when :square then Square.new\n    end\n  end\nend`, hints: ['Factory methods are class methods', 'Use case/when to select the type', 'Return a new instance of the appropriate class'], concepts: ['factory_method'] },
    { id: 'rb-factory-2', title: 'Register Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use registration pattern.', skeleton: `class Serializer\n  @registry = {}\n\n  def self.register(format, klass)\n    @registry[format] = klass\n  end\n\n  def self.for(format)\n    @registry.___(format) { raise \"Unknown\" }.new\n  end\nend`, solution: `class Serializer\n  @registry = {}\n\n  def self.register(format, klass)\n    @registry[format] = klass\n  end\n\n  def self.for(format)\n    @registry.fetch(format) { raise \"Unknown\" }.new\n  end\nend`, hints: ['fetch raises if key is missing', 'The block provides the error', '.new creates an instance of the registered class'], concepts: ['registration_pattern'] },
    { id: 'rb-factory-3', title: 'Factory with Config', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Pass configuration to factory.', skeleton: `class Connection\n  def self.create(type, **opts)\n    case type\n    when :postgres then PostgresConn.new(___)\n    when :mysql then MysqlConn.new(___)\n    end\n  end\nend`, solution: `class Connection\n  def self.create(type, **opts)\n    case type\n    when :postgres then PostgresConn.new(**opts)\n    when :mysql then MysqlConn.new(**opts)\n    end\n  end\nend`, hints: ['**opts captures keyword arguments', 'Pass them through with **opts', 'Each connection type receives the same options'], concepts: ['factory_with_options'] },
    { id: 'rb-factory-4', title: 'Abstract Factory Base', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Define an abstract factory.', skeleton: `class UIFactory\n  def create_button\n    raise ___\n  end\n\n  def create_input\n    raise ___\n  end\nend`, solution: `class UIFactory\n  def create_button\n    raise NotImplementedError\n  end\n\n  def create_input\n    raise NotImplementedError\n  end\nend`, hints: ['NotImplementedError signals abstract methods', 'Subclasses must override these methods', 'This enforces the factory interface'], concepts: ['abstract_factory'] },
    { id: 'rb-factory-5', title: 'Inherited Registration', type: 'fill-blank', difficulty: 'advanced', language: 'ruby', goal: 'Auto-register via inherited hook.', skeleton: `class Handler\n  @handlers = {}\n\n  def self.___(subclass)\n    super\n  end\n\n  def self.register_as(name)\n    Handler.instance_variable_get(:@handlers)[name] = self\n  end\n\n  def self.for(name)\n    @handlers[name].new\n  end\nend`, solution: `class Handler\n  @handlers = {}\n\n  def self.inherited(subclass)\n    super\n  end\n\n  def self.register_as(name)\n    Handler.instance_variable_get(:@handlers)[name] = self\n  end\n\n  def self.for(name)\n    @handlers[name].new\n  end\nend`, hints: ['inherited tracks new subclasses', 'register_as lets subclasses self-register', 'for looks up and instantiates'], concepts: ['inherited_registration'] },
    { id: 'rb-factory-6', title: 'Lambda Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use lambdas as factories.', skeleton: `factories = {\n  greeting: ___ { |name| \"Hello, \\\#{name}!\" },\n  farewell: ___ { |name| \"Goodbye, \\\#{name}!\" }\n}\n\nputs factories[:greeting].call(\"Alice\")`, solution: `factories = {\n  greeting: lambda { |name| \"Hello, \\\#{name}!\" },\n  farewell: lambda { |name| \"Goodbye, \\\#{name}!\" }\n}\n\nputs factories[:greeting].call(\"Alice\")`, hints: ['Lambdas can serve as lightweight factories', '.call invokes the lambda', 'No need for classes for simple object creation'], concepts: ['lambda_factory'] },
    { id: 'rb-factory-7', title: 'Write Document Factory', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a document factory with registration.', skeleton: `# Write a DocumentFactory with:\n# - register(ext, klass) class method\n# - create(filename) that picks class by extension\n# - Document base class with name and content\n# - PdfDocument, HtmlDocument, TxtDocument subclasses\n`, solution: `class Document\n  attr_reader :name, :content\n  def initialize(name)\n    @name = name\n    @content = \"\"\n  end\n  def type = self.class.name\nend\n\nclass PdfDocument < Document; end\nclass HtmlDocument < Document; end\nclass TxtDocument < Document; end\n\nclass DocumentFactory\n  @registry = {}\n\n  def self.register(ext, klass)\n    @registry[ext] = klass\n  end\n\n  def self.create(filename)\n    ext = File.extname(filename).delete('.')\n    klass = @registry.fetch(ext) { raise \"Unknown format: \\\#{ext}\" }\n    klass.new(filename)\n  end\nend\n\nDocumentFactory.register(\"pdf\", PdfDocument)\nDocumentFactory.register(\"html\", HtmlDocument)\nDocumentFactory.register(\"txt\", TxtDocument)\n\nputs DocumentFactory.create(\"report.pdf\").type\nputs DocumentFactory.create(\"page.html\").type`, hints: ['Extract extension from filename', 'Look up class in registry', 'Instantiate with the filename'], concepts: ['document_factory'] },
    { id: 'rb-factory-8', title: 'Write Abstract Factory', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write abstract factory for UI themes.', skeleton: `# Write:\n# - UIFactory base with create_button, create_checkbox (abstract)\n# - LightFactory creates LightButton, LightCheckbox\n# - DarkFactory creates DarkButton, DarkCheckbox\n# - Each widget has a render method\n`, solution: `class UIFactory\n  def create_button = raise NotImplementedError\n  def create_checkbox = raise NotImplementedError\nend\n\nclass LightButton\n  def render = \"[ Light Button ]\"\nend\n\nclass LightCheckbox\n  def render = \"[ ] Light Checkbox\"\nend\n\nclass DarkButton\n  def render = \"[# Dark Button #]\"\nend\n\nclass DarkCheckbox\n  def render = \"[x] Dark Checkbox\"\nend\n\nclass LightFactory < UIFactory\n  def create_button = LightButton.new\n  def create_checkbox = LightCheckbox.new\nend\n\nclass DarkFactory < UIFactory\n  def create_button = DarkButton.new\n  def create_checkbox = DarkCheckbox.new\nend\n\ndef render_ui(factory)\n  btn = factory.create_button\n  cb = factory.create_checkbox\n  puts btn.render\n  puts cb.render\nend\n\nrender_ui(LightFactory.new)\nrender_ui(DarkFactory.new)`, hints: ['Base factory defines the interface', 'Concrete factories return specific implementations', 'Client code uses the factory interface'], concepts: ['abstract_factory'] },
    { id: 'rb-factory-9', title: 'Write Builder Factory', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a factory with builder pattern.', skeleton: `# Write a QueryBuilder factory:\n# - QueryBuilder.select(:users) starts a query\n# - .where(age: 18) adds conditions\n# - .order(:name) adds ordering\n# - .to_sql returns the SQL string\n`, solution: `class QueryBuilder\n  def self.select(table)\n    new(table)\n  end\n\n  def initialize(table)\n    @table = table\n    @conditions = []\n    @order = nil\n  end\n\n  def where(conditions)\n    conditions.each do |k, v|\n      @conditions << \"\\\#{k} = '\\\#{v}'\"\n    end\n    self\n  end\n\n  def order(field)\n    @order = field\n    self\n  end\n\n  def to_sql\n    sql = \"SELECT * FROM \\\#{@table}\"\n    sql += \" WHERE \\\#{@conditions.join(' AND ')}\" unless @conditions.empty?\n    sql += \" ORDER BY \\\#{@order}\" if @order\n    sql\n  end\nend\n\nputs QueryBuilder.select(:users).where(age: 18).order(:name).to_sql`, hints: ['Return self from each method for chaining', 'select is the factory entry point', 'to_sql assembles the final query'], concepts: ['builder_pattern'] },
    { id: 'rb-factory-10', title: 'Write Prototype Factory', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a factory that clones prototypes.', skeleton: `# Write a PrototypeFactory:\n# - register(name, prototype) stores a clonable prototype\n# - create(name, **overrides) clones and applies overrides\n# Use Struct for prototypes\n`, solution: `Config = Struct.new(:host, :port, :ssl, keyword_init: true)\n\nclass PrototypeFactory\n  def initialize\n    @prototypes = {}\n  end\n\n  def register(name, prototype)\n    @prototypes[name] = prototype\n  end\n\n  def create(name, **overrides)\n    proto = @prototypes.fetch(name) { raise \"Unknown: \\\#{name}\" }\n    clone = proto.dup\n    overrides.each { |k, v| clone.send(\"\\\#{k}=\", v) }\n    clone\n  end\nend\n\nfactory = PrototypeFactory.new\nfactory.register(:dev, Config.new(host: \"localhost\", port: 3000, ssl: false))\nfactory.register(:prod, Config.new(host: \"app.com\", port: 443, ssl: true))\n\ndev = factory.create(:dev, port: 4000)\nputs dev.inspect\nprod = factory.create(:prod)\nputs prod.inspect`, hints: ['dup creates a shallow copy', 'Apply overrides by calling setter methods', 'Prototypes serve as templates'], concepts: ['prototype_pattern'] },
    { id: 'rb-factory-11', title: 'Write Method Factory', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write factory methods on a base class.', skeleton: `# Write a Notification base class with:\n# - self.create(type, message) factory method\n# - EmailNotification, SmsNotification, PushNotification subclasses\n# - Each has a deliver method with different output\n`, solution: `class Notification\n  attr_reader :message\n\n  def initialize(message)\n    @message = message\n  end\n\n  def self.create(type, message)\n    case type\n    when :email then EmailNotification.new(message)\n    when :sms then SmsNotification.new(message)\n    when :push then PushNotification.new(message)\n    else raise \"Unknown type: \\\#{type}\"\n    end\n  end\n\n  def deliver = raise NotImplementedError\nend\n\nclass EmailNotification < Notification\n  def deliver = \"Email: \\\#{message}\"\nend\n\nclass SmsNotification < Notification\n  def deliver = \"SMS: \\\#{message}\"\nend\n\nclass PushNotification < Notification\n  def deliver = \"Push: \\\#{message}\"\nend\n\n[:email, :sms, :push].each do |type|\n  puts Notification.create(type, \"Hello!\").deliver\nend`, hints: ['Factory method lives on the base class', 'case/when selects the subclass', 'Each subclass implements deliver differently'], concepts: ['factory_method_pattern'] },
    { id: 'rb-factory-12', title: 'Write Dynamic Factory', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a factory that creates classes dynamically.', skeleton: `# Write a ModelFactory that:\n# - define_model(name, *fields) creates a new Struct-based class\n# - stores it as a constant\n# - create(name, **attrs) instantiates the model\n`, solution: `module ModelFactory\n  @models = {}\n\n  def self.define_model(name, *fields)\n    klass = Struct.new(*fields, keyword_init: true)\n    @models[name] = klass\n    const_set(name, klass)\n  end\n\n  def self.create(name, **attrs)\n    @models.fetch(name) { raise \"Unknown model: \\\#{name}\" }.new(**attrs)\n  end\nend\n\nModelFactory.define_model(:User, :name, :email, :age)\nModelFactory.define_model(:Product, :title, :price)\n\nuser = ModelFactory.create(:User, name: \"Alice\", email: \"a@b.com\", age: 30)\nputs user.inspect\n\nproduct = ModelFactory.create(:Product, title: \"Widget\", price: 9.99)\nputs product.inspect`, hints: ['Struct.new dynamically creates a class', 'const_set makes it accessible as a constant', 'Store in a registry for lookup'], concepts: ['dynamic_class_creation'] },
    { id: 'rb-factory-13', title: 'Fix Factory Missing Default', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the factory that returns nil for unknown types.', skeleton: `class Animal\n  def self.create(type)\n    case type\n    when :dog then \"Dog\"\n    when :cat then \"Cat\"\n    end\n    # Bug: returns nil for unknown types silently\n  end\nend\n\nputs Animal.create(:fish).upcase  # NoMethodError on nil`, solution: `class Animal\n  def self.create(type)\n    case type\n    when :dog then \"Dog\"\n    when :cat then \"Cat\"\n    else raise ArgumentError, \"Unknown animal: \\\#{type}\"\n    end\n  end\nend\n\nbegin\n  Animal.create(:fish)\nrescue ArgumentError => e\n  puts e.message\nend`, hints: ['Add an else clause to raise an error', 'Fail fast on unknown types', 'Silent nil returns cause confusing errors later'], concepts: ['fail_fast'] },
    { id: 'rb-factory-14', title: 'Fix Registry Overwrite', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix factory that silently overwrites registrations.', skeleton: `class Parser\n  @registry = {}\n\n  def self.register(format, klass)\n    # Bug: silently overwrites existing registrations\n    @registry[format] = klass\n  end\n\n  def self.for(format)\n    @registry[format]&.new\n  end\nend`, solution: `class Parser\n  @registry = {}\n\n  def self.register(format, klass)\n    if @registry.key?(format)\n      raise \"Format '\\\#{format}' already registered to \\\#{@registry[format]}\"\n    end\n    @registry[format] = klass\n  end\n\n  def self.for(format)\n    @registry.fetch(format) { raise \"Unknown format: \\\#{format}\" }.new\n  end\nend`, hints: ['Check if the key already exists', 'Raise an error on duplicate registration', 'This prevents accidental overwrites'], concepts: ['safe_registration'] },
    { id: 'rb-factory-15', title: 'Fix Factory Return Type', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix factory returning class instead of instance.', skeleton: `class Logger\n  @types = { file: FileLogger, console: ConsoleLogger }\n\n  def self.create(type)\n    # Bug: returns the class, not an instance\n    @types[type]\n  end\nend\n\n# logger = Logger.create(:file)\n# logger.log(\"hello\")  # calls class method instead of instance method`, solution: `class Logger\n  @types = { file: FileLogger, console: ConsoleLogger }\n\n  def self.create(type)\n    klass = @types.fetch(type) { raise \"Unknown: \\\#{type}\" }\n    klass.new\n  end\nend`, hints: ['The factory should return an instance, not a class', 'Call .new on the looked-up class', 'fetch raises on missing keys'], concepts: ['factory_instantiation'] },
    { id: 'rb-factory-16', title: 'Predict Factory Output', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict factory creation.', skeleton: `class Shape\n  attr_reader :type\n  def initialize(type) = @type = type\n  def self.circle = new(:circle)\n  def self.square = new(:square)\nend\n\nputs Shape.circle.type\nputs Shape.square.type\nputs Shape.circle.equal?(Shape.circle)`, solution: `circle\nsquare\nfalse`, hints: ['Each call creates a new instance', 'circle and square are factory methods', 'equal? checks identity - each call makes a new object'], concepts: ['factory_identity'] },
    { id: 'rb-factory-17', title: 'Predict Registration', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict registration-based factory behavior.', skeleton: `class Store\n  @items = {}\n  def self.register(k, v) = @items[k] = v\n  def self.get(k) = @items[k]\n  def self.count = @items.size\nend\n\nStore.register(:a, 1)\nStore.register(:b, 2)\nStore.register(:a, 3)\nputs Store.get(:a)\nputs Store.count`, solution: `3\n2`, hints: ['Registering :a twice overwrites the first', ':a now maps to 3', 'Count is 2 because there are 2 unique keys'], concepts: ['registration_overwrite'] },
    { id: 'rb-factory-18', title: 'Predict Abstract Factory', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict abstract factory behavior.', skeleton: `class Base\n  def make = raise NotImplementedError\nend\n\nclass ConcreteA < Base\n  def make = \"A\"\nend\n\nclass ConcreteB < Base\n  def make = \"B\"\nend\n\nfactories = [ConcreteA.new, ConcreteB.new, ConcreteA.new]\nputs factories.map(&:make).join(\", \")`, solution: `A, B, A`, hints: ['Each factory makes its own type', 'map calls make on each', 'join combines with commas'], concepts: ['polymorphic_factory'] },
    { id: 'rb-factory-19', title: 'Refactor Conditional to Factory', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor nested conditionals to factory pattern.', skeleton: `def format_output(data, format)\n  if format == :json\n    data.to_s  # simplified\n  elsif format == :xml\n    \"<data>\\\#{data}</data>\"\n  elsif format == :csv\n    data.to_s.tr(\" \", \",\")\n  elsif format == :yaml\n    \"---\\n\\\#{data}\"\n  else\n    raise \"Unknown format\"\n  end\nend`, solution: `class Formatter\n  @registry = {}\n\n  def self.register(name, &block)\n    @registry[name] = block\n  end\n\n  def self.format(data, type)\n    @registry.fetch(type) { raise \"Unknown format: \\\#{type}\" }.call(data)\n  end\nend\n\nFormatter.register(:json) { |d| d.to_s }\nFormatter.register(:xml) { |d| \"<data>\\\#{d}</data>\" }\nFormatter.register(:csv) { |d| d.to_s.tr(\" \", \",\") }\nFormatter.register(:yaml) { |d| \"---\\n\\\#{d}\" }\n\nputs Formatter.format(\"hello world\", :xml)`, hints: ['Extract each branch into a registered handler', 'Use blocks for simple formatters', 'New formats are added without modifying existing code'], concepts: ['open_closed_principle'] },
    { id: 'rb-factory-20', title: 'Refactor new Override to Factory', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor a .new override to a proper factory method.', skeleton: `class Connection\n  # Anti-pattern: overriding new\n  def self.new(type, **opts)\n    case type\n    when :http then HttpConnection.allocate.tap { |o| o.send(:initialize, **opts) }\n    when :ws then WsConnection.allocate.tap { |o| o.send(:initialize, **opts) }\n    else super(**opts)\n    end\n  end\n\n  def initialize(**opts)\n    @opts = opts\n  end\nend`, solution: `class Connection\n  def initialize(**opts)\n    @opts = opts\n  end\n\n  def self.create(type, **opts)\n    case type\n    when :http then HttpConnection.new(**opts)\n    when :ws then WsConnection.new(**opts)\n    else raise \"Unknown connection type: \\\#{type}\"\n    end\n  end\nend\n\nclass HttpConnection < Connection; end\nclass WsConnection < Connection; end\n\nconn = Connection.create(:http, host: \"example.com\")\nputs conn.class`, hints: ['Never override .new for factory logic', 'Use a separate factory method like .create', 'This is clearer and avoids allocate hacks'], concepts: ['factory_method_vs_new'] },
  ],
};
