import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-observer',
  title: '43. Observer',
  explanation: `## Observer Pattern in Ruby

The Observer pattern lets objects subscribe to events from another object, enabling loose coupling.

### Custom Observer

\`\`\`ruby
module Observable
  def self.included(base)
    base.instance_variable_set(:@observers, Hash.new { |h, k| h[k] = [] })
    base.extend(ClassMethods)
  end

  module ClassMethods
    def on(event, &block)
      @observers[event] << block
    end
  end

  def notify(event, *args)
    self.class.instance_variable_get(:@observers)[event].each do |handler|
      handler.call(*args)
    end
  end
end
\`\`\`

### Ruby's Observable Module

\`\`\`ruby
require 'observer'

class Sensor
  include Observable

  def temperature=(val)
    @temperature = val
    changed
    notify_observers(val)
  end
end

class Display
  def update(temp)
    puts "Temperature: \#{temp}"
  end
end

sensor = Sensor.new
sensor.add_observer(Display.new)
sensor.temperature = 25
\`\`\``,
  exercises: [
    { id: 'rb-observer-1', title: 'Add Observer', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Add an observer to a subject.', skeleton: `require 'observer'\n\nclass EventSource\n  include Observable\n  def fire(data)\n    changed\n    ___(data)\n  end\nend`, solution: `require 'observer'\n\nclass EventSource\n  include Observable\n  def fire(data)\n    changed\n    notify_observers(data)\n  end\nend`, hints: ['changed marks the object as changed', 'notify_observers sends to all observers', 'Observers must implement update'], concepts: ['notify_observers'] },
    { id: 'rb-observer-2', title: 'Observer Update', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Implement observer update method.', skeleton: `class Logger\n  def ___(event_data)\n    puts \"[LOG] \\\#{event_data}\"\n  end\nend`, solution: `class Logger\n  def update(event_data)\n    puts \"[LOG] \\\#{event_data}\"\n  end\nend`, hints: ['Observers must implement update', 'update receives the notification data', 'This is the callback method'], concepts: ['update'] },
    { id: 'rb-observer-3', title: 'Changed Flag', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use the changed flag correctly.', skeleton: `require 'observer'\n\nclass Stock\n  include Observable\n  attr_reader :price\n\n  def price=(new_price)\n    if new_price != @price\n      @price = new_price\n      ___\n      notify_observers(self)\n    end\n  end\nend`, solution: `require 'observer'\n\nclass Stock\n  include Observable\n  attr_reader :price\n\n  def price=(new_price)\n    if new_price != @price\n      @price = new_price\n      changed\n      notify_observers(self)\n    end\n  end\nend`, hints: ['changed must be called before notify_observers', 'Without changed, observers are not notified', 'Only notify when value actually changes'], concepts: ['changed_flag'] },
    { id: 'rb-observer-4', title: 'Remove Observer', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Remove an observer.', skeleton: `require 'observer'\n\nclass Source\n  include Observable\nend\n\nsrc = Source.new\nlogger = Object.new\ndef logger.update(d) = puts d\n\nsrc.add_observer(logger)\nsrc.___observer(logger)`, solution: `require 'observer'\n\nclass Source\n  include Observable\nend\n\nsrc = Source.new\nlogger = Object.new\ndef logger.update(d) = puts d\n\nsrc.add_observer(logger)\nsrc.delete_observer(logger)`, hints: ['delete_observer removes a specific observer', 'The observer will no longer receive notifications', 'delete_observers (plural) removes all'], concepts: ['delete_observer'] },
    { id: 'rb-observer-5', title: 'Custom Method Observer', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use a custom method name for observer callback.', skeleton: `require 'observer'\n\nclass AlertSystem\n  include Observable\n  def alert(msg)\n    changed\n    notify_observers(msg)\n  end\nend\n\nclass Siren\n  def on_alert(msg)\n    puts \"ALERT: \\\#{msg}\"\n  end\nend\n\nsys = AlertSystem.new\nsys.add_observer(Siren.new, :___)`, solution: `require 'observer'\n\nclass AlertSystem\n  include Observable\n  def alert(msg)\n    changed\n    notify_observers(msg)\n  end\nend\n\nclass Siren\n  def on_alert(msg)\n    puts \"ALERT: \\\#{msg}\"\n  end\nend\n\nsys = AlertSystem.new\nsys.add_observer(Siren.new, :on_alert)`, hints: ['add_observer accepts an optional method name', 'Default is :update', 'Pass the symbol of the method to call'], concepts: ['custom_callback'] },
    { id: 'rb-observer-6', title: 'Count Observers', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Check observer count.', skeleton: `require 'observer'\n\nclass Bus\n  include Observable\nend\n\nbus = Bus.new\n3.times { bus.add_observer(Object.new) }\nputs bus.___`, solution: `require 'observer'\n\nclass Bus\n  include Observable\nend\n\nbus = Bus.new\n3.times { bus.add_observer(Object.new) }\nputs bus.count_observers`, hints: ['count_observers returns the number of observers', 'Each add_observer increments the count', 'Objects need update method to receive notifications'], concepts: ['count_observers'] },
    { id: 'rb-observer-7', title: 'Write Custom Observable', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a custom event system without the Observable module.', skeleton: `# Write an EventEmitter module with:\n# - on(event, &block) subscribes to an event\n# - emit(event, *args) triggers all handlers\n# - off(event) removes all handlers for an event\n# - once(event, &block) subscribes for a single trigger\n`, solution: `module EventEmitter\n  def on(event, &block)\n    listeners[event] << block\n  end\n\n  def emit(event, *args)\n    listeners[event].each { |l| l.call(*args) }\n    once_listeners[event].each { |l| l.call(*args) }\n    once_listeners[event].clear\n  end\n\n  def off(event)\n    listeners.delete(event)\n    once_listeners.delete(event)\n  end\n\n  def once(event, &block)\n    once_listeners[event] << block\n  end\n\n  private\n\n  def listeners\n    @listeners ||= Hash.new { |h, k| h[k] = [] }\n  end\n\n  def once_listeners\n    @once_listeners ||= Hash.new { |h, k| h[k] = [] }\n  end\nend\n\nclass Server\n  include EventEmitter\nend\n\ns = Server.new\ns.on(:connect) { |ip| puts \"Connected: \\\#{ip}\" }\ns.once(:start) { puts \"Server started!\" }\n\ns.emit(:start)\ns.emit(:start)  # not printed again\ns.emit(:connect, \"192.168.1.1\")`, hints: ['Use hashes of arrays for event handlers', 'once handlers are removed after first emit', 'Separate storage for once handlers'], concepts: ['event_emitter'] },
    { id: 'rb-observer-8', title: 'Write Typed Event System', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write an event system with typed events.', skeleton: `# Write:\n# - Event class with :name and :data\n# - EventBus with subscribe(event_class, &handler) and publish(event)\n# - UserCreated and OrderPlaced event classes\n`, solution: `class Event\n  attr_reader :data\n  def initialize(**data)\n    @data = data\n  end\nend\n\nclass UserCreated < Event; end\nclass OrderPlaced < Event; end\n\nclass EventBus\n  def initialize\n    @subscribers = Hash.new { |h, k| h[k] = [] }\n  end\n\n  def subscribe(event_class, &handler)\n    @subscribers[event_class] << handler\n  end\n\n  def publish(event)\n    @subscribers[event.class].each { |h| h.call(event) }\n  end\nend\n\nbus = EventBus.new\nbus.subscribe(UserCreated) { |e| puts \"User: \\\#{e.data[:name]}\" }\nbus.subscribe(OrderPlaced) { |e| puts \"Order: $\\\#{e.data[:total]}\" }\n\nbus.publish(UserCreated.new(name: \"Alice\"))\nbus.publish(OrderPlaced.new(total: 99.99))`, hints: ['Use the event class as the subscription key', 'Events carry data as keyword arguments', 'publish looks up handlers by event class'], concepts: ['typed_events'] },
    { id: 'rb-observer-9', title: 'Write Reactive Property', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a class with observable properties.', skeleton: `# Write an ObservableProperty module:\n# - observable_attr(name) defines getter/setter with change notifications\n# - on_change(attr, &block) subscribes to changes\n# - Changes notify with old and new values\n`, solution: `module ObservableProperty\n  def self.included(base)\n    base.extend(ClassMethods)\n    base.instance_variable_set(:@change_handlers, Hash.new { |h, k| h[k] = [] })\n  end\n\n  module ClassMethods\n    def observable_attr(name)\n      define_method(name) { instance_variable_get(\"@\\\#{name}\") }\n      define_method(\"\\\#{name}=\") do |new_val|\n        old_val = instance_variable_get(\"@\\\#{name}\")\n        instance_variable_set(\"@\\\#{name}\", new_val)\n        if old_val != new_val\n          self.class.instance_variable_get(:@change_handlers)[name].each do |h|\n            h.call(old_val, new_val)\n          end\n        end\n      end\n    end\n\n    def on_change(attr, &block)\n      @change_handlers[attr] << block\n    end\n  end\nend\n\nclass User\n  include ObservableProperty\n  observable_attr :name\n  observable_attr :age\n  on_change(:name) { |old, new_val| puts \"Name: \\\#{old} -> \\\#{new_val}\" }\nend\n\nu = User.new\nu.name = \"Alice\"\nu.name = \"Bob\"`, hints: ['define_method for dynamic getter/setter', 'Compare old and new values before notifying', 'Store handlers per attribute name'], concepts: ['observable_property'] },
    { id: 'rb-observer-10', title: 'Write Middleware Chain', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write an observer-based middleware chain.', skeleton: `# Write a MiddlewareChain:\n# - use(&block) adds middleware\n# - call(request) runs each middleware in order\n# - Each middleware receives (request, next_middleware)\n# - Can modify request or short-circuit\n`, solution: `class MiddlewareChain\n  def initialize\n    @middlewares = []\n  end\n\n  def use(&block)\n    @middlewares << block\n    self\n  end\n\n  def call(request)\n    run_chain(request, 0)\n  end\n\n  private\n\n  def run_chain(request, index)\n    return request if index >= @middlewares.size\n    @middlewares[index].call(request) do |modified_request|\n      run_chain(modified_request, index + 1)\n    end\n  end\nend\n\nchain = MiddlewareChain.new\nchain.use do |req, &next_mw|\n  puts \"Auth check\"\n  next_mw.call(req.merge(authenticated: true))\nend\nchain.use do |req, &next_mw|\n  puts \"Logging: \\\#{req.inspect}\"\n  next_mw.call(req)\nend\n\nresult = chain.call({ path: \"/api\" })\nputs result.inspect`, hints: ['Each middleware calls next_mw.call to continue', 'Middlewares can modify the request', 'Not calling next_mw short-circuits the chain'], concepts: ['middleware_pattern'] },
    { id: 'rb-observer-11', title: 'Write Pub/Sub with Topics', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a pub/sub system with topic filtering.', skeleton: `# Write a PubSub class:\n# - subscribe(topic_pattern, &handler) where pattern can use *\n# - publish(topic, data) notifies matching subscribers\n# - \"user.*\" matches \"user.created\", \"user.deleted\"\n`, solution: `class PubSub\n  def initialize\n    @subscriptions = []\n  end\n\n  def subscribe(pattern, &handler)\n    regex = Regexp.new(\"^\" + pattern.gsub(\".\", \"\\\\.\").gsub(\"*\", \"[^.]+\") + \"$\")\n    @subscriptions << { pattern: regex, handler: handler }\n    self\n  end\n\n  def publish(topic, data = nil)\n    @subscriptions.each do |sub|\n      sub[:handler].call(topic, data) if topic.match?(sub[:pattern])\n    end\n  end\nend\n\nps = PubSub.new\nps.subscribe(\"user.*\") { |t, d| puts \"User event: \\\#{t} -> \\\#{d}\" }\nps.subscribe(\"order.created\") { |t, d| puts \"New order: \\\#{d}\" }\n\nps.publish(\"user.created\", \"Alice\")\nps.publish(\"user.deleted\", \"Bob\")\nps.publish(\"order.created\", \"#1234\")`, hints: ['Convert glob patterns to regex', '* matches one segment between dots', 'Check each subscription pattern against the topic'], concepts: ['pub_sub', 'topic_matching'] },
    { id: 'rb-observer-12', title: 'Write Observer with History', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write an observable that keeps event history.', skeleton: `# Write a HistoryObservable:\n# - on(event, &handler) subscribes\n# - emit(event, data) triggers and records\n# - history(event) returns past emissions\n# - replay(event) re-emits all past events to current subscribers\n`, solution: `class HistoryObservable\n  def initialize\n    @handlers = Hash.new { |h, k| h[k] = [] }\n    @history = Hash.new { |h, k| h[k] = [] }\n  end\n\n  def on(event, &handler)\n    @handlers[event] << handler\n  end\n\n  def emit(event, data = nil)\n    @history[event] << data\n    @handlers[event].each { |h| h.call(data) }\n  end\n\n  def history(event)\n    @history[event].dup\n  end\n\n  def replay(event)\n    @history[event].each do |data|\n      @handlers[event].each { |h| h.call(data) }\n    end\n  end\nend\n\nobs = HistoryObservable.new\nobs.emit(:click, \"button1\")\nobs.emit(:click, \"button2\")\n\nobs.on(:click) { |d| puts \"Clicked: \\\#{d}\" }\nobs.replay(:click)`, hints: ['Record each emission in a history array', 'replay iterates history and calls current handlers', 'New subscribers can catch up via replay'], concepts: ['event_history', 'replay'] },
    { id: 'rb-observer-13', title: 'Fix Missing changed Call', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the observer notification that never fires.', skeleton: `require 'observer'\n\nclass Ticker\n  include Observable\n  def tick(val)\n    # Bug: forgot to call changed\n    notify_observers(val)\n  end\nend\n\nt = Ticker.new\nt.add_observer(Object.new.tap { |o| def o.update(v) = puts v })\nt.tick(42)  # Nothing printed!`, solution: `require 'observer'\n\nclass Ticker\n  include Observable\n  def tick(val)\n    changed\n    notify_observers(val)\n  end\nend\n\nt = Ticker.new\nt.add_observer(Object.new.tap { |o| def o.update(v) = puts v })\nt.tick(42)`, hints: ['Observable requires changed before notify_observers', 'Without changed, observers are not notified', 'This is a safety mechanism to prevent unnecessary notifications'], concepts: ['changed_required'] },
    { id: 'rb-observer-14', title: 'Fix Observer Memory Leak', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the observer that is never cleaned up.', skeleton: `class EventSystem\n  def initialize\n    @handlers = Hash.new { |h, k| h[k] = [] }\n  end\n\n  def on(event, &block)\n    @handlers[event] << block\n    # Bug: no way to remove handlers, they accumulate forever\n  end\n\n  def emit(event, data)\n    @handlers[event].each { |h| h.call(data) }\n  end\nend`, solution: `class EventSystem\n  def initialize\n    @handlers = Hash.new { |h, k| h[k] = [] }\n  end\n\n  def on(event, &block)\n    @handlers[event] << block\n    block  # return the handler for later removal\n  end\n\n  def off(event, handler = nil)\n    if handler\n      @handlers[event].delete(handler)\n    else\n      @handlers.delete(event)\n    end\n  end\n\n  def emit(event, data)\n    @handlers[event].each { |h| h.call(data) }\n  end\nend`, hints: ['Return the handler from on for reference', 'Add off method to remove specific handlers', 'Allow removing all handlers for an event'], concepts: ['handler_cleanup'] },
    { id: 'rb-observer-15', title: 'Fix Observer Exception Handling', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the system where one bad observer breaks all notifications.', skeleton: `class Notifier\n  def initialize\n    @observers = []\n  end\n\n  def add(obs) = @observers << obs\n\n  def notify(data)\n    # Bug: if one observer raises, subsequent ones don't get notified\n    @observers.each { |o| o.call(data) }\n  end\nend`, solution: `class Notifier\n  def initialize\n    @observers = []\n  end\n\n  def add(obs) = @observers << obs\n\n  def notify(data)\n    @observers.each do |o|\n      begin\n        o.call(data)\n      rescue => e\n        puts \"Observer error: \\\#{e.message}\"\n      end\n    end\n  end\nend`, hints: ['Wrap each observer call in begin/rescue', 'One failing observer should not stop others', 'Log the error and continue'], concepts: ['error_isolation'] },
    { id: 'rb-observer-16', title: 'Predict Observer Order', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict observer notification order.', skeleton: `class Bus\n  def initialize = @subs = []\n  def on(&b) = @subs << b\n  def emit(d) = @subs.each { |s| s.call(d) }\nend\n\nbus = Bus.new\nbus.on { |d| puts \"A: \\\#{d}\" }\nbus.on { |d| puts \"B: \\\#{d}\" }\nbus.on { |d| puts \"C: \\\#{d}\" }\nbus.emit(\"hello\")`, solution: `A: hello\nB: hello\nC: hello`, hints: ['Observers are notified in subscription order', 'Each iterates the array in order', 'All observers receive the same data'], concepts: ['notification_order'] },
    { id: 'rb-observer-17', title: 'Predict Multiple Events', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict output with multiple event types.', skeleton: `class E\n  def initialize = @h = Hash.new { |h, k| h[k] = [] }\n  def on(e, &b) = @h[e] << b\n  def emit(e, d) = @h[e].each { |b| b.call(d) }\nend\n\ne = E.new\ne.on(:a) { |d| puts \"A: \\\#{d}\" }\ne.on(:b) { |d| puts \"B: \\\#{d}\" }\ne.on(:a) { |d| puts \"A2: \\\#{d}\" }\n\ne.emit(:a, 1)\ne.emit(:b, 2)`, solution: `A: 1\nA2: 1\nB: 2`, hints: ['Event :a has two handlers', 'Event :b has one handler', 'Only matching event handlers fire'], concepts: ['event_filtering'] },
    { id: 'rb-observer-18', title: 'Predict Once Behavior', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict once-only observer behavior.', skeleton: `class E\n  def initialize\n    @subs = []\n    @once = []\n  end\n  def on(&b) = @subs << b\n  def once(&b) = @once << b\n  def emit(d)\n    @subs.each { |s| s.call(d) }\n    @once.each { |s| s.call(d) }\n    @once.clear\n  end\nend\n\ne = E.new\ne.on { |d| puts \"on: \\\#{d}\" }\ne.once { |d| puts \"once: \\\#{d}\" }\ne.emit(1)\ne.emit(2)`, solution: `on: 1\nonce: 1\non: 2`, hints: ['on handler fires every time', 'once handler fires only on first emit', 'After first emit, once handlers are cleared'], concepts: ['once_semantics'] },
    { id: 'rb-observer-19', title: 'Refactor Polling to Observer', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor polling-based checks to observer pattern.', skeleton: `# Polling approach - wasteful\nclass DataStore\n  attr_reader :data\n  def initialize = @data = nil\n  def update(val) = @data = val\nend\n\nstore = DataStore.new\n# Client polls:\n# loop { break if store.data; sleep 0.1 }`, solution: `class DataStore\n  def initialize\n    @data = nil\n    @observers = []\n  end\n\n  def on_update(&block)\n    @observers << block\n  end\n\n  def update(val)\n    @data = val\n    @observers.each { |o| o.call(val) }\n  end\nend\n\nstore = DataStore.new\nstore.on_update { |val| puts \"Data ready: \\\#{val}\" }\nstore.update(\"result\")`, hints: ['Replace polling with callbacks', 'Notify observers when data changes', 'No need for sleep loops'], concepts: ['polling_to_observer'] },
    { id: 'rb-observer-20', title: 'Refactor Direct Coupling to Events', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor tightly coupled classes to use events.', skeleton: `class OrderService\n  def initialize(email_service, inventory_service, analytics)\n    @email = email_service\n    @inventory = inventory_service\n    @analytics = analytics\n  end\n\n  def place_order(order)\n    # Tightly coupled to all services\n    @email.send_confirmation(order)\n    @inventory.reserve(order.items)\n    @analytics.track(\"order_placed\", order.id)\n  end\nend`, solution: `class OrderService\n  include EventEmitter  # from exercise 7\n\n  def place_order(order)\n    # Process order...\n    emit(:order_placed, order)\n  end\nend\n\n# Each service subscribes independently\norder_service = OrderService.new\norder_service.on(:order_placed) { |o| EmailService.send_confirmation(o) }\norder_service.on(:order_placed) { |o| InventoryService.reserve(o.items) }\norder_service.on(:order_placed) { |o| Analytics.track(\"order_placed\", o.id) }`, hints: ['OrderService should not know about email, inventory, analytics', 'Emit an event and let subscribers handle it', 'New services can subscribe without modifying OrderService'], concepts: ['decoupling', 'event_driven'] },
  ],
};
