import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-strategy',
  title: '44. Strategy',
  explanation: `## Strategy Pattern in Ruby

The Strategy pattern defines a family of algorithms, encapsulates each one, and makes them interchangeable.

### Duck Typing Strategy

\`\`\`ruby
class Sorter
  def initialize(strategy)
    @strategy = strategy
  end

  def sort(data)
    @strategy.sort(data)
  end
end

class BubbleSort
  def sort(data)
    # bubble sort implementation
  end
end

class QuickSort
  def sort(data)
    # quick sort implementation
  end
end
\`\`\`

### Proc/Lambda Strategy

\`\`\`ruby
formatter = ->(text) { text.upcase }
sorter.sort(data, &formatter)
\`\`\`

### Built-in Strategy: sort_by

\`\`\`ruby
users.sort_by { |u| u.name }        # strategy: sort by name
users.sort_by { |u| -u.age }        # strategy: sort by age desc
users.sort_by { |u| [u.role, u.name] }  # multi-key
\`\`\``,
  exercises: [
    { id: 'rb-strategy-1', title: 'Basic Strategy', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Inject a strategy object.', skeleton: `class Formatter\n  def initialize(strategy)\n    @___ = strategy\n  end\n\n  def format(text)\n    @strategy.___(text)\n  end\nend`, solution: `class Formatter\n  def initialize(strategy)\n    @strategy = strategy\n  end\n\n  def format(text)\n    @strategy.call(text)\n  end\nend`, hints: ['Store the strategy', 'Call the strategy to execute it', 'Strategies respond to call'], concepts: ['strategy_injection'] },
    { id: 'rb-strategy-2', title: 'Lambda Strategy', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use a lambda as strategy.', skeleton: `upcase_strategy = ___ { |t| t.upcase }\ndowncase_strategy = ___ { |t| t.downcase }\n\nf = Formatter.new(upcase_strategy)\nputs f.format(\"hello\")`, solution: `upcase_strategy = lambda { |t| t.upcase }\ndowncase_strategy = lambda { |t| t.downcase }\n\nf = Formatter.new(upcase_strategy)\nputs f.format(\"hello\")`, hints: ['lambda creates a strategy object', 'Lambdas respond to .call', 'They can be passed like any object'], concepts: ['lambda_strategy'] },
    { id: 'rb-strategy-3', title: 'Strategy Swap', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Swap strategy at runtime.', skeleton: `class Compressor\n  attr_writer :___\n\n  def compress(data)\n    @strategy.call(data)\n  end\nend\n\nc = Compressor.new\nc.strategy = ->(d) { d.chars.uniq.join }\nputs c.compress(\"aabbcc\")`, solution: `class Compressor\n  attr_writer :strategy\n\n  def compress(data)\n    @strategy.call(data)\n  end\nend\n\nc = Compressor.new\nc.strategy = ->(d) { d.chars.uniq.join }\nputs c.compress(\"aabbcc\")`, hints: ['attr_writer creates a setter', 'The strategy can be changed at any time', 'New strategy takes effect immediately'], concepts: ['runtime_swap'] },
    { id: 'rb-strategy-4', title: 'Duck Typing Strategy', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use duck typing for strategies.', skeleton: `class JsonRenderer\n  def render(data)\n    data.to_s\n  end\nend\n\nclass XmlRenderer\n  def ___(data)\n    \"<data>\\\#{data}</data>\"\n  end\nend\n\nclass Report\n  def initialize(renderer)\n    @renderer = renderer\n  end\n\n  def generate(data)\n    @renderer.render(data)\n  end\nend`, solution: `class JsonRenderer\n  def render(data)\n    data.to_s\n  end\nend\n\nclass XmlRenderer\n  def render(data)\n    \"<data>\\\#{data}</data>\"\n  end\nend\n\nclass Report\n  def initialize(renderer)\n    @renderer = renderer\n  end\n\n  def generate(data)\n    @renderer.render(data)\n  end\nend`, hints: ['Both renderers must respond to render', 'Duck typing: if it quacks like a render, it is a render', 'No interface needed, just matching method names'], concepts: ['duck_typing'] },
    { id: 'rb-strategy-5', title: 'Block as Strategy', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Accept a block as strategy.', skeleton: `class Filter\n  def filter(items, ___)\n    items.select(&strategy)\n  end\nend\n\nf = Filter.new\nputs f.filter([1,2,3,4,5]) { |n| n.odd? }.inspect`, solution: `class Filter\n  def filter(items, &strategy)\n    items.select(&strategy)\n  end\nend\n\nf = Filter.new\nputs f.filter([1,2,3,4,5]) { |n| n.odd? }.inspect`, hints: ['&strategy captures the block as a Proc', 'Pass it to select with &', 'Blocks are the simplest strategy form'], concepts: ['block_strategy'] },
    { id: 'rb-strategy-6', title: 'Strategy with sort_by', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use sort_by with different strategies.', skeleton: `words = [\"banana\", \"apple\", \"cherry\", \"date\"]\n\nby_alpha = words.sort_by { |w| w }\nby_length = words.___ { |w| w.length }\nby_last = words.sort_by { |w| w[-1] }\n\nputs by_length.inspect`, solution: `words = [\"banana\", \"apple\", \"cherry\", \"date\"]\n\nby_alpha = words.sort_by { |w| w }\nby_length = words.sort_by { |w| w.length }\nby_last = words.sort_by { |w| w[-1] }\n\nputs by_length.inspect`, hints: ['sort_by takes a block as the sorting strategy', 'The block returns the comparison key', 'Different blocks = different sort strategies'], concepts: ['sort_by_strategy'] },
    { id: 'rb-strategy-7', title: 'Write Pricing Strategy', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a pricing calculator with swappable strategies.', skeleton: `# Write:\n# - RegularPricing: price as-is\n# - MemberPricing: 10% discount\n# - VIPPricing: 20% discount + free shipping (shipping = 0)\n# - PriceCalculator takes a strategy and calculates total(price, shipping)\n`, solution: `class RegularPricing\n  def calculate(price, shipping)\n    price + shipping\n  end\nend\n\nclass MemberPricing\n  def calculate(price, shipping)\n    price * 0.9 + shipping\n  end\nend\n\nclass VIPPricing\n  def calculate(price, shipping)\n    price * 0.8\n  end\nend\n\nclass PriceCalculator\n  def initialize(strategy)\n    @strategy = strategy\n  end\n\n  def total(price, shipping = 5.0)\n    @strategy.calculate(price, shipping)\n  end\nend\n\nputs PriceCalculator.new(RegularPricing.new).total(100)\nputs PriceCalculator.new(MemberPricing.new).total(100)\nputs PriceCalculator.new(VIPPricing.new).total(100)`, hints: ['Each strategy implements calculate(price, shipping)', 'VIP ignores shipping', 'The calculator delegates to the strategy'], concepts: ['pricing_strategy'] },
    { id: 'rb-strategy-8', title: 'Write Validation Strategy', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a validator with composable strategies.', skeleton: `# Write:\n# - Validator class that takes multiple strategy procs\n# - validate(value) runs all strategies, returns array of error messages\n# - Strategies: presence, min_length(n), format(regex)\n`, solution: `class Validator\n  def initialize(*strategies)\n    @strategies = strategies\n  end\n\n  def validate(value)\n    @strategies.filter_map { |s| s.call(value) }\n  end\n\n  def valid?(value)\n    validate(value).empty?\n  end\nend\n\npresence = ->(v) { \"can't be blank\" if v.nil? || v.empty? }\nmin_length = ->(n) { ->(v) { \"must be at least \\\#{n} chars\" if v && v.length < n } }\nformat_check = ->(re, msg) { ->(v) { msg if v && !v.match?(re) } }\n\nemail_validator = Validator.new(\n  presence,\n  min_length.call(5),\n  format_check.call(/@/, \"must contain @\")\n)\n\nputs email_validator.validate(\"\").inspect\nputs email_validator.validate(\"abc\").inspect\nputs email_validator.validate(\"user@example.com\").inspect`, hints: ['Strategies return an error message or nil', 'filter_map collects non-nil results', 'Higher-order lambdas create parameterized strategies'], concepts: ['composable_strategies'] },
    { id: 'rb-strategy-9', title: 'Write Cache Strategy', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a cache with pluggable eviction strategies.', skeleton: `# Write:\n# - Cache class with get/set and max_size\n# - LRU strategy: evict least recently used\n# - FIFO strategy: evict oldest entry\n# Strategy determines which key to evict when full\n`, solution: `class FIFOStrategy\n  def initialize = @order = []\n  def access(key) = @order << key unless @order.include?(key)\n  def evict_key = @order.shift\nend\n\nclass LRUStrategy\n  def initialize = @order = []\n  def access(key)\n    @order.delete(key)\n    @order << key\n  end\n  def evict_key = @order.shift\nend\n\nclass Cache\n  def initialize(max_size:, strategy:)\n    @max = max_size\n    @strategy = strategy\n    @store = {}\n  end\n\n  def set(key, value)\n    evict if @store.size >= @max && !@store.key?(key)\n    @store[key] = value\n    @strategy.access(key)\n  end\n\n  def get(key)\n    val = @store[key]\n    @strategy.access(key) if val\n    val\n  end\n\n  private\n\n  def evict\n    key = @strategy.evict_key\n    @store.delete(key)\n  end\nend\n\ncache = Cache.new(max_size: 3, strategy: LRUStrategy.new)\ncache.set(:a, 1)\ncache.set(:b, 2)\ncache.set(:c, 3)\ncache.get(:a)  # makes :a recently used\ncache.set(:d, 4)  # evicts :b (LRU)\nputs cache.get(:a)\nputs cache.get(:b).inspect`, hints: ['Strategy tracks access order', 'evict_key returns the key to remove', 'LRU moves accessed keys to the end'], concepts: ['cache_eviction'] },
    { id: 'rb-strategy-10', title: 'Write Retry Strategy', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a retry mechanism with pluggable backoff strategies.', skeleton: `# Write:\n# - with_retry(max_attempts:, backoff:, &block)\n# - Backoff strategies: constant(n), linear(base), exponential(base)\n# - Each strategy.wait(attempt) returns seconds to wait\n`, solution: `ConstantBackoff = ->(delay) { ->(_attempt) { delay } }\nLinearBackoff = ->(base) { ->(attempt) { base * attempt } }\nExponentialBackoff = ->(base) { ->(attempt) { base ** attempt } }\n\ndef with_retry(max_attempts:, backoff:)\n  attempts = 0\n  begin\n    attempts += 1\n    yield attempts\n  rescue => e\n    if attempts < max_attempts\n      wait = backoff.call(attempts)\n      puts \"Attempt \\\#{attempts} failed, retrying in \\\#{wait}s...\"\n      sleep(wait) if wait > 0\n      retry\n    end\n    raise\n  end\nend\n\nwith_retry(max_attempts: 3, backoff: ExponentialBackoff.call(0.01)) do |attempt|\n  puts \"Attempt \\\#{attempt}\"\n  raise \"fail\" if attempt < 3\n  puts \"Success!\"\nend`, hints: ['Backoff strategies are lambdas returning lambdas', 'The inner lambda takes attempt number', 'retry re-enters the begin block'], concepts: ['retry_strategy', 'backoff'] },
    { id: 'rb-strategy-11', title: 'Write Strategy Registry', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a strategy registry for lookup by name.', skeleton: `# Write a StrategyRegistry:\n# - register(name, strategy) stores strategies\n# - get(name) retrieves a strategy\n# - execute(name, *args) finds and calls the strategy\n# Register :upcase, :reverse, :titleize string strategies\n`, solution: `class StrategyRegistry\n  def initialize\n    @strategies = {}\n  end\n\n  def register(name, strategy = nil, &block)\n    @strategies[name] = strategy || block\n  end\n\n  def get(name)\n    @strategies.fetch(name) { raise \"Unknown strategy: \\\#{name}\" }\n  end\n\n  def execute(name, *args)\n    get(name).call(*args)\n  end\nend\n\nreg = StrategyRegistry.new\nreg.register(:upcase) { |s| s.upcase }\nreg.register(:reverse) { |s| s.reverse }\nreg.register(:titleize) { |s| s.split.map(&:capitalize).join(\" \") }\n\nputs reg.execute(:upcase, \"hello world\")\nputs reg.execute(:titleize, \"hello world\")`, hints: ['Accept both objects and blocks', 'Store in a hash by name', 'execute looks up and calls'], concepts: ['strategy_registry'] },
    { id: 'rb-strategy-12', title: 'Write Composable Strategies', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write strategies that can be composed (piped together).', skeleton: `# Write a Pipeline class:\n# - pipe(strategy) adds a step\n# - call(input) runs all steps in order\n# - Strategies are lambdas or objects with .call\n# Allow >> operator for composing\n`, solution: `class Pipeline\n  def initialize\n    @steps = []\n  end\n\n  def pipe(strategy)\n    @steps << strategy\n    self\n  end\n\n  def >>(strategy)\n    pipe(strategy)\n  end\n\n  def call(input)\n    @steps.reduce(input) { |data, step| step.call(data) }\n  end\nend\n\nupcase = ->(s) { s.upcase }\nstrip = ->(s) { s.strip }\nadd_bang = ->(s) { s + \"!\" }\n\npipeline = Pipeline.new\npipeline.pipe(strip).pipe(upcase).pipe(add_bang)\n\nputs pipeline.call(\"  hello world  \")`, hints: ['reduce chains the steps: output of one is input to next', 'pipe returns self for chaining', '>> is an operator alias for pipe'], concepts: ['pipeline', 'composition'] },
    { id: 'rb-strategy-13', title: 'Fix Missing Strategy Error', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the nil strategy crash.', skeleton: `class Processor\n  def initialize(strategy = nil)\n    @strategy = strategy\n  end\n\n  def process(data)\n    @strategy.call(data)  # NoMethodError when strategy is nil\n  end\nend\n\np = Processor.new\nputs p.process(\"hello\")`, solution: `class Processor\n  DEFAULT = ->(data) { data }\n\n  def initialize(strategy = nil)\n    @strategy = strategy || DEFAULT\n  end\n\n  def process(data)\n    @strategy.call(data)\n  end\nend\n\np = Processor.new\nputs p.process(\"hello\")`, hints: ['Provide a default strategy that passes data through', 'Use || to fall back to the default', 'A pass-through lambda is a good null strategy'], concepts: ['null_strategy'] },
    { id: 'rb-strategy-14', title: 'Fix Strategy Interface Mismatch', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the strategy that uses the wrong method name.', skeleton: `class Sorter\n  def initialize(algo)\n    @algo = algo\n  end\n\n  def sort(arr)\n    @algo.sort(arr)  # NoMethodError\n  end\nend\n\nclass MySorter\n  def execute(arr)  # wrong method name!\n    arr.sort\n  end\nend\n\nSorter.new(MySorter.new).sort([3,1,2])`, solution: `class Sorter\n  def initialize(algo)\n    @algo = algo\n  end\n\n  def sort(arr)\n    @algo.sort(arr)\n  end\nend\n\nclass MySorter\n  def sort(arr)\n    arr.sort\n  end\nend\n\nputs Sorter.new(MySorter.new).sort([3,1,2]).inspect`, hints: ['The strategy must match the expected interface', 'Rename execute to sort', 'Duck typing requires matching method names'], concepts: ['interface_contract'] },
    { id: 'rb-strategy-15', title: 'Fix Hardcoded Strategy', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor hardcoded logic to accept a strategy.', skeleton: `class TaxCalculator\n  def calculate(amount, country)\n    # Bug: hardcoded tax rates, can't change without modifying class\n    case country\n    when :us then amount * 0.08\n    when :uk then amount * 0.20\n    when :jp then amount * 0.10\n    end\n  end\nend`, solution: `class TaxCalculator\n  def initialize(rates = {})\n    @rates = rates\n  end\n\n  def calculate(amount, country)\n    rate = @rates.fetch(country) { raise \"Unknown country: \\\#{country}\" }\n    amount * rate\n  end\nend\n\ncalc = TaxCalculator.new(us: 0.08, uk: 0.20, jp: 0.10)\nputs calc.calculate(100, :us)\nputs calc.calculate(100, :uk)`, hints: ['Extract the rates into a configuration', 'Pass rates as a hash to the constructor', 'New countries can be added without code changes'], concepts: ['externalize_strategy'] },
    { id: 'rb-strategy-16', title: 'Predict Strategy Output', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict which strategy is used.', skeleton: `strategies = {\n  a: ->(x) { x * 2 },\n  b: ->(x) { x + 10 },\n  c: ->(x) { x ** 2 }\n}\n\nputs strategies[:b].call(5)\nputs strategies[:c].call(3)\nputs strategies[:a].call(7)`, solution: `15\n9\n14`, hints: [':b adds 10: 5+10=15', ':c squares: 3**2=9', ':a doubles: 7*2=14'], concepts: ['lambda_lookup'] },
    { id: 'rb-strategy-17', title: 'Predict sort_by Result', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict sort_by with different strategies.', skeleton: `data = [{n: \"c\", v: 1}, {n: \"a\", v: 3}, {n: \"b\", v: 2}]\n\nby_name = data.sort_by { |d| d[:n] }.map { |d| d[:n] }\nby_val = data.sort_by { |d| d[:v] }.map { |d| d[:n] }\n\nputs by_name.inspect\nputs by_val.inspect`, solution: `[\"a\", \"b\", \"c\"]\n[\"c\", \"b\", \"a\"]`, hints: ['by_name sorts alphabetically: a, b, c', 'by_val sorts by value: 1(c), 2(b), 3(a)', 'Different strategies produce different orders'], concepts: ['sort_by_comparison'] },
    { id: 'rb-strategy-18', title: 'Predict Pipeline', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict composed strategy output.', skeleton: `steps = [\n  ->(x) { x + 1 },\n  ->(x) { x * 3 },\n  ->(x) { x - 2 }\n]\n\nresult = steps.reduce(5) { |v, step| step.call(v) }\nputs result`, solution: `16`, hints: ['Step 1: 5 + 1 = 6', 'Step 2: 6 * 3 = 18', 'Step 3: 18 - 2 = 16'], concepts: ['reduce_pipeline'] },
    { id: 'rb-strategy-19', title: 'Refactor If/Else to Strategy', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor conditional discount logic to strategies.', skeleton: `class Order\n  def discount(type, subtotal)\n    if type == :percent_10\n      subtotal * 0.10\n    elsif type == :flat_5\n      5.0\n    elsif type == :buy2_get1\n      subtotal / 3.0\n    else\n      0\n    end\n  end\nend`, solution: `DISCOUNTS = {\n  percent_10: ->(subtotal) { subtotal * 0.10 },\n  flat_5: ->(_subtotal) { 5.0 },\n  buy2_get1: ->(subtotal) { subtotal / 3.0 },\n}\n\nclass Order\n  def discount(type, subtotal)\n    strategy = DISCOUNTS.fetch(type, ->(_) { 0 })\n    strategy.call(subtotal)\n  end\nend\n\no = Order.new\nputs o.discount(:percent_10, 100)\nputs o.discount(:flat_5, 100)\nputs o.discount(:unknown, 100)`, hints: ['Extract each branch into a lambda', 'Store in a hash keyed by type', 'fetch with default handles unknown types'], concepts: ['conditional_to_strategy'] },
    { id: 'rb-strategy-20', title: 'Refactor Inheritance to Strategy', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor class hierarchy to strategy composition.', skeleton: `class Report\n  def generate = raise NotImplementedError\nend\n\nclass PdfReport < Report\n  def generate = \"PDF output\"\nend\n\nclass HtmlReport < Report\n  def generate = \"HTML output\"\nend\n\nclass CsvReport < Report\n  def generate = \"CSV output\"\nend\n\n# Adding a new format requires a new subclass\n# Cannot combine formats`, solution: `class Report\n  def initialize(formatter)\n    @formatter = formatter\n  end\n\n  def generate(data)\n    @formatter.call(data)\n  end\nend\n\nFORMATTERS = {\n  pdf: ->(data) { \"PDF: \\\#{data}\" },\n  html: ->(data) { \"<html>\\\#{data}</html>\" },\n  csv: ->(data) { data.to_s.tr(\" \", \",\") },\n}\n\npdf_report = Report.new(FORMATTERS[:pdf])\nputs pdf_report.generate(\"Sales Data\")\n\nhtml_report = Report.new(FORMATTERS[:html])\nputs html_report.generate(\"Sales Data\")`, hints: ['One Report class with injectable formatter', 'Formatters are lambdas in a hash', 'New formats are added without subclassing'], concepts: ['composition_over_inheritance'] },
  ],
};
