import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-decorator',
  title: '45. Decorator',
  explanation: `## Decorator Pattern in Ruby

The Decorator pattern dynamically adds behavior to objects without modifying their class. Ruby offers several approaches.

### SimpleDelegator Decorator

\`\`\`ruby
require 'delegate'

class Coffee
  def cost = 2.0
  def description = "Coffee"
end

class MilkDecorator < SimpleDelegator
  def cost = super + 0.5
  def description = super + " + Milk"
end

coffee = MilkDecorator.new(Coffee.new)
\`\`\`

### Module Decorator (prepend)

\`\`\`ruby
module Logging
  def execute(*args)
    puts "Before"
    result = super
    puts "After"
    result
  end
end

class Service
  prepend Logging
  def execute = "done"
end
\`\`\`

### Proc/Lambda Decorator

\`\`\`ruby
def with_timing(method)
  ->(*args) {
    start = Time.now
    result = method.call(*args)
    puts "Took: \#{Time.now - start}s"
    result
  }
end
\`\`\``,
  exercises: [
    { id: 'rb-decorator-1', title: 'SimpleDelegator Decorator', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Create a decorator with SimpleDelegator.', skeleton: `require 'delegate'\n\nclass Pizza\n  def cost = 8.0\n  def toppings = \"cheese\"\nend\n\nclass PepperoniDecorator < ___\n  def cost = ___ + 2.0\n  def toppings = ___ + \", pepperoni\"\nend`, solution: `require 'delegate'\n\nclass Pizza\n  def cost = 8.0\n  def toppings = \"cheese\"\nend\n\nclass PepperoniDecorator < SimpleDelegator\n  def cost = super + 2.0\n  def toppings = super + \", pepperoni\"\nend`, hints: ['Inherit from SimpleDelegator', 'super calls the wrapped object method', 'Each decorator adds to the base behavior'], concepts: ['simple_delegator_decorator'] },
    { id: 'rb-decorator-2', title: 'Prepend Decorator', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use prepend as a decorator.', skeleton: `module TimingDecorator\n  def process\n    start = Time.now\n    result = ___\n    puts \"Took: \\\#{Time.now - start}s\"\n    result\n  end\nend\n\nclass Worker\n  ___ TimingDecorator\n  def process = \"done\"\nend`, solution: `module TimingDecorator\n  def process\n    start = Time.now\n    result = super\n    puts \"Took: \\\#{Time.now - start}s\"\n    result\n  end\nend\n\nclass Worker\n  prepend TimingDecorator\n  def process = \"done\"\nend`, hints: ['prepend inserts module before class in lookup', 'super calls the original method', 'The decorator wraps the original behavior'], concepts: ['prepend_decorator'] },
    { id: 'rb-decorator-3', title: 'Stacking Decorators', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Stack multiple decorators.', skeleton: `require 'delegate'\n\nclass Base\n  def value = 1\nend\n\nclass Double < SimpleDelegator\n  def value = super * 2\nend\n\nclass AddTen < SimpleDelegator\n  def value = super + 10\nend\n\nresult = ___.new(___.new(Base.new))\nputs result.value`, solution: `require 'delegate'\n\nclass Base\n  def value = 1\nend\n\nclass Double < SimpleDelegator\n  def value = super * 2\nend\n\nclass AddTen < SimpleDelegator\n  def value = super + 10\nend\n\nresult = AddTen.new(Double.new(Base.new))\nputs result.value`, hints: ['Wrap Base in Double, then in AddTen', 'Inner decorator runs first', 'Base(1) -> Double(2) -> AddTen(12)'], concepts: ['stacking'] },
    { id: 'rb-decorator-4', title: 'Module Extension Decorator', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Decorate a single object with extend.', skeleton: `module Shout\n  def to_s\n    ___.upcase + \"!!!\"\n  end\nend\n\nstr = \"hello\"\nstr.___(Shout)\nputs str.to_s`, solution: `module Shout\n  def to_s\n    super.upcase + \"!!!\"\n  end\nend\n\nstr = \"hello\"\nstr.extend(Shout)\nputs str.to_s`, hints: ['extend adds module methods to a single object', 'super calls the original to_s', 'Only this specific string gets the decoration'], concepts: ['extend_decorator'] },
    { id: 'rb-decorator-5', title: 'Method Wrapper', type: 'fill-blank', difficulty: 'advanced', language: 'ruby', goal: 'Wrap a method with a decorator.', skeleton: `class Service\n  def call(x)\n    x * 2\n  end\nend\n\ns = Service.new\noriginal = s.method(:call)\n\ndecorated = ___ do |*args|\n  puts \"Input: \\\#{args.inspect}\"\n  result = original.call(*args)\n  puts \"Output: \\\#{result}\"\n  result\nend`, solution: `class Service\n  def call(x)\n    x * 2\n  end\nend\n\ns = Service.new\noriginal = s.method(:call)\n\ndecorated = lambda do |*args|\n  puts \"Input: \\\#{args.inspect}\"\n  result = original.call(*args)\n  puts \"Output: \\\#{result}\"\n  result\nend`, hints: ['Capture the method as an object', 'Wrap it in a lambda', 'The lambda adds behavior around the original call'], concepts: ['method_wrapping'] },
    { id: 'rb-decorator-6', title: 'Conditional Decorator', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Apply decorator conditionally.', skeleton: `require 'delegate'\n\nclass Logger < SimpleDelegator\n  def execute\n    puts \"Executing...\"\n    ___\n  end\nend\n\nclass Task\n  def execute = \"done\"\nend\n\ntask = Task.new\ntask = Logger.new(task) ___ ENV[\"DEBUG\"]\nputs task.execute`, solution: `require 'delegate'\n\nclass Logger < SimpleDelegator\n  def execute\n    puts \"Executing...\"\n    super\n  end\nend\n\nclass Task\n  def execute = \"done\"\nend\n\ntask = Task.new\ntask = Logger.new(task) if ENV[\"DEBUG\"]\nputs task.execute`, hints: ['Apply the decorator only when condition is met', 'if/unless after the expression', 'Without the decorator, task remains unwrapped'], concepts: ['conditional_decoration'] },
    { id: 'rb-decorator-7', title: 'Write Coffee Shop Decorators', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a coffee order system with stackable decorators.', skeleton: `require 'delegate'\n\n# Write:\n# - Coffee class: cost = 2.0, description = \"Coffee\"\n# - MilkDecorator: +0.5, \"+ Milk\"\n# - SugarDecorator: +0.25, \"+ Sugar\"\n# - WhipDecorator: +0.75, \"+ Whipped Cream\"\n# Stack them and show total\n`, solution: `require 'delegate'\n\nclass Coffee\n  def cost = 2.0\n  def description = \"Coffee\"\nend\n\nclass MilkDecorator < SimpleDelegator\n  def cost = super + 0.5\n  def description = super + \" + Milk\"\nend\n\nclass SugarDecorator < SimpleDelegator\n  def cost = super + 0.25\n  def description = super + \" + Sugar\"\nend\n\nclass WhipDecorator < SimpleDelegator\n  def cost = super + 0.75\n  def description = super + \" + Whipped Cream\"\nend\n\norder = WhipDecorator.new(SugarDecorator.new(MilkDecorator.new(Coffee.new)))\nputs order.description\nputs \"$\\\#{order.cost}\"`, hints: ['Each decorator wraps the previous', 'super propagates through the chain', 'Order of wrapping determines description order'], concepts: ['coffee_decorator'] },
    { id: 'rb-decorator-8', title: 'Write Logging Decorator', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a generic logging decorator.', skeleton: `# Write a LoggingDecorator that:\n# - Wraps any object\n# - Logs method name and args before each call\n# - Logs return value after each call\n# - Uses method_missing to intercept all calls\n`, solution: `class LoggingDecorator\n  def initialize(target, logger: $stdout)\n    @target = target\n    @logger = logger\n  end\n\n  def method_missing(name, *args, &block)\n    if @target.respond_to?(name)\n      @logger.puts \"[CALL] \\\#{name}(\\\#{args.map(&:inspect).join(', ')})\"\n      result = @target.send(name, *args, &block)\n      @logger.puts \"[RETURN] \\\#{result.inspect}\"\n      result\n    else\n      super\n    end\n  end\n\n  def respond_to_missing?(name, include_private = false)\n    @target.respond_to?(name, include_private) || super\n  end\nend\n\narr = LoggingDecorator.new([1, 2, 3])\narr.push(4)\nputs arr.length`, hints: ['method_missing intercepts all calls', 'Forward to the target object', 'Log before and after the call'], concepts: ['generic_decorator'] },
    { id: 'rb-decorator-9', title: 'Write Retry Decorator', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a decorator that adds retry logic to any method.', skeleton: `require 'delegate'\n\n# Write a RetryDecorator:\n# - Wraps an object\n# - Retries failed method calls up to max_retries times\n# - Only retries methods listed in retry_methods array\n`, solution: `require 'delegate'\n\nclass RetryDecorator < SimpleDelegator\n  def initialize(target, max_retries: 3, retry_methods: [])\n    super(target)\n    @max_retries = max_retries\n    @retry_methods = retry_methods\n  end\n\n  def method_missing(name, *args, &block)\n    if @retry_methods.include?(name)\n      attempts = 0\n      begin\n        attempts += 1\n        super\n      rescue => e\n        if attempts < @max_retries\n          puts \"Retry \\\#{attempts} for \\\#{name}: \\\#{e.message}\"\n          retry\n        end\n        raise\n      end\n    else\n      super\n    end\n  end\nend\n\nclass FlakeyService\n  def initialize = @calls = 0\n  def fetch\n    @calls += 1\n    raise \"Timeout\" if @calls < 3\n    \"data\"\n  end\nend\n\nservice = RetryDecorator.new(FlakeyService.new, max_retries: 3, retry_methods: [:fetch])\nputs service.fetch`, hints: ['Override method_missing for selected methods', 'Use begin/rescue/retry for retry logic', 'Non-retry methods pass through with super'], concepts: ['retry_decorator'] },
    { id: 'rb-decorator-10', title: 'Write Caching Decorator', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a decorator that caches method results.', skeleton: `require 'delegate'\n\n# Write a CachingDecorator:\n# - Wraps any object\n# - Caches results of specified methods by arguments\n# - cache_clear resets the cache\n`, solution: `require 'delegate'\n\nclass CachingDecorator < SimpleDelegator\n  def initialize(target, cached_methods: [])\n    super(target)\n    @cached_methods = cached_methods\n    @cache = {}\n  end\n\n  def method_missing(name, *args, &block)\n    if @cached_methods.include?(name)\n      key = [name, args]\n      @cache[key] ||= super\n    else\n      super\n    end\n  end\n\n  def cache_clear\n    @cache.clear\n  end\nend\n\nclass Calculator\n  def expensive(n)\n    puts \"Computing \\\#{n}...\"\n    n ** 2\n  end\nend\n\ncalc = CachingDecorator.new(Calculator.new, cached_methods: [:expensive])\nputs calc.expensive(5)\nputs calc.expensive(5)  # cached\nputs calc.expensive(10)`, hints: ['Cache key is [method_name, args]', 'Use ||= for cache-on-first-call', 'cache_clear allows manual invalidation'], concepts: ['caching_decorator'] },
    { id: 'rb-decorator-11', title: 'Write Authorization Decorator', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a decorator that checks permissions.', skeleton: `require 'delegate'\n\n# Write an AuthDecorator:\n# - Wraps a service object\n# - Takes a user and required_role\n# - Protected methods raise \"Unauthorized\" if user role doesn't match\n`, solution: `require 'delegate'\n\nclass AuthDecorator < SimpleDelegator\n  def initialize(target, user:, required_role:, protected_methods: [])\n    super(target)\n    @user = user\n    @required_role = required_role\n    @protected = protected_methods\n  end\n\n  def method_missing(name, *args, &block)\n    if @protected.include?(name)\n      unless @user[:role] == @required_role\n        raise \"Unauthorized: \\\#{@user[:name]} cannot access \\\#{name}\"\n      end\n    end\n    super\n  end\nend\n\nclass AdminPanel\n  def view_users = \"User list\"\n  def delete_user(id) = \"Deleted \\\#{id}\"\nend\n\nadmin = { name: \"Alice\", role: :admin }\nguest = { name: \"Bob\", role: :guest }\n\npanel = AuthDecorator.new(AdminPanel.new, user: admin, required_role: :admin, protected_methods: [:delete_user])\nputs panel.view_users\nputs panel.delete_user(1)\n\npanel2 = AuthDecorator.new(AdminPanel.new, user: guest, required_role: :admin, protected_methods: [:delete_user])\nbegin\n  panel2.delete_user(1)\nrescue => e\n  puts e.message\nend`, hints: ['Check role before forwarding protected methods', 'Unprotected methods pass through', 'Raise on authorization failure'], concepts: ['authorization_decorator'] },
    { id: 'rb-decorator-12', title: 'Write Decorator with Proc', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a functional decorator using Proc composition.', skeleton: `# Write a decorate method that wraps a proc:\n# - decorate(original, *decorators) applies decorators in order\n# - Each decorator is a proc that takes (original_proc, *args)\n# Show with timing, logging, and validation decorators\n`, solution: `def decorate(original, *decorators)\n  decorators.reduce(original) do |fn, decorator|\n    ->(*args) { decorator.call(fn, *args) }\n  end\nend\n\ntiming = ->(fn, *args) {\n  start = Time.now\n  result = fn.call(*args)\n  puts \"Time: \\\#{Time.now - start}s\"\n  result\n}\n\nlogging = ->(fn, *args) {\n  puts \"Args: \\\#{args.inspect}\"\n  result = fn.call(*args)\n  puts \"Result: \\\#{result}\"\n  result\n}\n\ncompute = ->(n) { n ** 2 }\ndecorated = decorate(compute, logging, timing)\nputs decorated.call(5)`, hints: ['reduce wraps each decorator around the previous', 'Each decorator calls fn.call to invoke the inner function', 'Decorators are applied inside-out'], concepts: ['functional_decorator'] },
    { id: 'rb-decorator-13', title: 'Fix Decorator super Bug', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the decorator that forgets to call super.', skeleton: `require 'delegate'\n\nclass Base\n  def value = 10\nend\n\nclass Doubler < SimpleDelegator\n  def value\n    # Bug: returns 20 always, ignoring the wrapped value\n    20\n  end\nend\n\nputs Doubler.new(Base.new).value  # should double the base`, solution: `require 'delegate'\n\nclass Base\n  def value = 10\nend\n\nclass Doubler < SimpleDelegator\n  def value\n    super * 2\n  end\nend\n\nputs Doubler.new(Base.new).value`, hints: ['Decorators should call super to get the wrapped value', 'Then modify the result', 'Without super, the chain is broken'], concepts: ['super_in_decorator'] },
    { id: 'rb-decorator-14', title: 'Fix Decorator Order Bug', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the wrong decorator application order.', skeleton: `require 'delegate'\n\nclass Text\n  def content = \"hello\"\nend\n\nclass Upcase < SimpleDelegator\n  def content = super.upcase\nend\n\nclass Wrap < SimpleDelegator\n  def content = \"[\\\#{super}]\"\nend\n\n# Bug: want [HELLO] but getting [hello] uppercased\nresult = Upcase.new(Wrap.new(Text.new))\nputs result.content  # => [HELLO] but wraps lowercase`, solution: `require 'delegate'\n\nclass Text\n  def content = \"hello\"\nend\n\nclass Upcase < SimpleDelegator\n  def content = super.upcase\nend\n\nclass Wrap < SimpleDelegator\n  def content = \"[\\\#{super}]\"\nend\n\nresult = Wrap.new(Upcase.new(Text.new))\nputs result.content  # => [HELLO]`, hints: ['Inner decorators execute first', 'Upcase should be inner, Wrap should be outer', 'Read as: Wrap around (Upcase around (Text))'], concepts: ['decorator_order'] },
    { id: 'rb-decorator-15', title: 'Fix Prepend Decorator Missing super', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the prepend decorator that replaces instead of decorating.', skeleton: `module Validator\n  def save\n    # Bug: replaces save entirely instead of decorating\n    raise \"Invalid!\" unless valid?\n    # Original save never called\n  end\nend\n\nclass Record\n  prepend Validator\n  def save = puts \"Saved!\"\n  def valid? = true\nend\n\nRecord.new.save  # Only validates, never saves`, solution: `module Validator\n  def save\n    raise \"Invalid!\" unless valid?\n    super\n  end\nend\n\nclass Record\n  prepend Validator\n  def save = puts \"Saved!\"\n  def valid? = true\nend\n\nRecord.new.save`, hints: ['Add super after the validation check', 'super calls the original save method', 'Decorators should enhance, not replace'], concepts: ['prepend_super'] },
    { id: 'rb-decorator-16', title: 'Predict Decorator Chain', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict stacked decorator output.', skeleton: `require 'delegate'\n\nclass V\n  def val = 1\nend\n\nclass A < SimpleDelegator\n  def val = super + 10\nend\n\nclass B < SimpleDelegator\n  def val = super * 3\nend\n\nputs B.new(A.new(V.new)).val\nputs A.new(B.new(V.new)).val`, solution: `33\n13`, hints: ['B(A(V)): V=1, A=1+10=11, B=11*3=33', 'A(B(V)): V=1, B=1*3=3, A=3+10=13', 'Order of nesting matters!'], concepts: ['chain_evaluation'] },
    { id: 'rb-decorator-17', title: 'Predict Prepend Order', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict prepend decoration order.', skeleton: `module A\n  def greet = \"[A:\\\#{super}]\"\nend\n\nmodule B\n  def greet = \"[B:\\\#{super}]\"\nend\n\nclass Base\n  def greet = \"hi\"\nend\n\nclass C < Base\n  prepend A\n  prepend B\nend\n\nputs C.new.greet`, solution: `[B:[A:hi]]`, hints: ['Last prepend goes first in lookup', 'B is prepended last, so it runs first', 'Chain: B -> A -> Base'], concepts: ['prepend_order'] },
    { id: 'rb-decorator-18', title: 'Predict Extend Decorator', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict extend decoration on single object.', skeleton: `module Loud\n  def speak = super.upcase\nend\n\nclass Person\n  def speak = \"hello\"\nend\n\na = Person.new\nb = Person.new\nb.extend(Loud)\n\nputs a.speak\nputs b.speak`, solution: `hello\nHELLO`, hints: ['Only b is extended with Loud', 'a is unaffected', 'extend only modifies the single object'], concepts: ['extend_single_object'] },
    { id: 'rb-decorator-19', title: 'Refactor Subclass to Decorator', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor inheritance-based features to decorators.', skeleton: `class BasicLogger\n  def log(msg) = puts msg\nend\n\nclass TimestampLogger < BasicLogger\n  def log(msg) = super(\"[\\\#{Time.now}] \\\#{msg}\")\nend\n\nclass PrefixLogger < BasicLogger\n  def log(msg) = super(\"[APP] \\\#{msg}\")\nend\n\n# Can't have both timestamp AND prefix without another subclass`, solution: `require 'delegate'\n\nclass BasicLogger\n  def log(msg) = puts msg\nend\n\nclass TimestampDecorator < SimpleDelegator\n  def log(msg) = super(\"[\\\#{Time.now}] \\\#{msg}\")\nend\n\nclass PrefixDecorator < SimpleDelegator\n  def initialize(target, prefix: \"APP\")\n    super(target)\n    @prefix = prefix\n  end\n  def log(msg) = super(\"[\\\#{@prefix}] \\\#{msg}\")\nend\n\nlogger = PrefixDecorator.new(\n  TimestampDecorator.new(BasicLogger.new),\n  prefix: \"APP\"\n)\nlogger.log(\"Started\")`, hints: ['Replace inheritance with SimpleDelegator wrappers', 'Decorators can be freely combined', 'No need for a combined subclass'], concepts: ['inheritance_to_decorator'] },
    { id: 'rb-decorator-20', title: 'Refactor to Dynamic Decoration', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor static decoration to dynamic application.', skeleton: `require 'delegate'\n\n# Static - must write each combination\nclass CachedService < SimpleDelegator\n  def fetch(id)\n    @cache ||= {}\n    @cache[id] ||= super\n  end\nend\n\nclass LoggedService < SimpleDelegator\n  def fetch(id)\n    puts \"Fetching \\\#{id}\"\n    super\n  end\nend\n\n# Want: decorate(service, :cache, :log) dynamically`, solution: `require 'delegate'\n\nclass Decoratable\n  DECORATORS = {\n    cache: lambda { |klass|\n      Module.new do\n        define_method(:fetch) do |id|\n          @cache ||= {}\n          @cache[id] ||= super(id)\n        end\n      end\n    },\n    log: lambda { |klass|\n      Module.new do\n        define_method(:fetch) do |id|\n          puts \"Fetching \\\#{id}\"\n          super(id)\n        end\n      end\n    }\n  }\n\n  def self.decorate(target, *names)\n    names.each do |name|\n      mod = DECORATORS.fetch(name).call(target.class)\n      target.singleton_class.prepend(mod)\n    end\n    target\n  end\nend\n\nclass Service\n  def fetch(id) = \"Data for \\\#{id}\"\nend\n\nservice = Decoratable.decorate(Service.new, :log, :cache)\nputs service.fetch(1)\nputs service.fetch(1)`, hints: ['Store decorator factories in a hash', 'Create anonymous modules with define_method', 'Prepend to singleton_class for per-object decoration'], concepts: ['dynamic_decoration'] },
  ],
};
