import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-command',
  title: '46. Command',
  explanation: `## Command Pattern in Ruby

The Command pattern encapsulates a request as an object, allowing parameterization, queuing, logging, and undo operations.

### Basic Command

\`\`\`ruby
class PrintCommand
  def initialize(message)
    @message = message
  end

  def execute
    puts @message
  end
end

cmd = PrintCommand.new("Hello")
cmd.execute
\`\`\`

### With Undo

\`\`\`ruby
class AddItemCommand
  def initialize(list, item)
    @list = list
    @item = item
  end

  def execute
    @list << @item
  end

  def undo
    @list.delete(@item)
  end
end
\`\`\`

### Command Queue

\`\`\`ruby
class CommandQueue
  def initialize
    @commands = []
  end

  def add(cmd)
    @commands << cmd
  end

  def execute_all
    @commands.each(&:execute)
  end
end
\`\`\``,
  exercises: [
    { id: 'rb-command-1', title: 'Basic Command', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Create a basic command object.', skeleton: `class GreetCommand\n  def initialize(name)\n    @name = name\n  end\n\n  def ___\n    puts \"Hello, \\\#{@name}!\"\n  end\nend\n\ncmd = GreetCommand.new(\"Alice\")\ncmd.execute`, solution: `class GreetCommand\n  def initialize(name)\n    @name = name\n  end\n\n  def execute\n    puts \"Hello, \\\#{@name}!\"\n  end\nend\n\ncmd = GreetCommand.new(\"Alice\")\ncmd.execute`, hints: ['Commands implement an execute method', 'The command encapsulates the action and its data', 'execute triggers the action'], concepts: ['command_execute'] },
    { id: 'rb-command-2', title: 'Command with Undo', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Add undo to a command.', skeleton: `class InsertCommand\n  def initialize(doc, pos, text)\n    @doc, @pos, @text = doc, pos, text\n  end\n\n  def execute\n    @doc.insert(@pos, @text)\n  end\n\n  def ___\n    @doc.slice!(@pos, @text.length)\n  end\nend`, solution: `class InsertCommand\n  def initialize(doc, pos, text)\n    @doc, @pos, @text = doc, pos, text\n  end\n\n  def execute\n    @doc.insert(@pos, @text)\n  end\n\n  def undo\n    @doc.slice!(@pos, @text.length)\n  end\nend`, hints: ['undo reverses the execute action', 'For insert, undo removes the inserted text', 'Store enough state to reverse'], concepts: ['undo'] },
    { id: 'rb-command-3', title: 'Command Queue', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Execute commands from a queue.', skeleton: `class CommandQueue\n  def initialize = @cmds = []\n  def add(cmd) = @cmds << cmd\n  def execute_all = @cmds.each(&:___)\nend`, solution: `class CommandQueue\n  def initialize = @cmds = []\n  def add(cmd) = @cmds << cmd\n  def execute_all = @cmds.each(&:execute)\nend`, hints: ['each(&:execute) calls execute on each command', '& converts the symbol to a proc', 'All queued commands run in order'], concepts: ['command_queue'] },
    { id: 'rb-command-4', title: 'Macro Command', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Create a macro command that runs multiple commands.', skeleton: `class MacroCommand\n  def initialize(*commands)\n    @commands = commands\n  end\n\n  def execute\n    @commands.each(&:execute)\n  end\n\n  def undo\n    @commands.___.each(&:undo)\n  end\nend`, solution: `class MacroCommand\n  def initialize(*commands)\n    @commands = commands\n  end\n\n  def execute\n    @commands.each(&:execute)\n  end\n\n  def undo\n    @commands.reverse.each(&:undo)\n  end\nend`, hints: ['Undo in reverse order of execution', '.reverse gives the opposite order', 'Last executed = first undone'], concepts: ['macro_command'] },
    { id: 'rb-command-5', title: 'Lambda Command', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use a lambda as a command.', skeleton: `commands = [\n  ___ { puts \"Step 1\" },\n  ___ { puts \"Step 2\" },\n  ___ { puts \"Step 3\" },\n]\n\ncommands.each(&:call)`, solution: `commands = [\n  lambda { puts \"Step 1\" },\n  lambda { puts \"Step 2\" },\n  lambda { puts \"Step 3\" },\n]\n\ncommands.each(&:call)`, hints: ['Lambdas are the simplest command objects', 'They respond to call', 'Good for commands that do not need undo'], concepts: ['lambda_command'] },
    { id: 'rb-command-6', title: 'Command History', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Track command history for undo.', skeleton: `class History\n  def initialize = @___ = []\n\n  def execute(cmd)\n    cmd.execute\n    @history << cmd\n  end\n\n  def undo\n    cmd = @history.___\n    cmd&.undo\n  end\nend`, solution: `class History\n  def initialize = @history = []\n\n  def execute(cmd)\n    cmd.execute\n    @history << cmd\n  end\n\n  def undo\n    cmd = @history.pop\n    cmd&.undo\n  end\nend`, hints: ['Store executed commands in an array', 'pop removes and returns the last command', '&. safely handles nil if history is empty'], concepts: ['command_history'] },
    { id: 'rb-command-7', title: 'Write Text Editor Commands', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write undoable text editor commands.', skeleton: `# Write:\n# - TextBuffer class with content string\n# - TypeCommand: appends text\n# - DeleteCommand: deletes last n characters\n# - Both support undo\n# - Editor class with execute and undo using history\n`, solution: `class TextBuffer\n  attr_accessor :content\n  def initialize = @content = \"\"\n  def to_s = @content\nend\n\nclass TypeCommand\n  def initialize(buffer, text)\n    @buffer = buffer\n    @text = text\n  end\n  def execute = @buffer.content += @text\n  def undo = @buffer.content = @buffer.content[0...-@text.length]\nend\n\nclass DeleteCommand\n  def initialize(buffer, count)\n    @buffer = buffer\n    @count = count\n    @deleted = nil\n  end\n  def execute\n    @deleted = @buffer.content[-@count..]\n    @buffer.content = @buffer.content[0...-@count]\n  end\n  def undo\n    @buffer.content += @deleted if @deleted\n  end\nend\n\nclass Editor\n  def initialize\n    @buffer = TextBuffer.new\n    @history = []\n  end\n\n  def type(text)\n    cmd = TypeCommand.new(@buffer, text)\n    cmd.execute\n    @history << cmd\n  end\n\n  def delete(n)\n    cmd = DeleteCommand.new(@buffer, n)\n    cmd.execute\n    @history << cmd\n  end\n\n  def undo = @history.pop&.undo\n  def to_s = @buffer.to_s\nend\n\ned = Editor.new\ned.type(\"Hello\")\ned.type(\" World\")\nputs ed\ned.delete(6)\nputs ed\ned.undo\nputs ed`, hints: ['TypeCommand saves text for undo', 'DeleteCommand saves deleted text for undo', 'History is a stack (last in, first out)'], concepts: ['text_editor_commands'] },
    { id: 'rb-command-8', title: 'Write Calculator Commands', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write calculator with command history and undo.', skeleton: `# Write:\n# - Calculator with value attribute\n# - AddCommand, SubtractCommand, MultiplyCommand\n# - Each supports execute and undo\n# - Calculator.compute chains operations, .undo goes back\n`, solution: `class Calculator\n  attr_accessor :value\n  def initialize(start = 0)\n    @value = start\n    @history = []\n  end\n\n  def execute(cmd)\n    cmd.execute(self)\n    @history << cmd\n    self\n  end\n\n  def undo\n    @history.pop&.undo(self)\n    self\n  end\nend\n\nclass AddCommand\n  def initialize(n) = @n = n\n  def execute(calc) = calc.value += @n\n  def undo(calc) = calc.value -= @n\nend\n\nclass SubtractCommand\n  def initialize(n) = @n = n\n  def execute(calc) = calc.value -= @n\n  def undo(calc) = calc.value += @n\nend\n\nclass MultiplyCommand\n  def initialize(n) = @n = n\n  def execute(calc)\n    @prev = calc.value\n    calc.value *= @n\n  end\n  def undo(calc) = calc.value = @prev\nend\n\nc = Calculator.new(10)\nc.execute(AddCommand.new(5)).execute(MultiplyCommand.new(3))\nputs c.value  # 45\nc.undo\nputs c.value  # 15\nc.undo\nputs c.value  # 10`, hints: ['Commands receive the calculator as argument', 'Multiply saves previous value for undo', 'execute returns self for chaining'], concepts: ['calculator_commands'] },
    { id: 'rb-command-9', title: 'Write Command Serializer', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write commands that can be serialized and replayed.', skeleton: `# Write:\n# - Commands that can be serialized to hashes\n# - CommandLog that records and replays from serialized form\n# - to_h serializes, from_h deserializes\n`, solution: `class MoveCommand\n  attr_reader :direction, :steps\n  def initialize(direction, steps)\n    @direction = direction\n    @steps = steps\n  end\n  def execute(pos)\n    case @direction\n    when :up then pos[:y] += @steps\n    when :down then pos[:y] -= @steps\n    when :left then pos[:x] -= @steps\n    when :right then pos[:x] += @steps\n    end\n  end\n  def to_h = { type: \"move\", direction: @direction, steps: @steps }\n  def self.from_h(h) = new(h[:direction].to_sym, h[:steps])\nend\n\nclass CommandLog\n  def initialize = @log = []\n\n  def record(cmd)\n    @log << cmd.to_h\n  end\n\n  def replay(pos)\n    @log.each do |h|\n      cmd = MoveCommand.from_h(h)\n      cmd.execute(pos)\n    end\n  end\nend\n\npos = { x: 0, y: 0 }\nlog = CommandLog.new\n\ncmd1 = MoveCommand.new(:up, 5)\ncmd1.execute(pos)\nlog.record(cmd1)\n\ncmd2 = MoveCommand.new(:right, 3)\ncmd2.execute(pos)\nlog.record(cmd2)\n\nputs pos.inspect\n\npos2 = { x: 0, y: 0 }\nlog.replay(pos2)\nputs pos2.inspect`, hints: ['to_h converts command to a hash', 'from_h reconstructs from a hash', 'The log stores serialized commands'], concepts: ['command_serialization'] },
    { id: 'rb-command-10', title: 'Write Batch Command', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a batch command with transaction-like behavior.', skeleton: `# Write a BatchCommand:\n# - Takes multiple commands\n# - execute runs all; if any fails, undo all that succeeded\n# - All-or-nothing semantics\n`, solution: `class BatchCommand\n  def initialize(*commands)\n    @commands = commands\n  end\n\n  def execute\n    executed = []\n    begin\n      @commands.each do |cmd|\n        cmd.execute\n        executed << cmd\n      end\n    rescue => e\n      executed.reverse.each(&:undo)\n      raise \"Batch failed: \\\#{e.message}. Rolled back \\\#{executed.size} commands.\"\n    end\n  end\n\n  def undo\n    @commands.reverse.each(&:undo)\n  end\nend\n\nclass SetValue\n  attr_reader :key\n  def initialize(store, key, val)\n    @store, @key, @val = store, key, val\n    @prev = nil\n  end\n  def execute\n    @prev = @store[@key]\n    @store[@key] = @val\n  end\n  def undo\n    @store[@key] = @prev\n  end\nend\n\nstore = {}\nbatch = BatchCommand.new(\n  SetValue.new(store, :a, 1),\n  SetValue.new(store, :b, 2)\n)\nbatch.execute\nputs store.inspect\nbatch.undo\nputs store.inspect`, hints: ['Track which commands executed successfully', 'On failure, undo them in reverse', 'This provides transaction semantics'], concepts: ['batch_command', 'rollback'] },
    { id: 'rb-command-11', title: 'Write Command with Redo', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a command system with both undo and redo.', skeleton: `# Write a CommandManager:\n# - execute(cmd) runs and records\n# - undo pops from history, pushes to redo stack\n# - redo pops from redo stack, re-executes\n# - New execute clears redo stack\n`, solution: `class CommandManager\n  def initialize\n    @history = []\n    @redo_stack = []\n  end\n\n  def execute(cmd)\n    cmd.execute\n    @history << cmd\n    @redo_stack.clear\n  end\n\n  def undo\n    return if @history.empty?\n    cmd = @history.pop\n    cmd.undo\n    @redo_stack << cmd\n  end\n\n  def redo_cmd\n    return if @redo_stack.empty?\n    cmd = @redo_stack.pop\n    cmd.execute\n    @history << cmd\n  end\nend\n\nclass Increment\n  def initialize(counter) = @counter = counter\n  def execute = @counter[:val] += 1\n  def undo = @counter[:val] -= 1\nend\n\ncounter = { val: 0 }\nmgr = CommandManager.new\nmgr.execute(Increment.new(counter))\nmgr.execute(Increment.new(counter))\nputs counter[:val]  # 2\nmgr.undo\nputs counter[:val]  # 1\nmgr.redo_cmd\nputs counter[:val]  # 2`, hints: ['Two stacks: history and redo', 'undo moves from history to redo', 'New execute clears redo (forking point)'], concepts: ['undo_redo'] },
    { id: 'rb-command-12', title: 'Write Delayed Command', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write commands that execute after a delay.', skeleton: `# Write a Scheduler:\n# - schedule(delay_seconds, &block) queues a command\n# - run executes all due commands\n# - pending returns count of pending commands\n`, solution: `class Scheduler\n  def initialize\n    @queue = []\n  end\n\n  def schedule(delay, &block)\n    @queue << { run_at: Time.now + delay, command: block }\n    self\n  end\n\n  def run\n    now = Time.now\n    due = @queue.select { |item| item[:run_at] <= now }\n    due.each { |item| item[:command].call }\n    @queue -= due\n    due.size\n  end\n\n  def pending\n    @queue.size\n  end\nend\n\ns = Scheduler.new\ns.schedule(0) { puts \"Immediate!\" }\ns.schedule(0) { puts \"Also immediate!\" }\ns.schedule(60) { puts \"In a minute\" }\n\nran = s.run\nputs \"Ran \\\#{ran} commands, \\\#{s.pending} pending\"`, hints: ['Store run_at time with each command', 'run checks which commands are due', 'Remove executed commands from the queue'], concepts: ['delayed_command'] },
    { id: 'rb-command-13', title: 'Fix Missing Undo State', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the command that cannot undo properly.', skeleton: `class ReplaceCommand\n  def initialize(str, old_text, new_text)\n    @str = str\n    @old = old_text\n    @new = new_text\n  end\n\n  def execute\n    @str.gsub!(@old, @new)\n  end\n\n  def undo\n    # Bug: gsub! is not perfectly reversible if @new appears elsewhere\n    @str.gsub!(@new, @old)\n  end\nend`, solution: `class ReplaceCommand\n  def initialize(str, old_text, new_text)\n    @str = str\n    @old = old_text\n    @new = new_text\n    @snapshot = nil\n  end\n\n  def execute\n    @snapshot = @str.dup\n    @str.gsub!(@old, @new)\n  end\n\n  def undo\n    @str.replace(@snapshot) if @snapshot\n  end\nend`, hints: ['Save a snapshot before executing', 'Undo restores the snapshot', 'String#replace changes content in-place'], concepts: ['snapshot_undo'] },
    { id: 'rb-command-14', title: 'Fix Double Execute', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the command that can be executed multiple times.', skeleton: `class AddToList\n  def initialize(list, item)\n    @list = list\n    @item = item\n  end\n\n  def execute\n    # Bug: calling execute twice adds the item twice\n    @list << @item\n  end\n\n  def undo\n    @list.delete(@item)\n  end\nend`, solution: `class AddToList\n  def initialize(list, item)\n    @list = list\n    @item = item\n    @executed = false\n  end\n\n  def execute\n    return if @executed\n    @list << @item\n    @executed = true\n  end\n\n  def undo\n    return unless @executed\n    @list.delete(@item)\n    @executed = false\n  end\nend`, hints: ['Track whether the command has been executed', 'Guard against double execution', 'undo should only work if previously executed'], concepts: ['idempotent_command'] },
    { id: 'rb-command-15', title: 'Fix Undo Order', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the undo order in a command history.', skeleton: `class History\n  def initialize = @cmds = []\n  def execute(cmd)\n    cmd.execute\n    @cmds << cmd\n  end\n  def undo_all\n    # Bug: undoing in execution order instead of reverse\n    @cmds.each(&:undo)\n  end\nend`, solution: `class History\n  def initialize = @cmds = []\n  def execute(cmd)\n    cmd.execute\n    @cmds << cmd\n  end\n  def undo_all\n    @cmds.reverse_each(&:undo)\n  end\nend`, hints: ['Undo must happen in reverse order', 'reverse_each iterates backwards', 'Last executed = first undone'], concepts: ['undo_order'] },
    { id: 'rb-command-16', title: 'Predict Command Output', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict command execution sequence.', skeleton: `cmds = []\ncmds << lambda { print \"A\" }\ncmds << lambda { print \"B\" }\ncmds << lambda { print \"C\" }\ncmds.each(&:call)\nputs`, solution: `ABC`, hints: ['Commands execute in array order', 'print does not add newline', 'puts adds the final newline'], concepts: ['command_sequence'] },
    { id: 'rb-command-17', title: 'Predict Undo Result', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict the state after execute and undo.', skeleton: `arr = []\n\nclass Push\n  def initialize(arr, v) = (@arr, @v = arr, v)\n  def execute = @arr << @v\n  def undo = @arr.pop\nend\n\ncmds = [Push.new(arr, 1), Push.new(arr, 2), Push.new(arr, 3)]\ncmds.each(&:execute)\nputs arr.inspect\ncmds.last.undo\ncmds[-2].undo\nputs arr.inspect`, solution: `[1, 2, 3]\n[1]`, hints: ['After all executes: [1, 2, 3]', 'Undo last (3 removed): [1, 2]', 'Undo second-to-last (2 removed): [1]'], concepts: ['undo_state'] },
    { id: 'rb-command-18', title: 'Predict Macro Command', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict macro command behavior.', skeleton: `class Cmd\n  def initialize(n) = @n = n\n  def execute = puts \"exec \\\#{@n}\"\n  def undo = puts \"undo \\\#{@n}\"\nend\n\nclass Macro\n  def initialize(*cs) = @cs = cs\n  def execute = @cs.each(&:execute)\n  def undo = @cs.reverse_each(&:undo)\nend\n\nm = Macro.new(Cmd.new(1), Cmd.new(2), Cmd.new(3))\nm.execute\nm.undo`, solution: `exec 1\nexec 2\nexec 3\nundo 3\nundo 2\nundo 1`, hints: ['Execute runs forward: 1, 2, 3', 'Undo runs backward: 3, 2, 1', 'Macro coordinates the sequence'], concepts: ['macro_order'] },
    { id: 'rb-command-19', title: 'Refactor Callback to Command', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor inline callbacks to command objects.', skeleton: `class Button\n  def initialize(&on_click)\n    @on_click = on_click\n  end\n  def click = @on_click.call\nend\n\n# Can't undo, can't serialize, can't queue\nsave_btn = Button.new { puts \"Saving...\" }\nsave_btn.click`, solution: `class SaveCommand\n  def execute = puts \"Saving...\"\n  def undo = puts \"Reverting save...\"\n  def to_s = \"SaveCommand\"\nend\n\nclass Button\n  def initialize(command)\n    @command = command\n    @history = []\n  end\n\n  def click\n    @command.execute\n    @history << @command\n  end\n\n  def undo\n    @history.pop&.undo\n  end\nend\n\nsave_btn = Button.new(SaveCommand.new)\nsave_btn.click\nsave_btn.undo`, hints: ['Commands are objects, not just blocks', 'Objects can have undo, to_s, and other methods', 'Button stores command history for undo'], concepts: ['callback_to_command'] },
    { id: 'rb-command-20', title: 'Refactor Switch/Case to Commands', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor a switch/case handler to command pattern.', skeleton: `def handle_action(action, data)\n  case action\n  when \"create\"\n    puts \"Creating \\\#{data[:name]}\"\n  when \"update\"\n    puts \"Updating \\\#{data[:id]}\"\n  when \"delete\"\n    puts \"Deleting \\\#{data[:id]}\"\n  else\n    raise \"Unknown action\"\n  end\nend\n\nhandle_action(\"create\", { name: \"Widget\" })`, solution: `class CreateCommand\n  def initialize(data) = @data = data\n  def execute = puts \"Creating \\\#{@data[:name]}\"\nend\n\nclass UpdateCommand\n  def initialize(data) = @data = data\n  def execute = puts \"Updating \\\#{@data[:id]}\"\nend\n\nclass DeleteCommand\n  def initialize(data) = @data = data\n  def execute = puts \"Deleting \\\#{@data[:id]}\"\nend\n\nCOMMANDS = {\n  \"create\" => CreateCommand,\n  \"update\" => UpdateCommand,\n  \"delete\" => DeleteCommand,\n}\n\ndef handle_action(action, data)\n  klass = COMMANDS.fetch(action) { raise \"Unknown action: \\\#{action}\" }\n  klass.new(data).execute\nend\n\nhandle_action(\"create\", { name: \"Widget\" })`, hints: ['Each case branch becomes a command class', 'A registry maps action names to classes', 'New actions are added without modifying handle_action'], concepts: ['switch_to_command'] },
  ],
};
