import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-web',
  title: '47. Ruby Web Basics',
  explanation: `## Ruby Web Basics

Ruby has a rich ecosystem for web development, from low-level Rack interfaces to high-level frameworks like Sinatra.

### Rack Interface

Rack is the foundation of Ruby web frameworks. A Rack app is any object that responds to \`call\` with an env hash and returns a three-element array:

\`\`\`ruby
# A minimal Rack application
app = lambda do |env|
  [200, { "content-type" => "text/plain" }, ["Hello, World!"]]
end
\`\`\`

### WEBrick HTTP Server

\`\`\`ruby
require 'webrick'

server = WEBrick::HTTPServer.new(Port: 8080)
server.mount_proc '/' do |req, res|
  res.body = "Hello from WEBrick!"
end
server.start
\`\`\`

### Sinatra Basics

\`\`\`ruby
require 'sinatra'

get '/' do
  "Hello, Sinatra!"
end

get '/greet/:name' do
  "Hello, \\\#{params[:name]}!"
end
\`\`\`

### Middleware

\`\`\`ruby
class Logger
  def initialize(app)
    @app = app
  end

  def call(env)
    puts "Request: \\\#{env['REQUEST_METHOD']} \\\#{env['PATH_INFO']}"
    @app.call(env)
  end
end
\`\`\`

### ERB Templates

\`\`\`ruby
require 'erb'

template = ERB.new("Hello, <%= name %>!")
name = "Ruby"
puts template.result(binding)  # "Hello, Ruby!"
\`\`\``,
  exercises: [
    { id: 'rb-web-1', title: 'Minimal Rack App', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Complete a minimal Rack application that returns a 200 response.', skeleton: `app = lambda do |env|\n  [___, { \"content-type\" => \"text/plain\" }, [\"Hello!\"]]\nend\n\nstatus, headers, body = app.call({})\nputs status\nputs body.first`, solution: `app = lambda do |env|\n  [200, { \"content-type\" => \"text/plain\" }, [\"Hello!\"]]\nend\n\nstatus, headers, body = app.call({})\nputs status\nputs body.first`, hints: ['Rack responses are [status, headers, body]', 'HTTP 200 means OK', 'The body must be an array of strings'], concepts: ['rack_basics', 'http_status'] },
    { id: 'rb-web-2', title: 'Rack Env Variables', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Read CGI variables from the Rack environment hash.', skeleton: `app = lambda do |env|\n  method = env['___']\n  path = env['PATH_INFO']\n  body = \"Method: \\\#{method}, Path: \\\#{path}\"\n  [200, { \"content-type\" => \"text/plain\" }, [body]]\nend\n\nenv = { 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/users' }\nstatus, _, body = app.call(env)\nputs body.first`, solution: `app = lambda do |env|\n  method = env['REQUEST_METHOD']\n  path = env['PATH_INFO']\n  body = \"Method: \\\#{method}, Path: \\\#{path}\"\n  [200, { \"content-type\" => \"text/plain\" }, [body]]\nend\n\nenv = { 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/users' }\nstatus, _, body = app.call(env)\nputs body.first`, hints: ['CGI variables are uppercase strings in the env hash', 'REQUEST_METHOD holds GET, POST, etc.', 'PATH_INFO holds the URL path'], concepts: ['cgi_variables', 'rack_env'] },
    { id: 'rb-web-3', title: 'Rack Response Headers', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Set the correct content-type header for JSON.', skeleton: `app = lambda do |env|\n  data = '{ \"status\": \"ok\" }'\n  [200, { \"___\" => \"application/json\" }, [data]]\nend\n\nstatus, headers, body = app.call({})\nputs headers.keys.first`, solution: `app = lambda do |env|\n  data = '{ \"status\": \"ok\" }'\n  [200, { \"content-type\" => \"application/json\" }, [data]]\nend\n\nstatus, headers, body = app.call({})\nputs headers.keys.first`, hints: ['The content-type header tells clients the response format', 'JSON responses use application/json', 'Headers are a hash of string key-value pairs'], concepts: ['http_headers', 'content_type'] },
    { id: 'rb-web-4', title: 'Basic Middleware', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Complete a Rack middleware that adds a custom header.', skeleton: `class AddHeader\n  def initialize(app)\n    @app = app\n  end\n\n  def call(env)\n    status, headers, body = @app.___(env)\n    headers['X-Custom'] = 'ForgeIDE'\n    [status, headers, body]\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"OK\"]] }\napp = AddHeader.new(inner)\nstatus, headers, body = app.call({})\nputs headers['X-Custom']`, solution: `class AddHeader\n  def initialize(app)\n    @app = app\n  end\n\n  def call(env)\n    status, headers, body = @app.call(env)\n    headers['X-Custom'] = 'ForgeIDE'\n    [status, headers, body]\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"OK\"]] }\napp = AddHeader.new(inner)\nstatus, headers, body = app.call({})\nputs headers['X-Custom']`, hints: ['Middleware wraps an inner app', 'It calls the inner app and can modify the response', 'call(env) delegates to the wrapped app'], concepts: ['middleware', 'rack_middleware'] },
    { id: 'rb-web-5', title: 'Query String Parsing', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Parse query string parameters from the Rack env.', skeleton: `require 'uri'\n\ndef parse_query(query_string)\n  URI.decode_www_form(query_string).to_h\nend\n\napp = lambda do |env|\n  params = parse_query(env['___'] || '')\n  [200, {}, [\"Name: \\\#{params['name']}\"]]\nend\n\nenv = { 'QUERY_STRING' => 'name=Ruby&version=3' }\n_, _, body = app.call(env)\nputs body.first`, solution: `require 'uri'\n\ndef parse_query(query_string)\n  URI.decode_www_form(query_string).to_h\nend\n\napp = lambda do |env|\n  params = parse_query(env['QUERY_STRING'] || '')\n  [200, {}, [\"Name: \\\#{params['name']}\"]]\nend\n\nenv = { 'QUERY_STRING' => 'name=Ruby&version=3' }\n_, _, body = app.call(env)\nputs body.first`, hints: ['QUERY_STRING contains the URL query parameters', 'URI.decode_www_form parses key=value pairs', 'to_h converts the array of pairs to a hash'], concepts: ['query_string', 'params_parsing'] },
    { id: 'rb-web-6', title: 'ERB Template Rendering', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Render an ERB template with variables.', skeleton: `require 'erb'\n\ndef render(template_str, vars)\n  b = binding\n  vars.each { |k, v| b.local_variable_set(k, v) }\n  ERB.___(template_str).result(b)\nend\n\nhtml = render(\"<h1><%= title %></h1><p><%= body %></p>\",\n  { title: \"Welcome\", body: \"Hello from ERB\" })\nputs html`, solution: `require 'erb'\n\ndef render(template_str, vars)\n  b = binding\n  vars.each { |k, v| b.local_variable_set(k, v) }\n  ERB.new(template_str).result(b)\nend\n\nhtml = render(\"<h1><%= title %></h1><p><%= body %></p>\",\n  { title: \"Welcome\", body: \"Hello from ERB\" })\nputs html`, hints: ['ERB.new creates a new template', '.result(binding) evaluates the template', 'local_variable_set injects variables into the binding'], concepts: ['erb_templates', 'template_rendering'] },
    { id: 'rb-web-7', title: 'Write a Router', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a simple Rack router that dispatches to handlers based on PATH_INFO.', skeleton: `# Write a Router class:\n# - add(method, path, &handler) registers a route\n# - call(env) finds matching route and calls handler\n# - Returns 404 if no route matches\n# - Handler receives env and returns [status, headers, body]\n`, solution: `class Router\n  def initialize\n    @routes = []\n  end\n\n  def add(method, path, &handler)\n    @routes << { method: method.upcase, path: path, handler: handler }\n  end\n\n  def call(env)\n    req_method = env['REQUEST_METHOD']\n    req_path = env['PATH_INFO']\n\n    route = @routes.find do |r|\n      r[:method] == req_method && r[:path] == req_path\n    end\n\n    if route\n      route[:handler].call(env)\n    else\n      [404, { \"content-type\" => \"text/plain\" }, [\"Not Found\"]]\n    end\n  end\nend\n\nrouter = Router.new\nrouter.add('GET', '/') { |env| [200, {}, [\"Home\"]] }\nrouter.add('GET', '/about') { |env| [200, {}, [\"About\"]] }\n\nstatus, _, body = router.call({ 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/' })\nputs \"\\\#{status}: \\\#{body.first}\"\n\nstatus, _, body = router.call({ 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/missing' })\nputs \"\\\#{status}: \\\#{body.first}\"`, hints: ['Store routes as an array of hashes with method, path, and handler', 'Use find to locate a matching route', 'Return 404 when no route matches'], concepts: ['routing', 'rack_app'] },
    { id: 'rb-web-8', title: 'Write Request Object', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a Request class that wraps the Rack env hash for easy access.', skeleton: `# Write a Request class:\n# - initialize(env) stores the env hash\n# - method returns REQUEST_METHOD\n# - path returns PATH_INFO\n# - query_params parses QUERY_STRING into a hash\n# - header(name) returns HTTP_* headers (e.g., header('Accept'))\n`, solution: `require 'uri'\n\nclass Request\n  def initialize(env)\n    @env = env\n  end\n\n  def method\n    @env['REQUEST_METHOD']\n  end\n\n  def path\n    @env['PATH_INFO']\n  end\n\n  def query_params\n    qs = @env['QUERY_STRING'] || ''\n    return {} if qs.empty?\n    URI.decode_www_form(qs).to_h\n  end\n\n  def header(name)\n    key = \"HTTP_\\\#{name.upcase.tr('-', '_')}\"\n    @env[key]\n  end\nend\n\nenv = {\n  'REQUEST_METHOD' => 'GET',\n  'PATH_INFO' => '/users',\n  'QUERY_STRING' => 'page=1&per=10',\n  'HTTP_ACCEPT' => 'application/json',\n  'HTTP_X_REQUEST_ID' => 'abc123'\n}\n\nreq = Request.new(env)\nputs req.method\nputs req.path\nputs req.query_params.inspect\nputs req.header('Accept')\nputs req.header('X-Request-Id')`, hints: ['Rack stores HTTP headers as HTTP_* env variables', 'Convert header name: upcase and replace - with _', 'URI.decode_www_form parses query strings'], concepts: ['request_object', 'cgi_variables'] },
    { id: 'rb-web-9', title: 'Write Response Builder', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a Response class that builds Rack-compatible responses.', skeleton: `# Write a Response class:\n# - status, headers, body accessors\n# - set_header(key, value)\n# - write(text) appends to body\n# - to_rack returns [status, headers, body_array]\n# - Provide convenience class methods: ok(body), not_found, redirect(url)\n`, solution: `class Response\n  attr_accessor :status, :headers, :body\n\n  def initialize(status = 200)\n    @status = status\n    @headers = { \"content-type\" => \"text/html\" }\n    @body = []\n  end\n\n  def set_header(key, value)\n    @headers[key] = value\n  end\n\n  def write(text)\n    @body << text\n  end\n\n  def to_rack\n    [@status, @headers, @body]\n  end\n\n  def self.ok(body)\n    r = new(200)\n    r.write(body)\n    r\n  end\n\n  def self.not_found\n    r = new(404)\n    r.write(\"Not Found\")\n    r\n  end\n\n  def self.redirect(url)\n    r = new(302)\n    r.set_header(\"location\", url)\n    r\n  end\nend\n\nok = Response.ok(\"Hello!\")\nputs ok.to_rack.inspect\n\nnf = Response.not_found\nputs nf.to_rack.inspect\n\nrd = Response.redirect(\"/login\")\nputs rd.to_rack.inspect`, hints: ['to_rack returns the standard [status, headers, body] array', 'Body is an array of strings in Rack', 'Class methods are factory methods for common responses'], concepts: ['response_object', 'rack_response'] },
    { id: 'rb-web-10', title: 'Write Middleware Stack', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a middleware stack builder that chains middleware around an app.', skeleton: `# Write a MiddlewareStack class:\n# - use(middleware_class) adds middleware\n# - run(app) sets the inner app\n# - build returns the composed app (outermost middleware wraps innermost)\n# - call(env) delegates to the built app\n`, solution: `class MiddlewareStack\n  def initialize\n    @middlewares = []\n    @app = nil\n  end\n\n  def use(middleware_class)\n    @middlewares << middleware_class\n    self\n  end\n\n  def run(app)\n    @app = app\n    self\n  end\n\n  def build\n    @middlewares.reverse.reduce(@app) do |app, mw|\n      mw.new(app)\n    end\n  end\n\n  def call(env)\n    @built ||= build\n    @built.call(env)\n  end\nend\n\nclass Timer\n  def initialize(app) = @app = app\n  def call(env)\n    start = Time.now\n    status, headers, body = @app.call(env)\n    elapsed = Time.now - start\n    headers['X-Runtime'] = elapsed.to_s\n    [status, headers, body]\n  end\nend\n\nclass Upcaser\n  def initialize(app) = @app = app\n  def call(env)\n    status, headers, body = @app.call(env)\n    [status, headers, body.map(&:upcase)]\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"hello world\"]] }\n\nstack = MiddlewareStack.new\nstack.use(Timer)\nstack.use(Upcaser)\nstack.run(inner)\n\nstatus, headers, body = stack.call({})\nputs body.first\nputs headers.key?('X-Runtime')`, hints: ['Middleware wraps from inside out', 'Use reverse.reduce to build the chain', 'The last use() is the outermost wrapper'], concepts: ['middleware_stack', 'rack_builder'] },
    { id: 'rb-web-11', title: 'Write Sinatra-Style DSL', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a tiny Sinatra-like DSL for defining routes.', skeleton: `# Write a MicroApp class:\n# - Class methods: get(path, &block), post(path, &block)\n# - Instance method call(env) dispatches to the right handler\n# - The block receives a params hash\n# - Supports path parameters like /users/:id\n`, solution: `class MicroApp\n  @@routes = []\n\n  def self.get(path, &block)\n    @@routes << { method: 'GET', pattern: path, handler: block }\n  end\n\n  def self.post(path, &block)\n    @@routes << { method: 'POST', pattern: path, handler: block }\n  end\n\n  def self.match_path(pattern, path)\n    parts_p = pattern.split('/')\n    parts_a = path.split('/')\n    return nil unless parts_p.size == parts_a.size\n\n    params = {}\n    parts_p.zip(parts_a).each do |pp, pa|\n      if pp.start_with?(':')\n        params[pp[1..].to_sym] = pa\n      elsif pp != pa\n        return nil\n      end\n    end\n    params\n  end\n\n  def call(env)\n    req_method = env['REQUEST_METHOD']\n    req_path = env['PATH_INFO']\n\n    @@routes.each do |route|\n      next unless route[:method] == req_method\n      params = self.class.match_path(route[:pattern], req_path)\n      next unless params\n      body = route[:handler].call(params)\n      return [200, { \"content-type\" => \"text/plain\" }, [body.to_s]]\n    end\n\n    [404, { \"content-type\" => \"text/plain\" }, [\"Not Found\"]]\n  end\nend\n\nMicroApp.get('/') { |p| \"Home\" }\nMicroApp.get('/users/:id') { |p| \"User \\\#{p[:id]}\" }\nMicroApp.post('/users') { |p| \"Created\" }\n\napp = MicroApp.new\nputs app.call({ 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/' })[2].first\nputs app.call({ 'REQUEST_METHOD' => 'GET', 'PATH_INFO' => '/users/42' })[2].first\nputs app.call({ 'REQUEST_METHOD' => 'DELETE', 'PATH_INFO' => '/' })[2].first`, hints: ['Path parameters start with : in the pattern', 'Split both pattern and actual path to compare segments', 'Store matched parameters in a hash'], concepts: ['dsl_routing', 'sinatra_style'] },
    { id: 'rb-web-12', title: 'Write Cookie Handler', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write middleware that parses and sets cookies.', skeleton: `# Write a CookieJar class:\n# - parse(cookie_string) extracts cookies from HTTP_COOKIE\n# - get(name) returns a cookie value\n# - set(name, value, opts = {}) adds a Set-Cookie header\n# - apply(headers) adds Set-Cookie headers to response\n`, solution: `class CookieJar\n  def initialize\n    @cookies = {}\n    @set_cookies = []\n  end\n\n  def parse(cookie_string)\n    return unless cookie_string\n    cookie_string.split('; ').each do |pair|\n      key, value = pair.split('=', 2)\n      @cookies[key.strip] = value&.strip\n    end\n  end\n\n  def get(name)\n    @cookies[name]\n  end\n\n  def set(name, value, opts = {})\n    cookie = \"\\\#{name}=\\\#{value}\"\n    cookie += \"; Path=\\\#{opts[:path]}\" if opts[:path]\n    cookie += \"; Max-Age=\\\#{opts[:max_age]}\" if opts[:max_age]\n    cookie += \"; HttpOnly\" if opts[:http_only]\n    @set_cookies << cookie\n  end\n\n  def apply(headers)\n    @set_cookies.each_with_index do |c, i|\n      key = i == 0 ? 'set-cookie' : \"set-cookie-\\\#{i}\"\n      headers[key] = c\n    end\n    headers\n  end\nend\n\njar = CookieJar.new\njar.parse(\"session=abc123; theme=dark\")\nputs jar.get(\"session\")\nputs jar.get(\"theme\")\n\njar.set(\"token\", \"xyz789\", path: \"/\", http_only: true)\nheaders = {}\njar.apply(headers)\nputs headers.inspect`, hints: ['Cookies are sent as semicolon-separated key=value pairs', 'Set-Cookie headers include directives like Path, Max-Age, HttpOnly', 'parse splits the cookie string into individual pairs'], concepts: ['cookies', 'http_cookies'] },
    { id: 'rb-web-13', title: 'Fix Rack Response Body', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the Rack app that returns a string instead of an array for the body.', skeleton: `app = lambda do |env|\n  # Bug: body must be an array of strings, not a string\n  [200, { \"content-type\" => \"text/plain\" }, \"Hello World\"]\nend\n\nstatus, headers, body = app.call({})\nbody.each { |chunk| puts chunk }`, solution: `app = lambda do |env|\n  [200, { \"content-type\" => \"text/plain\" }, [\"Hello World\"]]\nend\n\nstatus, headers, body = app.call({})\nbody.each { |chunk| puts chunk }`, hints: ['Rack requires the body to be an iterable of strings', 'Wrap the string in an array', 'body.each must work - strings do not have each by default'], concepts: ['rack_body', 'rack_spec'] },
    { id: 'rb-web-14', title: 'Fix Middleware Chain', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the middleware that forgets to call the inner app.', skeleton: `class Auth\n  def initialize(app)\n    @app = app\n  end\n\n  def call(env)\n    # Bug: returns early without calling inner app when authorized\n    if env['HTTP_AUTHORIZATION'] == 'Bearer secret'\n      [200, {}, [\"Authorized\"]]\n    else\n      [401, {}, [\"Unauthorized\"]]\n    end\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"Protected Content\"]] }\napp = Auth.new(inner)\n\nstatus, _, body = app.call({ 'HTTP_AUTHORIZATION' => 'Bearer secret' })\nputs \"\\\#{status}: \\\#{body.first}\"`, solution: `class Auth\n  def initialize(app)\n    @app = app\n  end\n\n  def call(env)\n    if env['HTTP_AUTHORIZATION'] == 'Bearer secret'\n      @app.call(env)\n    else\n      [401, {}, [\"Unauthorized\"]]\n    end\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"Protected Content\"]] }\napp = Auth.new(inner)\n\nstatus, _, body = app.call({ 'HTTP_AUTHORIZATION' => 'Bearer secret' })\nputs \"\\\#{status}: \\\#{body.first}\"`, hints: ['Middleware should delegate to the inner app when authorized', 'Only short-circuit on failure (401)', 'Call @app.call(env) to pass through to the inner app'], concepts: ['middleware_delegation', 'auth_middleware'] },
    { id: 'rb-web-15', title: 'Fix ERB HTML Escaping', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the XSS vulnerability in the ERB template.', skeleton: `require 'erb'\n\n# Bug: user input is not HTML-escaped, allowing XSS\nuser_input = \"<script>alert('xss')</script>\"\n\ntemplate = ERB.new(\"<p>Hello, <%= user_input %></p>\")\nputs template.result(binding)`, solution: `require 'erb'\nrequire 'cgi'\n\nuser_input = \"<script>alert('xss')</script>\"\n\ntemplate = ERB.new(\"<p>Hello, <%= CGI.escapeHTML(user_input) %></p>\")\nputs template.result(binding)`, hints: ['User input must be HTML-escaped to prevent XSS', 'CGI.escapeHTML converts < > & to HTML entities', 'Never render user input directly in HTML templates'], concepts: ['xss_prevention', 'html_escaping'] },
    { id: 'rb-web-16', title: 'Predict Rack Response', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict the output of a Rack app call.', skeleton: `app = lambda do |env|\n  path = env['PATH_INFO']\n  case path\n  when '/' then [200, {}, [\"Home\"]]\n  when '/about' then [200, {}, [\"About\"]]\n  else [404, {}, [\"Not Found\"]]\n  end\nend\n\nputs app.call({ 'PATH_INFO' => '/about' })[0]\nputs app.call({ 'PATH_INFO' => '/contact' })[2].first`, solution: `200\nNot Found`, hints: ['/about matches the second when clause', '/contact matches no route so hits else', 'Index [0] is status, [2] is body array'], concepts: ['rack_routing', 'case_statement'] },
    { id: 'rb-web-17', title: 'Predict Middleware Order', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict the order of middleware execution.', skeleton: `class MW\n  def initialize(app, name)\n    @app = app\n    @name = name\n  end\n  def call(env)\n    env[:log] << \"before-\\\#{@name}\"\n    status, headers, body = @app.call(env)\n    env[:log] << \"after-\\\#{@name}\"\n    [status, headers, body]\n  end\nend\n\ninner = lambda { |env| env[:log] << \"app\"; [200, {}, []] }\napp = MW.new(MW.new(inner, \"B\"), \"A\")\n\nenv = { log: [] }\napp.call(env)\nputs env[:log].join(\", \")`, solution: `before-A, before-B, app, after-B, after-A`, hints: ['A is the outermost middleware, B is inner', 'before hooks run outside-in: A then B', 'after hooks run inside-out: B then A'], concepts: ['middleware_order', 'request_lifecycle'] },
    { id: 'rb-web-18', title: 'Predict Query Parse', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict parsed query string output.', skeleton: `require 'uri'\n\nqs = \"color=red&size=large&color=blue\"\npairs = URI.decode_www_form(qs)\nputs pairs.length\nputs pairs.last.inspect`, solution: `3\n[\"color\", \"blue\"]`, hints: ['decode_www_form returns an array of [key, value] pairs', 'Duplicate keys produce separate pairs', 'The last pair is ["color", "blue"]'], concepts: ['query_parsing', 'uri_decode'] },
    { id: 'rb-web-19', title: 'Refactor Proc Routes to Classes', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor inline proc handlers into controller-style classes.', skeleton: `routes = {\n  '/' => lambda { |env| [200, {}, [\"Welcome\"]] },\n  '/users' => lambda { |env| [200, {}, [\"User list\"]] },\n  '/users/new' => lambda { |env| [200, {}, [\"New user form\"]] },\n}\n\ndef dispatch(routes, env)\n  handler = routes[env['PATH_INFO']]\n  handler ? handler.call(env) : [404, {}, [\"Not Found\"]]\nend\n\nputs dispatch(routes, { 'PATH_INFO' => '/' })[2].first`, solution: `class HomeController\n  def call(env)\n    [200, {}, [\"Welcome\"]]\n  end\nend\n\nclass UsersController\n  def index(env)\n    [200, {}, [\"User list\"]]\n  end\n\n  def new_form(env)\n    [200, {}, [\"New user form\"]]\n  end\nend\n\nroutes = {\n  '/' => HomeController.new.method(:call),\n  '/users' => UsersController.new.method(:index),\n  '/users/new' => UsersController.new.method(:new_form),\n}\n\ndef dispatch(routes, env)\n  handler = routes[env['PATH_INFO']]\n  handler ? handler.call(env) : [404, {}, [\"Not Found\"]]\nend\n\nputs dispatch(routes, { 'PATH_INFO' => '/' })[2].first`, hints: ['Group related routes into controller classes', 'Each action is a method that returns a Rack response', '.method(:name) converts a method into a callable object'], concepts: ['controllers', 'refactor_to_classes'] },
    { id: 'rb-web-20', title: 'Refactor to Rack::Builder Style', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor manual middleware wiring into a builder pattern.', skeleton: `class Logger\n  def initialize(app) = @app = app\n  def call(env)\n    puts \"LOG: \\\#{env['PATH_INFO']}\"\n    @app.call(env)\n  end\nend\n\nclass Timer\n  def initialize(app) = @app = app\n  def call(env)\n    t = Time.now\n    r = @app.call(env)\n    puts \"Time: \\\#{Time.now - t}s\"\n    r\n  end\nend\n\ninner = lambda { |env| [200, {}, [\"OK\"]] }\napp = Logger.new(Timer.new(inner))\napp.call({ 'PATH_INFO' => '/' })`, solution: `class Logger\n  def initialize(app) = @app = app\n  def call(env)\n    puts \"LOG: \\\#{env['PATH_INFO']}\"\n    @app.call(env)\n  end\nend\n\nclass Timer\n  def initialize(app) = @app = app\n  def call(env)\n    t = Time.now\n    r = @app.call(env)\n    puts \"Time: \\\#{Time.now - t}s\"\n    r\n  end\nend\n\nclass Builder\n  def initialize(&block)\n    @middlewares = []\n    @app = nil\n    instance_eval(&block)\n  end\n\n  def use(mw) = @middlewares << mw\n  def run(app) = @app = app\n\n  def to_app\n    @middlewares.reverse.reduce(@app) { |app, mw| mw.new(app) }\n  end\nend\n\napp = Builder.new do\n  use Logger\n  use Timer\n  run lambda { |env| [200, {}, [\"OK\"]] }\nend.to_app\n\napp.call({ 'PATH_INFO' => '/' })`, hints: ['Builder uses instance_eval to evaluate the block in its own context', 'use adds middleware, run sets the inner app', 'to_app chains middleware with reverse.reduce'], concepts: ['builder_pattern', 'rack_builder'] },
  ],
};
