import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-json-api',
  title: '48. JSON & API Development',
  explanation: `## JSON & API Development in Ruby

Ruby has built-in JSON support and powerful HTTP libraries for building and consuming APIs.

### JSON Parsing & Generation

\`\`\`ruby
require 'json'

# Parse JSON string to Ruby hash
data = JSON.parse('{"name": "Ruby", "version": 3}')
puts data["name"]  # "Ruby"

# Generate JSON from Ruby object
json_str = JSON.generate({ name: "Ruby", version: 3 })
puts json_str  # {"name":"Ruby","version":3}

# Pretty print
puts JSON.pretty_generate({ users: [{ id: 1 }] })
\`\`\`

### Net::HTTP Client

\`\`\`ruby
require 'net/http'
require 'uri'
require 'json'

uri = URI("https://api.example.com/users")
response = Net::HTTP.get_response(uri)
data = JSON.parse(response.body)
\`\`\`

### REST API Patterns

\`\`\`ruby
# Standard REST response format
def json_response(status, data)
  [status,
   { "content-type" => "application/json" },
   [JSON.generate(data)]]
end

json_response(200, { users: [] })
json_response(404, { error: "Not found" })
\`\`\`

### API Authentication

\`\`\`ruby
def authenticate(env)
  token = env['HTTP_AUTHORIZATION']&.sub('Bearer ', '')
  return nil unless token
  # Verify token and return user
  decode_token(token)
end
\`\`\``,
  exercises: [
    { id: 'rb-json-api-1', title: 'Parse JSON', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Parse a JSON string into a Ruby hash.', skeleton: `require 'json'\n\njson_str = '{\"name\": \"Alice\", \"age\": 30}'\ndata = JSON.___(json_str)\nputs data[\"name\"]\nputs data[\"age\"]`, solution: `require 'json'\n\njson_str = '{\"name\": \"Alice\", \"age\": 30}'\ndata = JSON.parse(json_str)\nputs data[\"name\"]\nputs data[\"age\"]`, hints: ['JSON.parse converts a JSON string to Ruby objects', 'Keys become strings by default', 'The result is a regular Ruby hash'], concepts: ['json_parse'] },
    { id: 'rb-json-api-2', title: 'Generate JSON', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Convert a Ruby hash to a JSON string.', skeleton: `require 'json'\n\ndata = { name: \"Bob\", scores: [95, 87, 92] }\njson_str = JSON.___(data)\nputs json_str`, solution: `require 'json'\n\ndata = { name: \"Bob\", scores: [95, 87, 92] }\njson_str = JSON.generate(data)\nputs json_str`, hints: ['JSON.generate converts Ruby objects to JSON strings', 'Symbols become string keys in JSON', 'Arrays are preserved as JSON arrays'], concepts: ['json_generate'] },
    { id: 'rb-json-api-3', title: 'Symbolize Keys', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Parse JSON with symbol keys instead of string keys.', skeleton: `require 'json'\n\njson_str = '{\"name\": \"Carol\", \"role\": \"admin\"}'\ndata = JSON.parse(json_str, ___: true)\nputs data[:name]\nputs data[:role]`, solution: `require 'json'\n\njson_str = '{\"name\": \"Carol\", \"role\": \"admin\"}'\ndata = JSON.parse(json_str, symbolize_names: true)\nputs data[:name]\nputs data[:role]`, hints: ['symbolize_names: true converts string keys to symbols', 'Access with :name instead of "name"', 'This is a common Ruby convention for internal data'], concepts: ['symbolize_names', 'json_options'] },
    { id: 'rb-json-api-4', title: 'JSON Response Helper', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Complete a helper that returns Rack-compatible JSON responses.', skeleton: `require 'json'\n\ndef json_response(status, data)\n  [status,\n   { \"content-type\" => \"___\" },\n   [JSON.generate(data)]]\nend\n\nstatus, headers, body = json_response(200, { message: \"OK\" })\nputs status\nputs headers[\"content-type\"]\nputs body.first`, solution: `require 'json'\n\ndef json_response(status, data)\n  [status,\n   { \"content-type\" => \"application/json\" },\n   [JSON.generate(data)]]\nend\n\nstatus, headers, body = json_response(200, { message: \"OK\" })\nputs status\nputs headers[\"content-type\"]\nputs body.first`, hints: ['JSON responses use the application/json content type', 'The body must be a JSON string wrapped in an array', 'This follows the Rack response format'], concepts: ['json_response', 'content_type'] },
    { id: 'rb-json-api-5', title: 'Error Response Format', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Create a standard API error response.', skeleton: `require 'json'\n\ndef error_response(status, message, code: nil)\n  body = { error: { message: message } }\n  body[:error][:code] = code if code\n  [status, { \"content-type\" => \"application/json\" }, [JSON.___(body)]]\nend\n\nstatus, _, body = error_response(404, \"User not found\", code: \"NOT_FOUND\")\nputs status\nputs body.first`, solution: `require 'json'\n\ndef error_response(status, message, code: nil)\n  body = { error: { message: message } }\n  body[:error][:code] = code if code\n  [status, { \"content-type\" => \"application/json\" }, [JSON.generate(body)]]\nend\n\nstatus, _, body = error_response(404, \"User not found\", code: \"NOT_FOUND\")\nputs status\nputs body.first`, hints: ['JSON.generate converts the hash to a JSON string', 'Error responses should include a descriptive message', 'Optional error codes help clients handle specific errors'], concepts: ['error_response', 'api_errors'] },
    { id: 'rb-json-api-6', title: 'Bearer Token Extraction', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Extract a bearer token from the Authorization header.', skeleton: `def extract_token(env)\n  auth = env['HTTP_AUTHORIZATION']\n  return nil unless auth\n  match = auth.match(/^Bearer\\s+(.+)$/)\n  match ? match[___] : nil\nend\n\nputs extract_token({ 'HTTP_AUTHORIZATION' => 'Bearer abc123' })\nputs extract_token({}).inspect`, solution: `def extract_token(env)\n  auth = env['HTTP_AUTHORIZATION']\n  return nil unless auth\n  match = auth.match(/^Bearer\\s+(.+)$/)\n  match ? match[1] : nil\nend\n\nputs extract_token({ 'HTTP_AUTHORIZATION' => 'Bearer abc123' })\nputs extract_token({}).inspect`, hints: ['match[1] returns the first capture group', 'The regex captures everything after "Bearer "', 'Return nil when no Authorization header is present'], concepts: ['bearer_token', 'regex_capture'] },
    { id: 'rb-json-api-7', title: 'Write JSON Serializer', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a serializer that converts Ruby objects to API-friendly JSON.', skeleton: `# Write a Serializer class:\n# - initialize with a list of field names\n# - serialize(object) returns a hash with only the specified fields\n# - serialize_many(objects) serializes an array\n# - to_json(object_or_array) returns the JSON string\n# Object fields accessed via methods or hash keys\n`, solution: `require 'json'\n\nclass Serializer\n  def initialize(*fields)\n    @fields = fields\n  end\n\n  def serialize(object)\n    @fields.each_with_object({}) do |field, hash|\n      hash[field] = if object.is_a?(Hash)\n        object[field] || object[field.to_s]\n      else\n        object.send(field)\n      end\n    end\n  end\n\n  def serialize_many(objects)\n    objects.map { |obj| serialize(obj) }\n  end\n\n  def to_json(input)\n    data = input.is_a?(Array) ? serialize_many(input) : serialize(input)\n    JSON.generate(data)\n  end\nend\n\nUser = Struct.new(:id, :name, :email, :password_hash, keyword_init: true)\n\nserializer = Serializer.new(:id, :name, :email)\n\nuser = User.new(id: 1, name: \"Alice\", email: \"alice@example.com\", password_hash: \"secret\")\nputs serializer.to_json(user)\n\nusers = [\n  User.new(id: 1, name: \"Alice\", email: \"a@test.com\", password_hash: \"x\"),\n  User.new(id: 2, name: \"Bob\", email: \"b@test.com\", password_hash: \"y\"),\n]\nputs serializer.to_json(users)`, hints: ['Use send(field) to call a method by name on objects', 'For hashes, use hash[field] to get the value', 'Serializers filter sensitive fields like passwords'], concepts: ['serialization', 'api_serializer'] },
    { id: 'rb-json-api-8', title: 'Write Pagination Helper', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a pagination helper for API responses.', skeleton: `# Write a Paginator class:\n# - initialize(items, page:, per_page:)\n# - current_page returns paginated items\n# - metadata returns { page:, per_page:, total:, total_pages: }\n# - to_response returns { data: [...], meta: {...} }\n`, solution: `require 'json'\n\nclass Paginator\n  def initialize(items, page: 1, per_page: 10)\n    @items = items\n    @page = [page, 1].max\n    @per_page = [per_page, 1].max\n  end\n\n  def total_pages\n    (@items.size.to_f / @per_page).ceil\n  end\n\n  def current_page\n    offset = (@page - 1) * @per_page\n    @items[offset, @per_page] || []\n  end\n\n  def metadata\n    {\n      page: @page,\n      per_page: @per_page,\n      total: @items.size,\n      total_pages: total_pages\n    }\n  end\n\n  def to_response\n    { data: current_page, meta: metadata }\n  end\nend\n\nitems = (1..25).to_a\n\np1 = Paginator.new(items, page: 1, per_page: 10)\nputs JSON.generate(p1.to_response)\n\np3 = Paginator.new(items, page: 3, per_page: 10)\nputs JSON.generate(p3.to_response)`, hints: ['Offset = (page - 1) * per_page', 'Use .ceil to round up total_pages', 'Return empty array if page is beyond the data'], concepts: ['pagination', 'api_pagination'] },
    { id: 'rb-json-api-9', title: 'Write Rate Limiter', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a token-bucket rate limiter for API endpoints.', skeleton: `# Write a RateLimiter class:\n# - initialize(max_requests, window_seconds)\n# - allow?(client_id) returns true if request is allowed\n# - Tracks requests per client within the time window\n# - reset! clears all tracking data\n`, solution: `class RateLimiter\n  def initialize(max_requests, window_seconds)\n    @max = max_requests\n    @window = window_seconds\n    @clients = {}\n  end\n\n  def allow?(client_id)\n    now = Time.now.to_f\n    cleanup(client_id, now)\n\n    @clients[client_id] ||= []\n    requests = @clients[client_id]\n\n    if requests.size < @max\n      requests << now\n      true\n    else\n      false\n    end\n  end\n\n  def remaining(client_id)\n    now = Time.now.to_f\n    cleanup(client_id, now)\n    count = (@clients[client_id] || []).size\n    [@max - count, 0].max\n  end\n\n  def reset!\n    @clients.clear\n  end\n\n  private\n\n  def cleanup(client_id, now)\n    return unless @clients[client_id]\n    @clients[client_id].reject! { |t| now - t > @window }\n  end\nend\n\nlimiter = RateLimiter.new(3, 60)\n\nputs limiter.allow?(\"user1\")\nputs limiter.allow?(\"user1\")\nputs limiter.allow?(\"user1\")\nputs limiter.allow?(\"user1\")\nputs limiter.remaining(\"user1\")\nputs limiter.allow?(\"user2\")`, hints: ['Track timestamps of each request per client', 'Remove timestamps older than the window', 'Compare count against max to decide'], concepts: ['rate_limiting', 'token_bucket'] },
    { id: 'rb-json-api-10', title: 'Write API Versioning', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write middleware that routes requests to versioned API handlers.', skeleton: `# Write a VersionRouter middleware:\n# - Reads API version from Accept header (application/vnd.api.v1+json)\n# - Falls back to URL prefix (/v1/..., /v2/...)\n# - Dispatches to the correct version handler\n# - Returns 406 if version is unsupported\n`, solution: `require 'json'\n\nclass VersionRouter\n  def initialize(versions = {})\n    @versions = versions\n  end\n\n  def register(version, app)\n    @versions[version] = app\n    self\n  end\n\n  def call(env)\n    version = extract_version(env)\n    app = @versions[version]\n\n    if app\n      if env['PATH_INFO']&.match?(/^\\/v\\d+/)\n        env['PATH_INFO'] = env['PATH_INFO'].sub(/^\\/v\\d+/, '')\n        env['PATH_INFO'] = '/' if env['PATH_INFO'].empty?\n      end\n      app.call(env)\n    else\n      [406, { \"content-type\" => \"application/json\" },\n       [JSON.generate({ error: \"Unsupported API version: \\\#{version}\" })]]\n    end\n  end\n\n  private\n\n  def extract_version(env)\n    accept = env['HTTP_ACCEPT'] || ''\n    if (m = accept.match(/application\\/vnd\\.api\\.v(\\d+)\\+json/))\n      m[1].to_i\n    elsif (m = env['PATH_INFO']&.match(/^\\/v(\\d+)/))\n      m[1].to_i\n    else\n      1\n    end\n  end\nend\n\nv1 = lambda { |env| [200, {}, [JSON.generate({ version: 1, data: \"old format\" })]] }\nv2 = lambda { |env| [200, {}, [JSON.generate({ version: 2, data: { value: \"new format\" } })]] }\n\nrouter = VersionRouter.new\nrouter.register(1, v1)\nrouter.register(2, v2)\n\nstatus, _, body = router.call({ 'PATH_INFO' => '/v2/users', 'HTTP_ACCEPT' => '' })\nputs body.first\n\nstatus, _, body = router.call({ 'PATH_INFO' => '/users', 'HTTP_ACCEPT' => 'application/vnd.api.v1+json' })\nputs body.first\n\nstatus, _, body = router.call({ 'PATH_INFO' => '/v99/users' })\nputs \"\\\#{status}: \\\#{body.first}\"`, hints: ['Check Accept header first, then URL prefix', 'Strip the version prefix from PATH_INFO before delegating', 'Return 406 Not Acceptable for unsupported versions'], concepts: ['api_versioning', 'content_negotiation'] },
    { id: 'rb-json-api-11', title: 'Write HTTP Client Wrapper', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a simple HTTP client wrapper around Net::HTTP.', skeleton: `# Write an ApiClient class:\n# - initialize(base_url)\n# - get(path, headers: {}) makes a GET request\n# - post(path, body:, headers: {}) makes a POST request\n# - Returns a Result struct with status, headers, body (parsed JSON)\n# (Simulate responses for testing without real HTTP)\n`, solution: `require 'json'\nrequire 'uri'\n\nResult = Struct.new(:status, :headers, :body, keyword_init: true)\n\nclass ApiClient\n  def initialize(base_url)\n    @base_url = base_url\n  end\n\n  def get(path, headers: {})\n    request(:GET, path, headers: headers)\n  end\n\n  def post(path, body: {}, headers: {})\n    request(:POST, path, body: body, headers: headers)\n  end\n\n  private\n\n  def request(method, path, body: nil, headers: {})\n    uri = URI.join(@base_url, path)\n    default_headers = { \"content-type\" => \"application/json\", \"accept\" => \"application/json\" }\n    merged_headers = default_headers.merge(headers)\n\n    # In real code, this would use Net::HTTP\n    # Simulating for demonstration\n    puts \"[API] \\\#{method} \\\#{uri}\"\n    puts \"[API] Headers: \\\#{merged_headers.inspect}\"\n    puts \"[API] Body: \\\#{JSON.generate(body)}\" if body\n\n    # Simulated response\n    Result.new(\n      status: 200,\n      headers: { \"content-type\" => \"application/json\" },\n      body: { path: path, method: method.to_s }\n    )\n  end\nend\n\nclient = ApiClient.new(\"https://api.example.com\")\n\nresult = client.get(\"/users\")\nputs result.status\nputs result.body.inspect\n\nresult = client.post(\"/users\", body: { name: \"Alice\" })\nputs result.status`, hints: ['URI.join combines base_url with path', 'Merge default headers with custom headers', 'Return a structured result instead of raw response'], concepts: ['http_client', 'net_http'] },
    { id: 'rb-json-api-12', title: 'Write JSON Schema Validator', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a simple JSON schema validator for API input.', skeleton: `# Write a Schema class:\n# - define fields with type, required, optional constraints\n# - validate(data) returns { valid: true/false, errors: [...] }\n# - Support types: string, integer, array, hash\n# - Support required fields and optional with defaults\n`, solution: `class Schema\n  def initialize(&block)\n    @fields = {}\n    instance_eval(&block) if block\n  end\n\n  def field(name, type:, required: true, default: nil)\n    @fields[name] = { type: type, required: required, default: default }\n  end\n\n  def validate(data)\n    errors = []\n    result = {}\n\n    @fields.each do |name, rules|\n      value = data[name] || data[name.to_s]\n\n      if value.nil?\n        if rules[:required]\n          errors << \"Missing required field: \\\#{name}\"\n          next\n        else\n          value = rules[:default]\n        end\n      end\n\n      unless value.nil?\n        unless type_match?(value, rules[:type])\n          errors << \"Field \\\#{name}: expected \\\#{rules[:type]}, got \\\#{value.class}\"\n          next\n        end\n      end\n\n      result[name] = value\n    end\n\n    { valid: errors.empty?, errors: errors, data: result }\n  end\n\n  private\n\n  def type_match?(value, type)\n    case type\n    when :string then value.is_a?(String)\n    when :integer then value.is_a?(Integer)\n    when :array then value.is_a?(Array)\n    when :hash then value.is_a?(Hash)\n    else true\n    end\n  end\nend\n\nuser_schema = Schema.new do\n  field :name, type: :string\n  field :age, type: :integer\n  field :role, type: :string, required: false, default: \"user\"\nend\n\ngood = user_schema.validate({ name: \"Alice\", age: 30 })\nputs good.inspect\n\nbad = user_schema.validate({ name: 123 })\nputs bad.inspect`, hints: ['Check each field for presence and type', 'Collect all errors instead of failing on the first one', 'Apply defaults for missing optional fields'], concepts: ['schema_validation', 'input_validation'] },
    { id: 'rb-json-api-13', title: 'Fix JSON Parse Error Handling', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the API that crashes on invalid JSON input.', skeleton: `require 'json'\n\ndef parse_request_body(body_string)\n  # Bug: crashes with JSON::ParserError on invalid input\n  data = JSON.parse(body_string)\n  { success: true, data: data }\nend\n\nputs parse_request_body('{\"name\": \"Alice\"}').inspect\nputs parse_request_body('not valid json').inspect`, solution: `require 'json'\n\ndef parse_request_body(body_string)\n  data = JSON.parse(body_string)\n  { success: true, data: data }\nrescue JSON::ParserError => e\n  { success: false, error: \"Invalid JSON: \\\#{e.message}\" }\nend\n\nputs parse_request_body('{\"name\": \"Alice\"}').inspect\nputs parse_request_body('not valid json').inspect`, hints: ['Wrap JSON.parse in a rescue block', 'Catch JSON::ParserError specifically', 'Return a structured error instead of crashing'], concepts: ['error_handling', 'json_parse_error'] },
    { id: 'rb-json-api-14', title: 'Fix Missing Content-Type', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the API endpoint that returns JSON without proper content-type.', skeleton: `require 'json'\n\nclass UsersApi\n  def call(env)\n    users = [{ id: 1, name: \"Alice\" }, { id: 2, name: \"Bob\" }]\n    # Bug: missing content-type header causes clients to misinterpret response\n    [200, {}, [JSON.generate({ users: users })]]\n  end\nend\n\napp = UsersApi.new\nstatus, headers, body = app.call({})\nputs headers.inspect\nputs body.first`, solution: `require 'json'\n\nclass UsersApi\n  def call(env)\n    users = [{ id: 1, name: \"Alice\" }, { id: 2, name: \"Bob\" }]\n    [200, { \"content-type\" => \"application/json\" }, [JSON.generate({ users: users })]]\n  end\nend\n\napp = UsersApi.new\nstatus, headers, body = app.call({})\nputs headers.inspect\nputs body.first`, hints: ['API responses must include the correct content-type header', 'JSON responses need application/json', 'Clients rely on content-type to parse the response'], concepts: ['content_type', 'http_headers'] },
    { id: 'rb-json-api-15', title: 'Fix Nested JSON Serialization', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the double-serialization bug in the API response.', skeleton: `require 'json'\n\ndef api_response(data)\n  # Bug: data is already JSON-serialized, then serialized again\n  json_data = JSON.generate(data)\n  [200, { \"content-type\" => \"application/json\" }, [JSON.generate(json_data)]]\nend\n\n_, _, body = api_response({ users: [\"Alice\"] })\nputs body.first\n# Outputs: \"\\\"{\\\\\\\"users\\\\\\\":[\\\\\\\"Alice\\\\\\\"]}\\\"\" (double-encoded!)`, solution: `require 'json'\n\ndef api_response(data)\n  [200, { \"content-type\" => \"application/json\" }, [JSON.generate(data)]]\nend\n\n_, _, body = api_response({ users: [\"Alice\"] })\nputs body.first`, hints: ['The data is being JSON-serialized twice', 'JSON.generate should be called only once', 'Remove the intermediate serialization step'], concepts: ['double_serialization', 'json_generate'] },
    { id: 'rb-json-api-16', title: 'Predict JSON Parse Output', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict the result of parsing JSON with different options.', skeleton: `require 'json'\n\ndata = JSON.parse('{\"name\": \"test\", \"count\": 5}')\nputs data.class\nputs data[\"count\"] + 1\nputs data[:name].inspect`, solution: `Hash\n6\nnil`, hints: ['JSON.parse returns a Hash by default', 'JSON numbers become Ruby integers', 'Keys are strings unless symbolize_names is used'], concepts: ['json_parse', 'key_types'] },
    { id: 'rb-json-api-17', title: 'Predict API Response Flow', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict the output of chained API middleware.', skeleton: `require 'json'\n\nclass JsonBody\n  def initialize(app) = @app = app\n  def call(env)\n    status, headers, body = @app.call(env)\n    parsed = JSON.parse(body.first)\n    parsed[\"processed\"] = true\n    [status, headers, [JSON.generate(parsed)]]\n  end\nend\n\ninner = lambda { |env| [200, {}, ['{\"msg\": \"hello\"}']] }\napp = JsonBody.new(inner)\n\n_, _, body = app.call({})\nresult = JSON.parse(body.first)\nputs result.keys.sort.join(\", \")\nputs result[\"processed\"]`, solution: `msg, processed\ntrue`, hints: ['The middleware parses the inner response body', 'It adds "processed" => true to the parsed hash', 'keys.sort alphabetically sorts the key names'], concepts: ['middleware_transform', 'json_manipulation'] },
    { id: 'rb-json-api-18', title: 'Predict JSON Generate Types', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict how Ruby types are converted to JSON.', skeleton: `require 'json'\n\ndata = {\n  string: \"hello\",\n  number: 42,\n  float: 3.14,\n  bool: true,\n  nothing: nil,\n  list: [1, 2, 3]\n}\n\njson = JSON.generate(data)\nparsed = JSON.parse(json)\nputs parsed[\"nothing\"].inspect\nputs parsed[\"bool\"].class\nputs parsed[\"list\"].length`, solution: `nil\nTrueClass\n3`, hints: ['Ruby nil becomes JSON null, parsed back as nil', 'JSON true becomes Ruby TrueClass', 'Arrays preserve their length through serialization'], concepts: ['json_type_mapping', 'serialization'] },
    { id: 'rb-json-api-19', title: 'Refactor String Responses to JSON', type: 'refactor', difficulty: 'intermediate', language: 'ruby', goal: 'Refactor an API that returns plain text to return proper JSON.', skeleton: `def get_user(id)\n  if id == 1\n    [200, {}, [\"User: Alice, Age: 30\"]]\n  else\n    [404, {}, [\"Error: User not found\"]]\n  end\nend\n\nputs get_user(1)[2].first\nputs get_user(99)[2].first`, solution: `require 'json'\n\ndef get_user(id)\n  headers = { \"content-type\" => \"application/json\" }\n\n  if id == 1\n    [200, headers, [JSON.generate({ user: { id: 1, name: \"Alice\", age: 30 } })]]\n  else\n    [404, headers, [JSON.generate({ error: { message: \"User not found\", code: \"NOT_FOUND\" } })]]\n  end\nend\n\nputs get_user(1)[2].first\nputs get_user(99)[2].first`, hints: ['Return structured JSON instead of plain text strings', 'Include proper content-type headers', 'Use consistent error response format'], concepts: ['json_responses', 'api_conventions'] },
    { id: 'rb-json-api-20', title: 'Refactor Inline Auth to Middleware', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor inline authentication checks into reusable middleware.', skeleton: `require 'json'\n\nTOKENS = { \"abc123\" => { id: 1, name: \"Alice\" }, \"xyz789\" => { id: 2, name: \"Bob\" } }\n\ndef get_profile(env)\n  token = env['HTTP_AUTHORIZATION']&.sub('Bearer ', '')\n  unless token && TOKENS[token]\n    return [401, { \"content-type\" => \"application/json\" },\n            [JSON.generate({ error: \"Unauthorized\" })]]\n  end\n  user = TOKENS[token]\n  [200, { \"content-type\" => \"application/json\" },\n   [JSON.generate({ user: user })]]\nend\n\ndef get_settings(env)\n  token = env['HTTP_AUTHORIZATION']&.sub('Bearer ', '')\n  unless token && TOKENS[token]\n    return [401, { \"content-type\" => \"application/json\" },\n            [JSON.generate({ error: \"Unauthorized\" })]]\n  end\n  [200, { \"content-type\" => \"application/json\" },\n   [JSON.generate({ settings: { theme: \"dark\" } })]]\nend\n\nputs get_profile({ 'HTTP_AUTHORIZATION' => 'Bearer abc123' })[2].first`, solution: `require 'json'\n\nTOKENS = { \"abc123\" => { id: 1, name: \"Alice\" }, \"xyz789\" => { id: 2, name: \"Bob\" } }\n\nclass AuthMiddleware\n  def initialize(app)\n    @app = app\n  end\n\n  def call(env)\n    token = env['HTTP_AUTHORIZATION']&.sub('Bearer ', '')\n    user = TOKENS[token] if token\n\n    unless user\n      return [401, { \"content-type\" => \"application/json\" },\n              [JSON.generate({ error: \"Unauthorized\" })]]\n    end\n\n    env['current_user'] = user\n    @app.call(env)\n  end\nend\n\nget_profile = lambda do |env|\n  user = env['current_user']\n  [200, { \"content-type\" => \"application/json\" },\n   [JSON.generate({ user: user })]]\nend\n\nget_settings = lambda do |env|\n  [200, { \"content-type\" => \"application/json\" },\n   [JSON.generate({ settings: { theme: \"dark\" } })]]\nend\n\nprofile_app = AuthMiddleware.new(get_profile)\nsettings_app = AuthMiddleware.new(get_settings)\n\nputs profile_app.call({ 'HTTP_AUTHORIZATION' => 'Bearer abc123' })[2].first\nputs settings_app.call({})[0]`, hints: ['Extract the repeated auth logic into a middleware class', 'Middleware sets current_user in env for downstream handlers', 'Handlers no longer need to check authentication themselves'], concepts: ['auth_middleware', 'dry_principle'] },
  ],
};
