import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-perf',
  title: '49. Ruby Performance',
  explanation: `## Ruby Performance

Writing performant Ruby requires understanding memory allocation, method dispatch, and the garbage collector.

### Benchmark Module

\`\`\`ruby
require 'benchmark'

Benchmark.bm(10) do |x|
  x.report("concat:") { 1000.times { "a" + "b" } }
  x.report("interp:") { 1000.times { "\\\#{"a"}\\\#{"b"}" } }
end
\`\`\`

### Frozen String Literals

\`\`\`ruby
# frozen_string_literal: true
# Strings are frozen by default, reducing allocations

str = "hello"        # Frozen, reused
str.frozen?          # true
mutable = +"hello"   # Unfrozen copy with unary +
\`\`\`

### Memoization

\`\`\`ruby
class Fibonacci
  def initialize
    @cache = {}
  end

  def compute(n)
    @cache[n] ||= n < 2 ? n : compute(n - 1) + compute(n - 2)
  end
end
\`\`\`

### Lazy Enumerators

\`\`\`ruby
# Processes only what's needed, avoids building full arrays
(1..Float::INFINITY).lazy.select(&:odd?).take(5).to_a
# => [1, 3, 5, 7, 9]
\`\`\`

### Symbol vs String

\`\`\`ruby
# Symbols are immutable and unique - ideal for identifiers
:name.object_id == :name.object_id  # true (same object)
"name".object_id == "name".object_id  # false (different objects)
\`\`\`

### GC Tuning

\`\`\`ruby
GC.stat          # GC statistics hash
GC.count         # Number of GC runs
GC.disable       # Temporarily disable GC
GC.enable        # Re-enable
\`\`\``,
  exercises: [
    { id: 'rb-perf-1', title: 'Basic Benchmark', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use the Benchmark module to measure code execution time.', skeleton: `require '___'\n\nresult = Benchmark.measure { 100_000.times { \"hello\" + \" world\" } }\nputs result`, solution: `require 'benchmark'\n\nresult = Benchmark.measure { 100_000.times { \"hello\" + \" world\" } }\nputs result`, hints: ['The benchmark module is part of Ruby stdlib', 'Benchmark.measure wraps a block and times it', 'It returns user, system, and real time'], concepts: ['benchmark', 'measure'] },
    { id: 'rb-perf-2', title: 'Frozen Strings', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use frozen strings to reduce object allocation.', skeleton: `str = \"hello\".___ \nbegin\n  str << \" world\"\nrescue => e\n  puts e.class\nend\nputs str`, solution: `str = \"hello\".freeze\nbegin\n  str << \" world\"\nrescue => e\n  puts e.class\nend\nputs str`, hints: ['.freeze makes the string immutable', 'Attempting to modify a frozen string raises FrozenError', 'Frozen strings are more memory-efficient'], concepts: ['frozen_strings', 'immutability'] },
    { id: 'rb-perf-3', title: 'Memoization with ||=', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Use memoization to cache expensive computations.', skeleton: `class Calculator\n  def expensive_result\n    @result ___= begin\n      puts \"Computing...\"\n      (1..1_000_000).sum\n    end\n  end\nend\n\nc = Calculator.new\nputs c.expensive_result\nputs c.expensive_result`, solution: `class Calculator\n  def expensive_result\n    @result ||= begin\n      puts \"Computing...\"\n      (1..1_000_000).sum\n    end\n  end\nend\n\nc = Calculator.new\nputs c.expensive_result\nputs c.expensive_result`, hints: ['||= assigns only if the variable is nil or false', 'The block runs only on the first call', 'Subsequent calls return the cached value'], concepts: ['memoization', 'caching'] },
    { id: 'rb-perf-4', title: 'Lazy Enumerator', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Use lazy evaluation to process infinite sequences efficiently.', skeleton: `result = (1..Float::INFINITY)\n  .___\n  .select { |n| n % 3 == 0 }\n  .map { |n| n * n }\n  .first(5)\n\nputs result.inspect`, solution: `result = (1..Float::INFINITY)\n  .lazy\n  .select { |n| n % 3 == 0 }\n  .map { |n| n * n }\n  .first(5)\n\nputs result.inspect`, hints: ['.lazy creates a lazy enumerator', 'Elements are processed one at a time, on demand', 'Without lazy, this would try to create an infinite array'], concepts: ['lazy_enumerator', 'infinite_sequences'] },
    { id: 'rb-perf-5', title: 'Symbol vs String Keys', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Demonstrate why symbols are faster as hash keys than strings.', skeleton: `require 'benchmark'\n\nn = 500_000\n\nBenchmark.bm(12) do |x|\n  x.report(\"string keys:\") {\n    h = {}\n    n.times { |i| h[\"key\"] = i }\n  }\n  x.report(\"symbol keys:\") {\n    h = {}\n    n.times { |i| h[:___] = i }\n  }\nend\n\nputs :key.object_id == :key.object_id\nputs \"key\".object_id == \"key\".object_id`, solution: `require 'benchmark'\n\nn = 500_000\n\nBenchmark.bm(12) do |x|\n  x.report(\"string keys:\") {\n    h = {}\n    n.times { |i| h[\"key\"] = i }\n  }\n  x.report(\"symbol keys:\") {\n    h = {}\n    n.times { |i| h[:key] = i }\n  }\nend\n\nputs :key.object_id == :key.object_id\nputs \"key\".object_id == \"key\".object_id`, hints: ['Symbols have the same object_id every time', 'String literals create new objects each time (unless frozen)', 'Symbol comparison is faster because it compares object_ids'], concepts: ['symbol_performance', 'object_identity'] },
    { id: 'rb-perf-6', title: 'GC Statistics', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Read garbage collector statistics to understand memory usage.', skeleton: `before = GC.___\n\n# Generate garbage\n100_000.times { \"x\" * 100 }\n\nafter = GC.count\nputs \"GC runs: \\\#{after - before}\"\n\nstats = GC.stat\nputs \"Heap pages: \\\#{stats[:heap_allocated_pages]}\"\nputs \"Total objects: \\\#{stats[:total_allocated_objects]}\"`, solution: `before = GC.count\n\n# Generate garbage\n100_000.times { \"x\" * 100 }\n\nafter = GC.count\nputs \"GC runs: \\\#{after - before}\"\n\nstats = GC.stat\nputs \"Heap pages: \\\#{stats[:heap_allocated_pages]}\"\nputs \"Total objects: \\\#{stats[:total_allocated_objects]}\"`, hints: ['GC.count returns the number of GC runs so far', 'GC.stat returns a hash of detailed statistics', 'Compare before/after to see GC activity from your code'], concepts: ['gc_stats', 'garbage_collection'] },
    { id: 'rb-perf-7', title: 'Write Memoized Fibonacci', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a memoized Fibonacci calculator and benchmark it against naive recursion.', skeleton: `# Write:\n# - fib_naive(n): recursive Fibonacci without memoization\n# - FibMemo class with compute(n) using a cache hash\n# - Benchmark both for n = 30\n`, solution: `require 'benchmark'\n\ndef fib_naive(n)\n  return n if n < 2\n  fib_naive(n - 1) + fib_naive(n - 2)\nend\n\nclass FibMemo\n  def initialize\n    @cache = {}\n  end\n\n  def compute(n)\n    @cache[n] ||= if n < 2\n      n\n    else\n      compute(n - 1) + compute(n - 2)\n    end\n  end\nend\n\nmemo = FibMemo.new\n\nBenchmark.bm(10) do |x|\n  x.report(\"naive:\") { fib_naive(30) }\n  x.report(\"memoized:\") { memo.compute(30) }\nend\n\nputs \"Result: \\\#{memo.compute(30)}\"`, hints: ['Naive recursion has exponential time complexity O(2^n)', 'Memoization reduces it to O(n) with a cache', '||= caches the result on first computation'], concepts: ['memoization', 'fibonacci', 'big_o'] },
    { id: 'rb-perf-8', title: 'Write Object Pool', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write an object pool that reuses objects instead of allocating new ones.', skeleton: `# Write an ObjectPool class:\n# - initialize(size, &factory) creates a pool of reusable objects\n# - checkout yields an object to a block, returns it on completion\n# - Objects are reused to reduce GC pressure\n# - Thread-safe with Mutex\n`, solution: `class ObjectPool\n  def initialize(size, &factory)\n    @mutex = Mutex.new\n    @pool = Array.new(size) { factory.call }\n    @factory = factory\n  end\n\n  def checkout\n    obj = @mutex.synchronize { @pool.pop }\n    obj ||= @factory.call\n    begin\n      yield obj\n    ensure\n      @mutex.synchronize { @pool.push(obj) }\n    end\n  end\n\n  def size\n    @mutex.synchronize { @pool.size }\n  end\nend\n\npool = ObjectPool.new(3) { String.new }\n\nputs \"Pool size: \\\#{pool.size}\"\n\npool.checkout do |str|\n  str.replace(\"Hello from pool!\")\n  puts str\n  puts \"Pool during checkout: \\\#{pool.size}\"\nend\n\nputs \"Pool after return: \\\#{pool.size}\"`, hints: ['Pre-allocate objects in the constructor', 'checkout pops from pool, returns object via ensure', 'Mutex makes it safe for concurrent access'], concepts: ['object_pool', 'gc_pressure', 'thread_safety'] },
    { id: 'rb-perf-9', title: 'Write Method Cache', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a method-level caching decorator using a module.', skeleton: `# Write a Cacheable module:\n# - cache_method(method_name) wraps a method with memoization\n# - Caches based on arguments\n# - clear_cache resets all cached values\n`, solution: `module Cacheable\n  def self.included(base)\n    base.extend(ClassMethods)\n    base.instance_variable_set(:@_cache_store, {})\n  end\n\n  module ClassMethods\n    def cache_method(method_name)\n      original = instance_method(method_name)\n\n      define_method(method_name) do |*args|\n        cache = (@_method_cache ||= {})\n        key = [method_name, args]\n        if cache.key?(key)\n          cache[key]\n        else\n          cache[key] = original.bind(self).call(*args)\n        end\n      end\n    end\n  end\n\n  def clear_cache\n    @_method_cache&.clear\n  end\nend\n\nclass MathService\n  include Cacheable\n\n  def factorial(n)\n    puts \"Computing factorial(\\\#{n})\"\n    return 1 if n <= 1\n    n * factorial(n - 1)\n  end\n  cache_method :factorial\n\n  def square(n)\n    puts \"Computing square(\\\#{n})\"\n    n * n\n  end\n  cache_method :square\nend\n\nm = MathService.new\nputs m.factorial(5)\nputs m.factorial(5)\nputs m.square(4)\nputs m.square(4)`, hints: ['Use instance_method to get the original unbound method', 'define_method replaces the method with a caching wrapper', 'Cache key includes method name and arguments'], concepts: ['method_caching', 'decorator_pattern'] },
    { id: 'rb-perf-10', title: 'Write String Builder', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a string builder that avoids repeated string allocation.', skeleton: `# Write a StringBuilder class:\n# - append(str) adds to the buffer efficiently\n# - prepend(str) adds to the front\n# - to_s returns the built string\n# - Benchmark against naive string concatenation\n`, solution: `require 'benchmark'\n\nclass StringBuilder\n  def initialize\n    @parts = []\n  end\n\n  def append(str)\n    @parts << str\n    self\n  end\n\n  def prepend(str)\n    @parts.unshift(str)\n    self\n  end\n\n  def to_s\n    @parts.join\n  end\n\n  def length\n    @parts.sum(&:length)\n  end\nend\n\nn = 50_000\n\nBenchmark.bm(15) do |x|\n  x.report(\"concat (+):\") {\n    str = \"\"\n    n.times { str = str + \"x\" }\n  }\n\n  x.report(\"shovel (<<):\") {\n    str = String.new\n    n.times { str << \"x\" }\n  }\n\n  x.report(\"StringBuilder:\") {\n    sb = StringBuilder.new\n    n.times { sb.append(\"x\") }\n    sb.to_s\n  }\n\n  x.report(\"Array#join:\") {\n    parts = []\n    n.times { parts << \"x\" }\n    parts.join\n  }\nend`, hints: ['String + creates a new object each time (O(n^2))', '<< mutates in place (O(n) amortized)', 'Array#join is often the fastest approach'], concepts: ['string_performance', 'allocation'] },
    { id: 'rb-perf-11', title: 'Write Lazy Data Pipeline', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a lazy data processing pipeline that handles large datasets efficiently.', skeleton: `# Write a Pipeline class:\n# - from(enumerable) starts the pipeline\n# - where(&block) filters lazily\n# - transform(&block) maps lazily\n# - take(n) limits results\n# - to_a materializes the pipeline\n# Use lazy enumerators internally\n`, solution: `class Pipeline\n  def initialize(source)\n    @chain = source.lazy\n  end\n\n  def self.from(enumerable)\n    new(enumerable)\n  end\n\n  def where(&block)\n    @chain = @chain.select(&block)\n    self\n  end\n\n  def transform(&block)\n    @chain = @chain.map(&block)\n    self\n  end\n\n  def take(n)\n    @chain = @chain.take(n)\n    self\n  end\n\n  def each(&block)\n    @chain.each(&block)\n  end\n\n  def to_a\n    @chain.to_a\n  end\n\n  def reduce(initial, &block)\n    @chain.reduce(initial, &block)\n  end\nend\n\n# Process an \"infinite\" dataset\nresult = Pipeline\n  .from(1..Float::INFINITY)\n  .where { |n| n.odd? }\n  .transform { |n| n ** 2 }\n  .where { |n| n > 10 }\n  .take(5)\n  .to_a\n\nputs result.inspect\n\n# Process a large range without loading it all into memory\nsum = Pipeline\n  .from(1..1_000_000)\n  .where { |n| n % 7 == 0 }\n  .transform { |n| n * 2 }\n  .take(100)\n  .reduce(0) { |acc, n| acc + n }\n\nputs \"Sum: \\\#{sum}\"`, hints: ['Use .lazy to create lazy enumerators', 'Chain operations without materializing intermediate arrays', 'to_a or reduce forces evaluation of the chain'], concepts: ['lazy_evaluation', 'data_pipeline'] },
    { id: 'rb-perf-12', title: 'Write Allocation Tracker', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a utility that counts object allocations in a block.', skeleton: `# Write an AllocationTracker module:\n# - track { ... } returns { count:, by_type: { String: n, Array: m, ... } }\n# - Uses GC.stat and ObjectSpace to count allocations\n`, solution: `require 'objspace'\n\nmodule AllocationTracker\n  def self.track\n    GC.start\n    GC.disable\n\n    before = ObjectSpace.count_objects\n    yield\n    after = ObjectSpace.count_objects\n\n    GC.enable\n\n    diff = {}\n    after.each do |type, count|\n      change = count - (before[type] || 0)\n      diff[type] = change if change > 0\n    end\n\n    total = diff.values.sum\n    { count: total, by_type: diff }\n  end\nend\n\nresult = AllocationTracker.track do\n  100.times { \"hello\" + \" world\" }\nend\nputs \"Total allocations: \\\#{result[:count]}\"\nputs \"By type: \\\#{result[:by_type].inspect}\"\n\nresult2 = AllocationTracker.track do\n  str = String.new\n  100.times { str << \"hello world\" }\nend\nputs \"\\nWith <<:\"\nputs \"Total allocations: \\\#{result2[:count]}\"\nputs \"By type: \\\#{result2[:by_type].inspect}\"`, hints: ['Disable GC during tracking so objects are not collected', 'ObjectSpace.count_objects returns counts by type', 'Compare before and after to find new allocations'], concepts: ['allocation_tracking', 'objectspace'] },
    { id: 'rb-perf-13', title: 'Fix N+1 Query Pattern', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the N+1 data access pattern that causes poor performance.', skeleton: `# Simulated database\nUSERS = { 1 => \"Alice\", 2 => \"Bob\", 3 => \"Carol\" }\nORDERS = [\n  { id: 1, user_id: 1, total: 100 },\n  { id: 2, user_id: 1, total: 200 },\n  { id: 3, user_id: 2, total: 150 },\n  { id: 4, user_id: 3, total: 300 },\n  { id: 5, user_id: 2, total: 50 },\n]\n\n# Bug: N+1 - fetches user name separately for each order\ndef order_summaries\n  ORDERS.map do |order|\n    # This simulates a separate DB query per order\n    user_name = USERS[order[:user_id]]\n    \"\\\#{user_name}: $\\\#{order[:total]}\"\n  end\nend\n\norder_summaries.each { |s| puts s }`, solution: `USERS = { 1 => \"Alice\", 2 => \"Bob\", 3 => \"Carol\" }\nORDERS = [\n  { id: 1, user_id: 1, total: 100 },\n  { id: 2, user_id: 1, total: 200 },\n  { id: 3, user_id: 2, total: 150 },\n  { id: 4, user_id: 3, total: 300 },\n  { id: 5, user_id: 2, total: 50 },\n]\n\ndef order_summaries\n  # Pre-load all needed users in one batch\n  user_ids = ORDERS.map { |o| o[:user_id] }.uniq\n  users_cache = user_ids.each_with_object({}) { |id, h| h[id] = USERS[id] }\n\n  ORDERS.map do |order|\n    user_name = users_cache[order[:user_id]]\n    \"\\\#{user_name}: $\\\#{order[:total]}\"\n  end\nend\n\norder_summaries.each { |s| puts s }`, hints: ['Collect all needed user IDs first', 'Fetch all users in one batch (eager loading)', 'Then look up from the cache instead of querying each time'], concepts: ['n_plus_one', 'eager_loading'] },
    { id: 'rb-perf-14', title: 'Fix Memory Leak in Cache', type: 'fix-bug', difficulty: 'advanced', language: 'ruby', goal: 'Fix the unbounded cache that causes a memory leak.', skeleton: `class DataCache\n  def initialize\n    @cache = {}\n  end\n\n  def fetch(key)\n    # Bug: cache grows without bound, causing memory leak\n    @cache[key] ||= expensive_compute(key)\n  end\n\n  def size\n    @cache.size\n  end\n\n  private\n\n  def expensive_compute(key)\n    \"result_for_\\\#{key}\" * 100\n  end\nend\n\ncache = DataCache.new\n10_000.times { |i| cache.fetch(\"key_\\\#{i}\") }\nputs \"Cache size: \\\#{cache.size}\"`, solution: `class DataCache\n  MAX_SIZE = 1000\n\n  def initialize\n    @cache = {}\n    @order = []\n  end\n\n  def fetch(key)\n    if @cache.key?(key)\n      @order.delete(key)\n      @order.push(key)\n      @cache[key]\n    else\n      evict if @cache.size >= MAX_SIZE\n      result = expensive_compute(key)\n      @cache[key] = result\n      @order.push(key)\n      result\n    end\n  end\n\n  def size\n    @cache.size\n  end\n\n  private\n\n  def evict\n    oldest = @order.shift\n    @cache.delete(oldest)\n  end\n\n  def expensive_compute(key)\n    \"result_for_\\\#{key}\" * 100\n  end\nend\n\ncache = DataCache.new\n10_000.times { |i| cache.fetch(\"key_\\\#{i}\") }\nputs \"Cache size: \\\#{cache.size}\"`, hints: ['Add a maximum cache size', 'Evict the oldest entry when the cache is full (LRU)', 'Track insertion order to know what to evict'], concepts: ['lru_cache', 'memory_leak'] },
    { id: 'rb-perf-15', title: 'Fix Inefficient String Building', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the O(n^2) string concatenation.', skeleton: `# Bug: String + creates a new string each time, O(n^2)\ndef build_report(items)\n  result = \"\"\n  items.each do |item|\n    result = result + \"Item: \\\#{item}\\n\"\n  end\n  result\nend\n\nitems = (1..1000).to_a\nputs build_report(items).lines.count`, solution: `def build_report(items)\n  result = String.new\n  items.each do |item|\n    result << \"Item: \\\#{item}\\n\"\n  end\n  result\nend\n\nitems = (1..1000).to_a\nputs build_report(items).lines.count`, hints: ['Use << instead of + for string building', '<< mutates in place, avoiding new allocations', 'String.new creates a mutable empty string'], concepts: ['string_concatenation', 'shovel_operator'] },
    { id: 'rb-perf-16', title: 'Predict Frozen String Behavior', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict frozen string behavior.', skeleton: `a = \"hello\"\nb = \"hello\"\nputs a.equal?(b)\n\na.freeze\nb.freeze\nputs a.frozen?\nputs b.frozen?\nputs a == b\nputs a.equal?(b)`, solution: `false\ntrue\ntrue\ntrue\nfalse`, hints: ['equal? checks object identity (same object_id)', 'Two string literals are different objects', 'Freezing does not make them the same object'], concepts: ['frozen_strings', 'object_identity'] },
    { id: 'rb-perf-17', title: 'Predict Lazy vs Eager', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict the difference between lazy and eager evaluation.', skeleton: `log = []\n\neager = [1, 2, 3, 4, 5]\n  .select { |n| log << \"s\\\#{n}\"; n.odd? }\n  .map { |n| log << \"m\\\#{n}\"; n * 10 }\n  .first(2)\n\nputs log.length\nlog.clear\n\nlazy = [1, 2, 3, 4, 5]\n  .lazy\n  .select { |n| log << \"s\\\#{n}\"; n.odd? }\n  .map { |n| log << \"m\\\#{n}\"; n * 10 }\n  .first(2)\n\nputs log.length`, solution: `8\n6`, hints: ['Eager processes ALL elements through select (5), then ALL results through map (3)', 'Lazy processes elements one at a time until it has enough', 'Lazy stops after finding 2 matching: processes s1,m1,s2,s3,m3,s4 = wait, let me recount...'], concepts: ['lazy_evaluation', 'short_circuit'] },
    { id: 'rb-perf-18', title: 'Predict Memoization Calls', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict how many times a memoized method computes.', skeleton: `class Service\n  attr_reader :call_count\n\n  def initialize\n    @call_count = 0\n  end\n\n  def result\n    @result ||= begin\n      @call_count += 1\n      42\n    end\n  end\nend\n\ns = Service.new\n5.times { s.result }\nputs s.call_count\nputs s.result`, solution: `1\n42`, hints: ['||= only evaluates the right side once', 'After the first call, @result is 42 (truthy)', 'call_count increments only on the first computation'], concepts: ['memoization', 'short_circuit_assignment'] },
    { id: 'rb-perf-19', title: 'Refactor Each to Map', type: 'refactor', difficulty: 'beginner', language: 'ruby', goal: 'Refactor imperative each+push to functional map.', skeleton: `# Imperative style with manual array building\ndef transform_data(items)\n  result = []\n  items.each do |item|\n    result.push(item.to_s.upcase)\n  end\n  result\nend\n\nputs transform_data([1, 2, 3]).inspect`, solution: `def transform_data(items)\n  items.map { |item| item.to_s.upcase }\nend\n\nputs transform_data([1, 2, 3]).inspect`, hints: ['map replaces the each+push pattern', 'It creates a new array from the block results', 'More concise and avoids manual array management'], concepts: ['map_vs_each', 'functional_style'] },
    { id: 'rb-perf-20', title: 'Refactor Repeated Lookups', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor code that repeatedly computes the same values into a lookup table.', skeleton: `PRODUCTS = [\n  { id: 1, name: \"Widget\", category: \"A\" },\n  { id: 2, name: \"Gadget\", category: \"B\" },\n  { id: 3, name: \"Doohickey\", category: \"A\" },\n  { id: 4, name: \"Thingamajig\", category: \"C\" },\n  { id: 5, name: \"Whatsit\", category: \"B\" },\n]\n\n# Scans the entire array each time\ndef find_product(id)\n  PRODUCTS.find { |p| p[:id] == id }\nend\n\ndef find_by_category(cat)\n  PRODUCTS.select { |p| p[:category] == cat }\nend\n\nputs find_product(3)[:name]\nputs find_by_category(\"B\").map { |p| p[:name] }.inspect`, solution: `PRODUCTS = [\n  { id: 1, name: \"Widget\", category: \"A\" },\n  { id: 2, name: \"Gadget\", category: \"B\" },\n  { id: 3, name: \"Doohickey\", category: \"A\" },\n  { id: 4, name: \"Thingamajig\", category: \"C\" },\n  { id: 5, name: \"Whatsit\", category: \"B\" },\n]\n\n# Build lookup tables once\nPRODUCT_BY_ID = PRODUCTS.each_with_object({}) { |p, h| h[p[:id]] = p }\nPRODUCTS_BY_CATEGORY = PRODUCTS.group_by { |p| p[:category] }\n\ndef find_product(id)\n  PRODUCT_BY_ID[id]\nend\n\ndef find_by_category(cat)\n  PRODUCTS_BY_CATEGORY[cat] || []\nend\n\nputs find_product(3)[:name]\nputs find_by_category(\"B\").map { |p| p[:name] }.inspect`, hints: ['Build a hash index for O(1) lookup by id', 'Use group_by to index by category', 'Trade memory for speed when data is read often'], concepts: ['lookup_table', 'indexing'] },
  ],
};
