import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'rb-capstone',
  title: '50. Ruby Capstone',
  explanation: `## Ruby Capstone Project

This capstone section combines all major Ruby concepts into a cohesive mini-project: a **Task Management System**. You will build classes, modules, use metaprogramming, blocks, procs, file I/O, JSON, error handling, testing, iterators, and design patterns.

### Project Overview

\`\`\`ruby
# A task manager that supports:
# - Creating and managing tasks
# - Persistence via JSON files
# - Filtering and querying with blocks
# - Plugin system via modules and metaprogramming
# - Event hooks for task lifecycle
# - Serialization and deserialization
# - Error handling for invalid operations
\`\`\`

### Core Concepts Used

- **Classes & Inheritance** - Task, Project, User models
- **Modules & Mixins** - Shared behaviors, plugins
- **Blocks & Procs** - Custom filters, callbacks
- **Metaprogramming** - Dynamic attribute definitions
- **File I/O & JSON** - Persistence layer
- **Error Handling** - Custom exceptions
- **Iterators & Enumerable** - Collection traversal
- **Design Patterns** - Observer, Strategy, Command
- **Testing** - Minitest assertions

### Architecture

\`\`\`ruby
module TaskManager
  class Task
    # Core task with title, status, priority
  end

  class Project
    include Enumerable
    # Collection of tasks with iteration
  end

  module Persistence
    # Save/load from JSON files
  end

  module Hooks
    # Lifecycle callbacks (before_save, after_complete, etc.)
  end
end
\`\`\``,
  exercises: [
    { id: 'rb-capstone-1', title: 'Define Task Class', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Create the core Task class with attributes and validation.', skeleton: `class Task\n  attr_reader :id, :title, :status, :priority, :created_at\n\n  VALID_STATUSES = [:pending, :in_progress, :completed, :cancelled]\n  VALID_PRIORITIES = [:low, :medium, :high, :critical]\n\n  def initialize(title:, priority: :medium)\n    @id = object_id\n    @title = title\n    @status = :pending\n    @priority = priority\n    @created_at = Time.now\n    ___\n  end\n\n  def validate!\n    raise ArgumentError, \"Title cannot be empty\" if @title.nil? || @title.strip.empty?\n    raise ArgumentError, \"Invalid priority\" unless VALID_PRIORITIES.include?(@priority)\n  end\n\n  def to_s\n    \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\n  end\nend\n\ntask = Task.new(title: \"Write tests\", priority: :high)\nputs task`, solution: `class Task\n  attr_reader :id, :title, :status, :priority, :created_at\n\n  VALID_STATUSES = [:pending, :in_progress, :completed, :cancelled]\n  VALID_PRIORITIES = [:low, :medium, :high, :critical]\n\n  def initialize(title:, priority: :medium)\n    @id = object_id\n    @title = title\n    @status = :pending\n    @priority = priority\n    @created_at = Time.now\n    validate!\n  end\n\n  def validate!\n    raise ArgumentError, \"Title cannot be empty\" if @title.nil? || @title.strip.empty?\n    raise ArgumentError, \"Invalid priority\" unless VALID_PRIORITIES.include?(@priority)\n  end\n\n  def to_s\n    \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\n  end\nend\n\ntask = Task.new(title: \"Write tests\", priority: :high)\nputs task`, hints: ['Call validate! in initialize to enforce constraints', 'validate! raises ArgumentError for invalid data', 'This ensures no invalid Task objects exist'], concepts: ['class_definition', 'validation'] },
    { id: 'rb-capstone-2', title: 'Task State Transitions', type: 'fill-blank', difficulty: 'beginner', language: 'ruby', goal: 'Add state transition methods with validation to the Task class.', skeleton: `class Task\n  attr_reader :status\n\n  TRANSITIONS = {\n    pending: [:in_progress, :cancelled],\n    in_progress: [:completed, :cancelled],\n    completed: [],\n    cancelled: [],\n  }\n\n  def initialize(title:)\n    @title = title\n    @status = :pending\n  end\n\n  def transition_to(new_status)\n    allowed = TRANSITIONS[@status]\n    unless allowed.___(___)  \n      raise \"Cannot transition from \\\#{@status} to \\\#{new_status}\"\n    end\n    @status = new_status\n  end\n\n  def complete! = transition_to(:completed)\n  def cancel! = transition_to(:cancelled)\n  def start! = transition_to(:in_progress)\nend\n\nt = Task.new(title: \"Test\")\nt.start!\nputs t.status\nt.complete!\nputs t.status`, solution: `class Task\n  attr_reader :status\n\n  TRANSITIONS = {\n    pending: [:in_progress, :cancelled],\n    in_progress: [:completed, :cancelled],\n    completed: [],\n    cancelled: [],\n  }\n\n  def initialize(title:)\n    @title = title\n    @status = :pending\n  end\n\n  def transition_to(new_status)\n    allowed = TRANSITIONS[@status]\n    unless allowed.include?(new_status)\n      raise \"Cannot transition from \\\#{@status} to \\\#{new_status}\"\n    end\n    @status = new_status\n  end\n\n  def complete! = transition_to(:completed)\n  def cancel! = transition_to(:cancelled)\n  def start! = transition_to(:in_progress)\nend\n\nt = Task.new(title: \"Test\")\nt.start!\nputs t.status\nt.complete!\nputs t.status`, hints: ['include? checks if an array contains an element', 'TRANSITIONS maps each status to allowed next statuses', 'This implements a finite state machine'], concepts: ['state_machine', 'transitions'] },
    { id: 'rb-capstone-3', title: 'Enumerable Project', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Make a Project class that includes Enumerable for task iteration.', skeleton: `class Task\n  attr_reader :title, :priority, :status\n  def initialize(title:, priority: :medium)\n    @title = title\n    @priority = priority\n    @status = :pending\n  end\n  def complete! = @status = :completed\n  def to_s = \"[\\\#{@status}] \\\#{@title}\"\nend\n\nclass Project\n  include ___\n  attr_reader :name\n\n  def initialize(name)\n    @name = name\n    @tasks = []\n  end\n\n  def add(task) = @tasks << task\n  def each(&block) = @tasks.each(&block)\n  def size = @tasks.size\nend\n\nproject = Project.new(\"Capstone\")\nproject.add(Task.new(title: \"Design\", priority: :high))\nproject.add(Task.new(title: \"Implement\"))\nproject.add(Task.new(title: \"Test\", priority: :low))\n\nputs project.count\nputs project.map(&:title).inspect\nputs project.select { |t| t.priority == :medium }.map(&:title).inspect`, solution: `class Task\n  attr_reader :title, :priority, :status\n  def initialize(title:, priority: :medium)\n    @title = title\n    @priority = priority\n    @status = :pending\n  end\n  def complete! = @status = :completed\n  def to_s = \"[\\\#{@status}] \\\#{@title}\"\nend\n\nclass Project\n  include Enumerable\n  attr_reader :name\n\n  def initialize(name)\n    @name = name\n    @tasks = []\n  end\n\n  def add(task) = @tasks << task\n  def each(&block) = @tasks.each(&block)\n  def size = @tasks.size\nend\n\nproject = Project.new(\"Capstone\")\nproject.add(Task.new(title: \"Design\", priority: :high))\nproject.add(Task.new(title: \"Implement\"))\nproject.add(Task.new(title: \"Test\", priority: :low))\n\nputs project.count\nputs project.map(&:title).inspect\nputs project.select { |t| t.priority == :medium }.map(&:title).inspect`, hints: ['Include Enumerable and define each', 'Enumerable provides map, select, count, etc.', 'each delegates to the internal tasks array'], concepts: ['enumerable', 'iteration'] },
    { id: 'rb-capstone-4', title: 'Hooks Module', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Implement lifecycle hooks using a module and blocks.', skeleton: `module Hooks\n  def self.included(base)\n    base.extend(ClassMethods)\n  end\n\n  module ClassMethods\n    def before(event, &block)\n      hooks[\"before_\\\#{event}\"] ||= []\n      hooks[\"before_\\\#{event}\"] << block\n    end\n\n    def after(event, &block)\n      hooks[\"after_\\\#{event}\"] ||= []\n      hooks[\"after_\\\#{event}\"] << block\n    end\n\n    def hooks\n      @hooks ||= {}\n    end\n  end\n\n  def run_hooks(timing, event)\n    hooks = self.class.hooks[\"\\\#{timing}_\\\#{event}\"] || []\n    hooks.each { |hook| instance_exec(&___) }\n  end\nend\n\nclass Task\n  include Hooks\n\n  attr_reader :title, :status\n\n  before(:complete) { puts \"About to complete: \\\#{@title}\" }\n  after(:complete) { puts \"Completed: \\\#{@title}\" }\n\n  def initialize(title:)\n    @title = title\n    @status = :pending\n  end\n\n  def complete!\n    run_hooks(:before, :complete)\n    @status = :completed\n    run_hooks(:after, :complete)\n  end\nend\n\nTask.new(title: \"Capstone\").complete!`, solution: `module Hooks\n  def self.included(base)\n    base.extend(ClassMethods)\n  end\n\n  module ClassMethods\n    def before(event, &block)\n      hooks[\"before_\\\#{event}\"] ||= []\n      hooks[\"before_\\\#{event}\"] << block\n    end\n\n    def after(event, &block)\n      hooks[\"after_\\\#{event}\"] ||= []\n      hooks[\"after_\\\#{event}\"] << block\n    end\n\n    def hooks\n      @hooks ||= {}\n    end\n  end\n\n  def run_hooks(timing, event)\n    hooks = self.class.hooks[\"\\\#{timing}_\\\#{event}\"] || []\n    hooks.each { |hook| instance_exec(&hook) }\n  end\nend\n\nclass Task\n  include Hooks\n\n  attr_reader :title, :status\n\n  before(:complete) { puts \"About to complete: \\\#{@title}\" }\n  after(:complete) { puts \"Completed: \\\#{@title}\" }\n\n  def initialize(title:)\n    @title = title\n    @status = :pending\n  end\n\n  def complete!\n    run_hooks(:before, :complete)\n    @status = :completed\n    run_hooks(:after, :complete)\n  end\nend\n\nTask.new(title: \"Capstone\").complete!`, hints: ['instance_exec runs the block in the context of the instance', 'The hook block can access instance variables like @title', 'hook is the local variable holding the proc'], concepts: ['hooks', 'instance_exec', 'callbacks'] },
    { id: 'rb-capstone-5', title: 'JSON Persistence', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Serialize and deserialize tasks to JSON for file persistence.', skeleton: `require 'json'\n\nclass Task\n  attr_reader :title, :status, :priority\n\n  def initialize(title:, priority: :medium, status: :pending)\n    @title = title\n    @priority = priority\n    @status = status\n  end\n\n  def to_h\n    { title: @title, priority: @priority.to_s, status: @status.to_s }\n  end\n\n  def self.from_h(hash)\n    new(\n      title: hash[:title] || hash[\"title\"],\n      priority: (hash[:priority] || hash[\"priority\"]).___,\n      status: (hash[:status] || hash[\"status\"]).to_sym\n    )\n  end\n\n  def to_s = \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\nend\n\ntask = Task.new(title: \"Build\", priority: :high)\njson = JSON.generate(task.to_h)\nputs json\n\nrestored = Task.from_h(JSON.parse(json, symbolize_names: true))\nputs restored`, solution: `require 'json'\n\nclass Task\n  attr_reader :title, :status, :priority\n\n  def initialize(title:, priority: :medium, status: :pending)\n    @title = title\n    @priority = priority\n    @status = status\n  end\n\n  def to_h\n    { title: @title, priority: @priority.to_s, status: @status.to_s }\n  end\n\n  def self.from_h(hash)\n    new(\n      title: hash[:title] || hash[\"title\"],\n      priority: (hash[:priority] || hash[\"priority\"]).to_sym,\n      status: (hash[:status] || hash[\"status\"]).to_sym\n    )\n  end\n\n  def to_s = \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\nend\n\ntask = Task.new(title: \"Build\", priority: :high)\njson = JSON.generate(task.to_h)\nputs json\n\nrestored = Task.from_h(JSON.parse(json, symbolize_names: true))\nputs restored`, hints: ['to_sym converts a string back to a symbol', 'Symbols are not valid JSON, so convert to strings first', 'from_h is a factory method that reconstructs from a hash'], concepts: ['serialization', 'json_persistence'] },
    { id: 'rb-capstone-6', title: 'Custom Error Hierarchy', type: 'fill-blank', difficulty: 'intermediate', language: 'ruby', goal: 'Create a custom exception hierarchy for the task manager.', skeleton: `module TaskManager\n  class Error < StandardError; end\n  class ValidationError < ___; end\n  class TransitionError < Error; end\n  class NotFoundError < Error; end\n\n  class Task\n    def initialize(title:)\n      raise ValidationError, \"Title required\" if title.nil? || title.empty?\n      @title = title\n      @status = :pending\n    end\n\n    def complete!\n      raise TransitionError, \"Already completed\" if @status == :completed\n      @status = :completed\n    end\n  end\nend\n\nbegin\n  TaskManager::Task.new(title: \"\")\nrescue TaskManager::Error => e\n  puts \"\\\#{e.class}: \\\#{e.message}\"\nend`, solution: `module TaskManager\n  class Error < StandardError; end\n  class ValidationError < Error; end\n  class TransitionError < Error; end\n  class NotFoundError < Error; end\n\n  class Task\n    def initialize(title:)\n      raise ValidationError, \"Title required\" if title.nil? || title.empty?\n      @title = title\n      @status = :pending\n    end\n\n    def complete!\n      raise TransitionError, \"Already completed\" if @status == :completed\n      @status = :completed\n    end\n  end\nend\n\nbegin\n  TaskManager::Task.new(title: \"\")\nrescue TaskManager::Error => e\n  puts \"\\\#{e.class}: \\\#{e.message}\"\nend`, hints: ['ValidationError should inherit from Error', 'This lets you catch all TaskManager errors with Error', 'rescue Error catches ValidationError, TransitionError, etc.'], concepts: ['custom_exceptions', 'exception_hierarchy'] },
    { id: 'rb-capstone-7', title: 'Write Dynamic Attributes', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Use metaprogramming to add dynamic attributes to tasks.', skeleton: `# Write a DynamicAttributes module that:\n# - attribute(name, type:, default:) class method\n# - Defines getter and setter methods\n# - Validates type on set\n# - Stores metadata about defined attributes\n# - attributes class method returns all defined attribute names\n`, solution: `module DynamicAttributes\n  def self.included(base)\n    base.extend(ClassMethods)\n    base.instance_variable_set(:@_attributes, {})\n  end\n\n  module ClassMethods\n    def attribute(name, type: Object, default: nil)\n      @_attributes[name] = { type: type, default: default }\n\n      define_method(name) do\n        instance_variable_get(\"@\\\#{name}\") || self.class.instance_variable_get(:@_attributes)[name][:default]\n      end\n\n      define_method(\"\\\#{name}=\") do |value|\n        expected_type = self.class.instance_variable_get(:@_attributes)[name][:type]\n        unless value.is_a?(expected_type)\n          raise TypeError, \"\\\#{name} must be \\\#{expected_type}, got \\\#{value.class}\"\n        end\n        instance_variable_set(\"@\\\#{name}\", value)\n      end\n\n      attr_name = name\n    end\n\n    def attributes\n      @_attributes.keys\n    end\n  end\nend\n\nclass Task\n  include DynamicAttributes\n\n  attribute :title, type: String, default: \"Untitled\"\n  attribute :priority, type: Integer, default: 0\n  attribute :tags, type: Array, default: []\nend\n\nt = Task.new\nputs t.title\nt.title = \"Capstone Project\"\nputs t.title\nt.priority = 5\nputs t.priority\nputs Task.attributes.inspect\n\nbegin\n  t.priority = \"high\"\nrescue TypeError => e\n  puts e.message\nend`, hints: ['define_method creates methods at runtime', 'Use instance_variable_get/set for dynamic instance variables', 'Store attribute metadata in a class-level hash'], concepts: ['metaprogramming', 'dynamic_attributes'] },
    { id: 'rb-capstone-8', title: 'Write Filter DSL', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Write a DSL for filtering tasks using blocks and method chaining.', skeleton: `# Write a TaskQuery class:\n# - where(field, operator, value) for filtering\n# - order_by(field, direction) for sorting\n# - limit(n) to restrict results\n# - execute runs the query and returns results\n# Support operators: :eq, :gt, :lt, :in, :contains\n`, solution: `class Task\n  attr_reader :title, :priority, :status, :created_at\n  PRIORITY_ORDER = { low: 0, medium: 1, high: 2, critical: 3 }\n\n  def initialize(title:, priority: :medium, status: :pending)\n    @title = title\n    @priority = priority\n    @status = status\n    @created_at = Time.now\n  end\n\n  def priority_value = PRIORITY_ORDER[@priority]\n  def to_s = \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\nend\n\nclass TaskQuery\n  def initialize(tasks)\n    @tasks = tasks\n    @filters = []\n    @sort_field = nil\n    @sort_dir = :asc\n    @limit_count = nil\n  end\n\n  def where(field, operator, value)\n    @filters << { field: field, op: operator, value: value }\n    self\n  end\n\n  def order_by(field, direction = :asc)\n    @sort_field = field\n    @sort_dir = direction\n    self\n  end\n\n  def limit(n)\n    @limit_count = n\n    self\n  end\n\n  def execute\n    result = @tasks.select { |task| matches_all?(task) }\n\n    if @sort_field\n      result.sort_by! { |t| t.send(@sort_field) }\n      result.reverse! if @sort_dir == :desc\n    end\n\n    result = result.first(@limit_count) if @limit_count\n    result\n  end\n\n  private\n\n  def matches_all?(task)\n    @filters.all? { |f| matches?(task, f) }\n  end\n\n  def matches?(task, filter)\n    val = task.send(filter[:field])\n    case filter[:op]\n    when :eq then val == filter[:value]\n    when :gt then val > filter[:value]\n    when :lt then val < filter[:value]\n    when :in then filter[:value].include?(val)\n    when :contains then val.to_s.include?(filter[:value].to_s)\n    end\n  end\nend\n\ntasks = [\n  Task.new(title: \"Design UI\", priority: :high),\n  Task.new(title: \"Write tests\", priority: :medium),\n  Task.new(title: \"Deploy\", priority: :critical),\n  Task.new(title: \"Refactor\", priority: :low),\n  Task.new(title: \"Document API\", priority: :medium),\n]\n\nresults = TaskQuery.new(tasks)\n  .where(:priority, :in, [:high, :critical])\n  .order_by(:title)\n  .execute\n\nresults.each { |t| puts t }\n\nputs \"---\"\n\nresults2 = TaskQuery.new(tasks)\n  .where(:title, :contains, \"e\")\n  .limit(2)\n  .execute\n\nresults2.each { |t| puts t }`, hints: ['Use send(field) to access task attributes dynamically', 'Chain methods by returning self', 'execute materializes the query by running all filters'], concepts: ['query_dsl', 'method_chaining', 'strategy_pattern'] },
    { id: 'rb-capstone-9', title: 'Write Observer System', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Implement an observer pattern for task events.', skeleton: `# Write an EventEmitter module:\n# - on(event, &handler) registers a listener\n# - emit(event, *args) notifies all listeners\n# - off(event) removes listeners for an event\n# Use it in a Task class for :created, :completed, :cancelled events\n`, solution: `module EventEmitter\n  def self.included(base)\n    base.instance_variable_set(:@_listeners, {})\n    base.extend(ClassMethods)\n  end\n\n  module ClassMethods\n    def on(event, &handler)\n      @_listeners[event] ||= []\n      @_listeners[event] << handler\n    end\n\n    def off(event)\n      @_listeners.delete(event)\n    end\n\n    def listeners\n      @_listeners\n    end\n  end\n\n  def emit(event, *args)\n    handlers = self.class.listeners[event] || []\n    handlers.each { |h| h.call(self, *args) }\n  end\nend\n\nclass Task\n  include EventEmitter\n\n  attr_reader :title, :status\n\n  on(:created) { |task| puts \"Task created: \\\#{task.title}\" }\n  on(:completed) { |task| puts \"Task completed: \\\#{task.title}\" }\n  on(:cancelled) { |task, reason| puts \"Task cancelled: \\\#{task.title} - \\\#{reason}\" }\n\n  def initialize(title:)\n    @title = title\n    @status = :pending\n    emit(:created)\n  end\n\n  def complete!\n    @status = :completed\n    emit(:completed)\n  end\n\n  def cancel!(reason = \"No reason\")\n    @status = :cancelled\n    emit(:cancelled, reason)\n  end\nend\n\nt = Task.new(title: \"Build capstone\")\nt.complete!\n\nt2 = Task.new(title: \"Optional feature\")\nt2.cancel!(\"Out of scope\")`, hints: ['Store listeners in a class-level hash keyed by event name', 'emit iterates over registered listeners and calls them', 'Handlers receive the emitting object and any extra args'], concepts: ['observer_pattern', 'event_emitter'] },
    { id: 'rb-capstone-10', title: 'Write Plugin System', type: 'write-function', difficulty: 'advanced', language: 'ruby', goal: 'Build a plugin system that extends task functionality via modules.', skeleton: `# Write a PluginSystem module:\n# - register_plugin(mod) includes a module and runs its setup\n# - Plugins can define new methods, hooks, and class methods\n# - Write example plugins: Tagging, DueDates, History\n`, solution: `module PluginSystem\n  def self.included(base)\n    base.extend(ClassMethods)\n    base.instance_variable_set(:@_plugins, [])\n  end\n\n  module ClassMethods\n    def register_plugin(mod)\n      include mod\n      mod.setup(self) if mod.respond_to?(:setup)\n      @_plugins << mod\n    end\n\n    def plugins\n      @_plugins\n    end\n  end\nend\n\nmodule Tagging\n  def self.setup(base)\n    base.define_method(:add_tag) { |tag| (@tags ||= []) << tag; self }\n    base.define_method(:tags) { @tags || [] }\n    base.define_method(:tagged?) { |tag| tags.include?(tag) }\n  end\nend\n\nmodule DueDates\n  def self.setup(base)\n    base.define_method(:due_date=) { |date| @due_date = date }\n    base.define_method(:due_date) { @due_date }\n    base.define_method(:overdue?) { @due_date && @due_date < Time.now }\n  end\nend\n\nmodule History\n  def self.setup(base)\n    base.define_method(:history) { @history || [] }\n    base.define_method(:record) { |entry| (@history ||= []) << { at: Time.now, entry: entry }; self }\n  end\nend\n\nclass Task\n  include PluginSystem\n\n  attr_reader :title\n\n  register_plugin Tagging\n  register_plugin DueDates\n  register_plugin History\n\n  def initialize(title:)\n    @title = title\n  end\nend\n\nt = Task.new(title: \"Capstone\")\nt.add_tag(\"ruby\").add_tag(\"learning\")\nputs t.tags.inspect\nputs t.tagged?(\"ruby\")\n\nt.record(\"Created task\")\nt.record(\"Added tags\")\nputs t.history.map { |h| h[:entry] }.inspect\n\nputs \"Plugins: \\\#{Task.plugins.map(&:name).inspect}\"`, hints: ['Plugins are modules with a setup class method', 'setup receives the host class and can define_method on it', 'register_plugin includes the module and calls setup'], concepts: ['plugin_system', 'metaprogramming', 'modules'] },
    { id: 'rb-capstone-11', title: 'Write File-Based Storage', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write a persistence layer that saves and loads tasks from JSON files.', skeleton: `# Write a Storage class:\n# - initialize(filepath)\n# - save(tasks) writes tasks to JSON file\n# - load returns array of task hashes from file\n# - Handle missing file gracefully\n# - Backup before overwriting\n`, solution: `require 'json'\nrequire 'fileutils'\n\nclass Storage\n  def initialize(filepath)\n    @filepath = filepath\n  end\n\n  def save(tasks)\n    backup if File.exist?(@filepath)\n    data = tasks.map(&:to_h)\n    File.write(@filepath, JSON.pretty_generate(data))\n    data.size\n  rescue IOError, SystemCallError => e\n    raise \"Failed to save: \\\#{e.message}\"\n  end\n\n  def load\n    return [] unless File.exist?(@filepath)\n    content = File.read(@filepath)\n    JSON.parse(content, symbolize_names: true)\n  rescue JSON::ParserError => e\n    raise \"Corrupt data file: \\\#{e.message}\"\n  end\n\n  def exists?\n    File.exist?(@filepath)\n  end\n\n  private\n\n  def backup\n    FileUtils.cp(@filepath, \"\\\#{@filepath}.bak\")\n  end\nend\n\n# Demo with simulated tasks\nclass Task\n  attr_reader :title, :status\n  def initialize(title:, status: :pending)\n    @title = title\n    @status = status\n  end\n  def to_h = { title: @title, status: @status.to_s }\n  def self.from_h(h) = new(title: h[:title], status: h[:status].to_sym)\nend\n\nstorage = Storage.new(\"tasks_demo.json\")\n\ntasks = [\n  Task.new(title: \"Design\"),\n  Task.new(title: \"Build\", status: :in_progress)\n]\n\ncount = storage.save(tasks)\nputs \"Saved \\\#{count} tasks\"\n\nloaded = storage.load\nputs \"Loaded: \\\#{loaded.inspect}\"\n\nrestored = loaded.map { |h| Task.from_h(h) }\nrestored.each { |t| puts \"[\\\#{t.status}] \\\#{t.title}\" }\n\n# Cleanup demo files\nFile.delete(\"tasks_demo.json\") if File.exist?(\"tasks_demo.json\")\nFile.delete(\"tasks_demo.json.bak\") if File.exist?(\"tasks_demo.json.bak\")`, hints: ['File.write and File.read handle the I/O', 'JSON.pretty_generate makes readable output', 'Always handle missing files and corrupt data'], concepts: ['file_io', 'json_persistence', 'error_handling'] },
    { id: 'rb-capstone-12', title: 'Write Testing Suite', type: 'write-function', difficulty: 'intermediate', language: 'ruby', goal: 'Write minitest-style assertions for the Task class.', skeleton: `# Write test methods for Task:\n# - test_creation with valid params\n# - test_validation rejects blank titles\n# - test_state_transitions\n# - test_serialization round-trip\n# Use assert, assert_equal, assert_raises style\n`, solution: `class Task\n  attr_reader :title, :status, :priority\n\n  def initialize(title:, priority: :medium)\n    raise ArgumentError, \"Title required\" if title.nil? || title.strip.empty?\n    @title = title\n    @priority = priority\n    @status = :pending\n  end\n\n  def start! = @status == :pending ? (@status = :in_progress) : (raise \"Invalid transition\")\n  def complete! = @status == :in_progress ? (@status = :completed) : (raise \"Invalid transition\")\n  def to_h = { title: @title, priority: @priority.to_s, status: @status.to_s }\n  def self.from_h(h) = new(title: h[:title], priority: h[:priority].to_sym)\nend\n\n# Simple test framework\ndef assert(condition, msg = \"Assertion failed\")\n  raise msg unless condition\n  print \".\"\nend\n\ndef assert_equal(expected, actual)\n  assert(expected == actual, \"Expected \\\#{expected.inspect}, got \\\#{actual.inspect}\")\nend\n\ndef assert_raises(exception_class)\n  yield\n  raise \"Expected \\\#{exception_class} but nothing was raised\"\nrescue exception_class\n  print \".\"\nend\n\n# Tests\ndef test_creation\n  t = Task.new(title: \"Test\", priority: :high)\n  assert_equal \"Test\", t.title\n  assert_equal :high, t.priority\n  assert_equal :pending, t.status\nend\n\ndef test_validation\n  assert_raises(ArgumentError) { Task.new(title: \"\") }\n  assert_raises(ArgumentError) { Task.new(title: \"   \") }\nend\n\ndef test_state_transitions\n  t = Task.new(title: \"Flow\")\n  assert_equal :pending, t.status\n  t.start!\n  assert_equal :in_progress, t.status\n  t.complete!\n  assert_equal :completed, t.status\n  assert_raises(RuntimeError) { t.complete! }\nend\n\ndef test_serialization\n  original = Task.new(title: \"Serialize\", priority: :high)\n  hash = original.to_h\n  restored = Task.from_h(hash.transform_values(&:to_sym).merge(title: hash[:title]))\n  assert_equal original.title, restored.title\n  assert_equal original.priority, restored.priority\nend\n\ntest_creation\ntest_validation\ntest_state_transitions\ntest_serialization\nputs \"\\nAll tests passed!\"`, hints: ['assert checks a boolean condition', 'assert_raises expects a specific exception from the block', 'Test each behavior in isolation'], concepts: ['testing', 'assertions', 'minitest'] },
    { id: 'rb-capstone-13', title: 'Fix Circular to_h', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix the circular reference in task serialization that causes infinite recursion.', skeleton: `require 'json'\n\nclass Project\n  attr_reader :name, :tasks\n  def initialize(name)\n    @name = name\n    @tasks = []\n  end\n  def add(task)\n    task.instance_variable_set(:@project, self)\n    @tasks << task\n  end\n  # Bug: to_h includes tasks, which include project, which includes tasks...\n  def to_h\n    { name: @name, tasks: @tasks.map(&:to_h) }\n  end\nend\n\nclass Task\n  attr_reader :title\n  def initialize(title:)\n    @title = title\n    @project = nil\n  end\n  # Bug: includes project reference, causing circular serialization\n  def to_h\n    { title: @title, project: @project&.to_h }\n  end\nend\n\np = Project.new(\"Capstone\")\np.add(Task.new(title: \"Design\"))\n# This would cause SystemStackError (stack overflow)\n# puts JSON.generate(p.to_h)`, solution: `require 'json'\n\nclass Project\n  attr_reader :name, :tasks\n  def initialize(name)\n    @name = name\n    @tasks = []\n  end\n  def add(task)\n    task.instance_variable_set(:@project, self)\n    @tasks << task\n  end\n  def to_h\n    { name: @name, tasks: @tasks.map(&:to_h) }\n  end\nend\n\nclass Task\n  attr_reader :title\n  def initialize(title:)\n    @title = title\n    @project = nil\n  end\n  def to_h\n    h = { title: @title }\n    h[:project_name] = @project.name if @project\n    h\n  end\nend\n\np = Project.new(\"Capstone\")\np.add(Task.new(title: \"Design\"))\nputs JSON.generate(p.to_h)`, hints: ['The circular reference is Task -> Project -> Tasks -> Project...', 'Break the cycle by serializing only the project name in Task', 'Use a reference (name/id) instead of the full nested object'], concepts: ['circular_reference', 'serialization'] },
    { id: 'rb-capstone-14', title: 'Fix Block Not Yielded', type: 'fix-bug', difficulty: 'beginner', language: 'ruby', goal: 'Fix the method that accepts a block but never yields to it.', skeleton: `class TaskList\n  def initialize\n    @tasks = []\n  end\n\n  def add(title)\n    task = { title: title, status: :pending }\n    @tasks << task\n    # Bug: block is accepted but never called\n    task\n  end\n\n  def each\n    @tasks.each { |t| t }\n  end\nend\n\nlist = TaskList.new\nlist.add(\"Design\") { |t| puts \"Added: \\\#{t[:title]}\" }\nlist.add(\"Build\") { |t| puts \"Added: \\\#{t[:title]}\" }\n\nlist.each { |t| puts t[:title] }`, solution: `class TaskList\n  def initialize\n    @tasks = []\n  end\n\n  def add(title)\n    task = { title: title, status: :pending }\n    @tasks << task\n    yield task if block_given?\n    task\n  end\n\n  def each\n    @tasks.each { |t| yield t }\n  end\nend\n\nlist = TaskList.new\nlist.add(\"Design\") { |t| puts \"Added: \\\#{t[:title]}\" }\nlist.add(\"Build\") { |t| puts \"Added: \\\#{t[:title]}\" }\n\nlist.each { |t| puts t[:title] }`, hints: ['Use yield to invoke the block passed to the method', 'block_given? checks if a block was provided', 'each must yield each element to its block'], concepts: ['blocks', 'yield', 'block_given'] },
    { id: 'rb-capstone-15', title: 'Fix Memoization Bug', type: 'fix-bug', difficulty: 'intermediate', language: 'ruby', goal: 'Fix memoization that caches nil/false incorrectly.', skeleton: `class Config\n  def initialize(settings = {})\n    @settings = settings\n  end\n\n  def get(key)\n    # Bug: ||= re-evaluates when value is nil or false\n    @cache ||= {}\n    @cache[key] ||= @settings[key]\n  end\nend\n\nc = Config.new({ verbose: false, debug: nil, name: \"App\" })\nputs c.get(:name)\nputs c.get(:verbose).inspect   # Should be false, but keeps re-evaluating\nputs c.get(:debug).inspect     # Should be nil, but keeps re-evaluating`, solution: `class Config\n  def initialize(settings = {})\n    @settings = settings\n  end\n\n  def get(key)\n    @cache ||= {}\n    if @cache.key?(key)\n      @cache[key]\n    else\n      @cache[key] = @settings[key]\n    end\n  end\nend\n\nc = Config.new({ verbose: false, debug: nil, name: \"App\" })\nputs c.get(:name)\nputs c.get(:verbose).inspect\nputs c.get(:debug).inspect`, hints: ['||= treats nil and false as unset, re-evaluating each time', 'Use .key? to check if the key exists in the cache', 'This correctly caches nil and false values'], concepts: ['memoization_gotcha', 'nil_false_caching'] },
    { id: 'rb-capstone-16', title: 'Predict Block Execution', type: 'predict-output', difficulty: 'beginner', language: 'ruby', goal: 'Predict the output of task processing with blocks.', skeleton: `tasks = [\"Design\", \"Build\", \"Test\"]\n\nresults = tasks.map { |t| t.upcase }\n           .select { |t| t.length > 4 }\n           .map { |t| \"[\\\#{t}]\" }\n\nputs results.length\nputs results.first`, solution: `2\n[DESIGN]`, hints: ['map upcases all: DESIGN, BUILD, TEST', 'select keeps length > 4: DESIGN, BUILD', 'BUILD is 5 characters, TEST is 4 (not included). Wait - BUILD is 5, so it stays', 'Final map wraps in brackets'], concepts: ['enumerable_chain', 'blocks'] },
    { id: 'rb-capstone-17', title: 'Predict Module Include', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict method resolution with multiple module includes.', skeleton: `module Logging\n  def action = \"logged\"\nend\n\nmodule Tracking\n  def action = \"tracked\"\nend\n\nclass Task\n  include Logging\n  include Tracking\n\n  def report\n    puts action\n    puts self.class.ancestors[0..3].map(&:name).join(\", \")\n  end\nend\n\nTask.new.report`, solution: `tracked\nTask, Tracking, Logging, Object`, hints: ['The last included module wins in method resolution', 'ancestors shows: Class, then modules in reverse include order', 'Tracking was included last, so its action method is found first'], concepts: ['method_resolution', 'module_include_order'] },
    { id: 'rb-capstone-18', title: 'Predict Proc vs Lambda', type: 'predict-output', difficulty: 'intermediate', language: 'ruby', goal: 'Predict the difference between Proc and Lambda behavior.', skeleton: `def test_proc\n  p = Proc.new { |x, y| \"\\\#{x}-\\\#{y}\" }\n  puts p.call(1)\n  puts p.lambda?\nend\n\ndef test_lambda\n  l = lambda { |x, y| \"\\\#{x}-\\\#{y}\" }\n  begin\n    l.call(1)\n  rescue ArgumentError\n    puts \"wrong args\"\n  end\n  puts l.lambda?\nend\n\ntest_proc\ntest_lambda`, solution: `1-\nfalse\nwrong args\ntrue`, hints: ['Procs are lenient with arguments - missing args become nil', 'Lambdas are strict - wrong argument count raises ArgumentError', 'nil interpolated is empty string, so "1-" not "1-nil"'], concepts: ['proc_vs_lambda', 'arity'] },
    { id: 'rb-capstone-19', title: 'Refactor God Class', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Refactor a monolithic TaskManager class into focused classes with single responsibility.', skeleton: `class TaskManager\n  def initialize\n    @tasks = []\n    @next_id = 1\n  end\n\n  def create(title, priority = :medium)\n    task = { id: @next_id, title: title, priority: priority, status: :pending }\n    @next_id += 1\n    @tasks << task\n    puts \"Created: \\\#{title}\"\n    task\n  end\n\n  def complete(id)\n    task = @tasks.find { |t| t[:id] == id }\n    raise \"Not found\" unless task\n    task[:status] = :completed\n    puts \"Completed: \\\#{task[:title]}\"\n  end\n\n  def save(filepath)\n    require 'json'\n    File.write(filepath, JSON.generate(@tasks))\n    puts \"Saved to \\\#{filepath}\"\n  end\n\n  def find_by_priority(p)\n    @tasks.select { |t| t[:priority] == p }\n  end\n\n  def report\n    @tasks.group_by { |t| t[:status] }.each do |status, tasks|\n      puts \"\\\#{status}: \\\#{tasks.size}\"\n    end\n  end\nend`, solution: `require 'json'\n\nclass Task\n  attr_reader :id, :title, :priority\n  attr_accessor :status\n\n  def initialize(id:, title:, priority: :medium)\n    @id = id\n    @title = title\n    @priority = priority\n    @status = :pending\n  end\n\n  def complete!\n    @status = :completed\n  end\n\n  def to_h = { id: @id, title: @title, priority: @priority, status: @status }\n  def to_s = \"[\\\#{@status}] \\\#{@title} (\\\#{@priority})\"\nend\n\nclass TaskRepository\n  include Enumerable\n\n  def initialize\n    @tasks = []\n    @next_id = 1\n  end\n\n  def add(title, priority: :medium)\n    task = Task.new(id: @next_id, title: title, priority: priority)\n    @next_id += 1\n    @tasks << task\n    task\n  end\n\n  def find(id)\n    @tasks.find { |t| t.id == id } || raise(\"Task \\\#{id} not found\")\n  end\n\n  def by_priority(p) = @tasks.select { |t| t.priority == p }\n  def each(&block) = @tasks.each(&block)\nend\n\nclass TaskStorage\n  def initialize(filepath)\n    @filepath = filepath\n  end\n\n  def save(tasks)\n    data = tasks.map(&:to_h)\n    File.write(@filepath, JSON.pretty_generate(data))\n  end\nend\n\nclass TaskReporter\n  def report(tasks)\n    tasks.group_by(&:status).each do |status, group|\n      puts \"\\\#{status}: \\\#{group.size}\"\n    end\n  end\nend\n\nrepo = TaskRepository.new\nrepo.add(\"Design\", priority: :high)\nrepo.add(\"Build\")\nrepo.add(\"Test\", priority: :low)\n\nrepo.find(1).complete!\n\nTaskReporter.new.report(repo.to_a)\n\nputs \"\\nHigh priority:\"\nrepo.by_priority(:high).each { |t| puts t }`, hints: ['Split into Task (model), TaskRepository (collection), TaskStorage (persistence), TaskReporter (reporting)', 'Each class has a single responsibility', 'TaskRepository includes Enumerable for iteration'], concepts: ['single_responsibility', 'refactoring', 'solid'] },
    { id: 'rb-capstone-20', title: 'Refactor Conditionals to Polymorphism', type: 'refactor', difficulty: 'advanced', language: 'ruby', goal: 'Replace type-checking conditionals with polymorphic classes.', skeleton: `def process_notification(type, data)\n  case type\n  when :email\n    puts \"Sending email to \\\#{data[:to]}: \\\#{data[:subject]}\"\n  when :sms\n    puts \"Sending SMS to \\\#{data[:phone]}: \\\#{data[:message]}\"\n  when :push\n    puts \"Pushing to device \\\#{data[:device_id]}: \\\#{data[:title]}\"\n  when :slack\n    puts \"Posting to \\\#{data[:channel]}: \\\#{data[:text]}\"\n  else\n    raise \"Unknown notification type: \\\#{type}\"\n  end\nend\n\nprocess_notification(:email, { to: \"a@b.com\", subject: \"Hello\" })\nprocess_notification(:sms, { phone: \"555-1234\", message: \"Hi\" })\nprocess_notification(:push, { device_id: \"abc\", title: \"Alert\" })`, solution: `class Notification\n  def deliver\n    raise NotImplementedError, \"Subclass must implement deliver\"\n  end\nend\n\nclass EmailNotification < Notification\n  def initialize(to:, subject:, body: \"\")\n    @to = to\n    @subject = subject\n    @body = body\n  end\n  def deliver = puts \"Sending email to \\\#{@to}: \\\#{@subject}\"\nend\n\nclass SmsNotification < Notification\n  def initialize(phone:, message:)\n    @phone = phone\n    @message = message\n  end\n  def deliver = puts \"Sending SMS to \\\#{@phone}: \\\#{@message}\"\nend\n\nclass PushNotification < Notification\n  def initialize(device_id:, title:)\n    @device_id = device_id\n    @title = title\n  end\n  def deliver = puts \"Pushing to device \\\#{@device_id}: \\\#{@title}\"\nend\n\nclass SlackNotification < Notification\n  def initialize(channel:, text:)\n    @channel = channel\n    @text = text\n  end\n  def deliver = puts \"Posting to \\\#{@channel}: \\\#{@text}\"\nend\n\n# Registry for creating from type symbol\nNOTIFICATION_TYPES = {\n  email: EmailNotification,\n  sms: SmsNotification,\n  push: PushNotification,\n  slack: SlackNotification,\n}\n\ndef send_notification(type, **data)\n  klass = NOTIFICATION_TYPES.fetch(type) { raise \"Unknown type: \\\#{type}\" }\n  klass.new(**data).deliver\nend\n\nsend_notification(:email, to: \"a@b.com\", subject: \"Hello\")\nsend_notification(:sms, phone: \"555-1234\", message: \"Hi\")\nsend_notification(:push, device_id: \"abc\", title: \"Alert\")\nsend_notification(:slack, channel: \"#general\", text: \"Deploy done\")`, hints: ['Each case branch becomes its own class', 'All classes share a common deliver interface', 'A registry maps type symbols to classes for construction'], concepts: ['polymorphism', 'open_closed_principle', 'factory'] },
  ],
};
