import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
	id: 'go-grpc',
	title: '48. gRPC Basics',
	explanation: `## gRPC Basics in Go

gRPC is a high-performance RPC framework using Protocol Buffers for serialization and HTTP/2 for transport.

### Protocol Buffer Definition

\`\`\`protobuf
syntax = "proto3";

package greet;
option go_package = "./greetpb";

message HelloRequest {
    string name = 1;
}

message HelloResponse {
    string message = 1;
}

service GreetService {
    rpc Hello(HelloRequest) returns (HelloResponse);
    rpc HelloStream(HelloRequest) returns (stream HelloResponse);
}
\`\`\`

### Generating Go Code

\`\`\`bash
protoc --go_out=. --go-grpc_out=. greet.proto
\`\`\`

### Implementing a gRPC Server

\`\`\`go
import (
    "context"
    "net"
    "google.golang.org/grpc"
    pb "myapp/greetpb"
)

type server struct {
    pb.UnimplementedGreetServiceServer
}

func (s *server) Hello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloResponse, error) {
    return &pb.HelloResponse{
        Message: "Hello, " + req.GetName() + "!",
    }, nil
}

func main() {
    lis, _ := net.Listen("tcp", ":50051")
    s := grpc.NewServer()
    pb.RegisterGreetServiceServer(s, &server{})
    s.Serve(lis)
}
\`\`\`

### Creating a gRPC Client

\`\`\`go
conn, err := grpc.Dial("localhost:50051", grpc.WithTransportCredentials(insecure.NewCredentials()))
if err != nil {
    log.Fatal(err)
}
defer conn.Close()

client := pb.NewGreetServiceClient(conn)
resp, err := client.Hello(context.Background(), &pb.HelloRequest{Name: "World"})
fmt.Println(resp.GetMessage())
\`\`\`

### Server Streaming

\`\`\`go
func (s *server) HelloStream(req *pb.HelloRequest, stream pb.GreetService_HelloStreamServer) error {
    for i := 0; i < 5; i++ {
        err := stream.Send(&pb.HelloResponse{
            Message: fmt.Sprintf("Hello #%d, %s!", i+1, req.GetName()),
        })
        if err != nil {
            return err
        }
        time.Sleep(time.Second)
    }
    return nil
}
\`\`\`

### Interceptors (Middleware)

\`\`\`go
func loggingInterceptor(
    ctx context.Context,
    req interface{},
    info *grpc.UnaryServerInfo,
    handler grpc.UnaryHandler,
) (interface{}, error) {
    log.Printf("Method: %s", info.FullMethod)
    start := time.Now()
    resp, err := handler(ctx, req)
    log.Printf("Duration: %v, Error: %v", time.Since(start), err)
    return resp, err
}

s := grpc.NewServer(grpc.UnaryInterceptor(loggingInterceptor))
\`\`\`

### Metadata (Headers)

\`\`\`go
import "google.golang.org/grpc/metadata"

// Client: send metadata
md := metadata.Pairs("authorization", "Bearer token123")
ctx := metadata.NewOutgoingContext(context.Background(), md)
resp, err := client.Hello(ctx, req)

// Server: read metadata
md, ok := metadata.FromIncomingContext(ctx)
if ok {
    tokens := md.Get("authorization")
}
\`\`\`
`,
	exercises: [
		{
			id: 'go-grpc-1',
			title: 'Basic Proto Message Struct',
			type: 'fill-blank',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Use generated protobuf message structs correctly.',
			skeleton: `package main

import (
	"fmt"
	pb "myapp/userpb"
)

func main() {
	user := &pb.__BLANK__{
		Id:    1,
		Name:  "Alice",
		Email: "alice@example.com",
	}
	fmt.Printf("User: %s (%s)\\n", user.__BLANK__(), user.GetEmail())
}`,
			solution: `package main

import (
	"fmt"
	pb "myapp/userpb"
)

func main() {
	user := &pb.User{
		Id:    1,
		Name:  "Alice",
		Email: "alice@example.com",
	}
	fmt.Printf("User: %s (%s)\\n", user.GetName(), user.GetEmail())
}`,
			hints: [
				'Proto messages generate Go structs with the same name.',
				'Use getter methods like GetName() for safe nil-aware access.',
				'The struct type matches the message name in the .proto file.',
			],
			concepts: ['grpc', 'protobuf', 'generated-code'],
		},
		{
			id: 'go-grpc-2',
			title: 'Create gRPC Server',
			type: 'fill-blank',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Set up a basic gRPC server with a registered service.',
			skeleton: `package main

import (
	"net"
	"google.golang.org/grpc"
	pb "myapp/greetpb"
)

type greetServer struct {
	pb.UnimplementedGreetServiceServer
}

func main() {
	lis, _ := net.Listen("tcp", ":50051")
	s := grpc.__BLANK__()
	pb.__BLANK__(s, &greetServer{})
	s.__BLANK__(lis)
}`,
			solution: `package main

import (
	"net"
	"google.golang.org/grpc"
	pb "myapp/greetpb"
)

type greetServer struct {
	pb.UnimplementedGreetServiceServer
}

func main() {
	lis, _ := net.Listen("tcp", ":50051")
	s := grpc.NewServer()
	pb.RegisterGreetServiceServer(s, &greetServer{})
	s.Serve(lis)
}`,
			hints: [
				'grpc.NewServer() creates a new gRPC server instance.',
				'RegisterXxxServer is generated by protoc and registers your implementation.',
				'Serve() starts listening on the provided listener.',
			],
			concepts: ['grpc', 'server', 'registration'],
		},
		{
			id: 'go-grpc-3',
			title: 'gRPC Client Dial',
			type: 'fill-blank',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Create a gRPC client connection and make a call.',
			skeleton: `package main

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	pb "myapp/greetpb"
)

func main() {
	conn, err := grpc.__BLANK__("localhost:50051",
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.__BLANK__()

	client := pb.NewGreetServiceClient(conn)
	resp, err := client.Hello(__BLANK__.Background(), &pb.HelloRequest{Name: "World"})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(resp.GetMessage())
}`,
			solution: `package main

import (
	"context"
	"fmt"
	"log"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	pb "myapp/greetpb"
)

func main() {
	conn, err := grpc.Dial("localhost:50051",
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	client := pb.NewGreetServiceClient(conn)
	resp, err := client.Hello(context.Background(), &pb.HelloRequest{Name: "World"})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(resp.GetMessage())
}`,
			hints: [
				'grpc.Dial creates a client connection to the server.',
				'Always defer conn.Close() to clean up resources.',
				'context.Background() provides a non-nil empty context.',
			],
			concepts: ['grpc', 'client', 'dial', 'context'],
		},
		{
			id: 'go-grpc-4',
			title: 'Unary RPC Implementation',
			type: 'fill-blank',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Implement a unary RPC method on a gRPC server.',
			skeleton: `package main

import (
	"context"
	"fmt"
	pb "myapp/mathpb"
)

type mathServer struct {
	pb.UnimplementedMathServiceServer
}

func (s *mathServer) Add(__BLANK__ context.Context, req *pb.AddRequest) (*pb.__BLANK__, error) {
	result := req.GetA() + req.GetB()
	return &pb.AddResponse{Result: result}, __BLANK__
}`,
			solution: `package main

import (
	"context"
	"fmt"
	pb "myapp/mathpb"
)

type mathServer struct {
	pb.UnimplementedMathServiceServer
}

func (s *mathServer) Add(ctx context.Context, req *pb.AddRequest) (*pb.AddResponse, error) {
	result := req.GetA() + req.GetB()
	return &pb.AddResponse{Result: result}, nil
}`,
			hints: [
				'Unary RPCs take a context and request, return response and error.',
				'The response type matches the returns type in the proto definition.',
				'Return nil for error on success.',
			],
			concepts: ['grpc', 'unary-rpc', 'server-implementation'],
		},
		{
			id: 'go-grpc-5',
			title: 'Metadata in Context',
			type: 'fill-blank',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Send and receive gRPC metadata (headers).',
			skeleton: `package main

import (
	"context"
	"fmt"

	"google.golang.org/grpc/metadata"
)

func sendWithAuth(ctx context.Context, token string) context.Context {
	md := metadata.__BLANK__("authorization", "Bearer "+token)
	return metadata.__BLANK__(ctx, md)
}

func extractToken(ctx context.Context) (string, bool) {
	md, ok := metadata.__BLANK__(ctx)
	if !ok {
		return "", false
	}
	values := md.Get("authorization")
	if len(values) == 0 {
		return "", false
	}
	return values[0], true
}`,
			solution: `package main

import (
	"context"
	"fmt"

	"google.golang.org/grpc/metadata"
)

func sendWithAuth(ctx context.Context, token string) context.Context {
	md := metadata.Pairs("authorization", "Bearer "+token)
	return metadata.NewOutgoingContext(ctx, md)
}

func extractToken(ctx context.Context) (string, bool) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return "", false
	}
	values := md.Get("authorization")
	if len(values) == 0 {
		return "", false
	}
	return values[0], true
}`,
			hints: [
				'metadata.Pairs creates metadata from key-value pairs.',
				'NewOutgoingContext attaches metadata to outgoing requests.',
				'FromIncomingContext extracts metadata on the server side.',
			],
			concepts: ['grpc', 'metadata', 'authorization', 'context'],
		},
		{
			id: 'go-grpc-6',
			title: 'gRPC Status Errors',
			type: 'fill-blank',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Return proper gRPC status errors from a server method.',
			skeleton: `package main

import (
	"context"

	pb "myapp/userpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type userServer struct {
	pb.UnimplementedUserServiceServer
	users map[string]*pb.User
}

func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.User, error) {
	if req.GetId() == "" {
		return nil, status.__BLANK__(codes.__BLANK__, "user ID is required")
	}
	user, ok := s.users[req.GetId()]
	if !ok {
		return nil, status.Errorf(codes.__BLANK__, "user %s not found", req.GetId())
	}
	return user, nil
}`,
			solution: `package main

import (
	"context"

	pb "myapp/userpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type userServer struct {
	pb.UnimplementedUserServiceServer
	users map[string]*pb.User
}

func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.User, error) {
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "user ID is required")
	}
	user, ok := s.users[req.GetId()]
	if !ok {
		return nil, status.Errorf(codes.NotFound, "user %s not found", req.GetId())
	}
	return user, nil
}`,
			hints: [
				'status.Errorf creates a gRPC error with a status code and message.',
				'codes.InvalidArgument indicates the client sent bad input.',
				'codes.NotFound indicates the requested resource does not exist.',
			],
			concepts: ['grpc', 'status-codes', 'error-handling'],
		},
		{
			id: 'go-grpc-7',
			title: 'Write a Unary gRPC Server Method',
			type: 'write-function',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Implement a gRPC server method that converts temperature from Celsius to Fahrenheit.',
			skeleton: `package main

import (
	"context"
	pb "myapp/temppb"
)

type tempServer struct {
	pb.UnimplementedTempServiceServer
}

// Implement the Convert method:
// - Takes a TempRequest with a Celsius float64 field
// - Returns a TempResponse with a Fahrenheit float64 field
// - Formula: F = C * 9/5 + 32
`,
			solution: `package main

import (
	"context"
	pb "myapp/temppb"
)

type tempServer struct {
	pb.UnimplementedTempServiceServer
}

func (s *tempServer) Convert(ctx context.Context, req *pb.TempRequest) (*pb.TempResponse, error) {
	fahrenheit := req.GetCelsius()*9.0/5.0 + 32.0
	return &pb.TempResponse{Fahrenheit: fahrenheit}, nil
}`,
			hints: [
				'The method signature follows the unary RPC pattern: (context, *Request) (*Response, error).',
				'Use getter methods to access request fields safely.',
				'Return nil error on success.',
			],
			concepts: ['grpc', 'unary-rpc', 'server-method'],
		},
		{
			id: 'go-grpc-8',
			title: 'Write a Server Streaming RPC',
			type: 'write-function',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Implement a server-streaming RPC that sends countdown messages.',
			skeleton: `package main

import (
	"fmt"
	"time"

	pb "myapp/countdownpb"
)

type countdownServer struct {
	pb.UnimplementedCountdownServiceServer
}

// Implement the Countdown method:
// - Takes a CountdownRequest with a Start int32 field
// - Streams CountdownResponse messages with Number and Message fields
// - Counts down from Start to 0
// - Message is "T-minus {n}" for n > 0, and "Liftoff!" for 0
// - Sends one message per 100ms
`,
			solution: `package main

import (
	"fmt"
	"time"

	pb "myapp/countdownpb"
)

type countdownServer struct {
	pb.UnimplementedCountdownServiceServer
}

func (s *countdownServer) Countdown(req *pb.CountdownRequest, stream pb.CountdownService_CountdownServer) error {
	start := int(req.GetStart())
	for i := start; i >= 0; i-- {
		msg := fmt.Sprintf("T-minus %d", i)
		if i == 0 {
			msg = "Liftoff!"
		}
		err := stream.Send(&pb.CountdownResponse{
			Number:  int32(i),
			Message: msg,
		})
		if err != nil {
			return err
		}
		time.Sleep(100 * time.Millisecond)
	}
	return nil
}`,
			hints: [
				'Server-streaming RPCs take the request and a stream object.',
				'Use stream.Send() to push each response to the client.',
				'Return nil at the end to signal the stream is complete.',
			],
			concepts: ['grpc', 'server-streaming', 'stream-send'],
		},
		{
			id: 'go-grpc-9',
			title: 'Write a Unary Interceptor',
			type: 'write-function',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Write a gRPC unary server interceptor that logs method calls and duration.',
			skeleton: `package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"
)

// Write a unary server interceptor called loggingInterceptor that:
// - Logs the method name (from info.FullMethod) before handling
// - Calls the handler
// - Logs the duration and whether an error occurred
// - Returns the handler's response and error
`,
			solution: `package main

import (
	"context"
	"log"
	"time"

	"google.golang.org/grpc"
)

func loggingInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	log.Printf("RPC call: %s", info.FullMethod)
	start := time.Now()
	resp, err := handler(ctx, req)
	duration := time.Since(start)
	if err != nil {
		log.Printf("RPC %s failed in %v: %v", info.FullMethod, duration, err)
	} else {
		log.Printf("RPC %s completed in %v", info.FullMethod, duration)
	}
	return resp, err
}`,
			hints: [
				'The interceptor signature is: func(ctx, req, info, handler) (resp, err).',
				'info.FullMethod gives the full RPC method path.',
				'Call handler(ctx, req) to invoke the actual RPC method.',
			],
			concepts: ['grpc', 'interceptor', 'middleware', 'logging'],
		},
		{
			id: 'go-grpc-10',
			title: 'Write an Auth Interceptor',
			type: 'write-function',
			difficulty: 'advanced',
			language: 'go',
			goal: 'Write a gRPC interceptor that validates bearer tokens from metadata.',
			skeleton: `package main

import (
	"context"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Write authInterceptor that:
// - Extracts "authorization" from incoming metadata
// - Checks the value starts with "Bearer "
// - Validates the token is not empty after "Bearer "
// - Returns codes.Unauthenticated if any check fails
// - Calls handler if auth succeeds
`,
			solution: `package main

import (
	"context"
	"strings"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

func authInterceptor(
	ctx context.Context,
	req interface{},
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (interface{}, error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, status.Errorf(codes.Unauthenticated, "missing metadata")
	}

	values := md.Get("authorization")
	if len(values) == 0 {
		return nil, status.Errorf(codes.Unauthenticated, "missing authorization header")
	}

	auth := values[0]
	if !strings.HasPrefix(auth, "Bearer ") {
		return nil, status.Errorf(codes.Unauthenticated, "invalid authorization format")
	}

	token := strings.TrimPrefix(auth, "Bearer ")
	if token == "" {
		return nil, status.Errorf(codes.Unauthenticated, "empty bearer token")
	}

	return handler(ctx, req)
}`,
			hints: [
				'Use metadata.FromIncomingContext to get request metadata.',
				'Check for the "authorization" key in the metadata map.',
				'Return status.Errorf with codes.Unauthenticated for auth failures.',
			],
			concepts: ['grpc', 'interceptor', 'authentication', 'metadata'],
		},
		{
			id: 'go-grpc-11',
			title: 'Write Client-Side Streaming',
			type: 'write-function',
			difficulty: 'advanced',
			language: 'go',
			goal: 'Implement a client-streaming RPC that calculates the average of streamed numbers.',
			skeleton: `package main

import (
	"io"

	pb "myapp/mathpb"
)

type mathServer struct {
	pb.UnimplementedMathServiceServer
}

// Implement Average that:
// - Receives a stream of NumberRequest messages (each has a Value float64)
// - When the stream ends, returns AverageResponse with the average
// - Returns 0 if no numbers were sent
`,
			solution: `package main

import (
	"io"

	pb "myapp/mathpb"
)

type mathServer struct {
	pb.UnimplementedMathServiceServer
}

func (s *mathServer) Average(stream pb.MathService_AverageServer) error {
	var sum float64
	var count int

	for {
		req, err := stream.Recv()
		if err == io.EOF {
			avg := 0.0
			if count > 0 {
				avg = sum / float64(count)
			}
			return stream.SendAndClose(&pb.AverageResponse{Average: avg})
		}
		if err != nil {
			return err
		}
		sum += req.GetValue()
		count++
	}
}`,
			hints: [
				'Client-streaming RPCs receive a stream object as the parameter.',
				'Use stream.Recv() in a loop; io.EOF signals the client is done.',
				'stream.SendAndClose sends the final response and closes the stream.',
			],
			concepts: ['grpc', 'client-streaming', 'recv', 'send-and-close'],
		},
		{
			id: 'go-grpc-12',
			title: 'Write Bidirectional Streaming',
			type: 'write-function',
			difficulty: 'advanced',
			language: 'go',
			goal: 'Implement a bidirectional streaming RPC that echoes messages back in uppercase.',
			skeleton: `package main

import (
	"io"
	"strings"

	pb "myapp/echopb"
)

type echoServer struct {
	pb.UnimplementedEchoServiceServer
}

// Implement EchoUpper that:
// - Receives EchoRequest messages with a Text field
// - For each message, sends back EchoResponse with Text in uppercase
// - Continues until the client closes the stream
`,
			solution: `package main

import (
	"io"
	"strings"

	pb "myapp/echopb"
)

type echoServer struct {
	pb.UnimplementedEchoServiceServer
}

func (s *echoServer) EchoUpper(stream pb.EchoService_EchoUpperServer) error {
	for {
		req, err := stream.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		resp := &pb.EchoResponse{
			Text: strings.ToUpper(req.GetText()),
		}
		if err := stream.Send(resp); err != nil {
			return err
		}
	}
}`,
			hints: [
				'Bidirectional streaming uses both stream.Recv() and stream.Send().',
				'Loop until Recv returns io.EOF.',
				'strings.ToUpper converts a string to uppercase.',
			],
			concepts: ['grpc', 'bidirectional-streaming', 'echo'],
		},
		{
			id: 'go-grpc-13',
			title: 'Fix Missing Unimplemented Embedding',
			type: 'fix-bug',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Fix the server that fails to compile because it does not embed the unimplemented server.',
			skeleton: `package main

import (
	"context"
	"net"

	"google.golang.org/grpc"
	pb "myapp/greetpb"
)

type greetServer struct{}

func (s *greetServer) Hello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloResponse, error) {
	return &pb.HelloResponse{Message: "Hello, " + req.GetName()}, nil
}

func main() {
	lis, _ := net.Listen("tcp", ":50051")
	s := grpc.NewServer()
	pb.RegisterGreetServiceServer(s, &greetServer{})
	s.Serve(lis)
}`,
			solution: `package main

import (
	"context"
	"net"

	"google.golang.org/grpc"
	pb "myapp/greetpb"
)

type greetServer struct {
	pb.UnimplementedGreetServiceServer
}

func (s *greetServer) Hello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloResponse, error) {
	return &pb.HelloResponse{Message: "Hello, " + req.GetName()}, nil
}

func main() {
	lis, _ := net.Listen("tcp", ":50051")
	s := grpc.NewServer()
	pb.RegisterGreetServiceServer(s, &greetServer{})
	s.Serve(lis)
}`,
			hints: [
				'gRPC generated code requires embedding the Unimplemented server struct.',
				'This ensures forward compatibility when new methods are added.',
				'Embed pb.UnimplementedXxxServer in your server struct.',
			],
			concepts: ['grpc', 'unimplemented-server', 'embedding', 'debugging'],
		},
		{
			id: 'go-grpc-14',
			title: 'Fix Stream Error Handling',
			type: 'fix-bug',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Fix the streaming RPC that panics when the client disconnects.',
			skeleton: `package main

import (
	pb "myapp/feedpb"
)

type feedServer struct {
	pb.UnimplementedFeedServiceServer
}

func (s *feedServer) Subscribe(req *pb.SubscribeRequest, stream pb.FeedService_SubscribeServer) error {
	events := getEventChannel(req.GetTopic())
	for event := range events {
		stream.Send(&pb.Event{Data: event})
	}
	return nil
}`,
			solution: `package main

import (
	pb "myapp/feedpb"
)

type feedServer struct {
	pb.UnimplementedFeedServiceServer
}

func (s *feedServer) Subscribe(req *pb.SubscribeRequest, stream pb.FeedService_SubscribeServer) error {
	events := getEventChannel(req.GetTopic())
	for event := range events {
		if err := stream.Send(&pb.Event{Data: event}); err != nil {
			return err
		}
		if stream.Context().Err() != nil {
			return stream.Context().Err()
		}
	}
	return nil
}`,
			hints: [
				'stream.Send can fail if the client disconnects.',
				'Always check the error returned by stream.Send.',
				'Check stream.Context().Err() to detect client cancellation.',
			],
			concepts: ['grpc', 'streaming', 'error-handling', 'context-cancellation'],
		},
		{
			id: 'go-grpc-15',
			title: 'Fix Deadline Handling',
			type: 'fix-bug',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Fix the server method that ignores client deadlines.',
			skeleton: `package main

import (
	"context"
	"time"

	pb "myapp/searchpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type searchServer struct {
	pb.UnimplementedSearchServiceServer
}

func (s *searchServer) Search(ctx context.Context, req *pb.SearchRequest) (*pb.SearchResponse, error) {
	results := make([]string, 0)

	for i := 0; i < 100; i++ {
		time.Sleep(50 * time.Millisecond)
		results = append(results, searchShard(i, req.GetQuery()))
	}

	return &pb.SearchResponse{Results: results}, nil
}`,
			solution: `package main

import (
	"context"
	"time"

	pb "myapp/searchpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type searchServer struct {
	pb.UnimplementedSearchServiceServer
}

func (s *searchServer) Search(ctx context.Context, req *pb.SearchRequest) (*pb.SearchResponse, error) {
	results := make([]string, 0)

	for i := 0; i < 100; i++ {
		select {
		case <-ctx.Done():
			return nil, status.Errorf(codes.DeadlineExceeded, "search cancelled: %v", ctx.Err())
		default:
		}
		time.Sleep(50 * time.Millisecond)
		results = append(results, searchShard(i, req.GetQuery()))
	}

	return &pb.SearchResponse{Results: results}, nil
}`,
			hints: [
				'Check ctx.Done() in long-running loops to respect client deadlines.',
				'Use a select with ctx.Done() to detect cancellation.',
				'Return codes.DeadlineExceeded when the context is cancelled.',
			],
			concepts: ['grpc', 'deadlines', 'context', 'cancellation'],
		},
		{
			id: 'go-grpc-16',
			title: 'Predict gRPC Status Code',
			type: 'predict-output',
			difficulty: 'beginner',
			language: 'go',
			goal: 'Predict which gRPC status code is returned for a given error.',
			skeleton: `package main

import (
	"fmt"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

func main() {
	err := status.Errorf(codes.NotFound, "user %s not found", "alice")
	st, _ := status.FromError(err)
	fmt.Println(st.Code())
	fmt.Println(st.Message())
}`,
			solution: `NotFound
user alice not found`,
			hints: [
				'status.FromError extracts the status from a gRPC error.',
				'Code() returns the gRPC status code.',
				'Message() returns the error message string.',
			],
			concepts: ['grpc', 'status-codes', 'error-inspection'],
		},
		{
			id: 'go-grpc-17',
			title: 'Predict Metadata Behavior',
			type: 'predict-output',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Predict how gRPC metadata key-value pairs are handled.',
			skeleton: `package main

import (
	"fmt"
	"google.golang.org/grpc/metadata"
)

func main() {
	md := metadata.Pairs(
		"key", "value1",
		"key", "value2",
		"other", "value3",
	)
	fmt.Println(len(md.Get("key")))
	fmt.Println(md.Get("key")[0])
	fmt.Println(md.Get("key")[1])
	fmt.Println(len(md.Get("missing")))
}`,
			solution: `2
value1
value2
0`,
			hints: [
				'Metadata allows duplicate keys, storing all values.',
				'Get returns a slice of all values for the given key.',
				'Getting a missing key returns an empty slice (length 0).',
			],
			concepts: ['grpc', 'metadata', 'key-value-pairs'],
		},
		{
			id: 'go-grpc-18',
			title: 'Predict Stream Completion',
			type: 'predict-output',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Predict the output of a gRPC client consuming a server stream.',
			skeleton: `package main

import "fmt"

// Simulating a gRPC server stream response sequence:
// Server sends: {Value: 10}, {Value: 20}, {Value: 30}, then closes
// Client code:
func main() {
	values := []int{10, 20, 30}
	sum := 0
	count := 0
	for _, v := range values {
		sum += v
		count++
	}
	fmt.Printf("Received %d messages\\n", count)
	fmt.Printf("Sum: %d\\n", sum)
	fmt.Printf("Average: %d\\n", sum/count)
}`,
			solution: `Received 3 messages
Sum: 60
Average: 20`,
			hints: [
				'The client receives 3 messages with values 10, 20, and 30.',
				'Sum is 10 + 20 + 30 = 60.',
				'Average is 60 / 3 = 20 (integer division).',
			],
			concepts: ['grpc', 'server-streaming', 'client-consumption'],
		},
		{
			id: 'go-grpc-19',
			title: 'Refactor Repeated Error Handling',
			type: 'refactor',
			difficulty: 'intermediate',
			language: 'go',
			goal: 'Refactor repetitive gRPC error handling into reusable helpers.',
			skeleton: `package main

import (
	"context"
	"database/sql"

	pb "myapp/userpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type userServer struct {
	pb.UnimplementedUserServiceServer
	db *sql.DB
}

func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.UserResponse, error) {
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "id is required")
	}
	var name, email string
	err := s.db.QueryRowContext(ctx, "SELECT name, email FROM users WHERE id = ?", req.GetId()).Scan(&name, &email)
	if err == sql.ErrNoRows {
		return nil, status.Errorf(codes.NotFound, "user %s not found", req.GetId())
	}
	if err != nil {
		return nil, status.Errorf(codes.Internal, "database error: %v", err)
	}
	return &pb.UserResponse{Name: name, Email: email}, nil
}

func (s *userServer) GetOrder(ctx context.Context, req *pb.GetOrderRequest) (*pb.OrderResponse, error) {
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "id is required")
	}
	var total float64
	var itemStatus string
	err := s.db.QueryRowContext(ctx, "SELECT total, status FROM orders WHERE id = ?", req.GetId()).Scan(&total, &itemStatus)
	if err == sql.ErrNoRows {
		return nil, status.Errorf(codes.NotFound, "order %s not found", req.GetId())
	}
	if err != nil {
		return nil, status.Errorf(codes.Internal, "database error: %v", err)
	}
	return &pb.OrderResponse{Total: total, Status: itemStatus}, nil
}

func (s *userServer) GetProduct(ctx context.Context, req *pb.GetProductRequest) (*pb.ProductResponse, error) {
	if req.GetId() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "id is required")
	}
	var name string
	var price float64
	err := s.db.QueryRowContext(ctx, "SELECT name, price FROM products WHERE id = ?", req.GetId()).Scan(&name, &price)
	if err == sql.ErrNoRows {
		return nil, status.Errorf(codes.NotFound, "product %s not found", req.GetId())
	}
	if err != nil {
		return nil, status.Errorf(codes.Internal, "database error: %v", err)
	}
	return &pb.ProductResponse{Name: name, Price: price}, nil
}`,
			solution: `package main

import (
	"context"
	"database/sql"

	pb "myapp/userpb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type userServer struct {
	pb.UnimplementedUserServiceServer
	db *sql.DB
}

func requireID(id string) error {
	if id == "" {
		return status.Errorf(codes.InvalidArgument, "id is required")
	}
	return nil
}

func handleDBError(err error, resource, id string) error {
	if err == sql.ErrNoRows {
		return status.Errorf(codes.NotFound, "%s %s not found", resource, id)
	}
	return status.Errorf(codes.Internal, "database error: %v", err)
}

func (s *userServer) GetUser(ctx context.Context, req *pb.GetUserRequest) (*pb.UserResponse, error) {
	if err := requireID(req.GetId()); err != nil {
		return nil, err
	}
	var name, email string
	err := s.db.QueryRowContext(ctx, "SELECT name, email FROM users WHERE id = ?", req.GetId()).Scan(&name, &email)
	if err != nil {
		return nil, handleDBError(err, "user", req.GetId())
	}
	return &pb.UserResponse{Name: name, Email: email}, nil
}

func (s *userServer) GetOrder(ctx context.Context, req *pb.GetOrderRequest) (*pb.OrderResponse, error) {
	if err := requireID(req.GetId()); err != nil {
		return nil, err
	}
	var total float64
	var itemStatus string
	err := s.db.QueryRowContext(ctx, "SELECT total, status FROM orders WHERE id = ?", req.GetId()).Scan(&total, &itemStatus)
	if err != nil {
		return nil, handleDBError(err, "order", req.GetId())
	}
	return &pb.OrderResponse{Total: total, Status: itemStatus}, nil
}

func (s *userServer) GetProduct(ctx context.Context, req *pb.GetProductRequest) (*pb.ProductResponse, error) {
	if err := requireID(req.GetId()); err != nil {
		return nil, err
	}
	var name string
	var price float64
	err := s.db.QueryRowContext(ctx, "SELECT name, price FROM products WHERE id = ?", req.GetId()).Scan(&name, &price)
	if err != nil {
		return nil, handleDBError(err, "product", req.GetId())
	}
	return &pb.ProductResponse{Name: name, Price: price}, nil
}`,
			hints: [
				'Extract requireID to validate non-empty IDs consistently.',
				'Extract handleDBError to map sql errors to gRPC status codes.',
				'Both helpers return gRPC-compatible errors directly.',
			],
			concepts: ['grpc', 'refactoring', 'error-helpers', 'dry-principle'],
		},
		{
			id: 'go-grpc-20',
			title: 'Refactor Inline Server to Clean Architecture',
			type: 'refactor',
			difficulty: 'advanced',
			language: 'go',
			goal: 'Refactor a monolithic gRPC server setup into clean, testable components.',
			skeleton: `package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"time"

	"google.golang.org/grpc"
	pb "myapp/todopb"
)

var todos = make(map[string]*pb.Todo)
var nextID = 1

type server struct {
	pb.UnimplementedTodoServiceServer
}

func (s *server) Create(ctx context.Context, req *pb.CreateRequest) (*pb.Todo, error) {
	id := fmt.Sprintf("todo-%d", nextID)
	nextID++
	todo := &pb.Todo{
		Id:        id,
		Title:     req.GetTitle(),
		Done:      false,
		CreatedAt: time.Now().Unix(),
	}
	todos[id] = todo
	log.Printf("Created todo: %s", id)
	return todo, nil
}

func (s *server) Get(ctx context.Context, req *pb.GetRequest) (*pb.Todo, error) {
	todo, ok := todos[req.GetId()]
	if !ok {
		return nil, fmt.Errorf("not found")
	}
	log.Printf("Got todo: %s", req.GetId())
	return todo, nil
}

func (s *server) Complete(ctx context.Context, req *pb.CompleteRequest) (*pb.Todo, error) {
	todo, ok := todos[req.GetId()]
	if !ok {
		return nil, fmt.Errorf("not found")
	}
	todo.Done = true
	log.Printf("Completed todo: %s", req.GetId())
	return todo, nil
}

func main() {
	lis, _ := net.Listen("tcp", ":50051")
	s := grpc.NewServer()
	pb.RegisterTodoServiceServer(s, &server{})
	log.Println("Server starting on :50051")
	s.Serve(lis)
}`,
			solution: `package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"sync"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	pb "myapp/todopb"
)

// Store interface for testability
type TodoStore interface {
	Create(title string) *pb.Todo
	Get(id string) (*pb.Todo, bool)
	Complete(id string) (*pb.Todo, bool)
}

// In-memory implementation
type inMemoryStore struct {
	mu     sync.RWMutex
	todos  map[string]*pb.Todo
	nextID int
}

func newInMemoryStore() *inMemoryStore {
	return &inMemoryStore{
		todos:  make(map[string]*pb.Todo),
		nextID: 1,
	}
}

func (s *inMemoryStore) Create(title string) *pb.Todo {
	s.mu.Lock()
	defer s.mu.Unlock()
	id := fmt.Sprintf("todo-%d", s.nextID)
	s.nextID++
	todo := &pb.Todo{
		Id:        id,
		Title:     title,
		Done:      false,
		CreatedAt: time.Now().Unix(),
	}
	s.todos[id] = todo
	return todo
}

func (s *inMemoryStore) Get(id string) (*pb.Todo, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	todo, ok := s.todos[id]
	return todo, ok
}

func (s *inMemoryStore) Complete(id string) (*pb.Todo, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	todo, ok := s.todos[id]
	if ok {
		todo.Done = true
	}
	return todo, ok
}

// gRPC server with injected store
type todoServer struct {
	pb.UnimplementedTodoServiceServer
	store TodoStore
}

func newTodoServer(store TodoStore) *todoServer {
	return &todoServer{store: store}
}

func (s *todoServer) Create(ctx context.Context, req *pb.CreateRequest) (*pb.Todo, error) {
	if req.GetTitle() == "" {
		return nil, status.Errorf(codes.InvalidArgument, "title is required")
	}
	todo := s.store.Create(req.GetTitle())
	return todo, nil
}

func (s *todoServer) Get(ctx context.Context, req *pb.GetRequest) (*pb.Todo, error) {
	todo, ok := s.store.Get(req.GetId())
	if !ok {
		return nil, status.Errorf(codes.NotFound, "todo %s not found", req.GetId())
	}
	return todo, nil
}

func (s *todoServer) Complete(ctx context.Context, req *pb.CompleteRequest) (*pb.Todo, error) {
	todo, ok := s.store.Complete(req.GetId())
	if !ok {
		return nil, status.Errorf(codes.NotFound, "todo %s not found", req.GetId())
	}
	return todo, nil
}

func main() {
	store := newInMemoryStore()
	srv := newTodoServer(store)

	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}

	s := grpc.NewServer()
	pb.RegisterTodoServiceServer(s, srv)
	log.Println("Server starting on :50051")
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}`,
			hints: [
				'Extract storage into an interface for testability.',
				'Add mutex protection for concurrent access to shared state.',
				'Use proper gRPC status codes instead of plain errors.',
			],
			concepts: ['grpc', 'clean-architecture', 'dependency-injection', 'refactoring'],
		},
	],
};
