import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-var',
  title: '01. Variables',
  explanation: `## Variables in PHP\n\nIn PHP, all variables start with a dollar sign (\`$\`) followed by the variable name. PHP is dynamically typed, so you don't need to declare a variable's type before using it.\n\n\`\`\`php\n$name = "Alice";\n$age = 30;\n$pi = 3.14;\n$isAdmin = true;\n\`\`\`\n\n### Assignment\n\nVariables are assigned using the \`=\` operator. PHP also supports assignment by reference using \`&\`:\n\n\`\`\`php\n$a = 10;\n$b = &$a; // $b is a reference to $a\n$b = 20;  // now $a is also 20\n\`\`\`\n\n### Inspecting Variables\n\n- \`var_dump($var)\` shows type and value\n- \`gettype($var)\` returns the type as a string\n- \`isset($var)\` checks if a variable is set and not null\n- \`unset($var)\` destroys a variable\n\n\`\`\`php\n$x = 42;\nvar_dump($x);    // int(42)\necho gettype($x); // integer\n\`\`\`\n\n### Variable Variables\n\nPHP supports variable variables -- a variable whose name is stored in another variable:\n\n\`\`\`php\n$varName = "greeting";\n$$varName = "Hello!"; // creates $greeting = "Hello!"\necho $greeting;       // Hello!\n\`\`\``,
  exercises: [
    {
      id: 'php-var-1',
      title: 'Declare a String Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Declare a variable named $name and assign it the string "Alice".',
      skeleton: `<?php\n___ = "Alice";\necho \$name;`,
      solution: `<?php\n\$name = "Alice";\necho \$name;`,
      hints: ['PHP variables start with a dollar sign ($)', 'Use the assignment operator =', 'The variable name is $name'],
      concepts: ['variables', 'string-assignment'],
    },
    {
      id: 'php-var-2',
      title: 'Assign an Integer',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Assign the integer 42 to the variable $answer.',
      skeleton: `<?php\n\$answer = ___;\necho \$answer;`,
      solution: `<?php\n\$answer = 42;\necho \$answer;`,
      hints: ['Integers in PHP do not need quotes', 'Just type the number directly', 'No type declaration needed'],
      concepts: ['variables', 'integer-assignment'],
    },
    {
      id: 'php-var-3',
      title: 'Check Variable Type',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use gettype() to print the type of $value.',
      skeleton: `<?php\n\$value = 3.14;\necho ___(\$value);`,
      solution: `<?php\n\$value = 3.14;\necho gettype(\$value);`,
      hints: ['The function that returns a type as a string is gettype()', 'Pass $value as the argument', 'This will output "double"'],
      concepts: ['gettype', 'type-inspection'],
    },
    {
      id: 'php-var-4',
      title: 'Use var_dump',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use var_dump() to inspect the variable $items.',
      skeleton: `<?php\n\$items = [1, 2, 3];\n___(\$items);`,
      solution: `<?php\n\$items = [1, 2, 3];\nvar_dump(\$items);`,
      hints: ['var_dump shows both type and value', 'It takes one or more arguments', 'Call var_dump with $items'],
      concepts: ['var_dump', 'debugging'],
    },
    {
      id: 'php-var-5',
      title: 'Check if Variable is Set',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use isset() to check whether $username is defined and not null.',
      skeleton: `<?php\n\$username = "bob";\nif (___(\$username)) {\n    echo "Username is set";\n}`,
      solution: `<?php\n\$username = "bob";\nif (isset(\$username)) {\n    echo "Username is set";\n}`,
      hints: ['isset() returns true if a variable exists and is not null', 'Pass $username as the argument', 'isset is a language construct, not a regular function'],
      concepts: ['isset', 'variable-checking'],
    },
    {
      id: 'php-var-6',
      title: 'Unset a Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Destroy the variable $temp using unset().',
      skeleton: `<?php\n\$temp = "temporary";\n___(\$temp);\nvar_dump(isset(\$temp)); // bool(false)`,
      solution: `<?php\n\$temp = "temporary";\nunset(\$temp);\nvar_dump(isset(\$temp)); // bool(false)`,
      hints: ['unset() destroys a variable', 'After unset, isset will return false', 'Pass $temp to unset()'],
      concepts: ['unset', 'variable-destruction'],
    },
    {
      id: 'php-var-7',
      title: 'Write a Swap Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function swap() that takes two variables by reference and swaps their values.',
      skeleton: `<?php\n// Write a function swap(&$a, &$b) that swaps the values of $a and $b\n`,
      solution: `<?php\nfunction swap(&\$a, &\$b) {\n    \$temp = \$a;\n    \$a = \$b;\n    \$b = \$temp;\n}`,
      hints: ['Use & before parameter names to pass by reference', 'Store one value in a temporary variable', 'Assign the second to the first, then the temp to the second'],
      concepts: ['pass-by-reference', 'functions', 'swap'],
    },
    {
      id: 'php-var-8',
      title: 'Write a Type Checker',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function describeVar($var) that returns a string like "Type: integer, Value: 42" using gettype().',
      skeleton: `<?php\n// Write function describeVar($var) that returns "Type: <type>, Value: <value>"\n`,
      solution: `<?php\nfunction describeVar(\$var) {\n    return "Type: " . gettype(\$var) . ", Value: " . \$var;\n}`,
      hints: ['Use gettype($var) to get the type string', 'Concatenate strings with the dot (.) operator', 'Return the formatted string'],
      concepts: ['gettype', 'string-concatenation', 'functions'],
    },
    {
      id: 'php-var-9',
      title: 'Write a Variable Existence Checker',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function safeGet(&$var, $default) that returns $var if it is set, or $default otherwise.',
      skeleton: `<?php\n// Write function safeGet(&$var, $default) that returns $var if set, otherwise $default\n`,
      solution: `<?php\nfunction safeGet(&\$var, \$default) {\n    return isset(\$var) ? \$var : \$default;\n}`,
      hints: ['Use isset() to check if $var is set', 'Use the ternary operator for a concise return', 'The & reference allows checking undefined variables without errors'],
      concepts: ['isset', 'ternary-operator', 'default-values'],
    },
    {
      id: 'php-var-10',
      title: 'Write a Multi-Assignment Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function initVars() that returns an associative array with keys "name" => "Unknown", "age" => 0, "active" => false.',
      skeleton: `<?php\n// Write function initVars() that returns an associative array with default values\n`,
      solution: `<?php\nfunction initVars() {\n    return [\n        "name" => "Unknown",\n        "age" => 0,\n        "active" => false,\n    ];\n}`,
      hints: ['Return an array with => syntax', 'Use square brackets [] for the array literal', 'Include all three key-value pairs'],
      concepts: ['associative-arrays', 'functions', 'return-values'],
    },
    {
      id: 'php-var-11',
      title: 'Write a Variable Variables Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function createVar($name, $value) that uses variable variables to create a variable with the given name and value, then returns it.',
      skeleton: `<?php\n// Write function createVar($name, $value) using variable variables ($$name)\n`,
      solution: `<?php\nfunction createVar(\$name, \$value) {\n    \$\$name = \$value;\n    return \$\$name;\n}`,
      hints: ['Use $$name to create a variable whose name is the value of $name', 'Assign $value to $$name', 'Return $$name'],
      concepts: ['variable-variables', 'dynamic-naming'],
    },
    {
      id: 'php-var-12',
      title: 'Write a Reference Counter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function incrementAll(&$a, &$b, &$c) that increments all three variables by 1.',
      skeleton: `<?php\n// Write function incrementAll(&$a, &$b, &$c) that adds 1 to each variable\n`,
      solution: `<?php\nfunction incrementAll(&\$a, &\$b, &\$c) {\n    \$a++;\n    \$b++;\n    \$c++;\n}`,
      hints: ['All parameters must be passed by reference with &', 'Use the ++ increment operator', 'No return value needed since we modify by reference'],
      concepts: ['pass-by-reference', 'increment-operator'],
    },
    {
      id: 'php-var-13',
      title: 'Fix the Missing Dollar Sign',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the bug: the variable is missing its $ prefix.',
      skeleton: `<?php\nname = "Alice";\necho \$name;`,
      solution: `<?php\n\$name = "Alice";\necho \$name;`,
      hints: ['All PHP variables must start with $', 'Look at the assignment line', 'name should be $name'],
      concepts: ['variables', 'syntax-errors'],
    },
    {
      id: 'php-var-14',
      title: 'Fix the Reference Assignment',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code so that $b is a reference to $a (changing $b should change $a).',
      skeleton: `<?php\n\$a = 10;\n\$b = \$a;\n\$b = 20;\necho \$a; // Should print 20`,
      solution: `<?php\n\$a = 10;\n\$b = &\$a;\n\$b = 20;\necho \$a; // Should print 20`,
      hints: ['To create a reference, use the & operator', 'Change $b = $a to $b = &$a', 'Without &, $b gets a copy, not a reference'],
      concepts: ['references', 'pass-by-reference'],
    },
    {
      id: 'php-var-15',
      title: 'Fix the isset Check',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the code: it should check if $user is set before echoing, but it currently causes an error.',
      skeleton: `<?php\nif (isset \$user) {\n    echo \$user;\n} else {\n    echo "No user";\n}`,
      solution: `<?php\nif (isset(\$user)) {\n    echo \$user;\n} else {\n    echo "No user";\n}`,
      hints: ['isset requires parentheses around its argument', 'It is a language construct but still needs ()', 'Change isset $user to isset($user)'],
      concepts: ['isset', 'syntax-errors'],
    },
    {
      id: 'php-var-16',
      title: 'Predict: Variable Assignment',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$x = 5;\n\$y = \$x;\n\$x = 10;\necho \$y;`,
      solution: `5`,
      hints: ['$y = $x copies the value, not a reference', '$y gets the value 5 at the time of assignment', 'Changing $x afterwards does not affect $y'],
      concepts: ['assignment', 'copy-by-value'],
    },
    {
      id: 'php-var-17',
      title: 'Predict: Reference Assignment',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$a = "hello";\n\$b = &\$a;\n\$b = "world";\necho \$a;`,
      solution: `world`,
      hints: ['$b = &$a makes $b a reference to $a', 'Changing $b also changes $a', 'The final value of $a is "world"'],
      concepts: ['references', 'assignment'],
    },
    {
      id: 'php-var-18',
      title: 'Predict: Variable Variables',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$var = "message";\n\$\$var = "Hello!";\necho \$message;`,
      solution: `Hello!`,
      hints: ['$$var creates a variable named by the value of $var', '$var is "message", so $$var creates $message', '$message is assigned "Hello!"'],
      concepts: ['variable-variables', 'dynamic-naming'],
    },
    {
      id: 'php-var-19',
      title: 'Refactor: Consolidate Variable Declarations',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor to use a single associative array $config instead of separate variables.',
      skeleton: `<?php\n\$host = "localhost";\n\$port = 3306;\n\$dbname = "myapp";\n\necho \$host . ":" . \$port . "/" . \$dbname;`,
      solution: `<?php\n\$config = [\n    "host" => "localhost",\n    "port" => 3306,\n    "dbname" => "myapp",\n];\n\necho \$config["host"] . ":" . \$config["port"] . "/" . \$config["dbname"];`,
      hints: ['Group related variables into an associative array', 'Use the => syntax for key-value pairs', 'Access values with $config["key"]'],
      concepts: ['associative-arrays', 'code-organization'],
    },
    {
      id: 'php-var-20',
      title: 'Refactor: Replace Repeated isset Checks',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the repeated isset checks into a helper function getOrDefault(&$var, $default).',
      skeleton: `<?php\n\$name = isset(\$_GET["name"]) ? \$_GET["name"] : "Guest";\n\$age = isset(\$_GET["age"]) ? \$_GET["age"] : 0;\n\$role = isset(\$_GET["role"]) ? \$_GET["role"] : "user";\n\necho "\$name, \$age, \$role";`,
      solution: `<?php\nfunction getOrDefault(&\$var, \$default) {\n    return isset(\$var) ? \$var : \$default;\n}\n\n\$name = getOrDefault(\$_GET["name"], "Guest");\n\$age = getOrDefault(\$_GET["age"], 0);\n\$role = getOrDefault(\$_GET["role"], "user");\n\necho "\$name, \$age, \$role";`,
      hints: ['Create a reusable function that handles the isset check', 'Pass the variable by reference so undefined vars do not error', 'Replace each ternary with a call to the new function'],
      concepts: ['refactoring', 'helper-functions', 'isset'],
    },
  ],
};
