import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-types',
  title: '02. Types',
  explanation: `## Types in PHP\n\nPHP has several built-in types: \`string\`, \`int\`, \`float\`, \`bool\`, \`null\`, and \`array\`. PHP is dynamically typed but supports optional type declarations.\n\n\`\`\`php\n\$str = "hello";     // string\n\$num = 42;          // int\n\$pi = 3.14;         // float\n\$flag = true;       // bool\n\$nothing = null;    // null\n\$list = [1, 2, 3];  // array\n\`\`\`\n\n### Type Juggling\n\nPHP automatically converts types in certain contexts. This is called type juggling:\n\n\`\`\`php\n\$result = "5" + 3;   // int(8) - string coerced to int\n\$bool = (bool)"";    // false - empty string is falsy\n\`\`\`\n\n### Strict Types\n\nYou can enforce strict type checking with \`declare(strict_types=1)\` at the top of a file:\n\n\`\`\`php\ndeclare(strict_types=1);\n\nfunction add(int \$a, int \$b): int {\n    return \$a + \$b;\n}\nadd("5", 3); // TypeError in strict mode!\n\`\`\`\n\n### Type Casting\n\nExplicitly cast values with \`(type)\` syntax:\n\n\`\`\`php\n\$x = (int)"42";      // 42\n\$y = (string)3.14;   // "3.14"\n\$z = (array)"hello"; // ["hello"]\n\`\`\``,
  exercises: [
    {
      id: 'php-types-1',
      title: 'Cast String to Integer',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Cast the string "42" to an integer.',
      skeleton: `<?php\n\$str = "42";\n\$num = ___\$str;\necho \$num; // 42`,
      solution: `<?php\n\$str = "42";\n\$num = (int)\$str;\necho \$num; // 42`,
      hints: ['Use (int) to cast to integer', 'Place the cast before the variable', 'The syntax is (int)$variable'],
      concepts: ['type-casting', 'int'],
    },
    {
      id: 'php-types-2',
      title: 'Cast to Boolean',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Cast the integer 0 to a boolean.',
      skeleton: `<?php\n\$val = 0;\n\$flag = ___\$val;\nvar_dump(\$flag); // bool(false)`,
      solution: `<?php\n\$val = 0;\n\$flag = (bool)\$val;\nvar_dump(\$flag); // bool(false)`,
      hints: ['Use (bool) to cast to boolean', '0 is falsy in PHP', 'Place the cast before $val'],
      concepts: ['type-casting', 'bool', 'falsy-values'],
    },
    {
      id: 'php-types-3',
      title: 'Check Type with gettype',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use gettype() to get the type of $value and store it in $type.',
      skeleton: `<?php\n\$value = 3.14;\n\$type = ___;\necho \$type; // double`,
      solution: `<?php\n\$value = 3.14;\n\$type = gettype(\$value);\necho \$type; // double`,
      hints: ['gettype() returns the type as a string', 'Float types return "double" in PHP', 'Pass $value to gettype()'],
      concepts: ['gettype', 'float'],
    },
    {
      id: 'php-types-4',
      title: 'Declare Strict Types',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Add the strict_types declaration at the top of this file.',
      skeleton: `<?php\n___\n\nfunction double(int \$n): int {\n    return \$n * 2;\n}`,
      solution: `<?php\ndeclare(strict_types=1);\n\nfunction double(int \$n): int {\n    return \$n * 2;\n}`,
      hints: ['Use declare(strict_types=1);', 'It must be the first statement in the file', 'This prevents automatic type coercion in function calls'],
      concepts: ['strict-types', 'type-safety'],
    },
    {
      id: 'php-types-5',
      title: 'Use is_string Check',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Check if $input is a string using the appropriate function.',
      skeleton: `<?php\n\$input = "hello";\nif (___(\$input)) {\n    echo "It is a string";\n}`,
      solution: `<?php\n\$input = "hello";\nif (is_string(\$input)) {\n    echo "It is a string";\n}`,
      hints: ['PHP has is_string() for type checking', 'It returns true if the value is a string', 'Similar functions: is_int(), is_float(), is_bool()'],
      concepts: ['is_string', 'type-checking'],
    },
    {
      id: 'php-types-6',
      title: 'Nullable Type Declaration',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Declare the return type as nullable string (?string).',
      skeleton: `<?php\nfunction findUser(int \$id): ___ {\n    if (\$id === 1) return "Alice";\n    return null;\n}`,
      solution: `<?php\nfunction findUser(int \$id): ?string {\n    if (\$id === 1) return "Alice";\n    return null;\n}`,
      hints: ['Prefix the type with ? to make it nullable', 'A ?string can return string or null', 'The syntax is ?string'],
      concepts: ['nullable-types', 'return-types'],
    },
    {
      id: 'php-types-7',
      title: 'Write a Type Validator',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function isNumericType($val) that returns true if $val is an int or a float.',
      skeleton: `<?php\n// Write function isNumericType($val) that returns true for int or float values\n`,
      solution: `<?php\nfunction isNumericType(\$val): bool {\n    return is_int(\$val) || is_float(\$val);\n}`,
      hints: ['Use is_int() and is_float()', 'Combine with the || (or) operator', 'Return a boolean'],
      concepts: ['is_int', 'is_float', 'type-checking'],
    },
    {
      id: 'php-types-8',
      title: 'Write a Safe Caster',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function toInt($val) that casts $val to int if it is numeric, otherwise returns 0.',
      skeleton: `<?php\n// Write function toInt($val) - returns (int)$val if numeric, 0 otherwise\n`,
      solution: `<?php\nfunction toInt(\$val): int {\n    return is_numeric(\$val) ? (int)\$val : 0;\n}`,
      hints: ['Use is_numeric() to check if the value can be treated as a number', 'Cast with (int) when valid', 'Return 0 as the fallback'],
      concepts: ['is_numeric', 'type-casting', 'ternary-operator'],
    },
    {
      id: 'php-types-9',
      title: 'Write a Type Descriptor',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function typeName($val) that returns "string", "integer", "float", "boolean", "null", or "other" based on the type of $val.',
      skeleton: `<?php\n// Write function typeName($val) returning a friendly type name\n`,
      solution: `<?php\nfunction typeName(\$val): string {\n    if (is_string(\$val)) return "string";\n    if (is_int(\$val)) return "integer";\n    if (is_float(\$val)) return "float";\n    if (is_bool(\$val)) return "boolean";\n    if (is_null(\$val)) return "null";\n    return "other";\n}`,
      hints: ['Use is_string(), is_int(), is_float(), is_bool(), is_null()', 'Check each type with an if statement', 'Return "other" as the default case'],
      concepts: ['type-checking', 'is_string', 'is_int', 'is_float', 'is_bool', 'is_null'],
    },
    {
      id: 'php-types-10',
      title: 'Write a Strict Adder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function strictAdd(int $a, int $b): int that adds two integers. Include declare(strict_types=1).',
      skeleton: `<?php\n// Write a strict-typed function strictAdd(int $a, int $b): int\n`,
      solution: `<?php\ndeclare(strict_types=1);\n\nfunction strictAdd(int \$a, int \$b): int {\n    return \$a + \$b;\n}`,
      hints: ['Add declare(strict_types=1) at the top', 'Declare parameter types as int', 'Declare return type as int after the colon'],
      concepts: ['strict-types', 'type-declarations', 'functions'],
    },
    {
      id: 'php-types-11',
      title: 'Write a Union Type Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function stringify(int|float|string $val): string that converts any of the accepted types to a string.',
      skeleton: `<?php\n// Write function stringify(int|float|string $val): string\n`,
      solution: `<?php\nfunction stringify(int|float|string \$val): string {\n    return (string)\$val;\n}`,
      hints: ['PHP 8 supports union types with the | separator', 'Cast to string with (string)', 'The return type is string'],
      concepts: ['union-types', 'type-casting', 'php8'],
    },
    {
      id: 'php-types-12',
      title: 'Write a Type Coercion Demonstrator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function coercionDemo($a, $b) that returns an array with keys "sum" (the sum), "types" (array of gettype for each input), and "result_type" (gettype of the sum).',
      skeleton: `<?php\n// Write function coercionDemo($a, $b) demonstrating type juggling\n`,
      solution: `<?php\nfunction coercionDemo(\$a, \$b): array {\n    \$sum = \$a + \$b;\n    return [\n        "sum" => \$sum,\n        "types" => [gettype(\$a), gettype(\$b)],\n        "result_type" => gettype(\$sum),\n    ];\n}`,
      hints: ['Add $a and $b together for the sum', 'Use gettype() on each value', 'Return an associative array with three keys'],
      concepts: ['type-juggling', 'gettype', 'associative-arrays'],
    },
    {
      id: 'php-types-13',
      title: 'Fix: Wrong Type Cast',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the type cast: the code tries to cast to integer but uses the wrong syntax.',
      skeleton: `<?php\n\$price = "29.99";\n\$cents = int(\$price) * 100;\necho \$cents;`,
      solution: `<?php\n\$price = "29.99";\n\$cents = (int)(\$price) * 100;\necho \$cents;`,
      hints: ['PHP type casting uses (type) syntax, not type() as a function', 'Change int($price) to (int)($price)', 'The parentheses around the type are required'],
      concepts: ['type-casting', 'syntax-errors'],
    },
    {
      id: 'php-types-14',
      title: 'Fix: Null Comparison',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the null check: the code uses == instead of === to check for null, causing "0" to match.',
      skeleton: `<?php\nfunction isNull(\$val): bool {\n    return \$val == null;\n}\n\nvar_dump(isNull(0));     // Should be false\nvar_dump(isNull(null));  // Should be true`,
      solution: `<?php\nfunction isNull(\$val): bool {\n    return \$val === null;\n}\n\nvar_dump(isNull(0));     // false\nvar_dump(isNull(null));  // true`,
      hints: ['The == operator does type juggling, 0 == null is true', 'Use === for strict comparison', 'Change == to ==='],
      concepts: ['strict-comparison', 'null', 'type-juggling'],
    },
    {
      id: 'php-types-15',
      title: 'Fix: Missing Return Type',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the function: it should return ?int but currently has no return type, and it returns null for invalid input without declaring it.',
      skeleton: `<?php\ndeclare(strict_types=1);\n\nfunction parseAge(string \$input): int {\n    if (!is_numeric(\$input)) return null;\n    return (int)\$input;\n}`,
      solution: `<?php\ndeclare(strict_types=1);\n\nfunction parseAge(string \$input): ?int {\n    if (!is_numeric(\$input)) return null;\n    return (int)\$input;\n}`,
      hints: ['The function returns null but declares int as return type', 'Use ?int to allow null returns', 'The ? prefix makes a type nullable'],
      concepts: ['nullable-types', 'strict-types', 'return-types'],
    },
    {
      id: 'php-types-16',
      title: 'Predict: Type Juggling Addition',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$a = "3 apples";\n\$b = 2;\necho \$a + \$b;`,
      solution: `5`,
      hints: ['PHP extracts the leading number from "3 apples"', 'The string "3 apples" becomes 3 in numeric context', '3 + 2 = 5'],
      concepts: ['type-juggling', 'string-to-int'],
    },
    {
      id: 'php-types-17',
      title: 'Predict: Boolean Casting',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nvar_dump((bool)"0");`,
      solution: `bool(false)`,
      hints: ['The string "0" is one of the falsy values in PHP', 'Unlike most languages, "0" is false in PHP', 'var_dump shows the type and value'],
      concepts: ['type-casting', 'falsy-values', 'bool'],
    },
    {
      id: 'php-types-18',
      title: 'Predict: Float Precision',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$a = 0.1 + 0.2;\nvar_dump(\$a == 0.3);`,
      solution: `bool(false)`,
      hints: ['Floating point arithmetic has precision issues', '0.1 + 0.2 is not exactly 0.3 in binary', 'This is a common gotcha in most programming languages'],
      concepts: ['float-precision', 'comparison'],
    },
    {
      id: 'php-types-19',
      title: 'Refactor: Replace Type Checks with Union Types',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the function to use PHP 8 union types instead of manual type checking.',
      skeleton: `<?php\nfunction formatValue(\$val): string {\n    if (!is_int(\$val) && !is_string(\$val)) {\n        throw new InvalidArgumentException("Invalid type");\n    }\n    return "Value: " . \$val;\n}`,
      solution: `<?php\nfunction formatValue(int|string \$val): string {\n    return "Value: " . \$val;\n}`,
      hints: ['PHP 8 union types let you declare int|string in the parameter', 'The type check is handled automatically by the engine', 'Remove the manual if check and use the type declaration'],
      concepts: ['union-types', 'php8', 'refactoring'],
    },
    {
      id: 'php-types-20',
      title: 'Refactor: Use Strict Types',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor this code to use declare(strict_types=1) and proper type declarations instead of manual validation.',
      skeleton: `<?php\nfunction multiply(\$a, \$b) {\n    if (!is_int(\$a) || !is_int(\$b)) {\n        throw new TypeError("Both arguments must be integers");\n    }\n    return \$a * \$b;\n}\n\necho multiply(3, 4);`,
      solution: `<?php\ndeclare(strict_types=1);\n\nfunction multiply(int \$a, int \$b): int {\n    return \$a * \$b;\n}\n\necho multiply(3, 4);`,
      hints: ['Add declare(strict_types=1) at the top', 'Add int type hints to parameters and return type', 'Remove the manual type checking - PHP will enforce it'],
      concepts: ['strict-types', 'type-declarations', 'refactoring'],
    },
  ],
};
