import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-ops',
  title: '03. Operators',
  explanation: `## Operators in PHP\n\nPHP provides a rich set of operators for arithmetic, comparison, logic, and more.\n\n### Arithmetic Operators\n\n\`\`\`php\n\$a + \$b   // addition\n\$a - \$b   // subtraction\n\$a * \$b   // multiplication\n\$a / \$b   // division\n\$a % \$b   // modulus\n\$a ** \$b  // exponentiation\n\`\`\`\n\n### Comparison: == vs ===\n\nThe \`==\` operator compares with type juggling, while \`===\` is strict (no type conversion):\n\n\`\`\`php\n0 == "foo"   // true (in PHP 7), false (PHP 8)\n0 === "foo"  // false (always)\n1 == "1"     // true\n1 === "1"    // false\n\`\`\`\n\n### Logical Operators\n\n\`\`\`php\n\$a && \$b   // and\n\$a || \$b   // or\n!\$a        // not\n\`\`\`\n\n### Null Coalescing Operator (??)\n\nReturns the left operand if it is set and not null, otherwise the right:\n\n\`\`\`php\n\$name = \$_GET['name'] ?? 'Guest';\n\`\`\`\n\n### Spaceship Operator (<=>)\n\nThree-way comparison returning -1, 0, or 1:\n\n\`\`\`php\n1 <=> 2   // -1\n1 <=> 1   //  0\n2 <=> 1   //  1\n\`\`\``,
  exercises: [
    {
      id: 'php-ops-1',
      title: 'Exponentiation Operator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Calculate 2 raised to the power of 8 using the exponentiation operator.',
      skeleton: `<?php\n\$result = 2 ___ 8;\necho \$result; // 256`,
      solution: `<?php\n\$result = 2 ** 8;\necho \$result; // 256`,
      hints: ['The exponentiation operator in PHP is **', 'It works like Math.pow() in other languages', '2 ** 8 = 256'],
      concepts: ['exponentiation', 'arithmetic-operators'],
    },
    {
      id: 'php-ops-2',
      title: 'Null Coalescing Operator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use the null coalescing operator to provide a default value of "Guest".',
      skeleton: `<?php\n\$user = null;\n\$name = \$user ___ "Guest";\necho \$name; // Guest`,
      solution: `<?php\n\$user = null;\n\$name = \$user ?? "Guest";\necho \$name; // Guest`,
      hints: ['The null coalescing operator is ??', 'It returns the left side if not null, otherwise the right', 'It is like isset($var) ? $var : default'],
      concepts: ['null-coalescing', 'default-values'],
    },
    {
      id: 'php-ops-3',
      title: 'Spaceship Operator',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Use the spaceship operator to compare $a and $b.',
      skeleton: `<?php\n\$a = 5;\n\$b = 10;\n\$result = \$a ___ \$b;\necho \$result; // -1`,
      solution: `<?php\n\$a = 5;\n\$b = 10;\n\$result = \$a <=> \$b;\necho \$result; // -1`,
      hints: ['The spaceship operator is <=>', 'It returns -1 if left < right, 0 if equal, 1 if left > right', '5 <=> 10 returns -1'],
      concepts: ['spaceship-operator', 'comparison'],
    },
    {
      id: 'php-ops-4',
      title: 'Strict Equality',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use strict equality to compare $a and $b without type juggling.',
      skeleton: `<?php\n\$a = 1;\n\$b = "1";\nvar_dump(\$a ___ \$b); // bool(false)`,
      solution: `<?php\n\$a = 1;\n\$b = "1";\nvar_dump(\$a === \$b); // bool(false)`,
      hints: ['Use === for strict comparison', '=== checks both value and type', '1 === "1" is false because int !== string'],
      concepts: ['strict-equality', 'comparison'],
    },
    {
      id: 'php-ops-5',
      title: 'Modulus Operator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use the modulus operator to check if $num is even.',
      skeleton: `<?php\n\$num = 42;\n\$isEven = \$num ___ 2 === 0;\nvar_dump(\$isEven); // bool(true)`,
      solution: `<?php\n\$num = 42;\n\$isEven = \$num % 2 === 0;\nvar_dump(\$isEven); // bool(true)`,
      hints: ['The modulus operator is %', 'It returns the remainder of division', 'An even number % 2 equals 0'],
      concepts: ['modulus', 'arithmetic-operators'],
    },
    {
      id: 'php-ops-6',
      title: 'Null Coalescing Assignment',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Use the null coalescing assignment operator to set $config["debug"] to false only if it is not already set.',
      skeleton: `<?php\n\$config = [];\n\$config["debug"] ___= false;\nvar_dump(\$config["debug"]); // bool(false)`,
      solution: `<?php\n\$config = [];\n\$config["debug"] ??= false;\nvar_dump(\$config["debug"]); // bool(false)`,
      hints: ['The null coalescing assignment operator is ??=', 'It assigns the right side only if the left is null/undefined', 'Combines ?? and = into one operator'],
      concepts: ['null-coalescing-assignment', 'php74'],
    },
    {
      id: 'php-ops-7',
      title: 'Write a Clamp Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function clamp(int $val, int $min, int $max): int that constrains $val between $min and $max.',
      skeleton: `<?php\n// Write function clamp(int \$val, int \$min, int \$max): int\n`,
      solution: `<?php\nfunction clamp(int \$val, int \$min, int \$max): int {\n    if (\$val < \$min) return \$min;\n    if (\$val > \$max) return \$max;\n    return \$val;\n}`,
      hints: ['If $val is less than $min, return $min', 'If $val is greater than $max, return $max', 'Otherwise return $val'],
      concepts: ['comparison-operators', 'functions', 'clamping'],
    },
    {
      id: 'php-ops-8',
      title: 'Write a Comparison Sorter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function compareUsers(array $a, array $b): int that compares two users by "age" using the spaceship operator.',
      skeleton: `<?php\n// Write function compareUsers(array \$a, array \$b): int using <=>\n`,
      solution: `<?php\nfunction compareUsers(array \$a, array \$b): int {\n    return \$a["age"] <=> \$b["age"];\n}`,
      hints: ['Use the spaceship operator <=>', 'Access the "age" key from each array', 'The spaceship operator returns -1, 0, or 1'],
      concepts: ['spaceship-operator', 'sorting', 'associative-arrays'],
    },
    {
      id: 'php-ops-9',
      title: 'Write a Safe Divider',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function safeDivide(float $a, float $b): ?float that returns $a / $b, or null if $b is 0.',
      skeleton: `<?php\n// Write function safeDivide(float \$a, float \$b): ?float\n`,
      solution: `<?php\nfunction safeDivide(float \$a, float \$b): ?float {\n    if (\$b == 0) return null;\n    return \$a / \$b;\n}`,
      hints: ['Check if $b is 0 before dividing', 'Return null for division by zero', 'Use ?float as the return type for nullable'],
      concepts: ['division', 'null', 'nullable-types'],
    },
    {
      id: 'php-ops-10',
      title: 'Write a Config Merger',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function mergeDefaults(array $config, array $defaults): array that fills in missing keys from $defaults using ??.',
      skeleton: `<?php\n// Write function mergeDefaults(array \$config, array \$defaults): array\n`,
      solution: `<?php\nfunction mergeDefaults(array \$config, array \$defaults): array {\n    foreach (\$defaults as \$key => \$value) {\n        \$config[\$key] = \$config[\$key] ?? \$value;\n    }\n    return \$config;\n}`,
      hints: ['Loop through $defaults with foreach', 'Use ?? to keep existing values or use the default', 'Return the merged config array'],
      concepts: ['null-coalescing', 'arrays', 'foreach'],
    },
    {
      id: 'php-ops-11',
      title: 'Write a Ternary Chain',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function grade(int $score): string that returns "A" for 90+, "B" for 80+, "C" for 70+, "D" for 60+, "F" otherwise.',
      skeleton: `<?php\n// Write function grade(int \$score): string using comparison operators\n`,
      solution: `<?php\nfunction grade(int \$score): string {\n    if (\$score >= 90) return "A";\n    if (\$score >= 80) return "B";\n    if (\$score >= 70) return "C";\n    if (\$score >= 60) return "D";\n    return "F";\n}`,
      hints: ['Check from highest to lowest', 'Use >= for each threshold', 'Return early for each grade level'],
      concepts: ['comparison-operators', 'conditional-logic'],
    },
    {
      id: 'php-ops-12',
      title: 'Write a Bitwise Flag Checker',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function hasFlag(int $permissions, int $flag): bool that checks if a bitwise flag is set.',
      skeleton: `<?php\n// Write function hasFlag(int \$permissions, int \$flag): bool\n`,
      solution: `<?php\nfunction hasFlag(int \$permissions, int \$flag): bool {\n    return (\$permissions & \$flag) === \$flag;\n}`,
      hints: ['Use the bitwise AND operator &', 'Compare the result with the flag itself', 'If ($permissions & $flag) equals $flag, the flag is set'],
      concepts: ['bitwise-operators', 'flags', 'permissions'],
    },
    {
      id: 'php-ops-13',
      title: 'Fix: Wrong Comparison Operator',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the bug: the code uses = instead of == for comparison.',
      skeleton: `<?php\n\$age = 18;\nif (\$age = 21) {\n    echo "Can drink";\n} else {\n    echo "Too young";\n}`,
      solution: `<?php\n\$age = 18;\nif (\$age === 21) {\n    echo "Can drink";\n} else {\n    echo "Too young";\n}`,
      hints: ['A single = is assignment, not comparison', 'Use === for strict comparison', 'The if condition assigns 21 to $age instead of comparing'],
      concepts: ['comparison-operators', 'assignment-vs-comparison'],
    },
    {
      id: 'php-ops-14',
      title: 'Fix: Null Coalescing Misuse',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: it should use ?? but uses ?: which does not handle undefined variables safely.',
      skeleton: `<?php\n\$settings = [];\n\$debug = \$settings["debug"] ?: false;`,
      solution: `<?php\n\$settings = [];\n\$debug = \$settings["debug"] ?? false;`,
      hints: ['The ?: operator does not suppress undefined key warnings', 'Use ?? for undefined key access', '?? checks isset, ?: checks truthiness'],
      concepts: ['null-coalescing', 'elvis-operator', 'undefined-keys'],
    },
    {
      id: 'php-ops-15',
      title: 'Fix: Operator Precedence',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the operator precedence bug: the condition should check if $x is between 1 and 10 inclusive.',
      skeleton: `<?php\n\$x = 5;\nif (\$x >= 1 && \$x <= 10 || \$x === 0) {\n    // Should only be true for 1-10, not 0\n    echo "In range";\n}`,
      solution: `<?php\n\$x = 5;\nif ((\$x >= 1 && \$x <= 10) || \$x === 0) {\n    // Parentheses clarify precedence\n    echo "In range";\n}`,
      hints: ['&& has higher precedence than ||, but adding parentheses makes intent clear', 'The original logic actually works due to && precedence, but parentheses prevent confusion', 'Group the range check in parentheses for clarity'],
      concepts: ['operator-precedence', 'logical-operators'],
    },
    {
      id: 'php-ops-16',
      title: 'Predict: Loose Comparison',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nvar_dump(0 == "foo");`,
      solution: `bool(false)`,
      hints: ['In PHP 8, 0 == "foo" is false (changed from PHP 7)', 'PHP 8 changed string-to-number comparison behavior', 'Non-numeric strings are no longer equal to 0'],
      concepts: ['loose-comparison', 'type-juggling', 'php8'],
    },
    {
      id: 'php-ops-17',
      title: 'Predict: Spaceship Operator',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\necho (10 <=> 10);`,
      solution: `0`,
      hints: ['The spaceship operator returns 0 when both sides are equal', '<=> returns -1, 0, or 1', '10 is equal to 10, so the result is 0'],
      concepts: ['spaceship-operator', 'comparison'],
    },
    {
      id: 'php-ops-18',
      title: 'Predict: Null Coalescing Chain',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$a = null;\n\$b = null;\n\$c = "found";\necho \$a ?? \$b ?? \$c;`,
      solution: `found`,
      hints: ['?? chains left to right', '$a is null so it moves to $b', '$b is null so it moves to $c which is "found"'],
      concepts: ['null-coalescing', 'chaining'],
    },
    {
      id: 'php-ops-19',
      title: 'Refactor: Replace Ternary with Null Coalescing',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor the ternary expression to use the null coalescing operator.',
      skeleton: `<?php\n\$data = ["name" => "Alice"];\n\$name = isset(\$data["name"]) ? \$data["name"] : "Unknown";\necho \$name;`,
      solution: `<?php\n\$data = ["name" => "Alice"];\n\$name = \$data["name"] ?? "Unknown";\necho \$name;`,
      hints: ['The ?? operator replaces the isset() ? value : default pattern', 'It is more concise and readable', 'Remove the isset check entirely'],
      concepts: ['null-coalescing', 'refactoring'],
    },
    {
      id: 'php-ops-20',
      title: 'Refactor: Use Spaceship for Sorting',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the manual comparison logic to use the spaceship operator.',
      skeleton: `<?php\nfunction compare(int \$a, int \$b): int {\n    if (\$a < \$b) return -1;\n    if (\$a > \$b) return 1;\n    return 0;\n}\n\n\$nums = [3, 1, 4, 1, 5];\nusort(\$nums, 'compare');\nprint_r(\$nums);`,
      solution: `<?php\n\$nums = [3, 1, 4, 1, 5];\nusort(\$nums, fn(int \$a, int \$b): int => \$a <=> \$b);\nprint_r(\$nums);`,
      hints: ['The spaceship operator <=> replaces the entire compare function', 'Use an arrow function fn() => for conciseness', 'usort accepts a callable as the second argument'],
      concepts: ['spaceship-operator', 'arrow-functions', 'usort', 'refactoring'],
    },
  ],
};
