import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-str',
  title: '04. Strings',
  explanation: `## Strings in PHP\n\nPHP has several ways to define strings, each with different behavior.\n\n### Single vs Double Quotes\n\nSingle-quoted strings are literal -- no variable interpolation or escape sequences (except \`\\'\` and \`\\\\\`):\n\n\`\`\`php\n\$name = 'Alice';\necho 'Hello \$name';   // Hello \$name (literal)\necho "Hello \$name";   // Hello Alice (interpolated)\n\`\`\`\n\n### Heredoc and Nowdoc\n\nHeredoc (\`<<<\`) works like double quotes. Nowdoc (\`<<<'\`) works like single quotes:\n\n\`\`\`php\n\$msg = <<<EOT\nHello \$name!\nEOT;\n\n\$raw = <<<'EOT'\nHello \$name!\nEOT;\n\`\`\`\n\n### Common String Functions\n\n\`\`\`php\nstrlen("hello");            // 5\nstrpos("hello world", "wo"); // 6\nsubstr("hello", 1, 3);      // "ell"\nstr_replace("o", "0", "foo"); // "f00"\nstrtolower("HELLO");         // "hello"\nstrtoupper("hello");         // "HELLO"\ntrim("  hi  ");              // "hi"\nexplode(",", "a,b,c");       // ["a", "b", "c"]\nimplode("-", ["a","b","c"]); // "a-b-c"\n\`\`\`\n\n### String Interpolation\n\nInside double-quoted strings, variables are expanded. Use curly braces for complex expressions:\n\n\`\`\`php\n\$item = "world";\necho "Hello {\$item}!";     // Hello world!\necho "Val: {\$arr['key']}"; // array access in string\n\`\`\``,
  exercises: [
    {
      id: 'php-str-1',
      title: 'String Length',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Get the length of the string $msg.',
      skeleton: `<?php\n\$msg = "Hello, World!";\n\$len = ___(\$msg);\necho \$len; // 13`,
      solution: `<?php\n\$msg = "Hello, World!";\n\$len = strlen(\$msg);\necho \$len; // 13`,
      hints: ['Use strlen() to get the length of a string', 'It counts the number of bytes', 'Pass the string as the argument'],
      concepts: ['strlen', 'string-functions'],
    },
    {
      id: 'php-str-2',
      title: 'Find Substring Position',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Find the position of "World" in the string.',
      skeleton: `<?php\n\$str = "Hello, World!";\n\$pos = ___(\$str, "World");\necho \$pos; // 7`,
      solution: `<?php\n\$str = "Hello, World!";\n\$pos = strpos(\$str, "World");\necho \$pos; // 7`,
      hints: ['Use strpos() to find the position of a substring', 'First argument is the haystack, second is the needle', 'Positions are zero-indexed'],
      concepts: ['strpos', 'string-search'],
    },
    {
      id: 'php-str-3',
      title: 'Extract a Substring',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Extract "World" from the string using substr().',
      skeleton: `<?php\n\$str = "Hello, World!";\n\$word = ___(\$str, 7, 5);\necho \$word; // World`,
      solution: `<?php\n\$str = "Hello, World!";\n\$word = substr(\$str, 7, 5);\necho \$word; // World`,
      hints: ['Use substr(string, start, length)', 'Start at position 7', '"World" is 5 characters long'],
      concepts: ['substr', 'string-extraction'],
    },
    {
      id: 'php-str-4',
      title: 'String Replacement',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Replace "World" with "PHP" in the string.',
      skeleton: `<?php\n\$str = "Hello, World!";\n\$new = ___("World", "PHP", \$str);\necho \$new; // Hello, PHP!`,
      solution: `<?php\n\$str = "Hello, World!";\n\$new = str_replace("World", "PHP", \$str);\necho \$new; // Hello, PHP!`,
      hints: ['Use str_replace(search, replace, subject)', 'First arg is what to find, second is the replacement', 'Third argument is the original string'],
      concepts: ['str_replace', 'string-manipulation'],
    },
    {
      id: 'php-str-5',
      title: 'String Interpolation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Use string interpolation to include $name in the greeting.',
      skeleton: `<?php\n\$name = "Alice";\necho ___; // Hello, Alice!`,
      solution: `<?php\n\$name = "Alice";\necho "Hello, \$name!"; // Hello, Alice!`,
      hints: ['Use double quotes for interpolation', 'Variables inside double quotes are expanded', 'Place $name directly in the string'],
      concepts: ['string-interpolation', 'double-quotes'],
    },
    {
      id: 'php-str-6',
      title: 'Explode a String',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Split the CSV string into an array using explode().',
      skeleton: `<?php\n\$csv = "apple,banana,cherry";\n\$fruits = ___(",", \$csv);\nprint_r(\$fruits);`,
      solution: `<?php\n\$csv = "apple,banana,cherry";\n\$fruits = explode(",", \$csv);\nprint_r(\$fruits);`,
      hints: ['Use explode(delimiter, string)', 'The delimiter is a comma ","', 'explode returns an array of parts'],
      concepts: ['explode', 'string-splitting'],
    },
    {
      id: 'php-str-7',
      title: 'Write a Slug Generator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function slugify(string $title): string that converts "Hello World" to "hello-world" (lowercase, spaces to hyphens).',
      skeleton: `<?php\n// Write function slugify(string \$title): string\n`,
      solution: `<?php\nfunction slugify(string \$title): string {\n    return str_replace(" ", "-", strtolower(trim(\$title)));\n}`,
      hints: ['Use strtolower() to convert to lowercase', 'Use str_replace() to replace spaces with hyphens', 'Use trim() to remove leading/trailing whitespace'],
      concepts: ['strtolower', 'str_replace', 'trim', 'slug'],
    },
    {
      id: 'php-str-8',
      title: 'Write a String Truncator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function truncate(string $str, int $len): string that truncates to $len chars and adds "..." if truncated.',
      skeleton: `<?php\n// Write function truncate(string \$str, int \$len): string\n`,
      solution: `<?php\nfunction truncate(string \$str, int \$len): string {\n    if (strlen(\$str) <= \$len) return \$str;\n    return substr(\$str, 0, \$len) . "...";\n}`,
      hints: ['Check if the string is already short enough with strlen()', 'Use substr() to cut the string', 'Append "..." with the concatenation operator (.)'],
      concepts: ['strlen', 'substr', 'string-concatenation'],
    },
    {
      id: 'php-str-9',
      title: 'Write a Word Counter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function countWords(string $text): int that returns the number of words.',
      skeleton: `<?php\n// Write function countWords(string \$text): int\n`,
      solution: `<?php\nfunction countWords(string \$text): int {\n    return str_word_count(\$text);\n}`,
      hints: ['PHP has a built-in str_word_count() function', 'It counts the number of words in a string', 'Alternatively you could use explode and count'],
      concepts: ['str_word_count', 'string-functions'],
    },
    {
      id: 'php-str-10',
      title: 'Write a Palindrome Checker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function isPalindrome(string $str): bool that checks if a string is a palindrome (case-insensitive).',
      skeleton: `<?php\n// Write function isPalindrome(string \$str): bool\n`,
      solution: `<?php\nfunction isPalindrome(string \$str): bool {\n    \$lower = strtolower(\$str);\n    return \$lower === strrev(\$lower);\n}`,
      hints: ['Convert to lowercase with strtolower()', 'Use strrev() to reverse the string', 'Compare the original with the reversed version'],
      concepts: ['strrev', 'strtolower', 'string-comparison'],
    },
    {
      id: 'php-str-11',
      title: 'Write an Initials Extractor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function initials(string $name): string that returns "J.D." from "John Doe".',
      skeleton: `<?php\n// Write function initials(string \$name): string\n`,
      solution: `<?php\nfunction initials(string \$name): string {\n    \$parts = explode(" ", \$name);\n    \$result = "";\n    foreach (\$parts as \$part) {\n        \$result .= strtoupper(\$part[0]) . ".";\n    }\n    return \$result;\n}`,
      hints: ['Split the name by spaces with explode()', 'Take the first character of each part with $part[0]', 'Use strtoupper() and append a dot'],
      concepts: ['explode', 'strtoupper', 'string-indexing'],
    },
    {
      id: 'php-str-12',
      title: 'Write a CSV Line Parser',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function parseCsvLine(string $line): array that splits a CSV line and trims each value.',
      skeleton: `<?php\n// Write function parseCsvLine(string \$line): array\n`,
      solution: `<?php\nfunction parseCsvLine(string \$line): array {\n    \$parts = explode(",", \$line);\n    return array_map('trim', \$parts);\n}`,
      hints: ['Use explode(",", $line) to split', 'Use array_map with trim to clean whitespace', 'Return the cleaned array'],
      concepts: ['explode', 'array_map', 'trim'],
    },
    {
      id: 'php-str-13',
      title: 'Fix: Interpolation in Single Quotes',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the code: variable interpolation does not work in single-quoted strings.',
      skeleton: `<?php\n\$name = "Alice";\necho 'Hello, \$name!';`,
      solution: `<?php\n\$name = "Alice";\necho "Hello, \$name!";`,
      hints: ['Single quotes do not interpolate variables', 'Change single quotes to double quotes', 'Or use concatenation: \'Hello, \' . $name . \'!\''],
      concepts: ['string-interpolation', 'single-quotes', 'double-quotes'],
    },
    {
      id: 'php-str-14',
      title: 'Fix: strpos False Check',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the bug: strpos returns 0 when the needle is at position 0, which is falsy.',
      skeleton: `<?php\n\$str = "Hello World";\nif (strpos(\$str, "Hello")) {\n    echo "Found";\n} else {\n    echo "Not found";\n}`,
      solution: `<?php\n\$str = "Hello World";\nif (strpos(\$str, "Hello") !== false) {\n    echo "Found";\n} else {\n    echo "Not found";\n}`,
      hints: ['strpos returns 0 when found at the start, which is falsy', 'Use !== false to check properly', 'In PHP 8, you can use str_contains() instead'],
      concepts: ['strpos', 'falsy-values', 'strict-comparison'],
    },
    {
      id: 'php-str-15',
      title: 'Fix: Wrong Concatenation Operator',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the string concatenation: PHP uses . not + for string joining.',
      skeleton: `<?php\n\$first = "Hello";\n\$second = " World";\necho \$first + \$second;`,
      solution: `<?php\n\$first = "Hello";\n\$second = " World";\necho \$first . \$second;`,
      hints: ['PHP uses the dot (.) operator for string concatenation', 'The + operator is for arithmetic in PHP', 'Change + to .'],
      concepts: ['string-concatenation', 'operators'],
    },
    {
      id: 'php-str-16',
      title: 'Predict: Single vs Double Quotes',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$x = 5;\necho 'Value: \$x';`,
      solution: `Value: \$x`,
      hints: ['Single quotes do not interpolate variables', 'The literal string $x is printed', 'Use double quotes for interpolation'],
      concepts: ['single-quotes', 'string-interpolation'],
    },
    {
      id: 'php-str-17',
      title: 'Predict: String Arithmetic',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\necho "hello" . " " . "world" . "!";`,
      solution: `hello world!`,
      hints: ['The dot operator concatenates strings', 'Each . joins the strings together', 'Spaces are included as literal strings'],
      concepts: ['string-concatenation', 'dot-operator'],
    },
    {
      id: 'php-str-18',
      title: 'Predict: substr with Negative Offset',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\necho substr("Hello, World!", -6);`,
      solution: `orld!`,
      hints: ['Negative offset counts from the end of the string', '-6 starts 6 characters from the end', 'It returns from that position to the end'],
      concepts: ['substr', 'negative-offset'],
    },
    {
      id: 'php-str-19',
      title: 'Refactor: Use str_contains Instead of strpos',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor to use PHP 8 str_contains() instead of strpos() !== false.',
      skeleton: `<?php\n\$email = "user@example.com";\nif (strpos(\$email, "@") !== false) {\n    echo "Valid email format";\n}`,
      solution: `<?php\n\$email = "user@example.com";\nif (str_contains(\$email, "@")) {\n    echo "Valid email format";\n}`,
      hints: ['PHP 8 added str_contains() for cleaner substring checks', 'It returns true/false directly', 'Replace the strpos !== false pattern'],
      concepts: ['str_contains', 'php8', 'refactoring'],
    },
    {
      id: 'php-str-20',
      title: 'Refactor: Use Interpolation Instead of Concatenation',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor the string concatenation to use double-quoted string interpolation.',
      skeleton: `<?php\n\$name = "Alice";\n\$age = 30;\n\$city = "NYC";\necho \$name . " is " . \$age . " years old and lives in " . \$city . ".";`,
      solution: `<?php\n\$name = "Alice";\n\$age = 30;\n\$city = "NYC";\necho "\$name is \$age years old and lives in \$city.";`,
      hints: ['Place variables directly inside double-quoted strings', 'Remove the dot concatenation operators', 'Variables are automatically expanded in double quotes'],
      concepts: ['string-interpolation', 'refactoring', 'double-quotes'],
    },
  ],
};
