import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-arr',
  title: '05. Arrays',
  explanation: `## Arrays in PHP\n\nPHP arrays are ordered maps that can serve as lists, dictionaries, stacks, and queues.\n\n### Indexed Arrays\n\n\`\`\`php\n\$fruits = ["apple", "banana", "cherry"];\necho \$fruits[0]; // apple\n\`\`\`\n\n### Associative Arrays\n\n\`\`\`php\n\$user = ["name" => "Alice", "age" => 30];\necho \$user["name"]; // Alice\n\`\`\`\n\n### Common Array Functions\n\n\`\`\`php\narray_push(\$arr, \$val);      // add to end\narray_pop(\$arr);              // remove from end\narray_merge(\$a, \$b);         // merge arrays\narray_map(fn, \$arr);          // transform each element\narray_filter(\$arr, fn);       // filter elements\narray_keys(\$arr);             // get all keys\narray_values(\$arr);           // get all values\ncount(\$arr);                  // number of elements\nin_array(\$val, \$arr);        // check if value exists\n\`\`\`\n\n### Looping with foreach\n\n\`\`\`php\nforeach (\$fruits as \$fruit) {\n    echo \$fruit;\n}\n\nforeach (\$user as \$key => \$value) {\n    echo "\$key: \$value";\n}\n\`\`\`\n\n### list() / Array Destructuring\n\n\`\`\`php\n[\$a, \$b, \$c] = [1, 2, 3];\nlist(\$x, \$y) = [10, 20];\n\`\`\``,
  exercises: [
    {
      id: 'php-arr-1',
      title: 'Push to Array',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Add "grape" to the end of the $fruits array.',
      skeleton: `<?php\n\$fruits = ["apple", "banana"];\n___(\$fruits, "grape");\nprint_r(\$fruits);`,
      solution: `<?php\n\$fruits = ["apple", "banana"];\narray_push(\$fruits, "grape");\nprint_r(\$fruits);`,
      hints: ['Use array_push() to add to the end', 'First argument is the array, second is the value', 'You can also use $fruits[] = "grape"'],
      concepts: ['array_push', 'array-manipulation'],
    },
    {
      id: 'php-arr-2',
      title: 'Access Associative Array',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Access the "name" key from the $user associative array.',
      skeleton: `<?php\n\$user = ["name" => "Alice", "age" => 30];\necho \$user___; // Alice`,
      solution: `<?php\n\$user = ["name" => "Alice", "age" => 30];\necho \$user["name"]; // Alice`,
      hints: ['Use square bracket notation with the key', 'Keys are strings in associative arrays', 'The syntax is $array["key"]'],
      concepts: ['associative-arrays', 'array-access'],
    },
    {
      id: 'php-arr-3',
      title: 'Count Array Elements',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Get the number of elements in the array.',
      skeleton: `<?php\n\$nums = [10, 20, 30, 40, 50];\necho ___(\$nums); // 5`,
      solution: `<?php\n\$nums = [10, 20, 30, 40, 50];\necho count(\$nums); // 5`,
      hints: ['Use count() to get the number of elements', 'sizeof() is an alias but count() is preferred', 'Pass the array as the argument'],
      concepts: ['count', 'array-length'],
    },
    {
      id: 'php-arr-4',
      title: 'Check if Value Exists',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Check if "banana" exists in the $fruits array.',
      skeleton: `<?php\n\$fruits = ["apple", "banana", "cherry"];\nif (___(\"banana\", \$fruits)) {\n    echo "Found!";\n}`,
      solution: `<?php\n\$fruits = ["apple", "banana", "cherry"];\nif (in_array("banana", \$fruits)) {\n    echo "Found!";\n}`,
      hints: ['Use in_array() to check for a value', 'First argument is the needle, second is the haystack', 'It returns true if found'],
      concepts: ['in_array', 'array-search'],
    },
    {
      id: 'php-arr-5',
      title: 'Merge Two Arrays',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Merge $a and $b into a single array.',
      skeleton: `<?php\n\$a = [1, 2, 3];\n\$b = [4, 5, 6];\n\$merged = ___(\$a, \$b);\nprint_r(\$merged);`,
      solution: `<?php\n\$a = [1, 2, 3];\n\$b = [4, 5, 6];\n\$merged = array_merge(\$a, \$b);\nprint_r(\$merged);`,
      hints: ['Use array_merge() to combine arrays', 'It returns a new array', 'In PHP 7.4+, you can also use the spread operator [...$a, ...$b]'],
      concepts: ['array_merge', 'array-combining'],
    },
    {
      id: 'php-arr-6',
      title: 'Array Destructuring',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Destructure the array into three variables $x, $y, $z.',
      skeleton: `<?php\n___ = [10, 20, 30];\necho "\$x, \$y, \$z"; // 10, 20, 30`,
      solution: `<?php\n[\$x, \$y, \$z] = [10, 20, 30];\necho "\$x, \$y, \$z"; // 10, 20, 30`,
      hints: ['Use [$x, $y, $z] = array syntax', 'This is PHP shorthand for list()', 'Each variable gets the corresponding array element'],
      concepts: ['destructuring', 'list'],
    },
    {
      id: 'php-arr-7',
      title: 'Write an Array Sum Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function sumArray(array $nums): int that returns the sum of all elements.',
      skeleton: `<?php\n// Write function sumArray(array \$nums): int\n`,
      solution: `<?php\nfunction sumArray(array \$nums): int {\n    return array_sum(\$nums);\n}`,
      hints: ['PHP has a built-in array_sum() function', 'It adds up all values in the array', 'Return the result directly'],
      concepts: ['array_sum', 'array-functions'],
    },
    {
      id: 'php-arr-8',
      title: 'Write an Array Flattener',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function flatten(array $nested): array that flattens a 2D array into a 1D array.',
      skeleton: `<?php\n// Write function flatten(array \$nested): array\n// Example: [[1,2],[3,4]] => [1,2,3,4]\n`,
      solution: `<?php\nfunction flatten(array \$nested): array {\n    return array_merge(...\$nested);\n}`,
      hints: ['Use the spread operator ... with array_merge', 'array_merge(...$nested) unpacks each sub-array', 'This works for one level of nesting'],
      concepts: ['array_merge', 'spread-operator', 'flattening'],
    },
    {
      id: 'php-arr-9',
      title: 'Write a Unique Values Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function unique(array $arr): array that returns an array with duplicate values removed, re-indexed.',
      skeleton: `<?php\n// Write function unique(array \$arr): array\n`,
      solution: `<?php\nfunction unique(array \$arr): array {\n    return array_values(array_unique(\$arr));\n}`,
      hints: ['Use array_unique() to remove duplicates', 'Wrap with array_values() to re-index keys', 'Return the cleaned array'],
      concepts: ['array_unique', 'array_values'],
    },
    {
      id: 'php-arr-10',
      title: 'Write a Group-By Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function groupBy(array $items, string $key): array that groups an array of associative arrays by a given key.',
      skeleton: `<?php\n// Write function groupBy(array \$items, string \$key): array\n// Example: groupBy([["type"=>"a","v"=>1],["type"=>"b","v"=>2],["type"=>"a","v"=>3]], "type")\n// => ["a" => [["type"=>"a","v"=>1],["type"=>"a","v"=>3]], "b" => [["type"=>"b","v"=>2]]]\n`,
      solution: `<?php\nfunction groupBy(array \$items, string \$key): array {\n    \$result = [];\n    foreach (\$items as \$item) {\n        \$result[\$item[\$key]][] = \$item;\n    }\n    return \$result;\n}`,
      hints: ['Loop through each item with foreach', 'Use the value of $item[$key] as the group key', 'Append each item to its group with []'],
      concepts: ['foreach', 'associative-arrays', 'grouping'],
    },
    {
      id: 'php-arr-11',
      title: 'Write an Array Map with Keys',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function mapWithKeys(array $arr, callable $fn): array that applies $fn($key, $value) to each element and returns the new array.',
      skeleton: `<?php\n// Write function mapWithKeys(array \$arr, callable \$fn): array\n`,
      solution: `<?php\nfunction mapWithKeys(array \$arr, callable \$fn): array {\n    \$result = [];\n    foreach (\$arr as \$key => \$value) {\n        \$result[\$key] = \$fn(\$key, \$value);\n    }\n    return \$result;\n}`,
      hints: ['Use foreach with $key => $value', 'Call $fn($key, $value) for each element', 'Store the result with the same key'],
      concepts: ['foreach', 'callable', 'array_map'],
    },
    {
      id: 'php-arr-12',
      title: 'Write a Pluck Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function pluck(array $items, string $key): array that extracts a single column from an array of associative arrays.',
      skeleton: `<?php\n// Write function pluck(array \$items, string \$key): array\n// Example: pluck([["name"=>"A"],["name"=>"B"]], "name") => ["A","B"]\n`,
      solution: `<?php\nfunction pluck(array \$items, string \$key): array {\n    return array_column(\$items, \$key);\n}`,
      hints: ['PHP has a built-in array_column() function', 'It extracts values for a given key from nested arrays', 'Pass the items and the column key'],
      concepts: ['array_column', 'data-extraction'],
    },
    {
      id: 'php-arr-13',
      title: 'Fix: foreach Modification',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: the foreach loop should double each value in place, but it does not modify the original array.',
      skeleton: `<?php\n\$nums = [1, 2, 3];\nforeach (\$nums as \$num) {\n    \$num *= 2;\n}\nprint_r(\$nums); // Should be [2, 4, 6]`,
      solution: `<?php\n\$nums = [1, 2, 3];\nforeach (\$nums as &\$num) {\n    \$num *= 2;\n}\nunset(\$num);\nprint_r(\$nums); // [2, 4, 6]`,
      hints: ['Use & before the variable to modify by reference', 'Change $num to &$num in the foreach', 'Always unset the reference variable after the loop'],
      concepts: ['foreach', 'pass-by-reference', 'array-modification'],
    },
    {
      id: 'php-arr-14',
      title: 'Fix: Array Key Check',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the code: it uses isset() to check for a key, but the key exists with a null value.',
      skeleton: `<?php\n\$data = ["name" => "Alice", "email" => null];\nif (isset(\$data["email"])) {\n    echo "Email key exists";\n} else {\n    echo "No email key"; // This runs incorrectly\n}`,
      solution: `<?php\n\$data = ["name" => "Alice", "email" => null];\nif (array_key_exists("email", \$data)) {\n    echo "Email key exists";\n} else {\n    echo "No email key";\n}`,
      hints: ['isset() returns false for null values', 'Use array_key_exists() to check if a key exists regardless of value', 'array_key_exists checks the key, not the value'],
      concepts: ['array_key_exists', 'isset', 'null'],
    },
    {
      id: 'php-arr-15',
      title: 'Fix: Array Merge vs Plus',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: using + to merge indexed arrays does not append, it keeps existing keys.',
      skeleton: `<?php\n\$a = [1, 2, 3];\n\$b = [4, 5, 6];\n\$result = \$a + \$b;\nprint_r(\$result); // Should be [1,2,3,4,5,6]`,
      solution: `<?php\n\$a = [1, 2, 3];\n\$b = [4, 5, 6];\n\$result = array_merge(\$a, \$b);\nprint_r(\$result); // [1,2,3,4,5,6]`,
      hints: ['The + operator on arrays does union, not append', 'It keeps keys from the left array and ignores duplicates', 'Use array_merge() for indexed array concatenation'],
      concepts: ['array_merge', 'array-union', 'operators'],
    },
    {
      id: 'php-arr-16',
      title: 'Predict: array_pop',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$stack = ["a", "b", "c"];\n\$last = array_pop(\$stack);\necho \$last;`,
      solution: `c`,
      hints: ['array_pop removes and returns the last element', 'The last element is "c"', '$stack becomes ["a", "b"] after the pop'],
      concepts: ['array_pop', 'stack-operations'],
    },
    {
      id: 'php-str-17',
      title: 'Predict: Array Spread',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$a = [1, 2];\n\$b = [3, 4];\n\$c = [...\$a, ...\$b];\necho count(\$c);`,
      solution: `4`,
      hints: ['The spread operator unpacks arrays', '[...$a, ...$b] creates [1, 2, 3, 4]', 'count() returns 4'],
      concepts: ['spread-operator', 'count', 'array-unpacking'],
    },
    {
      id: 'php-arr-18',
      title: 'Predict: foreach Key-Value',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$ages = ["Alice" => 30, "Bob" => 25];\nforeach (\$ages as \$name => \$age) {\n    echo "\$name:\$age ";\n}`,
      solution: `Alice:30 Bob:25 `,
      hints: ['foreach with => gives both key and value', 'It iterates in insertion order', 'Each iteration prints name:age followed by a space'],
      concepts: ['foreach', 'associative-arrays'],
    },
    {
      id: 'php-arr-19',
      title: 'Refactor: Replace Loop with array_map',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the foreach loop to use array_map() with an arrow function.',
      skeleton: `<?php\n\$nums = [1, 2, 3, 4, 5];\n\$doubled = [];\nforeach (\$nums as \$n) {\n    \$doubled[] = \$n * 2;\n}\nprint_r(\$doubled);`,
      solution: `<?php\n\$nums = [1, 2, 3, 4, 5];\n\$doubled = array_map(fn(\$n) => \$n * 2, \$nums);\nprint_r(\$doubled);`,
      hints: ['Use array_map with fn($n) => $n * 2', 'array_map takes the callback first, then the array', 'Arrow functions (fn =>) automatically capture nothing by reference'],
      concepts: ['array_map', 'arrow-functions', 'refactoring'],
    },
    {
      id: 'php-arr-20',
      title: 'Refactor: Replace Loop with array_filter',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the foreach loop to use array_filter() with an arrow function.',
      skeleton: `<?php\n\$nums = [1, 2, 3, 4, 5, 6, 7, 8];\n\$evens = [];\nforeach (\$nums as \$n) {\n    if (\$n % 2 === 0) {\n        \$evens[] = \$n;\n    }\n}\nprint_r(\$evens);`,
      solution: `<?php\n\$nums = [1, 2, 3, 4, 5, 6, 7, 8];\n\$evens = array_values(array_filter(\$nums, fn(\$n) => \$n % 2 === 0));\nprint_r(\$evens);`,
      hints: ['Use array_filter with fn($n) => $n % 2 === 0', 'Wrap with array_values() to re-index the result', 'array_filter preserves keys, so re-indexing is needed'],
      concepts: ['array_filter', 'arrow-functions', 'array_values', 'refactoring'],
    },
  ],
};
