import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-flow',
  title: '06. Control Flow',
  explanation: `## Control Flow in PHP\n\nPHP provides the standard control flow constructs plus some PHP-specific features.\n\n### if / elseif / else\n\n\`\`\`php\nif (\$age >= 18) {\n    echo "Adult";\n} elseif (\$age >= 13) {\n    echo "Teen";\n} else {\n    echo "Child";\n}\n\`\`\`\n\n### switch\n\n\`\`\`php\nswitch (\$color) {\n    case "red":\n        echo "Stop";\n        break;\n    case "green":\n        echo "Go";\n        break;\n    default:\n        echo "Unknown";\n}\n\`\`\`\n\n### match Expression (PHP 8)\n\nA strict, expression-based alternative to switch:\n\n\`\`\`php\n\$result = match(\$status) {\n    200 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n    default => "Unknown",\n};\n\`\`\`\n\n### Loops\n\n\`\`\`php\nfor (\$i = 0; \$i < 10; \$i++) { ... }\nwhile (\$condition) { ... }\ndo { ... } while (\$condition);\nforeach (\$arr as \$val) { ... }\n\`\`\`\n\n### break and continue\n\n\`break\` exits a loop. \`continue\` skips to the next iteration. Both accept an optional numeric level for nested loops:\n\n\`\`\`php\nbreak 2;    // break out of 2 levels\ncontinue 2; // continue outer loop\n\`\`\``,
  exercises: [
    {
      id: 'php-flow-1',
      title: 'Basic if Statement',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Complete the if condition to check if $age is 18 or older.',
      skeleton: `<?php\n\$age = 21;\nif (\$age ___ 18) {\n    echo "Adult";\n}`,
      solution: `<?php\n\$age = 21;\nif (\$age >= 18) {\n    echo "Adult";\n}`,
      hints: ['Use the >= operator for "greater than or equal"', 'Check if $age is at least 18', 'The operator goes between $age and 18'],
      concepts: ['if-statement', 'comparison-operators'],
    },
    {
      id: 'php-flow-2',
      title: 'Match Expression',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Use a match expression to map HTTP status codes to messages.',
      skeleton: `<?php\n\$code = 404;\n\$msg = ___(\$code) {\n    200 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n    default => "Unknown",\n};\necho \$msg;`,
      solution: `<?php\n\$code = 404;\n\$msg = match(\$code) {\n    200 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n    default => "Unknown",\n};\necho \$msg;`,
      hints: ['The match expression was introduced in PHP 8', 'It uses strict comparison (===)', 'The syntax is match($value) { ... }'],
      concepts: ['match-expression', 'php8'],
    },
    {
      id: 'php-flow-3',
      title: 'For Loop Range',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a for loop that prints numbers 1 through 5.',
      skeleton: `<?php\nfor (\$i = ___; \$i <= ___; \$i++) {\n    echo \$i . " ";\n}`,
      solution: `<?php\nfor (\$i = 1; \$i <= 5; \$i++) {\n    echo \$i . " ";\n}`,
      hints: ['Start at 1 and end at 5', 'Use <= for the condition', '$i++ increments by 1 each iteration'],
      concepts: ['for-loop', 'iteration'],
    },
    {
      id: 'php-flow-4',
      title: 'While Loop',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Complete the while loop to count down from 5 to 1.',
      skeleton: `<?php\n\$n = 5;\nwhile (\$n ___ 0) {\n    echo \$n . " ";\n    \$n--;\n}`,
      solution: `<?php\n\$n = 5;\nwhile (\$n > 0) {\n    echo \$n . " ";\n    \$n--;\n}`,
      hints: ['Continue while $n is greater than 0', 'Use the > operator', '$n-- decrements $n each iteration'],
      concepts: ['while-loop', 'countdown'],
    },
    {
      id: 'php-flow-5',
      title: 'elseif Chain',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Complete the elseif chain to classify a temperature.',
      skeleton: `<?php\n\$temp = 25;\nif (\$temp >= 30) {\n    echo "Hot";\n} ___ (\$temp >= 20) {\n    echo "Warm";\n} else {\n    echo "Cold";\n}`,
      solution: `<?php\n\$temp = 25;\nif (\$temp >= 30) {\n    echo "Hot";\n} elseif (\$temp >= 20) {\n    echo "Warm";\n} else {\n    echo "Cold";\n}`,
      hints: ['PHP uses elseif (one word) or else if (two words)', 'Place it between if and else', 'elseif is the most common PHP convention'],
      concepts: ['elseif', 'conditional-chains'],
    },
    {
      id: 'php-flow-6',
      title: 'Switch with Break',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Add the missing break statements to prevent fall-through.',
      skeleton: `<?php\n\$day = "Mon";\nswitch (\$day) {\n    case "Mon":\n    case "Tue":\n    case "Wed":\n    case "Thu":\n    case "Fri":\n        echo "Weekday";\n        ___;\n    case "Sat":\n    case "Sun":\n        echo "Weekend";\n        ___;\n}`,
      solution: `<?php\n\$day = "Mon";\nswitch (\$day) {\n    case "Mon":\n    case "Tue":\n    case "Wed":\n    case "Thu":\n    case "Fri":\n        echo "Weekday";\n        break;\n    case "Sat":\n    case "Sun":\n        echo "Weekend";\n        break;\n}`,
      hints: ['Use break to prevent falling through to the next case', 'Without break, execution continues into the next case', 'Each group of cases needs a break at the end'],
      concepts: ['switch', 'break', 'fall-through'],
    },
    {
      id: 'php-flow-7',
      title: 'Write a FizzBuzz Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function fizzBuzz(int $n): string that returns "FizzBuzz" if divisible by both 3 and 5, "Fizz" if by 3, "Buzz" if by 5, or the number as a string.',
      skeleton: `<?php\n// Write function fizzBuzz(int \$n): string\n`,
      solution: `<?php\nfunction fizzBuzz(int \$n): string {\n    if (\$n % 15 === 0) return "FizzBuzz";\n    if (\$n % 3 === 0) return "Fizz";\n    if (\$n % 5 === 0) return "Buzz";\n    return (string)\$n;\n}`,
      hints: ['Check divisible by 15 first (both 3 and 5)', 'Use the modulus operator %', 'Cast to string for the default case'],
      concepts: ['modulus', 'if-statements', 'fizzbuzz'],
    },
    {
      id: 'php-flow-8',
      title: 'Write a Number Classifier with match',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function classify(int $n): string using match(true) that returns "negative" for <0, "zero" for 0, "small" for 1-10, "large" for >10.',
      skeleton: `<?php\n// Write function classify(int \$n): string using match(true)\n`,
      solution: `<?php\nfunction classify(int \$n): string {\n    return match(true) {\n        \$n < 0 => "negative",\n        \$n === 0 => "zero",\n        \$n <= 10 => "small",\n        default => "large",\n    };\n}`,
      hints: ['match(true) allows using conditions as arms', 'Each arm is a boolean expression => result', 'Arms are checked in order, first match wins'],
      concepts: ['match-expression', 'match-true', 'classification'],
    },
    {
      id: 'php-flow-9',
      title: 'Write a Retry Loop',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function retry(callable $fn, int $maxAttempts): mixed that calls $fn() up to $maxAttempts times, returning the result on success, or null if all attempts throw.',
      skeleton: `<?php\n// Write function retry(callable \$fn, int \$maxAttempts): mixed\n`,
      solution: `<?php\nfunction retry(callable \$fn, int \$maxAttempts): mixed {\n    for (\$i = 0; \$i < \$maxAttempts; \$i++) {\n        try {\n            return \$fn();\n        } catch (\\Exception \$e) {\n            continue;\n        }\n    }\n    return null;\n}`,
      hints: ['Use a for loop for the attempts', 'Wrap $fn() in a try-catch block', 'Return null if all attempts fail'],
      concepts: ['for-loop', 'try-catch', 'retry-pattern'],
    },
    {
      id: 'php-flow-10',
      title: 'Write a Do-While Validator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function generateEven(callable $generator): int that calls $generator() in a do-while loop until it returns an even number.',
      skeleton: `<?php\n// Write function generateEven(callable \$generator): int\n`,
      solution: `<?php\nfunction generateEven(callable \$generator): int {\n    do {\n        \$val = \$generator();\n    } while (\$val % 2 !== 0);\n    return \$val;\n}`,
      hints: ['Use do-while to ensure at least one call', 'Check if the value is odd in the while condition', 'Return the value once it is even'],
      concepts: ['do-while', 'callable', 'validation'],
    },
    {
      id: 'php-flow-11',
      title: 'Write a Range Collector',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write a function collectRange(int $start, int $end): array that returns an array of integers from $start to $end inclusive using a for loop.',
      skeleton: `<?php\n// Write function collectRange(int \$start, int \$end): array\n`,
      solution: `<?php\nfunction collectRange(int \$start, int \$end): array {\n    \$result = [];\n    for (\$i = \$start; \$i <= \$end; \$i++) {\n        \$result[] = \$i;\n    }\n    return \$result;\n}`,
      hints: ['Use a for loop from $start to $end', 'Append each value with $result[] = $i', 'You could also use range($start, $end)'],
      concepts: ['for-loop', 'array-building'],
    },
    {
      id: 'php-flow-12',
      title: 'Write a Continue Filter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function skipNegatives(array $nums): array that uses continue to skip negative numbers and collects only non-negative ones.',
      skeleton: `<?php\n// Write function skipNegatives(array \$nums): array using continue\n`,
      solution: `<?php\nfunction skipNegatives(array \$nums): array {\n    \$result = [];\n    foreach (\$nums as \$n) {\n        if (\$n < 0) continue;\n        \$result[] = \$n;\n    }\n    return \$result;\n}`,
      hints: ['Use continue to skip to the next iteration', 'Check if $n < 0 and continue if so', 'Collect non-negative values in $result'],
      concepts: ['continue', 'foreach', 'filtering'],
    },
    {
      id: 'php-flow-13',
      title: 'Fix: Missing break in switch',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the switch: "apple" should only print "Fruit" but it falls through to "Unknown" because of a missing break.',
      skeleton: `<?php\n\$item = "apple";\nswitch (\$item) {\n    case "apple":\n        echo "Fruit";\n    case "carrot":\n        echo "Vegetable";\n    default:\n        echo "Unknown";\n}`,
      solution: `<?php\n\$item = "apple";\nswitch (\$item) {\n    case "apple":\n        echo "Fruit";\n        break;\n    case "carrot":\n        echo "Vegetable";\n        break;\n    default:\n        echo "Unknown";\n}`,
      hints: ['Without break, execution falls through to the next case', 'Add break after each echo statement', 'Each case block needs its own break'],
      concepts: ['switch', 'break', 'fall-through'],
    },
    {
      id: 'php-flow-14',
      title: 'Fix: Infinite While Loop',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the infinite loop: $i is never incremented.',
      skeleton: `<?php\n\$i = 0;\nwhile (\$i < 5) {\n    echo \$i . " ";\n}\n// Never terminates!`,
      solution: `<?php\n\$i = 0;\nwhile (\$i < 5) {\n    echo \$i . " ";\n    \$i++;\n}`,
      hints: ['The loop condition never becomes false', 'Add $i++ inside the loop body', 'Without incrementing, $i stays 0 forever'],
      concepts: ['while-loop', 'infinite-loop', 'increment'],
    },
    {
      id: 'php-flow-15',
      title: 'Fix: match Without Default',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the match expression: it throws an UnhandledMatchError when $status is 403 because there is no default arm.',
      skeleton: `<?php\n\$status = 403;\n\$msg = match(\$status) {\n    200 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n};\necho \$msg;`,
      solution: `<?php\n\$status = 403;\n\$msg = match(\$status) {\n    200 => "OK",\n    404 => "Not Found",\n    500 => "Server Error",\n    default => "Unknown",\n};\necho \$msg;`,
      hints: ['match throws UnhandledMatchError if no arm matches', 'Add a default arm to handle unexpected values', 'default => "Unknown" catches all unmatched cases'],
      concepts: ['match-expression', 'default-arm', 'error-handling'],
    },
    {
      id: 'php-flow-16',
      title: 'Predict: match vs switch Strictness',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$val = "1";\n\$result = match(\$val) {\n    1 => "integer one",\n    "1" => "string one",\n    default => "other",\n};\necho \$result;`,
      solution: `string one`,
      hints: ['match uses strict comparison (===)', '"1" === 1 is false, "1" === "1" is true', 'Unlike switch, match does not do type juggling'],
      concepts: ['match-expression', 'strict-comparison'],
    },
    {
      id: 'php-flow-17',
      title: 'Predict: for Loop with Continue',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nfor (\$i = 1; \$i <= 5; \$i++) {\n    if (\$i === 3) continue;\n    echo \$i;\n}`,
      solution: `1245`,
      hints: ['continue skips the rest of the loop body for that iteration', 'When $i is 3, echo is skipped', 'All other values are printed'],
      concepts: ['continue', 'for-loop'],
    },
    {
      id: 'php-flow-18',
      title: 'Predict: do-while Executes at Least Once',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$x = 10;\ndo {\n    echo \$x;\n} while (\$x < 5);`,
      solution: `10`,
      hints: ['do-while always executes the body at least once', 'The condition is checked after the body runs', '$x is 10 which is not < 5, so the loop exits after one iteration'],
      concepts: ['do-while', 'loop-execution'],
    },
    {
      id: 'php-flow-19',
      title: 'Refactor: Replace switch with match',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the switch statement to use a PHP 8 match expression.',
      skeleton: `<?php\n\$role = "admin";\nswitch (\$role) {\n    case "admin":\n        \$level = 3;\n        break;\n    case "editor":\n        \$level = 2;\n        break;\n    case "viewer":\n        \$level = 1;\n        break;\n    default:\n        \$level = 0;\n        break;\n}\necho \$level;`,
      solution: `<?php\n\$role = "admin";\n\$level = match(\$role) {\n    "admin" => 3,\n    "editor" => 2,\n    "viewer" => 1,\n    default => 0,\n};\necho \$level;`,
      hints: ['match is an expression, so assign it directly to $level', 'Use => instead of case/break blocks', 'No break statements needed in match'],
      concepts: ['match-expression', 'switch', 'refactoring'],
    },
    {
      id: 'php-flow-20',
      title: 'Refactor: Replace Nested ifs with Early Returns',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the deeply nested if statements into guard clauses with early returns.',
      skeleton: `<?php\nfunction processOrder(array \$order): string {\n    if (isset(\$order["items"])) {\n        if (count(\$order["items"]) > 0) {\n            if (isset(\$order["payment"])) {\n                return "Order processed";\n            } else {\n                return "No payment";\n            }\n        } else {\n            return "Empty cart";\n        }\n    } else {\n        return "No items";\n    }\n}`,
      solution: `<?php\nfunction processOrder(array \$order): string {\n    if (!isset(\$order["items"])) return "No items";\n    if (count(\$order["items"]) === 0) return "Empty cart";\n    if (!isset(\$order["payment"])) return "No payment";\n    return "Order processed";\n}`,
      hints: ['Invert each condition and return early', 'This flattens the nesting', 'The happy path is the last return statement'],
      concepts: ['guard-clauses', 'early-returns', 'refactoring'],
    },
  ],
};
