import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-func',
  title: '07. Functions',
  explanation: `## Functions in PHP\n\nFunctions are declared with the \`function\` keyword and support type declarations for parameters and return values.\n\n### Basic Declaration\n\n\`\`\`php\nfunction greet(string \$name): string {\n    return "Hello, \$name!";\n}\n\`\`\`\n\n### Default Parameters\n\n\`\`\`php\nfunction greet(string \$name = "World"): string {\n    return "Hello, \$name!";\n}\n\`\`\`\n\n### Nullable Types\n\n\`\`\`php\nfunction find(int \$id): ?string {\n    return \$id === 1 ? "Alice" : null;\n}\n\`\`\`\n\n### Variadic Arguments\n\n\`\`\`php\nfunction sum(int ...\$nums): int {\n    return array_sum(\$nums);\n}\nsum(1, 2, 3); // 6\n\`\`\`\n\n### Named Arguments (PHP 8)\n\nCall functions with named parameters in any order:\n\n\`\`\`php\nfunction createUser(string \$name, int \$age, string \$role = "user"): array {\n    return compact('name', 'age', 'role');\n}\n\ncreateUser(age: 30, name: "Alice");\n\`\`\`\n\n### Return Types\n\n\`\`\`php\nfunction process(): void { /* no return */ }\nfunction getData(): array { return []; }\nfunction calc(): int|float { return 3.14; }\n\`\`\``,
  exercises: [
    {
      id: 'php-func-1',
      title: 'Declare a Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Declare a function named greet that takes a string $name and returns a greeting.',
      skeleton: `<?php\n___ greet(string \$name): string {\n    return "Hello, \$name!";\n}`,
      solution: `<?php\nfunction greet(string \$name): string {\n    return "Hello, \$name!";\n}`,
      hints: ['Functions are declared with the function keyword', 'Place it before the function name', 'The syntax is function name(params): returnType'],
      concepts: ['function-declaration', 'return-types'],
    },
    {
      id: 'php-func-2',
      title: 'Default Parameter Value',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Give the $greeting parameter a default value of "Hello".',
      skeleton: `<?php\nfunction sayHi(string \$name, string \$greeting ___): string {\n    return "\$greeting, \$name!";\n}\necho sayHi("Alice"); // Hello, Alice!`,
      solution: `<?php\nfunction sayHi(string \$name, string \$greeting = "Hello"): string {\n    return "\$greeting, \$name!";\n}\necho sayHi("Alice"); // Hello, Alice!`,
      hints: ['Use = to assign a default value', 'Parameters with defaults must come after required ones', 'The syntax is $param = "default"'],
      concepts: ['default-parameters', 'optional-arguments'],
    },
    {
      id: 'php-func-3',
      title: 'Variadic Arguments',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Use variadic arguments to accept any number of integers.',
      skeleton: `<?php\nfunction sum(int ___\$nums): int {\n    return array_sum(\$nums);\n}\necho sum(1, 2, 3, 4); // 10`,
      solution: `<?php\nfunction sum(int ...\$nums): int {\n    return array_sum(\$nums);\n}\necho sum(1, 2, 3, 4); // 10`,
      hints: ['Use ... (splat operator) before the parameter name', 'The type hint applies to each individual argument', '$nums becomes an array inside the function'],
      concepts: ['variadic-arguments', 'splat-operator'],
    },
    {
      id: 'php-func-4',
      title: 'Named Arguments',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Call the function using named arguments to skip the $age parameter.',
      skeleton: `<?php\nfunction createProfile(string \$name, int \$age = 0, string \$city = "Unknown"): string {\n    return "\$name, \$age, \$city";\n}\necho createProfile(___ "Alice", ___ "NYC");`,
      solution: `<?php\nfunction createProfile(string \$name, int \$age = 0, string \$city = "Unknown"): string {\n    return "\$name, \$age, \$city";\n}\necho createProfile(name: "Alice", city: "NYC");`,
      hints: ['Named arguments use paramName: value syntax', 'You can skip optional parameters with named args', 'PHP 8 introduced named arguments'],
      concepts: ['named-arguments', 'php8'],
    },
    {
      id: 'php-func-5',
      title: 'Void Return Type',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Declare the return type as void since the function does not return a value.',
      skeleton: `<?php\nfunction logMessage(string \$msg): ___ {\n    echo "[LOG] \$msg\\n";\n}`,
      solution: `<?php\nfunction logMessage(string \$msg): void {\n    echo "[LOG] \$msg\\n";\n}`,
      hints: ['Use void when a function returns nothing', 'A void function cannot have a return value', 'It can still use return; (without a value) to exit early'],
      concepts: ['void-return', 'return-types'],
    },
    {
      id: 'php-func-6',
      title: 'Union Return Type',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Declare the return type as int|false since strpos can return false.',
      skeleton: `<?php\nfunction findChar(string \$haystack, string \$needle): ___ {\n    return strpos(\$haystack, \$needle);\n}`,
      solution: `<?php\nfunction findChar(string \$haystack, string \$needle): int|false {\n    return strpos(\$haystack, \$needle);\n}`,
      hints: ['PHP 8 supports union types with |', 'strpos returns int on success, false on failure', 'The syntax is int|false'],
      concepts: ['union-types', 'return-types', 'php8'],
    },
    {
      id: 'php-func-7',
      title: 'Write a Recursive Factorial',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function factorial(int $n): int that computes the factorial recursively.',
      skeleton: `<?php\n// Write function factorial(int \$n): int\n`,
      solution: `<?php\nfunction factorial(int \$n): int {\n    if (\$n <= 1) return 1;\n    return \$n * factorial(\$n - 1);\n}`,
      hints: ['Base case: factorial of 0 or 1 is 1', 'Recursive case: n * factorial(n - 1)', 'Call the function within itself'],
      concepts: ['recursion', 'base-case', 'factorial'],
    },
    {
      id: 'php-func-8',
      title: 'Write a Curry-like Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function multiply(int $a) that returns a callable which takes int $b and returns $a * $b.',
      skeleton: `<?php\n// Write function multiply(int \$a) that returns a closure multiplying by \$a\n`,
      solution: `<?php\nfunction multiply(int \$a): callable {\n    return fn(int \$b): int => \$a * \$b;\n}`,
      hints: ['Return a closure (arrow function) from the function', 'The inner function captures $a from the outer scope', 'Arrow functions automatically capture variables'],
      concepts: ['closures', 'arrow-functions', 'higher-order-functions'],
    },
    {
      id: 'php-func-9',
      title: 'Write a Pipe Function',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function pipe(mixed $value, callable ...$fns): mixed that passes $value through each function in order.',
      skeleton: `<?php\n// Write function pipe(mixed \$value, callable ...\$fns): mixed\n`,
      solution: `<?php\nfunction pipe(mixed \$value, callable ...\$fns): mixed {\n    foreach (\$fns as \$fn) {\n        \$value = \$fn(\$value);\n    }\n    return \$value;\n}`,
      hints: ['Loop through each function with foreach', 'Pass the current $value to each function', 'Reassign $value with the result each time'],
      concepts: ['variadic-arguments', 'callable', 'pipe-pattern'],
    },
    {
      id: 'php-func-10',
      title: 'Write an Array Reducer',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function reduce(array $arr, callable $fn, mixed $initial): mixed that reduces an array to a single value.',
      skeleton: `<?php\n// Write function reduce(array \$arr, callable \$fn, mixed \$initial): mixed\n`,
      solution: `<?php\nfunction reduce(array \$arr, callable \$fn, mixed \$initial): mixed {\n    \$acc = \$initial;\n    foreach (\$arr as \$item) {\n        \$acc = \$fn(\$acc, \$item);\n    }\n    return \$acc;\n}`,
      hints: ['Start with $initial as the accumulator', 'Call $fn($accumulator, $item) for each element', 'Return the final accumulator value'],
      concepts: ['reduce', 'callable', 'accumulator-pattern'],
    },
    {
      id: 'php-func-11',
      title: 'Write a Memoizer',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function memoize(callable $fn): callable that caches results based on the first argument.',
      skeleton: `<?php\n// Write function memoize(callable \$fn): callable\n`,
      solution: `<?php\nfunction memoize(callable \$fn): callable {\n    \$cache = [];\n    return function () use (\$fn, &\$cache) {\n        \$key = serialize(func_get_args());\n        if (!array_key_exists(\$key, \$cache)) {\n            \$cache[\$key] = \$fn(...func_get_args());\n        }\n        return \$cache[\$key];\n    };\n}`,
      hints: ['Use a closure to capture a $cache array by reference', 'Serialize the arguments as a cache key', 'Check the cache before calling $fn'],
      concepts: ['memoization', 'closures', 'caching'],
    },
    {
      id: 'php-func-12',
      title: 'Write a Validator Builder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function between(int $min, int $max): callable that returns a function checking if a number is between $min and $max inclusive.',
      skeleton: `<?php\n// Write function between(int \$min, int \$max): callable\n`,
      solution: `<?php\nfunction between(int \$min, int \$max): callable {\n    return fn(int \$val): bool => \$val >= \$min && \$val <= \$max;\n}`,
      hints: ['Return an arrow function that checks the range', 'Arrow functions capture outer variables automatically', 'The returned function takes one parameter and returns bool'],
      concepts: ['higher-order-functions', 'arrow-functions', 'validation'],
    },
    {
      id: 'php-func-13',
      title: 'Fix: Missing Return Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the function: it returns a string but has no return type declaration. Add the proper return type.',
      skeleton: `<?php\ndeclare(strict_types=1);\n\nfunction getName() {\n    return "Alice";\n}\necho getName();`,
      solution: `<?php\ndeclare(strict_types=1);\n\nfunction getName(): string {\n    return "Alice";\n}\necho getName();`,
      hints: ['Add : string after the parameter list', 'Return type declarations come after the closing parenthesis', 'This is good practice especially with strict_types'],
      concepts: ['return-types', 'strict-types'],
    },
    {
      id: 'php-func-14',
      title: 'Fix: Variadic Must Be Last',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the function: the variadic parameter must be the last parameter.',
      skeleton: `<?php\nfunction tag(string ...\$classes, string \$content): string {\n    \$cls = implode(" ", \$classes);\n    return "<div class=\\\"\$cls\\\">\$content</div>";\n}`,
      solution: `<?php\nfunction tag(string \$content, string ...\$classes): string {\n    \$cls = implode(" ", \$classes);\n    return "<div class=\\\"\$cls\\\">\$content</div>";\n}`,
      hints: ['Variadic parameters must come last', 'Move $content before ...$classes', 'Only one variadic parameter is allowed per function'],
      concepts: ['variadic-arguments', 'parameter-order'],
    },
    {
      id: 'php-func-15',
      title: 'Fix: Default Before Required',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the parameter order: required parameters must come before optional ones.',
      skeleton: `<?php\nfunction greet(string \$greeting = "Hello", string \$name): string {\n    return "\$greeting, \$name!";\n}\necho greet("Alice");`,
      solution: `<?php\nfunction greet(string \$name, string \$greeting = "Hello"): string {\n    return "\$greeting, \$name!";\n}\necho greet("Alice");`,
      hints: ['Required parameters must come before optional ones', 'Move $name before $greeting', '$greeting has a default so it should be last'],
      concepts: ['parameter-order', 'default-parameters'],
    },
    {
      id: 'php-func-16',
      title: 'Predict: Named Arguments Order',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nfunction info(string \$name, int \$age): string {\n    return "\$name is \$age";\n}\necho info(age: 25, name: "Bob");`,
      solution: `Bob is 25`,
      hints: ['Named arguments can be in any order', 'name: "Bob" maps to $name, age: 25 maps to $age', 'The output follows the function body, not the call order'],
      concepts: ['named-arguments', 'parameter-binding'],
    },
    {
      id: 'php-func-17',
      title: 'Predict: Variadic Arguments',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nfunction first(string ...\$args): string {\n    return \$args[0];\n}\necho first("a", "b", "c");`,
      solution: `a`,
      hints: ['Variadic args become an array', '$args is ["a", "b", "c"]', '$args[0] is "a"'],
      concepts: ['variadic-arguments', 'array-access'],
    },
    {
      id: 'php-func-18',
      title: 'Predict: Recursive Countdown',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nfunction countdown(int \$n): void {\n    if (\$n <= 0) return;\n    echo \$n;\n    countdown(\$n - 1);\n}\ncountdown(3);`,
      solution: `321`,
      hints: ['countdown(3) prints 3, then calls countdown(2)', 'countdown(2) prints 2, then calls countdown(1)', 'countdown(1) prints 1, then calls countdown(0) which returns'],
      concepts: ['recursion', 'void-return'],
    },
    {
      id: 'php-func-19',
      title: 'Refactor: Extract Repeated Logic',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the repeated formatting logic into a reusable function.',
      skeleton: `<?php\n\$price1 = 19.99;\n\$price2 = 5.50;\n\$price3 = 100.00;\n\necho "$" . number_format(\$price1, 2) . "\\n";\necho "$" . number_format(\$price2, 2) . "\\n";\necho "$" . number_format(\$price3, 2) . "\\n";`,
      solution: `<?php\nfunction formatPrice(float \$price): string {\n    return "$" . number_format(\$price, 2);\n}\n\n\$price1 = 19.99;\n\$price2 = 5.50;\n\$price3 = 100.00;\n\necho formatPrice(\$price1) . "\\n";\necho formatPrice(\$price2) . "\\n";\necho formatPrice(\$price3) . "\\n";`,
      hints: ['Create a function that handles the formatting', 'The function takes a float and returns a formatted string', 'Replace each repeated pattern with a function call'],
      concepts: ['function-extraction', 'DRY-principle', 'refactoring'],
    },
    {
      id: 'php-func-20',
      title: 'Refactor: Use Named Arguments for Clarity',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the function call to use named arguments for better readability.',
      skeleton: `<?php\nfunction createUser(string \$name, string \$email, string \$role, bool \$active, int \$age): array {\n    return compact('name', 'email', 'role', 'active', 'age');\n}\n\n\$user = createUser("Alice", "alice@test.com", "admin", true, 30);`,
      solution: `<?php\nfunction createUser(string \$name, string \$email, string \$role, bool \$active, int \$age): array {\n    return compact('name', 'email', 'role', 'active', 'age');\n}\n\n\$user = createUser(\n    name: "Alice",\n    email: "alice@test.com",\n    role: "admin",\n    active: true,\n    age: 30,\n);`,
      hints: ['Named arguments make the call self-documenting', 'Each argument is labeled with paramName: value', 'Especially helpful when there are many parameters'],
      concepts: ['named-arguments', 'readability', 'refactoring'],
    },
  ],
};
