import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-closures',
  title: '08. Closures',
  explanation: `## Closures in PHP\n\nClosures are anonymous functions that can capture variables from their surrounding scope.\n\n### Anonymous Functions\n\n\`\`\`php\n\$greet = function(string \$name): string {\n    return "Hello, \$name!";\n};\necho \$greet("Alice"); // Hello, Alice!\n\`\`\`\n\n### The \`use\` Keyword\n\nUnlike JavaScript, PHP closures do not automatically capture outer variables. Use the \`use\` keyword:\n\n\`\`\`php\n\$prefix = "Dear";\n\$greet = function(string \$name) use (\$prefix): string {\n    return "\$prefix \$name";\n};\n\`\`\`\n\nTo modify the captured variable, pass it by reference:\n\n\`\`\`php\n\$count = 0;\n\$inc = function() use (&\$count): void {\n    \$count++;\n};\n\`\`\`\n\n### Arrow Functions (PHP 7.4+)\n\nArrow functions are short closures that automatically capture variables by value:\n\n\`\`\`php\n\$double = fn(int \$n): int => \$n * 2;\n\`\`\`\n\n### Closure::bind\n\nBind a closure to a specific object and class scope:\n\n\`\`\`php\n\$fn = Closure::bind(function() {\n    return \$this->secret;\n}, \$obj, get_class(\$obj));\n\`\`\`\n\n### First-Class Callable Syntax (PHP 8.1)\n\n\`\`\`php\n\$fn = strlen(...);\necho \$fn("hello"); // 5\n\`\`\``,
  exercises: [
    {
      id: 'php-closures-1',
      title: 'Create an Anonymous Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Assign an anonymous function to $double that doubles a number.',
      skeleton: `<?php\n\$double = ___(int \$n): int {\n    return \$n * 2;\n};\necho \$double(5); // 10`,
      solution: `<?php\n\$double = function(int \$n): int {\n    return \$n * 2;\n};\necho \$double(5); // 10`,
      hints: ['Anonymous functions start with the function keyword', 'No function name is needed', 'Note the semicolon after the closing brace'],
      concepts: ['anonymous-functions', 'closures'],
    },
    {
      id: 'php-closures-2',
      title: 'Capture Variable with use',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Capture the $multiplier variable using the use keyword.',
      skeleton: `<?php\n\$multiplier = 3;\n\$multiply = function(int \$n) ___(\$multiplier): int {\n    return \$n * \$multiplier;\n};\necho \$multiply(4); // 12`,
      solution: `<?php\n\$multiplier = 3;\n\$multiply = function(int \$n) use (\$multiplier): int {\n    return \$n * \$multiplier;\n};\necho \$multiply(4); // 12`,
      hints: ['The use keyword imports variables from the outer scope', 'Place use() between the parameter list and return type', 'Variables are captured by value by default'],
      concepts: ['use-keyword', 'variable-capture'],
    },
    {
      id: 'php-closures-3',
      title: 'Arrow Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Create an arrow function that triples a number.',
      skeleton: `<?php\n\$triple = ___(int \$n): int => \$n * 3;\necho \$triple(4); // 12`,
      solution: `<?php\n\$triple = fn(int \$n): int => \$n * 3;\necho \$triple(4); // 12`,
      hints: ['Arrow functions use the fn keyword', 'The syntax is fn(params) => expression', 'Arrow functions auto-capture outer variables by value'],
      concepts: ['arrow-functions', 'fn-keyword'],
    },
    {
      id: 'php-closures-4',
      title: 'Capture by Reference',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Capture $counter by reference so the closure can modify it.',
      skeleton: `<?php\n\$counter = 0;\n\$inc = function() use (___\$counter): void {\n    \$counter++;\n};\n\$inc();\n\$inc();\necho \$counter; // 2`,
      solution: `<?php\n\$counter = 0;\n\$inc = function() use (&\$counter): void {\n    \$counter++;\n};\n\$inc();\n\$inc();\necho \$counter; // 2`,
      hints: ['Use & before the variable name in the use clause', 'Without &, the closure gets a copy', 'With &, modifications affect the outer variable'],
      concepts: ['capture-by-reference', 'closures'],
    },
    {
      id: 'php-closures-5',
      title: 'First-Class Callable',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Create a first-class callable reference to strlen.',
      skeleton: `<?php\n\$len = ___;\necho \$len("hello"); // 5`,
      solution: `<?php\n\$len = strlen(...);\necho \$len("hello"); // 5`,
      hints: ['PHP 8.1 introduced first-class callable syntax', 'Use functionName(...) to create a callable reference', 'The ... is literal syntax, not the spread operator here'],
      concepts: ['first-class-callable', 'php81'],
    },
    {
      id: 'php-closures-6',
      title: 'Closure as Callback',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Pass an arrow function to array_map to square each number.',
      skeleton: `<?php\n\$nums = [1, 2, 3, 4];\n\$squared = array_map(___, \$nums);\nprint_r(\$squared); // [1, 4, 9, 16]`,
      solution: `<?php\n\$nums = [1, 2, 3, 4];\n\$squared = array_map(fn(\$n) => \$n ** 2, \$nums);\nprint_r(\$squared); // [1, 4, 9, 16]`,
      hints: ['Use fn($n) => $n ** 2 as the callback', 'Arrow functions work perfectly as inline callbacks', '** is the exponentiation operator'],
      concepts: ['arrow-functions', 'array_map', 'callbacks'],
    },
    {
      id: 'php-closures-7',
      title: 'Write a Counter Factory',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function makeCounter(int $start = 0): callable that returns a closure which returns the next integer each time it is called.',
      skeleton: `<?php\n// Write function makeCounter(int \$start = 0): callable\n`,
      solution: `<?php\nfunction makeCounter(int \$start = 0): callable {\n    \$count = \$start;\n    return function() use (&\$count): int {\n        return \$count++;\n    };\n}`,
      hints: ['Capture $count by reference with &', 'The closure increments and returns $count', 'Use post-increment $count++ to return then increment'],
      concepts: ['closures', 'capture-by-reference', 'factory-pattern'],
    },
    {
      id: 'php-closures-8',
      title: 'Write a Function Composer',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function compose(callable $f, callable $g): callable that returns a function computing $f($g($x)).',
      skeleton: `<?php\n// Write function compose(callable \$f, callable \$g): callable\n`,
      solution: `<?php\nfunction compose(callable \$f, callable \$g): callable {\n    return fn(mixed \$x): mixed => \$f(\$g(\$x));\n}`,
      hints: ['Return an arrow function that calls $g then $f', 'Arrow functions auto-capture $f and $g', 'The composition is f(g(x))'],
      concepts: ['composition', 'arrow-functions', 'higher-order-functions'],
    },
    {
      id: 'php-closures-9',
      title: 'Write a Once Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function once(callable $fn): callable that ensures $fn is only called once. Subsequent calls return the cached result.',
      skeleton: `<?php\n// Write function once(callable \$fn): callable\n`,
      solution: `<?php\nfunction once(callable \$fn): callable {\n    \$called = false;\n    \$result = null;\n    return function() use (\$fn, &\$called, &\$result): mixed {\n        if (!\$called) {\n            \$result = \$fn(...func_get_args());\n            \$called = true;\n        }\n        return \$result;\n    };\n}`,
      hints: ['Track if the function has been called with a boolean flag', 'Cache the result and return it on subsequent calls', 'Capture both the flag and result by reference'],
      concepts: ['closures', 'caching', 'once-pattern'],
    },
    {
      id: 'php-closures-10',
      title: 'Write a Partial Application',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a function partial(callable $fn, mixed ...$partial): callable that returns a closure which prepends $partial args before any new args.',
      skeleton: `<?php\n// Write function partial(callable \$fn, mixed ...\$partial): callable\n`,
      solution: `<?php\nfunction partial(callable \$fn, mixed ...\$partial): callable {\n    return function(mixed ...\$args) use (\$fn, \$partial): mixed {\n        return \$fn(...\$partial, ...\$args);\n    };\n}`,
      hints: ['Capture $fn and $partial in the closure', 'Spread both $partial and $args when calling $fn', 'Use the ... operator to unpack arrays as arguments'],
      concepts: ['partial-application', 'closures', 'spread-operator'],
    },
    {
      id: 'php-closures-11',
      title: 'Write a Debounce Timer Tracker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function makeThrottled(callable $fn, int $limit): callable that returns a closure which only calls $fn if at least $limit seconds have passed since the last call (using time()).',
      skeleton: `<?php\n// Write function makeThrottled(callable \$fn, int \$limit): callable\n`,
      solution: `<?php\nfunction makeThrottled(callable \$fn, int \$limit): callable {\n    \$lastCall = 0;\n    return function() use (\$fn, \$limit, &\$lastCall): mixed {\n        \$now = time();\n        if (\$now - \$lastCall >= \$limit) {\n            \$lastCall = \$now;\n            return \$fn(...func_get_args());\n        }\n        return null;\n    };\n}`,
      hints: ['Track the last call time with a reference variable', 'Compare time() with the last call time', 'Only call $fn if enough time has passed'],
      concepts: ['closures', 'throttling', 'time-tracking'],
    },
    {
      id: 'php-closures-12',
      title: 'Write a Tap Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a function tap(mixed $value, callable $fn): mixed that calls $fn($value) for side effects and returns $value unchanged.',
      skeleton: `<?php\n// Write function tap(mixed \$value, callable \$fn): mixed\n`,
      solution: `<?php\nfunction tap(mixed \$value, callable \$fn): mixed {\n    \$fn(\$value);\n    return \$value;\n}`,
      hints: ['Call $fn with $value', 'Ignore the return value of $fn', 'Return the original $value'],
      concepts: ['tap-pattern', 'side-effects', 'callables'],
    },
    {
      id: 'php-closures-13',
      title: 'Fix: Missing use Keyword',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the closure: it tries to use $prefix but does not capture it.',
      skeleton: `<?php\n\$prefix = "Hello";\n\$greet = function(string \$name): string {\n    return "\$prefix, \$name!";\n};\necho \$greet("Alice");`,
      solution: `<?php\n\$prefix = "Hello";\n\$greet = function(string \$name) use (\$prefix): string {\n    return "\$prefix, \$name!";\n};\necho \$greet("Alice");`,
      hints: ['PHP closures do not auto-capture outer variables', 'Add use ($prefix) to import the variable', 'Place use() between parameters and return type'],
      concepts: ['use-keyword', 'variable-capture', 'closures'],
    },
    {
      id: 'php-closures-14',
      title: 'Fix: Arrow Function Body',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the arrow function: it uses curly braces but arrow functions only support a single expression.',
      skeleton: `<?php\n\$process = fn(int \$n) => {\n    \$result = \$n * 2;\n    return \$result + 1;\n};\necho \$process(5);`,
      solution: `<?php\n\$process = function(int \$n): int {\n    \$result = \$n * 2;\n    return \$result + 1;\n};\necho \$process(5);`,
      hints: ['Arrow functions (fn =>) only support a single expression', 'For multiple statements, use a regular anonymous function', 'Change fn(...) => to function(...) { ... }'],
      concepts: ['arrow-functions', 'anonymous-functions', 'syntax-errors'],
    },
    {
      id: 'php-closures-15',
      title: 'Fix: Capture by Value Issue',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: the closure should accumulate values but captures $total by value instead of by reference.',
      skeleton: `<?php\n\$total = 0;\n\$add = function(int \$n) use (\$total): void {\n    \$total += \$n;\n};\n\$add(5);\n\$add(3);\necho \$total; // Should be 8 but is 0`,
      solution: `<?php\n\$total = 0;\n\$add = function(int \$n) use (&\$total): void {\n    \$total += \$n;\n};\n\$add(5);\n\$add(3);\necho \$total; // 8`,
      hints: ['Without &, the closure gets a copy of $total', 'Changes inside the closure do not affect the outer $total', 'Add & before $total in the use clause'],
      concepts: ['capture-by-reference', 'closures'],
    },
    {
      id: 'php-closures-16',
      title: 'Predict: Closure Captures at Definition Time',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$x = 10;\n\$fn = function() use (\$x): int { return \$x; };\n\$x = 20;\necho \$fn();`,
      solution: `10`,
      hints: ['use captures by value at the time the closure is created', 'Changing $x after creation does not affect the captured value', 'The closure captured 10, not a reference to $x'],
      concepts: ['capture-by-value', 'closure-creation-time'],
    },
    {
      id: 'php-closures-17',
      title: 'Predict: Arrow Function Auto-Capture',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$base = 100;\n\$calc = fn(int \$n): int => \$n + \$base;\necho \$calc(5);`,
      solution: `105`,
      hints: ['Arrow functions auto-capture outer variables by value', 'No use keyword needed', '$base is captured as 100, so 5 + 100 = 105'],
      concepts: ['arrow-functions', 'auto-capture'],
    },
    {
      id: 'php-closures-18',
      title: 'Predict: Reference Capture Mutation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\n\$arr = [1, 2, 3];\n\$adder = function(int \$val) use (&\$arr): void {\n    \$arr[] = \$val;\n};\n\$adder(4);\n\$adder(5);\necho count(\$arr);`,
      solution: `5`,
      hints: ['$arr is captured by reference', 'Each call appends to the original array', 'Starting with 3 elements + 2 additions = 5'],
      concepts: ['capture-by-reference', 'array-mutation'],
    },
    {
      id: 'php-closures-19',
      title: 'Refactor: Replace Anonymous Function with Arrow',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor the anonymous function to an arrow function.',
      skeleton: `<?php\n\$tax = 0.08;\n\$prices = [10, 20, 30];\n\$withTax = array_map(function(\$p) use (\$tax) {\n    return \$p * (1 + \$tax);\n}, \$prices);\nprint_r(\$withTax);`,
      solution: `<?php\n\$tax = 0.08;\n\$prices = [10, 20, 30];\n\$withTax = array_map(fn(\$p) => \$p * (1 + \$tax), \$prices);\nprint_r(\$withTax);`,
      hints: ['Arrow functions auto-capture variables, no use needed', 'Replace function($p) use ($tax) { return ...; } with fn($p) => ...', 'Arrow functions are ideal for short callbacks'],
      concepts: ['arrow-functions', 'refactoring', 'array_map'],
    },
    {
      id: 'php-closures-20',
      title: 'Refactor: Use First-Class Callable Syntax',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the closure wrapper to use PHP 8.1 first-class callable syntax.',
      skeleton: `<?php\n\$words = ["hello", "WORLD", "Foo"];\n\$lower = array_map(function(\$w) {\n    return strtolower(\$w);\n}, \$words);\nprint_r(\$lower);`,
      solution: `<?php\n\$words = ["hello", "WORLD", "Foo"];\n\$lower = array_map(strtolower(...), \$words);\nprint_r(\$lower);`,
      hints: ['PHP 8.1 lets you reference functions with functionName(...)', 'strtolower(...) creates a callable reference', 'No wrapper closure needed'],
      concepts: ['first-class-callable', 'php81', 'refactoring'],
    },
  ],
};
