import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-class',
  title: '09. Classes',
  explanation: `## Classes in PHP\n\nPHP supports full object-oriented programming with classes, properties, methods, and visibility modifiers.\n\n### Basic Class\n\n\`\`\`php\nclass User {\n    public string \$name;\n    public int \$age;\n\n    public function __construct(string \$name, int \$age) {\n        \$this->\$name = \$name;\n        \$this->age = \$age;\n    }\n\n    public function greet(): string {\n        return "Hi, I'm {\$this->name}";\n    }\n}\n\`\`\`\n\n### Constructor Promotion (PHP 8)\n\nDeclare and assign properties directly in the constructor:\n\n\`\`\`php\nclass User {\n    public function __construct(\n        public string \$name,\n        public int \$age,\n    ) {}\n}\n\`\`\`\n\n### Visibility\n\n- \`public\` -- accessible from anywhere\n- \`protected\` -- accessible from the class and subclasses\n- \`private\` -- accessible only from the class itself\n\n### Static Members\n\n\`\`\`php\nclass Counter {\n    private static int \$count = 0;\n\n    public static function increment(): void {\n        self::\$count++;\n    }\n\n    public static function getCount(): int {\n        return self::\$count;\n    }\n}\n\`\`\`\n\n### Class Constants\n\n\`\`\`php\nclass Config {\n    public const VERSION = "1.0.0";\n}\necho Config::VERSION;\n\`\`\``,
  exercises: [
    {
      id: 'php-class-1',
      title: 'Define a Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Define a class named Product with a public string property $name.',
      skeleton: `<?php\n___ Product {\n    public string \$name;\n}`,
      solution: `<?php\nclass Product {\n    public string \$name;\n}`,
      hints: ['Use the class keyword to define a class', 'Class names are typically PascalCase', 'Properties are declared inside the class body'],
      concepts: ['class-definition', 'properties'],
    },
    {
      id: 'php-class-2',
      title: 'Constructor',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Write the constructor method that assigns $name to the property.',
      skeleton: `<?php\nclass Pet {\n    public string \$name;\n\n    public function ___(string \$name) {\n        \$this->name = \$name;\n    }\n}`,
      solution: `<?php\nclass Pet {\n    public string \$name;\n\n    public function __construct(string \$name) {\n        \$this->name = \$name;\n    }\n}`,
      hints: ['The constructor method is named __construct', 'It is called automatically when creating an object with new', 'Use $this->name to assign to the property'],
      concepts: ['constructor', '__construct'],
    },
    {
      id: 'php-class-3',
      title: 'Constructor Promotion',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Use constructor promotion to declare and assign properties in one step.',
      skeleton: `<?php\nclass Point {\n    public function __construct(\n        ___ float \$x,\n        ___ float \$y,\n    ) {}\n}`,
      solution: `<?php\nclass Point {\n    public function __construct(\n        public float \$x,\n        public float \$y,\n    ) {}\n}`,
      hints: ['Add a visibility modifier before each parameter', 'public, protected, or private triggers promotion', 'The property is automatically declared and assigned'],
      concepts: ['constructor-promotion', 'php8'],
    },
    {
      id: 'php-class-4',
      title: 'Access a Property',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Access the name property of the $user object.',
      skeleton: `<?php\nclass User {\n    public function __construct(public string \$name) {}\n}\n\$user = new User("Alice");\necho \$user___; // Alice`,
      solution: `<?php\nclass User {\n    public function __construct(public string \$name) {}\n}\n\$user = new User("Alice");\necho \$user->name; // Alice`,
      hints: ['Use the arrow operator -> to access properties', 'The syntax is $object->property', 'No $ sign before the property name after ->'],
      concepts: ['property-access', 'arrow-operator'],
    },
    {
      id: 'php-class-5',
      title: 'Static Method',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Call the static method create() on the User class.',
      skeleton: `<?php\nclass User {\n    public function __construct(public string \$name) {}\n\n    public static function create(string \$name): self {\n        return new self(\$name);\n    }\n}\n\$user = User___create("Alice");\necho \$user->name;`,
      solution: `<?php\nclass User {\n    public function __construct(public string \$name) {}\n\n    public static function create(string \$name): self {\n        return new self(\$name);\n    }\n}\n\$user = User::create("Alice");\necho \$user->name;`,
      hints: ['Static methods are called with :: (double colon)', 'The syntax is ClassName::methodName()', 'No object instance needed for static calls'],
      concepts: ['static-methods', 'scope-resolution'],
    },
    {
      id: 'php-class-6',
      title: 'Class Constant',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Access the MAX_SIZE constant from the Config class.',
      skeleton: `<?php\nclass Config {\n    public const MAX_SIZE = 1024;\n}\necho Config___MAX_SIZE; // 1024`,
      solution: `<?php\nclass Config {\n    public const MAX_SIZE = 1024;\n}\necho Config::MAX_SIZE; // 1024`,
      hints: ['Constants are accessed with :: like static members', 'The syntax is ClassName::CONSTANT_NAME', 'Constants do not have a $ prefix'],
      concepts: ['class-constants', 'scope-resolution'],
    },
    {
      id: 'php-class-7',
      title: 'Write a BankAccount Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a BankAccount class with a private float $balance, a constructor, deposit(float $amount): void, and getBalance(): float.',
      skeleton: `<?php\n// Write class BankAccount with deposit and getBalance methods\n`,
      solution: `<?php\nclass BankAccount {\n    private float \$balance;\n\n    public function __construct(float \$initialBalance = 0) {\n        \$this->balance = \$initialBalance;\n    }\n\n    public function deposit(float \$amount): void {\n        \$this->balance += \$amount;\n    }\n\n    public function getBalance(): float {\n        return \$this->balance;\n    }\n}`,
      hints: ['Use private for encapsulation of $balance', 'The constructor sets the initial balance', 'deposit adds to balance, getBalance returns it'],
      concepts: ['encapsulation', 'private-properties', 'methods'],
    },
    {
      id: 'php-class-8',
      title: 'Write a Singleton Class',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write a Database class implementing the singleton pattern with a static getInstance() method.',
      skeleton: `<?php\n// Write class Database with a singleton getInstance() method\n`,
      solution: `<?php\nclass Database {\n    private static ?self \$instance = null;\n\n    private function __construct() {}\n\n    public static function getInstance(): self {\n        if (self::\$instance === null) {\n            self::\$instance = new self();\n        }\n        return self::\$instance;\n    }\n}`,
      hints: ['Store the instance in a private static property', 'Make the constructor private to prevent direct instantiation', 'Check if the instance is null before creating a new one'],
      concepts: ['singleton-pattern', 'static-properties', 'private-constructor'],
    },
    {
      id: 'php-class-9',
      title: 'Write a Fluent Builder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a QueryBuilder class with methods select(string $cols), from(string $table), and build(): string. Each method should return $this for chaining.',
      skeleton: `<?php\n// Write class QueryBuilder with fluent interface\n`,
      solution: `<?php\nclass QueryBuilder {\n    private string \$select = "*";\n    private string \$from = "";\n\n    public function select(string \$cols): self {\n        \$this->select = \$cols;\n        return \$this;\n    }\n\n    public function from(string \$table): self {\n        \$this->from = \$table;\n        return \$this;\n    }\n\n    public function build(): string {\n        return "SELECT {\$this->select} FROM {\$this->from}";\n    }\n}`,
      hints: ['Return $this from setter methods to enable chaining', 'Use self as the return type', 'build() assembles the final query string'],
      concepts: ['fluent-interface', 'method-chaining', 'builder-pattern'],
    },
    {
      id: 'php-class-10',
      title: 'Write a Collection Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a Collection class with add(mixed $item): void, count(): int, and toArray(): array methods.',
      skeleton: `<?php\n// Write class Collection with add, count, and toArray methods\n`,
      solution: `<?php\nclass Collection {\n    private array \$items = [];\n\n    public function add(mixed \$item): void {\n        \$this->items[] = \$item;\n    }\n\n    public function count(): int {\n        return count(\$this->items);\n    }\n\n    public function toArray(): array {\n        return \$this->items;\n    }\n}`,
      hints: ['Store items in a private array', 'Use [] to append to the array', 'count() uses PHP built-in count()'],
      concepts: ['collection-pattern', 'encapsulation', 'methods'],
    },
    {
      id: 'php-class-11',
      title: 'Write a Readonly DTO',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a readonly class UserDTO using PHP 8.2 readonly class syntax with properties name (string) and email (string).',
      skeleton: `<?php\n// Write a readonly class UserDTO with name and email\n`,
      solution: `<?php\nreadonly class UserDTO {\n    public function __construct(\n        public string \$name,\n        public string \$email,\n    ) {}\n}`,
      hints: ['PHP 8.2 supports readonly classes', 'All properties in a readonly class are implicitly readonly', 'Use constructor promotion for conciseness'],
      concepts: ['readonly-class', 'dto-pattern', 'php82'],
    },
    {
      id: 'php-class-12',
      title: 'Write a Static Registry',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a Registry class with static methods set(string $key, mixed $value): void, get(string $key): mixed, and has(string $key): bool.',
      skeleton: `<?php\n// Write class Registry with static set, get, and has methods\n`,
      solution: `<?php\nclass Registry {\n    private static array \$data = [];\n\n    public static function set(string \$key, mixed \$value): void {\n        self::\$data[\$key] = \$value;\n    }\n\n    public static function get(string \$key): mixed {\n        return self::\$data[\$key] ?? null;\n    }\n\n    public static function has(string \$key): bool {\n        return array_key_exists(\$key, self::\$data);\n    }\n}`,
      hints: ['Use a private static array to store data', 'Access static properties with self::', 'Use array_key_exists for the has method'],
      concepts: ['static-methods', 'static-properties', 'registry-pattern'],
    },
    {
      id: 'php-class-13',
      title: 'Fix: Accessing Private Property',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the code: $balance is private and cannot be accessed directly from outside the class.',
      skeleton: `<?php\nclass Account {\n    private float \$balance = 100;\n}\n\n\$acc = new Account();\necho \$acc->balance;`,
      solution: `<?php\nclass Account {\n    private float \$balance = 100;\n\n    public function getBalance(): float {\n        return \$this->balance;\n    }\n}\n\n\$acc = new Account();\necho \$acc->getBalance();`,
      hints: ['Private properties cannot be accessed from outside the class', 'Create a public getter method', 'The getter returns $this->balance'],
      concepts: ['encapsulation', 'private-properties', 'getters'],
    },
    {
      id: 'php-class-14',
      title: 'Fix: Static vs Instance Method',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: a static method cannot use $this.',
      skeleton: `<?php\nclass Logger {\n    private string \$prefix = "[LOG]";\n\n    public static function log(string \$msg): void {\n        echo \$this->prefix . " " . \$msg;\n    }\n}`,
      solution: `<?php\nclass Logger {\n    private string \$prefix = "[LOG]";\n\n    public function log(string \$msg): void {\n        echo \$this->prefix . " " . \$msg;\n    }\n}`,
      hints: ['Static methods do not have access to $this', 'Either remove static or use a static property with self::', 'The simplest fix is to make it an instance method'],
      concepts: ['static-methods', 'this-keyword'],
    },
    {
      id: 'php-class-15',
      title: 'Fix: Missing self:: for Static Property',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: static properties must be accessed with self:: not $this->.',
      skeleton: `<?php\nclass Counter {\n    private static int \$count = 0;\n\n    public static function increment(): void {\n        \$this->count++;\n    }\n\n    public static function getCount(): int {\n        return \$this->count;\n    }\n}`,
      solution: `<?php\nclass Counter {\n    private static int \$count = 0;\n\n    public static function increment(): void {\n        self::\$count++;\n    }\n\n    public static function getCount(): int {\n        return self::\$count;\n    }\n}`,
      hints: ['Static properties use self:: not $this->', 'Replace $this->count with self::$count', '$this is not available in static methods'],
      concepts: ['static-properties', 'self-keyword'],
    },
    {
      id: 'php-class-16',
      title: 'Predict: Constructor Promotion',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nclass Greeting {\n    public function __construct(\n        public string \$msg = "Hello",\n    ) {}\n}\n\$g = new Greeting();\necho \$g->msg;`,
      solution: `Hello`,
      hints: ['Constructor promotion creates and assigns the property', 'The default value "Hello" is used when no argument is passed', '$g->msg is "Hello"'],
      concepts: ['constructor-promotion', 'default-values'],
    },
    {
      id: 'php-class-17',
      title: 'Predict: Static Counter',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nclass Counter {\n    private static int \$n = 0;\n    public function __construct() { self::\$n++; }\n    public static function getCount(): int { return self::\$n; }\n}\nnew Counter();\nnew Counter();\nnew Counter();\necho Counter::getCount();`,
      solution: `3`,
      hints: ['Static properties are shared across all instances', 'Each new Counter() increments self::$n', 'After 3 instances, $n is 3'],
      concepts: ['static-properties', 'constructor'],
    },
    {
      id: 'php-class-18',
      title: 'Predict: Readonly Property',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What happens when this code runs?',
      skeleton: `<?php\nclass Config {\n    public function __construct(\n        public readonly string \$env = "prod",\n    ) {}\n}\n\$c = new Config();\n\$c->env = "dev";\necho \$c->env;`,
      solution: `Error: Cannot modify readonly property Config::$env`,
      hints: ['Readonly properties can only be set once, in the constructor', 'Attempting to modify throws an Error', 'The assignment $c->env = "dev" fails'],
      concepts: ['readonly-properties', 'immutability'],
    },
    {
      id: 'php-class-19',
      title: 'Refactor: Use Constructor Promotion',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Refactor the class to use PHP 8 constructor promotion.',
      skeleton: `<?php\nclass Product {\n    public string \$name;\n    public float \$price;\n    public int \$quantity;\n\n    public function __construct(string \$name, float \$price, int \$quantity) {\n        \$this->name = \$name;\n        \$this->price = \$price;\n        \$this->quantity = \$quantity;\n    }\n}`,
      solution: `<?php\nclass Product {\n    public function __construct(\n        public string \$name,\n        public float \$price,\n        public int \$quantity,\n    ) {}\n}`,
      hints: ['Add visibility modifiers to constructor parameters', 'Remove the manual property declarations', 'Remove the assignment statements in the body'],
      concepts: ['constructor-promotion', 'php8', 'refactoring'],
    },
    {
      id: 'php-class-20',
      title: 'Refactor: Extract Constants',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the magic numbers into class constants.',
      skeleton: `<?php\nclass PasswordValidator {\n    public function isValid(string \$password): bool {\n        if (strlen(\$password) < 8) return false;\n        if (strlen(\$password) > 64) return false;\n        return true;\n    }\n}`,
      solution: `<?php\nclass PasswordValidator {\n    private const MIN_LENGTH = 8;\n    private const MAX_LENGTH = 64;\n\n    public function isValid(string \$password): bool {\n        \$len = strlen(\$password);\n        if (\$len < self::MIN_LENGTH) return false;\n        if (\$len > self::MAX_LENGTH) return false;\n        return true;\n    }\n}`,
      hints: ['Replace magic numbers with named constants', 'Use private const for class-scoped constants', 'Reference them with self::CONSTANT_NAME'],
      concepts: ['class-constants', 'magic-numbers', 'refactoring'],
    },
  ],
};
