import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'php-inherit',
  title: '10. Inheritance',
  explanation: `## Inheritance in PHP\n\nPHP supports single inheritance with the \`extends\` keyword. Classes can inherit properties and methods from a parent class.\n\n### extends\n\n\`\`\`php\nclass Animal {\n    public function __construct(public string \$name) {}\n\n    public function speak(): string {\n        return "...";\n    }\n}\n\nclass Dog extends Animal {\n    public function speak(): string {\n        return "Woof!";\n    }\n}\n\`\`\`\n\n### parent::\n\nCall the parent class's methods using \`parent::\`:\n\n\`\`\`php\nclass Dog extends Animal {\n    public function speak(): string {\n        return parent::speak() . " Woof!";\n    }\n}\n\`\`\`\n\n### final\n\nPrevent a class from being extended or a method from being overridden:\n\n\`\`\`php\nfinal class Immutable { ... }\n\nclass Base {\n    final public function id(): int { return 1; }\n}\n\`\`\`\n\n### abstract\n\nAbstract classes cannot be instantiated and can define abstract methods that subclasses must implement:\n\n\`\`\`php\nabstract class Shape {\n    abstract public function area(): float;\n\n    public function describe(): string {\n        return "Area: " . \$this->area();\n    }\n}\n\`\`\`\n\n### Constructor Inheritance\n\nChild classes do not automatically call the parent constructor. You must call it explicitly:\n\n\`\`\`php\nclass Child extends Parent {\n    public function __construct(string \$name, public int \$extra) {\n        parent::__construct(\$name);\n    }\n}\n\`\`\``,
  exercises: [
    {
      id: 'php-inherit-1',
      title: 'Extend a Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Make the Dog class extend the Animal class.',
      skeleton: `<?php\nclass Animal {\n    public function __construct(public string \$name) {}\n}\n\nclass Dog ___ Animal {\n    public function bark(): string {\n        return "\$this->name says Woof!";\n    }\n}`,
      solution: `<?php\nclass Animal {\n    public function __construct(public string \$name) {}\n}\n\nclass Dog extends Animal {\n    public function bark(): string {\n        return "\$this->name says Woof!";\n    }\n}`,
      hints: ['Use the extends keyword for inheritance', 'Place it between the class name and the parent class', 'PHP only supports single inheritance'],
      concepts: ['extends', 'inheritance'],
    },
    {
      id: 'php-inherit-2',
      title: 'Call Parent Constructor',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Call the parent constructor from the child class.',
      skeleton: `<?php\nclass Vehicle {\n    public function __construct(public string \$make) {}\n}\n\nclass Car extends Vehicle {\n    public function __construct(string \$make, public int \$doors) {\n        ___(\$make);\n    }\n}`,
      solution: `<?php\nclass Vehicle {\n    public function __construct(public string \$make) {}\n}\n\nclass Car extends Vehicle {\n    public function __construct(string \$make, public int \$doors) {\n        parent::__construct(\$make);\n    }\n}`,
      hints: ['Use parent::__construct() to call the parent constructor', 'Pass the required arguments', 'This must be done explicitly in PHP'],
      concepts: ['parent-constructor', 'constructor-inheritance'],
    },
    {
      id: 'php-inherit-3',
      title: 'Override a Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Override the describe() method in the child class.',
      skeleton: `<?php\nclass Shape {\n    public function describe(): string {\n        return "I am a shape";\n    }\n}\n\nclass Circle extends Shape {\n    public function ___(___): string {\n        return "I am a circle";\n    }\n}`,
      solution: `<?php\nclass Shape {\n    public function describe(): string {\n        return "I am a shape";\n    }\n}\n\nclass Circle extends Shape {\n    public function describe(): string {\n        return "I am a circle";\n    }\n}`,
      hints: ['Use the same method name and signature to override', 'The return type must be compatible', 'Simply redefine the method in the child class'],
      concepts: ['method-overriding', 'polymorphism'],
    },
    {
      id: 'php-inherit-4',
      title: 'Abstract Class',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Declare the Shape class as abstract with an abstract area() method.',
      skeleton: `<?php\n___ class Shape {\n    ___ public function area(): float;\n}\n\nclass Square extends Shape {\n    public function __construct(private float \$side) {}\n\n    public function area(): float {\n        return \$this->side ** 2;\n    }\n}`,
      solution: `<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\n\nclass Square extends Shape {\n    public function __construct(private float \$side) {}\n\n    public function area(): float {\n        return \$this->side ** 2;\n    }\n}`,
      hints: ['Use the abstract keyword before class and method', 'Abstract methods have no body, just a semicolon', 'Subclasses must implement all abstract methods'],
      concepts: ['abstract-classes', 'abstract-methods'],
    },
    {
      id: 'php-inherit-5',
      title: 'Final Method',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Mark the getId() method as final to prevent overriding.',
      skeleton: `<?php\nclass Entity {\n    public function __construct(private int \$id) {}\n\n    ___ public function getId(): int {\n        return \$this->id;\n    }\n}`,
      solution: `<?php\nclass Entity {\n    public function __construct(private int \$id) {}\n\n    final public function getId(): int {\n        return \$this->id;\n    }\n}`,
      hints: ['Use the final keyword before the visibility modifier', 'final methods cannot be overridden by child classes', 'final can also be applied to entire classes'],
      concepts: ['final-methods', 'inheritance-control'],
    },
    {
      id: 'php-inherit-6',
      title: 'Call Parent Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Call the parent toString() method and add to it.',
      skeleton: `<?php\nclass Base {\n    public function toString(): string {\n        return "Base";\n    }\n}\n\nclass Child extends Base {\n    public function toString(): string {\n        return ___::toString() . " > Child";\n    }\n}`,
      solution: `<?php\nclass Base {\n    public function toString(): string {\n        return "Base";\n    }\n}\n\nclass Child extends Base {\n    public function toString(): string {\n        return parent::toString() . " > Child";\n    }\n}`,
      hints: ['Use parent:: to call the parent method', 'This allows extending the parent behavior', 'The result will be "Base > Child"'],
      concepts: ['parent-keyword', 'method-extension'],
    },
    {
      id: 'php-inherit-7',
      title: 'Write a Shape Hierarchy',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write an abstract class Shape with an abstract method area(): float, and two subclasses: Rectangle (width, height) and Circle (radius).',
      skeleton: `<?php\n// Write abstract class Shape, class Rectangle, and class Circle\n`,
      solution: `<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\n\nclass Rectangle extends Shape {\n    public function __construct(\n        private float \$width,\n        private float \$height,\n    ) {}\n\n    public function area(): float {\n        return \$this->width * \$this->height;\n    }\n}\n\nclass Circle extends Shape {\n    public function __construct(private float \$radius) {}\n\n    public function area(): float {\n        return M_PI * \$this->radius ** 2;\n    }\n}`,
      hints: ['Shape is abstract with an abstract area() method', 'Rectangle computes width * height', 'Circle computes pi * radius^2, use M_PI constant'],
      concepts: ['abstract-classes', 'inheritance', 'polymorphism'],
    },
    {
      id: 'php-inherit-8',
      title: 'Write a Template Method Pattern',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'php',
      goal: 'Write an abstract class Report with a final method generate(): string that calls abstract methods header(): string and body(): string, concatenating them.',
      skeleton: `<?php\n// Write abstract class Report with template method generate()\n`,
      solution: `<?php\nabstract class Report {\n    abstract protected function header(): string;\n    abstract protected function body(): string;\n\n    final public function generate(): string {\n        return \$this->header() . "\\n" . \$this->body();\n    }\n}`,
      hints: ['The generate() method is final -- it defines the template', 'header() and body() are abstract -- subclasses implement them', 'generate() calls both methods in order'],
      concepts: ['template-method-pattern', 'abstract-methods', 'final-methods'],
    },
    {
      id: 'php-inherit-9',
      title: 'Write a Chain of Constructors',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a class hierarchy: Entity (id), User extends Entity (id, name), Admin extends User (id, name, level). Each constructor calls parent::__construct().',
      skeleton: `<?php\n// Write classes Entity, User (extends Entity), Admin (extends User)\n`,
      solution: `<?php\nclass Entity {\n    public function __construct(public int \$id) {}\n}\n\nclass User extends Entity {\n    public function __construct(int \$id, public string \$name) {\n        parent::__construct(\$id);\n    }\n}\n\nclass Admin extends User {\n    public function __construct(int \$id, string \$name, public int \$level) {\n        parent::__construct(\$id, \$name);\n    }\n}`,
      hints: ['Each child calls parent::__construct() with the appropriate args', 'Use constructor promotion where possible', 'Admin -> User -> Entity forms the chain'],
      concepts: ['constructor-chaining', 'inheritance-hierarchy'],
    },
    {
      id: 'php-inherit-10',
      title: 'Write an Overriding Logger',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a Logger class with a log(string $msg): string method that returns "[LOG] $msg", and a TimestampLogger that overrides it to prepend a timestamp using date("H:i:s").',
      skeleton: `<?php\n// Write class Logger and class TimestampLogger extends Logger\n`,
      solution: `<?php\nclass Logger {\n    public function log(string \$msg): string {\n        return "[LOG] \$msg";\n    }\n}\n\nclass TimestampLogger extends Logger {\n    public function log(string \$msg): string {\n        \$time = date("H:i:s");\n        return "[\$time] " . parent::log(\$msg);\n    }\n}`,
      hints: ['TimestampLogger overrides log()', 'Call parent::log($msg) to reuse the parent formatting', 'Prepend the timestamp from date("H:i:s")'],
      concepts: ['method-overriding', 'parent-keyword'],
    },
    {
      id: 'php-inherit-11',
      title: 'Write an Abstract Validator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write an abstract class Validator with an abstract validate(mixed $value): bool and a concrete assertValid(mixed $value): void that throws InvalidArgumentException if validate returns false.',
      skeleton: `<?php\n// Write abstract class Validator with validate() and assertValid()\n`,
      solution: `<?php\nabstract class Validator {\n    abstract public function validate(mixed \$value): bool;\n\n    public function assertValid(mixed \$value): void {\n        if (!\$this->validate(\$value)) {\n            throw new \\InvalidArgumentException("Validation failed");\n        }\n    }\n}`,
      hints: ['validate() is abstract, assertValid() is concrete', 'assertValid calls validate and throws on failure', 'Use InvalidArgumentException for the error'],
      concepts: ['abstract-classes', 'exception-throwing', 'validation'],
    },
    {
      id: 'php-inherit-12',
      title: 'Write a Final Immutable Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Write a final class Money with readonly properties amount (int) and currency (string), and a method add(Money $other): Money that returns a new Money if currencies match or throws an exception.',
      skeleton: `<?php\n// Write final class Money with add() method\n`,
      solution: `<?php\nfinal class Money {\n    public function __construct(\n        public readonly int \$amount,\n        public readonly string \$currency,\n    ) {}\n\n    public function add(Money \$other): Money {\n        if (\$this->currency !== \$other->currency) {\n            throw new \\InvalidArgumentException("Currency mismatch");\n        }\n        return new Money(\$this->amount + \$other->amount, \$this->currency);\n    }\n}`,
      hints: ['final prevents subclassing', 'readonly prevents modification after construction', 'add() returns a new Money instance (immutable)'],
      concepts: ['final-class', 'readonly-properties', 'immutability', 'value-object'],
    },
    {
      id: 'php-inherit-13',
      title: 'Fix: Missing Parent Constructor Call',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the bug: the child class does not call the parent constructor, so $name is never set.',
      skeleton: `<?php\nclass Animal {\n    public string \$name;\n    public function __construct(string \$name) {\n        \$this->name = \$name;\n    }\n}\n\nclass Cat extends Animal {\n    public function __construct(string \$name, public string \$color) {\n        // Missing parent constructor call!\n    }\n}\n\n\$cat = new Cat("Whiskers", "orange");\necho \$cat->name; // Uninitialized`,
      solution: `<?php\nclass Animal {\n    public string \$name;\n    public function __construct(string \$name) {\n        \$this->name = \$name;\n    }\n}\n\nclass Cat extends Animal {\n    public function __construct(string \$name, public string \$color) {\n        parent::__construct(\$name);\n    }\n}\n\n\$cat = new Cat("Whiskers", "orange");\necho \$cat->name; // Whiskers`,
      hints: ['The child constructor must call parent::__construct()', 'Pass $name to the parent constructor', 'Without this call, the parent properties are not initialized'],
      concepts: ['parent-constructor', 'constructor-inheritance'],
    },
    {
      id: 'php-inherit-14',
      title: 'Fix: Overriding Final Method',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Fix the code: it tries to override a final method which is not allowed.',
      skeleton: `<?php\nclass Base {\n    final public function getId(): int {\n        return 1;\n    }\n}\n\nclass Child extends Base {\n    public function getId(): int {\n        return 2;\n    }\n}`,
      solution: `<?php\nclass Base {\n    final public function getId(): int {\n        return 1;\n    }\n}\n\nclass Child extends Base {\n    public function getChildId(): int {\n        return 2;\n    }\n}`,
      hints: ['Final methods cannot be overridden', 'Rename the method in the child class', 'Or remove final from the parent if overriding is desired'],
      concepts: ['final-methods', 'inheritance-restrictions'],
    },
    {
      id: 'php-inherit-15',
      title: 'Fix: Abstract Class Instantiation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'php',
      goal: 'Fix the code: it tries to instantiate an abstract class directly.',
      skeleton: `<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\n\n\$s = new Shape(); // Error!`,
      solution: `<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\n\nclass Square extends Shape {\n    public function __construct(private float \$side) {}\n\n    public function area(): float {\n        return \$this->side ** 2;\n    }\n}\n\n\$s = new Square(5);`,
      hints: ['Abstract classes cannot be instantiated', 'Create a concrete subclass that implements all abstract methods', 'Instantiate the concrete subclass instead'],
      concepts: ['abstract-classes', 'concrete-classes'],
    },
    {
      id: 'php-inherit-16',
      title: 'Predict: Method Override',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nclass A {\n    public function greet(): string { return "Hello from A"; }\n}\nclass B extends A {\n    public function greet(): string { return "Hello from B"; }\n}\n\$obj = new B();\necho \$obj->greet();`,
      solution: `Hello from B`,
      hints: ['B overrides the greet() method from A', 'The object is an instance of B', 'The overridden method in B is called'],
      concepts: ['method-overriding', 'polymorphism'],
    },
    {
      id: 'php-inherit-17',
      title: 'Predict: parent:: Call',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nclass Base {\n    public function name(): string { return "Base"; }\n}\nclass Child extends Base {\n    public function name(): string { return parent::name() . "::Child"; }\n}\n\$c = new Child();\necho \$c->name();`,
      solution: `Base::Child`,
      hints: ['parent::name() calls the Base version', 'It returns "Base"', 'The child appends "::Child"'],
      concepts: ['parent-keyword', 'method-chaining'],
    },
    {
      id: 'php-inherit-18',
      title: 'Predict: instanceof Check',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'php',
      goal: 'What does this code output?',
      skeleton: `<?php\nclass Animal {}\nclass Dog extends Animal {}\n\$d = new Dog();\nvar_dump(\$d instanceof Animal);`,
      solution: `bool(true)`,
      hints: ['instanceof checks if an object is of a class or its ancestors', 'Dog extends Animal, so a Dog is an instance of Animal', 'This is true for all parent classes in the chain'],
      concepts: ['instanceof', 'inheritance-chain'],
    },
    {
      id: 'php-inherit-19',
      title: 'Refactor: Replace Conditional with Polymorphism',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the switch statement into a class hierarchy using polymorphism.',
      skeleton: `<?php\nfunction calculateArea(string \$type, float \$a, float \$b = 0): float {\n    switch (\$type) {\n        case "circle":\n            return M_PI * \$a ** 2;\n        case "rectangle":\n            return \$a * \$b;\n        case "square":\n            return \$a ** 2;\n        default:\n            throw new InvalidArgumentException("Unknown shape");\n    }\n}`,
      solution: `<?php\nabstract class Shape {\n    abstract public function area(): float;\n}\n\nclass Circle extends Shape {\n    public function __construct(private float \$radius) {}\n    public function area(): float { return M_PI * \$this->radius ** 2; }\n}\n\nclass Rectangle extends Shape {\n    public function __construct(private float \$width, private float \$height) {}\n    public function area(): float { return \$this->width * \$this->height; }\n}\n\nclass Square extends Shape {\n    public function __construct(private float \$side) {}\n    public function area(): float { return \$this->side ** 2; }\n}`,
      hints: ['Create an abstract Shape with an abstract area() method', 'Each shape type becomes its own class', 'Each class encapsulates its own area calculation'],
      concepts: ['polymorphism', 'refactoring', 'abstract-classes'],
    },
    {
      id: 'php-inherit-20',
      title: 'Refactor: Use Abstract Method Instead of Default',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'php',
      goal: 'Refactor the base class: instead of a default implementation that throws, make the method abstract to enforce implementation at compile time.',
      skeleton: `<?php\nclass Formatter {\n    public function format(string \$data): string {\n        throw new RuntimeException("Subclass must implement format()");\n    }\n}\n\nclass JsonFormatter extends Formatter {\n    public function format(string \$data): string {\n        return json_encode(["data" => \$data]);\n    }\n}\n\nclass CsvFormatter extends Formatter {\n    public function format(string \$data): string {\n        return "data\\n" . \$data;\n    }\n}`,
      solution: `<?php\nabstract class Formatter {\n    abstract public function format(string \$data): string;\n}\n\nclass JsonFormatter extends Formatter {\n    public function format(string \$data): string {\n        return json_encode(["data" => \$data]);\n    }\n}\n\nclass CsvFormatter extends Formatter {\n    public function format(string \$data): string {\n        return "data\\n" . \$data;\n    }\n}`,
      hints: ['Make Formatter abstract', 'Make format() an abstract method', 'This catches missing implementations at class definition, not runtime'],
      concepts: ['abstract-classes', 'compile-time-safety', 'refactoring'],
    },
  ],
};
