import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-var',
  title: '01. Variables',
  explanation: `## Variables in Kotlin\n\nKotlin has two keywords for declaring variables:\n\n- **val** — read-only (immutable reference). Once assigned, it cannot be reassigned.\n- **var** — mutable. Can be reassigned at any time.\n\n\`\`\`kotlin\nval name = "Kotlin"   // type inferred as String\nvar count = 0          // type inferred as Int\ncount = 5              // OK — var can be reassigned\n// name = "Java"       // ERROR — val cannot be reassigned\n\`\`\`\n\nYou can specify the type explicitly:\n\n\`\`\`kotlin\nval pi: Double = 3.14\nvar message: String = "Hello"\n\`\`\`\n\n**const val** is used for compile-time constants (top-level or in objects):\n\n\`\`\`kotlin\nconst val MAX_SIZE = 100\n\`\`\`\n\nKotlin's type inference is powerful — you rarely need to write types explicitly, but you can when clarity matters.`,
  exercises: [
    {
      id: 'kt-var-1',
      title: 'Declare a Read-Only Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a read-only variable named greeting with value "Hello".',
      skeleton: `fun main() {\n    ___ greeting = "Hello"\n    println(greeting)\n}`,
      solution: `fun main() {\n    val greeting = "Hello"\n    println(greeting)\n}`,
      hints: ['Use the keyword for read-only variables.', 'val declares an immutable reference.', 'val greeting = "Hello"'],
      concepts: ['val'],
    },
    {
      id: 'kt-var-2',
      title: 'Declare a Mutable Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a mutable variable named counter starting at 0, then reassign it to 10.',
      skeleton: `fun main() {\n    ___ counter = 0\n    counter = 10\n    println(counter)\n}`,
      solution: `fun main() {\n    var counter = 0\n    counter = 10\n    println(counter)\n}`,
      hints: ['You need a variable that can be reassigned.', 'var allows reassignment.', 'var counter = 0'],
      concepts: ['var'],
    },
    {
      id: 'kt-var-3',
      title: 'Explicit Type Annotation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a val with explicit Double type.',
      skeleton: `fun main() {\n    val temperature___Double = 98.6\n    println(temperature)\n}`,
      solution: `fun main() {\n    val temperature: Double = 98.6\n    println(temperature)\n}`,
      hints: ['Types are annotated with a colon after the name.', 'The syntax is name: Type.', ': Double'],
      concepts: ['explicit-types'],
    },
    {
      id: 'kt-var-4',
      title: 'Type Inference',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict what this code prints.',
      skeleton: `fun main() {\n    val x = 42\n    val y = 3.14\n    println(x::class.simpleName)\n    println(y::class.simpleName)\n}`,
      solution: `Int\nDouble`,
      hints: ['42 is an integer literal.', '3.14 is a double literal.', 'Kotlin infers Int and Double.'],
      concepts: ['type-inference'],
    },
    {
      id: 'kt-var-5',
      title: 'Const Val Declaration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a compile-time constant MAX_RETRIES equal to 3.',
      skeleton: `___ ___ MAX_RETRIES = 3\n\nfun main() {\n    println(MAX_RETRIES)\n}`,
      solution: `const val MAX_RETRIES = 3\n\nfun main() {\n    println(MAX_RETRIES)\n}`,
      hints: ['Compile-time constants use two keywords.', 'const val is used for compile-time constants.', 'const val MAX_RETRIES = 3'],
      concepts: ['const-val'],
    },
    {
      id: 'kt-var-6',
      title: 'Fix the Reassignment Bug',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code so count can be reassigned.',
      skeleton: `fun main() {\n    val count = 0\n    count = 5\n    println(count)\n}`,
      solution: `fun main() {\n    var count = 0\n    count = 5\n    println(count)\n}`,
      hints: ['val cannot be reassigned.', 'Change val to var to allow mutation.', 'var count = 0'],
      concepts: ['val', 'var'],
    },
    {
      id: 'kt-var-7',
      title: 'Write a Swap Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a main function that declares two vars a=1 and b=2, swaps them using a temp variable, and prints "$a $b".',
      skeleton: `fun main() {\n    // Declare a = 1 and b = 2, swap them, print "\$a \$b"\n}`,
      solution: `fun main() {\n    var a = 1\n    var b = 2\n    val temp = a\n    a = b\n    b = temp\n    println("\$a \$b")\n}`,
      hints: ['You need a temporary variable to hold one value.', 'Use val temp = a before swapping.', 'After swap, a should be 2 and b should be 1.'],
      concepts: ['var', 'val'],
    },
    {
      id: 'kt-var-8',
      title: 'Delayed Initialization',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a val with explicit String type and assign it later in the same block.',
      skeleton: `fun main() {\n    val name: ___\n    name = "Kotlin"\n    println(name)\n}`,
      solution: `fun main() {\n    val name: String\n    name = "Kotlin"\n    println(name)\n}`,
      hints: ['A val can be assigned once, even if not at declaration.', 'You need to specify the type when not assigning immediately.', 'String'],
      concepts: ['val', 'explicit-types'],
    },
    {
      id: 'kt-var-9',
      title: 'Predict Reassignment Error',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict whether this code compiles or errors.',
      skeleton: `fun main() {\n    val language = "Kotlin"\n    language = "Java"\n    println(language)\n}`,
      solution: `Compilation error: Val cannot be reassigned`,
      hints: ['val creates a read-only reference.', 'You cannot reassign a val.', 'This will not compile.'],
      concepts: ['val'],
    },
    {
      id: 'kt-var-10',
      title: 'Fix Missing Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code so the variable is properly declared without an initializer.',
      skeleton: `fun main() {\n    val result\n    result = 42\n    println(result)\n}`,
      solution: `fun main() {\n    val result: Int\n    result = 42\n    println(result)\n}`,
      hints: ['Without an initializer, Kotlin cannot infer the type.', 'Add an explicit type annotation.', 'val result: Int'],
      concepts: ['explicit-types'],
    },
    {
      id: 'kt-var-11',
      title: 'Write a Circle Area Calculator',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function circleArea(radius: Double): Double that returns the area using a const val PI = 3.14159.',
      skeleton: `// Declare a const val PI\n\nfun circleArea(radius: Double): Double {\n    // return area\n}`,
      solution: `const val PI = 3.14159\n\nfun circleArea(radius: Double): Double {\n    return PI * radius * radius\n}`,
      hints: ['const val must be at the top level.', 'Area = PI * r * r.', 'const val PI = 3.14159'],
      concepts: ['const-val', 'val'],
    },
    {
      id: 'kt-var-12',
      title: 'Multiple Variable Declaration',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a main function that declares val firstName = "John", val lastName = "Doe", and prints the full name.',
      skeleton: `fun main() {\n    // declare firstName and lastName, print full name\n}`,
      solution: `fun main() {\n    val firstName = "John"\n    val lastName = "Doe"\n    println("\$firstName \$lastName")\n}`,
      hints: ['Use val for both since they do not change.', 'Use string templates with $ to combine them.', 'println("$firstName $lastName")'],
      concepts: ['val', 'string-templates'],
    },
    {
      id: 'kt-var-13',
      title: 'Predict Type Inference with Long',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict what type Kotlin infers for large numbers.',
      skeleton: `fun main() {\n    val big = 3_000_000_000\n    println(big::class.simpleName)\n}`,
      solution: `Long`,
      hints: ['3 billion exceeds Int range.', 'Kotlin auto-promotes to Long.', 'Long'],
      concepts: ['type-inference'],
    },
    {
      id: 'kt-var-14',
      title: 'Fix the Const Val Placement',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code so the const val compiles correctly.',
      skeleton: `fun main() {\n    const val GREETING = "Hello"\n    println(GREETING)\n}`,
      solution: `const val GREETING = "Hello"\n\nfun main() {\n    println(GREETING)\n}`,
      hints: ['const val cannot be declared inside a function.', 'Move it to the top level.', 'const val must be top-level or in an object.'],
      concepts: ['const-val'],
    },
    {
      id: 'kt-var-15',
      title: 'Write a Temperature Converter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function celsiusToFahrenheit(c: Double): Double that converts Celsius to Fahrenheit.',
      skeleton: `fun celsiusToFahrenheit(c: Double): Double {\n    // F = C * 9/5 + 32\n}`,
      solution: `fun celsiusToFahrenheit(c: Double): Double {\n    return c * 9.0 / 5.0 + 32.0\n}`,
      hints: ['Formula: F = C * 9/5 + 32.', 'Use Double literals (9.0, 5.0, 32.0) to avoid integer division.', 'return c * 9.0 / 5.0 + 32.0'],
      concepts: ['val', 'explicit-types'],
    },
    {
      id: 'kt-var-16',
      title: 'Refactor to Val',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor: change any var that is never reassigned to val.',
      skeleton: `fun main() {\n    var name = "Kotlin"\n    var version = 2.0\n    var counter = 0\n    counter = counter + 1\n    println("\$name \$version \$counter")\n}`,
      solution: `fun main() {\n    val name = "Kotlin"\n    val version = 2.0\n    var counter = 0\n    counter = counter + 1\n    println("\$name \$version \$counter")\n}`,
      hints: ['Only variables that are reassigned need var.', 'name and version are never changed.', 'Only counter is reassigned.'],
      concepts: ['val', 'var'],
    },
    {
      id: 'kt-var-17',
      title: 'Write an Incrementer',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function that takes an Int and returns it incremented by 1.',
      skeleton: `fun increment(n: Int): Int {\n    // return n + 1\n}`,
      solution: `fun increment(n: Int): Int {\n    return n + 1\n}`,
      hints: ['Simply add 1 to the parameter.', 'return n + 1', 'Parameters in Kotlin are val by default.'],
      concepts: ['val', 'functions'],
    },
    {
      id: 'kt-var-18',
      title: 'Fill in Underscores in Numbers',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use underscores to make the number one million readable.',
      skeleton: `fun main() {\n    val million = ___\n    println(million)\n}`,
      solution: `fun main() {\n    val million = 1_000_000\n    println(million)\n}`,
      hints: ['Kotlin allows underscores in numeric literals for readability.', 'One million = 1_000_000.', '1_000_000'],
      concepts: ['numeric-literals'],
    },
    {
      id: 'kt-var-19',
      title: 'Refactor Explicit Types to Inferred',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Remove unnecessary explicit type annotations where the type is obvious from the initializer.',
      skeleton: `fun main() {\n    val name: String = "Kotlin"\n    val age: Int = 30\n    val pi: Double = 3.14\n    println("\$name \$age \$pi")\n}`,
      solution: `fun main() {\n    val name = "Kotlin"\n    val age = 30\n    val pi = 3.14\n    println("\$name \$age \$pi")\n}`,
      hints: ['When the type is obvious from the right side, you can omit it.', 'Remove : String, : Int, : Double.', 'Kotlin infers types from the initializer.'],
      concepts: ['type-inference'],
    },
    {
      id: 'kt-var-20',
      title: 'Write a Variable Summary Printer',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a main function that declares const val APP_NAME at top level, and val version and var runCount in main, increments runCount, and prints all three.',
      skeleton: `// Declare APP_NAME here\n\nfun main() {\n    // Declare version and runCount, increment runCount, print all\n}`,
      solution: `const val APP_NAME = "MyApp"\n\nfun main() {\n    val version = "1.0"\n    var runCount = 0\n    runCount++\n    println("\$APP_NAME v\$version runs: \$runCount")\n}`,
      hints: ['const val goes at top level.', 'val for version (not reassigned), var for runCount (incremented).', 'Use ++ to increment runCount.'],
      concepts: ['const-val', 'val', 'var'],
    },
  ],
};
