import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-types',
  title: '02. Types',
  explanation: `## Basic Types in Kotlin\n\nKotlin has a rich set of built-in types:\n\n| Type | Size | Example |\n|------|------|---------|\n| Byte | 8-bit | 127 |\n| Short | 16-bit | 32767 |\n| Int | 32-bit | 2147483647 |\n| Long | 64-bit | 9223372036854775807L |\n| Float | 32-bit | 3.14f |\n| Double | 64-bit | 3.14 |\n| Boolean | - | true / false |\n| Char | 16-bit | 'A' |\n| String | - | "Hello" |\n\n\`\`\`kotlin\nval age: Int = 30\nval price: Double = 19.99\nval letter: Char = 'K'\nval flag: Boolean = true\nval big: Long = 100L\n\`\`\`\n\n**Type conversions** must be explicit — Kotlin does NOT auto-widen:\n\n\`\`\`kotlin\nval i: Int = 42\nval l: Long = i.toLong()  // explicit conversion\nval d: Double = i.toDouble()\n\`\`\`\n\n**Any** is the root of the type hierarchy (like Object in Java).`,
  exercises: [
    {
      id: 'kt-types-1',
      title: 'Declare an Int',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare an explicit Int variable.',
      skeleton: `fun main() {\n    val age: ___ = 25\n    println(age)\n}`,
      solution: `fun main() {\n    val age: Int = 25\n    println(age)\n}`,
      hints: ['25 is a whole number.', 'The 32-bit integer type in Kotlin is Int.', 'Int'],
      concepts: ['Int'],
    },
    {
      id: 'kt-types-2',
      title: 'Long Literal Suffix',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a Long using the L suffix.',
      skeleton: `fun main() {\n    val bigNumber = 100___ \n    println(bigNumber::class.simpleName)\n}`,
      solution: `fun main() {\n    val bigNumber = 100L \n    println(bigNumber::class.simpleName)\n}`,
      hints: ['Long literals use a suffix.', 'Append L to the number.', 'L'],
      concepts: ['Long'],
    },
    {
      id: 'kt-types-3',
      title: 'Float Literal Suffix',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a Float using the f suffix.',
      skeleton: `fun main() {\n    val pi: Float = 3.14___\n    println(pi)\n}`,
      solution: `fun main() {\n    val pi: Float = 3.14f\n    println(pi)\n}`,
      hints: ['Float literals need a suffix to distinguish from Double.', 'Append f.', 'f'],
      concepts: ['Float'],
    },
    {
      id: 'kt-types-4',
      title: 'Explicit Type Conversion',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Convert an Int to a Long explicitly.',
      skeleton: `fun main() {\n    val x: Int = 42\n    val y: Long = x.___\n    println(y)\n}`,
      solution: `fun main() {\n    val x: Int = 42\n    val y: Long = x.toLong()\n    println(y)\n}`,
      hints: ['Kotlin requires explicit conversion.', 'Use the to<Type>() function.', 'toLong()'],
      concepts: ['type-conversion'],
    },
    {
      id: 'kt-types-5',
      title: 'Boolean Variable',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a Boolean variable set to true.',
      skeleton: `fun main() {\n    val isActive: ___ = true\n    println(isActive)\n}`,
      solution: `fun main() {\n    val isActive: Boolean = true\n    println(isActive)\n}`,
      hints: ['The type for true/false values.', 'Boolean', 'Boolean'],
      concepts: ['Boolean'],
    },
    {
      id: 'kt-types-6',
      title: 'Char Declaration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a Char variable with the letter K.',
      skeleton: `fun main() {\n    val letter: Char = ___\n    println(letter)\n}`,
      solution: `fun main() {\n    val letter: Char = 'K'\n    println(letter)\n}`,
      hints: ['Char uses single quotes.', 'Single character in single quotes.', "'K'"],
      concepts: ['Char'],
    },
    {
      id: 'kt-types-7',
      title: 'Predict Type of Division',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of integer division.',
      skeleton: `fun main() {\n    val a = 7\n    val b = 2\n    println(a / b)\n}`,
      solution: `3`,
      hints: ['Both a and b are Int.', 'Integer division truncates the decimal.', '7 / 2 = 3 in integer math.'],
      concepts: ['Int', 'division'],
    },
    {
      id: 'kt-types-8',
      title: 'Fix Type Mismatch',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the type mismatch error.',
      skeleton: `fun main() {\n    val x: Int = 42\n    val y: Long = x\n    println(y)\n}`,
      solution: `fun main() {\n    val x: Int = 42\n    val y: Long = x.toLong()\n    println(y)\n}`,
      hints: ['Kotlin does not auto-widen Int to Long.', 'Use explicit conversion.', 'x.toLong()'],
      concepts: ['type-conversion'],
    },
    {
      id: 'kt-types-9',
      title: 'Write a Type Converter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function intToDouble(n: Int): Double that converts an Int to Double.',
      skeleton: `fun intToDouble(n: Int): Double {\n    // convert and return\n}`,
      solution: `fun intToDouble(n: Int): Double {\n    return n.toDouble()\n}`,
      hints: ['Use the toDouble() method.', 'return n.toDouble()', 'Kotlin has explicit conversion methods.'],
      concepts: ['type-conversion'],
    },
    {
      id: 'kt-types-10',
      title: 'Predict Boolean Expression',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of boolean logic.',
      skeleton: `fun main() {\n    val a = true\n    val b = false\n    println(a && b)\n    println(a || b)\n}`,
      solution: `false\ntrue`,
      hints: ['&& is logical AND.', '|| is logical OR.', 'true AND false = false; true OR false = true.'],
      concepts: ['Boolean'],
    },
    {
      id: 'kt-types-11',
      title: 'Write a Max Finder',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function maxOf(a: Int, b: Int): Int that returns the larger value.',
      skeleton: `fun maxOf(a: Int, b: Int): Int {\n    // return the larger value\n}`,
      solution: `fun maxOf(a: Int, b: Int): Int {\n    return if (a >= b) a else b\n}`,
      hints: ['Use an if expression.', 'if (a >= b) a else b', 'Kotlin if is an expression that returns a value.'],
      concepts: ['Int', 'if-expression'],
    },
    {
      id: 'kt-types-12',
      title: 'Fix Float Literal',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code so it compiles — the Float needs a proper literal.',
      skeleton: `fun main() {\n    val price: Float = 9.99\n    println(price)\n}`,
      solution: `fun main() {\n    val price: Float = 9.99f\n    println(price)\n}`,
      hints: ['9.99 is a Double literal by default.', 'Float literals need the f suffix.', '9.99f'],
      concepts: ['Float'],
    },
    {
      id: 'kt-types-13',
      title: 'Write a Safe Divider',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function safeDivide(a: Int, b: Int): Double that returns a/b as a Double (handle division properly).',
      skeleton: `fun safeDivide(a: Int, b: Int): Double {\n    // divide and return as Double\n}`,
      solution: `fun safeDivide(a: Int, b: Int): Double {\n    return a.toDouble() / b.toDouble()\n}`,
      hints: ['Convert to Double before dividing.', 'a.toDouble() / b.toDouble()', 'Integer division truncates — convert first.'],
      concepts: ['type-conversion', 'Double'],
    },
    {
      id: 'kt-types-14',
      title: 'Any Type',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function printType(value: Any) that prints the simple class name of the value.',
      skeleton: `fun printType(value: Any) {\n    // print the class simple name\n}`,
      solution: `fun printType(value: Any) {\n    println(value::class.simpleName)\n}`,
      hints: ['Any is the root of all types.', 'Use ::class.simpleName to get the type name.', 'value::class.simpleName'],
      concepts: ['Any'],
    },
    {
      id: 'kt-types-15',
      title: 'Predict Char Arithmetic',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of Char arithmetic.',
      skeleton: `fun main() {\n    val c = 'A'\n    println(c + 3)\n}`,
      solution: `D`,
      hints: ['Adding an Int to a Char shifts the character.', 'A is code 65, +3 = 68 = D.', 'D'],
      concepts: ['Char'],
    },
    {
      id: 'kt-types-16',
      title: 'Write a Number Classifier',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function isEven(n: Int): Boolean that returns true if n is even.',
      skeleton: `fun isEven(n: Int): Boolean {\n    // return true if even\n}`,
      solution: `fun isEven(n: Int): Boolean {\n    return n % 2 == 0\n}`,
      hints: ['Use the modulo operator %.', 'n % 2 == 0 means even.', 'return n % 2 == 0'],
      concepts: ['Int', 'Boolean'],
    },
    {
      id: 'kt-types-17',
      title: 'Fix Double to Int Conversion',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code to properly convert a Double to Int.',
      skeleton: `fun main() {\n    val price: Double = 19.99\n    val rounded: Int = price\n    println(rounded)\n}`,
      solution: `fun main() {\n    val price: Double = 19.99\n    val rounded: Int = price.toInt()\n    println(rounded)\n}`,
      hints: ['Kotlin requires explicit narrowing conversions.', 'Use toInt() to convert.', 'price.toInt()'],
      concepts: ['type-conversion'],
    },
    {
      id: 'kt-types-18',
      title: 'Refactor to Use Type Inference',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Remove unnecessary explicit type declarations where the type is obvious.',
      skeleton: `fun main() {\n    val count: Int = 10\n    val name: String = "Kotlin"\n    val active: Boolean = true\n    val rate: Double = 4.5\n    println("\$count \$name \$active \$rate")\n}`,
      solution: `fun main() {\n    val count = 10\n    val name = "Kotlin"\n    val active = true\n    val rate = 4.5\n    println("\$count \$name \$active \$rate")\n}`,
      hints: ['All types can be inferred from the initializer.', 'Remove : Type from each declaration.', 'Kotlin infers types automatically from literals.'],
      concepts: ['type-inference'],
    },
    {
      id: 'kt-types-19',
      title: 'Refactor to Explicit Types',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add explicit type annotations to all variables for documentation purposes.',
      skeleton: `fun main() {\n    val width = 100\n    val height = 200\n    val area = width * height\n    println(area)\n}`,
      solution: `fun main() {\n    val width: Int = 100\n    val height: Int = 200\n    val area: Int = width * height\n    println(area)\n}`,
      hints: ['Add : Int to each variable.', 'All values here are Int.', 'width * height produces an Int.'],
      concepts: ['explicit-types'],
    },
    {
      id: 'kt-types-20',
      title: 'Write a Byte Range Checker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function isValidByte(n: Int): Boolean that returns true if n is in the Byte range (-128..127).',
      skeleton: `fun isValidByte(n: Int): Boolean {\n    // check if n is in Byte range\n}`,
      solution: `fun isValidByte(n: Int): Boolean {\n    return n in Byte.MIN_VALUE..Byte.MAX_VALUE\n}`,
      hints: ['Byte range is -128 to 127.', 'Use the in operator with a range.', 'Byte.MIN_VALUE..Byte.MAX_VALUE'],
      concepts: ['Byte', 'ranges'],
    },
  ],
};
