import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-str',
  title: '03. Strings',
  explanation: `## Strings in Kotlin\n\nKotlin strings are sequences of characters with powerful features:\n\n**String Templates** — embed expressions with \`$\`:\n\n\`\`\`kotlin\nval name = "World"\nprintln("Hello, \$name!")         // Hello, World!\nprintln("Length: \${name.length}") // Length: 5\n\`\`\`\n\n**Raw Strings** — triple-quoted, no escape processing:\n\n\`\`\`kotlin\nval path = \"\"\"C:\\Users\\docs\"\"\"\nval json = \"\"\"\n    {\n        "key": "value"\n    }\n\"\"\".trimIndent()\n\`\`\`\n\n**Useful String Functions:**\n\n\`\`\`kotlin\n"hello".uppercase()        // HELLO\n"HELLO".lowercase()        // hello\n"  hi  ".trim()            // hi\n"hello".substring(0, 3)    // hel\n"a,b,c".split(",")         // [a, b, c]\n"hello".reversed()         // olleh\n"hello".contains("ell")    // true\n\`\`\``,
  exercises: [
    {
      id: 'kt-str-1',
      title: 'Simple String Template',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use a string template to embed a variable.',
      skeleton: `fun main() {\n    val lang = "Kotlin"\n    println("I love ___!")\n}`,
      solution: `fun main() {\n    val lang = "Kotlin"\n    println("I love \$lang!")\n}`,
      hints: ['Use $ to embed a variable in a string.', '$variableName inserts the value.', '$lang'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-2',
      title: 'Expression in String Template',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use an expression inside a string template.',
      skeleton: `fun main() {\n    val items = listOf("a", "b", "c")\n    println("Count: ___")\n}`,
      solution: `fun main() {\n    val items = listOf("a", "b", "c")\n    println("Count: \${items.size}")\n}`,
      hints: ['Use ${expression} for complex expressions.', 'Access the size property.', '\\${items.size}'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-3',
      title: 'Raw String with trimIndent',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a multiline raw string and trim the indentation.',
      skeleton: `fun main() {\n    val text = """\n        Line 1\n        Line 2\n        Line 3\n    """.___\n    println(text)\n}`,
      solution: `fun main() {\n    val text = """\n        Line 1\n        Line 2\n        Line 3\n    """.trimIndent()\n    println(text)\n}`,
      hints: ['Raw strings use triple quotes.', 'trimIndent() removes common leading whitespace.', 'trimIndent()'],
      concepts: ['raw-strings'],
    },
    {
      id: 'kt-str-4',
      title: 'String Concatenation vs Templates',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output using string templates.',
      skeleton: `fun main() {\n    val a = 3\n    val b = 4\n    println("\$a + \$b = \${a + b}")\n}`,
      solution: `3 + 4 = 7`,
      hints: ['$a becomes 3, $b becomes 4.', '${a + b} evaluates the expression.', '3 + 4 = 7'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-5',
      title: 'Uppercase and Lowercase',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Convert a string to uppercase.',
      skeleton: `fun main() {\n    val word = "hello"\n    println(word.___)\n}`,
      solution: `fun main() {\n    val word = "hello"\n    println(word.uppercase())\n}`,
      hints: ['Use the function that converts to all caps.', 'uppercase() returns the uppercase version.', 'uppercase()'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-6',
      title: 'Fix Broken String Template',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the string template so it prints the length of the name.',
      skeleton: `fun main() {\n    val name = "Kotlin"\n    println("Length: \$name.length")\n}`,
      solution: `fun main() {\n    val name = "Kotlin"\n    println("Length: \${name.length}")\n}`,
      hints: ['Property access needs curly braces in templates.', 'Use ${name.length} for expressions.', 'Wrap in ${...}.'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-7',
      title: 'Write a Greeting Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function greet(name: String): String that returns "Hello, <name>!".',
      skeleton: `fun greet(name: String): String {\n    // return greeting\n}`,
      solution: `fun greet(name: String): String {\n    return "Hello, \$name!"\n}`,
      hints: ['Use a string template.', 'return "Hello, $name!"', 'Embed name with $.'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-8',
      title: 'Split a String',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function splitCSV(line: String): List<String> that splits a comma-separated string.',
      skeleton: `fun splitCSV(line: String): List<String> {\n    // split by comma\n}`,
      solution: `fun splitCSV(line: String): List<String> {\n    return line.split(",")\n}`,
      hints: ['Use the split function.', 'split(",") splits by comma.', 'return line.split(",")'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-9',
      title: 'Predict String Comparison',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of string equality checks.',
      skeleton: `fun main() {\n    val a = "hello"\n    val b = "hello"\n    println(a == b)\n    println(a === b)\n}`,
      solution: `true\ntrue`,
      hints: ['== checks structural equality in Kotlin.', '=== checks referential equality.', 'String literals are interned in Kotlin.'],
      concepts: ['string-equality'],
    },
    {
      id: 'kt-str-10',
      title: 'Fix Escaped Characters',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the string so it prints a tab between words.',
      skeleton: `fun main() {\n    println("Hello\\tWorld")\n}`,
      solution: `fun main() {\n    println("Hello\tWorld")\n}`,
      hints: ['\\\\t is a literal backslash + t, not a tab.', 'Use \\t for a tab character.', 'Remove the extra backslash.'],
      concepts: ['escape-sequences'],
    },
    {
      id: 'kt-str-11',
      title: 'Write a Reverser',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function reverseString(s: String): String that returns the reversed string.',
      skeleton: `fun reverseString(s: String): String {\n    // reverse the string\n}`,
      solution: `fun reverseString(s: String): String {\n    return s.reversed()\n}`,
      hints: ['Kotlin strings have a reversed() function.', 'return s.reversed()', 'reversed() returns a new string.'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-12',
      title: 'Substring Extraction',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Extract the first 5 characters of a string.',
      skeleton: `fun main() {\n    val word = "Kotlin is fun"\n    println(word.___(0, 5))\n}`,
      solution: `fun main() {\n    val word = "Kotlin is fun"\n    println(word.substring(0, 5))\n}`,
      hints: ['Use the function that extracts part of a string.', 'substring(start, end) extracts characters.', 'substring(0, 5)'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-13',
      title: 'Predict trimIndent',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output after trimIndent.',
      skeleton: `fun main() {\n    val s = """\n        |Hello\n        |World\n    """.trimMargin()\n    println(s)\n}`,
      solution: `Hello\nWorld`,
      hints: ['trimMargin() removes leading whitespace up to | by default.', 'Each line is trimmed to after the | character.', 'Hello on first line, World on second.'],
      concepts: ['raw-strings'],
    },
    {
      id: 'kt-str-14',
      title: 'Write a Word Counter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function wordCount(text: String): Int that counts words (split by spaces).',
      skeleton: `fun wordCount(text: String): Int {\n    // count words\n}`,
      solution: `fun wordCount(text: String): Int {\n    return text.trim().split("\\s+".toRegex()).size\n}`,
      hints: ['Split by whitespace then count.', 'Use a regex to handle multiple spaces.', '"\\\\s+".toRegex() matches one or more whitespace chars.'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-15',
      title: 'Fix String Template Dollar Sign',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code to print a literal dollar sign followed by 100.',
      skeleton: `fun main() {\n    val price = 100\n    println("Price: $price")\n}`,
      solution: `fun main() {\n    val price = 100\n    println("Price: \\\$\$price")\n}`,
      hints: ['$ starts a string template.', 'To print a literal $, escape it or use ${"$"}.', 'Use \\$ for a literal dollar sign before the template.'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-16',
      title: 'Write a Palindrome Checker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function isPalindrome(s: String): Boolean that checks if a string reads the same forwards and backwards (case-insensitive).',
      skeleton: `fun isPalindrome(s: String): Boolean {\n    // check palindrome\n}`,
      solution: `fun isPalindrome(s: String): Boolean {\n    val lower = s.lowercase()\n    return lower == lower.reversed()\n}`,
      hints: ['Convert to lowercase first.', 'Compare the string with its reverse.', 'lower == lower.reversed()'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-17',
      title: 'Refactor Concatenation to Template',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor string concatenation to use string templates.',
      skeleton: `fun main() {\n    val first = "John"\n    val last = "Doe"\n    val age = 30\n    println(first + " " + last + " is " + age + " years old")\n}`,
      solution: `fun main() {\n    val first = "John"\n    val last = "Doe"\n    val age = 30\n    println("\$first \$last is \$age years old")\n}`,
      hints: ['Replace + concatenation with $ templates.', 'Use $variable for each value.', '"$first $last is $age years old"'],
      concepts: ['string-templates'],
    },
    {
      id: 'kt-str-18',
      title: 'Refactor to Raw String',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the escaped string to a raw string.',
      skeleton: `fun main() {\n    val path = "C:\\\\Users\\\\Zan\\\\Documents"\n    println(path)\n}`,
      solution: `fun main() {\n    val path = """C:\\Users\\Zan\\Documents"""\n    println(path)\n}`,
      hints: ['Raw strings do not process escape sequences.', 'Use triple quotes for raw strings.', '"""C:\\Users\\Zan\\Documents"""'],
      concepts: ['raw-strings'],
    },
    {
      id: 'kt-str-19',
      title: 'Write a Repeat Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function repeatString(s: String, n: Int): String that repeats a string n times.',
      skeleton: `fun repeatString(s: String, n: Int): String {\n    // repeat the string\n}`,
      solution: `fun repeatString(s: String, n: Int): String {\n    return s.repeat(n)\n}`,
      hints: ['Kotlin strings have a repeat() function.', 'return s.repeat(n)', 'repeat(n) duplicates the string n times.'],
      concepts: ['string-functions'],
    },
    {
      id: 'kt-str-20',
      title: 'Predict String Template with Expression',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of a complex string template.',
      skeleton: `fun main() {\n    val name = "Kotlin"\n    println("\$name has \${name.length} chars and starts with '\${name[0]}'")\n}`,
      solution: `Kotlin has 6 chars and starts with 'K'`,
      hints: ['$name = Kotlin, ${name.length} = 6.', 'name[0] gets the first character.', 'Kotlin has 6 chars and starts with K.'],
      concepts: ['string-templates'],
    },
  ],
};
