import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-flow',
  title: '04. Control Flow',
  explanation: `## Control Flow in Kotlin\n\n**if expression** — Kotlin's if is an expression that returns a value:\n\n\`\`\`kotlin\nval max = if (a > b) a else b\n\`\`\`\n\n**when expression** — powerful replacement for switch:\n\n\`\`\`kotlin\nwhen (x) {\n    1 -> println("one")\n    2, 3 -> println("two or three")\n    in 4..10 -> println("between 4 and 10")\n    else -> println("other")\n}\n\`\`\`\n\n**for loop** — iterates over anything that provides an iterator:\n\n\`\`\`kotlin\nfor (i in 1..5) println(i)       // 1 2 3 4 5\nfor (i in 5 downTo 1) println(i) // 5 4 3 2 1\nfor (i in 0 until 5) println(i)  // 0 1 2 3 4\nfor (i in 0..10 step 2) println(i) // 0 2 4 6 8 10\n\`\`\`\n\n**while / do-while:**\n\n\`\`\`kotlin\nwhile (condition) { ... }\ndo { ... } while (condition)\n\`\`\`\n\n**Ranges:** \`1..5\` includes both endpoints, \`0 until 5\` excludes the end.`,
  exercises: [
    {
      id: 'kt-flow-1',
      title: 'If Expression',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use if as an expression to assign the larger value.',
      skeleton: `fun main() {\n    val a = 10\n    val b = 20\n    val max = ___ (a > b) a ___ b\n    println(max)\n}`,
      solution: `fun main() {\n    val a = 10\n    val b = 20\n    val max = if (a > b) a else b\n    println(max)\n}`,
      hints: ['if in Kotlin returns a value.', 'Use if ... else as an expression.', 'if (a > b) a else b'],
      concepts: ['if-expression'],
    },
    {
      id: 'kt-flow-2',
      title: 'When Expression Basics',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Complete the when expression to match day numbers to names.',
      skeleton: `fun dayName(day: Int): String {\n    return ___(day) {\n        1 -> "Monday"\n        2 -> "Tuesday"\n        3 -> "Wednesday"\n        ___ -> "Other"\n    }\n}`,
      solution: `fun dayName(day: Int): String {\n    return when(day) {\n        1 -> "Monday"\n        2 -> "Tuesday"\n        3 -> "Wednesday"\n        else -> "Other"\n    }\n}`,
      hints: ['when is Kotlin\'s replacement for switch.', 'The default branch uses else.', 'when(day) { ... else -> ... }'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-3',
      title: 'For Loop with Range',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a for loop that prints numbers 1 through 5.',
      skeleton: `fun main() {\n    for (i ___ 1___5) {\n        println(i)\n    }\n}`,
      solution: `fun main() {\n    for (i in 1..5) {\n        println(i)\n    }\n}`,
      hints: ['Use in to iterate over a range.', '1..5 creates a range from 1 to 5 inclusive.', 'for (i in 1..5)'],
      concepts: ['for-loop', 'ranges'],
    },
    {
      id: 'kt-flow-4',
      title: 'Predict For Loop Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of a downTo loop.',
      skeleton: `fun main() {\n    for (i in 3 downTo 1) {\n        print("\$i ")\n    }\n}`,
      solution: `3 2 1 `,
      hints: ['downTo counts backwards.', 'Starts at 3, ends at 1 inclusive.', '3 2 1'],
      concepts: ['for-loop', 'ranges'],
    },
    {
      id: 'kt-flow-5',
      title: 'Until Range (Exclusive End)',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a range from 0 to 4 (excluding 5).',
      skeleton: `fun main() {\n    for (i in 0 ___ 5) {\n        print("\$i ")\n    }\n}`,
      solution: `fun main() {\n    for (i in 0 until 5) {\n        print("\$i ")\n    }\n}`,
      hints: ['until excludes the end value.', '0 until 5 gives 0, 1, 2, 3, 4.', 'until'],
      concepts: ['ranges'],
    },
    {
      id: 'kt-flow-6',
      title: 'When with Range Check',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function classify(score: Int): String that returns "Fail" for 0..49, "Pass" for 50..69, "Merit" for 70..89, "Distinction" for 90..100, else "Invalid".',
      skeleton: `fun classify(score: Int): String {\n    // use when with ranges\n}`,
      solution: `fun classify(score: Int): String {\n    return when (score) {\n        in 0..49 -> "Fail"\n        in 50..69 -> "Pass"\n        in 70..89 -> "Merit"\n        in 90..100 -> "Distinction"\n        else -> "Invalid"\n    }\n}`,
      hints: ['Use in with ranges inside when.', 'in 0..49 -> "Fail"', 'Each branch uses in start..end -> result.'],
      concepts: ['when-expression', 'ranges'],
    },
    {
      id: 'kt-flow-7',
      title: 'Fix Off-by-One in Loop',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the loop so it prints 0 through 4 (not 0 through 5).',
      skeleton: `fun main() {\n    for (i in 0..5) {\n        println(i)\n    }\n}`,
      solution: `fun main() {\n    for (i in 0 until 5) {\n        println(i)\n    }\n}`,
      hints: ['0..5 includes 5.', 'Use until to exclude the end.', '0 until 5'],
      concepts: ['ranges'],
    },
    {
      id: 'kt-flow-8',
      title: 'While Loop Sum',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function sumUpTo(n: Int): Int that sums 1 to n using a while loop.',
      skeleton: `fun sumUpTo(n: Int): Int {\n    // use while loop\n}`,
      solution: `fun sumUpTo(n: Int): Int {\n    var sum = 0\n    var i = 1\n    while (i <= n) {\n        sum += i\n        i++\n    }\n    return sum\n}`,
      hints: ['Initialize sum = 0 and i = 1.', 'Loop while i <= n.', 'Add i to sum and increment i each iteration.'],
      concepts: ['while-loop'],
    },
    {
      id: 'kt-flow-9',
      title: 'Predict When Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of this when expression.',
      skeleton: `fun main() {\n    val x = 15\n    val result = when {\n        x < 0 -> "negative"\n        x == 0 -> "zero"\n        x < 10 -> "small"\n        x < 100 -> "medium"\n        else -> "large"\n    }\n    println(result)\n}`,
      solution: `medium`,
      hints: ['when without argument checks conditions top-down.', '15 is not < 0, not 0, not < 10, but is < 100.', 'medium'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-10',
      title: 'Fix Missing Else in When',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the when expression used as a value — it needs to be exhaustive.',
      skeleton: `fun describe(x: Int): String {\n    return when (x) {\n        1 -> "one"\n        2 -> "two"\n    }\n}`,
      solution: `fun describe(x: Int): String {\n    return when (x) {\n        1 -> "one"\n        2 -> "two"\n        else -> "other"\n    }\n}`,
      hints: ['when used as an expression must cover all cases.', 'Add an else branch.', 'else -> "other"'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-11',
      title: 'Step in Range',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function evenNumbers(max: Int): List<Int> that returns even numbers from 0 to max using step 2.',
      skeleton: `fun evenNumbers(max: Int): List<Int> {\n    // use for loop with step\n}`,
      solution: `fun evenNumbers(max: Int): List<Int> {\n    val result = mutableListOf<Int>()\n    for (i in 0..max step 2) {\n        result.add(i)\n    }\n    return result\n}`,
      hints: ['Use step 2 with a range.', '0..max step 2 gives 0, 2, 4, ...', 'Collect results in a mutableListOf.'],
      concepts: ['for-loop', 'ranges'],
    },
    {
      id: 'kt-flow-12',
      title: 'Write FizzBuzz',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function fizzBuzz(n: Int): String that returns "FizzBuzz" if divisible by 15, "Fizz" if by 3, "Buzz" if by 5, else the number as a string.',
      skeleton: `fun fizzBuzz(n: Int): String {\n    // implement FizzBuzz\n}`,
      solution: `fun fizzBuzz(n: Int): String {\n    return when {\n        n % 15 == 0 -> "FizzBuzz"\n        n % 3 == 0 -> "Fizz"\n        n % 5 == 0 -> "Buzz"\n        else -> n.toString()\n    }\n}`,
      hints: ['Check divisible by 15 first.', 'Use when without an argument for conditions.', 'n % 15 == 0 -> "FizzBuzz"'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-13',
      title: 'For Loop with Index',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Iterate over a list with both index and value.',
      skeleton: `fun main() {\n    val fruits = listOf("apple", "banana", "cherry")\n    for ((index, fruit) in fruits.___) {\n        println("\$index: \$fruit")\n    }\n}`,
      solution: `fun main() {\n    val fruits = listOf("apple", "banana", "cherry")\n    for ((index, fruit) in fruits.withIndex()) {\n        println("\$index: \$fruit")\n    }\n}`,
      hints: ['Use withIndex() to get both index and value.', 'Destructure into (index, fruit).', 'withIndex()'],
      concepts: ['for-loop'],
    },
    {
      id: 'kt-flow-14',
      title: 'Predict Nested If',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of nested if expressions.',
      skeleton: `fun main() {\n    val x = 5\n    val label = if (x > 0) {\n        if (x > 10) "big" else "small"\n    } else {\n        "non-positive"\n    }\n    println(label)\n}`,
      solution: `small`,
      hints: ['x is 5, which is > 0.', '5 is not > 10, so "small".', 'small'],
      concepts: ['if-expression'],
    },
    {
      id: 'kt-flow-15',
      title: 'Fix Infinite While Loop',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the infinite loop by adding the increment.',
      skeleton: `fun main() {\n    var i = 0\n    while (i < 5) {\n        println(i)\n    }\n}`,
      solution: `fun main() {\n    var i = 0\n    while (i < 5) {\n        println(i)\n        i++\n    }\n}`,
      hints: ['The loop never increments i.', 'Add i++ inside the loop body.', 'Without incrementing, i < 5 is always true.'],
      concepts: ['while-loop'],
    },
    {
      id: 'kt-flow-16',
      title: 'Write a Factorial Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function factorial(n: Int): Long that computes n! using a for loop.',
      skeleton: `fun factorial(n: Int): Long {\n    // compute factorial\n}`,
      solution: `fun factorial(n: Int): Long {\n    var result = 1L\n    for (i in 2..n) {\n        result *= i\n    }\n    return result\n}`,
      hints: ['Start with result = 1L.', 'Multiply by each number from 2 to n.', 'Use Long to handle large factorials.'],
      concepts: ['for-loop', 'ranges'],
    },
    {
      id: 'kt-flow-17',
      title: 'When with Multiple Values',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function isWeekend(day: String): Boolean using when that returns true for "Saturday" and "Sunday".',
      skeleton: `fun isWeekend(day: String): Boolean {\n    // use when\n}`,
      solution: `fun isWeekend(day: String): Boolean {\n    return when (day) {\n        "Saturday", "Sunday" -> true\n        else -> false\n    }\n}`,
      hints: ['when can match multiple values with commas.', '"Saturday", "Sunday" -> true', 'Combine cases with commas.'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-18',
      title: 'Refactor If-Else Chain to When',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the if-else chain into a when expression.',
      skeleton: `fun describe(x: Int): String {\n    if (x == 0) return "zero"\n    else if (x == 1) return "one"\n    else if (x == 2) return "two"\n    else return "many"\n}`,
      solution: `fun describe(x: Int): String {\n    return when (x) {\n        0 -> "zero"\n        1 -> "one"\n        2 -> "two"\n        else -> "many"\n    }\n}`,
      hints: ['when is cleaner than if-else chains.', 'Each if becomes a when branch.', 'when (x) { 0 -> "zero" ... }'],
      concepts: ['when-expression'],
    },
    {
      id: 'kt-flow-19',
      title: 'Refactor Loop to Use downTo',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the manual countdown loop to use downTo.',
      skeleton: `fun main() {\n    var i = 5\n    while (i >= 1) {\n        println(i)\n        i--\n    }\n}`,
      solution: `fun main() {\n    for (i in 5 downTo 1) {\n        println(i)\n    }\n}`,
      hints: ['Use for with downTo instead of while.', 'for (i in 5 downTo 1) replaces the while loop.', 'downTo counts backwards.'],
      concepts: ['for-loop', 'ranges'],
    },
    {
      id: 'kt-flow-20',
      title: 'Break and Continue',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output with continue.',
      skeleton: `fun main() {\n    for (i in 1..5) {\n        if (i == 3) continue\n        print("\$i ")\n    }\n}`,
      solution: `1 2 4 5 `,
      hints: ['continue skips the current iteration.', 'When i is 3, it skips to the next iteration.', '1 2 4 5'],
      concepts: ['for-loop', 'continue'],
    },
  ],
};
