import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-func',
  title: '05. Functions',
  explanation: `## Functions in Kotlin\n\nFunctions are declared with the **fun** keyword:\n\n\`\`\`kotlin\nfun greet(name: String): String {\n    return "Hello, \$name!"\n}\n\`\`\`\n\n**Single-expression functions** - omit braces and return:\n\n\`\`\`kotlin\nfun double(x: Int) = x * 2\n\`\`\`\n\n**Default parameters:**\n\n\`\`\`kotlin\nfun greet(name: String = "World") = "Hello, \$name!"\ngreet()          // Hello, World!\ngreet("Kotlin")  // Hello, Kotlin!\n\`\`\`\n\n**Named arguments:**\n\n\`\`\`kotlin\nfun createUser(name: String, age: Int, active: Boolean = true)\ncreateUser(name = "Alice", age = 30)\ncreateUser(age = 25, name = "Bob")  // order doesn't matter\n\`\`\`\n\n**Unit return type** - when a function returns nothing (like void):\n\n\`\`\`kotlin\nfun printHello(): Unit { println("Hello") }\nfun printHello() { println("Hello") } // Unit is implicit\n\`\`\``,
  exercises: [
    {
      id: 'kt-func-1',
      title: 'Declare a Simple Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a function that adds two integers.',
      skeleton: `___ add(a: Int, b: Int): Int {\n    return a + b\n}`,
      solution: `fun add(a: Int, b: Int): Int {\n    return a + b\n}`,
      hints: ['Functions are declared with a keyword.', 'The keyword is fun.', 'fun'],
      concepts: ['fun-declaration'],
    },
    {
      id: 'kt-func-2',
      title: 'Single-Expression Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Convert to a single-expression function.',
      skeleton: `fun square(x: Int) ___ x * x`,
      solution: `fun square(x: Int) = x * x`,
      hints: ['Single-expression functions use = instead of braces.', 'No return keyword needed.', '= x * x'],
      concepts: ['single-expression'],
    },
    {
      id: 'kt-func-3',
      title: 'Default Parameter Value',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a default value for the greeting parameter.',
      skeleton: `fun greet(name: String ___ "World"): String {\n    return "Hello, \$name!"\n}`,
      solution: `fun greet(name: String = "World"): String {\n    return "Hello, \$name!"\n}`,
      hints: ['Default values use = after the type.', 'name: String = "World"', '= "World"'],
      concepts: ['default-params'],
    },
    {
      id: 'kt-func-4',
      title: 'Predict Default Param Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output when using default and explicit arguments.',
      skeleton: `fun greet(name: String = "World", punctuation: String = "!") = "Hello, \$name\$punctuation"\n\nfun main() {\n    println(greet())\n    println(greet("Kotlin"))\n    println(greet("Kotlin", "."))\n}`,
      solution: `Hello, World!\nHello, Kotlin!\nHello, Kotlin.`,
      hints: ['First call uses both defaults.', 'Second call overrides name only.', 'Third call overrides both.'],
      concepts: ['default-params'],
    },
    {
      id: 'kt-func-5',
      title: 'Named Arguments',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Call the function using named arguments in reverse order.',
      skeleton: `fun createTag(tag: String, content: String) = "<\$tag>\$content</\$tag>"\n\nfun main() {\n    println(createTag(___ = "Hello", ___ = "h1"))\n}`,
      solution: `fun createTag(tag: String, content: String) = "<\$tag>\$content</\$tag>"\n\nfun main() {\n    println(createTag(content = "Hello", tag = "h1"))\n}`,
      hints: ['Named arguments let you pass in any order.', 'Use paramName = value syntax.', 'content = "Hello", tag = "h1"'],
      concepts: ['named-args'],
    },
    {
      id: 'kt-func-6',
      title: 'Fix Missing Return Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the function that is missing its return type.',
      skeleton: `fun multiply(a: Int, b: Int) {\n    return a * b\n}`,
      solution: `fun multiply(a: Int, b: Int): Int {\n    return a * b\n}`,
      hints: ['Functions with a body block need an explicit return type.', 'a * b returns an Int.', 'Add : Int after the parameters.'],
      concepts: ['fun-declaration'],
    },
    {
      id: 'kt-func-7',
      title: 'Write a Power Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function power(base: Int, exponent: Int = 2): Int that returns base raised to exponent (use a loop).',
      skeleton: `fun power(base: Int, exponent: Int = 2): Int {\n    // compute base^exponent\n}`,
      solution: `fun power(base: Int, exponent: Int = 2): Int {\n    var result = 1\n    for (i in 1..exponent) {\n        result *= base\n    }\n    return result\n}`,
      hints: ['Start with result = 1.', 'Multiply by base, exponent times.', 'Default exponent is 2 for squaring.'],
      concepts: ['default-params', 'fun-declaration'],
    },
    {
      id: 'kt-func-8',
      title: 'Write a String Formatter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a single-expression function formatName(first: String, last: String): String that returns "Last, First".',
      skeleton: `// Write as a single-expression function`,
      solution: `fun formatName(first: String, last: String) = "\$last, \$first"`,
      hints: ['Use = instead of braces for single-expression.', 'fun formatName(...) = "..."', 'Use string templates.'],
      concepts: ['single-expression', 'string-templates'],
    },
    {
      id: 'kt-func-9',
      title: 'Predict Named Argument Call',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output when using named arguments.',
      skeleton: `fun info(name: String, age: Int, city: String = "Unknown") =\n    "\$name, \$age, \$city"\n\nfun main() {\n    println(info(age = 25, name = "Alice"))\n}`,
      solution: `Alice, 25, Unknown`,
      hints: ['Named args can be in any order.', 'city uses its default "Unknown".', 'Alice, 25, Unknown'],
      concepts: ['named-args', 'default-params'],
    },
    {
      id: 'kt-func-10',
      title: 'Fix Incorrect Default Usage',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the function call to skip the middle parameter using named args.',
      skeleton: `fun log(message: String, level: String = "INFO", timestamp: Boolean = true): String =\n    "\$level: \$message (ts=\$timestamp)"\n\nfun main() {\n    println(log("Hello", true))\n}`,
      solution: `fun log(message: String, level: String = "INFO", timestamp: Boolean = true): String =\n    "\$level: \$message (ts=\$timestamp)"\n\nfun main() {\n    println(log("Hello", timestamp = true))\n}`,
      hints: ['true is being passed as the level parameter.', 'Use named arguments to skip middle params.', 'log("Hello", timestamp = true)'],
      concepts: ['named-args', 'default-params'],
    },
    {
      id: 'kt-func-11',
      title: 'Unit Return Type',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a function with Unit return type (can be omitted).',
      skeleton: `fun printGreeting(name: String)___ {\n    println("Hello, \$name!")\n}`,
      solution: `fun printGreeting(name: String): Unit {\n    println("Hello, \$name!")\n}`,
      hints: ['Unit is like void in other languages.', 'Functions that return nothing return Unit.', ': Unit'],
      concepts: ['unit-type'],
    },
    {
      id: 'kt-func-12',
      title: 'Write a Vararg Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function sumAll(vararg numbers: Int): Int that sums all arguments.',
      skeleton: `fun sumAll(vararg numbers: Int): Int {\n    // sum all numbers\n}`,
      solution: `fun sumAll(vararg numbers: Int): Int {\n    var total = 0\n    for (n in numbers) {\n        total += n\n    }\n    return total\n}`,
      hints: ['vararg allows passing multiple arguments.', 'Iterate over numbers like an array.', 'for (n in numbers) total += n'],
      concepts: ['vararg'],
    },
    {
      id: 'kt-func-13',
      title: 'Write a Clamp Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function clamp(value: Int, min: Int = 0, max: Int = 100): Int that constrains value to the range [min, max].',
      skeleton: `fun clamp(value: Int, min: Int = 0, max: Int = 100): Int {\n    // constrain value\n}`,
      solution: `fun clamp(value: Int, min: Int = 0, max: Int = 100): Int {\n    return when {\n        value < min -> min\n        value > max -> max\n        else -> value\n    }\n}`,
      hints: ['If below min, return min. If above max, return max.', 'Use when for cleaner logic.', 'Three cases: below, above, or in range.'],
      concepts: ['default-params', 'when-expression'],
    },
    {
      id: 'kt-func-14',
      title: 'Predict Vararg Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of a vararg function call.',
      skeleton: `fun joinAll(separator: String, vararg words: String): String {\n    return words.joinToString(separator)\n}\n\nfun main() {\n    println(joinAll("-", "a", "b", "c"))\n}`,
      solution: `a-b-c`,
      hints: ['separator is "-".', 'words are "a", "b", "c".', 'joinToString joins with the separator.'],
      concepts: ['vararg'],
    },
    {
      id: 'kt-func-15',
      title: 'Fix Ambiguous Call',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the ambiguous function call by using named arguments.',
      skeleton: `fun display(text: String = "Hello", count: Int = 1, uppercase: Boolean = false): String {\n    val t = if (uppercase) text.uppercase() else text\n    return t.repeat(count)\n}\n\nfun main() {\n    println(display(3))\n}`,
      solution: `fun display(text: String = "Hello", count: Int = 1, uppercase: Boolean = false): String {\n    val t = if (uppercase) text.uppercase() else text\n    return t.repeat(count)\n}\n\nfun main() {\n    println(display(count = 3))\n}`,
      hints: ['3 is being passed as the text parameter (type mismatch).', 'Use named argument to specify count.', 'display(count = 3)'],
      concepts: ['named-args'],
    },
    {
      id: 'kt-func-16',
      title: 'Write a Recursive Fibonacci',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a recursive function fib(n: Int): Int that returns the nth Fibonacci number (fib(0)=0, fib(1)=1).',
      skeleton: `fun fib(n: Int): Int {\n    // recursive fibonacci\n}`,
      solution: `fun fib(n: Int): Int {\n    return when (n) {\n        0 -> 0\n        1 -> 1\n        else -> fib(n - 1) + fib(n - 2)\n    }\n}`,
      hints: ['Base cases: fib(0) = 0, fib(1) = 1.', 'Recursive case: fib(n) = fib(n-1) + fib(n-2).', 'Use when for clean base cases.'],
      concepts: ['recursion', 'fun-declaration'],
    },
    {
      id: 'kt-func-17',
      title: 'Refactor to Single-Expression',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the function to a single-expression function.',
      skeleton: `fun isPositive(n: Int): Boolean {\n    return n > 0\n}`,
      solution: `fun isPositive(n: Int) = n > 0`,
      hints: ['Remove braces and return.', 'Use = for single-expression functions.', 'fun isPositive(n: Int) = n > 0'],
      concepts: ['single-expression'],
    },
    {
      id: 'kt-func-18',
      title: 'Refactor to Use Default Params',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the two overloaded functions into one with a default parameter.',
      skeleton: `fun greet(name: String): String {\n    return "Hello, \$name!"\n}\n\nfun greet(): String {\n    return "Hello, World!"\n}`,
      solution: `fun greet(name: String = "World"): String {\n    return "Hello, \$name!"\n}`,
      hints: ['Default parameters replace function overloading.', 'Add = "World" to the name parameter.', 'One function with a default replaces two.'],
      concepts: ['default-params'],
    },
    {
      id: 'kt-func-19',
      title: 'Write a Higher-Order Peek',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function applyTwice(x: Int, f: (Int) -> Int): Int that applies f to x twice.',
      skeleton: `fun applyTwice(x: Int, f: (Int) -> Int): Int {\n    // apply f twice\n}`,
      solution: `fun applyTwice(x: Int, f: (Int) -> Int): Int {\n    return f(f(x))\n}`,
      hints: ['Apply f to x, then apply f to the result.', 'f(f(x))', 'Nested function calls.'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-func-20',
      title: 'Write a Local Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function validateAndFormat(name: String): String that uses a local function to validate (non-empty) and then returns the formatted name.',
      skeleton: `fun validateAndFormat(name: String): String {\n    // define a local function to validate\n    // return formatted name\n}`,
      solution: `fun validateAndFormat(name: String): String {\n    fun validate(input: String) {\n        require(input.isNotBlank()) { "Name must not be blank" }\n    }\n    validate(name)\n    return name.trim().replaceFirstChar { it.uppercase() }\n}`,
      hints: ['Local functions are defined inside other functions.', 'Use require() for validation.', 'Local functions can access outer parameters.'],
      concepts: ['local-functions'],
    },
  ],
};
