import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-null',
  title: '06. Null Safety',
  explanation: `## Null Safety in Kotlin\n\nKotlin's type system distinguishes nullable and non-nullable types to eliminate NullPointerExceptions:\n\n\`\`\`kotlin\nvar name: String = "Kotlin"  // Cannot be null\nvar nick: String? = null      // Nullable - can be null\n\`\`\`\n\n**Safe call operator ?.** - returns null if the receiver is null:\n\n\`\`\`kotlin\nval len: Int? = nick?.length  // null if nick is null\n\`\`\`\n\n**Elvis operator ?:** - provides a default when null:\n\n\`\`\`kotlin\nval len: Int = nick?.length ?: 0\n\`\`\`\n\n**Non-null assertion !!** - throws NPE if null (use sparingly):\n\n\`\`\`kotlin\nval len: Int = nick!!.length  // throws if nick is null\n\`\`\`\n\n**Safe let** - execute block only if non-null:\n\n\`\`\`kotlin\nnick?.let { println("Nickname: \$it") }\n\`\`\``,
  exercises: [
    {
      id: 'kt-null-1',
      title: 'Declare a Nullable Type',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a nullable String variable.',
      skeleton: `fun main() {\n    var name: String___ = null\n    println(name)\n}`,
      solution: `fun main() {\n    var name: String? = null\n    println(name)\n}`,
      hints: ['Append ? to make a type nullable.', 'String? allows null values.', '?'],
      concepts: ['nullable-types'],
    },
    {
      id: 'kt-null-2',
      title: 'Safe Call Operator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use the safe call operator to get the length of a nullable string.',
      skeleton: `fun main() {\n    val name: String? = "Kotlin"\n    println(name___length)\n}`,
      solution: `fun main() {\n    val name: String? = "Kotlin"\n    println(name?.length)\n}`,
      hints: ['Use ?. for safe property access.', '?. returns null if the receiver is null.', '?.'],
      concepts: ['safe-call'],
    },
    {
      id: 'kt-null-3',
      title: 'Elvis Operator',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Provide a default value of 0 when the length is null.',
      skeleton: `fun main() {\n    val name: String? = null\n    val len = name?.length ___ 0\n    println(len)\n}`,
      solution: `fun main() {\n    val name: String? = null\n    val len = name?.length ?: 0\n    println(len)\n}`,
      hints: ['The Elvis operator provides a default for null.', '?: is the Elvis operator.', '?:'],
      concepts: ['elvis-operator'],
    },
    {
      id: 'kt-null-4',
      title: 'Predict Safe Call Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output when calling a method on null.',
      skeleton: `fun main() {\n    val text: String? = null\n    println(text?.uppercase())\n}`,
      solution: `null`,
      hints: ['text is null.', '?. returns null when the receiver is null.', 'null'],
      concepts: ['safe-call'],
    },
    {
      id: 'kt-null-5',
      title: 'Predict Elvis Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of the Elvis operator.',
      skeleton: `fun main() {\n    val a: String? = null\n    val b: String? = "Hello"\n    println(a ?: "default")\n    println(b ?: "default")\n}`,
      solution: `default\nHello`,
      hints: ['a is null, so ?: returns "default".', 'b is "Hello" (non-null), so ?: returns "Hello".', 'default then Hello.'],
      concepts: ['elvis-operator'],
    },
    {
      id: 'kt-null-6',
      title: 'Non-Null Assertion',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use the non-null assertion to force unwrap a nullable value.',
      skeleton: `fun main() {\n    val name: String? = "Kotlin"\n    val len: Int = name___length\n    println(len)\n}`,
      solution: `fun main() {\n    val name: String? = "Kotlin"\n    val len: Int = name!!.length\n    println(len)\n}`,
      hints: ['!! asserts the value is non-null.', 'Throws NPE if the value is null.', '!!.'],
      concepts: ['non-null-assertion'],
    },
    {
      id: 'kt-null-7',
      title: 'Fix Null Safety Error',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the compilation error caused by calling a method on a nullable type.',
      skeleton: `fun main() {\n    val text: String? = "hello"\n    println(text.uppercase())\n}`,
      solution: `fun main() {\n    val text: String? = "hello"\n    println(text?.uppercase())\n}`,
      hints: ['Cannot call methods directly on nullable types.', 'Use the safe call operator ?.', 'text?.uppercase()'],
      concepts: ['safe-call'],
    },
    {
      id: 'kt-null-8',
      title: 'Safe Let Block',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function printIfPresent(value: String?) that prints the value only if it is not null, using let.',
      skeleton: `fun printIfPresent(value: String?) {\n    // use let\n}`,
      solution: `fun printIfPresent(value: String?) {\n    value?.let { println(it) }\n}`,
      hints: ['?.let executes the block only if non-null.', 'Inside let, the value is accessible as it.', 'value?.let { println(it) }'],
      concepts: ['let'],
    },
    {
      id: 'kt-null-9',
      title: 'Write a Null-Safe Getter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function safeLength(s: String?): Int that returns the string length or 0 if null.',
      skeleton: `fun safeLength(s: String?): Int {\n    // return length or 0\n}`,
      solution: `fun safeLength(s: String?): Int {\n    return s?.length ?: 0\n}`,
      hints: ['Use safe call with Elvis.', 's?.length ?: 0', 'Combine ?. and ?:.'],
      concepts: ['safe-call', 'elvis-operator'],
    },
    {
      id: 'kt-null-10',
      title: 'Fix Double Bang Crash',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code to avoid a NullPointerException - use safe call and Elvis instead.',
      skeleton: `fun getLength(s: String?): Int {\n    return s!!.length\n}`,
      solution: `fun getLength(s: String?): Int {\n    return s?.length ?: 0\n}`,
      hints: ['!! will crash if s is null.', 'Replace !! with ?. and ?:.', 's?.length ?: 0 is safe.'],
      concepts: ['safe-call', 'elvis-operator'],
    },
    {
      id: 'kt-null-11',
      title: 'Write a Chained Safe Call',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Given a data class User(val address: Address?) and data class Address(val city: String?), write a function getCity(user: User?): String that returns the city or "Unknown".',
      skeleton: `data class Address(val city: String?)\ndata class User(val address: Address?)\n\nfun getCity(user: User?): String {\n    // chain safe calls\n}`,
      solution: `data class Address(val city: String?)\ndata class User(val address: Address?)\n\nfun getCity(user: User?): String {\n    return user?.address?.city ?: "Unknown"\n}`,
      hints: ['Chain ?. for nested nullable access.', 'user?.address?.city chains through nullables.', 'Add ?: "Unknown" at the end.'],
      concepts: ['safe-call', 'elvis-operator'],
    },
    {
      id: 'kt-null-12',
      title: 'Predict Let Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of let on a nullable value.',
      skeleton: `fun main() {\n    val x: Int? = 5\n    val y: Int? = null\n    x?.let { print("\${it * 2} ") }\n    y?.let { print("\${it * 2} ") }\n    println("done")\n}`,
      solution: `10 done`,
      hints: ['x is 5, so let runs: 5*2=10.', 'y is null, so let does not run.', '10 done'],
      concepts: ['let'],
    },
    {
      id: 'kt-null-13',
      title: 'Write a Null Coalescing Chain',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function firstNonNull(a: String?, b: String?, c: String?): String that returns the first non-null value, or "none".',
      skeleton: `fun firstNonNull(a: String?, b: String?, c: String?): String {\n    // return first non-null\n}`,
      solution: `fun firstNonNull(a: String?, b: String?, c: String?): String {\n    return a ?: b ?: c ?: "none"\n}`,
      hints: ['Chain Elvis operators.', 'a ?: b ?: c ?: "none"', 'Each ?: falls through if null.'],
      concepts: ['elvis-operator'],
    },
    {
      id: 'kt-null-14',
      title: 'Write a Smart Cast with If',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function describeNullable(value: String?): String that returns "Empty" if null, "Blank" if blank, or the uppercase value.',
      skeleton: `fun describeNullable(value: String?): String {\n    // handle null, blank, or return uppercase\n}`,
      solution: `fun describeNullable(value: String?): String {\n    if (value == null) return "Empty"\n    if (value.isBlank()) return "Blank"\n    return value.uppercase()\n}`,
      hints: ['After a null check, Kotlin smart casts to non-null.', 'Check null first, then blank.', 'After if (value == null) return, value is smart cast to String.'],
      concepts: ['smart-cast', 'nullable-types'],
    },
    {
      id: 'kt-null-15',
      title: 'Fix Nullable Return',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the function to properly return a nullable type.',
      skeleton: `fun findItem(items: List<String>, target: String): String {\n    for (item in items) {\n        if (item == target) return item\n    }\n    return null\n}`,
      solution: `fun findItem(items: List<String>, target: String): String? {\n    for (item in items) {\n        if (item == target) return item\n    }\n    return null\n}`,
      hints: ['The function can return null but the return type is not nullable.', 'Change the return type to String?.', 'String? allows returning null.'],
      concepts: ['nullable-types'],
    },
    {
      id: 'kt-null-16',
      title: 'Write a Null-Safe Map Operation',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function uppercaseOrNull(s: String?): String? that returns the uppercase string or null.',
      skeleton: `fun uppercaseOrNull(s: String?): String? {\n    // return uppercase or null\n}`,
      solution: `fun uppercaseOrNull(s: String?): String? {\n    return s?.uppercase()\n}`,
      hints: ['Safe call returns null if receiver is null.', 's?.uppercase() returns String?.', 'The whole expression is nullable.'],
      concepts: ['safe-call'],
    },
    {
      id: 'kt-null-17',
      title: 'Refactor to Elvis',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the if-null check to use the Elvis operator.',
      skeleton: `fun getDisplayName(name: String?): String {\n    if (name != null) {\n        return name\n    } else {\n        return "Anonymous"\n    }\n}`,
      solution: `fun getDisplayName(name: String?): String {\n    return name ?: "Anonymous"\n}`,
      hints: ['The Elvis operator replaces if-null checks.', 'name ?: "Anonymous"', '?: provides the default for null.'],
      concepts: ['elvis-operator'],
    },
    {
      id: 'kt-null-18',
      title: 'Refactor to Safe Call Chain',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the nested null checks into a safe call chain.',
      skeleton: `data class Company(val address: Address?)\ndata class Address(val city: String?)\n\nfun getCityName(company: Company?): String {\n    if (company != null) {\n        if (company.address != null) {\n            if (company.address.city != null) {\n                return company.address.city\n            }\n        }\n    }\n    return "Unknown"\n}`,
      solution: `data class Company(val address: Address?)\ndata class Address(val city: String?)\n\nfun getCityName(company: Company?): String {\n    return company?.address?.city ?: "Unknown"\n}`,
      hints: ['Chain ?. calls for nested nullable access.', 'company?.address?.city chains through nullables.', 'Add ?: "Unknown" for the default.'],
      concepts: ['safe-call', 'elvis-operator'],
    },
    {
      id: 'kt-null-19',
      title: 'Write a RequireNotNull',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function ensureNotNull(value: String?): String that throws IllegalArgumentException if null, or returns the value.',
      skeleton: `fun ensureNotNull(value: String?): String {\n    // throw if null, return otherwise\n}`,
      solution: `fun ensureNotNull(value: String?): String {\n    return requireNotNull(value) { "Value must not be null" }\n}`,
      hints: ['Kotlin has a built-in requireNotNull function.', 'requireNotNull throws IllegalArgumentException if null.', 'requireNotNull(value) { "message" }'],
      concepts: ['requireNotNull'],
    },
    {
      id: 'kt-null-20',
      title: 'Predict Chained Null Safety',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of chained null-safe operations.',
      skeleton: `fun main() {\n    val words: List<String>? = listOf("hello", "world")\n    val result = words?.firstOrNull()?.uppercase() ?: "NONE"\n    println(result)\n    \n    val empty: List<String>? = null\n    val result2 = empty?.firstOrNull()?.uppercase() ?: "NONE"\n    println(result2)\n}`,
      solution: `HELLO\nNONE`,
      hints: ['words is non-null, firstOrNull returns "hello", uppercase is "HELLO".', 'empty is null, so the whole chain is null.', 'Elvis provides "NONE" for the null chain.'],
      concepts: ['safe-call', 'elvis-operator'],
    },
  ],
};
