import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-class',
  title: '07. Classes',
  explanation: `## Classes in Kotlin\n\nKotlin classes are declared with the **class** keyword:\n\n\`\`\`kotlin\nclass Person(val name: String, var age: Int)\n\`\`\`\n\nThe **primary constructor** is part of the class header. Parameters with val/var become properties:\n\n\`\`\`kotlin\nval p = Person("Alice", 30)\nprintln(p.name)  // Alice\np.age = 31       // OK - age is var\n\`\`\`\n\n**Init blocks** run during construction:\n\n\`\`\`kotlin\nclass Person(val name: String) {\n    init {\n        require(name.isNotBlank()) { "Name required" }\n    }\n}\n\`\`\`\n\n**Properties** can have custom getters/setters:\n\n\`\`\`kotlin\nclass Rectangle(val width: Double, val height: Double) {\n    val area: Double\n        get() = width * height\n}\n\`\`\`\n\n**Secondary constructors** use \`constructor\`:\n\n\`\`\`kotlin\nclass Person(val name: String, val age: Int) {\n    constructor(name: String) : this(name, 0)\n}\n\`\`\``,
  exercises: [
    {
      id: 'kt-class-1',
      title: 'Declare a Basic Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a class with a primary constructor.',
      skeleton: `___ Person(___ name: String, ___ age: Int)\n\nfun main() {\n    val p = Person("Alice", 30)\n    println("\${p.name} is \${p.age}")\n}`,
      solution: `class Person(val name: String, var age: Int)\n\nfun main() {\n    val p = Person("Alice", 30)\n    println("\${p.name} is \${p.age}")\n}`,
      hints: ['Use class keyword to declare.', 'val for read-only, var for mutable properties.', 'class Person(val name: String, var age: Int)'],
      concepts: ['class', 'primary-constructor'],
    },
    {
      id: 'kt-class-2',
      title: 'Init Block',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add an init block that validates the name is not blank.',
      skeleton: `class User(val name: String) {\n    ___ {\n        require(name.isNotBlank()) { "Name must not be blank" }\n    }\n}`,
      solution: `class User(val name: String) {\n    init {\n        require(name.isNotBlank()) { "Name must not be blank" }\n    }\n}`,
      hints: ['init blocks run during construction.', 'The keyword is init.', 'init { ... }'],
      concepts: ['init-block'],
    },
    {
      id: 'kt-class-3',
      title: 'Custom Getter',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a custom getter for the area property.',
      skeleton: `class Circle(val radius: Double) {\n    val area: Double\n        ___() = 3.14159 * radius * radius\n}`,
      solution: `class Circle(val radius: Double) {\n    val area: Double\n        get() = 3.14159 * radius * radius\n}`,
      hints: ['Custom getters use the get() syntax.', 'get() = expression computes the value.', 'get()'],
      concepts: ['properties'],
    },
    {
      id: 'kt-class-4',
      title: 'Predict Property Access',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of property access on a class.',
      skeleton: `class Counter(var count: Int = 0) {\n    fun increment() { count++ }\n}\n\nfun main() {\n    val c = Counter()\n    c.increment()\n    c.increment()\n    c.increment()\n    println(c.count)\n}`,
      solution: `3`,
      hints: ['Counter starts at 0.', 'increment is called 3 times.', '0 + 3 = 3'],
      concepts: ['properties', 'class'],
    },
    {
      id: 'kt-class-5',
      title: 'Write a Rectangle Class',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a class Rectangle with val width and val height, and a computed property area.',
      skeleton: `// Define Rectangle class with width, height, and area`,
      solution: `class Rectangle(val width: Double, val height: Double) {\n    val area: Double\n        get() = width * height\n}`,
      hints: ['Primary constructor takes width and height.', 'area is a computed property with a custom getter.', 'get() = width * height'],
      concepts: ['class', 'properties'],
    },
    {
      id: 'kt-class-6',
      title: 'Fix Missing Val/Var in Constructor',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the class so that name and age are accessible as properties.',
      skeleton: `class Person(name: String, age: Int)\n\nfun main() {\n    val p = Person("Alice", 30)\n    println(p.name)\n    println(p.age)\n}`,
      solution: `class Person(val name: String, val age: Int)\n\nfun main() {\n    val p = Person("Alice", 30)\n    println(p.name)\n    println(p.age)\n}`,
      hints: ['Without val/var, constructor parameters are not properties.', 'Add val to make them accessible.', 'class Person(val name: String, val age: Int)'],
      concepts: ['primary-constructor'],
    },
    {
      id: 'kt-class-7',
      title: 'Write a BankAccount Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class BankAccount with val owner: String, a private var _balance: Double = 0.0, a val balance getter, and methods deposit(amount: Double) and withdraw(amount: Double): Boolean.',
      skeleton: `// Define BankAccount class`,
      solution: `class BankAccount(val owner: String) {\n    private var _balance: Double = 0.0\n    val balance: Double\n        get() = _balance\n\n    fun deposit(amount: Double) {\n        _balance += amount\n    }\n\n    fun withdraw(amount: Double): Boolean {\n        return if (amount <= _balance) {\n            _balance -= amount\n            true\n        } else {\n            false\n        }\n    }\n}`,
      hints: ['Use a private backing field for balance.', 'Expose balance as a read-only property.', 'withdraw returns false if insufficient funds.'],
      concepts: ['class', 'properties', 'encapsulation'],
    },
    {
      id: 'kt-class-8',
      title: 'Secondary Constructor',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Add a secondary constructor that takes only a name and defaults age to 0.',
      skeleton: `class Person(val name: String, val age: Int) {\n    ___(name: String) : ___(name, 0)\n}`,
      solution: `class Person(val name: String, val age: Int) {\n    constructor(name: String) : this(name, 0)\n}`,
      hints: ['Secondary constructors use the constructor keyword.', 'They must delegate to the primary constructor.', 'constructor(name: String) : this(name, 0)'],
      concepts: ['secondary-constructor'],
    },
    {
      id: 'kt-class-9',
      title: 'Write a ToString Override',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a class Product(val name: String, val price: Double) that overrides toString to return "Product(name=..., price=...)".',
      skeleton: `class Product(val name: String, val price: Double) {\n    // override toString\n}`,
      solution: `class Product(val name: String, val price: Double) {\n    override fun toString(): String {\n        return "Product(name=\$name, price=\$price)"\n    }\n}`,
      hints: ['Override toString() from Any.', 'Use the override keyword.', 'override fun toString(): String'],
      concepts: ['class', 'override'],
    },
    {
      id: 'kt-class-10',
      title: 'Predict Init Block Order',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the order of init block and property initializer execution.',
      skeleton: `class Demo(val x: Int) {\n    val a = run { println("a init"); 1 }\n    init { println("init block") }\n    val b = run { println("b init"); 2 }\n}\n\nfun main() {\n    Demo(0)\n}`,
      solution: `a init\ninit block\nb init`,
      hints: ['Properties and init blocks execute in declaration order.', 'a is first, then init, then b.', 'Top-to-bottom order in the class body.'],
      concepts: ['init-block', 'properties'],
    },
    {
      id: 'kt-class-11',
      title: 'Fix Property Custom Setter',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the custom setter so it clamps the value between 0 and 100.',
      skeleton: `class Score {\n    var value: Int = 0\n        set(v) {\n            field = v\n        }\n}`,
      solution: `class Score {\n    var value: Int = 0\n        set(v) {\n            field = v.coerceIn(0, 100)\n        }\n}`,
      hints: ['The setter should clamp the value.', 'Use coerceIn(0, 100) to restrict the range.', 'field = v.coerceIn(0, 100)'],
      concepts: ['properties'],
    },
    {
      id: 'kt-class-12',
      title: 'Write a Stack Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class IntStack with methods push(value: Int), pop(): Int?, and peek(): Int?, backed by a MutableList.',
      skeleton: `class IntStack {\n    // implement push, pop, peek\n}`,
      solution: `class IntStack {\n    private val items = mutableListOf<Int>()\n\n    fun push(value: Int) {\n        items.add(value)\n    }\n\n    fun pop(): Int? {\n        return if (items.isNotEmpty()) items.removeAt(items.size - 1) else null\n    }\n\n    fun peek(): Int? {\n        return items.lastOrNull()\n    }\n}`,
      hints: ['Use a MutableList as backing storage.', 'pop removes and returns the last element.', 'peek returns the last element without removing.'],
      concepts: ['class', 'encapsulation'],
    },
    {
      id: 'kt-class-13',
      title: 'Predict Secondary Constructor',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output from secondary constructor delegation.',
      skeleton: `class Log(val message: String, val level: String) {\n    constructor(message: String) : this(message, "INFO")\n\n    override fun toString() = "[\$level] \$message"\n}\n\nfun main() {\n    println(Log("Starting"))\n    println(Log("Oops", "ERROR"))\n}`,
      solution: `[INFO] Starting\n[ERROR] Oops`,
      hints: ['First uses secondary constructor, level defaults to "INFO".', 'Second uses primary constructor directly.', '[INFO] Starting then [ERROR] Oops.'],
      concepts: ['secondary-constructor'],
    },
    {
      id: 'kt-class-14',
      title: 'Write a Lateinit Property',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class Config with a lateinit var databaseUrl: String and a method isInitialized(): Boolean.',
      skeleton: `class Config {\n    // lateinit property and check method\n}`,
      solution: `class Config {\n    lateinit var databaseUrl: String\n\n    fun isInitialized(): Boolean {\n        return ::databaseUrl.isInitialized\n    }\n}`,
      hints: ['lateinit allows deferred initialization.', 'Check with ::property.isInitialized.', 'lateinit var databaseUrl: String'],
      concepts: ['lateinit'],
    },
    {
      id: 'kt-class-15',
      title: 'Write a Class with Method Chaining',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class StringBuilder with a private val buffer: MutableList<String>, a method append(s: String): StringBuilder that returns this, and build(): String.',
      skeleton: `class StringBuilder {\n    // implement with method chaining\n}`,
      solution: `class StringBuilder {\n    private val buffer = mutableListOf<String>()\n\n    fun append(s: String): StringBuilder {\n        buffer.add(s)\n        return this\n    }\n\n    fun build(): String {\n        return buffer.joinToString("")\n    }\n}`,
      hints: ['Return this from append for chaining.', 'Use a MutableList to store parts.', 'joinToString("") combines all parts.'],
      concepts: ['class', 'method-chaining'],
    },
    {
      id: 'kt-class-16',
      title: 'Refactor to Primary Constructor',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the class to use a primary constructor instead of initializing in the body.',
      skeleton: `class Car {\n    val make: String\n    val model: String\n    val year: Int\n\n    constructor(make: String, model: String, year: Int) {\n        this.make = make\n        this.model = model\n        this.year = year\n    }\n}`,
      solution: `class Car(val make: String, val model: String, val year: Int)`,
      hints: ['Move properties into the primary constructor.', 'Primary constructor is in the class header.', 'class Car(val make: String, val model: String, val year: Int)'],
      concepts: ['primary-constructor'],
    },
    {
      id: 'kt-class-17',
      title: 'Refactor to Computed Property',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the method to a computed property.',
      skeleton: `class Circle(val radius: Double) {\n    fun getArea(): Double {\n        return 3.14159 * radius * radius\n    }\n    fun getCircumference(): Double {\n        return 2 * 3.14159 * radius\n    }\n}`,
      solution: `class Circle(val radius: Double) {\n    val area: Double\n        get() = 3.14159 * radius * radius\n    val circumference: Double\n        get() = 2 * 3.14159 * radius\n}`,
      hints: ['Replace getter methods with computed properties.', 'val area get() = expression', 'Properties are more idiomatic in Kotlin.'],
      concepts: ['properties'],
    },
    {
      id: 'kt-class-18',
      title: 'Write a Class with Visibility',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class Password with a private val hash: String computed from the input, and a method verify(input: String): Boolean.',
      skeleton: `class Password(input: String) {\n    // private hash, verify method\n}`,
      solution: `class Password(input: String) {\n    private val hash: String = input.reversed()\n\n    fun verify(input: String): Boolean {\n        return input.reversed() == hash\n    }\n}`,
      hints: ['Note: input without val/var is just a constructor param, not a property.', 'Store the hash as a private property.', 'verify compares the input hash with the stored hash.'],
      concepts: ['class', 'encapsulation'],
    },
    {
      id: 'kt-class-19',
      title: 'Write an Inner Class',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class Outer(val x: Int) with an inner class Inner(val y: Int) that has a method sum(): Int returning x + y.',
      skeleton: `class Outer(val x: Int) {\n    // define inner class\n}`,
      solution: `class Outer(val x: Int) {\n    inner class Inner(val y: Int) {\n        fun sum(): Int = x + y\n    }\n}`,
      hints: ['inner keyword gives access to outer class members.', 'Without inner, nested classes cannot access outer members.', 'inner class Inner(val y: Int)'],
      concepts: ['inner-class'],
    },
    {
      id: 'kt-class-20',
      title: 'Write a Class with Multiple Init Blocks',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class Validated(val email: String, val age: Int) with two init blocks: one validating email contains "@", another validating age >= 0.',
      skeleton: `class Validated(val email: String, val age: Int) {\n    // two init blocks\n}`,
      solution: `class Validated(val email: String, val age: Int) {\n    init {\n        require("@" in email) { "Invalid email" }\n    }\n\n    init {\n        require(age >= 0) { "Age must be non-negative" }\n    }\n}`,
      hints: ['A class can have multiple init blocks.', 'They execute in order of declaration.', 'Use require() for validation.'],
      concepts: ['init-block'],
    },
  ],
};
