import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-data',
  title: '08. Data Classes',
  explanation: `## Data Classes in Kotlin\n\nData classes automatically generate useful methods from primary constructor properties:\n\n\`\`\`kotlin\ndata class User(val name: String, val age: Int)\n\`\`\`\n\nThis generates:\n- **equals()** / **hashCode()** - based on all properties\n- **toString()** - e.g. \`User(name=Alice, age=30)\`\n- **copy()** - creates a copy with optional modifications\n- **componentN()** - for destructuring\n\n\`\`\`kotlin\nval user = User("Alice", 30)\nval copy = user.copy(age = 31)\nval (name, age) = user  // destructuring\nprintln(user)           // User(name=Alice, age=30)\n\`\`\`\n\nRules for data classes:\n- Must have at least one val/var in the primary constructor\n- Cannot be abstract, open, sealed, or inner\n- Properties in the body are NOT included in generated methods`,
  exercises: [
    {
      id: 'kt-data-1',
      title: 'Declare a Data Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a data class for a Point with x and y coordinates.',
      skeleton: `___ ___ Point(val x: Int, val y: Int)`,
      solution: `data class Point(val x: Int, val y: Int)`,
      hints: ['Data classes use the data modifier.', 'data class declares a data class.', 'data class'],
      concepts: ['data-class'],
    },
    {
      id: 'kt-data-2',
      title: 'Predict toString Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the auto-generated toString output.',
      skeleton: `data class Book(val title: String, val author: String)\n\nfun main() {\n    println(Book("1984", "Orwell"))\n}`,
      solution: `Book(title=1984, author=Orwell)`,
      hints: ['Data classes generate toString from constructor properties.', 'Format: ClassName(prop1=val1, prop2=val2)', 'Book(title=1984, author=Orwell)'],
      concepts: ['data-class', 'toString'],
    },
    {
      id: 'kt-data-3',
      title: 'Copy with Modification',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use copy() to create a modified copy of a data class instance.',
      skeleton: `data class User(val name: String, val age: Int)\n\nfun main() {\n    val alice = User("Alice", 30)\n    val older = alice.___(age = 31)\n    println(older)\n}`,
      solution: `data class User(val name: String, val age: Int)\n\nfun main() {\n    val alice = User("Alice", 30)\n    val older = alice.copy(age = 31)\n    println(older)\n}`,
      hints: ['copy() creates a new instance with modified properties.', 'Pass named arguments for changes.', 'copy(age = 31)'],
      concepts: ['copy'],
    },
    {
      id: 'kt-data-4',
      title: 'Destructuring Declaration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Destructure a data class into individual variables.',
      skeleton: `data class Pair(val first: String, val second: Int)\n\nfun main() {\n    val pair = Pair("Alice", 30)\n    val (___, ___) = pair\n    println("\$name is \$age")\n}`,
      solution: `data class Pair(val first: String, val second: Int)\n\nfun main() {\n    val pair = Pair("Alice", 30)\n    val (name, age) = pair\n    println("\$name is \$age")\n}`,
      hints: ['Destructuring uses val (a, b) = instance.', 'Variables map to component1(), component2() etc.', 'val (name, age) = pair'],
      concepts: ['destructuring'],
    },
    {
      id: 'kt-data-5',
      title: 'Predict Equals Behavior',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of data class equality.',
      skeleton: `data class Color(val r: Int, val g: Int, val b: Int)\n\nfun main() {\n    val a = Color(255, 0, 0)\n    val b = Color(255, 0, 0)\n    println(a == b)\n    println(a === b)\n}`,
      solution: `true\nfalse`,
      hints: ['== uses the generated equals (structural equality).', '=== checks reference equality.', 'Same values but different objects.'],
      concepts: ['equals', 'data-class'],
    },
    {
      id: 'kt-data-6',
      title: 'Fix Non-Data Class Equality',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the class so that two instances with the same values are equal.',
      skeleton: `class Point(val x: Int, val y: Int)\n\nfun main() {\n    val a = Point(1, 2)\n    val b = Point(1, 2)\n    println(a == b)  // should print true\n}`,
      solution: `data class Point(val x: Int, val y: Int)\n\nfun main() {\n    val a = Point(1, 2)\n    val b = Point(1, 2)\n    println(a == b)  // should print true\n}`,
      hints: ['Regular classes use reference equality by default.', 'Add data modifier for auto-generated equals.', 'data class Point(...)'],
      concepts: ['data-class', 'equals'],
    },
    {
      id: 'kt-data-7',
      title: 'Write a Data Class with Methods',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a data class Vector2D(val x: Double, val y: Double) with a method magnitude(): Double.',
      skeleton: `// Define data class with magnitude method`,
      solution: `data class Vector2D(val x: Double, val y: Double) {\n    fun magnitude(): Double = Math.sqrt(x * x + y * y)\n}`,
      hints: ['Data classes can have methods.', 'Magnitude = sqrt(x^2 + y^2).', 'Math.sqrt(x * x + y * y)'],
      concepts: ['data-class'],
    },
    {
      id: 'kt-data-8',
      title: 'Write a Copy Modifier Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function incrementAge(user: User): User that returns a copy with age + 1.',
      skeleton: `data class User(val name: String, val age: Int)\n\nfun incrementAge(user: User): User {\n    // return copy with incremented age\n}`,
      solution: `data class User(val name: String, val age: Int)\n\nfun incrementAge(user: User): User {\n    return user.copy(age = user.age + 1)\n}`,
      hints: ['Use copy() with named argument.', 'user.copy(age = user.age + 1)', 'copy creates a new instance.'],
      concepts: ['copy'],
    },
    {
      id: 'kt-data-9',
      title: 'Fix Property Not in Equals',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Understand why two instances are considered equal despite different timestamps - move timestamp to constructor.',
      skeleton: `data class Event(val name: String) {\n    var timestamp: Long = System.currentTimeMillis()\n}\n\nfun main() {\n    val a = Event("click")\n    val b = Event("click")\n    b.timestamp = 999\n    println(a == b)  // prints true - but they have different timestamps!\n}`,
      solution: `data class Event(val name: String, var timestamp: Long = System.currentTimeMillis())\n\nfun main() {\n    val a = Event("click")\n    val b = Event("click")\n    b.timestamp = 999\n    println(a == b)  // now prints false\n}`,
      hints: ['Properties in the class body are NOT part of equals/hashCode.', 'Move timestamp to the primary constructor.', 'Only constructor properties are used in generated methods.'],
      concepts: ['data-class', 'equals'],
    },
    {
      id: 'kt-data-10',
      title: 'Destructuring in a Loop',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function printPairs(pairs: List<Pair<String, Int>>) that destructures each pair and prints "name: value".',
      skeleton: `fun printPairs(pairs: List<Pair<String, Int>>) {\n    // destructure and print each pair\n}`,
      solution: `fun printPairs(pairs: List<Pair<String, Int>>) {\n    for ((name, value) in pairs) {\n        println("\$name: \$value")\n    }\n}`,
      hints: ['Destructure in the for loop.', 'for ((name, value) in pairs)', 'Pair supports component1() and component2().'],
      concepts: ['destructuring'],
    },
    {
      id: 'kt-data-11',
      title: 'Write a Triple Data Class',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a data class RGB(val r: Int, val g: Int, val b: Int) and a function toHex(color: RGB): String.',
      skeleton: `// Define RGB data class and toHex function`,
      solution: `data class RGB(val r: Int, val g: Int, val b: Int)\n\nfun toHex(color: RGB): String {\n    return "#%02x%02x%02x".format(color.r, color.g, color.b)\n}`,
      hints: ['data class RGB(val r: Int, val g: Int, val b: Int)', 'Use String.format for hex conversion.', '%02x formats as 2-digit hex.'],
      concepts: ['data-class'],
    },
    {
      id: 'kt-data-12',
      title: 'Predict Copy Behavior',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output after copy.',
      skeleton: `data class Config(val host: String, val port: Int)\n\nfun main() {\n    val dev = Config("localhost", 8080)\n    val prod = dev.copy(host = "example.com", port = 443)\n    println(dev)\n    println(prod)\n}`,
      solution: `Config(host=localhost, port=8080)\nConfig(host=example.com, port=443)`,
      hints: ['copy creates a new instance; original is unchanged.', 'dev stays the same.', 'prod has the new values.'],
      concepts: ['copy'],
    },
    {
      id: 'kt-data-13',
      title: 'Write a Data Class Transform',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function normalizeUser(user: User): User that returns a copy with name trimmed and lowercased.',
      skeleton: `data class User(val name: String, val email: String)\n\nfun normalizeUser(user: User): User {\n    // normalize name\n}`,
      solution: `data class User(val name: String, val email: String)\n\nfun normalizeUser(user: User): User {\n    return user.copy(name = user.name.trim().lowercase())\n}`,
      hints: ['Use copy with the transformed value.', 'user.copy(name = user.name.trim().lowercase())', 'trim removes whitespace, lowercase converts case.'],
      concepts: ['copy', 'data-class'],
    },
    {
      id: 'kt-data-14',
      title: 'Fix Data Class Copy Bug',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code that tries to mutate a val property instead of using copy.',
      skeleton: `data class Settings(val theme: String, val fontSize: Int)\n\nfun main() {\n    val s = Settings("dark", 14)\n    s.fontSize = 16\n    println(s)\n}`,
      solution: `data class Settings(val theme: String, val fontSize: Int)\n\nfun main() {\n    val s = Settings("dark", 14)\n    val updated = s.copy(fontSize = 16)\n    println(updated)\n}`,
      hints: ['val properties cannot be reassigned.', 'Use copy() to create a modified version.', 's.copy(fontSize = 16)'],
      concepts: ['copy', 'val'],
    },
    {
      id: 'kt-data-15',
      title: 'Write Destructuring Swap',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function swap(pair: Pair<Int, Int>): Pair<Int, Int> that returns the pair with swapped values.',
      skeleton: `fun swap(pair: Pair<Int, Int>): Pair<Int, Int> {\n    // destructure and swap\n}`,
      solution: `fun swap(pair: Pair<Int, Int>): Pair<Int, Int> {\n    val (a, b) = pair\n    return Pair(b, a)\n}`,
      hints: ['Destructure with val (a, b) = pair.', 'Return Pair(b, a).', 'Destructuring makes this clean.'],
      concepts: ['destructuring'],
    },
    {
      id: 'kt-data-16',
      title: 'Predict HashCode',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict whether two data class instances have the same hash code.',
      skeleton: `data class Key(val id: Int, val name: String)\n\nfun main() {\n    val a = Key(1, "alpha")\n    val b = Key(1, "alpha")\n    println(a.hashCode() == b.hashCode())\n}`,
      solution: `true`,
      hints: ['Data classes generate hashCode from constructor properties.', 'Same values produce the same hash code.', 'true'],
      concepts: ['hashCode', 'data-class'],
    },
    {
      id: 'kt-data-17',
      title: 'Refactor to Data Class',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the regular class to a data class, removing manual equals/hashCode/toString.',
      skeleton: `class Coordinate(val lat: Double, val lng: Double) {\n    override fun equals(other: Any?): Boolean {\n        if (other !is Coordinate) return false\n        return lat == other.lat && lng == other.lng\n    }\n\n    override fun hashCode(): Int = 31 * lat.hashCode() + lng.hashCode()\n\n    override fun toString(): String = "Coordinate(lat=\$lat, lng=\$lng)"\n}`,
      solution: `data class Coordinate(val lat: Double, val lng: Double)`,
      hints: ['data class generates equals, hashCode, and toString.', 'Remove all manual overrides.', 'data class Coordinate(val lat: Double, val lng: Double)'],
      concepts: ['data-class'],
    },
    {
      id: 'kt-data-18',
      title: 'Refactor Mutable to Immutable Copy',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor from mutable var properties to immutable val with copy-based updates.',
      skeleton: `data class Profile(var name: String, var bio: String)\n\nfun updateBio(profile: Profile, newBio: String) {\n    profile.bio = newBio\n}`,
      solution: `data class Profile(val name: String, val bio: String)\n\nfun updateBio(profile: Profile, newBio: String): Profile {\n    return profile.copy(bio = newBio)\n}`,
      hints: ['Change var to val for immutability.', 'Return a new copy instead of mutating.', 'profile.copy(bio = newBio)'],
      concepts: ['data-class', 'copy'],
    },
    {
      id: 'kt-data-19',
      title: 'Write a Data Class List Filter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function getAdults(users: List<User>): List<User> that returns users with age >= 18.',
      skeleton: `data class User(val name: String, val age: Int)\n\nfun getAdults(users: List<User>): List<User> {\n    // filter adults\n}`,
      solution: `data class User(val name: String, val age: Int)\n\nfun getAdults(users: List<User>): List<User> {\n    return users.filter { it.age >= 18 }\n}`,
      hints: ['Use filter with a predicate.', 'it.age >= 18 checks adult age.', 'users.filter { it.age >= 18 }'],
      concepts: ['data-class', 'filter'],
    },
    {
      id: 'kt-data-20',
      title: 'Write a Component Functions Demo',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that uses component1() and component2() explicitly on a data class.',
      skeleton: `data class NameAge(val name: String, val age: Int)\n\nfun describe(na: NameAge): String {\n    // use component1() and component2() explicitly\n}`,
      solution: `data class NameAge(val name: String, val age: Int)\n\nfun describe(na: NameAge): String {\n    return "\${na.component1()} is \${na.component2()} years old"\n}`,
      hints: ['component1() returns the first property.', 'component2() returns the second property.', 'These are what destructuring uses under the hood.'],
      concepts: ['destructuring', 'data-class'],
    },
  ],
};
