import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-inherit',
  title: '09. Inheritance',
  explanation: `## Inheritance in Kotlin\n\nClasses are **final by default** in Kotlin. Use **open** to allow inheritance:\n\n\`\`\`kotlin\nopen class Animal(val name: String) {\n    open fun speak(): String = "..."\n}\n\nclass Dog(name: String) : Animal(name) {\n    override fun speak(): String = "Woof!"\n}\n\`\`\`\n\n**Key points:**\n- Mark classes and methods with \`open\` to allow overriding\n- Use \`override\` to override a method\n- Use \`super\` to call the parent implementation\n- **abstract** classes/methods must be overridden\n\n\`\`\`kotlin\nabstract class Shape {\n    abstract fun area(): Double\n}\n\nclass Circle(val radius: Double) : Shape() {\n    override fun area() = 3.14159 * radius * radius\n}\n\`\`\`\n\nAll classes inherit from **Any** (which provides equals, hashCode, toString).`,
  exercises: [
    {
      id: 'kt-inherit-1',
      title: 'Open Class Declaration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Mark a class as open so it can be extended.',
      skeleton: `___ class Vehicle(val brand: String) {\n    ___ fun describe(): String = "Vehicle: \$brand"\n}`,
      solution: `open class Vehicle(val brand: String) {\n    open fun describe(): String = "Vehicle: \$brand"\n}`,
      hints: ['Classes are final by default in Kotlin.', 'Use open to allow inheritance.', 'open class, open fun'],
      concepts: ['open'],
    },
    {
      id: 'kt-inherit-2',
      title: 'Override a Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Override the speak method in the subclass.',
      skeleton: `open class Animal {\n    open fun speak() = "..."\n}\n\nclass Cat : Animal() {\n    ___ fun speak() = "Meow!"\n}`,
      solution: `open class Animal {\n    open fun speak() = "..."\n}\n\nclass Cat : Animal() {\n    override fun speak() = "Meow!"\n}`,
      hints: ['Use override when implementing a parent method.', 'override fun speak()', 'override'],
      concepts: ['override'],
    },
    {
      id: 'kt-inherit-3',
      title: 'Call Super Implementation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Call the parent implementation using super.',
      skeleton: `open class Logger {\n    open fun log(msg: String) = println("[LOG] \$msg")\n}\n\nclass TimestampLogger : Logger() {\n    override fun log(msg: String) {\n        print("[TIME] ")\n        ___.log(msg)\n    }\n}`,
      solution: `open class Logger {\n    open fun log(msg: String) = println("[LOG] \$msg")\n}\n\nclass TimestampLogger : Logger() {\n    override fun log(msg: String) {\n        print("[TIME] ")\n        super.log(msg)\n    }\n}`,
      hints: ['Use super to call the parent method.', 'super.log(msg) calls the parent version.', 'super'],
      concepts: ['super'],
    },
    {
      id: 'kt-inherit-4',
      title: 'Predict Polymorphic Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of polymorphic method calls.',
      skeleton: `open class Shape {\n    open fun name() = "Shape"\n}\nclass Circle : Shape() {\n    override fun name() = "Circle"\n}\nclass Square : Shape() {\n    override fun name() = "Square"\n}\n\nfun main() {\n    val shapes: List<Shape> = listOf(Circle(), Square(), Shape())\n    for (s in shapes) println(s.name())\n}`,
      solution: `Circle\nSquare\nShape`,
      hints: ['Polymorphism calls the overridden method.', 'Each subclass returns its own name.', 'Circle, Square, Shape'],
      concepts: ['polymorphism'],
    },
    {
      id: 'kt-inherit-5',
      title: 'Fix Missing Open Modifier',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code so the class can be inherited from.',
      skeleton: `class Base {\n    fun greet() = "Hello"\n}\n\nclass Child : Base() {\n    override fun greet() = "Hi"\n}`,
      solution: `open class Base {\n    open fun greet() = "Hello"\n}\n\nclass Child : Base() {\n    override fun greet() = "Hi"\n}`,
      hints: ['Classes and methods are final by default.', 'Add open to both the class and the method.', 'open class Base { open fun greet() }'],
      concepts: ['open'],
    },
    {
      id: 'kt-inherit-6',
      title: 'Write an Inheritance Hierarchy',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write open class Employee(val name: String, val salary: Double) with an open method bonus(): Double returning salary * 0.1. Then write class Manager that overrides bonus to return salary * 0.2.',
      skeleton: `// Define Employee and Manager`,
      solution: `open class Employee(val name: String, val salary: Double) {\n    open fun bonus(): Double = salary * 0.1\n}\n\nclass Manager(name: String, salary: Double) : Employee(name, salary) {\n    override fun bonus(): Double = salary * 0.2\n}`,
      hints: ['Employee must be open, as must bonus().', 'Manager extends Employee.', 'override fun bonus() = salary * 0.2'],
      concepts: ['open', 'override'],
    },
    {
      id: 'kt-inherit-7',
      title: 'Abstract Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare an abstract class with an abstract method.',
      skeleton: `___ class Shape {\n    ___ fun area(): Double\n}\n\nclass Rect(val w: Double, val h: Double) : Shape() {\n    override fun area() = w * h\n}`,
      solution: `abstract class Shape {\n    abstract fun area(): Double\n}\n\nclass Rect(val w: Double, val h: Double) : Shape() {\n    override fun area() = w * h\n}`,
      hints: ['Abstract classes cannot be instantiated.', 'abstract class, abstract fun', 'Abstract methods have no body.'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-inherit-8',
      title: 'Write an Abstract Class Hierarchy',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Converter with abstract fun convert(value: Double): Double. Implement CelsiusToFahrenheit and FahrenheitToCelsius.',
      skeleton: `// Define abstract Converter and two implementations`,
      solution: `abstract class Converter {\n    abstract fun convert(value: Double): Double\n}\n\nclass CelsiusToFahrenheit : Converter() {\n    override fun convert(value: Double): Double = value * 9.0 / 5.0 + 32.0\n}\n\nclass FahrenheitToCelsius : Converter() {\n    override fun convert(value: Double): Double = (value - 32.0) * 5.0 / 9.0\n}`,
      hints: ['Abstract class defines the contract.', 'Each subclass implements the conversion formula.', 'C to F: value * 9/5 + 32'],
      concepts: ['abstract', 'override'],
    },
    {
      id: 'kt-inherit-9',
      title: 'Predict Super Call Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when super is called.',
      skeleton: `open class A {\n    open fun greet() = "Hello from A"\n}\n\nclass B : A() {\n    override fun greet() = super.greet() + " and B"\n}\n\nfun main() {\n    println(B().greet())\n}`,
      solution: `Hello from A and B`,
      hints: ['super.greet() calls parent A.', 'B appends " and B".', 'Hello from A and B'],
      concepts: ['super'],
    },
    {
      id: 'kt-inherit-10',
      title: 'Fix Override Without Super Constructor',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the subclass to properly call the parent constructor.',
      skeleton: `open class Person(val name: String)\n\nclass Student(name: String, val grade: Int) : Person {\n    override fun toString() = "\$name (grade \$grade)"\n}`,
      solution: `open class Person(val name: String)\n\nclass Student(name: String, val grade: Int) : Person(name) {\n    override fun toString() = "\$name (grade \$grade)"\n}`,
      hints: ['Must call the parent constructor.', 'Pass name to Person().', ': Person(name)'],
      concepts: ['primary-constructor', 'inheritance'],
    },
    {
      id: 'kt-inherit-11',
      title: 'Write a Template Method Pattern',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Report with abstract fun gatherData(): String, abstract fun formatData(data: String): String, and a concrete fun generate(): String that calls both.',
      skeleton: `// Define abstract Report with template method`,
      solution: `abstract class Report {\n    abstract fun gatherData(): String\n    abstract fun formatData(data: String): String\n\n    fun generate(): String {\n        val data = gatherData()\n        return formatData(data)\n    }\n}`,
      hints: ['Template method calls abstract methods.', 'generate() is concrete but calls abstract methods.', 'Subclasses provide gatherData and formatData.'],
      concepts: ['abstract', 'template-pattern'],
    },
    {
      id: 'kt-inherit-12',
      title: 'Protected Member Access',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use protected to limit access to subclasses only.',
      skeleton: `open class Base {\n    ___ open fun secret() = "base secret"\n}\n\nclass Derived : Base() {\n    fun reveal() = secret()\n}`,
      solution: `open class Base {\n    protected open fun secret() = "base secret"\n}\n\nclass Derived : Base() {\n    fun reveal() = secret()\n}`,
      hints: ['protected members are accessible in subclasses.', 'Not accessible from outside the class hierarchy.', 'protected'],
      concepts: ['protected'],
    },
    {
      id: 'kt-inherit-13',
      title: 'Write Overriding Properties',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an open class with an open val property, and a subclass that overrides it.',
      skeleton: `// Base with open val, subclass that overrides it`,
      solution: `open class Notification(val message: String) {\n    open val priority: String = "normal"\n}\n\nclass UrgentNotification(message: String) : Notification(message) {\n    override val priority: String = "high"\n}`,
      hints: ['Properties can be open and overridden too.', 'Use override val in the subclass.', 'open val priority in base, override val priority in derived.'],
      concepts: ['open', 'override'],
    },
    {
      id: 'kt-inherit-14',
      title: 'Predict Init Order',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the initialization order in an inheritance chain.',
      skeleton: `open class Parent {\n    init { println("Parent init") }\n}\n\nclass Child : Parent() {\n    init { println("Child init") }\n}\n\nfun main() {\n    Child()\n}`,
      solution: `Parent init\nChild init`,
      hints: ['Parent is initialized before child.', 'init blocks run in inheritance order.', 'Parent init then Child init.'],
      concepts: ['init-block', 'inheritance'],
    },
    {
      id: 'kt-inherit-15',
      title: 'Fix Missing Override',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the compilation error by adding the missing override keyword.',
      skeleton: `abstract class Animal {\n    abstract fun sound(): String\n}\n\nclass Dog : Animal() {\n    fun sound(): String = "Woof"\n}`,
      solution: `abstract class Animal {\n    abstract fun sound(): String\n}\n\nclass Dog : Animal() {\n    override fun sound(): String = "Woof"\n}`,
      hints: ['Abstract methods must be explicitly overridden.', 'Add the override keyword.', 'override fun sound()'],
      concepts: ['override', 'abstract'],
    },
    {
      id: 'kt-inherit-16',
      title: 'Write a Chain of Overrides',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write three classes: open class A with open fun value() = 1, open class B : A() with override returning super + 10, class C : B() with override returning super + 100.',
      skeleton: `// Define A, B, C chain`,
      solution: `open class A {\n    open fun value(): Int = 1\n}\n\nopen class B : A() {\n    override fun value(): Int = super.value() + 10\n}\n\nclass C : B() {\n    override fun value(): Int = super.value() + 100\n}`,
      hints: ['B must be open too since C extends it.', 'Use super.value() to chain calls.', 'C().value() should be 111.'],
      concepts: ['open', 'override', 'super'],
    },
    {
      id: 'kt-inherit-17',
      title: 'Refactor to Inheritance',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor duplicate code into a base class.',
      skeleton: `class Dog(val name: String) {\n    fun speak() = "\$name says Woof!"\n    fun describe() = "Animal: \$name"\n}\n\nclass Cat(val name: String) {\n    fun speak() = "\$name says Meow!"\n    fun describe() = "Animal: \$name"\n}`,
      solution: `open class Animal(val name: String) {\n    open fun speak() = "\$name says ..."\n    fun describe() = "Animal: \$name"\n}\n\nclass Dog(name: String) : Animal(name) {\n    override fun speak() = "\$name says Woof!"\n}\n\nclass Cat(name: String) : Animal(name) {\n    override fun speak() = "\$name says Meow!"\n}`,
      hints: ['Extract common code into a base class.', 'describe() is the same - keep it in the base.', 'speak() differs - make it open and override.'],
      concepts: ['open', 'override', 'inheritance'],
    },
    {
      id: 'kt-inherit-18',
      title: 'Refactor to Abstract Base',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor to use an abstract base class with an abstract method.',
      skeleton: `class JsonExporter {\n    fun export(data: String): String = """{"data": "\$data"}"""\n}\n\nclass CsvExporter {\n    fun export(data: String): String = "data\\n\$data"\n}`,
      solution: `abstract class Exporter {\n    abstract fun export(data: String): String\n}\n\nclass JsonExporter : Exporter() {\n    override fun export(data: String): String = \"\"\"{\"data\": \"\$data\"}\"\"\"\n}\n\nclass CsvExporter : Exporter() {\n    override fun export(data: String): String = \"data\\n\$data\"\n}`,
      hints: ['Create an abstract base with abstract export method.', 'Each subclass overrides with its format.', 'abstract class Exporter'],
      concepts: ['abstract', 'override'],
    },
    {
      id: 'kt-inherit-19',
      title: 'Write a Final Override',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class hierarchy where the middle class marks its override as final to prevent further overriding.',
      skeleton: `// A -> B (final override) -> C cannot override`,
      solution: `open class A {\n    open fun action(): String = "A"\n}\n\nopen class B : A() {\n    final override fun action(): String = "B"\n}\n\nclass C : B() {\n    // Cannot override action() - it is final in B\n}`,
      hints: ['Use final override to prevent further overriding.', 'final override fun action()', 'C cannot override action.'],
      concepts: ['final', 'override'],
    },
    {
      id: 'kt-inherit-20',
      title: 'Write Constructor Delegation',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write open class Shape(val color: String) and class ColoredCircle(val radius: Double, color: String) that extends Shape.',
      skeleton: `// Define Shape and ColoredCircle`,
      solution: `open class Shape(val color: String)\n\nclass ColoredCircle(val radius: Double, color: String) : Shape(color) {\n    fun area(): Double = 3.14159 * radius * radius\n    override fun toString() = "ColoredCircle(radius=\$radius, color=\$color)"\n}`,
      hints: ['Pass color to the Shape constructor.', 'ColoredCircle adds its own radius property.', ': Shape(color) delegates to parent.'],
      concepts: ['primary-constructor', 'inheritance'],
    },
  ],
};
