import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-iface',
  title: '10. Interfaces',
  explanation: `## Interfaces in Kotlin\n\nInterfaces define a contract that classes can implement:\n\n\`\`\`kotlin\ninterface Clickable {\n    fun click()              // abstract - must be implemented\n    fun description() = "Clickable element"  // default implementation\n}\n\nclass Button : Clickable {\n    override fun click() = println("Button clicked")\n}\n\`\`\`\n\n**Key features:**\n- Can have abstract and default method implementations\n- Can declare properties (but no backing fields)\n- A class can implement multiple interfaces\n- No constructor - interfaces cannot hold state\n\n\`\`\`kotlin\ninterface Named {\n    val name: String  // abstract property\n}\n\ninterface Greeter {\n    fun greet(): String\n}\n\nclass Person(override val name: String) : Named, Greeter {\n    override fun greet() = "Hello, I'm \$name"\n}\n\`\`\`\n\nWhen multiple interfaces have the same method, use \`super<Interface>.method()\` to disambiguate.`,
  exercises: [
    {
      id: 'kt-iface-1',
      title: 'Declare an Interface',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare an interface with an abstract method.',
      skeleton: `___ Printable {\n    fun print()\n}`,
      solution: `interface Printable {\n    fun print()\n}`,
      hints: ['Interfaces are declared with the interface keyword.', 'No body means the method is abstract.', 'interface'],
      concepts: ['interface'],
    },
    {
      id: 'kt-iface-2',
      title: 'Implement an Interface',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Implement the Drawable interface.',
      skeleton: `interface Drawable {\n    fun draw(): String\n}\n\nclass Circle ___ Drawable {\n    ___ fun draw() = "Drawing circle"\n}`,
      solution: `interface Drawable {\n    fun draw(): String\n}\n\nclass Circle : Drawable {\n    override fun draw() = "Drawing circle"\n}`,
      hints: ['Use : to implement an interface.', 'Add override for the method.', ': Drawable { override fun draw() }'],
      concepts: ['interface', 'override'],
    },
    {
      id: 'kt-iface-3',
      title: 'Default Implementation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a default implementation to an interface method.',
      skeleton: `interface Logger {\n    fun log(message: String) ___ println("[LOG] \$message")\n}`,
      solution: `interface Logger {\n    fun log(message: String) = println("[LOG] \$message")\n}`,
      hints: ['Default implementations use = or a body block.', 'Just add the implementation after the signature.', '= println(...)'],
      concepts: ['default-implementation'],
    },
    {
      id: 'kt-iface-4',
      title: 'Predict Multiple Interface Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when implementing multiple interfaces.',
      skeleton: `interface A {\n    fun greet() = "Hello from A"\n}\ninterface B {\n    fun greet() = "Hello from B"\n}\nclass C : A, B {\n    override fun greet() = super<A>.greet() + " & " + super<B>.greet()\n}\n\nfun main() {\n    println(C().greet())\n}`,
      solution: `Hello from A & Hello from B`,
      hints: ['C must override greet since both A and B define it.', 'super<A>.greet() calls A version.', 'Hello from A & Hello from B'],
      concepts: ['interface', 'super'],
    },
    {
      id: 'kt-iface-5',
      title: 'Interface Property',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Implement an interface with an abstract property.',
      skeleton: `interface Named {\n    val name: String\n}\n\nclass User(___ ___ name: String) : Named`,
      solution: `interface Named {\n    val name: String\n}\n\nclass User(override val name: String) : Named`,
      hints: ['Override the abstract property in the constructor.', 'Use override val in the constructor.', 'override val name: String'],
      concepts: ['interface', 'properties'],
    },
    {
      id: 'kt-iface-6',
      title: 'Fix Missing Interface Implementation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the class that does not implement all interface methods.',
      skeleton: `interface Repository {\n    fun save(item: String)\n    fun findAll(): List<String>\n}\n\nclass InMemoryRepo : Repository {\n    private val items = mutableListOf<String>()\n    override fun save(item: String) { items.add(item) }\n}`,
      solution: `interface Repository {\n    fun save(item: String)\n    fun findAll(): List<String>\n}\n\nclass InMemoryRepo : Repository {\n    private val items = mutableListOf<String>()\n    override fun save(item: String) { items.add(item) }\n    override fun findAll(): List<String> = items.toList()\n}`,
      hints: ['All abstract methods must be implemented.', 'findAll() is missing its implementation.', 'Add override fun findAll()'],
      concepts: ['interface'],
    },
    {
      id: 'kt-iface-7',
      title: 'Write an Interface Hierarchy',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write interface Readable with fun read(): String, interface Writable with fun write(data: String), and class File implementing both.',
      skeleton: `// Define Readable, Writable, and File`,
      solution: `interface Readable {\n    fun read(): String\n}\n\ninterface Writable {\n    fun write(data: String)\n}\n\nclass File(var content: String = "") : Readable, Writable {\n    override fun read(): String = content\n    override fun write(data: String) { content = data }\n}`,
      hints: ['A class can implement multiple interfaces.', 'Separate interfaces with commas.', 'class File : Readable, Writable'],
      concepts: ['interface'],
    },
    {
      id: 'kt-iface-8',
      title: 'Write a Comparator Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an interface Sortable<T> with fun compareTo(other: T): Int, and implement it for a Scored class.',
      skeleton: `// Define Sortable interface and Scored class`,
      solution: `interface Sortable<T> {\n    fun compareTo(other: T): Int\n}\n\nclass Scored(val score: Int) : Sortable<Scored> {\n    override fun compareTo(other: Scored): Int = this.score - other.score\n}`,
      hints: ['Generic interface with type parameter T.', 'compareTo returns negative, zero, or positive.', 'this.score - other.score'],
      concepts: ['interface', 'generics'],
    },
    {
      id: 'kt-iface-9',
      title: 'Predict Default Method',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict whether the default implementation is used.',
      skeleton: `interface Greetable {\n    fun greet(name: String) = "Hello, \$name!"\n}\n\nclass Greeter : Greetable\n\nfun main() {\n    println(Greeter().greet("Kotlin"))\n}`,
      solution: `Hello, Kotlin!`,
      hints: ['Greeter does not override greet.', 'The default implementation is used.', 'Hello, Kotlin!'],
      concepts: ['default-implementation'],
    },
    {
      id: 'kt-iface-10',
      title: 'Fix Diamond Problem',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the diamond problem by explicitly calling the desired super method.',
      skeleton: `interface A {\n    fun action() = "A"\n}\ninterface B {\n    fun action() = "B"\n}\nclass C : A, B {\n    // Compilation error: must override action\n}`,
      solution: `interface A {\n    fun action() = "A"\n}\ninterface B {\n    fun action() = "B"\n}\nclass C : A, B {\n    override fun action() = super<A>.action()\n}`,
      hints: ['When two interfaces define the same method, you must override.', 'Use super<InterfaceName> to pick which.', 'override fun action() = super<A>.action()'],
      concepts: ['interface', 'super'],
    },
    {
      id: 'kt-iface-11',
      title: 'Write an Interface with Computed Property',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an interface HasArea with a val area: Double property that has a default getter, implemented by Circle.',
      skeleton: `// Define HasArea with computed property, and Circle`,
      solution: `interface HasArea {\n    val radius: Double\n    val area: Double\n        get() = 3.14159 * radius * radius\n}\n\nclass Circle(override val radius: Double) : HasArea`,
      hints: ['Interfaces can have properties with default getters.', 'The getter cannot access a backing field.', 'Compute from other abstract properties.'],
      concepts: ['interface', 'properties'],
    },
    {
      id: 'kt-iface-12',
      title: 'Predict Interface Property',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of an interface property with default getter.',
      skeleton: `interface Sizable {\n    val size: Int\n    val isEmpty: Boolean\n        get() = size == 0\n}\n\nclass Box(override val size: Int) : Sizable\n\nfun main() {\n    println(Box(0).isEmpty)\n    println(Box(5).isEmpty)\n}`,
      solution: `true\nfalse`,
      hints: ['isEmpty checks if size == 0.', 'Box(0).isEmpty is true.', 'Box(5).isEmpty is false.'],
      concepts: ['interface', 'properties'],
    },
    {
      id: 'kt-iface-13',
      title: 'Write a Functional Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a fun interface Transformer<T> with fun transform(value: T): T, and use it with a lambda.',
      skeleton: `// Define fun interface and use with lambda`,
      solution: `fun interface Transformer<T> {\n    fun transform(value: T): T\n}\n\nfun main() {\n    val doubler = Transformer<Int> { it * 2 }\n    println(doubler.transform(5))\n}`,
      hints: ['fun interface allows SAM conversion from lambdas.', 'Only one abstract method.', 'fun interface Transformer<T>'],
      concepts: ['fun-interface'],
    },
    {
      id: 'kt-iface-14',
      title: 'Write Interface Delegation',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class that delegates interface implementation to another object using by.',
      skeleton: `interface Printer {\n    fun print(text: String)\n}\n\n// ConsolePrinter implements Printer\n// LoggingPrinter delegates to a Printer via by`,
      solution: `interface Printer {\n    fun print(text: String)\n}\n\nclass ConsolePrinter : Printer {\n    override fun print(text: String) = println(text)\n}\n\nclass LoggingPrinter(printer: Printer) : Printer by printer`,
      hints: ['by keyword delegates implementation.', 'class LoggingPrinter(p: Printer) : Printer by p', 'All methods are forwarded to the delegate.'],
      concepts: ['delegation', 'interface'],
    },
    {
      id: 'kt-iface-15',
      title: 'Fix Interface Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the function to accept any Drawable, not just Circle.',
      skeleton: `interface Drawable {\n    fun draw(): String\n}\n\nclass Circle : Drawable {\n    override fun draw() = "Circle"\n}\n\nclass Square : Drawable {\n    override fun draw() = "Square"\n}\n\nfun render(shape: Circle) = println(shape.draw())`,
      solution: `interface Drawable {\n    fun draw(): String\n}\n\nclass Circle : Drawable {\n    override fun draw() = "Circle"\n}\n\nclass Square : Drawable {\n    override fun draw() = "Square"\n}\n\nfun render(shape: Drawable) = println(shape.draw())`,
      hints: ['Use the interface type for polymorphism.', 'Change Circle to Drawable in the parameter.', 'fun render(shape: Drawable)'],
      concepts: ['interface', 'polymorphism'],
    },
    {
      id: 'kt-iface-16',
      title: 'Write a Callback Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a fun interface OnComplete with fun onComplete(result: String), and a function process(callback: OnComplete) that calls it.',
      skeleton: `// Define fun interface and process function`,
      solution: `fun interface OnComplete {\n    fun onComplete(result: String)\n}\n\nfun process(callback: OnComplete) {\n    callback.onComplete("Done")\n}`,
      hints: ['fun interface for SAM conversion.', 'Can be called with a lambda.', 'process { println(it) }'],
      concepts: ['fun-interface'],
    },
    {
      id: 'kt-iface-17',
      title: 'Refactor to Interface',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the concrete dependency to depend on an interface instead.',
      skeleton: `class EmailSender {\n    fun send(to: String, body: String) = println("Email to \$to: \$body")\n}\n\nclass OrderService(val sender: EmailSender) {\n    fun placeOrder(email: String) {\n        sender.send(email, "Order placed!")\n    }\n}`,
      solution: `interface MessageSender {\n    fun send(to: String, body: String)\n}\n\nclass EmailSender : MessageSender {\n    override fun send(to: String, body: String) = println("Email to \$to: \$body")\n}\n\nclass OrderService(val sender: MessageSender) {\n    fun placeOrder(email: String) {\n        sender.send(email, "Order placed!")\n    }\n}`,
      hints: ['Extract an interface from EmailSender.', 'OrderService depends on the interface.', 'This enables swapping implementations.'],
      concepts: ['interface', 'dependency-inversion'],
    },
    {
      id: 'kt-iface-18',
      title: 'Refactor Multiple Inheritance to Interfaces',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor: Kotlin does not support multiple class inheritance. Use interfaces.',
      skeleton: `// This won't compile - can't extend two classes\n// open class Swimmer { open fun swim() = "swimming" }\n// open class Flyer { open fun fly() = "flying" }\n// class Duck : Swimmer(), Flyer()\n\n// Refactor to compile`,
      solution: `interface Swimmer {\n    fun swim() = "swimming"\n}\n\ninterface Flyer {\n    fun fly() = "flying"\n}\n\nclass Duck : Swimmer, Flyer`,
      hints: ['Convert classes to interfaces.', 'Interfaces support multiple inheritance.', 'class Duck : Swimmer, Flyer'],
      concepts: ['interface'],
    },
    {
      id: 'kt-iface-19',
      title: 'Write an Interface Extending Another',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write interface Closeable with fun close(), and interface Resource : Closeable with fun read(): String. Implement with FileResource.',
      skeleton: `// Define interface hierarchy and implementation`,
      solution: `interface Closeable {\n    fun close()\n}\n\ninterface Resource : Closeable {\n    fun read(): String\n}\n\nclass FileResource(private var data: String) : Resource {\n    private var open = true\n    override fun read(): String = if (open) data else "closed"\n    override fun close() { open = false }\n}`,
      hints: ['Interfaces can extend other interfaces.', 'interface Resource : Closeable', 'FileResource must implement both methods.'],
      concepts: ['interface'],
    },
    {
      id: 'kt-iface-20',
      title: 'Predict SAM Conversion',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of a SAM conversion with fun interface.',
      skeleton: `fun interface StringMapper {\n    fun map(input: String): String\n}\n\nfun applyMapper(input: String, mapper: StringMapper): String = mapper.map(input)\n\nfun main() {\n    val result = applyMapper("hello") { it.uppercase() }\n    println(result)\n}`,
      solution: `HELLO`,
      hints: ['The lambda is converted to a StringMapper.', 'it.uppercase() converts "hello" to "HELLO".', 'HELLO'],
      concepts: ['fun-interface'],
    },
  ],
};
