import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-abstract',
  title: '11. Abstract Classes',
  explanation: `## Abstract Classes in Kotlin\n\nAbstract classes cannot be instantiated and may contain both abstract and concrete members:\n\n\`\`\`kotlin\nabstract class Shape(val color: String) {\n    abstract fun area(): Double         // must be overridden\n    fun describe() = "A \$color shape"   // concrete - inherited as-is\n}\n\`\`\`\n\n**Abstract vs Interface:**\n- Abstract classes can have constructors, state (properties with backing fields)\n- Interfaces cannot have constructors or mutable state\n- A class can extend only ONE abstract class but implement MANY interfaces\n\n**Template Method Pattern** - define an algorithm skeleton in the abstract class, let subclasses fill in steps:\n\n\`\`\`kotlin\nabstract class DataProcessor {\n    fun process(data: String): String {\n        val cleaned = clean(data)\n        val result = transform(cleaned)\n        return format(result)\n    }\n    abstract fun clean(data: String): String\n    abstract fun transform(data: String): String\n    open fun format(data: String) = data  // optional override\n}\n\`\`\``,
  exercises: [
    {
      id: 'kt-abstract-1',
      title: 'Declare an Abstract Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare an abstract class with an abstract method.',
      skeleton: `___ class Animal {\n    ___ fun sound(): String\n}`,
      solution: `abstract class Animal {\n    abstract fun sound(): String\n}`,
      hints: ['Use abstract keyword for both class and method.', 'Abstract methods have no body.', 'abstract class, abstract fun'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-abstract-2',
      title: 'Implement Abstract Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Implement the abstract method in a subclass.',
      skeleton: `abstract class Shape {\n    abstract fun area(): Double\n}\n\nclass Square(val side: Double) : Shape() {\n    ___ fun area(): Double = side * side\n}`,
      solution: `abstract class Shape {\n    abstract fun area(): Double\n}\n\nclass Square(val side: Double) : Shape() {\n    override fun area(): Double = side * side\n}`,
      hints: ['Abstract methods must be overridden.', 'Use the override keyword.', 'override fun area()'],
      concepts: ['abstract', 'override'],
    },
    {
      id: 'kt-abstract-3',
      title: 'Abstract with Concrete Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Mix abstract and concrete methods in an abstract class.',
      skeleton: `abstract class Formatter {\n    ___ fun format(data: String): String\n    fun wrap(data: String) = "[\${format(data)}]"\n}`,
      solution: `abstract class Formatter {\n    abstract fun format(data: String): String\n    fun wrap(data: String) = "[\${format(data)}]"\n}`,
      hints: ['Only the unimplemented method needs abstract.', 'wrap() has a body so it is concrete.', 'abstract fun format(...)'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-abstract-4',
      title: 'Predict Abstract Class Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of calling concrete and overridden methods.',
      skeleton: `abstract class Greeter {\n    abstract fun greeting(): String\n    fun greet(name: String) = "\${greeting()}, \$name!"\n}\n\nclass FormalGreeter : Greeter() {\n    override fun greeting() = "Good day"\n}\n\nfun main() {\n    println(FormalGreeter().greet("Alice"))\n}`,
      solution: `Good day, Alice!`,
      hints: ['greeting() returns "Good day".', 'greet combines greeting + name.', 'Good day, Alice!'],
      concepts: ['abstract', 'template-pattern'],
    },
    {
      id: 'kt-abstract-5',
      title: 'Fix Cannot Instantiate Abstract Class',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that tries to instantiate an abstract class.',
      skeleton: `abstract class Vehicle {\n    abstract fun fuelType(): String\n}\n\nfun main() {\n    val v = Vehicle()\n    println(v.fuelType())\n}`,
      solution: `abstract class Vehicle {\n    abstract fun fuelType(): String\n}\n\nclass Car : Vehicle() {\n    override fun fuelType() = "Gasoline"\n}\n\nfun main() {\n    val v = Car()\n    println(v.fuelType())\n}`,
      hints: ['Abstract classes cannot be instantiated directly.', 'Create a concrete subclass.', 'class Car : Vehicle() { override fun fuelType() = "Gasoline" }'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-abstract-6',
      title: 'Write an Abstract Property',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an abstract class with an abstract property and implement it.',
      skeleton: `// Define abstract class with abstract val, and an implementation`,
      solution: `abstract class Document {\n    abstract val title: String\n    fun header() = "=== \$title ==="\n}\n\nclass Report(override val title: String) : Document()`,
      hints: ['Abstract properties use abstract val.', 'Override in the constructor with override val.', 'abstract val title: String'],
      concepts: ['abstract', 'properties'],
    },
    {
      id: 'kt-abstract-7',
      title: 'Write Template Method Pattern',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an abstract class Pipeline with abstract methods extract() and transform(), and a concrete run() that calls both.',
      skeleton: `// Define abstract Pipeline with template method`,
      solution: `abstract class Pipeline {\n    abstract fun extract(): String\n    abstract fun transform(data: String): String\n\n    fun run(): String {\n        val data = extract()\n        return transform(data)\n    }\n}`,
      hints: ['Template method defines the algorithm structure.', 'run() calls abstract methods in sequence.', 'Subclasses provide extract() and transform().'],
      concepts: ['template-pattern', 'abstract'],
    },
    {
      id: 'kt-abstract-8',
      title: 'Predict Abstract Hierarchy',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of a multi-level abstract hierarchy.',
      skeleton: `abstract class Base {\n    abstract fun value(): Int\n    fun doubled() = value() * 2\n}\n\nabstract class Middle : Base() {\n    override fun value() = 5\n}\n\nclass Final : Middle()\n\nfun main() {\n    println(Final().doubled())\n}`,
      solution: `10`,
      hints: ['Final extends Middle which provides value() = 5.', 'doubled() calls value() * 2 = 10.', '10'],
      concepts: ['abstract', 'inheritance'],
    },
    {
      id: 'kt-abstract-9',
      title: 'Fix Missing Abstract Override',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the concrete class that does not implement all abstract methods.',
      skeleton: `abstract class Calculator {\n    abstract fun add(a: Int, b: Int): Int\n    abstract fun subtract(a: Int, b: Int): Int\n}\n\nclass SimpleCalc : Calculator() {\n    override fun add(a: Int, b: Int) = a + b\n}`,
      solution: `abstract class Calculator {\n    abstract fun add(a: Int, b: Int): Int\n    abstract fun subtract(a: Int, b: Int): Int\n}\n\nclass SimpleCalc : Calculator() {\n    override fun add(a: Int, b: Int) = a + b\n    override fun subtract(a: Int, b: Int) = a - b\n}`,
      hints: ['All abstract methods must be implemented.', 'subtract is not overridden.', 'Add override fun subtract(a, b) = a - b'],
      concepts: ['abstract', 'override'],
    },
    {
      id: 'kt-abstract-10',
      title: 'Write an Abstract State Machine',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class State with abstract val name: String and abstract fun next(): State. Implement GreenState and RedState that cycle.',
      skeleton: `// Define abstract State and two implementations`,
      solution: `abstract class State {\n    abstract val name: String\n    abstract fun next(): State\n}\n\nclass GreenState : State() {\n    override val name = "Green"\n    override fun next(): State = RedState()\n}\n\nclass RedState : State() {\n    override val name = "Red"\n    override fun next(): State = GreenState()\n}`,
      hints: ['Each state returns the other from next().', 'GreenState.next() returns RedState.', 'Abstract class defines the state interface.'],
      concepts: ['abstract', 'state-pattern'],
    },
    {
      id: 'kt-abstract-11',
      title: 'Write Abstract with Constructor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Notification(val message: String) with abstract fun channel(): String and concrete fun send() that prints "[channel] message".',
      skeleton: `// Define abstract Notification with constructor`,
      solution: `abstract class Notification(val message: String) {\n    abstract fun channel(): String\n    fun send() = println("[\${channel()}] \$message")\n}\n\nclass EmailNotification(message: String) : Notification(message) {\n    override fun channel() = "Email"\n}\n\nclass SmsNotification(message: String) : Notification(message) {\n    override fun channel() = "SMS"\n}`,
      hints: ['Abstract classes can have constructors.', 'Subclasses pass message to parent constructor.', 'abstract class Notification(val message: String)'],
      concepts: ['abstract', 'primary-constructor'],
    },
    {
      id: 'kt-abstract-12',
      title: 'Predict Template Method Order',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the execution order in a template method.',
      skeleton: `abstract class Builder {\n    fun build(): String {\n        val a = step1()\n        val b = step2()\n        return "\$a-\$b"\n    }\n    abstract fun step1(): String\n    abstract fun step2(): String\n}\n\nclass MyBuilder : Builder() {\n    override fun step1() = "A"\n    override fun step2() = "B"\n}\n\nfun main() {\n    println(MyBuilder().build())\n}`,
      solution: `A-B`,
      hints: ['build() calls step1() then step2().', 'step1 returns "A", step2 returns "B".', 'A-B'],
      concepts: ['template-pattern'],
    },
    {
      id: 'kt-abstract-13',
      title: 'Write an Abstract Iterator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Counter with abstract fun hasNext(): Boolean and abstract fun nextValue(): Int, plus a concrete fun sumAll(): Int.',
      skeleton: `// Define abstract Counter with sumAll template method`,
      solution: `abstract class Counter {\n    abstract fun hasNext(): Boolean\n    abstract fun nextValue(): Int\n\n    fun sumAll(): Int {\n        var sum = 0\n        while (hasNext()) {\n            sum += nextValue()\n        }\n        return sum\n    }\n}`,
      hints: ['sumAll uses hasNext and nextValue in a loop.', 'Template method pattern.', 'while (hasNext()) sum += nextValue()'],
      concepts: ['abstract', 'template-pattern'],
    },
    {
      id: 'kt-abstract-14',
      title: 'Fix Abstract in Wrong Position',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the abstract class that incorrectly tries to be data class.',
      skeleton: `abstract data class Entity(val id: Int) {\n    abstract fun type(): String\n}`,
      solution: `abstract class Entity(val id: Int) {\n    abstract fun type(): String\n}`,
      hints: ['data classes cannot be abstract.', 'Remove the data modifier.', 'abstract class Entity(val id: Int)'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-abstract-15',
      title: 'Write an Abstract Validator',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Validator<T> with abstract fun isValid(value: T): Boolean and concrete fun validate(value: T): String.',
      skeleton: `// Define generic abstract Validator`,
      solution: `abstract class Validator<T> {\n    abstract fun isValid(value: T): Boolean\n\n    fun validate(value: T): String {\n        return if (isValid(value)) "Valid" else "Invalid"\n    }\n}`,
      hints: ['Generic abstract class with type parameter T.', 'validate uses isValid to produce a result.', 'abstract fun isValid(value: T): Boolean'],
      concepts: ['abstract', 'generics'],
    },
    {
      id: 'kt-abstract-16',
      title: 'Write Abstract with Protected',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write abstract class Logger with protected abstract fun formatMessage(msg: String): String and public fun log(msg: String).',
      skeleton: `// Define abstract Logger with protected abstract method`,
      solution: `abstract class Logger {\n    protected abstract fun formatMessage(msg: String): String\n\n    fun log(msg: String) {\n        println(formatMessage(msg))\n    }\n}`,
      hints: ['protected abstract is accessible only in subclasses.', 'log() is public and calls the protected method.', 'protected abstract fun formatMessage(msg: String): String'],
      concepts: ['abstract', 'protected'],
    },
    {
      id: 'kt-abstract-17',
      title: 'Refactor to Abstract Base',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Extract common logic into an abstract base class.',
      skeleton: `class JsonParser {\n    fun parse(input: String): Map<String, String> {\n        val cleaned = input.trim()\n        return parseJson(cleaned)\n    }\n    private fun parseJson(s: String): Map<String, String> = mapOf("json" to s)\n}\n\nclass XmlParser {\n    fun parse(input: String): Map<String, String> {\n        val cleaned = input.trim()\n        return parseXml(cleaned)\n    }\n    private fun parseXml(s: String): Map<String, String> = mapOf("xml" to s)\n}`,
      solution: `abstract class Parser {\n    fun parse(input: String): Map<String, String> {\n        val cleaned = input.trim()\n        return doParse(cleaned)\n    }\n    protected abstract fun doParse(s: String): Map<String, String>\n}\n\nclass JsonParser : Parser() {\n    override fun doParse(s: String) = mapOf("json" to s)\n}\n\nclass XmlParser : Parser() {\n    override fun doParse(s: String) = mapOf("xml" to s)\n}`,
      hints: ['Both classes have the same parse structure.', 'Extract trim + delegate pattern to abstract base.', 'The parsing step differs, so make it abstract.'],
      concepts: ['abstract', 'template-pattern'],
    },
    {
      id: 'kt-abstract-18',
      title: 'Refactor Concrete to Abstract',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor a concrete class with TODO methods to an abstract class.',
      skeleton: `class Serializer {\n    fun serialize(data: Any): String {\n        TODO("Not implemented")\n    }\n    fun deserialize(input: String): Any {\n        TODO("Not implemented")\n    }\n}`,
      solution: `abstract class Serializer {\n    abstract fun serialize(data: Any): String\n    abstract fun deserialize(input: String): Any\n}`,
      hints: ['TODO methods should be abstract instead.', 'Make the class abstract.', 'Replace TODO bodies with abstract keyword.'],
      concepts: ['abstract'],
    },
    {
      id: 'kt-abstract-19',
      title: 'Write Abstract with Init Block',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an abstract class Connection(val url: String) with an init block that validates url is not blank, and abstract fun connect(): Boolean.',
      skeleton: `// Define abstract Connection with validation`,
      solution: `abstract class Connection(val url: String) {\n    init {\n        require(url.isNotBlank()) { "URL must not be blank" }\n    }\n\n    abstract fun connect(): Boolean\n}`,
      hints: ['Abstract classes can have init blocks.', 'Init blocks validate constructor parameters.', 'require(url.isNotBlank())'],
      concepts: ['abstract', 'init-block'],
    },
    {
      id: 'kt-abstract-20',
      title: 'Predict Abstract Chain',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of chained abstract method calls.',
      skeleton: `abstract class Transformer {\n    abstract fun transform(s: String): String\n    fun process(s: String): String {\n        val t1 = transform(s)\n        val t2 = transform(t1)\n        return t2\n    }\n}\n\nclass Uppercaser : Transformer() {\n    override fun transform(s: String) = s.uppercase()\n}\n\nfun main() {\n    println(Uppercaser().process("hello"))\n}`,
      solution: `HELLO`,
      hints: ['First transform: "hello" -> "HELLO".', 'Second transform: "HELLO" -> "HELLO" (already uppercase).', 'HELLO'],
      concepts: ['abstract', 'template-pattern'],
    },
  ],
};
