import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-enum',
  title: '12. Enums',
  explanation: `## Enum Classes in Kotlin\n\nEnum classes define a fixed set of constants:\n\n\`\`\`kotlin\nenum class Direction {\n    NORTH, SOUTH, EAST, WEST\n}\n\`\`\`\n\n**Enums with properties:**\n\n\`\`\`kotlin\nenum class Color(val hex: String) {\n    RED("#FF0000"),\n    GREEN("#00FF00"),\n    BLUE("#0000FF")\n}\n\`\`\`\n\n**Enums with abstract methods:**\n\n\`\`\`kotlin\nenum class Operation {\n    ADD {\n        override fun apply(a: Int, b: Int) = a + b\n    },\n    SUB {\n        override fun apply(a: Int, b: Int) = a - b\n    };\n    abstract fun apply(a: Int, b: Int): Int\n}\n\`\`\`\n\n**Useful methods:**\n- \`valueOf("NORTH")\` — get enum by name\n- \`entries\` — list of all enum values\n- \`.name\` / \`.ordinal\` — name string and index`,
  exercises: [
    {
      id: 'kt-enum-1',
      title: 'Declare a Simple Enum',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare an enum class for seasons.',
      skeleton: `___ ___ Season {\n    SPRING, SUMMER, AUTUMN, WINTER\n}`,
      solution: `enum class Season {\n    SPRING, SUMMER, AUTUMN, WINTER\n}`,
      hints: ['Enum classes use enum class.', 'Constants are listed separated by commas.', 'enum class'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-2',
      title: 'Enum with Property',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a property to enum constants.',
      skeleton: `enum class Planet(val mass: Double) {\n    EARTH(___),\n    MARS(___)\n}`,
      solution: `enum class Planet(val mass: Double) {\n    EARTH(5.972e24),\n    MARS(6.39e23)\n}`,
      hints: ['Each constant passes a value to the constructor.', 'Earth mass is ~5.972e24 kg.', '5.972e24 and 6.39e23'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-3',
      title: 'Predict Enum Name and Ordinal',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the name and ordinal of an enum constant.',
      skeleton: `enum class Color { RED, GREEN, BLUE }\n\nfun main() {\n    val c = Color.GREEN\n    println(c.name)\n    println(c.ordinal)\n}`,
      solution: `GREEN\n1`,
      hints: ['name returns the constant name as a String.', 'ordinal is the zero-based index.', 'GREEN is at index 1.'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-4',
      title: 'Enum valueOf',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Get an enum constant by its name string.',
      skeleton: `enum class Size { S, M, L, XL }\n\nfun main() {\n    val size = Size.___(\"M\")\n    println(size)\n}`,
      solution: `enum class Size { S, M, L, XL }\n\nfun main() {\n    val size = Size.valueOf(\"M\")\n    println(size)\n}`,
      hints: ['valueOf converts a string to an enum constant.', 'Size.valueOf("M") returns Size.M.', 'valueOf("M")'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-5',
      title: 'Enum Entries',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Iterate over all enum values.',
      skeleton: `enum class Day { MON, TUE, WED, THU, FRI, SAT, SUN }\n\nfun main() {\n    for (day in Day.___) {\n        println(day)\n    }\n}`,
      solution: `enum class Day { MON, TUE, WED, THU, FRI, SAT, SUN }\n\nfun main() {\n    for (day in Day.entries) {\n        println(day)\n    }\n}`,
      hints: ['entries returns all enum constants.', 'Day.entries is a List<Day>.', 'entries'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-6',
      title: 'Enum in When Expression',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function describe(season: Season): String using when that returns a description for each season.',
      skeleton: `enum class Season { SPRING, SUMMER, AUTUMN, WINTER }\n\nfun describe(season: Season): String {\n    // use when\n}`,
      solution: `enum class Season { SPRING, SUMMER, AUTUMN, WINTER }\n\nfun describe(season: Season): String {\n    return when (season) {\n        Season.SPRING -> "Flowers bloom"\n        Season.SUMMER -> "Sun shines"\n        Season.AUTUMN -> "Leaves fall"\n        Season.WINTER -> "Snow falls"\n    }\n}`,
      hints: ['when on enum is exhaustive — no else needed if all covered.', 'Match each Season constant.', 'Season.SPRING -> "Flowers bloom"'],
      concepts: ['enum-class', 'when-expression'],
    },
    {
      id: 'kt-enum-7',
      title: 'Fix Enum Missing Semicolon',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the enum class that has methods but is missing the semicolon after constants.',
      skeleton: `enum class Level(val severity: Int) {\n    LOW(1),\n    MEDIUM(5),\n    HIGH(10)\n\n    fun isUrgent() = severity >= 5\n}`,
      solution: `enum class Level(val severity: Int) {\n    LOW(1),\n    MEDIUM(5),\n    HIGH(10);\n\n    fun isUrgent() = severity >= 5\n}`,
      hints: ['When an enum has members after constants, you need a semicolon.', 'Add ; after the last constant.', 'HIGH(10);'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-8',
      title: 'Write an Enum with Abstract Method',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write enum class Operation with ADD and MULTIPLY, each implementing abstract fun apply(a: Int, b: Int): Int.',
      skeleton: `// Define enum with abstract method`,
      solution: `enum class Operation {\n    ADD {\n        override fun apply(a: Int, b: Int) = a + b\n    },\n    MULTIPLY {\n        override fun apply(a: Int, b: Int) = a * b\n    };\n\n    abstract fun apply(a: Int, b: Int): Int\n}`,
      hints: ['Each constant provides its own implementation.', 'Constants are like anonymous subclasses.', 'Semicolon after last constant before abstract fun.'],
      concepts: ['enum-class', 'abstract'],
    },
    {
      id: 'kt-enum-9',
      title: 'Predict Enum When',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of enum in a when expression.',
      skeleton: `enum class Light { RED, YELLOW, GREEN }\n\nfun action(light: Light) = when (light) {\n    Light.RED -> "Stop"\n    Light.YELLOW -> "Caution"\n    Light.GREEN -> "Go"\n}\n\nfun main() {\n    println(action(Light.YELLOW))\n}`,
      solution: `Caution`,
      hints: ['YELLOW matches the second branch.', 'Returns "Caution".', 'Caution'],
      concepts: ['enum-class', 'when-expression'],
    },
    {
      id: 'kt-enum-10',
      title: 'Fix Enum valueOf Error',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code to handle invalid enum names gracefully.',
      skeleton: `enum class Status { ACTIVE, INACTIVE }\n\nfun getStatus(name: String): Status {\n    return Status.valueOf(name)\n}`,
      solution: `enum class Status { ACTIVE, INACTIVE }\n\nfun getStatus(name: String): Status? {\n    return try {\n        Status.valueOf(name)\n    } catch (e: IllegalArgumentException) {\n        null\n    }\n}`,
      hints: ['valueOf throws if the name is invalid.', 'Wrap in try-catch or use entries.find.', 'Return nullable type.'],
      concepts: ['enum-class', 'exceptions'],
    },
    {
      id: 'kt-enum-11',
      title: 'Write an Enum with Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an enum class that implements an interface.',
      skeleton: `// Define Printable interface and enum implementing it`,
      solution: `interface Printable {\n    fun printValue(): String\n}\n\nenum class Currency(val symbol: String) : Printable {\n    USD("\$"),\n    EUR("E"),\n    GBP("P");\n\n    override fun printValue() = "\$name (\$symbol)"\n}`,
      hints: ['Enum classes can implement interfaces.', 'Add : Interface after the constructor.', 'Override the interface method in the enum body.'],
      concepts: ['enum-class', 'interface'],
    },
    {
      id: 'kt-enum-12',
      title: 'Write Enum Companion Method',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an enum with a companion object method that finds a constant by a custom property.',
      skeleton: `// Enum with companion object factory method`,
      solution: `enum class HttpStatus(val code: Int) {\n    OK(200),\n    NOT_FOUND(404),\n    ERROR(500);\n\n    companion object {\n        fun fromCode(code: Int): HttpStatus? =\n            entries.find { it.code == code }\n    }\n}`,
      hints: ['Use a companion object for static-like methods.', 'entries.find searches by predicate.', 'companion object { fun fromCode(...) }'],
      concepts: ['enum-class', 'companion-object'],
    },
    {
      id: 'kt-enum-13',
      title: 'Predict Enum Entries',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of iterating enum entries.',
      skeleton: `enum class Coin(val value: Int) {\n    PENNY(1), NICKEL(5), DIME(10), QUARTER(25)\n}\n\nfun main() {\n    val total = Coin.entries.sumOf { it.value }\n    println(total)\n}`,
      solution: `41`,
      hints: ['Sum all coin values: 1 + 5 + 10 + 25.', 'sumOf adds up the values.', '41'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-14',
      title: 'Fix Missing When Branch',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the non-exhaustive when on an enum.',
      skeleton: `enum class Priority { LOW, MEDIUM, HIGH, CRITICAL }\n\nfun label(p: Priority): String = when (p) {\n    Priority.LOW -> "Low"\n    Priority.MEDIUM -> "Med"\n    Priority.HIGH -> "High"\n}`,
      solution: `enum class Priority { LOW, MEDIUM, HIGH, CRITICAL }\n\nfun label(p: Priority): String = when (p) {\n    Priority.LOW -> "Low"\n    Priority.MEDIUM -> "Med"\n    Priority.HIGH -> "High"\n    Priority.CRITICAL -> "Critical"\n}`,
      hints: ['when on enum must cover all constants when used as expression.', 'CRITICAL is missing.', 'Add Priority.CRITICAL -> "Critical"'],
      concepts: ['enum-class', 'when-expression'],
    },
    {
      id: 'kt-enum-15',
      title: 'Write an Enum Method',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write enum class Direction with NORTH, SOUTH, EAST, WEST and a method opposite(): Direction.',
      skeleton: `// Define Direction enum with opposite() method`,
      solution: `enum class Direction {\n    NORTH, SOUTH, EAST, WEST;\n\n    fun opposite(): Direction = when (this) {\n        NORTH -> SOUTH\n        SOUTH -> NORTH\n        EAST -> WEST\n        WEST -> EAST\n    }\n}`,
      hints: ['Use when(this) to match the current enum constant.', 'Each direction returns its opposite.', 'NORTH -> SOUTH, etc.'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-16',
      title: 'Write Enum to Range',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that converts a Grade enum (A, B, C, D, F) to a score range string.',
      skeleton: `enum class Grade { A, B, C, D, F }\n\nfun gradeRange(grade: Grade): String {\n    // return score range\n}`,
      solution: `enum class Grade { A, B, C, D, F }\n\nfun gradeRange(grade: Grade): String = when (grade) {\n    Grade.A -> "90-100"\n    Grade.B -> "80-89"\n    Grade.C -> "70-79"\n    Grade.D -> "60-69"\n    Grade.F -> "0-59"\n}`,
      hints: ['Map each grade to a range string.', 'Use when expression.', 'Grade.A -> "90-100"'],
      concepts: ['enum-class', 'when-expression'],
    },
    {
      id: 'kt-enum-17',
      title: 'Refactor Magic Strings to Enum',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor magic string constants to an enum.',
      skeleton: `fun getDiscount(tier: String): Double = when (tier) {\n    "BRONZE" -> 0.05\n    "SILVER" -> 0.10\n    "GOLD" -> 0.15\n    else -> 0.0\n}`,
      solution: `enum class Tier(val discount: Double) {\n    BRONZE(0.05),\n    SILVER(0.10),\n    GOLD(0.15)\n}\n\nfun getDiscount(tier: Tier): Double = tier.discount`,
      hints: ['Replace strings with enum constants.', 'Move discount into enum property.', 'enum class Tier(val discount: Double)'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-18',
      title: 'Refactor If-Else to Enum Method',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Move the logic into the enum as a method instead of an external function.',
      skeleton: `enum class Shape { CIRCLE, SQUARE, TRIANGLE }\n\nfun sides(shape: Shape): Int = when (shape) {\n    Shape.CIRCLE -> 0\n    Shape.SQUARE -> 4\n    Shape.TRIANGLE -> 3\n}`,
      solution: `enum class Shape(val sides: Int) {\n    CIRCLE(0),\n    SQUARE(4),\n    TRIANGLE(3)\n}`,
      hints: ['Move data into enum properties.', 'Each constant carries its own sides count.', 'enum class Shape(val sides: Int)'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-19',
      title: 'Write Enum Comparison',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function isHigherPriority(a: Priority, b: Priority): Boolean that returns true if a has a higher ordinal than b.',
      skeleton: `enum class Priority { LOW, MEDIUM, HIGH, CRITICAL }\n\nfun isHigherPriority(a: Priority, b: Priority): Boolean {\n    // compare by ordinal\n}`,
      solution: `enum class Priority { LOW, MEDIUM, HIGH, CRITICAL }\n\nfun isHigherPriority(a: Priority, b: Priority): Boolean {\n    return a.ordinal > b.ordinal\n}`,
      hints: ['Enums have ordinal property (0-based index).', 'Higher ordinal = later in the declaration.', 'a.ordinal > b.ordinal'],
      concepts: ['enum-class'],
    },
    {
      id: 'kt-enum-20',
      title: 'Predict Enum Abstract Method',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of calling abstract methods on enum constants.',
      skeleton: `enum class Expr {\n    DOUBLE {\n        override fun compute(n: Int) = n * 2\n    },\n    SQUARE {\n        override fun compute(n: Int) = n * n\n    };\n    abstract fun compute(n: Int): Int\n}\n\nfun main() {\n    println(Expr.DOUBLE.compute(5))\n    println(Expr.SQUARE.compute(5))\n}`,
      solution: `10\n25`,
      hints: ['DOUBLE.compute(5) = 5 * 2 = 10.', 'SQUARE.compute(5) = 5 * 5 = 25.', '10 and 25'],
      concepts: ['enum-class', 'abstract'],
    },
  ],
};
