import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-sealed',
  title: '13. Sealed Classes',
  explanation: `## Sealed Classes in Kotlin\n\nSealed classes restrict class hierarchies — all subclasses must be defined in the same package:\n\n\`\`\`kotlin\nsealed class Result {\n    data class Success(val data: String) : Result()\n    data class Error(val message: String) : Result()\n    data object Loading : Result()\n}\n\`\`\`\n\n**Key benefits:**\n- **Exhaustive when** — the compiler knows all subclasses, so no \`else\` needed\n- Type-safe state modeling\n- Better than enums when subclasses need different data\n\n\`\`\`kotlin\nfun handle(result: Result): String = when (result) {\n    is Result.Success -> "Got: \${result.data}"\n    is Result.Error -> "Error: \${result.message}"\n    Result.Loading -> "Loading..."\n}\n\`\`\`\n\n**Sealed interfaces** work similarly:\n\n\`\`\`kotlin\nsealed interface Shape\ndata class Circle(val r: Double) : Shape\ndata class Rect(val w: Double, val h: Double) : Shape\n\`\`\``,
  exercises: [
    {
      id: 'kt-sealed-1',
      title: 'Declare a Sealed Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a sealed class with subclasses.',
      skeleton: `___ class Result {\n    data class Success(val value: Int) : Result()\n    data class Failure(val error: String) : Result()\n}`,
      solution: `sealed class Result {\n    data class Success(val value: Int) : Result()\n    data class Failure(val error: String) : Result()\n}`,
      hints: ['Sealed classes use the sealed keyword.', 'Subclasses are defined inside or in the same file.', 'sealed'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-2',
      title: 'Exhaustive When on Sealed',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Handle all cases of a sealed class in when.',
      skeleton: `sealed class Shape {\n    data class Circle(val r: Double) : Shape()\n    data class Square(val s: Double) : Shape()\n}\n\nfun area(shape: Shape): Double = when (shape) {\n    ___ Shape.Circle -> 3.14159 * shape.r * shape.r\n    ___ Shape.Square -> shape.s * shape.s\n}`,
      solution: `sealed class Shape {\n    data class Circle(val r: Double) : Shape()\n    data class Square(val s: Double) : Shape()\n}\n\nfun area(shape: Shape): Double = when (shape) {\n    is Shape.Circle -> 3.14159 * shape.r * shape.r\n    is Shape.Square -> shape.s * shape.s\n}`,
      hints: ['Use is for type checking in when.', 'Smart cast gives access to properties after is.', 'is Shape.Circle'],
      concepts: ['sealed-class', 'when-expression'],
    },
    {
      id: 'kt-sealed-3',
      title: 'Sealed with Data Object',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a singleton state to a sealed class.',
      skeleton: `sealed class State {\n    ___ ___ Loading : State()\n    data class Loaded(val data: String) : State()\n    data class Error(val msg: String) : State()\n}`,
      solution: `sealed class State {\n    data object Loading : State()\n    data class Loaded(val data: String) : State()\n    data class Error(val msg: String) : State()\n}`,
      hints: ['For sealed subclasses without data, use data object.', 'data object is a singleton.', 'data object Loading'],
      concepts: ['sealed-class', 'data-object'],
    },
    {
      id: 'kt-sealed-4',
      title: 'Predict Sealed When Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output when handling a sealed class instance.',
      skeleton: `sealed class Expr {\n    data class Num(val value: Int) : Expr()\n    data class Add(val left: Expr, val right: Expr) : Expr()\n}\n\nfun eval(expr: Expr): Int = when (expr) {\n    is Expr.Num -> expr.value\n    is Expr.Add -> eval(expr.left) + eval(expr.right)\n}\n\nfun main() {\n    val e = Expr.Add(Expr.Num(3), Expr.Num(4))\n    println(eval(e))\n}`,
      solution: `7`,
      hints: ['Add(Num(3), Num(4)) evaluates to 3 + 4.', 'Recursive evaluation.', '7'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-5',
      title: 'Fix Non-Exhaustive When',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the when expression that is missing a sealed class branch.',
      skeleton: `sealed class Response {\n    data class Success(val body: String) : Response()\n    data class Error(val code: Int) : Response()\n    data object Timeout : Response()\n}\n\nfun describe(r: Response): String = when (r) {\n    is Response.Success -> "OK: \${r.body}"\n    is Response.Error -> "Error: \${r.code}"\n}`,
      solution: `sealed class Response {\n    data class Success(val body: String) : Response()\n    data class Error(val code: Int) : Response()\n    data object Timeout : Response()\n}\n\nfun describe(r: Response): String = when (r) {\n    is Response.Success -> "OK: \${r.body}"\n    is Response.Error -> "Error: \${r.code}"\n    Response.Timeout -> "Timed out"\n}`,
      hints: ['Timeout case is missing.', 'For data object, match without is.', 'Response.Timeout -> "Timed out"'],
      concepts: ['sealed-class', 'when-expression'],
    },
    {
      id: 'kt-sealed-6',
      title: 'Write a Sealed Result Type',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class Result<out T> with Success(val data: T), Error(val exception: String), and Loading. Write a function getMessage.',
      skeleton: `// Define sealed Result<T> and getMessage function`,
      solution: `sealed class Result<out T> {\n    data class Success<T>(val data: T) : Result<T>()\n    data class Error(val exception: String) : Result<Nothing>()\n    data object Loading : Result<Nothing>()\n}\n\nfun <T> getMessage(result: Result<T>): String = when (result) {\n    is Result.Success -> "Success: \${result.data}"\n    is Result.Error -> "Error: \${result.exception}"\n    Result.Loading -> "Loading..."\n}`,
      hints: ['Use out T for covariant generic.', 'Error and Loading use Nothing as type param.', 'sealed class Result<out T>'],
      concepts: ['sealed-class', 'generics'],
    },
    {
      id: 'kt-sealed-7',
      title: 'Write a Sealed Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed interface Event with data classes Click(val x: Int, val y: Int), KeyPress(val key: Char), and data object Scroll.',
      skeleton: `// Define sealed interface Event with subclasses`,
      solution: `sealed interface Event\ndata class Click(val x: Int, val y: Int) : Event\ndata class KeyPress(val key: Char) : Event\ndata object Scroll : Event`,
      hints: ['Sealed interfaces use sealed interface.', 'Subclasses can be defined at top level in the same file.', 'sealed interface Event'],
      concepts: ['sealed-interface'],
    },
    {
      id: 'kt-sealed-8',
      title: 'Predict Sealed Hierarchy',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when processing a list of sealed class instances.',
      skeleton: `sealed class Command {\n    data object Start : Command()\n    data object Stop : Command()\n    data class Log(val msg: String) : Command()\n}\n\nfun execute(cmd: Command) = when (cmd) {\n    Command.Start -> "Started"\n    Command.Stop -> "Stopped"\n    is Command.Log -> "Log: \${cmd.msg}"\n}\n\nfun main() {\n    val cmds = listOf(Command.Start, Command.Log("hello"), Command.Stop)\n    cmds.forEach { println(execute(it)) }\n}`,
      solution: `Started\nLog: hello\nStopped`,
      hints: ['Each command maps to its handler.', 'Start -> Started, Log -> Log: hello, Stop -> Stopped.', 'Started, Log: hello, Stopped'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-9',
      title: 'Fix Sealed Class Outside File',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Understand why adding a subclass in another file breaks things — fix by using the sealed class properly.',
      skeleton: `// File: Result.kt\nsealed class Result\ndata class Success(val v: Int) : Result()\ndata class Failure(val e: String) : Result()\n\n// This function must handle all cases\nfun handle(r: Result): String = when (r) {\n    is Success -> "OK"\n    is Failure -> "Fail"\n    else -> "Unknown" // This else should not be needed\n}`,
      solution: `// File: Result.kt\nsealed class Result\ndata class Success(val v: Int) : Result()\ndata class Failure(val e: String) : Result()\n\n// This function handles all cases exhaustively\nfun handle(r: Result): String = when (r) {\n    is Success -> "OK"\n    is Failure -> "Fail"\n}`,
      hints: ['With all subclasses in the same file, when is exhaustive.', 'Remove the else branch.', 'Sealed classes guarantee exhaustiveness.'],
      concepts: ['sealed-class', 'when-expression'],
    },
    {
      id: 'kt-sealed-10',
      title: 'Write Sealed for UI State',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class UiState with Idle, Loading, Success(val items: List<String>), and Error(val message: String). Write a render function.',
      skeleton: `// Define UiState sealed class and render function`,
      solution: `sealed class UiState {\n    data object Idle : UiState()\n    data object Loading : UiState()\n    data class Success(val items: List<String>) : UiState()\n    data class Error(val message: String) : UiState()\n}\n\nfun render(state: UiState): String = when (state) {\n    UiState.Idle -> "Waiting..."\n    UiState.Loading -> "Loading..."\n    is UiState.Success -> "Items: \${state.items.joinToString()}"\n    is UiState.Error -> "Error: \${state.message}"\n}`,
      hints: ['Common pattern for UI state management.', 'Use data object for states without data.', 'data class for states with data.'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-11',
      title: 'Write Sealed with Nested Hierarchy',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class that has another sealed class as a subclass for error categorization.',
      skeleton: `// ApiResult with Success and sealed Error (NetworkError, ServerError, AuthError)`,
      solution: `sealed class ApiResult {\n    data class Success(val data: String) : ApiResult()\n    sealed class Error : ApiResult() {\n        data class Network(val cause: String) : Error()\n        data class Server(val code: Int) : Error()\n        data object Auth : Error()\n    }\n}`,
      hints: ['Sealed classes can be nested.', 'Error is itself a sealed class inside ApiResult.', 'sealed class Error : ApiResult()'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-12',
      title: 'Predict Nested Sealed When',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when handling nested sealed classes.',
      skeleton: `sealed class Msg {\n    data class Text(val body: String) : Msg()\n    data class Image(val url: String) : Msg()\n}\n\nfun summary(msg: Msg) = when (msg) {\n    is Msg.Text -> "Text(\${msg.body.length} chars)"\n    is Msg.Image -> "Image"\n}\n\nfun main() {\n    println(summary(Msg.Text("Hello")))\n}`,
      solution: `Text(5 chars)`,
      hints: ['"Hello" has 5 characters.', 'Text branch formats with length.', 'Text(5 chars)'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-13',
      title: 'Write Sealed for Navigation',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class Route for app navigation with Home, Profile(val userId: String), and Settings.',
      skeleton: `// Define sealed Route and a navigate function`,
      solution: `sealed class Route {\n    data object Home : Route()\n    data class Profile(val userId: String) : Route()\n    data object Settings : Route()\n}\n\nfun navigate(route: Route): String = when (route) {\n    Route.Home -> "/home"\n    is Route.Profile -> "/profile/\${route.userId}"\n    Route.Settings -> "/settings"\n}`,
      hints: ['Navigation routes are a classic sealed class use case.', 'data object for singleton routes.', 'data class for routes with parameters.'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-14',
      title: 'Fix Sealed Smart Cast',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code that does not smart-cast properly after is check.',
      skeleton: `sealed class Animal {\n    data class Dog(val name: String) : Animal()\n    data class Cat(val name: String) : Animal()\n}\n\nfun getName(animal: Animal): String {\n    if (animal is Animal.Dog) {\n        return animal.name\n    }\n    return animal.name  // Error: Animal has no name property\n}`,
      solution: `sealed class Animal {\n    data class Dog(val name: String) : Animal()\n    data class Cat(val name: String) : Animal()\n}\n\nfun getName(animal: Animal): String = when (animal) {\n    is Animal.Dog -> animal.name\n    is Animal.Cat -> animal.name\n}`,
      hints: ['After the if, animal is not necessarily Cat.', 'Use when to handle all cases.', 'Each branch smart casts to the correct type.'],
      concepts: ['sealed-class', 'smart-cast'],
    },
    {
      id: 'kt-sealed-15',
      title: 'Write Sealed Class Mapping',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that maps a sealed class to another sealed class.',
      skeleton: `sealed class Input {\n    data class Text(val value: String) : Input()\n    data class Number(val value: Int) : Input()\n}\n\nsealed class Output {\n    data class StringResult(val value: String) : Output()\n    data class IntResult(val value: Int) : Output()\n}\n\nfun convert(input: Input): Output {\n    // map Input to Output\n}`,
      solution: `sealed class Input {\n    data class Text(val value: String) : Input()\n    data class Number(val value: Int) : Input()\n}\n\nsealed class Output {\n    data class StringResult(val value: String) : Output()\n    data class IntResult(val value: Int) : Output()\n}\n\nfun convert(input: Input): Output = when (input) {\n    is Input.Text -> Output.StringResult(input.value)\n    is Input.Number -> Output.IntResult(input.value)\n}`,
      hints: ['Map each Input subclass to corresponding Output.', 'Use when for exhaustive matching.', 'Input.Text -> Output.StringResult'],
      concepts: ['sealed-class'],
    },
    {
      id: 'kt-sealed-16',
      title: 'Write Sealed with Method',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class Expr with Const(val n: Int) and Add(val a: Expr, val b: Expr), plus a method eval() on each.',
      skeleton: `// Define sealed Expr with eval method`,
      solution: `sealed class Expr {\n    abstract fun eval(): Int\n\n    data class Const(val n: Int) : Expr() {\n        override fun eval() = n\n    }\n\n    data class Add(val a: Expr, val b: Expr) : Expr() {\n        override fun eval() = a.eval() + b.eval()\n    }\n}`,
      hints: ['Add an abstract fun eval() to the sealed class.', 'Each subclass overrides eval().', 'Const returns n, Add returns a.eval() + b.eval().'],
      concepts: ['sealed-class', 'abstract'],
    },
    {
      id: 'kt-sealed-17',
      title: 'Refactor Enum to Sealed Class',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor an enum that needs different data per variant to a sealed class.',
      skeleton: `enum class PaymentMethod {\n    CASH,\n    CREDIT_CARD, // needs cardNumber\n    BANK_TRANSFER // needs accountId\n}`,
      solution: `sealed class PaymentMethod {\n    data object Cash : PaymentMethod()\n    data class CreditCard(val cardNumber: String) : PaymentMethod()\n    data class BankTransfer(val accountId: String) : PaymentMethod()\n}`,
      hints: ['Enums cannot hold different data per constant.', 'Sealed classes allow different properties per subclass.', 'data class CreditCard(val cardNumber: String)'],
      concepts: ['sealed-class', 'enum-class'],
    },
    {
      id: 'kt-sealed-18',
      title: 'Refactor instanceof Chain to Sealed When',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor manual type checks to exhaustive sealed when.',
      skeleton: `open class Event\nclass ClickEvent(val x: Int) : Event()\nclass KeyEvent(val key: Char) : Event()\n\nfun handle(event: Event): String {\n    if (event is ClickEvent) return "Click at \${event.x}"\n    if (event is KeyEvent) return "Key: \${event.key}"\n    return "Unknown"\n}`,
      solution: `sealed class Event {\n    data class Click(val x: Int) : Event()\n    data class Key(val key: Char) : Event()\n}\n\nfun handle(event: Event): String = when (event) {\n    is Event.Click -> "Click at \${event.x}"\n    is Event.Key -> "Key: \${event.key}"\n}`,
      hints: ['Make Event sealed to enable exhaustive when.', 'No else branch needed.', 'Compiler ensures all cases are handled.'],
      concepts: ['sealed-class', 'when-expression'],
    },
    {
      id: 'kt-sealed-19',
      title: 'Write Sealed with Companion Factory',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class with a companion object factory method.',
      skeleton: `// Sealed class with companion factory`,
      solution: `sealed class JsonValue {\n    data class JsonString(val value: String) : JsonValue()\n    data class JsonNumber(val value: Double) : JsonValue()\n    data object JsonNull : JsonValue()\n\n    companion object {\n        fun parse(input: String): JsonValue = when {\n            input == "null" -> JsonNull\n            input.toDoubleOrNull() != null -> JsonNumber(input.toDouble())\n            else -> JsonString(input)\n        }\n    }\n}`,
      hints: ['Companion object provides a factory method.', 'parse returns the appropriate subclass.', 'companion object { fun parse(...) }'],
      concepts: ['sealed-class', 'companion-object'],
    },
    {
      id: 'kt-sealed-20',
      title: 'Predict Sealed Class Equality',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict equality behavior of sealed class instances.',
      skeleton: `sealed class Token {\n    data class Word(val text: String) : Token()\n    data object EOF : Token()\n}\n\nfun main() {\n    println(Token.Word("hi") == Token.Word("hi"))\n    println(Token.EOF == Token.EOF)\n    println(Token.Word("hi") == Token.Word("bye"))\n}`,
      solution: `true\ntrue\nfalse`,
      hints: ['data class uses structural equality.', 'data object is a singleton.', 'Same values = equal, different values = not equal.'],
      concepts: ['sealed-class', 'equals'],
    },
  ],
};
