import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-objects',
  title: '14. Objects',
  explanation: `## Objects in Kotlin\n\n**Object declaration** — creates a singleton:\n\n\`\`\`kotlin\nobject Database {\n    val url = "jdbc:sqlite:app.db"\n    fun connect() = println("Connected to \$url")\n}\nDatabase.connect()  // access directly\n\`\`\`\n\n**Companion object** — static-like members inside a class:\n\n\`\`\`kotlin\nclass User(val name: String) {\n    companion object {\n        fun create(name: String) = User(name)\n        const val MAX_NAME_LENGTH = 50\n    }\n}\nval user = User.create("Alice")\n\`\`\`\n\n**Object expression** — anonymous objects (like anonymous classes in Java):\n\n\`\`\`kotlin\nval comparator = object : Comparator<String> {\n    override fun compare(a: String, b: String) = a.length - b.length\n}\n\`\`\`\n\nObjects are initialized lazily when first accessed. Companion objects are initialized when the containing class is loaded.`,
  exercises: [
    {
      id: 'kt-objects-1',
      title: 'Declare a Singleton Object',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a singleton object.',
      skeleton: `___ Logger {\n    fun log(msg: String) = println("[LOG] \$msg")\n}`,
      solution: `object Logger {\n    fun log(msg: String) = println("[LOG] \$msg")\n}`,
      hints: ['Singleton objects use the object keyword.', 'No class keyword needed.', 'object Logger'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-2',
      title: 'Companion Object',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a companion object with a factory method.',
      skeleton: `class Color(val r: Int, val g: Int, val b: Int) {\n    ___ ___ {\n        fun red() = Color(255, 0, 0)\n        fun green() = Color(0, 255, 0)\n    }\n}`,
      solution: `class Color(val r: Int, val g: Int, val b: Int) {\n    companion object {\n        fun red() = Color(255, 0, 0)\n        fun green() = Color(0, 255, 0)\n    }\n}`,
      hints: ['Companion objects are declared inside a class.', 'companion object { ... }', 'companion object'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-3',
      title: 'Access Companion Method',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Call a companion object method.',
      skeleton: `class Config {\n    companion object {\n        fun default() = Config()\n    }\n}\n\nfun main() {\n    val cfg = Config.___\n    println(cfg)\n}`,
      solution: `class Config {\n    companion object {\n        fun default() = Config()\n    }\n}\n\nfun main() {\n    val cfg = Config.default()\n    println(cfg)\n}`,
      hints: ['Call companion methods on the class name.', 'Config.default()', 'default()'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-4',
      title: 'Predict Singleton Behavior',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict whether two references to an object are the same instance.',
      skeleton: `object Counter {\n    var count = 0\n}\n\nfun main() {\n    Counter.count++\n    Counter.count++\n    println(Counter.count)\n    println(Counter === Counter)\n}`,
      solution: `2\ntrue`,
      hints: ['Object declarations are singletons.', 'count is incremented twice.', 'Counter === Counter is always true.'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-5',
      title: 'Object Expression',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Create an anonymous object implementing an interface.',
      skeleton: `interface Greeter {\n    fun greet(): String\n}\n\nfun main() {\n    val g = ___ : Greeter {\n        override fun greet() = "Hello!"\n    }\n    println(g.greet())\n}`,
      solution: `interface Greeter {\n    fun greet(): String\n}\n\nfun main() {\n    val g = object : Greeter {\n        override fun greet() = "Hello!"\n    }\n    println(g.greet())\n}`,
      hints: ['Anonymous objects use object : Interface.', 'Similar to anonymous classes in Java.', 'object : Greeter { ... }'],
      concepts: ['object-expression'],
    },
    {
      id: 'kt-objects-6',
      title: 'Fix Object Constructor Error',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the object declaration that incorrectly has a constructor.',
      skeleton: `object Registry(val name: String) {\n    val items = mutableListOf<String>()\n}`,
      solution: `object Registry {\n    val name = "default"\n    val items = mutableListOf<String>()\n}`,
      hints: ['Object declarations cannot have constructors.', 'Remove the constructor, initialize properties directly.', 'object Registry { val name = "default" }'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-7',
      title: 'Write a Singleton Registry',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an object ServiceRegistry with a private map, and register/get methods.',
      skeleton: `// Define singleton ServiceRegistry`,
      solution: `object ServiceRegistry {\n    private val services = mutableMapOf<String, Any>()\n\n    fun register(name: String, service: Any) {\n        services[name] = service\n    }\n\n    fun get(name: String): Any? = services[name]\n}`,
      hints: ['Object declarations are singletons.', 'Use a MutableMap for storage.', 'object ServiceRegistry { ... }'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-8',
      title: 'Write a Named Companion Object',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class with a named companion object Factory that creates instances.',
      skeleton: `// Class with named companion object`,
      solution: `class Connection(val host: String, val port: Int) {\n    companion object Factory {\n        fun local() = Connection("localhost", 8080)\n        fun remote(host: String) = Connection(host, 443)\n    }\n}`,
      hints: ['Companion objects can have names.', 'companion object Factory { ... }', 'Access via Connection.Factory.local() or Connection.local()'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-9',
      title: 'Predict Companion Const',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of companion object const val.',
      skeleton: `class AppConfig {\n    companion object {\n        const val VERSION = "2.0"\n        const val APP_NAME = "MyApp"\n    }\n}\n\nfun main() {\n    println("\${AppConfig.APP_NAME} v\${AppConfig.VERSION}")\n}`,
      solution: `MyApp v2.0`,
      hints: ['const val in companion objects are compile-time constants.', 'Access via ClassName.CONSTANT.', 'MyApp v2.0'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-10',
      title: 'Fix Companion Object Access',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that tries to access a companion method on an instance.',
      skeleton: `class MathUtils {\n    companion object {\n        fun square(n: Int) = n * n\n    }\n}\n\nfun main() {\n    val utils = MathUtils()\n    println(utils.square(5))\n}`,
      solution: `class MathUtils {\n    companion object {\n        fun square(n: Int) = n * n\n    }\n}\n\nfun main() {\n    println(MathUtils.square(5))\n}`,
      hints: ['Companion methods are called on the class, not instances.', 'MathUtils.square(5)', 'Remove the instance creation.'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-11',
      title: 'Write Object Implementing Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a singleton object that implements Comparator<String> comparing by length.',
      skeleton: `// Object implementing Comparator<String>`,
      solution: `object LengthComparator : Comparator<String> {\n    override fun compare(a: String, b: String): Int = a.length - b.length\n}`,
      hints: ['Objects can implement interfaces.', 'object Name : Interface', 'override fun compare(a, b) = a.length - b.length'],
      concepts: ['object-declaration', 'interface'],
    },
    {
      id: 'kt-objects-12',
      title: 'Write Companion with Interface',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class whose companion object implements an interface (factory pattern).',
      skeleton: `// Interface, class, and companion implementing the interface`,
      solution: `interface Factory<T> {\n    fun create(): T\n}\n\nclass MyService(val name: String) {\n    companion object : Factory<MyService> {\n        override fun create() = MyService("default")\n    }\n}`,
      hints: ['Companion objects can implement interfaces.', 'companion object : Factory<MyService>', 'This enables passing the companion as a Factory.'],
      concepts: ['companion-object', 'interface'],
    },
    {
      id: 'kt-objects-13',
      title: 'Predict Object Expression Closure',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict how an object expression captures variables from its scope.',
      skeleton: `fun main() {\n    var count = 0\n    val counter = object {\n        fun increment() { count++ }\n        fun get() = count\n    }\n    counter.increment()\n    counter.increment()\n    println(counter.get())\n}`,
      solution: `2`,
      hints: ['Object expressions can access and modify outer variables.', 'increment is called twice.', 'count becomes 2.'],
      concepts: ['object-expression'],
    },
    {
      id: 'kt-objects-14',
      title: 'Write a Companion Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function on a companion object.',
      skeleton: `class MyClass {\n    companion object\n}\n\n// Write an extension function on MyClass.Companion`,
      solution: `class MyClass {\n    companion object\n}\n\nfun MyClass.Companion.hello() = "Hello from companion!"`,
      hints: ['Extension functions can be added to companion objects.', 'fun ClassName.Companion.name()', 'Access via MyClass.hello()'],
      concepts: ['companion-object', 'extensions'],
    },
    {
      id: 'kt-objects-15',
      title: 'Fix Object Expression Type',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the object expression that loses its custom members when assigned to an interface type.',
      skeleton: `interface Describable {\n    fun describe(): String\n}\n\nfun main() {\n    val obj: Describable = object : Describable {\n        val extra = "bonus"\n        override fun describe() = "described"\n    }\n    println(obj.extra)  // Error: extra not accessible\n}`,
      solution: `interface Describable {\n    fun describe(): String\n}\n\nfun main() {\n    val obj = object : Describable {\n        val extra = "bonus"\n        override fun describe() = "described"\n    }\n    println(obj.extra)\n}`,
      hints: ['When typed as the interface, custom members are hidden.', 'Remove the explicit type to keep the anonymous type.', 'val obj = object : Describable { ... }'],
      concepts: ['object-expression'],
    },
    {
      id: 'kt-objects-16',
      title: 'Write a Companion Object Logger',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class that uses a companion object to hold a logger instance and a tag.',
      skeleton: `// Class with companion object logger`,
      solution: `class UserService {\n    companion object {\n        private const val TAG = "UserService"\n        fun log(msg: String) = println("[\$TAG] \$msg")\n    }\n\n    fun createUser(name: String) {\n        log("Creating user: \$name")\n    }\n}`,
      hints: ['const val in companion for the tag.', 'log function in companion object.', 'Instance methods can call companion methods directly.'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-17',
      title: 'Refactor Static Methods to Companion',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor top-level utility functions into a companion object.',
      skeleton: `fun createUser(name: String) = User(name)\nfun defaultUser() = User("Guest")\n\nclass User(val name: String)`,
      solution: `class User(val name: String) {\n    companion object {\n        fun create(name: String) = User(name)\n        fun default() = User("Guest")\n    }\n}`,
      hints: ['Factory methods belong in companion objects.', 'Move functions inside companion object.', 'User.create("Alice"), User.default()'],
      concepts: ['companion-object'],
    },
    {
      id: 'kt-objects-18',
      title: 'Refactor to Object Declaration',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor a class that should be a singleton into an object.',
      skeleton: `class AppSettings {\n    val theme = "dark"\n    val language = "en"\n    fun describe() = "Theme: \$theme, Lang: \$language"\n}\n\n// Usage: val settings = AppSettings() // but we only want one instance`,
      solution: `object AppSettings {\n    val theme = "dark"\n    val language = "en"\n    fun describe() = "Theme: \$theme, Lang: \$language"\n}`,
      hints: ['If only one instance is needed, use object.', 'Replace class with object.', 'object AppSettings { ... }'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-19',
      title: 'Write an Object with Mutable State',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a singleton IdGenerator object with a private var counter and a fun next(): Int.',
      skeleton: `// Define IdGenerator singleton`,
      solution: `object IdGenerator {\n    private var counter = 0\n\n    fun next(): Int {\n        counter++\n        return counter\n    }\n\n    fun reset() {\n        counter = 0\n    }\n}`,
      hints: ['Singleton with mutable internal state.', 'private var counter keeps track.', 'next() increments and returns.'],
      concepts: ['object-declaration'],
    },
    {
      id: 'kt-objects-20',
      title: 'Predict Companion Object Init',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict when a companion object is initialized.',
      skeleton: `class MyClass {\n    companion object {\n        init { println("Companion init") }\n        val value = run { println("Value init"); 42 }\n    }\n    init { println("Class init") }\n}\n\nfun main() {\n    println("Before")\n    val x = MyClass()\n    println("After")\n}`,
      solution: `Before\nCompanion init\nValue init\nClass init\nAfter`,
      hints: ['Companion object is initialized when the class is first accessed.', 'Companion init and value run before class init.', 'Before, Companion init, Value init, Class init, After.'],
      concepts: ['companion-object'],
    },
  ],
};
