import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-generics',
  title: '15. Generics',
  explanation: `## Generics in Kotlin\n\nGenerics allow writing type-safe code that works with different types:\n\n\`\`\`kotlin\nclass Box<T>(val value: T)\nval intBox = Box(42)        // Box<Int>\nval strBox = Box("Hello")   // Box<String>\n\`\`\`\n\n**Generic functions:**\n\n\`\`\`kotlin\nfun <T> singletonList(item: T): List<T> = listOf(item)\n\`\`\`\n\n**Type constraints:**\n\n\`\`\`kotlin\nfun <T : Comparable<T>> max(a: T, b: T): T = if (a > b) a else b\n\`\`\`\n\n**Variance:**\n- \`out T\` — covariant (producer, like ? extends T in Java)\n- \`in T\` — contravariant (consumer, like ? super T in Java)\n\n\`\`\`kotlin\ninterface Producer<out T> { fun produce(): T }\ninterface Consumer<in T> { fun consume(item: T) }\n\`\`\`\n\n**Reified type parameters** — access type info at runtime (inline functions only):\n\n\`\`\`kotlin\ninline fun <reified T> isType(value: Any): Boolean = value is T\n\`\`\``,
  exercises: [
    {
      id: 'kt-generics-1',
      title: 'Declare a Generic Class',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a generic class that holds a value of any type.',
      skeleton: `class Wrapper___T___(val value: T)`,
      solution: `class Wrapper<T>(val value: T)`,
      hints: ['Type parameters go in angle brackets.', '<T> declares the type parameter.', 'class Wrapper<T>(val value: T)'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-2',
      title: 'Generic Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a generic function that returns the first element of a list.',
      skeleton: `fun ___T___ first(list: List<T>): T = list[0]`,
      solution: `fun <T> first(list: List<T>): T = list[0]`,
      hints: ['Generic functions declare type parameter before function name.', 'fun <T> functionName()', '<T>'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-3',
      title: 'Type Constraint',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Add a type constraint so T must be Comparable.',
      skeleton: `fun <T ___ Comparable<T>> maxOf(a: T, b: T): T = if (a > b) a else b`,
      solution: `fun <T : Comparable<T>> maxOf(a: T, b: T): T = if (a > b) a else b`,
      hints: ['Use : to constrain a type parameter.', 'T : Comparable<T> means T must be comparable.', ':'],
      concepts: ['type-constraints'],
    },
    {
      id: 'kt-generics-4',
      title: 'Predict Generic Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of a generic function.',
      skeleton: `fun <T> repeat(item: T, n: Int): List<T> {\n    val result = mutableListOf<T>()\n    for (i in 1..n) result.add(item)\n    return result\n}\n\nfun main() {\n    println(repeat("ha", 3))\n}`,
      solution: `[ha, ha, ha]`,
      hints: ['repeat adds "ha" 3 times.', 'List toString shows [item, item, item].', '[ha, ha, ha]'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-5',
      title: 'Covariant Out',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Make the type parameter covariant using out.',
      skeleton: `interface Source<___ T> {\n    fun next(): T\n}`,
      solution: `interface Source<out T> {\n    fun next(): T\n}`,
      hints: ['out makes a type parameter covariant.', 'Covariant means Source<Cat> is a subtype of Source<Animal>.', 'out T'],
      concepts: ['variance'],
    },
    {
      id: 'kt-generics-6',
      title: 'Fix Generic Type Mismatch',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the function that should work with any Number type.',
      skeleton: `fun sum(list: List<Int>): Double {\n    return list.sumOf { it.toDouble() }\n}\n\nfun main() {\n    val doubles = listOf(1.5, 2.5, 3.0)\n    println(sum(doubles))  // Error: List<Double> not List<Int>\n}`,
      solution: `fun <T : Number> sum(list: List<T>): Double {\n    return list.sumOf { it.toDouble() }\n}\n\nfun main() {\n    val doubles = listOf(1.5, 2.5, 3.0)\n    println(sum(doubles))\n}`,
      hints: ['Use a generic type parameter bounded by Number.', 'fun <T : Number> sum(list: List<T>)', 'This accepts List<Int>, List<Double>, etc.'],
      concepts: ['type-constraints'],
    },
    {
      id: 'kt-generics-7',
      title: 'Write a Generic Stack',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a generic class Stack<T> with push, pop, and peek.',
      skeleton: `// Define generic Stack<T>`,
      solution: `class Stack<T> {\n    private val items = mutableListOf<T>()\n\n    fun push(item: T) { items.add(item) }\n\n    fun pop(): T? = if (items.isNotEmpty()) items.removeAt(items.size - 1) else null\n\n    fun peek(): T? = items.lastOrNull()\n\n    fun isEmpty(): Boolean = items.isEmpty()\n}`,
      hints: ['class Stack<T> with a MutableList<T> backing.', 'push adds, pop removes last, peek returns last.', 'Return T? for pop and peek.'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-8',
      title: 'Write a Generic Pair Mapper',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function mapPair<A, B, C>(pair: Pair<A, B>, transform: (A) -> C): Pair<C, B>.',
      skeleton: `fun <A, B, C> mapPair(pair: Pair<A, B>, transform: (A) -> C): Pair<C, B> {\n    // map first element\n}`,
      solution: `fun <A, B, C> mapPair(pair: Pair<A, B>, transform: (A) -> C): Pair<C, B> {\n    return Pair(transform(pair.first), pair.second)\n}`,
      hints: ['Transform the first element, keep the second.', 'Pair(transform(pair.first), pair.second)', 'Multiple type parameters separated by commas.'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-9',
      title: 'Predict Variance',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict whether the assignment compiles with out variance.',
      skeleton: `open class Animal\nclass Cat : Animal()\n\ninterface Cage<out T> {\n    fun get(): T\n}\n\nclass CatCage : Cage<Cat> {\n    override fun get(): Cat = Cat()\n}\n\nfun main() {\n    val catCage: Cage<Cat> = CatCage()\n    val animalCage: Cage<Animal> = catCage  // Does this compile?\n    println("Compiles!")\n}`,
      solution: `Compiles!`,
      hints: ['out makes Cage covariant.', 'Cage<Cat> is a subtype of Cage<Animal> with out.', 'The assignment is valid.'],
      concepts: ['variance'],
    },
    {
      id: 'kt-generics-10',
      title: 'Fix In/Out Variance',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the interface that uses T in both in and out positions but is declared as out.',
      skeleton: `interface Container<out T> {\n    fun get(): T\n    fun set(item: T)  // Error: T is in an 'in' position\n}`,
      solution: `interface Container<T> {\n    fun get(): T\n    fun set(item: T)\n}`,
      hints: ['out T can only be used in return (out) positions.', 'set uses T in an in position.', 'Remove out to make it invariant.'],
      concepts: ['variance'],
    },
    {
      id: 'kt-generics-11',
      title: 'Write a Reified Type Check',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an inline function isOfType<T>(value: Any): Boolean using reified.',
      skeleton: `// Define inline reified function`,
      solution: `inline fun <reified T> isOfType(value: Any): Boolean = value is T`,
      hints: ['reified allows runtime type checks.', 'Must be an inline function.', 'inline fun <reified T> isOfType(value: Any) = value is T'],
      concepts: ['reified'],
    },
    {
      id: 'kt-generics-12',
      title: 'Predict Generic Type Inference',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict what type Kotlin infers for a generic function.',
      skeleton: `fun <T> wrap(item: T): List<T> = listOf(item)\n\nfun main() {\n    val result = wrap(42)\n    println(result)\n    println(result::class.simpleName)\n}`,
      solution: `[42]\nArrayList`,
      hints: ['wrap(42) creates a List<Int>.', 'listOf returns an ArrayList under the hood.', '[42] and ArrayList.'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-13',
      title: 'Write a Generic Filter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function filterByType<T>(items: List<Any>): List<T> using reified to filter items by type.',
      skeleton: `// Define inline reified filter function`,
      solution: `inline fun <reified T> filterByType(items: List<Any>): List<T> {\n    return items.filterIsInstance<T>()\n}`,
      hints: ['reified lets you use T in filterIsInstance.', 'filterIsInstance<T>() filters by type.', 'inline fun <reified T> filterByType(...)'],
      concepts: ['reified', 'generics'],
    },
    {
      id: 'kt-generics-14',
      title: 'Write a Generic Result Type',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a sealed class Result<out T> with Success<T>(val data: T), Error(val message: String).',
      skeleton: `// Define generic sealed Result`,
      solution: `sealed class Result<out T> {\n    data class Success<T>(val data: T) : Result<T>()\n    data class Error(val message: String) : Result<Nothing>()\n}`,
      hints: ['out T for covariance.', 'Error uses Nothing since it has no T data.', 'sealed class Result<out T>'],
      concepts: ['generics', 'sealed-class'],
    },
    {
      id: 'kt-generics-15',
      title: 'Fix Star Projection',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the function that needs to accept a list of any type.',
      skeleton: `fun printAll(list: List<Any>) {\n    for (item in list) println(item)\n}\n\nfun main() {\n    val ints: List<Int> = listOf(1, 2, 3)\n    printAll(ints)  // Works because List is covariant\n    \n    val mutInts: MutableList<Int> = mutableListOf(1, 2, 3)\n    printAll(mutInts)  // Error: MutableList is invariant\n}`,
      solution: `fun printAll(list: List<*>) {\n    for (item in list) println(item)\n}\n\nfun main() {\n    val ints: List<Int> = listOf(1, 2, 3)\n    printAll(ints)\n    \n    val mutInts: MutableList<Int> = mutableListOf(1, 2, 3)\n    printAll(mutInts)\n}`,
      hints: ['Use star projection List<*> to accept any type.', '* means unknown type.', 'List<*> accepts any List regardless of type parameter.'],
      concepts: ['star-projection'],
    },
    {
      id: 'kt-generics-16',
      title: 'Write a Contravariant Consumer',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a fun interface Processor<in T> with fun process(item: T), and demonstrate contravariance.',
      skeleton: `// Define contravariant Processor interface`,
      solution: `fun interface Processor<in T> {\n    fun process(item: T)\n}\n\nfun main() {\n    val anyProcessor = Processor<Any> { println(it) }\n    val stringProcessor: Processor<String> = anyProcessor  // OK: in variance\n    stringProcessor.process("Hello")\n}`,
      hints: ['in T means contravariant — consumes T.', 'Processor<Any> can be used as Processor<String>.', 'fun interface Processor<in T>'],
      concepts: ['variance'],
    },
    {
      id: 'kt-generics-17',
      title: 'Refactor to Generic Function',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor duplicate functions to a single generic one.',
      skeleton: `fun swapInt(pair: Pair<Int, Int>): Pair<Int, Int> = Pair(pair.second, pair.first)\nfun swapString(pair: Pair<String, String>): Pair<String, String> = Pair(pair.second, pair.first)\nfun swapDouble(pair: Pair<Double, Double>): Pair<Double, Double> = Pair(pair.second, pair.first)`,
      solution: `fun <T> swap(pair: Pair<T, T>): Pair<T, T> = Pair(pair.second, pair.first)`,
      hints: ['All three functions do the same thing with different types.', 'Use a generic type parameter.', 'fun <T> swap(pair: Pair<T, T>)'],
      concepts: ['generics'],
    },
    {
      id: 'kt-generics-18',
      title: 'Refactor to Bounded Generic',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor to use a type-bounded generic instead of Any.',
      skeleton: `fun findMin(list: List<Any>): Any {\n    var min = list[0]\n    for (item in list) {\n        if ((item as Comparable<Any>) < min) min = item\n    }\n    return min\n}`,
      solution: `fun <T : Comparable<T>> findMin(list: List<T>): T {\n    var min = list[0]\n    for (item in list) {\n        if (item < min) min = item\n    }\n    return min\n}`,
      hints: ['Use T : Comparable<T> for type safety.', 'No casts needed with proper bounds.', 'fun <T : Comparable<T>> findMin(list: List<T>): T'],
      concepts: ['type-constraints'],
    },
    {
      id: 'kt-generics-19',
      title: 'Write Multiple Bounds',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'kotlin',
      goal: 'Write a function that requires T to be both Comparable and CharSequence using where clause.',
      skeleton: `// Function with multiple type bounds`,
      solution: `fun <T> longestSorted(a: T, b: T): T where T : Comparable<T>, T : CharSequence {\n    return if (a > b) a else b\n}`,
      hints: ['Use where clause for multiple bounds.', 'where T : Comparable<T>, T : CharSequence', 'Both bounds must be satisfied.'],
      concepts: ['type-constraints'],
    },
    {
      id: 'kt-generics-20',
      title: 'Write a Generic Extension Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a generic extension function List<T>.secondOrNull(): T? that returns the second element or null.',
      skeleton: `// Define generic extension function`,
      solution: `fun <T> List<T>.secondOrNull(): T? {\n    return if (size >= 2) this[1] else null\n}`,
      hints: ['Extension function on List<T>.', 'Check size before accessing index 1.', 'fun <T> List<T>.secondOrNull(): T?'],
      concepts: ['generics', 'extensions'],
    },
  ],
};
