import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-list',
  title: '16. Lists',
  explanation: `## Lists in Kotlin\n\n**Immutable lists** (read-only):\n\n\`\`\`kotlin\nval fruits = listOf("apple", "banana", "cherry")\nprintln(fruits[0])        // apple\nprintln(fruits.size)      // 3\n\`\`\`\n\n**Mutable lists:**\n\n\`\`\`kotlin\nval items = mutableListOf(1, 2, 3)\nitems.add(4)\nitems.removeAt(0)\nitems[0] = 10\n\`\`\`\n\n**Common operations:**\n\n\`\`\`kotlin\nlistOf(1, 2, 3, 4, 5)\n    .filter { it > 2 }        // [3, 4, 5]\n    .map { it * 2 }           // [6, 8, 10]\n    .sorted()                  // [6, 8, 10]\n    .first()                   // 6\n    .take(2)                   // [6, 8]\n\`\`\`\n\n**Other useful functions:** any, all, none, find, count, groupBy, flatMap, zip, fold, reduce.`,
  exercises: [
    {
      id: 'kt-list-1',
      title: 'Create an Immutable List',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a read-only list of integers.',
      skeleton: `fun main() {\n    val numbers = ___(1, 2, 3, 4, 5)\n    println(numbers)\n}`,
      solution: `fun main() {\n    val numbers = listOf(1, 2, 3, 4, 5)\n    println(numbers)\n}`,
      hints: ['listOf creates an immutable list.', 'listOf(1, 2, 3, 4, 5)', 'listOf'],
      concepts: ['listOf'],
    },
    {
      id: 'kt-list-2',
      title: 'Create a Mutable List',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a mutable list and add an element.',
      skeleton: `fun main() {\n    val items = ___<String>()\n    items.add("hello")\n    println(items)\n}`,
      solution: `fun main() {\n    val items = mutableListOf<String>()\n    items.add("hello")\n    println(items)\n}`,
      hints: ['mutableListOf creates a modifiable list.', 'mutableListOf<String>()', 'mutableListOf'],
      concepts: ['mutableListOf'],
    },
    {
      id: 'kt-list-3',
      title: 'Filter a List',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Filter a list to keep only even numbers.',
      skeleton: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5, 6)\n    val evens = nums.___ { it % 2 == 0 }\n    println(evens)\n}`,
      solution: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5, 6)\n    val evens = nums.filter { it % 2 == 0 }\n    println(evens)\n}`,
      hints: ['filter keeps elements matching the predicate.', 'it % 2 == 0 checks for even.', 'filter'],
      concepts: ['filter'],
    },
    {
      id: 'kt-list-4',
      title: 'Map a List',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Transform each element by doubling it.',
      skeleton: `fun main() {\n    val nums = listOf(1, 2, 3)\n    val doubled = nums.___ { it * 2 }\n    println(doubled)\n}`,
      solution: `fun main() {\n    val nums = listOf(1, 2, 3)\n    val doubled = nums.map { it * 2 }\n    println(doubled)\n}`,
      hints: ['map transforms each element.', 'it * 2 doubles each number.', 'map'],
      concepts: ['map'],
    },
    {
      id: 'kt-list-5',
      title: 'Predict Filter + Map',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of chained operations.',
      skeleton: `fun main() {\n    val result = listOf(1, 2, 3, 4, 5)\n        .filter { it > 2 }\n        .map { it * 10 }\n    println(result)\n}`,
      solution: `[30, 40, 50]`,
      hints: ['filter keeps 3, 4, 5.', 'map multiplies by 10: 30, 40, 50.', '[30, 40, 50]'],
      concepts: ['filter', 'map'],
    },
    {
      id: 'kt-list-6',
      title: 'Fix Immutable List Modification',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that tries to add to an immutable list.',
      skeleton: `fun main() {\n    val items = listOf("a", "b")\n    items.add("c")\n    println(items)\n}`,
      solution: `fun main() {\n    val items = mutableListOf("a", "b")\n    items.add("c")\n    println(items)\n}`,
      hints: ['listOf creates a read-only list.', 'Use mutableListOf to allow modification.', 'mutableListOf("a", "b")'],
      concepts: ['mutableListOf'],
    },
    {
      id: 'kt-list-7',
      title: 'Write a Sum Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function sumList(nums: List<Int>): Int using fold.',
      skeleton: `fun sumList(nums: List<Int>): Int {\n    // use fold\n}`,
      solution: `fun sumList(nums: List<Int>): Int {\n    return nums.fold(0) { acc, n -> acc + n }\n}`,
      hints: ['fold starts with an initial value and accumulates.', 'fold(0) { acc, n -> acc + n }', 'Or simply use nums.sum()'],
      concepts: ['fold'],
    },
    {
      id: 'kt-list-8',
      title: 'Write a FlatMap Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function getWords(sentences: List<String>): List<String> that splits each sentence into words.',
      skeleton: `fun getWords(sentences: List<String>): List<String> {\n    // split each sentence and flatten\n}`,
      solution: `fun getWords(sentences: List<String>): List<String> {\n    return sentences.flatMap { it.split(" ") }\n}`,
      hints: ['flatMap maps and flattens.', 'Split each sentence by space.', 'sentences.flatMap { it.split(" ") }'],
      concepts: ['flatMap'],
    },
    {
      id: 'kt-list-9',
      title: 'Predict Sorted Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of sorting operations.',
      skeleton: `fun main() {\n    val nums = listOf(3, 1, 4, 1, 5)\n    println(nums.sorted())\n    println(nums.sortedDescending())\n}`,
      solution: `[1, 1, 3, 4, 5]\n[5, 4, 3, 1, 1]`,
      hints: ['sorted() returns ascending order.', 'sortedDescending() returns descending.', '[1, 1, 3, 4, 5] and [5, 4, 3, 1, 1]'],
      concepts: ['sorted'],
    },
    {
      id: 'kt-list-10',
      title: 'Fix IndexOutOfBounds',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that might throw an IndexOutOfBoundsException.',
      skeleton: `fun getThird(list: List<String>): String {\n    return list[2]\n}\n\nfun main() {\n    println(getThird(listOf("a")))  // crashes!\n}`,
      solution: `fun getThird(list: List<String>): String? {\n    return list.getOrNull(2)\n}\n\nfun main() {\n    println(getThird(listOf("a")))\n}`,
      hints: ['list[2] crashes if the list has fewer than 3 elements.', 'Use getOrNull for safe access.', 'list.getOrNull(2)'],
      concepts: ['safe-access'],
    },
    {
      id: 'kt-list-11',
      title: 'Write a GroupBy Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function groupByLength(words: List<String>): Map<Int, List<String>> that groups words by their length.',
      skeleton: `fun groupByLength(words: List<String>): Map<Int, List<String>> {\n    // group by length\n}`,
      solution: `fun groupByLength(words: List<String>): Map<Int, List<String>> {\n    return words.groupBy { it.length }\n}`,
      hints: ['groupBy creates a map from key to list.', 'it.length is the grouping key.', 'words.groupBy { it.length }'],
      concepts: ['groupBy'],
    },
    {
      id: 'kt-list-12',
      title: 'Predict Any/All/None',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of any, all, and none.',
      skeleton: `fun main() {\n    val nums = listOf(2, 4, 6, 8)\n    println(nums.any { it > 5 })\n    println(nums.all { it % 2 == 0 })\n    println(nums.none { it < 0 })\n}`,
      solution: `true\ntrue\ntrue`,
      hints: ['any: at least one > 5 (6, 8).', 'all: all are even.', 'none: no negatives.'],
      concepts: ['any', 'all', 'none'],
    },
    {
      id: 'kt-list-13',
      title: 'Write a Zip Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function pairUp(names: List<String>, ages: List<Int>): List<String> that zips names and ages into "name (age)" strings.',
      skeleton: `fun pairUp(names: List<String>, ages: List<Int>): List<String> {\n    // zip and format\n}`,
      solution: `fun pairUp(names: List<String>, ages: List<Int>): List<String> {\n    return names.zip(ages) { name, age -> "\$name (\$age)" }\n}`,
      hints: ['zip combines two lists element-wise.', 'The transform lambda formats each pair.', 'names.zip(ages) { name, age -> ... }'],
      concepts: ['zip'],
    },
    {
      id: 'kt-list-14',
      title: 'Write a Distinct Counter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function countDistinct(items: List<String>): Int that returns the number of unique items.',
      skeleton: `fun countDistinct(items: List<String>): Int {\n    // count unique items\n}`,
      solution: `fun countDistinct(items: List<String>): Int {\n    return items.distinct().size\n}`,
      hints: ['distinct() removes duplicates.', 'Then count with .size.', 'items.distinct().size'],
      concepts: ['distinct'],
    },
    {
      id: 'kt-list-15',
      title: 'Fix Mutable List ConcurrentModification',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the concurrent modification when filtering a mutable list.',
      skeleton: `fun main() {\n    val items = mutableListOf(1, 2, 3, 4, 5)\n    for (item in items) {\n        if (item % 2 == 0) items.remove(item)\n    }\n    println(items)\n}`,
      solution: `fun main() {\n    val items = mutableListOf(1, 2, 3, 4, 5)\n    items.removeAll { it % 2 == 0 }\n    println(items)\n}`,
      hints: ['Cannot modify a list while iterating it.', 'Use removeAll with a predicate.', 'items.removeAll { it % 2 == 0 }'],
      concepts: ['mutableListOf'],
    },
    {
      id: 'kt-list-16',
      title: 'Write a Chunked Processor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function batchSum(nums: List<Int>, batchSize: Int): List<Int> that chunks the list and sums each batch.',
      skeleton: `fun batchSum(nums: List<Int>, batchSize: Int): List<Int> {\n    // chunk and sum each batch\n}`,
      solution: `fun batchSum(nums: List<Int>, batchSize: Int): List<Int> {\n    return nums.chunked(batchSize) { it.sum() }\n}`,
      hints: ['chunked splits into sublists of the given size.', 'The transform lambda can sum each chunk.', 'nums.chunked(batchSize) { it.sum() }'],
      concepts: ['chunked'],
    },
    {
      id: 'kt-list-17',
      title: 'Refactor Loop to Map',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the for loop to use map.',
      skeleton: `fun uppercaseAll(words: List<String>): List<String> {\n    val result = mutableListOf<String>()\n    for (word in words) {\n        result.add(word.uppercase())\n    }\n    return result\n}`,
      solution: `fun uppercaseAll(words: List<String>): List<String> {\n    return words.map { it.uppercase() }\n}`,
      hints: ['map is cleaner than a manual loop.', 'words.map { it.uppercase() }', 'No need for a mutable result list.'],
      concepts: ['map'],
    },
    {
      id: 'kt-list-18',
      title: 'Refactor Filter Loop to filter',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the manual filter loop to use the filter function.',
      skeleton: `fun positives(nums: List<Int>): List<Int> {\n    val result = mutableListOf<Int>()\n    for (n in nums) {\n        if (n > 0) result.add(n)\n    }\n    return result\n}`,
      solution: `fun positives(nums: List<Int>): List<Int> {\n    return nums.filter { it > 0 }\n}`,
      hints: ['filter replaces the manual loop pattern.', 'nums.filter { it > 0 }', 'Much more concise.'],
      concepts: ['filter'],
    },
    {
      id: 'kt-list-19',
      title: 'Write a List Partition',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function splitBySign(nums: List<Int>): Pair<List<Int>, List<Int>> that partitions into non-negative and negative.',
      skeleton: `fun splitBySign(nums: List<Int>): Pair<List<Int>, List<Int>> {\n    // partition by sign\n}`,
      solution: `fun splitBySign(nums: List<Int>): Pair<List<Int>, List<Int>> {\n    return nums.partition { it >= 0 }\n}`,
      hints: ['partition splits into two lists by predicate.', 'First list: matches, Second list: does not match.', 'nums.partition { it >= 0 }'],
      concepts: ['partition'],
    },
    {
      id: 'kt-list-20',
      title: 'Predict Fold Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of fold.',
      skeleton: `fun main() {\n    val result = listOf("a", "b", "c").fold("") { acc, s -> "\$acc\$s-" }\n    println(result)\n}`,
      solution: `a-b-c-`,
      hints: ['fold starts with "" and concatenates.', '"" + "a-" = "a-", + "b-" = "a-b-", + "c-" = "a-b-c-".', 'a-b-c-'],
      concepts: ['fold'],
    },
  ],
};
