import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-map',
  title: '17. Maps',
  explanation: `## Maps in Kotlin\n\n**Immutable maps:**\n\n\`\`\`kotlin\nval colors = mapOf("red" to "#FF0000", "green" to "#00FF00")\nprintln(colors["red"])      // #FF0000\nprintln(colors.size)        // 2\n\`\`\`\n\n**Mutable maps:**\n\n\`\`\`kotlin\nval scores = mutableMapOf<String, Int>()\nscores["Alice"] = 95\nscores["Bob"] = 87\nscores.remove("Bob")\n\`\`\`\n\n**Key operations:**\n\n\`\`\`kotlin\nmap.keys              // Set of keys\nmap.values            // Collection of values\nmap.entries           // Set of key-value pairs\nmap.containsKey("k")  // true if key exists\nmap.getOrDefault("k", 0)  // value or default\nmap.getOrPut("k") { computeValue() }  // get or compute\n\`\`\`\n\n**Transformations:**\n\n\`\`\`kotlin\nmap.mapKeys { it.key.uppercase() }\nmap.mapValues { it.value * 2 }\nmap.filter { it.value > 10 }\nlist.groupBy { it.first() }  // group into map\n\`\`\``,
  exercises: [
    {
      id: 'kt-map-1',
      title: 'Create an Immutable Map',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a map using the to infix function.',
      skeleton: `fun main() {\n    val capitals = ___("France" ___ "Paris", "Japan" ___ "Tokyo")\n    println(capitals)\n}`,
      solution: `fun main() {\n    val capitals = mapOf("France" to "Paris", "Japan" to "Tokyo")\n    println(capitals)\n}`,
      hints: ['mapOf creates an immutable map.', 'to creates key-value pairs.', 'mapOf("France" to "Paris")'],
      concepts: ['mapOf'],
    },
    {
      id: 'kt-map-2',
      title: 'Access Map Values',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Access a value by key, with a default.',
      skeleton: `fun main() {\n    val ages = mapOf("Alice" to 30, "Bob" to 25)\n    val age = ages.___(\"Charlie\", 0)\n    println(age)\n}`,
      solution: `fun main() {\n    val ages = mapOf("Alice" to 30, "Bob" to 25)\n    val age = ages.getOrDefault(\"Charlie\", 0)\n    println(age)\n}`,
      hints: ['getOrDefault returns the default if key is missing.', 'getOrDefault("Charlie", 0)', 'getOrDefault'],
      concepts: ['getOrDefault'],
    },
    {
      id: 'kt-map-3',
      title: 'Mutable Map Operations',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a mutable map and add an entry.',
      skeleton: `fun main() {\n    val scores = ___<String, Int>()\n    scores[\"Alice\"] = 95\n    println(scores)\n}`,
      solution: `fun main() {\n    val scores = mutableMapOf<String, Int>()\n    scores[\"Alice\"] = 95\n    println(scores)\n}`,
      hints: ['mutableMapOf creates a modifiable map.', 'Use bracket syntax to add entries.', 'mutableMapOf<String, Int>()'],
      concepts: ['mutableMapOf'],
    },
    {
      id: 'kt-map-4',
      title: 'Predict Map Access',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict what happens when accessing a missing key.',
      skeleton: `fun main() {\n    val map = mapOf("a" to 1, "b" to 2)\n    println(map["a"])\n    println(map["c"])\n}`,
      solution: `1\nnull`,
      hints: ['map["a"] returns 1.', 'map["c"] returns null for missing key.', '1 and null'],
      concepts: ['mapOf'],
    },
    {
      id: 'kt-map-5',
      title: 'Iterate Over Map Entries',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Iterate over map entries using destructuring.',
      skeleton: `fun main() {\n    val map = mapOf("x" to 1, "y" to 2)\n    for ((___, ___) in map) {\n        println("\$key = \$value")\n    }\n}`,
      solution: `fun main() {\n    val map = mapOf("x" to 1, "y" to 2)\n    for ((key, value) in map) {\n        println("\$key = \$value")\n    }\n}`,
      hints: ['Destructure map entries into (key, value).', 'for ((key, value) in map)', 'key, value'],
      concepts: ['entries'],
    },
    {
      id: 'kt-map-6',
      title: 'Fix Map Mutation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that tries to add to an immutable map.',
      skeleton: `fun main() {\n    val config = mapOf("host" to "localhost")\n    config["port"] = "8080"\n    println(config)\n}`,
      solution: `fun main() {\n    val config = mutableMapOf("host" to "localhost")\n    config["port"] = "8080"\n    println(config)\n}`,
      hints: ['mapOf creates a read-only map.', 'Use mutableMapOf for modification.', 'mutableMapOf("host" to "localhost")'],
      concepts: ['mutableMapOf'],
    },
    {
      id: 'kt-map-7',
      title: 'Write a Word Counter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function wordFrequency(words: List<String>): Map<String, Int> that counts occurrences.',
      skeleton: `fun wordFrequency(words: List<String>): Map<String, Int> {\n    // count word frequencies\n}`,
      solution: `fun wordFrequency(words: List<String>): Map<String, Int> {\n    return words.groupingBy { it }.eachCount()\n}`,
      hints: ['groupingBy creates a Grouping.', 'eachCount counts occurrences per group.', 'words.groupingBy { it }.eachCount()'],
      concepts: ['groupBy'],
    },
    {
      id: 'kt-map-8',
      title: 'Write a Map Merger',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function mergeMaps(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> that sums values for duplicate keys.',
      skeleton: `fun mergeMaps(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> {\n    // merge with sum for conflicts\n}`,
      solution: `fun mergeMaps(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> {\n    val result = a.toMutableMap()\n    for ((key, value) in b) {\n        result[key] = result.getOrDefault(key, 0) + value\n    }\n    return result\n}`,
      hints: ['Start with a copy of map a.', 'For each entry in b, add to existing value.', 'getOrDefault handles missing keys.'],
      concepts: ['mutableMapOf', 'getOrDefault'],
    },
    {
      id: 'kt-map-9',
      title: 'Predict MapValues Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of mapValues transformation.',
      skeleton: `fun main() {\n    val prices = mapOf("apple" to 1.5, "banana" to 0.75)\n    val doubled = prices.mapValues { it.value * 2 }\n    println(doubled)\n}`,
      solution: `{apple=3.0, banana=1.5}`,
      hints: ['mapValues transforms each value.', 'apple: 1.5 * 2 = 3.0, banana: 0.75 * 2 = 1.5.', '{apple=3.0, banana=1.5}'],
      concepts: ['mapValues'],
    },
    {
      id: 'kt-map-10',
      title: 'Fix Map getOrPut',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the grouping code using getOrPut instead of manual check.',
      skeleton: `fun groupByFirstLetter(words: List<String>): Map<Char, List<String>> {\n    val result = mutableMapOf<Char, MutableList<String>>()\n    for (word in words) {\n        val key = word[0]\n        if (result[key] == null) {\n            result[key] = mutableListOf()\n        }\n        result[key]!!.add(word)\n    }\n    return result\n}`,
      solution: `fun groupByFirstLetter(words: List<String>): Map<Char, List<String>> {\n    val result = mutableMapOf<Char, MutableList<String>>()\n    for (word in words) {\n        result.getOrPut(word[0]) { mutableListOf() }.add(word)\n    }\n    return result\n}`,
      hints: ['getOrPut simplifies the null check pattern.', 'It returns the existing value or puts the default.', 'result.getOrPut(key) { mutableListOf() }.add(word)'],
      concepts: ['getOrPut'],
    },
    {
      id: 'kt-map-11',
      title: 'Write a Map Filter',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function expensiveItems(prices: Map<String, Double>, threshold: Double): Map<String, Double>.',
      skeleton: `fun expensiveItems(prices: Map<String, Double>, threshold: Double): Map<String, Double> {\n    // filter by price\n}`,
      solution: `fun expensiveItems(prices: Map<String, Double>, threshold: Double): Map<String, Double> {\n    return prices.filter { it.value >= threshold }\n}`,
      hints: ['filter works on maps too.', 'it.value >= threshold checks the price.', 'prices.filter { it.value >= threshold }'],
      concepts: ['filter'],
    },
    {
      id: 'kt-map-12',
      title: 'Write an Invert Map Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function invert(map: Map<String, Int>): Map<Int, String> that swaps keys and values.',
      skeleton: `fun invert(map: Map<String, Int>): Map<Int, String> {\n    // swap keys and values\n}`,
      solution: `fun invert(map: Map<String, Int>): Map<Int, String> {\n    return map.entries.associate { (k, v) -> v to k }\n}`,
      hints: ['associate builds a new map from pairs.', 'Swap key and value: v to k.', 'map.entries.associate { (k, v) -> v to k }'],
      concepts: ['associate'],
    },
    {
      id: 'kt-map-13',
      title: 'Predict ContainsKey',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of containsKey and containsValue.',
      skeleton: `fun main() {\n    val map = mapOf("a" to 1, "b" to 2, "c" to 3)\n    println(map.containsKey("b"))\n    println(map.containsValue(5))\n    println("a" in map)\n}`,
      solution: `true\nfalse\ntrue`,
      hints: ['containsKey("b") is true.', 'containsValue(5) is false.', '"a" in map checks keys.'],
      concepts: ['containsKey'],
    },
    {
      id: 'kt-map-14',
      title: 'Write List to Map',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function nameToLength(names: List<String>): Map<String, Int> that maps each name to its length.',
      skeleton: `fun nameToLength(names: List<String>): Map<String, Int> {\n    // associate name to length\n}`,
      solution: `fun nameToLength(names: List<String>): Map<String, Int> {\n    return names.associateWith { it.length }\n}`,
      hints: ['associateWith maps each element to a computed value.', 'it.length gives the length.', 'names.associateWith { it.length }'],
      concepts: ['associateWith'],
    },
    {
      id: 'kt-map-15',
      title: 'Fix Null Safety on Map Access',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the unsafe map access that can return null.',
      skeleton: `fun getScore(scores: Map<String, Int>, name: String): Int {\n    return scores[name]\n}`,
      solution: `fun getScore(scores: Map<String, Int>, name: String): Int {\n    return scores[name] ?: 0\n}`,
      hints: ['Map access with [] returns nullable.', 'Use Elvis operator for a default.', 'scores[name] ?: 0'],
      concepts: ['null-safety'],
    },
    {
      id: 'kt-map-16',
      title: 'Write a GroupBy Counter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function countByLength(words: List<String>): Map<Int, Int> that counts how many words have each length.',
      skeleton: `fun countByLength(words: List<String>): Map<Int, Int> {\n    // group and count\n}`,
      solution: `fun countByLength(words: List<String>): Map<Int, Int> {\n    return words.groupBy { it.length }.mapValues { it.value.size }\n}`,
      hints: ['groupBy to group by length.', 'mapValues to count each group.', 'groupBy { it.length }.mapValues { it.value.size }'],
      concepts: ['groupBy', 'mapValues'],
    },
    {
      id: 'kt-map-17',
      title: 'Refactor to Associate',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor the manual map building to use associate.',
      skeleton: `fun buildMap(users: List<String>): Map<String, Int> {\n    val result = mutableMapOf<String, Int>()\n    for (user in users) {\n        result[user] = user.length\n    }\n    return result\n}`,
      solution: `fun buildMap(users: List<String>): Map<String, Int> {\n    return users.associateWith { it.length }\n}`,
      hints: ['associateWith replaces the manual loop.', 'users.associateWith { it.length }', 'Much more concise.'],
      concepts: ['associateWith'],
    },
    {
      id: 'kt-map-18',
      title: 'Refactor to MapOf',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the mutable map construction to an immutable mapOf.',
      skeleton: `fun getDefaults(): Map<String, String> {\n    val m = mutableMapOf<String, String>()\n    m["theme"] = "dark"\n    m["lang"] = "en"\n    m["font"] = "mono"\n    return m\n}`,
      solution: `fun getDefaults(): Map<String, String> {\n    return mapOf("theme" to "dark", "lang" to "en", "font" to "mono")\n}`,
      hints: ['If the map is built once, use mapOf directly.', 'mapOf("theme" to "dark", ...)', 'No need for mutable operations.'],
      concepts: ['mapOf'],
    },
    {
      id: 'kt-map-19',
      title: 'Write a Map Difference',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function diff(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> that returns entries in a that are not in b.',
      skeleton: `fun diff(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> {\n    // entries in a not in b\n}`,
      solution: `fun diff(a: Map<String, Int>, b: Map<String, Int>): Map<String, Int> {\n    return a.filter { it.key !in b }\n}`,
      hints: ['Filter entries whose key is not in b.', 'it.key !in b checks absence.', 'a.filter { it.key !in b }'],
      concepts: ['filter'],
    },
    {
      id: 'kt-map-20',
      title: 'Predict Map Plus Operator',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of the + operator on maps.',
      skeleton: `fun main() {\n    val a = mapOf("x" to 1, "y" to 2)\n    val b = mapOf("y" to 99, "z" to 3)\n    val c = a + b\n    println(c)\n}`,
      solution: `{x=1, y=99, z=3}`,
      hints: ['+ merges maps; right side wins on conflicts.', 'y from b (99) overrides y from a (2).', '{x=1, y=99, z=3}'],
      concepts: ['mapOf'],
    },
  ],
};
