import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-set',
  title: '18. Sets',
  explanation: `## Sets in Kotlin\n\nSets are unordered collections with no duplicates:\n\n\`\`\`kotlin\nval colors = setOf("red", "green", "blue")\nprintln("red" in colors)   // true\nprintln(colors.size)        // 3\n\`\`\`\n\n**Mutable sets:**\n\n\`\`\`kotlin\nval tags = mutableSetOf("kotlin", "android")\ntags.add("jvm")\ntags.remove("android")\n\`\`\`\n\n**Set operations:**\n\n\`\`\`kotlin\nval a = setOf(1, 2, 3)\nval b = setOf(2, 3, 4)\na intersect b   // [2, 3]\na union b       // [1, 2, 3, 4]\na subtract b    // [1]\na + b           // union\na - b           // subtract\n\`\`\`\n\n**Common uses:** removing duplicates, membership testing, mathematical set operations.`,
  exercises: [
    {
      id: 'kt-set-1',
      title: 'Create an Immutable Set',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a set of strings.',
      skeleton: `fun main() {\n    val fruits = ___("apple", "banana", "cherry")\n    println(fruits)\n}`,
      solution: `fun main() {\n    val fruits = setOf("apple", "banana", "cherry")\n    println(fruits)\n}`,
      hints: ['setOf creates an immutable set.', 'setOf("apple", "banana", "cherry")', 'setOf'],
      concepts: ['setOf'],
    },
    {
      id: 'kt-set-2',
      title: 'Set Membership Check',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Check if an element is in the set.',
      skeleton: `fun main() {\n    val vowels = setOf('a', 'e', 'i', 'o', 'u')\n    println('e' ___ vowels)\n}`,
      solution: `fun main() {\n    val vowels = setOf('a', 'e', 'i', 'o', 'u')\n    println('e' in vowels)\n}`,
      hints: ['Use in to check membership.', 'element in set returns Boolean.', 'in'],
      concepts: ['membership'],
    },
    {
      id: 'kt-set-3',
      title: 'Set Intersection',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Find common elements between two sets.',
      skeleton: `fun main() {\n    val a = setOf(1, 2, 3, 4)\n    val b = setOf(3, 4, 5, 6)\n    val common = a ___ b\n    println(common)\n}`,
      solution: `fun main() {\n    val a = setOf(1, 2, 3, 4)\n    val b = setOf(3, 4, 5, 6)\n    val common = a intersect b\n    println(common)\n}`,
      hints: ['intersect finds common elements.', 'a intersect b gives elements in both.', 'intersect'],
      concepts: ['intersect'],
    },
    {
      id: 'kt-set-4',
      title: 'Predict Set Deduplication',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict how sets handle duplicates.',
      skeleton: `fun main() {\n    val nums = setOf(1, 2, 2, 3, 3, 3)\n    println(nums)\n    println(nums.size)\n}`,
      solution: `[1, 2, 3]\n3`,
      hints: ['Sets automatically remove duplicates.', 'Only unique values are kept.', '[1, 2, 3] with size 3.'],
      concepts: ['setOf'],
    },
    {
      id: 'kt-set-5',
      title: 'Set Union',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Combine two sets.',
      skeleton: `fun main() {\n    val a = setOf("a", "b")\n    val b = setOf("b", "c")\n    val all = a ___ b\n    println(all)\n}`,
      solution: `fun main() {\n    val a = setOf("a", "b")\n    val b = setOf("b", "c")\n    val all = a union b\n    println(all)\n}`,
      hints: ['union combines both sets.', 'Duplicates are removed.', 'union'],
      concepts: ['union'],
    },
    {
      id: 'kt-set-6',
      title: 'Fix Set Modification',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that tries to add to an immutable set.',
      skeleton: `fun main() {\n    val tags = setOf("kotlin")\n    tags.add("java")\n    println(tags)\n}`,
      solution: `fun main() {\n    val tags = mutableSetOf("kotlin")\n    tags.add("java")\n    println(tags)\n}`,
      hints: ['setOf creates a read-only set.', 'Use mutableSetOf for modification.', 'mutableSetOf("kotlin")'],
      concepts: ['mutableSetOf'],
    },
    {
      id: 'kt-set-7',
      title: 'Write a Unique Elements Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function unique(list: List<Int>): Set<Int> that returns the unique elements.',
      skeleton: `fun unique(list: List<Int>): Set<Int> {\n    // return unique elements\n}`,
      solution: `fun unique(list: List<Int>): Set<Int> {\n    return list.toSet()\n}`,
      hints: ['toSet() converts a list to a set, removing duplicates.', 'return list.toSet()', 'toSet()'],
      concepts: ['toSet'],
    },
    {
      id: 'kt-set-8',
      title: 'Write a Set Difference',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function removed(original: Set<String>, toRemove: Set<String>): Set<String> that returns elements in original but not in toRemove.',
      skeleton: `fun removed(original: Set<String>, toRemove: Set<String>): Set<String> {\n    // set difference\n}`,
      solution: `fun removed(original: Set<String>, toRemove: Set<String>): Set<String> {\n    return original subtract toRemove\n}`,
      hints: ['subtract gives elements in first but not second.', 'original subtract toRemove', 'Or use original - toRemove'],
      concepts: ['subtract'],
    },
    {
      id: 'kt-set-9',
      title: 'Predict Set Operations',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of multiple set operations.',
      skeleton: `fun main() {\n    val a = setOf(1, 2, 3)\n    val b = setOf(2, 3, 4)\n    println(a union b)\n    println(a intersect b)\n    println(a subtract b)\n}`,
      solution: `[1, 2, 3, 4]\n[2, 3]\n[1]`,
      hints: ['union: all unique elements.', 'intersect: common elements.', 'subtract: in a but not b.'],
      concepts: ['union', 'intersect', 'subtract'],
    },
    {
      id: 'kt-set-10',
      title: 'Fix Set Equality Check',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Understand that set equality ignores order - fix the test.',
      skeleton: `fun main() {\n    val a = setOf(1, 2, 3)\n    val b = setOf(3, 2, 1)\n    // Developer expects false because order differs\n    if (a != b) println("Different!") else println("Same!")\n}`,
      solution: `fun main() {\n    val a = setOf(1, 2, 3)\n    val b = setOf(3, 2, 1)\n    // Sets are equal if they contain the same elements regardless of order\n    if (a == b) println("Same!") else println("Different!")\n}`,
      hints: ['Sets compare by content, not order.', '{1,2,3} == {3,2,1} is true.', 'Fix the expected behavior.'],
      concepts: ['set-equality'],
    },
    {
      id: 'kt-set-11',
      title: 'Write a Symmetric Difference',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function symmetricDiff(a: Set<Int>, b: Set<Int>): Set<Int> that returns elements in either but not both.',
      skeleton: `fun symmetricDiff(a: Set<Int>, b: Set<Int>): Set<Int> {\n    // elements in either but not both\n}`,
      solution: `fun symmetricDiff(a: Set<Int>, b: Set<Int>): Set<Int> {\n    return (a union b) subtract (a intersect b)\n}`,
      hints: ['Symmetric difference = union minus intersection.', '(a union b) subtract (a intersect b)', 'Elements unique to each set.'],
      concepts: ['union', 'intersect', 'subtract'],
    },
    {
      id: 'kt-set-12',
      title: 'Predict MutableSet Add',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the return value of adding to a set.',
      skeleton: `fun main() {\n    val s = mutableSetOf(1, 2, 3)\n    println(s.add(4))  // new element\n    println(s.add(2))  // duplicate\n    println(s)\n}`,
      solution: `true\nfalse\n[1, 2, 3, 4]`,
      hints: ['add returns true if element was added.', 'add returns false if already present.', 'true, false, [1, 2, 3, 4]'],
      concepts: ['mutableSetOf'],
    },
    {
      id: 'kt-set-13',
      title: 'Write a Subset Checker',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function isSubset(sub: Set<Int>, super_: Set<Int>): Boolean.',
      skeleton: `fun isSubset(sub: Set<Int>, super_: Set<Int>): Boolean {\n    // check if sub is a subset of super_\n}`,
      solution: `fun isSubset(sub: Set<Int>, super_: Set<Int>): Boolean {\n    return super_.containsAll(sub)\n}`,
      hints: ['containsAll checks if all elements are present.', 'super_.containsAll(sub)', 'A is subset of B if B contains all of A.'],
      concepts: ['containsAll'],
    },
    {
      id: 'kt-set-14',
      title: 'Write a Duplicate Finder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function findDuplicates(list: List<Int>): Set<Int> that returns elements appearing more than once.',
      skeleton: `fun findDuplicates(list: List<Int>): Set<Int> {\n    // find duplicates\n}`,
      solution: `fun findDuplicates(list: List<Int>): Set<Int> {\n    return list.groupBy { it }.filter { it.value.size > 1 }.keys\n}`,
      hints: ['Group by element, filter groups with size > 1.', 'Take the keys of those groups.', 'groupBy { it }.filter { it.value.size > 1 }.keys'],
      concepts: ['groupBy', 'filter'],
    },
    {
      id: 'kt-set-15',
      title: 'Fix Set Type Inference',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the empty set creation that has no type information.',
      skeleton: `fun main() {\n    val items = setOf()\n    items.contains("test")  // Error: inferred as Set<Nothing>\n}`,
      solution: `fun main() {\n    val items = emptySet<String>()\n    items.contains("test")\n}`,
      hints: ['Empty setOf() creates Set<Nothing>.', 'Use emptySet<String>() for proper typing.', 'emptySet<String>()'],
      concepts: ['setOf'],
    },
    {
      id: 'kt-set-16',
      title: 'Write a Set from Map Keys',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function allKeys(maps: List<Map<String, Any>>): Set<String> that collects all unique keys from multiple maps.',
      skeleton: `fun allKeys(maps: List<Map<String, Any>>): Set<String> {\n    // collect all unique keys\n}`,
      solution: `fun allKeys(maps: List<Map<String, Any>>): Set<String> {\n    return maps.flatMap { it.keys }.toSet()\n}`,
      hints: ['flatMap to collect all keys.', 'toSet() to deduplicate.', 'maps.flatMap { it.keys }.toSet()'],
      concepts: ['flatMap', 'toSet'],
    },
    {
      id: 'kt-set-17',
      title: 'Refactor List to Set',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor: use a Set instead of a List for unique membership checks.',
      skeleton: `fun hasPermission(userPerms: List<String>, required: String): Boolean {\n    for (perm in userPerms) {\n        if (perm == required) return true\n    }\n    return false\n}`,
      solution: `fun hasPermission(userPerms: Set<String>, required: String): Boolean {\n    return required in userPerms\n}`,
      hints: ['Set membership check is O(1) vs O(n) for List.', 'Use in operator.', 'required in userPerms'],
      concepts: ['membership'],
    },
    {
      id: 'kt-set-18',
      title: 'Refactor to Set Operations',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor manual loop to use set operations.',
      skeleton: `fun commonTags(a: List<String>, b: List<String>): List<String> {\n    val result = mutableListOf<String>()\n    for (tag in a) {\n        if (b.contains(tag) && !result.contains(tag)) {\n            result.add(tag)\n        }\n    }\n    return result\n}`,
      solution: `fun commonTags(a: List<String>, b: List<String>): Set<String> {\n    return a.toSet() intersect b.toSet()\n}`,
      hints: ['Convert to sets and use intersect.', 'a.toSet() intersect b.toSet()', 'Much cleaner than manual loop.'],
      concepts: ['intersect', 'toSet'],
    },
    {
      id: 'kt-set-19',
      title: 'Write a Set Builder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function buildNumberSet(ranges: List<IntRange>): Set<Int> that creates a set from multiple ranges.',
      skeleton: `fun buildNumberSet(ranges: List<IntRange>): Set<Int> {\n    // combine all ranges into a single set\n}`,
      solution: `fun buildNumberSet(ranges: List<IntRange>): Set<Int> {\n    return ranges.flatMap { it.toList() }.toSet()\n}`,
      hints: ['flatMap to expand each range.', 'toSet() to deduplicate.', 'ranges.flatMap { it.toList() }.toSet()'],
      concepts: ['flatMap', 'toSet'],
    },
    {
      id: 'kt-set-20',
      title: 'Predict Set Plus/Minus',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of + and - operators on sets.',
      skeleton: `fun main() {\n    val s = setOf(1, 2, 3)\n    println(s + 4)\n    println(s - 2)\n    println(s + setOf(3, 4, 5))\n}`,
      solution: `[1, 2, 3, 4]\n[1, 3]\n[1, 2, 3, 4, 5]`,
      hints: ['+ adds element(s).', '- removes element(s).', 'Duplicates are ignored in sets.'],
      concepts: ['setOf'],
    },
  ],
};
