import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-seq',
  title: '19. Sequences',
  explanation: `## Sequences in Kotlin\n\nSequences are lazily evaluated collections — elements are processed one at a time, on demand:\n\n\`\`\`kotlin\nval result = sequenceOf(1, 2, 3, 4, 5)\n    .filter { it > 2 }\n    .map { it * 10 }\n    .first()  // processes only until first match: 30\n\`\`\`\n\n**Creating sequences:**\n\n\`\`\`kotlin\nval fromList = listOf(1, 2, 3).asSequence()\nval generated = generateSequence(1) { it * 2 }  // 1, 2, 4, 8, ...\nval built = sequence {\n    yield(1)\n    yieldAll(listOf(2, 3))\n    yield(4)\n}\n\`\`\`\n\n**When to use sequences:**\n- Large collections with chained operations\n- When you only need a subset of results\n- Infinite data streams\n\n**List vs Sequence:** Lists create intermediate collections at each step. Sequences process element-by-element lazily.`,
  exercises: [
    {
      id: 'kt-seq-1',
      title: 'Convert List to Sequence',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Convert a list to a sequence for lazy evaluation.',
      skeleton: `fun main() {\n    val result = listOf(1, 2, 3, 4, 5)\n        .___\n        .filter { it > 2 }\n        .map { it * 10 }\n        .toList()\n    println(result)\n}`,
      solution: `fun main() {\n    val result = listOf(1, 2, 3, 4, 5)\n        .asSequence()\n        .filter { it > 2 }\n        .map { it * 10 }\n        .toList()\n    println(result)\n}`,
      hints: ['asSequence() converts to a lazy sequence.', 'toList() triggers evaluation.', 'asSequence()'],
      concepts: ['asSequence'],
    },
    {
      id: 'kt-seq-2',
      title: 'Generate a Sequence',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Generate a sequence of powers of 2.',
      skeleton: `fun main() {\n    val powers = ___(1) { it * 2 }\n    println(powers.take(5).toList())\n}`,
      solution: `fun main() {\n    val powers = generateSequence(1) { it * 2 }\n    println(powers.take(5).toList())\n}`,
      hints: ['generateSequence creates a sequence from a seed.', 'Each element is computed from the previous.', 'generateSequence(1) { it * 2 }'],
      concepts: ['generateSequence'],
    },
    {
      id: 'kt-seq-3',
      title: 'Sequence Builder',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Build a sequence using the sequence builder.',
      skeleton: `fun main() {\n    val s = ___ {\n        yield(1)\n        yield(2)\n        yieldAll(listOf(3, 4, 5))\n    }\n    println(s.toList())\n}`,
      solution: `fun main() {\n    val s = sequence {\n        yield(1)\n        yield(2)\n        yieldAll(listOf(3, 4, 5))\n    }\n    println(s.toList())\n}`,
      hints: ['sequence { } is the builder.', 'yield emits a single element.', 'yieldAll emits a collection.'],
      concepts: ['sequence-builder'],
    },
    {
      id: 'kt-seq-4',
      title: 'Predict Lazy Evaluation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict how many times each operation runs with lazy evaluation.',
      skeleton: `fun main() {\n    val result = sequenceOf(1, 2, 3, 4, 5)\n        .filter {\n            print("f\$it ")\n            it % 2 != 0\n        }\n        .map {\n            print("m\$it ")\n            it * 10\n        }\n        .first()\n    println(result)\n}`,
      solution: `f1 m1 10`,
      hints: ['first() stops after finding the first match.', 'Only element 1 passes filter, so map runs once.', 'f1 m1 10'],
      concepts: ['lazy-evaluation'],
    },
    {
      id: 'kt-seq-5',
      title: 'Infinite Fibonacci Sequence',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that returns a sequence of Fibonacci numbers.',
      skeleton: `fun fibonacci(): Sequence<Int> {\n    // generate Fibonacci sequence\n}`,
      solution: `fun fibonacci(): Sequence<Int> = sequence {\n    var a = 0\n    var b = 1\n    while (true) {\n        yield(a)\n        val next = a + b\n        a = b\n        b = next\n    }\n}`,
      hints: ['Use sequence builder with an infinite loop.', 'yield each Fibonacci number.', 'Track two previous numbers.'],
      concepts: ['sequence-builder'],
    },
    {
      id: 'kt-seq-6',
      title: 'Fix Missing Terminal Operation',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the code that does nothing because it lacks a terminal operation.',
      skeleton: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    nums.asSequence()\n        .filter { it > 2 }\n        .map { it * 10 }\n    println("Done")  // filter and map never execute!\n}`,
      solution: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    val result = nums.asSequence()\n        .filter { it > 2 }\n        .map { it * 10 }\n        .toList()\n    println(result)\n}`,
      hints: ['Sequences are lazy — nothing happens without a terminal operation.', 'Add toList() to trigger evaluation.', '.toList() at the end'],
      concepts: ['lazy-evaluation'],
    },
    {
      id: 'kt-seq-7',
      title: 'Write a Take While',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function takeWhilePositive(nums: Sequence<Int>): List<Int> that takes elements while they are positive.',
      skeleton: `fun takeWhilePositive(nums: Sequence<Int>): List<Int> {\n    // take while positive\n}`,
      solution: `fun takeWhilePositive(nums: Sequence<Int>): List<Int> {\n    return nums.takeWhile { it > 0 }.toList()\n}`,
      hints: ['takeWhile keeps elements until predicate fails.', 'Stops at first non-positive.', 'nums.takeWhile { it > 0 }.toList()'],
      concepts: ['takeWhile'],
    },
    {
      id: 'kt-seq-8',
      title: 'Write a Collatz Sequence',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function collatz(n: Int): Sequence<Int> using generateSequence that follows the Collatz rule until reaching 1.',
      skeleton: `fun collatz(n: Int): Sequence<Int> {\n    // Collatz: if even, n/2; if odd, 3n+1; stop at 1\n}`,
      solution: `fun collatz(n: Int): Sequence<Int> {\n    return generateSequence(n) { if (it == 1) null else if (it % 2 == 0) it / 2 else it * 3 + 1 }\n}`,
      hints: ['generateSequence stops when the lambda returns null.', 'Return null when reaching 1.', 'If even: n/2, if odd: 3n+1'],
      concepts: ['generateSequence'],
    },
    {
      id: 'kt-seq-9',
      title: 'Predict Sequence vs List',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the processing order difference between list and sequence.',
      skeleton: `fun main() {\n    println("--- List ---")\n    listOf(1, 2, 3)\n        .filter { print("f\$it "); it > 1 }\n        .map { print("m\$it "); it * 10 }\n    println()\n    println("--- Sequence ---")\n    sequenceOf(1, 2, 3)\n        .filter { print("f\$it "); it > 1 }\n        .map { print("m\$it "); it * 10 }\n        .toList()\n}`,
      solution: `--- List ---\nf1 f2 f3 m2 m3 \n--- Sequence ---\nf1 f2 m2 f3 m3 `,
      hints: ['Lists process all elements per step.', 'Sequences process each element through all steps.', 'List: all filters then all maps. Sequence: element by element.'],
      concepts: ['lazy-evaluation'],
    },
    {
      id: 'kt-seq-10',
      title: 'Fix Infinite Sequence Without Limit',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the infinite sequence that will never terminate.',
      skeleton: `fun main() {\n    val nums = generateSequence(1) { it + 1 }\n    println(nums.toList())  // Runs forever!\n}`,
      solution: `fun main() {\n    val nums = generateSequence(1) { it + 1 }\n    println(nums.take(10).toList())\n}`,
      hints: ['Infinite sequences need a limit.', 'Use take(n) to limit elements.', 'nums.take(10).toList()'],
      concepts: ['generateSequence'],
    },
    {
      id: 'kt-seq-11',
      title: 'Write a Chunked Sequence Processor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function processInBatches(items: Sequence<String>, batchSize: Int): List<List<String>>.',
      skeleton: `fun processInBatches(items: Sequence<String>, batchSize: Int): List<List<String>> {\n    // chunk into batches\n}`,
      solution: `fun processInBatches(items: Sequence<String>, batchSize: Int): List<List<String>> {\n    return items.chunked(batchSize).toList()\n}`,
      hints: ['chunked splits sequence into sublists.', 'items.chunked(batchSize)', 'toList() triggers evaluation.'],
      concepts: ['chunked'],
    },
    {
      id: 'kt-seq-12',
      title: 'Predict generateSequence Termination',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict when generateSequence terminates.',
      skeleton: `fun main() {\n    val seq = generateSequence(10) { if (it > 1) it / 2 else null }\n    println(seq.toList())\n}`,
      solution: `[10, 5, 2, 1]`,
      hints: ['10 / 2 = 5, 5 / 2 = 2, 2 / 2 = 1, 1 returns null (stops).', 'Sequence terminates when lambda returns null.', '[10, 5, 2, 1]'],
      concepts: ['generateSequence'],
    },
    {
      id: 'kt-seq-13',
      title: 'Write a Windowed Sequence',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function movingAverage(nums: Sequence<Double>, windowSize: Int): List<Double> using windowed.',
      skeleton: `fun movingAverage(nums: Sequence<Double>, windowSize: Int): List<Double> {\n    // compute moving average\n}`,
      solution: `fun movingAverage(nums: Sequence<Double>, windowSize: Int): List<Double> {\n    return nums.windowed(windowSize) { window -> window.average() }.toList()\n}`,
      hints: ['windowed creates sliding windows.', 'Average each window.', 'nums.windowed(windowSize) { it.average() }'],
      concepts: ['windowed'],
    },
    {
      id: 'kt-seq-14',
      title: 'Write an Iterator to Sequence',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function rangeSequence(start: Int, end: Int): Sequence<Int> using sequence builder.',
      skeleton: `fun rangeSequence(start: Int, end: Int): Sequence<Int> {\n    // yield elements from start to end\n}`,
      solution: `fun rangeSequence(start: Int, end: Int): Sequence<Int> = sequence {\n    var current = start\n    while (current <= end) {\n        yield(current)\n        current++\n    }\n}`,
      hints: ['Use sequence builder with yield.', 'Loop from start to end.', 'yield(current) in a while loop.'],
      concepts: ['sequence-builder'],
    },
    {
      id: 'kt-seq-15',
      title: 'Fix Sequence Reuse',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Understand that sequences can only be iterated once if backed by an iterator.',
      skeleton: `fun main() {\n    val seq = listOf(1, 2, 3).asSequence()\n    println(seq.toList())  // [1, 2, 3]\n    println(seq.toList())  // should also work\n    // Fix: ensure this is safe\n}`,
      solution: `fun main() {\n    val seq = listOf(1, 2, 3).asSequence()\n    println(seq.toList())  // [1, 2, 3]\n    println(seq.toList())  // [1, 2, 3] - safe because backed by list\n}`,
      hints: ['Sequences from lists can be iterated multiple times.', 'Sequences from iterators can only be iterated once.', 'This is actually safe because asSequence from a list is reusable.'],
      concepts: ['asSequence'],
    },
    {
      id: 'kt-seq-16',
      title: 'Write a Sieve of Eratosthenes',
      type: 'write-function',
      difficulty: 'advanced',
      language: 'kotlin',
      goal: 'Write a function primes(): Sequence<Int> that generates prime numbers lazily.',
      skeleton: `fun primes(): Sequence<Int> {\n    // generate primes lazily\n}`,
      solution: `fun primes(): Sequence<Int> = sequence {\n    var numbers = generateSequence(2) { it + 1 }\n    while (true) {\n        val prime = numbers.first()\n        yield(prime)\n        numbers = numbers.drop(1).filter { it % prime != 0 }\n    }\n}`,
      hints: ['Start with 2, 3, 4, 5, ...', 'Take the first number as prime.', 'Filter out its multiples.'],
      concepts: ['sequence-builder', 'generateSequence'],
    },
    {
      id: 'kt-seq-17',
      title: 'Refactor to Sequence',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor list operations to sequence for better performance with large data.',
      skeleton: `fun processLargeData(data: List<String>): String {\n    return data\n        .filter { it.isNotBlank() }\n        .map { it.trim() }\n        .map { it.lowercase() }\n        .first { it.length > 5 }\n}`,
      solution: `fun processLargeData(data: List<String>): String {\n    return data.asSequence()\n        .filter { it.isNotBlank() }\n        .map { it.trim() }\n        .map { it.lowercase() }\n        .first { it.length > 5 }\n}`,
      hints: ['Add asSequence() to process lazily.', 'first() is a terminal operation.', 'Sequence avoids intermediate collections.'],
      concepts: ['asSequence', 'lazy-evaluation'],
    },
    {
      id: 'kt-seq-18',
      title: 'Refactor While Loop to Sequence',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor a while loop to use generateSequence.',
      skeleton: `fun powersOfTwo(max: Int): List<Int> {\n    val result = mutableListOf<Int>()\n    var n = 1\n    while (n <= max) {\n        result.add(n)\n        n *= 2\n    }\n    return result\n}`,
      solution: `fun powersOfTwo(max: Int): List<Int> {\n    return generateSequence(1) { it * 2 }\n        .takeWhile { it <= max }\n        .toList()\n}`,
      hints: ['generateSequence replaces the while loop.', 'takeWhile replaces the condition.', 'generateSequence(1) { it * 2 }.takeWhile { it <= max }'],
      concepts: ['generateSequence', 'takeWhile'],
    },
    {
      id: 'kt-seq-19',
      title: 'Write a Flatten Sequence',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function flattenSequences(seqs: List<Sequence<Int>>): Sequence<Int> that lazily flattens multiple sequences.',
      skeleton: `fun flattenSequences(seqs: List<Sequence<Int>>): Sequence<Int> {\n    // flatten lazily\n}`,
      solution: `fun flattenSequences(seqs: List<Sequence<Int>>): Sequence<Int> {\n    return seqs.asSequence().flatMap { it }\n}`,
      hints: ['asSequence the list, then flatMap.', 'flatMap flattens nested sequences.', 'seqs.asSequence().flatMap { it }'],
      concepts: ['flatMap', 'asSequence'],
    },
    {
      id: 'kt-seq-20',
      title: 'Predict Sequence Take',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict how many elements are computed with take.',
      skeleton: `fun main() {\n    var count = 0\n    val result = generateSequence(1) { it + 1 }\n        .map { count++; it * it }\n        .take(3)\n        .toList()\n    println(result)\n    println("Computed: \$count")\n}`,
      solution: `[1, 4, 9]\nComputed: 3`,
      hints: ['take(3) only computes 3 elements.', '1*1=1, 2*2=4, 3*3=9.', '[1, 4, 9] with count 3.'],
      concepts: ['lazy-evaluation'],
    },
  ],
};
