import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-lambda',
  title: '20. Lambdas',
  explanation: `## Lambdas in Kotlin\n\nLambdas are anonymous functions that can be passed as values:\n\n\`\`\`kotlin\nval double = { x: Int -> x * 2 }\nprintln(double(5))  // 10\n\`\`\`\n\n**Lambda syntax:**\n- \`{ parameters -> body }\`\n- **it** — implicit name when there is a single parameter\n- Last expression is the return value\n\n\`\`\`kotlin\nval names = listOf("Alice", "Bob")\nnames.filter { it.length > 3 }  // it = implicit single param\n\`\`\`\n\n**Higher-order functions** accept functions as parameters:\n\n\`\`\`kotlin\nfun operate(a: Int, b: Int, op: (Int, Int) -> Int): Int = op(a, b)\noperate(3, 4) { x, y -> x + y }  // 7\n\`\`\`\n\n**Closures** — lambdas capture variables from their scope:\n\n\`\`\`kotlin\nvar sum = 0\nlistOf(1, 2, 3).forEach { sum += it }  // sum = 6\n\`\`\`\n\n**Trailing lambda:** when the last parameter is a function, you can put the lambda outside the parentheses.`,
  exercises: [
    {
      id: 'kt-lambda-1',
      title: 'Basic Lambda',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Assign a lambda to a variable.',
      skeleton: `fun main() {\n    val greet = { name: String ___ "Hello, \$name!" }\n    println(greet("Kotlin"))\n}`,
      solution: `fun main() {\n    val greet = { name: String -> "Hello, \$name!" }\n    println(greet("Kotlin"))\n}`,
      hints: ['Lambdas use -> to separate params from body.', '{ param: Type -> body }', '->'],
      concepts: ['lambda'],
    },
    {
      id: 'kt-lambda-2',
      title: 'Lambda with It',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use the implicit it parameter in a lambda.',
      skeleton: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    val evens = nums.filter { ___ % 2 == 0 }\n    println(evens)\n}`,
      solution: `fun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    val evens = nums.filter { it % 2 == 0 }\n    println(evens)\n}`,
      hints: ['Single-parameter lambdas can use it.', 'it refers to the current element.', 'it'],
      concepts: ['it-parameter'],
    },
    {
      id: 'kt-lambda-3',
      title: 'Trailing Lambda Syntax',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use trailing lambda syntax with a higher-order function.',
      skeleton: `fun repeat(times: Int, action: (Int) -> Unit) {\n    for (i in 0 until times) action(i)\n}\n\nfun main() {\n    repeat(3) ___ println("Step \$it") ___\n}`,
      solution: `fun repeat(times: Int, action: (Int) -> Unit) {\n    for (i in 0 until times) action(i)\n}\n\nfun main() {\n    repeat(3) { println("Step \$it") }\n}`,
      hints: ['When the last param is a lambda, put it outside parens.', 'repeat(3) { ... }', '{ println("Step $it") }'],
      concepts: ['trailing-lambda'],
    },
    {
      id: 'kt-lambda-4',
      title: 'Predict Lambda Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of a lambda used with map.',
      skeleton: `fun main() {\n    val result = listOf("a", "bb", "ccc")\n        .map { it.length }\n    println(result)\n}`,
      solution: `[1, 2, 3]`,
      hints: ['map transforms each string to its length.', '"a" -> 1, "bb" -> 2, "ccc" -> 3.', '[1, 2, 3]'],
      concepts: ['lambda', 'map'],
    },
    {
      id: 'kt-lambda-5',
      title: 'Higher-Order Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a function that takes a function parameter.',
      skeleton: `fun applyOp(a: Int, b: Int, op: (Int, Int) ___ Int): Int = op(a, b)\n\nfun main() {\n    println(applyOp(3, 4) { x, y -> x + y })\n}`,
      solution: `fun applyOp(a: Int, b: Int, op: (Int, Int) -> Int): Int = op(a, b)\n\nfun main() {\n    println(applyOp(3, 4) { x, y -> x + y })\n}`,
      hints: ['Function types use (ParamTypes) -> ReturnType.', '(Int, Int) -> Int', '->'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-6',
      title: 'Fix Lambda Return Type',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the lambda that accidentally returns Unit.',
      skeleton: `fun main() {\n    val transform: (String) -> String = { s ->\n        println("Transforming \$s")\n    }\n    println(transform("hello"))\n}`,
      solution: `fun main() {\n    val transform: (String) -> String = { s ->\n        println("Transforming \$s")\n        s.uppercase()\n    }\n    println(transform("hello"))\n}`,
      hints: ['The last expression in a lambda is its return value.', 'println returns Unit, not String.', 'Add s.uppercase() as the last expression.'],
      concepts: ['lambda'],
    },
    {
      id: 'kt-lambda-7',
      title: 'Write a Custom forEach',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function myForEach(list: List<Int>, action: (Int) -> Unit) that applies action to each element.',
      skeleton: `fun myForEach(list: List<Int>, action: (Int) -> Unit) {\n    // apply action to each element\n}`,
      solution: `fun myForEach(list: List<Int>, action: (Int) -> Unit) {\n    for (item in list) {\n        action(item)\n    }\n}`,
      hints: ['Loop through the list.', 'Call action(item) for each element.', 'for (item in list) action(item)'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-8',
      title: 'Write a Compose Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function compose(f: (Int) -> Int, g: (Int) -> Int): (Int) -> Int that returns f(g(x)).',
      skeleton: `fun compose(f: (Int) -> Int, g: (Int) -> Int): (Int) -> Int {\n    // return composed function\n}`,
      solution: `fun compose(f: (Int) -> Int, g: (Int) -> Int): (Int) -> Int {\n    return { x -> f(g(x)) }\n}`,
      hints: ['Return a new lambda.', '{ x -> f(g(x)) }', 'Apply g first, then f.'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-9',
      title: 'Predict Closure Capture',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when a lambda captures a mutable variable.',
      skeleton: `fun main() {\n    var counter = 0\n    val increment = { counter++ }\n    increment()\n    increment()\n    increment()\n    println(counter)\n}`,
      solution: `3`,
      hints: ['The lambda captures the counter variable.', 'Each call increments counter.', 'counter = 3'],
      concepts: ['closures'],
    },
    {
      id: 'kt-lambda-10',
      title: 'Fix Lambda Scope Issue',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the lambda that shadows a variable name.',
      skeleton: `fun main() {\n    val items = listOf("apple", "banana", "cherry")\n    val result = items.map { items -> items.uppercase() }\n    println(result)\n}`,
      solution: `fun main() {\n    val items = listOf("apple", "banana", "cherry")\n    val result = items.map { it.uppercase() }\n    println(result)\n}`,
      hints: ['The lambda parameter shadows the outer items variable.', 'Use it for single parameter lambdas.', 'it.uppercase()'],
      concepts: ['lambda'],
    },
    {
      id: 'kt-lambda-11',
      title: 'Write a Filter Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function myFilter(list: List<Int>, predicate: (Int) -> Boolean): List<Int>.',
      skeleton: `fun myFilter(list: List<Int>, predicate: (Int) -> Boolean): List<Int> {\n    // implement filter\n}`,
      solution: `fun myFilter(list: List<Int>, predicate: (Int) -> Boolean): List<Int> {\n    val result = mutableListOf<Int>()\n    for (item in list) {\n        if (predicate(item)) result.add(item)\n    }\n    return result\n}`,
      hints: ['Test each element with the predicate.', 'Add to result if predicate returns true.', 'if (predicate(item)) result.add(item)'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-12',
      title: 'Predict Reduce Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of reduce with a lambda.',
      skeleton: `fun main() {\n    val result = listOf(1, 2, 3, 4).reduce { acc, n -> acc * n }\n    println(result)\n}`,
      solution: `24`,
      hints: ['reduce: 1*2=2, 2*3=6, 6*4=24.', 'Starts with first element as accumulator.', '24'],
      concepts: ['reduce'],
    },
    {
      id: 'kt-lambda-13',
      title: 'Write a Counter Factory',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function makeCounter(): () -> Int that returns a lambda that counts up from 0.',
      skeleton: `fun makeCounter(): () -> Int {\n    // return a counting lambda (closure)\n}`,
      solution: `fun makeCounter(): () -> Int {\n    var count = 0\n    return { count++ }\n}`,
      hints: ['The lambda captures count as a closure.', 'Each call returns current value and increments.', 'var count = 0; return { count++ }'],
      concepts: ['closures'],
    },
    {
      id: 'kt-lambda-14',
      title: 'Fix Type Mismatch in Lambda',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the lambda type annotation to match the expected signature.',
      skeleton: `fun transform(input: String, fn: (String) -> Int): Int = fn(input)\n\nfun main() {\n    val result = transform("hello") { it.uppercase() }\n    println(result)\n}`,
      solution: `fun transform(input: String, fn: (String) -> String): String = fn(input)\n\nfun main() {\n    val result = transform("hello") { it.uppercase() }\n    println(result)\n}`,
      hints: ['uppercase() returns String, not Int.', 'Change the function type to (String) -> String.', 'fn: (String) -> String'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-15',
      title: 'Write a Pipeline Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function pipeline(value: Int, vararg ops: (Int) -> Int): Int that applies all operations in sequence.',
      skeleton: `fun pipeline(value: Int, vararg ops: (Int) -> Int): Int {\n    // apply all operations\n}`,
      solution: `fun pipeline(value: Int, vararg ops: (Int) -> Int): Int {\n    var result = value\n    for (op in ops) {\n        result = op(result)\n    }\n    return result\n}`,
      hints: ['Loop through each operation.', 'Apply each to the running result.', 'result = op(result)'],
      concepts: ['higher-order-functions', 'vararg'],
    },
    {
      id: 'kt-lambda-16',
      title: 'Write a Map with Index',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function indexedMap(list: List<String>, transform: (Int, String) -> String): List<String> that passes index and value.',
      skeleton: `fun indexedMap(list: List<String>, transform: (Int, String) -> String): List<String> {\n    // map with index\n}`,
      solution: `fun indexedMap(list: List<String>, transform: (Int, String) -> String): List<String> {\n    return list.mapIndexed { index, value -> transform(index, value) }\n}`,
      hints: ['mapIndexed gives both index and value.', 'Call transform(index, value).', 'list.mapIndexed { i, v -> transform(i, v) }'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-17',
      title: 'Refactor Anonymous Class to Lambda',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the anonymous object to a lambda.',
      skeleton: `fun main() {\n    val comparator = object : Comparator<String> {\n        override fun compare(a: String, b: String): Int {\n            return a.length - b.length\n        }\n    }\n    val sorted = listOf("cherry", "fig", "banana").sortedWith(comparator)\n    println(sorted)\n}`,
      solution: `fun main() {\n    val sorted = listOf("cherry", "fig", "banana").sortedWith(compareBy { it.length })\n    println(sorted)\n}`,
      hints: ['Replace anonymous class with a lambda.', 'compareBy { it.length } creates a Comparator.', 'Much more concise.'],
      concepts: ['lambda'],
    },
    {
      id: 'kt-lambda-18',
      title: 'Refactor to Higher-Order Function',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor duplicate code into a higher-order function.',
      skeleton: `fun processUsers(users: List<String>): List<String> {\n    val result = mutableListOf<String>()\n    for (u in users) {\n        if (u.isNotBlank()) result.add(u.trim().lowercase())\n    }\n    return result\n}\n\nfun processEmails(emails: List<String>): List<String> {\n    val result = mutableListOf<String>()\n    for (e in emails) {\n        if (e.isNotBlank()) result.add(e.trim().lowercase())\n    }\n    return result\n}`,
      solution: `fun cleanStrings(items: List<String>): List<String> {\n    return items.filter { it.isNotBlank() }.map { it.trim().lowercase() }\n}`,
      hints: ['Both functions do the same thing.', 'Extract to a single function.', 'filter + map replaces the manual loop.'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-19',
      title: 'Write a Retry Function',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function retry(times: Int, block: () -> Boolean): Boolean that calls block up to times until it returns true.',
      skeleton: `fun retry(times: Int, block: () -> Boolean): Boolean {\n    // retry up to times\n}`,
      solution: `fun retry(times: Int, block: () -> Boolean): Boolean {\n    for (i in 1..times) {\n        if (block()) return true\n    }\n    return false\n}`,
      hints: ['Call block() in a loop.', 'Return true as soon as block succeeds.', 'Return false if all attempts fail.'],
      concepts: ['higher-order-functions'],
    },
    {
      id: 'kt-lambda-20',
      title: 'Predict Lambda with Return',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the behavior of return inside a lambda.',
      skeleton: `fun findFirst(list: List<Int>, predicate: (Int) -> Boolean): Int? {\n    list.forEach {\n        if (predicate(it)) return it\n    }\n    return null\n}\n\nfun main() {\n    val result = findFirst(listOf(1, 2, 3, 4)) { it > 2 }\n    println(result)\n}`,
      solution: `3`,
      hints: ['return inside forEach returns from findFirst (non-local return).', 'First element > 2 is 3.', '3'],
      concepts: ['non-local-return'],
    },
  ],
};
