import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-scope',
  title: '21. Scope Functions',
  explanation: `## Scope Functions in Kotlin\n\nScope functions execute a block of code in the context of an object:\n\n| Function | Object ref | Return value | Use case |\n|----------|-----------|-------------|----------|\n| **let** | it | Lambda result | Null checks, transformations |\n| **run** | this | Lambda result | Object config + compute |\n| **with** | this | Lambda result | Grouping calls on an object |\n| **apply** | this | Object itself | Object configuration |\n| **also** | it | Object itself | Side effects |\n\n\`\`\`kotlin\n// let - transform or null-check\nval len = "hello"?.let { it.length }  // 5\n\n// apply - configure an object\nval person = Person().apply {\n    name = "Alice"\n    age = 30\n}\n\n// also - side effects\nval list = mutableListOf(1, 2).also { println(it) }\n\n// run - compute with this\nval greeting = "World".run { "Hello, \$this!" }\n\n// with - group operations\nval result = with(StringBuilder()) {\n    append("Hello")\n    append(" World")\n    toString()\n}\n\`\`\`\n\n**takeIf / takeUnless** - conditional returns:\n\n\`\`\`kotlin\nval positive = number.takeIf { it > 0 }  // number or null\n\`\`\``,
  exercises: [
    {
      id: 'kt-scope-1',
      title: 'Let for Null Check',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use let for a null-safe operation.',
      skeleton: `fun main() {\n    val name: String? = "Kotlin"\n    name?.___ { println("Length: \${it.length}") }\n}`,
      solution: `fun main() {\n    val name: String? = "Kotlin"\n    name?.let { println("Length: \${it.length}") }\n}`,
      hints: ['let executes the block if non-null.', 'Inside let, the value is it.', 'let'],
      concepts: ['let'],
    },
    {
      id: 'kt-scope-2',
      title: 'Apply for Configuration',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use apply to configure an object.',
      skeleton: `data class Config(var host: String = "", var port: Int = 0)\n\nfun main() {\n    val config = Config().___ {\n        host = "localhost"\n        port = 8080\n    }\n    println(config)\n}`,
      solution: `data class Config(var host: String = "", var port: Int = 0)\n\nfun main() {\n    val config = Config().apply {\n        host = "localhost"\n        port = 8080\n    }\n    println(config)\n}`,
      hints: ['apply configures an object and returns it.', 'Inside apply, this refers to the object.', 'apply'],
      concepts: ['apply'],
    },
    {
      id: 'kt-scope-3',
      title: 'Also for Side Effects',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use also for logging a side effect.',
      skeleton: `fun main() {\n    val numbers = mutableListOf(1, 2, 3)\n        .___ { println("Initial: \$it") }\n    numbers.add(4)\n    println(numbers)\n}`,
      solution: `fun main() {\n    val numbers = mutableListOf(1, 2, 3)\n        .also { println("Initial: \$it") }\n    numbers.add(4)\n    println(numbers)\n}`,
      hints: ['also performs a side effect and returns the object.', 'Inside also, the object is it.', 'also'],
      concepts: ['also'],
    },
    {
      id: 'kt-scope-4',
      title: 'Predict Let Output',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the return value of let.',
      skeleton: `fun main() {\n    val result = "Hello".let {\n        println(it)\n        it.length\n    }\n    println(result)\n}`,
      solution: `Hello\n5`,
      hints: ['let returns the last expression.', 'println prints "Hello", then it.length = 5.', 'Hello then 5'],
      concepts: ['let'],
    },
    {
      id: 'kt-scope-5',
      title: 'Run for Computation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use run to compute a value.',
      skeleton: `fun main() {\n    val greeting = "World".___ {\n        "Hello, \$this!"\n    }\n    println(greeting)\n}`,
      solution: `fun main() {\n    val greeting = "World".run {\n        "Hello, \$this!"\n    }\n    println(greeting)\n}`,
      hints: ['run computes a result with this as context.', 'Returns the lambda result.', 'run'],
      concepts: ['run'],
    },
    {
      id: 'kt-scope-6',
      title: 'With for Grouping',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use with to group operations on an object.',
      skeleton: `fun main() {\n    val result = ___(StringBuilder()) {\n        append("Hello")\n        append(" ")\n        append("World")\n        toString()\n    }\n    println(result)\n}`,
      solution: `fun main() {\n    val result = with(StringBuilder()) {\n        append("Hello")\n        append(" ")\n        append("World")\n        toString()\n    }\n    println(result)\n}`,
      hints: ['with takes the object as a parameter.', 'Inside the block, this is the StringBuilder.', 'with'],
      concepts: ['with'],
    },
    {
      id: 'kt-scope-7',
      title: 'Fix Apply vs Let',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code that uses apply but needs the lambda result (should use let).',
      skeleton: `fun main() {\n    val len = "Hello".apply { length }\n    println(len)  // prints "Hello" not 5!\n}`,
      solution: `fun main() {\n    val len = "Hello".let { it.length }\n    println(len)\n}`,
      hints: ['apply returns the object itself, not the lambda result.', 'let returns the lambda result.', 'Use let for transformations.'],
      concepts: ['let', 'apply'],
    },
    {
      id: 'kt-scope-8',
      title: 'Write a Builder with Apply',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that creates and configures an object using apply.',
      skeleton: `data class Email(var to: String = "", var subject: String = "", var body: String = "")\n\nfun createEmail(): Email {\n    // use apply to build\n}`,
      solution: `data class Email(var to: String = "", var subject: String = "", var body: String = "")\n\nfun createEmail(): Email {\n    return Email().apply {\n        to = "user@example.com"\n        subject = "Hello"\n        body = "Welcome!"\n    }\n}`,
      hints: ['apply configures and returns the object.', 'Email().apply { to = ...; subject = ... }', 'Properties accessed via this.'],
      concepts: ['apply'],
    },
    {
      id: 'kt-scope-9',
      title: 'Predict Also Chain',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of chained also calls.',
      skeleton: `fun main() {\n    val result = 42\n        .also { print("a:\$it ") }\n        .also { print("b:\$it ") }\n    println(result)\n}`,
      solution: `a:42 b:42 42`,
      hints: ['also returns the object unchanged.', 'Both also blocks see 42.', 'a:42 b:42 42'],
      concepts: ['also'],
    },
    {
      id: 'kt-scope-10',
      title: 'Fix Also vs Apply',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code where also tries to access properties without this.',
      skeleton: `data class User(var name: String = "", var age: Int = 0)\n\nfun main() {\n    val user = User().also {\n        name = "Alice"\n        age = 30\n    }\n    println(user)\n}`,
      solution: `data class User(var name: String = "", var age: Int = 0)\n\nfun main() {\n    val user = User().apply {\n        name = "Alice"\n        age = 30\n    }\n    println(user)\n}`,
      hints: ['also uses it, not this.', 'apply uses this, allowing direct property access.', 'Change also to apply.'],
      concepts: ['apply', 'also'],
    },
    {
      id: 'kt-scope-11',
      title: 'TakeIf',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function positiveOrNull(n: Int): Int? using takeIf.',
      skeleton: `fun positiveOrNull(n: Int): Int? {\n    // return n if positive, else null\n}`,
      solution: `fun positiveOrNull(n: Int): Int? {\n    return n.takeIf { it > 0 }\n}`,
      hints: ['takeIf returns the value if predicate is true, null otherwise.', 'n.takeIf { it > 0 }', 'Returns Int? since it might be null.'],
      concepts: ['takeIf'],
    },
    {
      id: 'kt-scope-12',
      title: 'TakeUnless',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function nonBlankOrNull(s: String): String? using takeUnless.',
      skeleton: `fun nonBlankOrNull(s: String): String? {\n    // return s unless it is blank\n}`,
      solution: `fun nonBlankOrNull(s: String): String? {\n    return s.takeUnless { it.isBlank() }\n}`,
      hints: ['takeUnless returns null if predicate is true.', 's.takeUnless { it.isBlank() }', 'Opposite of takeIf.'],
      concepts: ['takeUnless'],
    },
    {
      id: 'kt-scope-13',
      title: 'Predict Run Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of run as an extension function.',
      skeleton: `fun main() {\n    val result = "Kotlin".run {\n        val upper = uppercase()\n        "\$upper has \$length chars"\n    }\n    println(result)\n}`,
      solution: `KOTLIN has 6 chars`,
      hints: ['Inside run, this is "Kotlin".', 'uppercase() returns "KOTLIN", length is 6.', 'KOTLIN has 6 chars'],
      concepts: ['run'],
    },
    {
      id: 'kt-scope-14',
      title: 'Write a Chain of Scope Functions',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that creates a list, logs it, adds elements, and returns the size using scope function chaining.',
      skeleton: `fun buildAndCount(): Int {\n    // use also + apply + let chain\n}`,
      solution: `fun buildAndCount(): Int {\n    return mutableListOf<String>()\n        .apply {\n            add("a")\n            add("b")\n            add("c")\n        }\n        .also { println("Built: \$it") }\n        .let { it.size }\n}`,
      hints: ['apply to configure, also for logging, let for transformation.', 'Chain: apply -> also -> let', 'apply returns the list, also returns the list, let returns size.'],
      concepts: ['apply', 'also', 'let'],
    },
    {
      id: 'kt-scope-15',
      title: 'Fix Run vs With',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code that uses with on a nullable object.',
      skeleton: `fun describe(name: String?): String {\n    return with(name) {\n        "Name: \$this, Length: \$length"\n    }\n}`,
      solution: `fun describe(name: String?): String {\n    return name?.run {\n        "Name: \$this, Length: \$length"\n    } ?: "No name"\n}`,
      hints: ['with does not handle null safely.', 'Use ?.run for null-safe scope.', 'name?.run { ... } ?: "No name"'],
      concepts: ['run'],
    },
    {
      id: 'kt-scope-16',
      title: 'Write Scope Function Selection',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that demonstrates using the correct scope function for each situation.',
      skeleton: `data class Request(var url: String = "", var method: String = "GET", var headers: MutableMap<String, String> = mutableMapOf())\n\nfun buildRequest(): Request {\n    // use apply to configure\n}`,
      solution: `data class Request(var url: String = "", var method: String = "GET", var headers: MutableMap<String, String> = mutableMapOf())\n\nfun buildRequest(): Request {\n    return Request().apply {\n        url = "https://api.example.com"\n        method = "POST"\n        headers["Content-Type"] = "application/json"\n    }\n}`,
      hints: ['apply is ideal for object configuration.', 'this inside apply refers to Request.', 'Returns the configured Request.'],
      concepts: ['apply'],
    },
    {
      id: 'kt-scope-17',
      title: 'Refactor to Let',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the null check to use let.',
      skeleton: `fun printName(name: String?) {\n    if (name != null) {\n        val upper = name.uppercase()\n        println("Name: \$upper")\n    }\n}`,
      solution: `fun printName(name: String?) {\n    name?.let {\n        val upper = it.uppercase()\n        println("Name: \$upper")\n    }\n}`,
      hints: ['let replaces the manual null check.', 'name?.let { ... } only runs if non-null.', 'it refers to the non-null name.'],
      concepts: ['let'],
    },
    {
      id: 'kt-scope-18',
      title: 'Refactor to Apply',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor object initialization to use apply.',
      skeleton: `data class Person(var name: String = "", var age: Int = 0, var email: String = "")\n\nfun createPerson(): Person {\n    val p = Person()\n    p.name = "Alice"\n    p.age = 30\n    p.email = "alice@example.com"\n    return p\n}`,
      solution: `data class Person(var name: String = "", var age: Int = 0, var email: String = "")\n\nfun createPerson(): Person {\n    return Person().apply {\n        name = "Alice"\n        age = 30\n        email = "alice@example.com"\n    }\n}`,
      hints: ['apply replaces repetitive p.property = value calls.', 'Inside apply, this is the Person.', 'Person().apply { name = ...; age = ... }'],
      concepts: ['apply'],
    },
    {
      id: 'kt-scope-19',
      title: 'Write a TakeIf Chain',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function validEmail(email: String): String? that returns the email only if it contains @ and is not blank.',
      skeleton: `fun validEmail(email: String): String? {\n    // use takeIf for validation\n}`,
      solution: `fun validEmail(email: String): String? {\n    return email\n        .takeIf { it.isNotBlank() }\n        ?.takeIf { "@" in it }\n}`,
      hints: ['Chain takeIf calls.', 'First check not blank, then check @.', 'email.takeIf { ... }?.takeIf { ... }'],
      concepts: ['takeIf'],
    },
    {
      id: 'kt-scope-20',
      title: 'Predict With Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of with on a list.',
      skeleton: `fun main() {\n    val info = with(listOf("a", "b", "c")) {\n        "Size: \$size, First: \${first()}, Last: \${last()}"\n    }\n    println(info)\n}`,
      solution: `Size: 3, First: a, Last: c`,
      hints: ['with receives the list as this.', 'size=3, first()=a, last()=c.', 'Size: 3, First: a, Last: c'],
      concepts: ['with'],
    },
  ],
};
