import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-ext',
  title: '22. Extensions',
  explanation: `## Extension Functions in Kotlin\n\nExtension functions add new functions to existing classes without modifying them:\n\n\`\`\`kotlin\nfun String.isPalindrome(): Boolean = this == this.reversed()\n\n"racecar".isPalindrome()  // true\n"hello".isPalindrome()    // false\n\`\`\`\n\n**Extension properties:**\n\n\`\`\`kotlin\nval String.wordCount: Int\n    get() = this.split("\\\\s+".toRegex()).size\n\n"Hello World".wordCount  // 2\n\`\`\`\n\n**Key points:**\n- Extensions are resolved statically (at compile time)\n- They cannot access private members of the class\n- If a member and an extension have the same signature, the member wins\n\n**Nullable receiver:**\n\n\`\`\`kotlin\nfun String?.orEmpty(): String = this ?: ""\n\`\`\`\n\nExtensions are a powerful way to add utility functions without inheritance.`,
  exercises: [
    {
      id: 'kt-ext-1',
      title: 'Basic Extension Function',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write an extension function on Int.',
      skeleton: `fun Int.___(): Boolean = this % 2 == 0\n\nfun main() {\n    println(4.isEven())\n    println(3.isEven())\n}`,
      solution: `fun Int.isEven(): Boolean = this % 2 == 0\n\nfun main() {\n    println(4.isEven())\n    println(3.isEven())\n}`,
      hints: ['Extension functions use ReceiverType.name() syntax.', 'this refers to the receiver.', 'isEven'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-2',
      title: 'Extension on String',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write an extension function that adds exclamation marks.',
      skeleton: `fun String.___(n: Int): String = this + "!".repeat(n)\n\nfun main() {\n    println("Hello".exclaim(3))\n}`,
      solution: `fun String.exclaim(n: Int): String = this + "!".repeat(n)\n\nfun main() {\n    println("Hello".exclaim(3))\n}`,
      hints: ['Extension function on String.', 'this is the String receiver.', 'exclaim'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-3',
      title: 'Extension Property',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add an extension property to List.',
      skeleton: `val List<Int>.average: Double\n    ___() = if (isEmpty()) 0.0 else sum().toDouble() / size\n\nfun main() {\n    println(listOf(1, 2, 3, 4).average)\n}`,
      solution: `val List<Int>.average: Double\n    get() = if (isEmpty()) 0.0 else sum().toDouble() / size\n\nfun main() {\n    println(listOf(1, 2, 3, 4).average)\n}`,
      hints: ['Extension properties need a custom getter.', 'get() = expression', 'get()'],
      concepts: ['extension-properties'],
    },
    {
      id: 'kt-ext-4',
      title: 'Predict Extension Resolution',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict whether a member or extension function is called.',
      skeleton: `class MyClass {\n    fun greet() = "Member"\n}\n\nfun MyClass.greet() = "Extension"\n\nfun main() {\n    println(MyClass().greet())\n}`,
      solution: `Member`,
      hints: ['When member and extension have the same signature, member wins.', 'Extensions are resolved statically.', 'Member'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-5',
      title: 'Nullable Receiver Extension',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function with a nullable receiver.',
      skeleton: `fun String___.orDefault(default: String): String = this ___ default\n\nfun main() {\n    val name: String? = null\n    println(name.orDefault("Unknown"))\n}`,
      solution: `fun String?.orDefault(default: String): String = this ?: default\n\nfun main() {\n    val name: String? = null\n    println(name.orDefault("Unknown"))\n}`,
      hints: ['String? is a nullable receiver.', 'this can be null inside the extension.', 'this ?: default'],
      concepts: ['nullable-receiver'],
    },
    {
      id: 'kt-ext-6',
      title: 'Fix Extension Cannot Access Private',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the extension that tries to access a private member.',
      skeleton: `class Wallet {\n    private var balance: Double = 100.0\n    fun getBalance() = balance\n}\n\nfun Wallet.isRich(): Boolean = balance > 1000  // Error: private`,
      solution: `class Wallet {\n    private var balance: Double = 100.0\n    fun getBalance() = balance\n}\n\nfun Wallet.isRich(): Boolean = getBalance() > 1000`,
      hints: ['Extensions cannot access private members.', 'Use the public getter instead.', 'getBalance() > 1000'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-7',
      title: 'Write a String Extension',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write an extension function String.initials(): String that returns the first letter of each word.',
      skeleton: `// Define String.initials() extension`,
      solution: `fun String.initials(): String {\n    return this.split(" ")\n        .filter { it.isNotBlank() }\n        .map { it[0].uppercase() }\n        .joinToString("")\n}`,
      hints: ['Split by space, take first char of each word.', 'Map to uppercase first char.', 'Join into a single string.'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-8',
      title: 'Write a List Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function List<Int>.median(): Double that returns the median value.',
      skeleton: `fun List<Int>.median(): Double {\n    // return median\n}`,
      solution: `fun List<Int>.median(): Double {\n    val sorted = this.sorted()\n    val mid = sorted.size / 2\n    return if (sorted.size % 2 == 0) {\n        (sorted[mid - 1] + sorted[mid]) / 2.0\n    } else {\n        sorted[mid].toDouble()\n    }\n}`,
      hints: ['Sort first, then find the middle.', 'Even size: average two middle elements.', 'Odd size: return the middle element.'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-9',
      title: 'Predict Nullable Extension',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of a nullable receiver extension.',
      skeleton: `fun Any?.toSafeString(): String = this?.toString() ?: "null"\n\nfun main() {\n    println(42.toSafeString())\n    println(null.toSafeString())\n}`,
      solution: `42\nnull`,
      hints: ['42.toString() returns "42".', 'null?.toString() returns null, Elvis gives "null".', '42 and null'],
      concepts: ['nullable-receiver'],
    },
    {
      id: 'kt-ext-10',
      title: 'Fix Extension Shadowed by Import',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the naming conflict where the extension shadows a common function name.',
      skeleton: `fun List<Int>.sum(): Int = fold(0) { acc, n -> acc + n }  // shadows stdlib sum()\n\nfun main() {\n    println(listOf(1, 2, 3).sum())\n}`,
      solution: `fun List<Int>.total(): Int = fold(0) { acc, n -> acc + n }\n\nfun main() {\n    println(listOf(1, 2, 3).total())\n}`,
      hints: ['Naming extension same as stdlib function causes confusion.', 'Rename to avoid shadowing.', 'total() instead of sum()'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-11',
      title: 'Write a Generic Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a generic extension function T.applyIf(condition: Boolean, block: T.() -> T): T.',
      skeleton: `// Define applyIf extension`,
      solution: `fun <T> T.applyIf(condition: Boolean, block: T.() -> T): T {\n    return if (condition) block() else this\n}`,
      hints: ['Generic extension on T.', 'Run block only if condition is true.', 'Return this if condition is false.'],
      concepts: ['extension-functions', 'generics'],
    },
    {
      id: 'kt-ext-12',
      title: 'Predict Extension Static Resolution',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when extension is resolved statically.',
      skeleton: `open class Base\nclass Derived : Base()\n\nfun Base.name() = "Base"\nfun Derived.name() = "Derived"\n\nfun printName(b: Base) {\n    println(b.name())\n}\n\nfun main() {\n    printName(Derived())\n}`,
      solution: `Base`,
      hints: ['Extensions are resolved based on the declared type.', 'b is declared as Base, so Base.name() is called.', 'Base (static dispatch, not runtime).'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-13',
      title: 'Write Extension for Map',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function Map<String, Int>.prettyPrint() that prints each entry on a line.',
      skeleton: `fun Map<String, Int>.prettyPrint() {\n    // print each entry\n}`,
      solution: `fun Map<String, Int>.prettyPrint() {\n    for ((key, value) in this) {\n        println("\$key: \$value")\n    }\n}`,
      hints: ['this refers to the Map receiver.', 'Iterate over entries.', 'for ((key, value) in this)'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-14',
      title: 'Write an Infix Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an infix extension function Int.power(exp: Int): Int.',
      skeleton: `// Define infix extension`,
      solution: `infix fun Int.power(exp: Int): Int {\n    var result = 1\n    for (i in 1..exp) result *= this\n    return result\n}\n\n// Usage: 2 power 10`,
      hints: ['infix allows calling without dot and parens.', 'infix fun Int.power(exp: Int)', '2 power 10 = 1024'],
      concepts: ['extension-functions', 'infix'],
    },
    {
      id: 'kt-ext-15',
      title: 'Fix Mutable Extension',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the extension that tries to mutate an immutable list.',
      skeleton: `fun List<Int>.addAndReturn(item: Int): List<Int> {\n    add(item)  // Error: List is immutable\n    return this\n}`,
      solution: `fun List<Int>.addAndReturn(item: Int): List<Int> {\n    return this + item\n}`,
      hints: ['List is immutable; cannot call add.', 'Use + operator to create a new list.', 'this + item returns a new list.'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-16',
      title: 'Write a Scope Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function String.whenNotBlank(block: (String) -> Unit) that runs block only when the string is not blank.',
      skeleton: `fun String.whenNotBlank(block: (String) -> Unit) {\n    // run block if not blank\n}`,
      solution: `fun String.whenNotBlank(block: (String) -> Unit) {\n    if (this.isNotBlank()) block(this)\n}`,
      hints: ['Check isNotBlank() before calling block.', 'Pass this to the block.', 'if (this.isNotBlank()) block(this)'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-17',
      title: 'Refactor Utility to Extension',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor a utility function to an extension function.',
      skeleton: `fun capitalizeWords(text: String): String {\n    return text.split(" ").joinToString(" ") {\n        it.replaceFirstChar { c -> c.uppercase() }\n    }\n}`,
      solution: `fun String.capitalizeWords(): String {\n    return this.split(" ").joinToString(" ") {\n        it.replaceFirstChar { c -> c.uppercase() }\n    }\n}`,
      hints: ['Move the String parameter to the receiver.', 'fun String.capitalizeWords()', 'Replace text with this.'],
      concepts: ['extension-functions'],
    },
    {
      id: 'kt-ext-18',
      title: 'Refactor to Extension Property',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor a getter function to an extension property.',
      skeleton: `fun getLastChar(s: String): Char = s[s.length - 1]\n\nfun main() {\n    println(getLastChar("Hello"))\n}`,
      solution: `val String.lastChar: Char\n    get() = this[this.length - 1]\n\nfun main() {\n    println("Hello".lastChar)\n}`,
      hints: ['Extension properties use val/var with get().', 'val String.lastChar: Char get() = ...', 'Access as property: "Hello".lastChar'],
      concepts: ['extension-properties'],
    },
    {
      id: 'kt-ext-19',
      title: 'Write a Builder Extension',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write an extension function MutableList<T>.addAllIf(condition: Boolean, items: Collection<T>).',
      skeleton: `fun <T> MutableList<T>.addAllIf(condition: Boolean, items: Collection<T>) {\n    // add items only if condition is true\n}`,
      solution: `fun <T> MutableList<T>.addAllIf(condition: Boolean, items: Collection<T>) {\n    if (condition) addAll(items)\n}`,
      hints: ['Simple conditional delegation.', 'if (condition) addAll(items)', 'Generic extension on MutableList<T>.'],
      concepts: ['extension-functions', 'generics'],
    },
    {
      id: 'kt-ext-20',
      title: 'Predict Extension Property',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of an extension property.',
      skeleton: `val String.vowelCount: Int\n    get() = count { it.lowercaseChar() in "aeiou" }\n\nfun main() {\n    println("Hello World".vowelCount)\n}`,
      solution: `3`,
      hints: ['Count vowels in "Hello World".', 'e, o, o = 3 vowels.', '3'],
      concepts: ['extension-properties'],
    },
  ],
};
