import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-delegate',
  title: '23. Delegation',
  explanation: `## Delegation in Kotlin\n\nDelegation implements the delegation pattern with first-class language support:\n\n**Class delegation** — delegate interface implementation:\n\n\`\`\`kotlin\ninterface Printer {\n    fun print(msg: String)\n}\nclass ConsolePrinter : Printer {\n    override fun print(msg: String) = println(msg)\n}\nclass LoggingPrinter(p: Printer) : Printer by p\n\`\`\`\n\n**Property delegation** with built-in delegates:\n\n\`\`\`kotlin\n// lazy — computed on first access\nval data: String by lazy { expensiveComputation() }\n\n// observable — callback on change\nvar name: String by Delegates.observable("") { _, old, new ->\n    println("\$old -> \$new")\n}\n\n// map — store properties in a map\nclass User(map: Map<String, Any?>) {\n    val name: String by map\n    val age: Int by map\n}\n\`\`\`\n\n**Custom delegates** implement \`getValue\` and optionally \`setValue\`.`,
  exercises: [
    {
      id: 'kt-delegate-1',
      title: 'Lazy Property',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Declare a lazy property.',
      skeleton: `val data: String by ___ {\n    println("Computing...")\n    "Hello, World!"\n}`,
      solution: `val data: String by lazy {\n    println("Computing...")\n    "Hello, World!"\n}`,
      hints: ['lazy computes the value on first access.', 'Subsequent accesses return the cached value.', 'lazy'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-2',
      title: 'Class Delegation',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Delegate interface implementation using by.',
      skeleton: `interface Greeter {\n    fun greet(): String\n}\n\nclass DefaultGreeter : Greeter {\n    override fun greet() = "Hello!"\n}\n\nclass CustomGreeter(g: Greeter) : Greeter ___ g`,
      solution: `interface Greeter {\n    fun greet(): String\n}\n\nclass DefaultGreeter : Greeter {\n    override fun greet() = "Hello!"\n}\n\nclass CustomGreeter(g: Greeter) : Greeter by g`,
      hints: ['by keyword delegates all interface methods.', 'Greeter by g forwards calls to g.', 'by'],
      concepts: ['class-delegation'],
    },
    {
      id: 'kt-delegate-3',
      title: 'Observable Property',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use Delegates.observable to track changes.',
      skeleton: `import kotlin.properties.Delegates\n\nvar name: String by Delegates.___(\"initial\") { _, old, new ->\n    println("\$old -> \$new")\n}`,
      solution: `import kotlin.properties.Delegates\n\nvar name: String by Delegates.observable(\"initial\") { _, old, new ->\n    println("\$old -> \$new")\n}`,
      hints: ['observable fires callback on every change.', 'Delegates.observable(initialValue) { ... }', 'observable'],
      concepts: ['observable'],
    },
    {
      id: 'kt-delegate-4',
      title: 'Predict Lazy Initialization',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict when a lazy property is initialized.',
      skeleton: `val greeting: String by lazy {\n    println("Initializing")\n    "Hello"\n}\n\nfun main() {\n    println("Before")\n    println(greeting)\n    println(greeting)\n}`,
      solution: `Before\nInitializing\nHello\nHello`,
      hints: ['lazy initializes on first access.', '"Initializing" prints once.', 'Second access uses cached value.'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-5',
      title: 'Map Delegation',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Delegate properties to a map.',
      skeleton: `class User(map: Map<String, Any?>) {\n    val name: String ___ map\n    val age: Int ___ map\n}`,
      solution: `class User(map: Map<String, Any?>) {\n    val name: String by map\n    val age: Int by map\n}`,
      hints: ['by map delegates property access to the map.', 'Property name must match map key.', 'by'],
      concepts: ['map-delegation'],
    },
    {
      id: 'kt-delegate-6',
      title: 'Fix Lazy Thread Safety',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the lazy initialization to not use synchronization when not needed.',
      skeleton: `// In a single-threaded context, synchronized lazy is unnecessary overhead\nval cache: Map<String, String> by lazy(LazyThreadSafetyMode.SYNCHRONIZED) {\n    mapOf("key" to "value")\n}`,
      solution: `// In a single-threaded context, use NONE for better performance\nval cache: Map<String, String> by lazy(LazyThreadSafetyMode.NONE) {\n    mapOf("key" to "value")\n}`,
      hints: ['SYNCHRONIZED is the default but adds overhead.', 'Use NONE when thread safety is not needed.', 'LazyThreadSafetyMode.NONE'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-7',
      title: 'Write a Custom Delegate',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a custom property delegate that trims strings on set.',
      skeleton: `import kotlin.reflect.KProperty\n\n// Write TrimDelegate class`,
      solution: `import kotlin.reflect.KProperty\n\nclass TrimDelegate(private var value: String = "") {\n    operator fun getValue(thisRef: Any?, property: KProperty<*>): String = value\n    operator fun setValue(thisRef: Any?, property: KProperty<*>, newValue: String) {\n        value = newValue.trim()\n    }\n}`,
      hints: ['Implement getValue and setValue operators.', 'Trim in setValue.', 'operator fun getValue/setValue'],
      concepts: ['custom-delegate'],
    },
    {
      id: 'kt-delegate-8',
      title: 'Write a Delegation Override',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class that delegates interface implementation but overrides one method.',
      skeleton: `interface Logger {\n    fun info(msg: String)\n    fun error(msg: String)\n}\n\n// DefaultLogger + TimestampLogger that overrides info but delegates error`,
      solution: `interface Logger {\n    fun info(msg: String)\n    fun error(msg: String)\n}\n\nclass DefaultLogger : Logger {\n    override fun info(msg: String) = println("[INFO] \$msg")\n    override fun error(msg: String) = println("[ERROR] \$msg")\n}\n\nclass TimestampLogger(logger: Logger) : Logger by logger {\n    override fun info(msg: String) = println("[INFO \${System.currentTimeMillis()}] \$msg")\n}`,
      hints: ['Delegate with by, then override specific methods.', 'error is delegated, info is overridden.', 'class TimestampLogger(l: Logger) : Logger by l { override fun info(...) }'],
      concepts: ['class-delegation'],
    },
    {
      id: 'kt-delegate-9',
      title: 'Predict Observable Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of observable property changes.',
      skeleton: `import kotlin.properties.Delegates\n\nvar score: Int by Delegates.observable(0) { _, old, new ->\n    println("\$old -> \$new")\n}\n\nfun main() {\n    score = 10\n    score = 20\n}`,
      solution: `0 -> 10\n10 -> 20`,
      hints: ['observable fires on every set.', 'First: 0 -> 10, Second: 10 -> 20.', '0 -> 10 then 10 -> 20'],
      concepts: ['observable'],
    },
    {
      id: 'kt-delegate-10',
      title: 'Fix Map Delegation Key Mismatch',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the map delegation where property name does not match the map key.',
      skeleton: `class Config(map: Map<String, Any?>) {\n    val serverHost: String by map  // key is "server_host" in the map\n}\n\nfun main() {\n    val config = Config(mapOf("server_host" to "localhost"))\n    println(config.serverHost)  // NoSuchElementException!\n}`,
      solution: `class Config(private val map: Map<String, Any?>) {\n    val serverHost: String\n        get() = map["server_host"] as String\n}\n\nfun main() {\n    val config = Config(mapOf("server_host" to "localhost"))\n    println(config.serverHost)\n}`,
      hints: ['Map delegation uses the property name as key.', 'If the key differs, use a custom getter.', 'map["server_host"] as String'],
      concepts: ['map-delegation'],
    },
    {
      id: 'kt-delegate-11',
      title: 'Write a Vetoable Delegate',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use Delegates.vetoable to reject negative values.',
      skeleton: `import kotlin.properties.Delegates\n\n// Declare a vetoable property that rejects negative values`,
      solution: `import kotlin.properties.Delegates\n\nvar positiveOnly: Int by Delegates.vetoable(0) { _, _, new ->\n    new >= 0\n}`,
      hints: ['vetoable can reject changes by returning false.', 'Return true to accept, false to reject.', 'Delegates.vetoable(0) { _, _, new -> new >= 0 }'],
      concepts: ['vetoable'],
    },
    {
      id: 'kt-delegate-12',
      title: 'Predict Vetoable Output',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict which assignments are accepted by vetoable.',
      skeleton: `import kotlin.properties.Delegates\n\nvar age: Int by Delegates.vetoable(0) { _, _, new -> new in 0..150 }\n\nfun main() {\n    age = 25\n    println(age)\n    age = 200\n    println(age)\n    age = 30\n    println(age)\n}`,
      solution: `25\n25\n30`,
      hints: ['25 is accepted (0..150).', '200 is rejected (>150), age stays 25.', '30 is accepted.'],
      concepts: ['vetoable'],
    },
    {
      id: 'kt-delegate-13',
      title: 'Write a Logging Delegate',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a custom delegate that logs every get and set.',
      skeleton: `import kotlin.reflect.KProperty\n\n// Write LoggingDelegate`,
      solution: `import kotlin.reflect.KProperty\n\nclass LoggingDelegate<T>(private var value: T) {\n    operator fun getValue(thisRef: Any?, property: KProperty<*>): T {\n        println("Getting \${property.name}: \$value")\n        return value\n    }\n    operator fun setValue(thisRef: Any?, property: KProperty<*>, newValue: T) {\n        println("Setting \${property.name}: \$value -> \$newValue")\n        value = newValue\n    }\n}`,
      hints: ['Log in both getValue and setValue.', 'property.name gives the property name.', 'Generic T for any type.'],
      concepts: ['custom-delegate'],
    },
    {
      id: 'kt-delegate-14',
      title: 'Write Lazy with Custom Init',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a class that uses lazy for expensive initialization of multiple properties.',
      skeleton: `class Database {\n    // lazy properties for connection and schema\n}`,
      solution: `class Database {\n    val connection: String by lazy {\n        println("Connecting...")\n        "jdbc:sqlite:app.db"\n    }\n\n    val schema: List<String> by lazy {\n        println("Loading schema...")\n        listOf("users", "orders", "products")\n    }\n}`,
      hints: ['Each lazy property initializes independently.', 'Initialization happens on first access.', 'by lazy { ... }'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-15',
      title: 'Fix Delegate in Data Class',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix: delegated properties cannot be in data class primary constructor.',
      skeleton: `data class Config(\n    val name: String by lazy { "default" },\n    val port: Int = 8080\n)`,
      solution: `data class Config(\n    val name: String = "default",\n    val port: Int = 8080\n)`,
      hints: ['Delegated properties cannot be in primary constructor of data class.', 'Use a default value instead of lazy.', 'val name: String = "default"'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-16',
      title: 'Write a Caching Delegate',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a custom delegate that caches a value with a TTL (time-to-live), recomputing if expired.',
      skeleton: `import kotlin.reflect.KProperty\n\n// Write CachingDelegate with TTL`,
      solution: `import kotlin.reflect.KProperty\n\nclass CachingDelegate<T>(private val ttlMs: Long, private val compute: () -> T) {\n    private var value: T? = null\n    private var lastComputed: Long = 0\n\n    operator fun getValue(thisRef: Any?, property: KProperty<*>): T {\n        val now = System.currentTimeMillis()\n        if (value == null || now - lastComputed > ttlMs) {\n            value = compute()\n            lastComputed = now\n        }\n        return value!!\n    }\n}`,
      hints: ['Track the last computation time.', 'Recompute if TTL has expired.', 'getValue checks time and recomputes if needed.'],
      concepts: ['custom-delegate'],
    },
    {
      id: 'kt-delegate-17',
      title: 'Refactor to Lazy',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor the nullable + manual initialization to lazy.',
      skeleton: `class Service {\n    private var _client: HttpClient? = null\n    val client: HttpClient\n        get() {\n            if (_client == null) {\n                _client = HttpClient()\n            }\n            return _client!!\n        }\n}\n\nclass HttpClient`,
      solution: `class Service {\n    val client: HttpClient by lazy { HttpClient() }\n}\n\nclass HttpClient`,
      hints: ['lazy replaces the manual null-check pattern.', 'by lazy { HttpClient() }', 'Thread-safe by default.'],
      concepts: ['lazy'],
    },
    {
      id: 'kt-delegate-18',
      title: 'Refactor to Class Delegation',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor manual delegation to use by keyword.',
      skeleton: `interface Repository {\n    fun findAll(): List<String>\n    fun save(item: String)\n}\n\nclass CachedRepository(private val delegate: Repository) : Repository {\n    override fun findAll() = delegate.findAll()\n    override fun save(item: String) = delegate.save(item)\n}`,
      solution: `interface Repository {\n    fun findAll(): List<String>\n    fun save(item: String)\n}\n\nclass CachedRepository(delegate: Repository) : Repository by delegate`,
      hints: ['by delegate replaces manual forwarding.', 'All methods are forwarded automatically.', 'Repository by delegate'],
      concepts: ['class-delegation'],
    },
    {
      id: 'kt-delegate-19',
      title: 'Write a NotNull Delegate',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use Delegates.notNull for a property that must be set before first access.',
      skeleton: `import kotlin.properties.Delegates\n\nclass App {\n    // databaseUrl must be set before use\n}`,
      solution: `import kotlin.properties.Delegates\n\nclass App {\n    var databaseUrl: String by Delegates.notNull()\n\n    fun connect() {\n        println("Connecting to \$databaseUrl")\n    }\n}`,
      hints: ['notNull throws if accessed before set.', 'Like lateinit but works with delegates.', 'Delegates.notNull<String>()'],
      concepts: ['notNull'],
    },
    {
      id: 'kt-delegate-20',
      title: 'Predict Map Delegation',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of map-delegated properties.',
      skeleton: `class Config(map: Map<String, Any?>) {\n    val name: String by map\n    val version: Int by map\n}\n\nfun main() {\n    val config = Config(mapOf("name" to "MyApp", "version" to 2))\n    println(config.name)\n    println(config.version)\n}`,
      solution: `MyApp\n2`,
      hints: ['name reads map["name"] = "MyApp".', 'version reads map["version"] = 2.', 'MyApp and 2'],
      concepts: ['map-delegation'],
    },
  ],
};
