import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-except',
  title: '24. Exceptions',
  explanation: `## Exceptions in Kotlin\n\nKotlin uses **unchecked exceptions** only - no checked exceptions:\n\n\`\`\`kotlin\nfun divide(a: Int, b: Int): Int {\n    if (b == 0) throw IllegalArgumentException("Cannot divide by zero")\n    return a / b\n}\n\`\`\`\n\n**try/catch/finally:**\n\n\`\`\`kotlin\ntry {\n    val result = riskyOperation()\n} catch (e: IOException) {\n    println("IO error: \${e.message}")\n} catch (e: Exception) {\n    println("Error: \${e.message}")\n} finally {\n    cleanup()\n}\n\`\`\`\n\n**try as an expression:**\n\n\`\`\`kotlin\nval number = try { input.toInt() } catch (e: NumberFormatException) { 0 }\n\`\`\`\n\n**Nothing type** - functions that never return:\n\n\`\`\`kotlin\nfun fail(msg: String): Nothing = throw IllegalStateException(msg)\n\`\`\`\n\n**use** - auto-close resources (like try-with-resources):\n\n\`\`\`kotlin\nFileReader("file.txt").use { reader -> reader.readText() }\n\`\`\``,
  exercises: [
    {
      id: 'kt-except-1',
      title: 'Throw an Exception',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Throw an exception when a condition is met.',
      skeleton: `fun requirePositive(n: Int): Int {\n    if (n <= 0) ___ IllegalArgumentException("Must be positive")\n    return n\n}`,
      solution: `fun requirePositive(n: Int): Int {\n    if (n <= 0) throw IllegalArgumentException("Must be positive")\n    return n\n}`,
      hints: ['Use throw to raise an exception.', 'throw ExceptionType("message")', 'throw'],
      concepts: ['throw'],
    },
    {
      id: 'kt-except-2',
      title: 'Try-Catch Block',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Catch a NumberFormatException.',
      skeleton: `fun parseInt(s: String): Int {\n    return ___ {\n        s.toInt()\n    } ___ (e: NumberFormatException) {\n        0\n    }\n}`,
      solution: `fun parseInt(s: String): Int {\n    return try {\n        s.toInt()\n    } catch (e: NumberFormatException) {\n        0\n    }\n}`,
      hints: ['try/catch can be used as an expression.', 'try { ... } catch (e: Type) { ... }', 'try, catch'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-3',
      title: 'Finally Block',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Add a finally block that always executes.',
      skeleton: `fun riskyOp() {\n    try {\n        println("Trying")\n        throw RuntimeException("Oops")\n    } catch (e: RuntimeException) {\n        println("Caught: \${e.message}")\n    } ___ {\n        println("Always runs")\n    }\n}`,
      solution: `fun riskyOp() {\n    try {\n        println("Trying")\n        throw RuntimeException("Oops")\n    } catch (e: RuntimeException) {\n        println("Caught: \${e.message}")\n    } finally {\n        println("Always runs")\n    }\n}`,
      hints: ['finally always executes after try/catch.', 'Used for cleanup code.', 'finally'],
      concepts: ['finally'],
    },
    {
      id: 'kt-except-4',
      title: 'Predict Try Expression',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of try as an expression.',
      skeleton: `fun main() {\n    val a = try { "123".toInt() } catch (e: Exception) { -1 }\n    val b = try { "abc".toInt() } catch (e: Exception) { -1 }\n    println("\$a \$b")\n}`,
      solution: `123 -1`,
      hints: ['"123".toInt() succeeds with 123.', '"abc".toInt() throws, caught returns -1.', '123 -1'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-5',
      title: 'Nothing Return Type',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that always throws using Nothing return type.',
      skeleton: `fun fail(message: String): ___ {\n    throw IllegalStateException(message)\n}`,
      solution: `fun fail(message: String): Nothing {\n    throw IllegalStateException(message)\n}`,
      hints: ['Nothing indicates a function never returns.', 'Always throws an exception.', 'Nothing'],
      concepts: ['nothing-type'],
    },
    {
      id: 'kt-except-6',
      title: 'Fix Swallowed Exception',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the catch block that silently swallows the exception.',
      skeleton: `fun loadConfig(path: String): String {\n    return try {\n        readFile(path)\n    } catch (e: Exception) {\n        ""  // silently returns empty string\n    }\n}\n\nfun readFile(path: String): String = throw RuntimeException("File not found")`,
      solution: `fun loadConfig(path: String): String {\n    return try {\n        readFile(path)\n    } catch (e: Exception) {\n        println("Error loading config: \${e.message}")\n        throw e\n    }\n}\n\nfun readFile(path: String): String = throw RuntimeException("File not found")`,
      hints: ['Silently swallowing exceptions hides bugs.', 'Log the error and rethrow or return a meaningful default.', 'println + throw e'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-7',
      title: 'Write a Safe Division',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function safeDivide(a: Int, b: Int): Int? that returns null instead of throwing on division by zero.',
      skeleton: `fun safeDivide(a: Int, b: Int): Int? {\n    // return null on error\n}`,
      solution: `fun safeDivide(a: Int, b: Int): Int? {\n    return try {\n        a / b\n    } catch (e: ArithmeticException) {\n        null\n    }\n}`,
      hints: ['Division by zero throws ArithmeticException.', 'Catch and return null.', 'try { a / b } catch (e: ArithmeticException) { null }'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-8',
      title: 'Write a Require/Check Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Write a function that validates input using require and check.',
      skeleton: `fun createAccount(name: String, balance: Double): String {\n    // require name not blank, check balance >= 0\n}`,
      solution: `fun createAccount(name: String, balance: Double): String {\n    require(name.isNotBlank()) { "Name must not be blank" }\n    check(balance >= 0) { "Balance must be non-negative" }\n    return "Account(\$name, \$balance)"\n}`,
      hints: ['require throws IllegalArgumentException.', 'check throws IllegalStateException.', 'require for arguments, check for state.'],
      concepts: ['require', 'check'],
    },
    {
      id: 'kt-except-9',
      title: 'Predict Finally Execution',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict whether finally runs even when catch rethrows.',
      skeleton: `fun test(): String {\n    try {\n        throw RuntimeException("error")\n    } catch (e: Exception) {\n        println("caught")\n        return "from catch"\n    } finally {\n        println("finally")\n    }\n}\n\nfun main() {\n    println(test())\n}`,
      solution: `caught\nfinally\nfrom catch`,
      hints: ['finally always runs, even when returning from catch.', 'catch runs first, then finally, then return.', 'caught, finally, from catch'],
      concepts: ['finally'],
    },
    {
      id: 'kt-except-10',
      title: 'Fix Multiple Catch Order',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the catch order so specific exceptions are caught first.',
      skeleton: `fun handle(input: String): String {\n    return try {\n        input.toInt().toString()\n    } catch (e: Exception) {\n        "General error"\n    } catch (e: NumberFormatException) {\n        "Not a number"  // Never reached!\n    }\n}`,
      solution: `fun handle(input: String): String {\n    return try {\n        input.toInt().toString()\n    } catch (e: NumberFormatException) {\n        "Not a number"\n    } catch (e: Exception) {\n        "General error"\n    }\n}`,
      hints: ['More specific exceptions must come first.', 'Exception catches everything before NumberFormatException.', 'Put NumberFormatException before Exception.'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-11',
      title: 'Write a Result Wrapper',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function runCatching(block: () -> String): Result<String> using Kotlin built-in runCatching.',
      skeleton: `fun safeExecute(block: () -> String): Result<String> {\n    // use runCatching\n}`,
      solution: `fun safeExecute(block: () -> String): Result<String> {\n    return runCatching { block() }\n}`,
      hints: ['runCatching wraps the result or exception.', 'Returns Result<T>.', 'runCatching { block() }'],
      concepts: ['runCatching'],
    },
    {
      id: 'kt-except-12',
      title: 'Predict RunCatching',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of runCatching.',
      skeleton: `fun main() {\n    val success = runCatching { 42 / 2 }\n    val failure = runCatching { 42 / 0 }\n    println(success.getOrDefault(-1))\n    println(failure.getOrDefault(-1))\n}`,
      solution: `21\n-1`,
      hints: ['42 / 2 = 21, succeeds.', '42 / 0 throws, getOrDefault returns -1.', '21 and -1'],
      concepts: ['runCatching'],
    },
    {
      id: 'kt-except-13',
      title: 'Write a Custom Exception',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a custom exception class and throw it.',
      skeleton: `// Define ValidationException and a validate function`,
      solution: `class ValidationException(message: String) : Exception(message)\n\nfun validateAge(age: Int): Int {\n    if (age < 0 || age > 150) throw ValidationException("Invalid age: \$age")\n    return age\n}`,
      hints: ['Extend Exception for custom exceptions.', 'class MyException(msg: String) : Exception(msg)', 'Throw with throw ValidationException(...)'],
      concepts: ['custom-exception'],
    },
    {
      id: 'kt-except-14',
      title: 'Write Use for Resource',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that uses the use extension for auto-closing a resource.',
      skeleton: `class MyResource : AutoCloseable {\n    fun read() = "data"\n    override fun close() = println("Closed")\n}\n\nfun readData(): String {\n    // use the resource with auto-close\n}`,
      solution: `class MyResource : AutoCloseable {\n    fun read() = "data"\n    override fun close() = println("Closed")\n}\n\nfun readData(): String {\n    return MyResource().use { it.read() }\n}`,
      hints: ['use auto-closes after the block.', 'resource.use { it.method() }', 'Like try-with-resources in Java.'],
      concepts: ['use'],
    },
    {
      id: 'kt-except-15',
      title: 'Fix Error Function Usage',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code to use the error() function instead of manual throw.',
      skeleton: `fun getConfig(key: String): String {\n    val configs = mapOf("host" to "localhost")\n    val value = configs[key]\n    if (value == null) {\n        throw IllegalStateException("Config key not found: \$key")\n    }\n    return value\n}`,
      solution: `fun getConfig(key: String): String {\n    val configs = mapOf("host" to "localhost")\n    return configs[key] ?: error("Config key not found: \$key")\n}`,
      hints: ['error() is a stdlib shortcut for throw IllegalStateException.', 'Combine with Elvis operator.', 'configs[key] ?: error("...")'],
      concepts: ['error'],
    },
    {
      id: 'kt-except-16',
      title: 'Write an Exception Chain',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that catches an exception and wraps it in a new one with a cause.',
      skeleton: `fun processData(data: String): Int {\n    // wrap NumberFormatException in a RuntimeException\n}`,
      solution: `fun processData(data: String): Int {\n    return try {\n        data.toInt()\n    } catch (e: NumberFormatException) {\n        throw RuntimeException("Failed to process: \$data", e)\n    }\n}`,
      hints: ['Pass the original exception as cause.', 'RuntimeException("msg", originalException)', 'Exception chaining preserves the stack trace.'],
      concepts: ['exception-chaining'],
    },
    {
      id: 'kt-except-17',
      title: 'Refactor to Require',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor manual validation to use require.',
      skeleton: `fun setAge(age: Int) {\n    if (age < 0) {\n        throw IllegalArgumentException("Age cannot be negative")\n    }\n    if (age > 150) {\n        throw IllegalArgumentException("Age cannot exceed 150")\n    }\n    println("Age set to \$age")\n}`,
      solution: `fun setAge(age: Int) {\n    require(age in 0..150) { "Age must be between 0 and 150, got \$age" }\n    println("Age set to \$age")\n}`,
      hints: ['require throws IllegalArgumentException if false.', 'Combine both checks into one.', 'require(age in 0..150) { "message" }'],
      concepts: ['require'],
    },
    {
      id: 'kt-except-18',
      title: 'Refactor to RunCatching',
      type: 'refactor',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Refactor try/catch to use runCatching.',
      skeleton: `fun parseNumber(s: String): Int? {\n    return try {\n        s.toInt()\n    } catch (e: NumberFormatException) {\n        null\n    }\n}`,
      solution: `fun parseNumber(s: String): Int? {\n    return runCatching { s.toInt() }.getOrNull()\n}`,
      hints: ['runCatching wraps the operation.', 'getOrNull returns null on failure.', 'runCatching { s.toInt() }.getOrNull()'],
      concepts: ['runCatching'],
    },
    {
      id: 'kt-except-19',
      title: 'Write a Retry with Exception',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function retryOnException(times: Int, block: () -> String): String that retries the block on exception up to times.',
      skeleton: `fun retryOnException(times: Int, block: () -> String): String {\n    // retry on exception\n}`,
      solution: `fun retryOnException(times: Int, block: () -> String): String {\n    var lastException: Exception? = null\n    for (i in 1..times) {\n        try {\n            return block()\n        } catch (e: Exception) {\n            lastException = e\n        }\n    }\n    throw lastException ?: IllegalStateException("No attempts made")\n}`,
      hints: ['Loop up to times, catching exceptions.', 'Return on first success.', 'Throw the last exception if all attempts fail.'],
      concepts: ['try-catch'],
    },
    {
      id: 'kt-except-20',
      title: 'Predict Nothing in Elvis',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output when Nothing is used with Elvis operator.',
      skeleton: `fun fail(): Nothing = throw RuntimeException("Failed")\n\nfun main() {\n    val name: String? = "Kotlin"\n    val result = name ?: fail()\n    println(result)\n    \n    val empty: String? = null\n    try {\n        val r2 = empty ?: fail()\n    } catch (e: RuntimeException) {\n        println(e.message)\n    }\n}`,
      solution: `Kotlin\nFailed`,
      hints: ['name is non-null, so fail() is not called.', 'empty is null, so fail() throws.', 'Kotlin then Failed'],
      concepts: ['nothing-type'],
    },
  ],
};
