import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-typesys',
  title: '25. Type System',
  explanation: `## Kotlin Type System\n\n**Smart casts** — Kotlin automatically casts after a type check:\n\n\`\`\`kotlin\nfun describe(obj: Any): String = when (obj) {\n    is String -> "String of length \${obj.length}"\n    is Int -> "Int: \${obj + 1}"\n    else -> "Unknown"\n}\n\`\`\`\n\n**Type checks:**\n- \`is\` — checks if a value is a type\n- \`!is\` — checks if NOT a type\n\n**Casts:**\n- \`as\` — unsafe cast (throws ClassCastException)\n- \`as?\` — safe cast (returns null on failure)\n\n\`\`\`kotlin\nval x: Any = "hello"\nval s: String = x as String    // unsafe cast\nval n: Int? = x as? Int         // null (safe cast)\n\`\`\`\n\n**Type aliases:**\n\n\`\`\`kotlin\ntypealias StringMap = Map<String, String>\ntypealias Predicate<T> = (T) -> Boolean\n\`\`\`\n\n**Type hierarchy:** Any is the root, Nothing is the bottom (subtype of all types), Unit is the void equivalent.`,
  exercises: [
    {
      id: 'kt-typesys-1',
      title: 'Is Type Check',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Check if a value is a specific type.',
      skeleton: `fun isString(value: Any): Boolean = value ___ String`,
      solution: `fun isString(value: Any): Boolean = value is String`,
      hints: ['is checks the type at runtime.', 'value is Type returns Boolean.', 'is'],
      concepts: ['is-check'],
    },
    {
      id: 'kt-typesys-2',
      title: 'Smart Cast',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use smart cast after an is check.',
      skeleton: `fun stringLength(obj: Any): Int {\n    if (obj ___ String) {\n        return obj.length  // smart cast to String\n    }\n    return -1\n}`,
      solution: `fun stringLength(obj: Any): Int {\n    if (obj is String) {\n        return obj.length  // smart cast to String\n    }\n    return -1\n}`,
      hints: ['After is check, Kotlin smart casts automatically.', 'obj is treated as String inside the if.', 'is'],
      concepts: ['smart-cast'],
    },
    {
      id: 'kt-typesys-3',
      title: 'Safe Cast',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Use a safe cast that returns null on failure.',
      skeleton: `fun toIntOrNull(value: Any): Int? = value ___ Int`,
      solution: `fun toIntOrNull(value: Any): Int? = value as? Int`,
      hints: ['as? returns null instead of throwing.', 'Safe cast operator.', 'as?'],
      concepts: ['safe-cast'],
    },
    {
      id: 'kt-typesys-4',
      title: 'Predict Smart Cast in When',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of smart casts in a when expression.',
      skeleton: `fun describe(obj: Any): String = when (obj) {\n    is String -> "String: \$obj"\n    is Int -> "Int: \${obj * 2}"\n    is Boolean -> "Bool: \${!obj}"\n    else -> "Other"\n}\n\nfun main() {\n    println(describe("hi"))\n    println(describe(5))\n    println(describe(true))\n}`,
      solution: `String: hi\nInt: 10\nBool: false`,
      hints: ['"hi" is String, obj is smart cast.', '5 is Int, 5 * 2 = 10.', 'true is Boolean, !true = false.'],
      concepts: ['smart-cast', 'when-expression'],
    },
    {
      id: 'kt-typesys-5',
      title: 'Unsafe Cast',
      type: 'fill-blank',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Use an unsafe cast (throws if wrong type).',
      skeleton: `fun forceString(value: Any): String = value ___ String`,
      solution: `fun forceString(value: Any): String = value as String`,
      hints: ['as performs an unsafe cast.', 'Throws ClassCastException if wrong type.', 'as'],
      concepts: ['unsafe-cast'],
    },
    {
      id: 'kt-typesys-6',
      title: 'Fix Unsafe Cast Crash',
      type: 'fix-bug',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Fix the unsafe cast that crashes at runtime.',
      skeleton: `fun getLength(value: Any): Int {\n    val s = value as String\n    return s.length\n}\n\nfun main() {\n    println(getLength(42))  // ClassCastException!\n}`,
      solution: `fun getLength(value: Any): Int {\n    val s = value as? String\n    return s?.length ?: -1\n}\n\nfun main() {\n    println(getLength(42))\n}`,
      hints: ['Use as? for safe casting.', 'as? returns null on failure.', 'value as? String, then ?.length ?: -1'],
      concepts: ['safe-cast'],
    },
    {
      id: 'kt-typesys-7',
      title: 'Type Alias',
      type: 'fill-blank',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create a type alias for a complex type.',
      skeleton: `___ UserMap = Map<String, List<String>>\n\nfun getUsers(): UserMap = mapOf("admin" to listOf("Alice", "Bob"))`,
      solution: `typealias UserMap = Map<String, List<String>>\n\nfun getUsers(): UserMap = mapOf("admin" to listOf("Alice", "Bob"))`,
      hints: ['typealias creates a new name for a type.', 'typealias Name = ExistingType', 'typealias'],
      concepts: ['type-alias'],
    },
    {
      id: 'kt-typesys-8',
      title: 'Write a Type-Safe Dispatcher',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function process(value: Any): String using when with is checks.',
      skeleton: `fun process(value: Any): String {\n    // handle String, Int, List<*>, and else\n}`,
      solution: `fun process(value: Any): String = when (value) {\n    is String -> "String(\${value.length})"\n    is Int -> "Int(\${value * 2})"\n    is List<*> -> "List(size=\${value.size})"\n    else -> "Unknown(\${value::class.simpleName})"\n}`,
      hints: ['Use when with is for type dispatch.', 'Smart cast gives access to type-specific members.', 'List<*> uses star projection.'],
      concepts: ['smart-cast', 'when-expression'],
    },
    {
      id: 'kt-typesys-9',
      title: 'Predict Safe Cast',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of safe and unsafe casts.',
      skeleton: `fun main() {\n    val x: Any = "hello"\n    val s: String? = x as? String\n    val n: Int? = x as? Int\n    println(s)\n    println(n)\n}`,
      solution: `hello\nnull`,
      hints: ['x is a String, so as? String succeeds.', 'x is not an Int, so as? Int returns null.', 'hello and null'],
      concepts: ['safe-cast'],
    },
    {
      id: 'kt-typesys-10',
      title: 'Fix Smart Cast with Mutable Variable',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the code where smart cast fails because the variable is mutable.',
      skeleton: `fun printLength(obj: Any) {\n    var value = obj\n    if (value is String) {\n        println(value.length)  // Smart cast might fail with var\n    }\n}`,
      solution: `fun printLength(obj: Any) {\n    val value = obj\n    if (value is String) {\n        println(value.length)\n    }\n}`,
      hints: ['Smart casts may not work with var (could be reassigned).', 'Use val to ensure the value does not change.', 'Change var to val.'],
      concepts: ['smart-cast'],
    },
    {
      id: 'kt-typesys-11',
      title: 'Write a Type-Safe Converter',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function toStringOrDefault(value: Any?, default: String): String using safe cast.',
      skeleton: `fun toStringOrDefault(value: Any?, default: String): String {\n    // safe cast to String or use default\n}`,
      solution: `fun toStringOrDefault(value: Any?, default: String): String {\n    return (value as? String) ?: default\n}`,
      hints: ['Safe cast returns null if not String.', 'Elvis provides the default.', '(value as? String) ?: default'],
      concepts: ['safe-cast', 'elvis-operator'],
    },
    {
      id: 'kt-typesys-12',
      title: 'Predict Is Check',
      type: 'predict-output',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Predict the output of is and !is checks.',
      skeleton: `fun main() {\n    val x: Any = 42\n    println(x is Int)\n    println(x is String)\n    println(x !is Double)\n}`,
      solution: `true\nfalse\ntrue`,
      hints: ['42 is Int: true.', '42 is not String: false.', '42 is not Double: true.'],
      concepts: ['is-check'],
    },
    {
      id: 'kt-typesys-13',
      title: 'Write a Type Alias for Function',
      type: 'write-function',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Create type aliases for function types and use them.',
      skeleton: `// Define type aliases for function types`,
      solution: `typealias Predicate<T> = (T) -> Boolean\ntypealias Transform<T, R> = (T) -> R\n\nfun <T> filterWith(list: List<T>, predicate: Predicate<T>): List<T> {\n    return list.filter(predicate)\n}`,
      hints: ['typealias for function types improves readability.', 'typealias Predicate<T> = (T) -> Boolean', 'Use it just like the original type.'],
      concepts: ['type-alias'],
    },
    {
      id: 'kt-typesys-14',
      title: 'Write a Polymorphic Processor',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that processes a list of mixed types, summing numbers and concatenating strings.',
      skeleton: `fun processMixed(items: List<Any>): String {\n    // sum numbers, concatenate strings\n}`,
      solution: `fun processMixed(items: List<Any>): String {\n    var sum = 0\n    val strings = mutableListOf<String>()\n    for (item in items) {\n        when (item) {\n            is Int -> sum += item\n            is Double -> sum += item.toInt()\n            is String -> strings.add(item)\n        }\n    }\n    return "Sum=\$sum, Strings=\${strings.joinToString()}"\n}`,
      hints: ['Use when with is checks.', 'Smart cast gives access to type-specific operations.', 'Accumulate numbers and strings separately.'],
      concepts: ['smart-cast', 'when-expression'],
    },
    {
      id: 'kt-typesys-15',
      title: 'Fix ClassCastException',
      type: 'fix-bug',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Fix the function that uses an unsafe cast on a generic type.',
      skeleton: `fun <T> firstOrNull(list: List<Any>, type: Class<T>): T? {\n    for (item in list) {\n        return item as T  // Unsafe — unchecked cast\n    }\n    return null\n}`,
      solution: `fun <T> firstOrNull(list: List<Any>, type: Class<T>): T? {\n    for (item in list) {\n        if (type.isInstance(item)) {\n            @Suppress("UNCHECKED_CAST")\n            return item as T\n        }\n    }\n    return null\n}`,
      hints: ['Check the type before casting.', 'type.isInstance(item) checks at runtime.', 'Only cast after confirming the type.'],
      concepts: ['unsafe-cast'],
    },
    {
      id: 'kt-typesys-16',
      title: 'Write Any/Unit/Nothing Demo',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write functions demonstrating Any, Unit, and Nothing return types.',
      skeleton: `// Write three functions showing Any, Unit, Nothing`,
      solution: `fun anything(): Any = "could be anything"\n\nfun doWork(): Unit {\n    println("Working...")\n}\n\nfun impossible(): Nothing {\n    throw UnsupportedOperationException("Not possible")\n}`,
      hints: ['Any is the root type.', 'Unit is void (implicit return).', 'Nothing means the function never returns normally.'],
      concepts: ['any', 'unit', 'nothing-type'],
    },
    {
      id: 'kt-typesys-17',
      title: 'Refactor to Smart Cast',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor explicit casts to smart casts.',
      skeleton: `fun getInfo(obj: Any): String {\n    if (obj is String) {\n        return (obj as String).uppercase()\n    }\n    if (obj is Int) {\n        return (obj as Int).toString()\n    }\n    return "unknown"\n}`,
      solution: `fun getInfo(obj: Any): String = when (obj) {\n    is String -> obj.uppercase()\n    is Int -> obj.toString()\n    else -> "unknown"\n}`,
      hints: ['After is check, cast is automatic.', 'Remove explicit (obj as Type) casts.', 'Use when for cleaner code.'],
      concepts: ['smart-cast'],
    },
    {
      id: 'kt-typesys-18',
      title: 'Refactor to Type Alias',
      type: 'refactor',
      difficulty: 'beginner',
      language: 'kotlin',
      goal: 'Refactor complex type signatures to use type aliases.',
      skeleton: `fun processCallbacks(\n    onSuccess: (Map<String, List<String>>) -> Unit,\n    onError: (Map<String, List<String>>) -> Unit\n) {\n    // ...\n}`,
      solution: `typealias DataMap = Map<String, List<String>>\ntypealias Callback = (DataMap) -> Unit\n\nfun processCallbacks(onSuccess: Callback, onError: Callback) {\n    // ...\n}`,
      hints: ['Type aliases reduce repetition.', 'typealias DataMap = Map<String, List<String>>', 'Much more readable.'],
      concepts: ['type-alias'],
    },
    {
      id: 'kt-typesys-19',
      title: 'Write a Type-Safe Builder',
      type: 'write-function',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Write a function that builds different objects based on type parameter using reified.',
      skeleton: `// Write an inline reified factory function`,
      solution: `inline fun <reified T> defaultValue(): T = when (T::class) {\n    Int::class -> 0 as T\n    String::class -> "" as T\n    Boolean::class -> false as T\n    else -> throw IllegalArgumentException("Unsupported type: \${T::class}")\n}`,
      hints: ['reified allows accessing T::class at runtime.', 'Use when on T::class to determine the type.', 'inline fun <reified T> defaultValue(): T'],
      concepts: ['reified'],
    },
    {
      id: 'kt-typesys-20',
      title: 'Predict Type Hierarchy',
      type: 'predict-output',
      difficulty: 'intermediate',
      language: 'kotlin',
      goal: 'Predict the output of type checks across the type hierarchy.',
      skeleton: `fun main() {\n    val x: Int = 42\n    println(x is Any)\n    println(x is Number)\n    println(x is Comparable<*>)\n    val n: Nothing? = null\n    println(n is Any?)\n}`,
      solution: `true\ntrue\ntrue\ntrue`,
      hints: ['Int extends Number extends Any.', 'Int implements Comparable.', 'null is always Any? (nullable Any).'],
      concepts: ['type-hierarchy'],
    },
  ],
};
