import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-singleton',
  title: '42. Singleton',
  explanation: `## Singleton Pattern in Kotlin

Kotlin's \`object\` declaration is a first-class language feature for the Singleton pattern.

### object Declaration
\`\`\`kotlin
object Database {
    private val connections = mutableListOf<String>()
    fun connect(url: String) { connections.add(url) }
    fun getConnections() = connections.toList()
}
Database.connect("jdbc:h2:mem:test")
\`\`\`

### Lazy Initialization
\`\`\`kotlin
class HeavyService private constructor() {
    companion object {
        val instance: HeavyService by lazy { HeavyService() }
    }
}
\`\`\`

### Thread Safety
\`\`\`kotlin
object ThreadSafeRegistry {
    private val items = java.util.concurrent.ConcurrentHashMap<String, Any>()
    fun register(key: String, value: Any) { items[key] = value }
    fun get(key: String): Any? = items[key]
}
\`\`\`

### Dependency Injection Alternative
\`\`\`kotlin
interface Logger { fun log(msg: String) }
class ConsoleLogger : Logger { override fun log(msg: String) = println(msg) }

class App(private val logger: Logger) {
    fun run() { logger.log("Running") }
}
\`\`\``,
  exercises: [
    { id: 'kt-singleton-1', title: 'Object Singleton', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Create a singleton using object declaration.', skeleton: `___ AppConfig {\n    var appName = "MyApp"\n    var version = "1.0"\n    override fun toString() = "\${appName} v\${version}"\n}`, solution: `object AppConfig {\n    var appName = "MyApp"\n    var version = "1.0"\n    override fun toString() = "\${appName} v\${version}"\n}`, hints: ['object keyword creates a singleton.', 'Only one instance exists.', 'Accessed directly by name.'], concepts: ['object', 'singleton'] },
    { id: 'kt-singleton-2', title: 'Companion Object Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use companion object as a factory.', skeleton: `class Connection private constructor(val url: String) {\n    ___ ___ {\n        fun create(url: String) = Connection(url)\n    }\n}`, solution: `class Connection private constructor(val url: String) {\n    companion object {\n        fun create(url: String) = Connection(url)\n    }\n}`, hints: ['companion object holds static-like members.', 'Private constructor forces use of factory.', 'Called as Connection.create(url).'], concepts: ['companion-object', 'factory'] },
    { id: 'kt-singleton-3', title: 'Lazy Singleton', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a lazily initialized singleton.', skeleton: `class ExpensiveService private constructor() {\n    fun process() = "Processing"\n    companion object {\n        val instance: ExpensiveService by ___ { ExpensiveService() }\n    }\n}`, solution: `class ExpensiveService private constructor() {\n    fun process() = "Processing"\n    companion object {\n        val instance: ExpensiveService by lazy { ExpensiveService() }\n    }\n}`, hints: ['lazy delegates initialization until first access.', 'Thread-safe by default (LazyThreadSafetyMode.SYNCHRONIZED).', 'The instance is created only once.'], concepts: ['lazy', 'thread-safety'] },
    { id: 'kt-singleton-4', title: 'Thread-Safe Registry', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a thread-safe singleton registry.', skeleton: `object ServiceRegistry {\n    private val services = java.util.concurrent.___()\n    fun <T: Any> register(key: String, service: T) { services[key] = service }\n    fun get(key: String): Any? = services[key]\n}`, solution: `object ServiceRegistry {\n    private val services = java.util.concurrent.ConcurrentHashMap<String, Any>()\n    fun <T: Any> register(key: String, service: T) { services[key] = service }\n    fun get(key: String): Any? = services[key]\n}`, hints: ['ConcurrentHashMap is thread-safe.', 'Regular HashMap is not safe for concurrent access.', 'Object singletons may be accessed from multiple threads.'], concepts: ['ConcurrentHashMap', 'thread-safety'] },
    { id: 'kt-singleton-5', title: 'Named Companion Object', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a named companion object for a factory.', skeleton: `class Color private constructor(val r: Int, val g: Int, val b: Int) {\n    companion object ___ {\n        fun red() = Color(255, 0, 0)\n        fun green() = Color(0, 255, 0)\n        fun blue() = Color(0, 0, 255)\n    }\n}`, solution: `class Color private constructor(val r: Int, val g: Int, val b: Int) {\n    companion object Factory {\n        fun red() = Color(255, 0, 0)\n        fun green() = Color(0, 255, 0)\n        fun blue() = Color(0, 0, 255)\n    }\n}`, hints: ['Companion objects can have names.', 'Named companions are accessed as Color.Factory.red().', 'Or simply Color.red() as shorthand.'], concepts: ['named-companion', 'factory'] },
    { id: 'kt-singleton-6', title: 'Singleton Implementing Interface', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a singleton that implements an interface.', skeleton: `interface Logger {\n    fun log(message: String)\n}\n\n___ ConsoleLogger : Logger {\n    override fun log(message: String) {\n        println("[LOG] \${message}")\n    }\n}`, solution: `interface Logger {\n    fun log(message: String)\n}\n\nobject ConsoleLogger : Logger {\n    override fun log(message: String) {\n        println("[LOG] \${message}")\n    }\n}`, hints: ['Objects can implement interfaces.', 'This is the singleton implementing an interface.', 'Useful for providing a default implementation.'], concepts: ['object', 'interface', 'singleton'] },
    { id: 'kt-singleton-7', title: 'Write a Configuration Singleton', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a thread-safe configuration singleton.', skeleton: `// Write an object called Config that:\n// 1. Has a private val props = mutableMapOf<String, String>()\n// 2. Has fun set(key: String, value: String)\n// 3. Has fun get(key: String): String?\n// 4. Has fun getOrDefault(key: String, default: String): String\n// 5. Has fun loadDefaults() setting host=localhost, port=8080`, solution: `object Config {\n    private val props = mutableMapOf<String, String>()\n\n    fun set(key: String, value: String) { props[key] = value }\n    fun get(key: String): String? = props[key]\n    fun getOrDefault(key: String, default: String): String = props[key] ?: default\n\n    fun loadDefaults() {\n        props["host"] = "localhost"\n        props["port"] = "8080"\n    }\n}`, hints: ['object provides singleton behavior.', 'Internal state is shared across all callers.', 'loadDefaults populates initial configuration.'], concepts: ['object', 'configuration', 'singleton'] },
    { id: 'kt-singleton-8', title: 'Write a Singleton with DI', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a dependency injection approach instead of singleton.', skeleton: `// Write:\n// 1. interface Cache with fun get(key: String): String? and fun put(key: String, value: String)\n// 2. class InMemoryCache implementing Cache using HashMap\n// 3. class UserService(private val cache: Cache) with fun getUser(id: String): String\n//    that checks cache first, then returns "User-<id>" and caches it`, solution: `interface Cache {\n    fun get(key: String): String?\n    fun put(key: String, value: String)\n}\n\nclass InMemoryCache : Cache {\n    private val store = HashMap<String, String>()\n    override fun get(key: String): String? = store[key]\n    override fun put(key: String, value: String) { store[key] = value }\n}\n\nclass UserService(private val cache: Cache) {\n    fun getUser(id: String): String {\n        cache.get(id)?.let { return it }\n        val user = "User-\${id}"\n        cache.put(id, user)\n        return user\n    }\n}`, hints: ['DI allows swapping implementations easily.', 'Inject Cache interface, not a concrete class.', 'This is more testable than a singleton.'], concepts: ['dependency-injection', 'interface', 'testability'] },
    { id: 'kt-singleton-9', title: 'Write an Event Bus Singleton', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a simple event bus singleton.', skeleton: `// Write an object EventBus that:\n// 1. Has private val listeners = mutableMapOf<String, MutableList<(Any) -> Unit>>()\n// 2. fun on(event: String, listener: (Any) -> Unit) - registers a listener\n// 3. fun emit(event: String, data: Any) - calls all listeners for that event\n// 4. fun clear() - removes all listeners`, solution: `object EventBus {\n    private val listeners = mutableMapOf<String, MutableList<(Any) -> Unit>>()\n\n    fun on(event: String, listener: (Any) -> Unit) {\n        listeners.getOrPut(event) { mutableListOf() }.add(listener)\n    }\n\n    fun emit(event: String, data: Any) {\n        listeners[event]?.forEach { it(data) }\n    }\n\n    fun clear() {\n        listeners.clear()\n    }\n}`, hints: ['getOrPut creates the list if missing.', 'emit calls all registered listeners.', 'Event bus is a common singleton use case.'], concepts: ['event-bus', 'observer', 'singleton'] },
    { id: 'kt-singleton-10', title: 'Write a Connection Pool Singleton', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a simple connection pool singleton.', skeleton: `// Write an object ConnectionPool that:\n// 1. Has private val pool = ArrayDeque<String>() with max size 5\n// 2. init block adds 5 "Connection-1" through "Connection-5"\n// 3. fun acquire(): String? removes and returns from front, or null if empty\n// 4. fun release(conn: String) adds back if pool size < 5\n// 5. fun available(): Int returns pool size`, solution: `object ConnectionPool {\n    private val pool = ArrayDeque<String>()\n    private const val MAX_SIZE = 5\n\n    init {\n        for (i in 1..MAX_SIZE) {\n            pool.addLast("Connection-\${i}")\n        }\n    }\n\n    fun acquire(): String? = if (pool.isNotEmpty()) pool.removeFirst() else null\n\n    fun release(conn: String) {\n        if (pool.size < MAX_SIZE) pool.addLast(conn)\n    }\n\n    fun available(): Int = pool.size\n}`, hints: ['init block runs when the object is first accessed.', 'ArrayDeque works well as a pool backing structure.', 'acquire removes, release returns to pool.'], concepts: ['object', 'init', 'resource-pool'] },
    { id: 'kt-singleton-11', title: 'Write a Scoped Singleton', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a singleton scoped to a specific context.', skeleton: `// Write:\n// 1. class ScopedSingleton<T>(private val factory: () -> T)\n// 2. Has a private var instance: T? = null\n// 3. fun get(): T returns existing instance or creates new one\n// 4. fun reset() sets instance to null\n// 5. Demonstrate with a "DatabaseConnection" string type`, solution: `class ScopedSingleton<T>(private val factory: () -> T) {\n    private var instance: T? = null\n\n    fun get(): T {\n        if (instance == null) {\n            instance = factory()\n        }\n        return instance!!\n    }\n\n    fun reset() {\n        instance = null\n    }\n}\n\nval dbConnection = ScopedSingleton { "DatabaseConnection-\${System.currentTimeMillis()}" }`, hints: ['Scoped singletons can be reset.', 'Useful for test isolation.', 'factory is called lazily on first get().'], concepts: ['scoped-singleton', 'lazy-init', 'resettable'] },
    { id: 'kt-singleton-12', title: 'Write Double-Checked Locking', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a double-checked locking singleton (educational).', skeleton: `// Write a class Singleton with:\n// 1. Private constructor\n// 2. companion object with @Volatile private var instance: Singleton? = null\n// 3. fun getInstance(): Singleton using double-checked locking with synchronized\n// Note: In Kotlin, prefer lazy or object. This is for educational purposes.`, solution: `class Singleton private constructor() {\n    val id = System.nanoTime()\n\n    companion object {\n        @Volatile\n        private var instance: Singleton? = null\n\n        fun getInstance(): Singleton {\n            if (instance == null) {\n                synchronized(this) {\n                    if (instance == null) {\n                        instance = Singleton()\n                    }\n                }\n            }\n            return instance!!\n        }\n    }\n}`, hints: ['@Volatile ensures visibility across threads.', 'Double-check: first without lock, then with lock.', 'In Kotlin, prefer object or lazy instead.'], concepts: ['double-checked-locking', 'Volatile', 'synchronized'] },
    { id: 'kt-singleton-13', title: 'Fix Mutable Singleton State Leak', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix singleton that exposes its mutable internal state.', skeleton: `object UserStore {\n    val users = mutableListOf("Alice", "Bob")\n}\n\nfun main() {\n    UserStore.users.clear()  // External code can destroy state!\n    println(UserStore.users)\n}`, solution: `object UserStore {\n    private val _users = mutableListOf("Alice", "Bob")\n    val users: List<String> get() = _users.toList()\n\n    fun addUser(name: String) { _users.add(name) }\n    fun removeUser(name: String) { _users.remove(name) }\n}`, hints: ['Never expose mutable collections publicly.', 'Return a copy via toList().', 'Provide methods for controlled modification.'], concepts: ['encapsulation', 'defensive-copy'] },
    { id: 'kt-singleton-14', title: 'Fix Object Init Order', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix singleton that accesses uninitialized state.', skeleton: `object Config {\n    val greeting = "Hello, \${username}"\n    val username = "Admin"  // Initialized after greeting uses it!\n}\n\nfun main() {\n    println(Config.greeting)  // "Hello, null"\n}`, solution: `object Config {\n    val username = "Admin"\n    val greeting = "Hello, \${username}"\n}\n\nfun main() {\n    println(Config.greeting)\n}`, hints: ['Object properties initialize top-to-bottom.', 'greeting uses username before it is initialized.', 'Move username before greeting.'], concepts: ['initialization-order', 'object'] },
    { id: 'kt-singleton-15', title: 'Fix Non-Thread-Safe Singleton', type: 'fix-bug', difficulty: 'advanced', language: 'kotlin', goal: 'Fix a singleton that is not thread-safe.', skeleton: `object Counter {\n    private var count = 0\n    fun increment() { count++ }  // Not atomic!\n    fun get() = count\n}`, solution: `import java.util.concurrent.atomic.AtomicInteger\n\nobject Counter {\n    private val count = AtomicInteger(0)\n    fun increment() { count.incrementAndGet() }\n    fun get() = count.get()\n}`, hints: ['count++ is not atomic in multi-threaded code.', 'Use AtomicInteger for thread-safe counters.', 'incrementAndGet is atomic.'], concepts: ['AtomicInteger', 'thread-safety'] },
    { id: 'kt-singleton-16', title: 'Predict Object Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict singleton behavior.', skeleton: `object Counter {\n    var count = 0\n    fun increment() { count++ }\n}\n\nfun main() {\n    Counter.increment()\n    Counter.increment()\n    Counter.increment()\n    println(Counter.count)\n}`, solution: `3`, hints: ['Object state persists.', 'Three increments from 0.', 'count = 3.'], concepts: ['object', 'shared-state'] },
    { id: 'kt-singleton-17', title: 'Predict Lazy Init', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict when lazy initialization occurs.', skeleton: `class Heavy {\n    init { println("Created") }\n    companion object {\n        val instance by lazy {\n            println("Initializing")\n            Heavy()\n        }\n    }\n}\n\nfun main() {\n    println("Before")\n    val h = Heavy.instance\n    println("After")\n    val h2 = Heavy.instance\n    println("Done")\n}`, solution: `Before\nInitializing\nCreated\nAfter\nDone`, hints: ['lazy runs on first access only.', 'Second access reuses the instance.', '"Initializing" and "Created" print only once.'], concepts: ['lazy', 'initialization-timing'] },
    { id: 'kt-singleton-18', title: 'Predict Companion Factory', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict companion object factory output.', skeleton: `class Token private constructor(val value: String) {\n    companion object {\n        private var counter = 0\n        fun generate(): Token = Token("token-\${++counter}")\n    }\n}\n\nfun main() {\n    println(Token.generate().value)\n    println(Token.generate().value)\n    println(Token.generate().value)\n}`, solution: `token-1\ntoken-2\ntoken-3`, hints: ['counter persists across calls.', 'Each generate increments counter.', 'Private constructor forces factory usage.'], concepts: ['companion-object', 'factory', 'counter'] },
    { id: 'kt-singleton-19', title: 'Refactor Static Methods to Object', type: 'refactor', difficulty: 'beginner', language: 'kotlin', goal: 'Refactor Java-style static utility class to Kotlin object.', skeleton: `class MathUtils {\n    companion object {\n        fun square(x: Int) = x * x\n        fun cube(x: Int) = x * x * x\n        fun isEven(x: Int) = x % 2 == 0\n    }\n}`, solution: `object MathUtils {\n    fun square(x: Int) = x * x\n    fun cube(x: Int) = x * x * x\n    fun isEven(x: Int) = x % 2 == 0\n}`, hints: ['Utility classes are better as objects.', 'No need for companion when the class is only static methods.', 'object declaration is more idiomatic Kotlin.'], concepts: ['object', 'utility-class', 'refactoring'] },
    { id: 'kt-singleton-20', title: 'Refactor Singleton to DI', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor a hard singleton dependency to dependency injection.', skeleton: `object Database {\n    fun query(sql: String): String = "Result of: \${sql}"\n}\n\nclass UserRepository {\n    fun findUser(id: Int): String {\n        return Database.query("SELECT * FROM users WHERE id = \${id}")\n    }\n}`, solution: `interface Database {\n    fun query(sql: String): String\n}\n\nclass RealDatabase : Database {\n    override fun query(sql: String): String = "Result of: \${sql}"\n}\n\nclass UserRepository(private val db: Database) {\n    fun findUser(id: Int): String {\n        return db.query("SELECT * FROM users WHERE id = \${id}")\n    }\n}`, hints: ['Extract an interface from the object.', 'Inject the interface into dependent classes.', 'This enables testing with mock databases.'], concepts: ['dependency-injection', 'interface', 'testability'] },
  ],
};
