import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-factory',
  title: '43. Factory',
  explanation: `## Factory Pattern in Kotlin

Kotlin provides elegant ways to implement factories using companion objects, sealed classes, and generics.

### Companion Object Factory
\`\`\`kotlin
class User private constructor(val name: String, val role: String) {
    companion object {
        fun admin(name: String) = User(name, "admin")
        fun guest() = User("Guest", "guest")
    }
}
val admin = User.admin("Alice")
\`\`\`

### Sealed Class Factory
\`\`\`kotlin
sealed class Notification {
    data class Email(val to: String, val subject: String) : Notification()
    data class Sms(val phone: String, val message: String) : Notification()
    companion object {
        fun fromType(type: String, target: String, content: String): Notification = when (type) {
            "email" -> Email(target, content)
            "sms" -> Sms(target, content)
            else -> throw IllegalArgumentException("Unknown: \$type")
        }
    }
}
\`\`\`

### Generic Factory
\`\`\`kotlin
inline fun <reified T : Any> create(): T = T::class.java.getDeclaredConstructor().newInstance()
\`\`\``,
  exercises: [
    { id: 'kt-factory-1', title: 'Companion Factory', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Create a factory using companion object.', skeleton: `class Pizza private constructor(val size: String, val toppings: List<String>) {\n    ___ ___ {\n        fun small(vararg toppings: String) = Pizza("S", toppings.toList())\n        fun medium(vararg toppings: String) = Pizza("M", toppings.toList())\n        fun large(vararg toppings: String) = Pizza("L", toppings.toList())\n    }\n}`, solution: `class Pizza private constructor(val size: String, val toppings: List<String>) {\n    companion object {\n        fun small(vararg toppings: String) = Pizza("S", toppings.toList())\n        fun medium(vararg toppings: String) = Pizza("M", toppings.toList())\n        fun large(vararg toppings: String) = Pizza("L", toppings.toList())\n    }\n}`, hints: ['companion object holds factory methods.', 'Private constructor forces use of factory.', 'vararg allows variable number of toppings.'], concepts: ['companion-object', 'factory', 'private-constructor'] },
    { id: 'kt-factory-2', title: 'Sealed Class Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use sealed class with factory companion.', skeleton: `___ class Shape {\n    data class Circle(val radius: Double) : Shape()\n    data class Square(val side: Double) : Shape()\n    data class Triangle(val base: Double, val height: Double) : Shape()\n\n    companion object {\n        fun from(type: String, vararg args: Double): Shape = when (type) {\n            "circle" -> Circle(args[0])\n            "square" -> Square(args[0])\n            "triangle" -> Triangle(args[0], args[1])\n            else -> throw IllegalArgumentException("Unknown")\n        }\n    }\n}`, solution: `sealed class Shape {\n    data class Circle(val radius: Double) : Shape()\n    data class Square(val side: Double) : Shape()\n    data class Triangle(val base: Double, val height: Double) : Shape()\n\n    companion object {\n        fun from(type: String, vararg args: Double): Shape = when (type) {\n            "circle" -> Circle(args[0])\n            "square" -> Square(args[0])\n            "triangle" -> Triangle(args[0], args[1])\n            else -> throw IllegalArgumentException("Unknown")\n        }\n    }\n}`, hints: ['sealed class limits the hierarchy.', 'Factory method creates the right subclass.', 'when expression matches the type string.'], concepts: ['sealed-class', 'factory', 'when'] },
    { id: 'kt-factory-3', title: 'invoke Operator Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use operator invoke for factory syntax.', skeleton: `class Color private constructor(val hex: String) {\n    companion object {\n        ___ fun invoke(r: Int, g: Int, b: Int): Color {\n            val hex = "#%02x%02x%02x".format(r, g, b)\n            return Color(hex)\n        }\n    }\n}`, solution: `class Color private constructor(val hex: String) {\n    companion object {\n        operator fun invoke(r: Int, g: Int, b: Int): Color {\n            val hex = "#%02x%02x%02x".format(r, g, b)\n            return Color(hex)\n        }\n    }\n}`, hints: ['operator invoke allows calling Color(r, g, b).', 'It looks like a constructor but is a factory.', 'The actual constructor is private.'], concepts: ['operator-invoke', 'factory'] },
    { id: 'kt-factory-4', title: 'Generic Factory Function', type: 'fill-blank', difficulty: 'advanced', language: 'kotlin', goal: 'Write a generic factory using reified types.', skeleton: `interface Vehicle { val type: String }\nclass Car : Vehicle { override val type = "Car" }\nclass Truck : Vehicle { override val type = "Truck" }\n\ninline fun <___ T : Vehicle> createVehicle(): T {\n    return T::class.java.getDeclaredConstructor().newInstance()\n}`, solution: `interface Vehicle { val type: String }\nclass Car : Vehicle { override val type = "Car" }\nclass Truck : Vehicle { override val type = "Truck" }\n\ninline fun <reified T : Vehicle> createVehicle(): T {\n    return T::class.java.getDeclaredConstructor().newInstance()\n}`, hints: ['reified preserves the type at runtime.', 'getDeclaredConstructor().newInstance() creates an instance.', 'Only works for classes with no-arg constructors.'], concepts: ['reified', 'generic-factory'] },
    { id: 'kt-factory-5', title: 'Abstract Factory', type: 'fill-blank', difficulty: 'advanced', language: 'kotlin', goal: 'Implement an abstract factory pattern.', skeleton: `interface Button { fun render(): String }\ninterface TextField { fun render(): String }\n\n___ class UIFactory {\n    abstract fun createButton(): Button\n    abstract fun createTextField(): TextField\n}\n\nclass MaterialFactory : UIFactory() {\n    override fun createButton(): Button = object : Button { override fun render() = "[Material Button]" }\n    override fun createTextField(): TextField = object : TextField { override fun render() = "[Material TextField]" }\n}`, solution: `interface Button { fun render(): String }\ninterface TextField { fun render(): String }\n\nabstract class UIFactory {\n    abstract fun createButton(): Button\n    abstract fun createTextField(): TextField\n}\n\nclass MaterialFactory : UIFactory() {\n    override fun createButton(): Button = object : Button { override fun render() = "[Material Button]" }\n    override fun createTextField(): TextField = object : TextField { override fun render() = "[Material TextField]" }\n}`, hints: ['Abstract factory creates families of related objects.', 'Each concrete factory produces a different variant.', 'Clients use the factory interface, not concrete types.'], concepts: ['abstract-factory', 'abstract-class'] },
    { id: 'kt-factory-6', title: 'Map-Based Registry', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use a map registry for factory lookup.', skeleton: `interface Parser { fun parse(input: String): Any }\nclass JsonParser : Parser { override fun parse(input: String) = "JSON: \${input}" }\nclass XmlParser : Parser { override fun parse(input: String) = "XML: \${input}" }\n\nobject ParserFactory {\n    private val registry = ___<String, () -> Parser>(\n        "json" to ::JsonParser,\n        "xml" to ::XmlParser\n    )\n    fun create(type: String): Parser = registry[type]?.invoke() ?: throw IllegalArgumentException("Unknown: \${type}")\n}`, solution: `interface Parser { fun parse(input: String): Any }\nclass JsonParser : Parser { override fun parse(input: String) = "JSON: \${input}" }\nclass XmlParser : Parser { override fun parse(input: String) = "XML: \${input}" }\n\nobject ParserFactory {\n    private val registry = mapOf<String, () -> Parser>(\n        "json" to ::JsonParser,\n        "xml" to ::XmlParser\n    )\n    fun create(type: String): Parser = registry[type]?.invoke() ?: throw IllegalArgumentException("Unknown: \${type}")\n}`, hints: ['mapOf stores type-to-constructor mappings.', '::ClassName is a constructor reference.', 'invoke() calls the constructor.'], concepts: ['registry', 'constructor-reference', 'mapOf'] },
    { id: 'kt-factory-7', title: 'Write a Document Factory', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a factory for different document types.', skeleton: `// Write:\n// 1. sealed interface Document with val content: String\n// 2. data class PdfDoc, HtmlDoc, MarkdownDoc implementing Document\n// 3. fun createDocument(type: String, content: String): Document using when`, solution: `sealed interface Document {\n    val content: String\n}\n\ndata class PdfDoc(override val content: String) : Document\ndata class HtmlDoc(override val content: String) : Document\ndata class MarkdownDoc(override val content: String) : Document\n\nfun createDocument(type: String, content: String): Document = when (type) {\n    "pdf" -> PdfDoc(content)\n    "html" -> HtmlDoc(content)\n    "markdown" -> MarkdownDoc(content)\n    else -> throw IllegalArgumentException("Unknown type: \${type}")\n}`, hints: ['sealed interface restricts implementations.', 'when provides exhaustive matching.', 'Each type creates the appropriate subclass.'], concepts: ['sealed-interface', 'factory-function', 'when'] },
    { id: 'kt-factory-8', title: 'Write a Builder Factory', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a factory that combines builder and factory patterns.', skeleton: `// Write:\n// 1. data class HttpRequest(val method: String, val url: String, val headers: Map<String, String>, val body: String?)\n// 2. companion object with fun get(url: String), fun post(url: String, body: String)\n// 3. Both use a private builder internally`, solution: `data class HttpRequest(\n    val method: String,\n    val url: String,\n    val headers: Map<String, String>,\n    val body: String?\n) {\n    companion object {\n        fun get(url: String, headers: Map<String, String> = emptyMap()) =\n            HttpRequest("GET", url, headers, null)\n\n        fun post(url: String, body: String, headers: Map<String, String> = emptyMap()) =\n            HttpRequest("POST", url, headers + ("Content-Type" to "application/json"), body)\n\n        fun delete(url: String, headers: Map<String, String> = emptyMap()) =\n            HttpRequest("DELETE", url, headers, null)\n    }\n}`, hints: ['Factory methods hide construction complexity.', 'POST auto-adds Content-Type header.', 'Default parameters reduce boilerplate.'], concepts: ['companion-factory', 'default-parameters'] },
    { id: 'kt-factory-9', title: 'Write a Plugin Factory', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a factory that discovers and creates plugins.', skeleton: `// Write:\n// 1. interface Plugin with fun name(): String and fun execute(): String\n// 2. class LogPlugin, class MetricsPlugin implementing Plugin\n// 3. object PluginFactory with:\n//    - register(name: String, factory: () -> Plugin)\n//    - create(name: String): Plugin\n//    - createAll(): List<Plugin>`, solution: `interface Plugin {\n    fun name(): String\n    fun execute(): String\n}\n\nclass LogPlugin : Plugin {\n    override fun name() = "logger"\n    override fun execute() = "Logging enabled"\n}\n\nclass MetricsPlugin : Plugin {\n    override fun name() = "metrics"\n    override fun execute() = "Metrics collecting"\n}\n\nobject PluginFactory {\n    private val registry = mutableMapOf<String, () -> Plugin>()\n\n    fun register(name: String, factory: () -> Plugin) {\n        registry[name] = factory\n    }\n\n    fun create(name: String): Plugin =\n        registry[name]?.invoke() ?: throw IllegalArgumentException("Unknown plugin: \${name}")\n\n    fun createAll(): List<Plugin> = registry.values.map { it() }\n}`, hints: ['Registry pattern with mutable map.', 'Plugins register themselves with factories.', 'createAll instantiates every registered plugin.'], concepts: ['plugin-factory', 'registry', 'extensible'] },
    { id: 'kt-factory-10', title: 'Write a Cached Factory', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a factory that caches created instances.', skeleton: `// Write a class CachedFactory<K, V> that:\n// 1. Takes a factory: (K) -> V parameter\n// 2. Has private val cache = mutableMapOf<K, V>()\n// 3. fun get(key: K): V - returns cached or creates new\n// 4. fun invalidate(key: K) - removes from cache\n// 5. fun clear() - clears all cache`, solution: `class CachedFactory<K, V>(private val factory: (K) -> V) {\n    private val cache = mutableMapOf<K, V>()\n\n    fun get(key: K): V = cache.getOrPut(key) { factory(key) }\n\n    fun invalidate(key: K) { cache.remove(key) }\n\n    fun clear() { cache.clear() }\n\n    fun size(): Int = cache.size\n}`, hints: ['getOrPut creates if missing.', 'Cache avoids recreating expensive objects.', 'invalidate and clear manage cache lifecycle.'], concepts: ['cached-factory', 'getOrPut', 'memoization'] },
    { id: 'kt-factory-11', title: 'Write a Conditional Factory', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a factory that creates objects based on conditions.', skeleton: `// Write:\n// 1. interface Compressor with fun compress(data: String): String\n// 2. class GzipCompressor, class ZipCompressor, class NoopCompressor\n// 3. fun createCompressor(sizeKb: Int): Compressor\n//    - > 1000 KB: GzipCompressor\n//    - > 100 KB: ZipCompressor\n//    - else: NoopCompressor`, solution: `interface Compressor {\n    fun compress(data: String): String\n}\n\nclass GzipCompressor : Compressor {\n    override fun compress(data: String) = "gzip(\${data})"\n}\n\nclass ZipCompressor : Compressor {\n    override fun compress(data: String) = "zip(\${data})"\n}\n\nclass NoopCompressor : Compressor {\n    override fun compress(data: String) = data\n}\n\nfun createCompressor(sizeKb: Int): Compressor = when {\n    sizeKb > 1000 -> GzipCompressor()\n    sizeKb > 100 -> ZipCompressor()\n    else -> NoopCompressor()\n}`, hints: ['when without argument checks conditions.', 'Factory logic selects based on size.', 'Interface allows uniform usage.'], concepts: ['conditional-factory', 'when', 'interface'] },
    { id: 'kt-factory-12', title: 'Write a Parameterized Factory', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a generic parameterized factory.', skeleton: `// Write:\n// 1. A generic interface Factory<T> with fun create(): T\n// 2. An inline fun <reified T : Any> factory(crossinline init: () -> T): Factory<T>\n//    that returns object : Factory<T> { override fun create() = init() }\n// 3. Demonstrate creating factories for String and List<Int>`, solution: `interface Factory<T> {\n    fun create(): T\n}\n\ninline fun <reified T : Any> factory(crossinline init: () -> T): Factory<T> {\n    return object : Factory<T> {\n        override fun create(): T = init()\n    }\n}\n\nfun main() {\n    val stringFactory = factory { "Hello-\${System.nanoTime()}" }\n    val listFactory = factory { mutableListOf(1, 2, 3) }\n\n    println(stringFactory.create())\n    println(listFactory.create())\n}`, hints: ['Generic Factory interface for any type.', 'crossinline allows lambda in object expression.', 'Each create() call produces a new instance.'], concepts: ['generic-factory', 'crossinline', 'reified'] },
    { id: 'kt-factory-13', title: 'Fix Factory Returning Same Instance', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix factory that accidentally returns the same mutable instance.', skeleton: `class ListFactory {\n    private val template = mutableListOf(1, 2, 3)\n    fun create(): MutableList<Int> = template  // Returns same reference!\n}\n\nfun main() {\n    val f = ListFactory()\n    val a = f.create()\n    a.add(99)\n    val b = f.create()\n    println(b)  // [1, 2, 3, 99] -- contaminated!\n}`, solution: `class ListFactory {\n    private val template = listOf(1, 2, 3)\n    fun create(): MutableList<Int> = template.toMutableList()\n}\n\nfun main() {\n    val f = ListFactory()\n    val a = f.create()\n    a.add(99)\n    val b = f.create()\n    println(b)  // [1, 2, 3]\n}`, hints: ['Return a copy, not the original.', 'toMutableList() creates a new list.', 'Templates should be immutable.'], concepts: ['defensive-copy', 'factory-bug'] },
    { id: 'kt-factory-14', title: 'Fix Missing Sealed Subclass', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix incomplete when expression in factory.', skeleton: `sealed class Animal {\n    data class Dog(val breed: String) : Animal()\n    data class Cat(val color: String) : Animal()\n    data class Bird(val canFly: Boolean) : Animal()\n}\n\nfun createAnimal(type: String): Animal = when (type) {\n    "dog" -> Animal.Dog("Labrador")\n    "cat" -> Animal.Cat("black")\n    // Missing bird! Compiler doesn't warn because else is missing too\n    else -> throw IllegalArgumentException("Unknown")\n}`, solution: `sealed class Animal {\n    data class Dog(val breed: String) : Animal()\n    data class Cat(val color: String) : Animal()\n    data class Bird(val canFly: Boolean) : Animal()\n}\n\nfun createAnimal(type: String): Animal = when (type) {\n    "dog" -> Animal.Dog("Labrador")\n    "cat" -> Animal.Cat("black")\n    "bird" -> Animal.Bird(true)\n    else -> throw IllegalArgumentException("Unknown: \${type}")\n}`, hints: ['Add the missing "bird" case.', 'Sealed classes help catch missing cases.', 'Keep else for unknown inputs.'], concepts: ['sealed-class', 'exhaustive-when'] },
    { id: 'kt-factory-15', title: 'Fix Generic Type Erasure', type: 'fix-bug', difficulty: 'advanced', language: 'kotlin', goal: 'Fix factory that loses type information due to erasure.', skeleton: `fun <T> create(type: Class<T>): T {\n    return type.getDeclaredConstructor().newInstance()\n}\n\n// Caller must pass Class object explicitly\n// val s: String = create(String::class.java)`, solution: `inline fun <reified T : Any> create(): T {\n    return T::class.java.getDeclaredConstructor().newInstance()\n}\n\n// Now type is inferred\n// val s: String = create<String>()`, hints: ['reified preserves type at runtime.', 'No need to pass Class explicitly.', 'inline + reified is the Kotlin solution to type erasure.'], concepts: ['reified', 'type-erasure', 'inline'] },
    { id: 'kt-factory-16', title: 'Predict Factory Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the output of a companion factory.', skeleton: `class Greeting private constructor(val text: String) {\n    companion object {\n        fun formal(name: String) = Greeting("Dear \${name}")\n        fun casual(name: String) = Greeting("Hey \${name}!")\n    }\n}\n\nfun main() {\n    println(Greeting.formal("Alice").text)\n    println(Greeting.casual("Bob").text)\n}`, solution: `Dear Alice\nHey Bob!`, hints: ['formal prepends "Dear".', 'casual prepends "Hey" and appends "!".', 'Private constructor forces factory usage.'], concepts: ['companion-factory', 'output'] },
    { id: 'kt-factory-17', title: 'Predict Sealed Factory', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict sealed class factory output.', skeleton: `sealed class Result {\n    data class Success(val value: Int) : Result()\n    data class Error(val message: String) : Result()\n}\n\nfun compute(x: Int): Result = if (x > 0) Result.Success(x * 2) else Result.Error("Negative")\n\nfun main() {\n    println(compute(5))\n    println(compute(-1))\n}`, solution: `Success(value=10)\nError(message=Negative)`, hints: ['compute(5): 5 > 0, returns Success(10).', 'compute(-1): not > 0, returns Error.', 'Data class toString shows name and values.'], concepts: ['sealed-class', 'factory', 'data-class'] },
    { id: 'kt-factory-18', title: 'Predict Cached Factory', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict cached factory behavior.', skeleton: `class CachedFactory {\n    private val cache = mutableMapOf<String, String>()\n    private var created = 0\n    fun get(key: String): String = cache.getOrPut(key) {\n        created++\n        "Object-\${created}"\n    }\n}\n\nfun main() {\n    val f = CachedFactory()\n    println(f.get("a"))\n    println(f.get("b"))\n    println(f.get("a"))\n}`, solution: `Object-1\nObject-2\nObject-1`, hints: ['"a" is created first as Object-1.', '"b" is created as Object-2.', 'Second "a" returns cached Object-1.'], concepts: ['caching', 'getOrPut'] },
    { id: 'kt-factory-19', title: 'Refactor Constructor to Factory', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor direct construction to factory methods.', skeleton: `data class User(val name: String, val role: String, val permissions: List<String>)\n\nfun main() {\n    val admin = User("Alice", "admin", listOf("read", "write", "delete", "manage"))\n    val viewer = User("Bob", "viewer", listOf("read"))\n    val editor = User("Carol", "editor", listOf("read", "write"))\n}`, solution: `data class User(val name: String, val role: String, val permissions: List<String>) {\n    companion object {\n        fun admin(name: String) = User(name, "admin", listOf("read", "write", "delete", "manage"))\n        fun viewer(name: String) = User(name, "viewer", listOf("read"))\n        fun editor(name: String) = User(name, "editor", listOf("read", "write"))\n    }\n}\n\nfun main() {\n    val admin = User.admin("Alice")\n    val viewer = User.viewer("Bob")\n    val editor = User.editor("Carol")\n}`, hints: ['Factory methods encode role-permission mappings.', 'Callers no longer need to know permission lists.', 'Reduces duplication and potential errors.'], concepts: ['companion-factory', 'encapsulation'] },
    { id: 'kt-factory-20', title: 'Refactor if/else to Sealed Factory', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor string-based type checking to sealed class hierarchy.', skeleton: `data class Payment(val type: String, val amount: Double, val details: Map<String, String>)\n\nfun processPayment(p: Payment): String {\n    return if (p.type == "credit") {\n        "Charging credit card \${p.details["card"]} for \${p.amount}"\n    } else if (p.type == "paypal") {\n        "PayPal payment to \${p.details["email"]} for \${p.amount}"\n    } else if (p.type == "bank") {\n        "Bank transfer to \${p.details["account"]} for \${p.amount}"\n    } else {\n        "Unknown payment type"\n    }\n}`, solution: `sealed class Payment(val amount: Double) {\n    class CreditCard(amount: Double, val card: String) : Payment(amount)\n    class PayPal(amount: Double, val email: String) : Payment(amount)\n    class BankTransfer(amount: Double, val account: String) : Payment(amount)\n}\n\nfun processPayment(p: Payment): String = when (p) {\n    is Payment.CreditCard -> "Charging credit card \${p.card} for \${p.amount}"\n    is Payment.PayPal -> "PayPal payment to \${p.email} for \${p.amount}"\n    is Payment.BankTransfer -> "Bank transfer to \${p.account} for \${p.amount}"\n}`, hints: ['Sealed classes replace string type checking.', 'when is exhaustive for sealed classes.', 'Type-specific data is in each subclass.'], concepts: ['sealed-class', 'type-safety', 'refactoring'] },
  ],
};
