import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-observer',
  title: '44. Observer',
  explanation: `## Observer Pattern in Kotlin

Kotlin offers modern observer patterns using Flow, StateFlow, SharedFlow, and callback patterns.

### Flow-Based Observer
\`\`\`kotlin
val events = MutableSharedFlow<String>()
// Emitter
events.emit("UserLoggedIn")
// Observer
events.collect { event -> println("Event: \$event") }
\`\`\`

### StateFlow
\`\`\`kotlin
val state = MutableStateFlow("Initial")
state.value = "Updated"
state.collect { println(it) } // Only latest value
\`\`\`

### SharedFlow
\`\`\`kotlin
val events = MutableSharedFlow<String>(replay = 1)
events.emit("event1")
events.collect { println(it) } // Gets replayed events
\`\`\`

### Callback Patterns
\`\`\`kotlin
fun interface OnClickListener {
    fun onClick(id: String)
}
class Button {
    var onClick: OnClickListener? = null
    fun click() { onClick?.onClick("btn1") }
}
\`\`\``,
  exercises: [
    { id: 'kt-observer-1', title: 'MutableStateFlow', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Create and use a MutableStateFlow.', skeleton: `import kotlinx.coroutines.flow.*\n\nfun main() {\n    val counter = ___(0)\n    counter.value = 5\n    println(counter.value)\n}`, solution: `import kotlinx.coroutines.flow.*\n\nfun main() {\n    val counter = MutableStateFlow(0)\n    counter.value = 5\n    println(counter.value)\n}`, hints: ['MutableStateFlow holds a single updatable value.', 'Access and update via .value property.', 'It always has a current value.'], concepts: ['MutableStateFlow', 'state'] },
    { id: 'kt-observer-2', title: 'Collect StateFlow', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Collect values from a StateFlow.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val name = MutableStateFlow("Alice")\n    val job = launch {\n        name.___ { println("Name: \${it}") }\n    }\n    delay(100)\n    name.value = "Bob"\n    delay(100)\n    job.cancel()\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val name = MutableStateFlow("Alice")\n    val job = launch {\n        name.collect { println("Name: \${it}") }\n    }\n    delay(100)\n    name.value = "Bob"\n    delay(100)\n    job.cancel()\n}`, hints: ['collect is a terminal operator.', 'StateFlow emits on value changes.', 'collect suspends and processes each emission.'], concepts: ['collect', 'StateFlow'] },
    { id: 'kt-observer-3', title: 'SharedFlow Events', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a SharedFlow for event broadcasting.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = ___()\n    launch {\n        events.collect { println("Observer: \${it}") }\n    }\n    delay(100)\n    events.emit("click")\n    events.emit("scroll")\n    delay(100)\n    cancel()\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = MutableSharedFlow<String>()\n    launch {\n        events.collect { println("Observer: \${it}") }\n    }\n    delay(100)\n    events.emit("click")\n    events.emit("scroll")\n    delay(100)\n    cancel()\n}`, hints: ['MutableSharedFlow broadcasts to all collectors.', 'Unlike StateFlow, it does not conflate.', 'Every emission is delivered to every active collector.'], concepts: ['MutableSharedFlow', 'event-broadcasting'] },
    { id: 'kt-observer-4', title: 'SharedFlow with Replay', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a SharedFlow with replay buffer.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = MutableSharedFlow<String>(___ = 2)\n    events.emit("old1")\n    events.emit("old2")\n    events.emit("old3")\n    launch {\n        events.collect { println(it) }\n    }\n    delay(100)\n    cancel()\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = MutableSharedFlow<String>(replay = 2)\n    events.emit("old1")\n    events.emit("old2")\n    events.emit("old3")\n    launch {\n        events.collect { println(it) }\n    }\n    delay(100)\n    cancel()\n}`, hints: ['replay = 2 keeps the last 2 emissions.', 'New collectors receive replayed events.', '"old2" and "old3" are replayed (last 2).'], concepts: ['replay', 'SharedFlow'] },
    { id: 'kt-observer-5', title: 'fun interface Callback', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Define a SAM callback interface.', skeleton: `___ interface OnChange<T> {\n    fun onChange(value: T)\n}\n\nclass Observable<T>(initial: T) {\n    var value: T = initial\n        set(new) { field = new; listener?.onChange(new) }\n    var listener: OnChange<T>? = null\n}`, solution: `fun interface OnChange<T> {\n    fun onChange(value: T)\n}\n\nclass Observable<T>(initial: T) {\n    var value: T = initial\n        set(new) { field = new; listener?.onChange(new) }\n    var listener: OnChange<T>? = null\n}`, hints: ['fun interface enables SAM conversion.', 'Single method interfaces can use lambdas.', 'listener?.onChange uses safe call.'], concepts: ['fun-interface', 'SAM', 'callback'] },
    { id: 'kt-observer-6', title: 'Multiple Observers', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Support multiple observers with a list.', skeleton: `class EventEmitter<T> {\n    private val listeners = ___<(T) -> Unit>()\n    fun on(listener: (T) -> Unit) { listeners.add(listener) }\n    fun off(listener: (T) -> Unit) { listeners.remove(listener) }\n    fun emit(value: T) { listeners.forEach { it(value) } }\n}`, solution: `class EventEmitter<T> {\n    private val listeners = mutableListOf<(T) -> Unit>()\n    fun on(listener: (T) -> Unit) { listeners.add(listener) }\n    fun off(listener: (T) -> Unit) { listeners.remove(listener) }\n    fun emit(value: T) { listeners.forEach { it(value) } }\n}`, hints: ['mutableListOf holds multiple listeners.', 'on/off for subscribe/unsubscribe.', 'emit notifies all listeners.'], concepts: ['observer-list', 'event-emitter'] },
    { id: 'kt-observer-7', title: 'Write a Property Observer', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write an observable property using Delegates.observable.', skeleton: `import kotlin.properties.Delegates\n\n// Write a class User that:\n// 1. Has var name: String using Delegates.observable\n// 2. Initial value "Unknown"\n// 3. On change, prints "Name changed from <old> to <new>"\n// 4. Has var age: Int using Delegates.vetoable\n// 5. Only accepts age > 0`, solution: `import kotlin.properties.Delegates\n\nclass User {\n    var name: String by Delegates.observable("Unknown") { _, old, new ->\n        println("Name changed from \${old} to \${new}")\n    }\n\n    var age: Int by Delegates.vetoable(0) { _, _, new ->\n        new > 0\n    }\n}`, hints: ['Delegates.observable fires callback on every change.', 'Delegates.vetoable can reject changes.', 'Vetoable returns false to reject the new value.'], concepts: ['Delegates.observable', 'Delegates.vetoable'] },
    { id: 'kt-observer-8', title: 'Write a Typed Event Bus', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a typed event bus using SharedFlow.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\n// Write a class TypedEventBus that:\n// 1. Has private val _events = MutableSharedFlow<Any>()\n// 2. Has val events: SharedFlow<Any> = _events.asSharedFlow()\n// 3. Has suspend fun emit(event: Any)\n// 4. Has inline fun <reified T> on(): Flow<T> that filters by type`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass TypedEventBus {\n    private val _events = MutableSharedFlow<Any>()\n    val events: SharedFlow<Any> = _events.asSharedFlow()\n\n    suspend fun emit(event: Any) {\n        _events.emit(event)\n    }\n\n    inline fun <reified T> on(): Flow<T> {\n        return events.filterIsInstance<T>()\n    }\n}`, hints: ['MutableSharedFlow broadcasts events.', 'asSharedFlow creates read-only view.', 'filterIsInstance filters by type.'], concepts: ['SharedFlow', 'filterIsInstance', 'event-bus'] },
    { id: 'kt-observer-9', title: 'Write a ViewModel-Style State Holder', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a state holder using StateFlow.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\n// Write a class CounterViewModel that:\n// 1. Has private val _count = MutableStateFlow(0)\n// 2. Has val count: StateFlow<Int> = _count.asStateFlow()\n// 3. Has fun increment() that updates _count.value\n// 4. Has fun decrement() that updates _count.value\n// 5. Has fun reset()`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass CounterViewModel {\n    private val _count = MutableStateFlow(0)\n    val count: StateFlow<Int> = _count.asStateFlow()\n\n    fun increment() { _count.value++ }\n    fun decrement() { _count.value-- }\n    fun reset() { _count.value = 0 }\n}`, hints: ['Private mutable, public immutable pattern.', 'asStateFlow creates read-only view.', 'Observers collect from the public StateFlow.'], concepts: ['StateFlow', 'ViewModel', 'encapsulation'] },
    { id: 'kt-observer-10', title: 'Write a Combine Flow Observer', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write an observer that combines multiple StateFlows.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\n// Write a class FormState that:\n// 1. Has val email = MutableStateFlow("")\n// 2. Has val password = MutableStateFlow("")\n// 3. Has val isValid: StateFlow<Boolean> that combines both\n//    - email must contain "@", password.length >= 8\n// 4. Uses combine operator and stateIn`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass FormState(scope: CoroutineScope) {\n    val email = MutableStateFlow("")\n    val password = MutableStateFlow("")\n\n    val isValid: StateFlow<Boolean> = combine(email, password) { e, p ->\n        e.contains("@") && p.length >= 8\n    }.stateIn(scope, SharingStarted.Eagerly, false)\n}`, hints: ['combine merges multiple flows.', 'stateIn converts Flow to StateFlow.', 'SharingStarted.Eagerly starts immediately.'], concepts: ['combine', 'stateIn', 'derived-state'] },
    { id: 'kt-observer-11', title: 'Write a Debounced Observer', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write an observer that debounces rapid changes.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\n// Write a class SearchViewModel that:\n// 1. Has private val _query = MutableStateFlow("")\n// 2. Has val results: Flow<String> that:\n//    - debounces query by 300ms\n//    - filters blank queries\n//    - maps to "Results for: <query>"\n// 3. Has fun setQuery(q: String)`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass SearchViewModel {\n    private val _query = MutableStateFlow("")\n\n    val results: Flow<String> = _query\n        .debounce(300L)\n        .filter { it.isNotBlank() }\n        .distinctUntilChanged()\n        .map { "Results for: \${it}" }\n\n    fun setQuery(q: String) {\n        _query.value = q\n    }\n}`, hints: ['debounce waits for a pause in emissions.', 'distinctUntilChanged skips duplicates.', 'Flow operators chain naturally.'], concepts: ['debounce', 'distinctUntilChanged', 'search'] },
    { id: 'kt-observer-12', title: 'Write a Lifecycle-Aware Observer', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write an observer that respects lifecycle scope.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\n// Write a class Subscription that:\n// 1. Has private var job: Job? = null\n// 2. Has fun <T> observe(flow: Flow<T>, scope: CoroutineScope, collector: (T) -> Unit)\n//    - Cancels previous job\n//    - Launches new collection in scope\n// 3. Has fun cancel() that cancels the job`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass Subscription {\n    private var job: Job? = null\n\n    fun <T> observe(flow: Flow<T>, scope: CoroutineScope, collector: (T) -> Unit) {\n        job?.cancel()\n        job = scope.launch {\n            flow.collect { collector(it) }\n        }\n    }\n\n    fun cancel() {\n        job?.cancel()\n        job = null\n    }\n}`, hints: ['Cancel previous job before starting new one.', 'scope.launch ties collection to lifecycle.', 'When scope is cancelled, collection stops.'], concepts: ['Job', 'lifecycle', 'cancellation'] },
    { id: 'kt-observer-13', title: 'Fix SharedFlow Missed Events', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix observers that miss events emitted before subscription.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = MutableSharedFlow<String>()  // No replay!\n    events.emit("important-event")\n    launch {\n        events.collect { println(it) }  // Missed the event!\n    }\n    delay(100)\n    cancel()\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val events = MutableSharedFlow<String>(replay = 1)\n    events.emit("important-event")\n    launch {\n        events.collect { println(it) }\n    }\n    delay(100)\n    cancel()\n}`, hints: ['Default replay is 0 - no history.', 'Add replay = 1 to keep the last event.', 'New subscribers receive replayed events.'], concepts: ['replay', 'SharedFlow', 'missed-events'] },
    { id: 'kt-observer-14', title: 'Fix StateFlow Not Emitting Same Value', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix StateFlow that silently drops duplicate values.', skeleton: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nfun main() = runBlocking {\n    val state = MutableStateFlow("loading")\n    launch {\n        state.collect { println("State: \${it}") }\n    }\n    delay(100)\n    state.value = "error"\n    delay(100)\n    state.value = "loading"  // Want to re-trigger loading!\n    state.value = "loading"  // This is ignored by StateFlow\n    delay(100)\n    cancel()\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\ndata class StateEvent(val state: String, val timestamp: Long = System.nanoTime())\n\nfun main() = runBlocking {\n    val state = MutableStateFlow(StateEvent("loading"))\n    launch {\n        state.collect { println("State: \${it.state}") }\n    }\n    delay(100)\n    state.value = StateEvent("error")\n    delay(100)\n    state.value = StateEvent("loading")  // Different timestamp = new emission\n    delay(100)\n    cancel()\n}`, hints: ['StateFlow uses equality to skip duplicates.', 'Wrap state in a data class with unique field.', 'A timestamp ensures each emission is unique.'], concepts: ['StateFlow', 'equality', 'uniqueness'] },
    { id: 'kt-observer-15', title: 'Fix Memory Leak in Observer', type: 'fix-bug', difficulty: 'advanced', language: 'kotlin', goal: 'Fix observer that leaks because it is never unsubscribed.', skeleton: `class EventBus {\n    private val listeners = mutableListOf<(String) -> Unit>()\n    fun on(listener: (String) -> Unit) { listeners.add(listener) }\n    fun emit(event: String) { listeners.forEach { it(event) } }\n}\n\nclass Screen(private val bus: EventBus) {\n    init {\n        bus.on { println("Screen got: \${it}") }  // Never removed!\n    }\n}`, solution: `class EventBus {\n    private val listeners = mutableListOf<(String) -> Unit>()\n    fun on(listener: (String) -> Unit): () -> Unit {\n        listeners.add(listener)\n        return { listeners.remove(listener) }\n    }\n    fun emit(event: String) { listeners.forEach { it(event) } }\n}\n\nclass Screen(private val bus: EventBus) {\n    private var unsubscribe: (() -> Unit)? = null\n\n    fun start() {\n        unsubscribe = bus.on { println("Screen got: \${it}") }\n    }\n\n    fun stop() {\n        unsubscribe?.invoke()\n        unsubscribe = null\n    }\n}`, hints: ['Return an unsubscribe function from on().', 'Store the unsubscribe and call it on cleanup.', 'This prevents listener accumulation.'], concepts: ['unsubscribe', 'memory-leak', 'cleanup'] },
    { id: 'kt-observer-16', title: 'Predict StateFlow Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict StateFlow value changes.', skeleton: `import kotlinx.coroutines.flow.*\n\nfun main() {\n    val state = MutableStateFlow(10)\n    state.value = 20\n    state.value = 20\n    state.value = 30\n    println(state.value)\n}`, solution: `30`, hints: ['StateFlow holds the latest value.', 'Duplicate 20 is ignored.', 'Final value is 30.'], concepts: ['StateFlow', 'latest-value'] },
    { id: 'kt-observer-17', title: 'Predict Observer Count', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict how many times the observer fires.', skeleton: `class Counter {\n    private val observers = mutableListOf<(Int) -> Unit>()\n    var count = 0\n        private set\n    fun onChange(observer: (Int) -> Unit) { observers.add(observer) }\n    fun increment() { count++; observers.forEach { it(count) } }\n}\n\nfun main() {\n    val c = Counter()\n    var fires = 0\n    c.onChange { fires++ }\n    c.onChange { fires++ }\n    c.increment()\n    c.increment()\n    println(fires)\n}`, solution: `4`, hints: ['2 observers, each fires on increment.', '2 increments x 2 observers = 4 fires.', 'Each observer increments fires.'], concepts: ['observer', 'multiple-listeners'] },
    { id: 'kt-observer-18', title: 'Predict Delegates.observable', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict observable delegate behavior.', skeleton: `import kotlin.properties.Delegates\n\nvar score: Int by Delegates.observable(0) { _, old, new ->\n    println("\${old} -> \${new}")\n}\n\nfun main() {\n    score = 10\n    score = 20\n    score = 20\n}`, solution: `0 -> 10\n10 -> 20\n20 -> 20`, hints: ['observable fires on EVERY set, even same value.', 'Unlike StateFlow, duplicates are not skipped.', 'Three assignments = three callbacks.'], concepts: ['Delegates.observable', 'every-change'] },
    { id: 'kt-observer-19', title: 'Refactor Callbacks to Flow', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor callback-based observation to Flow.', skeleton: `class DataStore {\n    private var data = ""\n    private var listener: ((String) -> Unit)? = null\n    fun setListener(l: (String) -> Unit) { listener = l }\n    fun update(value: String) {\n        data = value\n        listener?.invoke(value)\n    }\n}`, solution: `import kotlinx.coroutines.flow.*\n\nclass DataStore {\n    private val _data = MutableStateFlow("")\n    val data: StateFlow<String> = _data.asStateFlow()\n\n    fun update(value: String) {\n        _data.value = value\n    }\n}`, hints: ['Replace callback with StateFlow.', 'Multiple observers can collect.', 'No manual listener management needed.'], concepts: ['StateFlow', 'callback-to-flow'] },
    { id: 'kt-observer-20', title: 'Refactor Pull to Push', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor polling to push-based observation.', skeleton: `import kotlinx.coroutines.*\n\nclass Sensor {\n    fun readValue(): Int = (Math.random() * 100).toInt()\n}\n\nsuspend fun monitor(sensor: Sensor) {\n    while (true) {\n        val value = sensor.readValue()\n        println("Value: \${value}")\n        delay(1000)  // Polling every second\n    }\n}`, solution: `import kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\n\nclass Sensor {\n    fun readValue(): Int = (Math.random() * 100).toInt()\n\n    fun valueFlow(intervalMs: Long): Flow<Int> = flow {\n        while (true) {\n            emit(readValue())\n            delay(intervalMs)\n        }\n    }\n}\n\nsuspend fun monitor(sensor: Sensor) {\n    sensor.valueFlow(1000)\n        .distinctUntilChanged()\n        .collect { println("Value: \${it}") }\n}`, hints: ['Convert polling loop to a Flow.', 'flow { } with delay creates periodic emissions.', 'distinctUntilChanged skips duplicate readings.'], concepts: ['flow', 'push-based', 'polling-to-flow'] },
  ],
};
