import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-strategy',
  title: '45. Strategy',
  explanation: `## Strategy Pattern in Kotlin

The Strategy pattern defines a family of algorithms and makes them interchangeable. Kotlin's function types and sealed classes make this elegant.

### Function Type Strategy
\`\`\`kotlin
fun process(items: List<Int>, strategy: (List<Int>) -> List<Int>): List<Int> {
    return strategy(items)
}
val sorted = process(listOf(3,1,2)) { it.sorted() }
val reversed = process(listOf(3,1,2)) { it.reversed() }
\`\`\`

### Sealed Class Strategy
\`\`\`kotlin
sealed class SortStrategy {
    object Ascending : SortStrategy()
    object Descending : SortStrategy()
    data class Custom(val comparator: Comparator<Int>) : SortStrategy()
}
\`\`\`

### Lambda Strategies
\`\`\`kotlin
typealias Validator = (String) -> Boolean
val emailValidator: Validator = { it.contains("@") }
val phoneValidator: Validator = { it.all { c -> c.isDigit() } }
\`\`\``,
  exercises: [
    { id: 'kt-strategy-1', title: 'Function Type Strategy', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Pass a strategy as a function parameter.', skeleton: `fun <T> applyStrategy(items: List<T>, strategy: (List<T>) -> List<T>): List<T> {\n    return ___(items)\n}\n\nfun main() {\n    val nums = listOf(3, 1, 4, 1, 5)\n    println(applyStrategy(nums) { it.sorted() })\n}`, solution: `fun <T> applyStrategy(items: List<T>, strategy: (List<T>) -> List<T>): List<T> {\n    return strategy(items)\n}\n\nfun main() {\n    val nums = listOf(3, 1, 4, 1, 5)\n    println(applyStrategy(nums) { it.sorted() })\n}`, hints: ['strategy is a function parameter.', 'Call it with strategy(items).', 'Lambda provides the algorithm.'], concepts: ['function-type', 'strategy', 'lambda'] },
    { id: 'kt-strategy-2', title: 'Typealias Strategy', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Define a strategy type with typealias.', skeleton: `___ Formatter = (String) -> String\n\nval uppercase: Formatter = { it.uppercase() }\nval lowercase: Formatter = { it.lowercase() }\nval titleCase: Formatter = { it.split(" ").joinToString(" ") { w -> w.replaceFirstChar { c -> c.uppercase() } } }`, solution: `typealias Formatter = (String) -> String\n\nval uppercase: Formatter = { it.uppercase() }\nval lowercase: Formatter = { it.lowercase() }\nval titleCase: Formatter = { it.split(" ").joinToString(" ") { w -> w.replaceFirstChar { c -> c.uppercase() } } }`, hints: ['typealias creates a named function type.', 'Each strategy is a lambda assigned to a val.', 'Strategies are interchangeable.'], concepts: ['typealias', 'strategy'] },
    { id: 'kt-strategy-3', title: 'Sealed Class Strategy', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use sealed class for named strategies.', skeleton: `___ class CompressionStrategy {\n    object None : CompressionStrategy()\n    object Gzip : CompressionStrategy()\n    object Zlib : CompressionStrategy()\n}\n\nfun compress(data: String, strategy: CompressionStrategy): String = when (strategy) {\n    CompressionStrategy.None -> data\n    CompressionStrategy.Gzip -> "gzip(\${data})"\n    CompressionStrategy.Zlib -> "zlib(\${data})"\n}`, solution: `sealed class CompressionStrategy {\n    object None : CompressionStrategy()\n    object Gzip : CompressionStrategy()\n    object Zlib : CompressionStrategy()\n}\n\nfun compress(data: String, strategy: CompressionStrategy): String = when (strategy) {\n    CompressionStrategy.None -> data\n    CompressionStrategy.Gzip -> "gzip(\${data})"\n    CompressionStrategy.Zlib -> "zlib(\${data})"\n}`, hints: ['sealed class enumerates all strategies.', 'when is exhaustive for sealed classes.', 'Each strategy is an object singleton.'], concepts: ['sealed-class', 'strategy', 'when'] },
    { id: 'kt-strategy-4', title: 'Interface Strategy', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Define a strategy with a fun interface.', skeleton: `___ interface PricingStrategy {\n    fun calculate(basePrice: Double): Double\n}\n\nval regular = PricingStrategy { it }\nval premium = PricingStrategy { it * 0.9 }\nval vip = PricingStrategy { it * 0.8 }`, solution: `fun interface PricingStrategy {\n    fun calculate(basePrice: Double): Double\n}\n\nval regular = PricingStrategy { it }\nval premium = PricingStrategy { it * 0.9 }\nval vip = PricingStrategy { it * 0.8 }`, hints: ['fun interface enables SAM conversion.', 'Each strategy is defined as a lambda.', 'Regular gets full price, VIP gets 20% off.'], concepts: ['fun-interface', 'SAM-conversion', 'pricing'] },
    { id: 'kt-strategy-5', title: 'Strategy with Data', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create strategies that carry configuration data.', skeleton: `sealed class RetryStrategy {\n    object NoRetry : RetryStrategy()\n    data class FixedDelay(val delayMs: Long, val maxRetries: Int) : RetryStrategy()\n    data class ExponentialBackoff(val initialMs: Long, val maxRetries: Int) : RetryStrategy()\n}\n\nfun getDelays(strategy: RetryStrategy): List<Long> = ___(strategy) {\n    is RetryStrategy.NoRetry -> emptyList()\n    is RetryStrategy.FixedDelay -> List(strategy.maxRetries) { strategy.delayMs }\n    is RetryStrategy.ExponentialBackoff -> List(strategy.maxRetries) { strategy.initialMs * (1L shl it) }\n}`, solution: `sealed class RetryStrategy {\n    object NoRetry : RetryStrategy()\n    data class FixedDelay(val delayMs: Long, val maxRetries: Int) : RetryStrategy()\n    data class ExponentialBackoff(val initialMs: Long, val maxRetries: Int) : RetryStrategy()\n}\n\nfun getDelays(strategy: RetryStrategy): List<Long> = when(strategy) {\n    is RetryStrategy.NoRetry -> emptyList()\n    is RetryStrategy.FixedDelay -> List(strategy.maxRetries) { strategy.delayMs }\n    is RetryStrategy.ExponentialBackoff -> List(strategy.maxRetries) { strategy.initialMs * (1L shl it) }\n}`, hints: ['Sealed data classes carry configuration.', 'when with smart cast accesses strategy-specific data.', 'shl is bitwise shift left for exponential.'], concepts: ['sealed-data-class', 'configuration', 'smart-cast'] },
    { id: 'kt-strategy-6', title: 'Strategy Map', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Store strategies in a map for dynamic selection.', skeleton: `typealias Hasher = (String) -> Int\n\nval strategies = ___<String, Hasher>(\n    "length" to { it.length },\n    "first" to { it.firstOrNull()?.code ?: 0 },\n    "sum" to { it.sumOf { c -> c.code } }\n)\n\nfun hash(input: String, method: String): Int {\n    return strategies[method]?.invoke(input) ?: throw IllegalArgumentException("Unknown")\n}`, solution: `typealias Hasher = (String) -> Int\n\nval strategies = mapOf<String, Hasher>(\n    "length" to { it.length },\n    "first" to { it.firstOrNull()?.code ?: 0 },\n    "sum" to { it.sumOf { c -> c.code } }\n)\n\nfun hash(input: String, method: String): Int {\n    return strategies[method]?.invoke(input) ?: throw IllegalArgumentException("Unknown")\n}`, hints: ['mapOf stores named strategies.', 'Dynamic lookup by string key.', 'invoke() calls the selected strategy.'], concepts: ['strategy-map', 'dynamic-selection'] },
    { id: 'kt-strategy-7', title: 'Write a Sorting Strategy', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a sorting function that accepts different strategies.', skeleton: `// Write:\n// 1. data class Product(val name: String, val price: Double, val rating: Int)\n// 2. typealias SortStrategy = Comparator<Product>\n// 3. val byPrice: SortStrategy, val byRating: SortStrategy, val byName: SortStrategy\n// 4. fun sortProducts(products: List<Product>, strategy: SortStrategy): List<Product>`, solution: `data class Product(val name: String, val price: Double, val rating: Int)\n\ntypealias SortStrategy = Comparator<Product>\n\nval byPrice: SortStrategy = compareBy { it.price }\nval byRating: SortStrategy = compareByDescending { it.rating }\nval byName: SortStrategy = compareBy { it.name }\n\nfun sortProducts(products: List<Product>, strategy: SortStrategy): List<Product> {\n    return products.sortedWith(strategy)\n}`, hints: ['compareBy creates a Comparator.', 'sortedWith applies the comparator.', 'Each val is a different sort strategy.'], concepts: ['Comparator', 'compareBy', 'sortedWith'] },
    { id: 'kt-strategy-8', title: 'Write a Validation Strategy', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write composable validation strategies.', skeleton: `// Write:\n// 1. typealias Validator = (String) -> String? (null = valid, String = error)\n// 2. val notBlank, val minLength(n), val hasDigit validators\n// 3. fun validate(value: String, vararg validators: Validator): List<String>`, solution: `typealias Validator = (String) -> String?\n\nval notBlank: Validator = { if (it.isBlank()) "Must not be blank" else null }\nfun minLength(n: Int): Validator = { if (it.length < n) "Must be at least \${n} chars" else null }\nval hasDigit: Validator = { if (it.none { c -> c.isDigit() }) "Must contain a digit" else null }\n\nfun validate(value: String, vararg validators: Validator): List<String> {\n    return validators.mapNotNull { it(value) }\n}`, hints: ['Validators return error message or null.', 'mapNotNull collects only non-null errors.', 'vararg allows passing multiple validators.'], concepts: ['validator', 'composition', 'mapNotNull'] },
    { id: 'kt-strategy-9', title: 'Write a Rate Limiting Strategy', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write different rate limiting strategies.', skeleton: `// Write:\n// 1. fun interface RateLimiter with fun allow(): Boolean\n// 2. class NoLimit : RateLimiter that always returns true\n// 3. class FixedWindow(maxCalls: Int) that counts and blocks after max\n// 4. fun createLimiter(type: String, max: Int = 10): RateLimiter`, solution: `fun interface RateLimiter {\n    fun allow(): Boolean\n}\n\nclass NoLimit : RateLimiter {\n    override fun allow() = true\n}\n\nclass FixedWindow(private val maxCalls: Int) : RateLimiter {\n    private var count = 0\n    override fun allow(): Boolean {\n        return if (count < maxCalls) { count++; true } else false\n    }\n    fun reset() { count = 0 }\n}\n\nfun createLimiter(type: String, max: Int = 10): RateLimiter = when (type) {\n    "none" -> NoLimit()\n    "fixed" -> FixedWindow(max)\n    else -> NoLimit()\n}`, hints: ['Each limiter has different allow() logic.', 'NoLimit always allows, FixedWindow counts.', 'Factory function selects the strategy.'], concepts: ['rate-limiting', 'fun-interface', 'factory'] },
    { id: 'kt-strategy-10', title: 'Write a Serialization Strategy', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write interchangeable serialization strategies.', skeleton: `// Write:\n// 1. fun interface Serializer<T> with fun serialize(value: T): String\n// 2. For data class User(val name: String, val age: Int):\n//    jsonSerializer that returns {"name":"...","age":...}\n//    csvSerializer that returns "name,age"\n//    xmlSerializer that returns <user><name>...</name><age>...</age></user>`, solution: `data class User(val name: String, val age: Int)\n\nfun interface Serializer<T> {\n    fun serialize(value: T): String\n}\n\nval jsonSerializer = Serializer<User> { """{"name":"\${it.name}","age":\${it.age}}""" }\nval csvSerializer = Serializer<User> { "\${it.name},\${it.age}" }\nval xmlSerializer = Serializer<User> { "<user><name>\${it.name}</name><age>\${it.age}</age></user>" }`, hints: ['Each serializer produces a different format.', 'fun interface enables lambda assignment.', 'Same data, different output format.'], concepts: ['serializer-strategy', 'fun-interface', 'formats'] },
    { id: 'kt-strategy-11', title: 'Write a Composable Strategy', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write strategies that can be composed together.', skeleton: `// Write:\n// 1. typealias Transform = (String) -> String\n// 2. infix fun Transform.then(other: Transform): Transform\n//    that chains: first this, then other\n// 3. val trim, val lowercase, val removeSpaces transforms\n// 4. Compose: trim then lowercase then removeSpaces`, solution: `typealias Transform = (String) -> String\n\ninfix fun Transform.then(other: Transform): Transform = { other(this(it)) }\n\nval trim: Transform = { it.trim() }\nval lowercase: Transform = { it.lowercase() }\nval removeSpaces: Transform = { it.replace(" ", "") }\n\nfun main() {\n    val pipeline = trim then lowercase then removeSpaces\n    println(pipeline("  Hello World  "))\n}`, hints: ['then chains two transforms.', 'infix allows natural reading.', 'Pipeline processes left to right.'], concepts: ['composition', 'infix', 'pipeline'] },
    { id: 'kt-strategy-12', title: 'Write a Strategy with Context', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a strategy pattern with execution context.', skeleton: `// Write:\n// 1. data class Context(val userId: String, val isAdmin: Boolean)\n// 2. fun interface AuthStrategy with fun authorize(ctx: Context, resource: String): Boolean\n// 3. val allowAll, val adminOnly, val ownerOnly(ownerId: String) strategies\n// 4. class ResourceGuard(strategy: AuthStrategy) with fun check(ctx, resource): Boolean`, solution: `data class Context(val userId: String, val isAdmin: Boolean)\n\nfun interface AuthStrategy {\n    fun authorize(ctx: Context, resource: String): Boolean\n}\n\nval allowAll = AuthStrategy { _, _ -> true }\nval adminOnly = AuthStrategy { ctx, _ -> ctx.isAdmin }\nfun ownerOnly(ownerId: String) = AuthStrategy { ctx, _ -> ctx.userId == ownerId }\n\nclass ResourceGuard(private val strategy: AuthStrategy) {\n    fun check(ctx: Context, resource: String): Boolean = strategy.authorize(ctx, resource)\n}`, hints: ['Context provides execution information.', 'Each strategy checks different conditions.', 'ResourceGuard delegates to the strategy.'], concepts: ['context', 'authorization', 'delegation'] },
    { id: 'kt-strategy-13', title: 'Fix Hardcoded Strategy', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix code that hardcodes a strategy instead of accepting it.', skeleton: `fun formatNumbers(numbers: List<Int>): String {\n    // Hardcoded to always sort ascending!\n    return numbers.sorted().joinToString(", ")\n}`, solution: `fun formatNumbers(numbers: List<Int>, strategy: (List<Int>) -> List<Int> = { it.sorted() }): String {\n    return strategy(numbers).joinToString(", ")\n}`, hints: ['Accept strategy as a parameter.', 'Provide a default for backward compatibility.', 'Callers can now pass any ordering.'], concepts: ['strategy-parameter', 'default-parameter'] },
    { id: 'kt-strategy-14', title: 'Fix Mutable Strategy State', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix strategy that mutates shared state.', skeleton: `class Counter {\n    var count = 0\n}\n\nval countingFilter: (Int, Counter) -> Boolean = { value, counter ->\n    counter.count++\n    value > 5\n}\n\n// Shared mutable counter between calls is dangerous!`, solution: `fun interface FilterStrategy {\n    fun test(value: Int): Boolean\n}\n\nval greaterThan5 = FilterStrategy { it > 5 }\n\nfun filterItems(items: List<Int>, strategy: FilterStrategy): List<Int> {\n    return items.filter { strategy.test(it) }\n}`, hints: ['Strategies should be stateless.', 'Remove the mutable Counter.', 'Pure functions are safer strategies.'], concepts: ['stateless', 'pure-function', 'strategy'] },
    { id: 'kt-strategy-15', title: 'Fix Missing Strategy Case', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix non-exhaustive strategy handling.', skeleton: `enum class LogLevel { DEBUG, INFO, WARN, ERROR }\n\nfun formatLog(level: LogLevel, message: String): String = when (level) {\n    LogLevel.DEBUG -> "[D] \${message}"\n    LogLevel.INFO -> "[I] \${message}"\n    LogLevel.WARN -> "[W] \${message}"\n    // Missing ERROR!\n    else -> message\n}`, solution: `enum class LogLevel { DEBUG, INFO, WARN, ERROR }\n\nfun formatLog(level: LogLevel, message: String): String = when (level) {\n    LogLevel.DEBUG -> "[D] \${message}"\n    LogLevel.INFO -> "[I] \${message}"\n    LogLevel.WARN -> "[W] \${message}"\n    LogLevel.ERROR -> "[E] \${message}"\n}`, hints: ['Handle all enum values explicitly.', 'Remove else to get compiler warnings on missing cases.', 'Add the ERROR case.'], concepts: ['exhaustive-when', 'enum'] },
    { id: 'kt-strategy-16', title: 'Predict Strategy Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict which strategy is applied.', skeleton: `typealias Transform = (Int) -> Int\n\nval double: Transform = { it * 2 }\nval square: Transform = { it * it }\nval negate: Transform = { -it }\n\nfun apply(value: Int, strategy: Transform) = strategy(value)\n\nfun main() {\n    println(apply(5, double))\n    println(apply(5, square))\n    println(apply(5, negate))\n}`, solution: `10\n25\n-5`, hints: ['double: 5 * 2 = 10.', 'square: 5 * 5 = 25.', 'negate: -5.'], concepts: ['function-strategy', 'application'] },
    { id: 'kt-strategy-17', title: 'Predict Composed Strategy', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of composed strategies.', skeleton: `fun compose(a: (Int) -> Int, b: (Int) -> Int): (Int) -> Int = { b(a(it)) }\n\nfun main() {\n    val doubleAndAdd1 = compose({ it * 2 }, { it + 1 })\n    println(doubleAndAdd1(5))\n}`, solution: `11`, hints: ['First doubles: 5 * 2 = 10.', 'Then adds 1: 10 + 1 = 11.', 'compose chains a then b.'], concepts: ['composition', 'chaining'] },
    { id: 'kt-strategy-18', title: 'Predict Sealed Strategy', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict sealed class strategy result.', skeleton: `sealed class Discount {\n    object None : Discount()\n    data class Percentage(val pct: Double) : Discount()\n    data class Fixed(val amount: Double) : Discount()\n}\n\nfun apply(price: Double, discount: Discount): Double = when (discount) {\n    is Discount.None -> price\n    is Discount.Percentage -> price * (1 - discount.pct / 100)\n    is Discount.Fixed -> price - discount.amount\n}\n\nfun main() {\n    println(apply(100.0, Discount.Percentage(20.0)))\n}`, solution: `80.0`, hints: ['20% off 100 = 80.', '100 * (1 - 20/100) = 100 * 0.8 = 80.', 'Percentage strategy calculates discount.'], concepts: ['sealed-class', 'discount'] },
    { id: 'kt-strategy-19', title: 'Refactor if/else to Strategy', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor conditional logic to strategy pattern.', skeleton: `fun calculateShipping(weight: Double, method: String): Double {\n    return if (method == "standard") {\n        weight * 1.0\n    } else if (method == "express") {\n        weight * 2.5\n    } else if (method == "overnight") {\n        weight * 5.0 + 10.0\n    } else {\n        throw IllegalArgumentException("Unknown")\n    }\n}`, solution: `fun interface ShippingStrategy {\n    fun calculate(weight: Double): Double\n}\n\nval standard = ShippingStrategy { it * 1.0 }\nval express = ShippingStrategy { it * 2.5 }\nval overnight = ShippingStrategy { it * 5.0 + 10.0 }\n\nfun calculateShipping(weight: Double, strategy: ShippingStrategy): Double {\n    return strategy.calculate(weight)\n}`, hints: ['Extract each branch to a strategy.', 'fun interface allows lambda syntax.', 'Caller selects strategy, not the function.'], concepts: ['strategy-refactoring', 'fun-interface'] },
    { id: 'kt-strategy-20', title: 'Refactor Enum to Sealed Strategy', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor enum-based behavior to sealed class strategy.', skeleton: `enum class FileType { CSV, JSON, XML }\n\nfun export(data: List<String>, type: FileType): String = when (type) {\n    FileType.CSV -> data.joinToString(",")\n    FileType.JSON -> "[" + data.joinToString(",") { "\\"\${it}\\"" } + "]"\n    FileType.XML -> "<items>" + data.joinToString("") { "<item>\${it}</item>" } + "</items>"\n}`, solution: `sealed class ExportStrategy {\n    abstract fun export(data: List<String>): String\n\n    object Csv : ExportStrategy() {\n        override fun export(data: List<String>) = data.joinToString(",")\n    }\n    object Json : ExportStrategy() {\n        override fun export(data: List<String>) = "[" + data.joinToString(",") { "\\"\${it}\\"" } + "]"\n    }\n    object Xml : ExportStrategy() {\n        override fun export(data: List<String>) = "<items>" + data.joinToString("") { "<item>\${it}</item>" } + "</items>"\n    }\n}\n\nfun export(data: List<String>, strategy: ExportStrategy): String = strategy.export(data)`, hints: ['Sealed class encapsulates behavior with data.', 'Each strategy knows how to export.', 'New formats can be added without modifying export function.'], concepts: ['sealed-class', 'encapsulation', 'open-closed'] },
  ],
};
