import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-builder',
  title: '46. Builder Pattern',
  explanation: `## Builder Pattern in Kotlin

The Builder pattern constructs complex objects step by step. Kotlin's \`apply\`, DSL builders, and \`@DslMarker\` make this exceptionally clean.

### Traditional Builder
\`\`\`kotlin
class Pizza private constructor(
    val size: String,
    val cheese: Boolean,
    val pepperoni: Boolean
) {
    class Builder {
        private var size = "medium"
        private var cheese = false
        private var pepperoni = false
        fun size(s: String) = apply { size = s }
        fun cheese() = apply { cheese = true }
        fun pepperoni() = apply { pepperoni = true }
        fun build() = Pizza(size, cheese, pepperoni)
    }
}
\`\`\`

### DSL-Style Builder
\`\`\`kotlin
fun html(init: HTML.() -> Unit): HTML = HTML().apply(init)

html {
    head { title("Page") }
    body { p("Hello") }
}
\`\`\`

### buildList / buildMap
\`\`\`kotlin
val items = buildList {
    add("first")
    addAll(listOf("second", "third"))
    if (condition) add("optional")
}
\`\`\`

### @DslMarker
\`\`\`kotlin
@DslMarker
annotation class HtmlDsl

@HtmlDsl
class HTML { ... }
\`\`\``,
  exercises: [
    { id: 'kt-builder-1', title: 'Basic Builder Class', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Complete a basic builder with apply.', skeleton: `class User private constructor(val name: String, val age: Int) {\n    class Builder {\n        private var name = ""\n        private var age = 0\n        fun name(n: String) = ___(this) { name = n }\n        fun age(a: Int) = apply { age = a }\n        fun build() = User(name, age)\n    }\n}`, solution: `class User private constructor(val name: String, val age: Int) {\n    class Builder {\n        private var name = ""\n        private var age = 0\n        fun name(n: String) = apply(this) { name = n }\n        fun age(a: Int) = apply { age = a }\n        fun build() = User(name, age)\n    }\n}`, hints: ['apply returns the receiver after executing the block.', 'apply { ... } is idiomatic for builder methods.', 'Each method sets a field and returns this.'], concepts: ['builder-pattern', 'apply'] },
    { id: 'kt-builder-2', title: 'Builder with apply', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Use apply to configure an object.', skeleton: `data class Config(var host: String = "", var port: Int = 0, var ssl: Boolean = false)\n\nfun createConfig(): Config = Config().___ {\n    host = "localhost"\n    port = 8080\n    ssl = true\n}`, solution: `data class Config(var host: String = "", var port: Int = 0, var ssl: Boolean = false)\n\nfun createConfig(): Config = Config().apply {\n    host = "localhost"\n    port = 8080\n    ssl = true\n}`, hints: ['apply sets properties on the receiver.', 'apply returns the same object.', 'No need for a separate Builder class.'], concepts: ['apply', 'configuration'] },
    { id: 'kt-builder-3', title: 'DSL Builder Init Lambda', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a DSL builder using an init lambda.', skeleton: `class Menu {\n    private val items = mutableListOf<String>()\n    fun item(name: String) { items.add(name) }\n    override fun toString() = items.joinToString(", ")\n}\n\nfun menu(init: Menu.___ Unit): Menu {\n    return Menu().apply(init)\n}`, solution: `class Menu {\n    private val items = mutableListOf<String>()\n    fun item(name: String) { items.add(name) }\n    override fun toString() = items.joinToString(", ")\n}\n\nfun menu(init: Menu.() -> Unit): Menu {\n    return Menu().apply(init)\n}`, hints: ['Menu.() -> Unit is a lambda with receiver.', 'The receiver becomes this inside the lambda.', 'apply passes the object as receiver.'], concepts: ['lambda-with-receiver', 'dsl-builder'] },
    { id: 'kt-builder-4', title: 'buildList Usage', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Use buildList to construct an immutable list.', skeleton: `val numbers = ___ {\n    add(1)\n    add(2)\n    addAll(listOf(3, 4, 5))\n    if (true) add(6)\n}`, solution: `val numbers = buildList {\n    add(1)\n    add(2)\n    addAll(listOf(3, 4, 5))\n    if (true) add(6)\n}`, hints: ['buildList creates a MutableList internally.', 'Returns an immutable List when done.', 'Conditional logic works inside the builder.'], concepts: ['buildList', 'collection-builder'] },
    { id: 'kt-builder-5', title: 'buildMap Usage', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Use buildMap to construct an immutable map.', skeleton: `val settings = ___<String, Any> {\n    put("theme", "dark")\n    put("fontSize", 14)\n    put("autoSave", true)\n}`, solution: `val settings = buildMap<String, Any> {\n    put("theme", "dark")\n    put("fontSize", 14)\n    put("autoSave", true)\n}`, hints: ['buildMap works like buildList but for maps.', 'put() adds key-value pairs.', 'Returns an immutable Map.'], concepts: ['buildMap', 'collection-builder'] },
    { id: 'kt-builder-6', title: '@DslMarker Annotation', type: 'fill-blank', difficulty: 'advanced', language: 'kotlin', goal: 'Use @DslMarker to restrict DSL scope.', skeleton: `@___\nannotation class FormDsl\n\n@FormDsl\nclass Form {\n    private val fields = mutableListOf<Field>()\n    fun field(init: Field.() -> Unit) { fields.add(Field().apply(init)) }\n}\n\n@FormDsl\nclass Field {\n    var name = ""\n    var required = false\n}`, solution: `@DslMarker\nannotation class FormDsl\n\n@FormDsl\nclass Form {\n    private val fields = mutableListOf<Field>()\n    fun field(init: Field.() -> Unit) { fields.add(Field().apply(init)) }\n}\n\n@FormDsl\nclass Field {\n    var name = ""\n    var required = false\n}`, hints: ['@DslMarker prevents accessing outer receivers implicitly.', 'Annotate the annotation class with @DslMarker.', 'Both Form and Field share the same DSL marker.'], concepts: ['DslMarker', 'scope-control'] },
    { id: 'kt-builder-7', title: 'Write a Traditional Builder', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a full builder pattern for an Email class.', skeleton: `// Write:\n// 1. data class Email with to, from, subject, body (all String)\n// 2. class EmailBuilder with matching private vars (defaults "")\n// 3. Builder methods: to(), from(), subject(), body() - each returns this\n// 4. build() returns Email\n// 5. Top-level fun buildEmail(init: EmailBuilder.() -> Unit): Email`, solution: `data class Email(val to: String, val from: String, val subject: String, val body: String)\n\nclass EmailBuilder {\n    private var to = ""\n    private var from = ""\n    private var subject = ""\n    private var body = ""\n\n    fun to(v: String) = apply { to = v }\n    fun from(v: String) = apply { from = v }\n    fun subject(v: String) = apply { subject = v }\n    fun body(v: String) = apply { body = v }\n    fun build() = Email(to, from, subject, body)\n}\n\nfun buildEmail(init: EmailBuilder.() -> Unit): Email {\n    return EmailBuilder().apply(init).build()\n}`, hints: ['apply returns the builder itself.', 'build() creates the immutable data class.', 'Top-level function wraps builder creation.'], concepts: ['builder-pattern', 'data-class', 'apply'] },
    { id: 'kt-builder-8', title: 'Write a Nested DSL Builder', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write nested DSL builders for an HTML-like structure.', skeleton: `// Write:\n// 1. class Document with title: String, sections: List<Section>\n// 2. class Section with heading: String, paragraphs: List<String>\n// 3. class DocumentBuilder with fun section(init: SectionBuilder.() -> Unit)\n// 4. class SectionBuilder with heading(String), paragraph(String)\n// 5. fun document(init: DocumentBuilder.() -> Unit): Document`, solution: `data class Section(val heading: String, val paragraphs: List<String>)\ndata class Document(val title: String, val sections: List<Section>)\n\nclass SectionBuilder {\n    var heading = ""\n    private val paragraphs = mutableListOf<String>()\n    fun paragraph(text: String) { paragraphs.add(text) }\n    fun build() = Section(heading, paragraphs.toList())\n}\n\nclass DocumentBuilder {\n    var title = ""\n    private val sections = mutableListOf<Section>()\n    fun section(init: SectionBuilder.() -> Unit) {\n        sections.add(SectionBuilder().apply(init).build())\n    }\n    fun build() = Document(title, sections.toList())\n}\n\nfun document(init: DocumentBuilder.() -> Unit): Document {\n    return DocumentBuilder().apply(init).build()\n}`, hints: ['Each builder has its own class.', 'section() creates a SectionBuilder and applies the init block.', 'build() converts mutable state to immutable data.'], concepts: ['nested-builder', 'dsl', 'lambda-with-receiver'] },
    { id: 'kt-builder-9', title: 'Write Builder with Validation', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a builder that validates before building.', skeleton: `// Write:\n// 1. data class Server(val host: String, val port: Int, val maxConn: Int)\n// 2. class ServerBuilder with host, port, maxConn vars\n// 3. build() that throws IllegalStateException if:\n//    - host is blank\n//    - port not in 1..65535\n//    - maxConn < 1\n// 4. fun server(init: ServerBuilder.() -> Unit): Server`, solution: `data class Server(val host: String, val port: Int, val maxConn: Int)\n\nclass ServerBuilder {\n    var host = ""\n    var port = 8080\n    var maxConn = 100\n\n    fun build(): Server {\n        require(host.isNotBlank()) { "Host must not be blank" }\n        require(port in 1..65535) { "Port must be 1..65535" }\n        require(maxConn >= 1) { "MaxConn must be >= 1" }\n        return Server(host, port, maxConn)\n    }\n}\n\nfun server(init: ServerBuilder.() -> Unit): Server {\n    return ServerBuilder().apply(init).build()\n}`, hints: ['require() throws IllegalArgumentException on failure.', 'Validate all fields before constructing.', 'apply(init) configures, then build() validates.'], concepts: ['validation', 'require', 'builder'] },
    { id: 'kt-builder-10', title: 'Write Immutable Builder with copy', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write an immutable builder using data class copy.', skeleton: `// Write:\n// 1. data class Theme(val primary: String = "#000", val secondary: String = "#fff",\n//    val fontSize: Int = 14, val darkMode: Boolean = false)\n// 2. fun Theme.modify(init: ThemeBuilder.() -> Unit): Theme\n//    using a ThemeBuilder that reads current values and produces a new Theme\n// 3. ThemeBuilder has var primary, secondary, fontSize, darkMode\n//    and build() returns Theme`, solution: `data class Theme(\n    val primary: String = "#000",\n    val secondary: String = "#fff",\n    val fontSize: Int = 14,\n    val darkMode: Boolean = false\n)\n\nclass ThemeBuilder(theme: Theme) {\n    var primary = theme.primary\n    var secondary = theme.secondary\n    var fontSize = theme.fontSize\n    var darkMode = theme.darkMode\n    fun build() = Theme(primary, secondary, fontSize, darkMode)\n}\n\nfun Theme.modify(init: ThemeBuilder.() -> Unit): Theme {\n    return ThemeBuilder(this).apply(init).build()\n}`, hints: ['ThemeBuilder reads current values from the Theme.', 'modify creates a new Theme without mutating.', 'Extension function provides fluent API.'], concepts: ['immutable-builder', 'copy-pattern', 'extension-function'] },
    { id: 'kt-builder-11', title: 'Write Type-Safe Builder', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a type-safe SQL query builder.', skeleton: `// Write:\n// 1. class QueryBuilder with:\n//    - private var table: String, cols: List<String>, condition: String?\n//    - fun from(table: String)\n//    - fun select(vararg cols: String)\n//    - fun where(cond: String)\n//    - fun build(): String returning "SELECT cols FROM table [WHERE cond]"\n// 2. fun query(init: QueryBuilder.() -> Unit): String`, solution: `class QueryBuilder {\n    private var table = ""\n    private var cols = listOf("*")\n    private var condition: String? = null\n\n    fun from(t: String) { table = t }\n    fun select(vararg c: String) { cols = c.toList() }\n    fun where(cond: String) { condition = cond }\n\n    fun build(): String {\n        require(table.isNotBlank()) { "Table required" }\n        val base = "SELECT \${cols.joinToString(", ")} FROM \${table}"\n        return if (condition != null) "\${base} WHERE \${condition}" else base\n    }\n}\n\nfun query(init: QueryBuilder.() -> Unit): String {\n    return QueryBuilder().apply(init).build()\n}`, hints: ['from sets the table name.', 'select sets columns, defaulting to *.', 'where is optional and appends a condition.'], concepts: ['type-safe-builder', 'query-dsl'] },
    { id: 'kt-builder-12', title: 'Write Builder Inheritance', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write builders that use inheritance.', skeleton: `// Write:\n// 1. open class BaseNotification(open val to: String, open val message: String)\n// 2. class EmailNotification(to, message, val subject: String) : BaseNotification\n// 3. class SmsNotification(to, message, val urgent: Boolean) : BaseNotification\n// 4. open class NotificationBuilder with var to, var message\n// 5. class EmailNotificationBuilder : NotificationBuilder with var subject, build()\n// 6. class SmsNotificationBuilder : NotificationBuilder with var urgent, build()`, solution: `open class BaseNotification(open val to: String, open val message: String)\nclass EmailNotification(to: String, message: String, val subject: String) : BaseNotification(to, message)\nclass SmsNotification(to: String, message: String, val urgent: Boolean) : BaseNotification(to, message)\n\nopen class NotificationBuilder {\n    var to = ""\n    var message = ""\n}\n\nclass EmailNotificationBuilder : NotificationBuilder() {\n    var subject = ""\n    fun build() = EmailNotification(to, message, subject)\n}\n\nclass SmsNotificationBuilder : NotificationBuilder() {\n    var urgent = false\n    fun build() = SmsNotification(to, message, urgent)\n}\n\nfun email(init: EmailNotificationBuilder.() -> Unit) = EmailNotificationBuilder().apply(init).build()\nfun sms(init: SmsNotificationBuilder.() -> Unit) = SmsNotificationBuilder().apply(init).build()`, hints: ['Base builder holds shared fields.', 'Subclass builders add type-specific fields.', 'Each build() returns its own type.'], concepts: ['builder-inheritance', 'open-class'] },
    { id: 'kt-builder-13', title: 'Fix Missing build() Call', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix a builder that returns itself instead of the built object.', skeleton: `data class Car(val make: String, val model: String, val year: Int)\n\nclass CarBuilder {\n    var make = ""\n    var model = ""\n    var year = 2024\n    fun build() = Car(make, model, year)\n}\n\nfun createCar(): Car {\n    val builder = CarBuilder().apply {\n        make = "Toyota"\n        model = "Camry"\n        year = 2024\n    }\n    return builder  // Error: Type mismatch\n}`, solution: `data class Car(val make: String, val model: String, val year: Int)\n\nclass CarBuilder {\n    var make = ""\n    var model = ""\n    var year = 2024\n    fun build() = Car(make, model, year)\n}\n\nfun createCar(): Car {\n    val builder = CarBuilder().apply {\n        make = "Toyota"\n        model = "Camry"\n        year = 2024\n    }\n    return builder.build()\n}`, hints: ['apply returns the CarBuilder, not a Car.', 'Call build() to get the final object.', 'builder is a CarBuilder, not a Car.'], concepts: ['builder-pattern', 'apply-returns-receiver'] },
    { id: 'kt-builder-14', title: 'Fix Mutable Leaking Builder', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a builder that leaks mutable state.', skeleton: `class ListBuilder {\n    val items = mutableListOf<String>()\n    fun add(item: String) = apply { items.add(item) }\n    fun build() = items  // Leaks mutable list!\n}\n\nfun main() {\n    val builder = ListBuilder().add("a").add("b")\n    val result = builder.build()\n    result.add("hacked!")  // Can modify internal state!\n}`, solution: `class ListBuilder {\n    private val items = mutableListOf<String>()\n    fun add(item: String) = apply { items.add(item) }\n    fun build(): List<String> = items.toList()\n}\n\nfun main() {\n    val builder = ListBuilder().add("a").add("b")\n    val result = builder.build()\n    // result.add("hacked!")  // Compile error: List has no add()\n}`, hints: ['build() returns the same mutable list reference.', 'Use toList() to return an immutable copy.', 'Make items private to prevent external access.'], concepts: ['defensive-copy', 'immutability', 'encapsulation'] },
    { id: 'kt-builder-15', title: 'Fix DSL Scope Leaking', type: 'fix-bug', difficulty: 'advanced', language: 'kotlin', goal: 'Fix a DSL where inner builder accesses outer receiver.', skeleton: `class Outer {\n    var name = ""\n    val inners = mutableListOf<Inner>()\n    fun inner(init: Inner.() -> Unit) { inners.add(Inner().apply(init)) }\n}\n\nclass Inner {\n    var value = ""\n}\n\nfun outer(init: Outer.() -> Unit) = Outer().apply(init)\n\n// Bug: Inside inner{}, you can access outer's name!\nval o = outer {\n    name = "parent"\n    inner {\n        value = "child"\n        name = "oops"  // This modifies Outer.name from inside Inner!\n    }\n}`, solution: `@DslMarker\nannotation class ScopeDsl\n\n@ScopeDsl\nclass Outer {\n    var name = ""\n    val inners = mutableListOf<Inner>()\n    fun inner(init: Inner.() -> Unit) { inners.add(Inner().apply(init)) }\n}\n\n@ScopeDsl\nclass Inner {\n    var value = ""\n}\n\nfun outer(init: Outer.() -> Unit) = Outer().apply(init)\n\nval o = outer {\n    name = "parent"\n    inner {\n        value = "child"\n        // name = "oops"  // Now compile error: scope restricted by @DslMarker\n    }\n}`, hints: ['@DslMarker prevents implicit access to outer receivers.', 'Create a custom annotation marked with @DslMarker.', 'Apply the annotation to both Outer and Inner.'], concepts: ['DslMarker', 'scope-restriction', 'dsl-safety'] },
    { id: 'kt-builder-16', title: 'Predict Builder Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the result of a builder chain.', skeleton: `data class Point(val x: Int, val y: Int)\n\nclass PointBuilder {\n    var x = 0\n    var y = 0\n    fun build() = Point(x, y)\n}\n\nfun main() {\n    val p = PointBuilder().apply {\n        x = 3\n        y = 4\n        x = x + y\n    }.build()\n    println(p)\n}`, solution: `Point(x=7, y=4)`, hints: ['x starts at 3, y is set to 4.', 'Then x = x + y = 3 + 4 = 7.', 'build() creates Point(7, 4).'], concepts: ['apply', 'evaluation-order'] },
    { id: 'kt-builder-17', title: 'Predict buildList Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of buildList with conditions.', skeleton: `fun main() {\n    val items = buildList {\n        add("a")\n        add("b")\n        if (size > 1) add("c")\n        removeFirst()\n        add("d")\n    }\n    println(items)\n}`, solution: `[b, c, d]`, hints: ['add a, add b -> [a, b], size is 2.', 'size > 1 is true, add c -> [a, b, c].', 'removeFirst removes a -> [b, c], add d -> [b, c, d].'], concepts: ['buildList', 'conditional-building'] },
    { id: 'kt-builder-18', title: 'Predict Nested Builder', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of nested builder calls.', skeleton: `class Tag(val name: String) {\n    val children = mutableListOf<Tag>()\n    fun tag(n: String, init: Tag.() -> Unit = {}) {\n        children.add(Tag(n).apply(init))\n    }\n    override fun toString(): String {\n        return if (children.isEmpty()) name\n        else "\${name}[\${children.joinToString(",")}]"\n    }\n}\n\nfun main() {\n    val root = Tag("a").apply {\n        tag("b") {\n            tag("c")\n        }\n        tag("d")\n    }\n    println(root)\n}`, solution: `a[b[c],d]`, hints: ['root is "a" with children "b" and "d".', '"b" has child "c" (no children of its own).', 'toString formats as name[child1,child2].'], concepts: ['nested-builder', 'tree-structure'] },
    { id: 'kt-builder-19', title: 'Refactor Constructor to Builder', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor a constructor with many params to use a builder.', skeleton: `class HttpRequest(\n    val method: String,\n    val url: String,\n    val headers: Map<String, String>,\n    val body: String?,\n    val timeout: Int,\n    val followRedirects: Boolean\n)\n\n// Ugly call:\nval req = HttpRequest("GET", "https://api.com", mapOf("Auth" to "token"), null, 30, true)`, solution: `class HttpRequest(\n    val method: String,\n    val url: String,\n    val headers: Map<String, String>,\n    val body: String?,\n    val timeout: Int,\n    val followRedirects: Boolean\n) {\n    class Builder {\n        var method = "GET"\n        var url = ""\n        private val headers = mutableMapOf<String, String>()\n        var body: String? = null\n        var timeout = 30\n        var followRedirects = true\n\n        fun header(key: String, value: String) = apply { headers[key] = value }\n        fun build() = HttpRequest(method, url, headers.toMap(), body, timeout, followRedirects)\n    }\n}\n\nfun httpRequest(init: HttpRequest.Builder.() -> Unit) = HttpRequest.Builder().apply(init).build()\n\nval req = httpRequest {\n    method = "GET"\n    url = "https://api.com"\n    header("Auth", "token")\n}`, hints: ['Builder provides defaults so most params are optional.', 'header() is a method instead of raw map construction.', 'DSL function wraps builder creation.'], concepts: ['builder-refactoring', 'named-params-alternative'] },
    { id: 'kt-builder-20', title: 'Refactor to also/let', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor verbose builder code to use also and let.', skeleton: `fun setupLogger(): Logger {\n    val logger = Logger()\n    logger.level = "DEBUG"\n    logger.format = "[%level] %message"\n    println("Logger created: \${logger.level}")\n    val handler = FileHandler()\n    handler.path = "/var/log/app.log"\n    handler.maxSize = 1024\n    logger.handler = handler\n    return logger\n}\n\nclass Logger {\n    var level = "INFO"\n    var format = "%message"\n    var handler: FileHandler? = null\n}\nclass FileHandler {\n    var path = ""\n    var maxSize = 0\n}`, solution: `fun setupLogger(): Logger = Logger().apply {\n    level = "DEBUG"\n    format = "[%level] %message"\n    handler = FileHandler().apply {\n        path = "/var/log/app.log"\n        maxSize = 1024\n    }\n}.also {\n    println("Logger created: \${it.level}")\n}\n\nclass Logger {\n    var level = "INFO"\n    var format = "%message"\n    var handler: FileHandler? = null\n}\nclass FileHandler {\n    var path = ""\n    var maxSize = 0\n}`, hints: ['apply configures the object, also performs side effects.', 'Nested apply configures the FileHandler.', 'also runs after apply and returns the same object.'], concepts: ['apply', 'also', 'scope-functions'] },
  ],
};
