import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-state',
  title: '47. State Pattern',
  explanation: `## State Pattern in Kotlin

The State pattern allows an object to change behavior when its internal state changes. Kotlin's sealed classes and \`when\` expressions make state machines expressive and type-safe.

### Sealed Class States
\`\`\`kotlin
sealed class DoorState {
    object Open : DoorState()
    object Closed : DoorState()
    object Locked : DoorState()
}
\`\`\`

### State Machine
\`\`\`kotlin
fun transition(state: DoorState, event: Event): DoorState = when (state) {
    is DoorState.Open -> when (event) {
        Event.Close -> DoorState.Closed
        else -> state
    }
    is DoorState.Closed -> when (event) {
        Event.Open -> DoorState.Open
        Event.Lock -> DoorState.Locked
        else -> state
    }
    is DoorState.Locked -> when (event) {
        Event.Unlock -> DoorState.Closed
        else -> state
    }
}
\`\`\`

### StateFlow for Reactive State
\`\`\`kotlin
val _state = MutableStateFlow<UiState>(UiState.Loading)
val state: StateFlow<UiState> = _state.asStateFlow()
\`\`\``,
  exercises: [
    { id: 'kt-state-1', title: 'Sealed Class States', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Define states using a sealed class.', skeleton: `___ class ConnectionState {\n    object Disconnected : ConnectionState()\n    object Connecting : ConnectionState()\n    object Connected : ConnectionState()\n    data class Error(val message: String) : ConnectionState()\n}`, solution: `sealed class ConnectionState {\n    object Disconnected : ConnectionState()\n    object Connecting : ConnectionState()\n    object Connected : ConnectionState()\n    data class Error(val message: String) : ConnectionState()\n}`, hints: ['sealed class restricts subclasses to the same file.', 'Each state is an object or data class.', 'Error carries a message as additional data.'], concepts: ['sealed-class', 'state-definition'] },
    { id: 'kt-state-2', title: 'when with State', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Handle states with an exhaustive when expression.', skeleton: `sealed class TrafficLight {\n    object Red : TrafficLight()\n    object Yellow : TrafficLight()\n    object Green : TrafficLight()\n}\n\nfun action(light: TrafficLight): String = ___(light) {\n    is TrafficLight.Red -> "Stop"\n    is TrafficLight.Yellow -> "Caution"\n    is TrafficLight.Green -> "Go"\n}`, solution: `sealed class TrafficLight {\n    object Red : TrafficLight()\n    object Yellow : TrafficLight()\n    object Green : TrafficLight()\n}\n\nfun action(light: TrafficLight): String = when(light) {\n    is TrafficLight.Red -> "Stop"\n    is TrafficLight.Yellow -> "Caution"\n    is TrafficLight.Green -> "Go"\n}`, hints: ['when is exhaustive for sealed classes.', 'No else branch needed.', 'is checks the subtype.'], concepts: ['when', 'exhaustive-matching'] },
    { id: 'kt-state-3', title: 'State Transition Function', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Implement a state transition function.', skeleton: `sealed class PlayerState {\n    object Idle : PlayerState()\n    object Playing : PlayerState()\n    object Paused : PlayerState()\n}\n\nenum class Action { Play, Pause, Stop }\n\nfun transition(state: PlayerState, action: Action): PlayerState = when (state) {\n    is PlayerState.Idle -> when (action) {\n        Action.Play -> PlayerState.___\n        else -> state\n    }\n    is PlayerState.Playing -> when (action) {\n        Action.Pause -> PlayerState.Paused\n        Action.Stop -> PlayerState.Idle\n        else -> state\n    }\n    is PlayerState.Paused -> when (action) {\n        Action.Play -> PlayerState.Playing\n        Action.Stop -> PlayerState.Idle\n        else -> state\n    }\n}`, solution: `sealed class PlayerState {\n    object Idle : PlayerState()\n    object Playing : PlayerState()\n    object Paused : PlayerState()\n}\n\nenum class Action { Play, Pause, Stop }\n\nfun transition(state: PlayerState, action: Action): PlayerState = when (state) {\n    is PlayerState.Idle -> when (action) {\n        Action.Play -> PlayerState.Playing\n        else -> state\n    }\n    is PlayerState.Playing -> when (action) {\n        Action.Pause -> PlayerState.Paused\n        Action.Stop -> PlayerState.Idle\n        else -> state\n    }\n    is PlayerState.Paused -> when (action) {\n        Action.Play -> PlayerState.Playing\n        Action.Stop -> PlayerState.Idle\n        else -> state\n    }\n}`, hints: ['From Idle, Play transitions to Playing.', 'Invalid actions return the current state.', 'Nested when handles action within each state.'], concepts: ['state-transition', 'nested-when'] },
    { id: 'kt-state-4', title: 'MutableStateFlow', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Create a reactive state holder with MutableStateFlow.', skeleton: `import kotlinx.coroutines.flow.*\n\nsealed class UiState {\n    object Loading : UiState()\n    data class Success(val data: String) : UiState()\n    data class Error(val msg: String) : UiState()\n}\n\nclass ViewModel {\n    private val _state = ___(UiState.Loading)\n    val state: StateFlow<UiState> = _state.asStateFlow()\n\n    fun loadData() {\n        _state.value = UiState.Success("loaded")\n    }\n}`, solution: `import kotlinx.coroutines.flow.*\n\nsealed class UiState {\n    object Loading : UiState()\n    data class Success(val data: String) : UiState()\n    data class Error(val msg: String) : UiState()\n}\n\nclass ViewModel {\n    private val _state = MutableStateFlow(UiState.Loading)\n    val state: StateFlow<UiState> = _state.asStateFlow()\n\n    fun loadData() {\n        _state.value = UiState.Success("loaded")\n    }\n}`, hints: ['MutableStateFlow holds a mutable current value.', 'asStateFlow() exposes a read-only view.', 'Setting .value emits the new state.'], concepts: ['MutableStateFlow', 'StateFlow', 'reactive-state'] },
    { id: 'kt-state-5', title: 'State with Data', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use data classes to carry state-specific information.', skeleton: `sealed class DownloadState {\n    object Idle : DownloadState()\n    ___ class Downloading(val progress: Int) : DownloadState()\n    data class Completed(val filePath: String) : DownloadState()\n    data class Failed(val error: Throwable) : DownloadState()\n}\n\nfun describe(state: DownloadState): String = when (state) {\n    is DownloadState.Idle -> "Ready"\n    is DownloadState.Downloading -> "Downloading: \${state.progress}%"\n    is DownloadState.Completed -> "Saved to \${state.filePath}"\n    is DownloadState.Failed -> "Error: \${state.error.message}"\n}`, solution: `sealed class DownloadState {\n    object Idle : DownloadState()\n    data class Downloading(val progress: Int) : DownloadState()\n    data class Completed(val filePath: String) : DownloadState()\n    data class Failed(val error: Throwable) : DownloadState()\n}\n\nfun describe(state: DownloadState): String = when (state) {\n    is DownloadState.Idle -> "Ready"\n    is DownloadState.Downloading -> "Downloading: \${state.progress}%"\n    is DownloadState.Completed -> "Saved to \${state.filePath}"\n    is DownloadState.Failed -> "Error: \${state.error.message}"\n}`, hints: ['data class carries associated data with the state.', 'Smart cast gives access to state-specific properties.', 'Downloading carries progress, Failed carries an error.'], concepts: ['data-class-state', 'smart-cast'] },
    { id: 'kt-state-6', title: 'Event-Driven State', type: 'fill-blank', difficulty: 'advanced', language: 'kotlin', goal: 'Implement event-driven state transitions with sealed events.', skeleton: `sealed class AuthState {\n    object LoggedOut : AuthState()\n    data class LoggedIn(val user: String) : AuthState()\n}\n\n___ class AuthEvent {\n    data class Login(val user: String, val pass: String) : AuthEvent()\n    object Logout : AuthEvent()\n}\n\nfun reduce(state: AuthState, event: AuthEvent): AuthState = when (event) {\n    is AuthEvent.Login -> AuthState.LoggedIn(event.user)\n    is AuthEvent.Logout -> AuthState.LoggedOut\n}`, solution: `sealed class AuthState {\n    object LoggedOut : AuthState()\n    data class LoggedIn(val user: String) : AuthState()\n}\n\nsealed class AuthEvent {\n    data class Login(val user: String, val pass: String) : AuthEvent()\n    object Logout : AuthEvent()\n}\n\nfun reduce(state: AuthState, event: AuthEvent): AuthState = when (event) {\n    is AuthEvent.Login -> AuthState.LoggedIn(event.user)\n    is AuthEvent.Logout -> AuthState.LoggedOut\n}`, hints: ['Both states and events are sealed classes.', 'reduce takes current state + event and returns new state.', 'This is the Redux/MVI pattern in Kotlin.'], concepts: ['event-driven', 'reducer', 'sealed-events'] },
    { id: 'kt-state-7', title: 'Write a State Machine Class', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a generic state machine class.', skeleton: `// Write:\n// 1. class StateMachine<S, E>(initialState: S, private val reducer: (S, E) -> S)\n// 2. Property currentState: S\n// 3. fun dispatch(event: E) updates currentState using reducer\n// 4. fun isInState(state: S): Boolean`, solution: `class StateMachine<S, E>(\n    initialState: S,\n    private val reducer: (S, E) -> S\n) {\n    var currentState: S = initialState\n        private set\n\n    fun dispatch(event: E) {\n        currentState = reducer(currentState, event)\n    }\n\n    fun isInState(state: S): Boolean = currentState == state\n}`, hints: ['Generic S for state, E for event.', 'dispatch applies the reducer to get new state.', 'currentState is publicly readable but privately settable.'], concepts: ['generic-state-machine', 'encapsulation'] },
    { id: 'kt-state-8', title: 'Write State with History', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a state holder that tracks history for undo/redo.', skeleton: `// Write:\n// 1. class StateHistory<T>(initial: T)\n// 2. Property current: T\n// 3. fun push(state: T) - saves current to undo stack, sets new state\n// 4. fun undo(): T? - reverts to previous state (push current to redo stack)\n// 5. fun redo(): T? - moves forward (push current to undo stack)`, solution: `class StateHistory<T>(initial: T) {\n    var current: T = initial\n        private set\n    private val undoStack = ArrayDeque<T>()\n    private val redoStack = ArrayDeque<T>()\n\n    fun push(state: T) {\n        undoStack.addLast(current)\n        current = state\n        redoStack.clear()\n    }\n\n    fun undo(): T? {\n        if (undoStack.isEmpty()) return null\n        redoStack.addLast(current)\n        current = undoStack.removeLast()\n        return current\n    }\n\n    fun redo(): T? {\n        if (redoStack.isEmpty()) return null\n        undoStack.addLast(current)\n        current = redoStack.removeLast()\n        return current\n    }\n}`, hints: ['Two stacks: undo and redo.', 'push clears the redo stack.', 'undo moves current to redo, pops undo to current.'], concepts: ['undo-redo', 'state-history', 'ArrayDeque'] },
    { id: 'kt-state-9', title: 'Write Order State Machine', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write an order processing state machine with validation.', skeleton: `// Write:\n// 1. sealed class OrderState: Pending, Confirmed, Shipped, Delivered, Cancelled\n// 2. sealed class OrderEvent: Confirm, Ship, Deliver, Cancel\n// 3. fun OrderState.transition(event: OrderEvent): OrderState\n//    Rules: Pending->Confirm=Confirmed, Confirmed->Ship=Shipped,\n//           Shipped->Deliver=Delivered, Pending/Confirmed->Cancel=Cancelled\n//    Invalid transitions throw IllegalStateException`, solution: `sealed class OrderState {\n    object Pending : OrderState()\n    object Confirmed : OrderState()\n    object Shipped : OrderState()\n    object Delivered : OrderState()\n    object Cancelled : OrderState()\n}\n\nsealed class OrderEvent {\n    object Confirm : OrderEvent()\n    object Ship : OrderEvent()\n    object Deliver : OrderEvent()\n    object Cancel : OrderEvent()\n}\n\nfun OrderState.transition(event: OrderEvent): OrderState = when (this) {\n    is OrderState.Pending -> when (event) {\n        is OrderEvent.Confirm -> OrderState.Confirmed\n        is OrderEvent.Cancel -> OrderState.Cancelled\n        else -> throw IllegalStateException("Cannot \${event} from Pending")\n    }\n    is OrderState.Confirmed -> when (event) {\n        is OrderEvent.Ship -> OrderState.Shipped\n        is OrderEvent.Cancel -> OrderState.Cancelled\n        else -> throw IllegalStateException("Cannot \${event} from Confirmed")\n    }\n    is OrderState.Shipped -> when (event) {\n        is OrderEvent.Deliver -> OrderState.Delivered\n        else -> throw IllegalStateException("Cannot \${event} from Shipped")\n    }\n    is OrderState.Delivered -> throw IllegalStateException("Order already delivered")\n    is OrderState.Cancelled -> throw IllegalStateException("Order already cancelled")\n}`, hints: ['Extension function on OrderState for transitions.', 'Terminal states (Delivered, Cancelled) reject all events.', 'Invalid transitions throw exceptions.'], concepts: ['state-machine', 'extension-function', 'validation'] },
    { id: 'kt-state-10', title: 'Write StateFlow ViewModel', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a ViewModel with StateFlow-based state management.', skeleton: `// Write:\n// 1. sealed class ScreenState: Loading, Content(items: List<String>), Empty, Error(msg: String)\n// 2. sealed class ScreenEvent: Refresh, AddItem(item: String), Clear\n// 3. class ScreenViewModel with:\n//    - private _state: MutableStateFlow<ScreenState> = Loading\n//    - val state: StateFlow<ScreenState>\n//    - fun onEvent(event: ScreenEvent) that updates state`, solution: `import kotlinx.coroutines.flow.MutableStateFlow\nimport kotlinx.coroutines.flow.StateFlow\nimport kotlinx.coroutines.flow.asStateFlow\n\nsealed class ScreenState {\n    object Loading : ScreenState()\n    data class Content(val items: List<String>) : ScreenState()\n    object Empty : ScreenState()\n    data class Error(val msg: String) : ScreenState()\n}\n\nsealed class ScreenEvent {\n    object Refresh : ScreenEvent()\n    data class AddItem(val item: String) : ScreenEvent()\n    object Clear : ScreenEvent()\n}\n\nclass ScreenViewModel {\n    private val _state = MutableStateFlow<ScreenState>(ScreenState.Loading)\n    val state: StateFlow<ScreenState> = _state.asStateFlow()\n\n    fun onEvent(event: ScreenEvent) {\n        _state.value = when (event) {\n            is ScreenEvent.Refresh -> ScreenState.Content(listOf("refreshed"))\n            is ScreenEvent.AddItem -> {\n                val current = _state.value\n                if (current is ScreenState.Content) {\n                    ScreenState.Content(current.items + event.item)\n                } else {\n                    ScreenState.Content(listOf(event.item))\n                }\n            }\n            is ScreenEvent.Clear -> ScreenState.Empty\n        }\n    }\n}`, hints: ['MutableStateFlow holds mutable state privately.', 'asStateFlow exposes read-only StateFlow.', 'onEvent reduces the event into a new state.'], concepts: ['StateFlow', 'ViewModel', 'MVI-pattern'] },
    { id: 'kt-state-11', title: 'Write Coroutine State Machine', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a state machine that uses coroutines for async transitions.', skeleton: `// Write:\n// 1. sealed class FetchState: Idle, Loading, Success(data: String), Failure(error: String)\n// 2. class FetchMachine with:\n//    - MutableStateFlow<FetchState> starting at Idle\n//    - suspend fun fetch(url: String) that:\n//      sets Loading, delays 100ms (simulate), then sets Success\n//    - fun reset() sets Idle`, solution: `import kotlinx.coroutines.delay\nimport kotlinx.coroutines.flow.MutableStateFlow\nimport kotlinx.coroutines.flow.StateFlow\nimport kotlinx.coroutines.flow.asStateFlow\n\nsealed class FetchState {\n    object Idle : FetchState()\n    object Loading : FetchState()\n    data class Success(val data: String) : FetchState()\n    data class Failure(val error: String) : FetchState()\n}\n\nclass FetchMachine {\n    private val _state = MutableStateFlow<FetchState>(FetchState.Idle)\n    val state: StateFlow<FetchState> = _state.asStateFlow()\n\n    suspend fun fetch(url: String) {\n        _state.value = FetchState.Loading\n        try {\n            delay(100)\n            _state.value = FetchState.Success("Data from \${url}")\n        } catch (e: Exception) {\n            _state.value = FetchState.Failure(e.message ?: "Unknown error")\n        }\n    }\n\n    fun reset() {\n        _state.value = FetchState.Idle\n    }\n}`, hints: ['suspend fun allows using delay() and other coroutines.', 'try/catch handles failures and transitions to Failure state.', 'StateFlow emits each state change to collectors.'], concepts: ['coroutine-state', 'suspend-function', 'StateFlow'] },
    { id: 'kt-state-12', title: 'Write Finite State Machine DSL', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a DSL for defining state machines declaratively.', skeleton: `// Write:\n// 1. class FsmBuilder<S, E> with:\n//    - fun state(s: S, init: StateConfig<S, E>.() -> Unit)\n//    - fun build(): Map<S, Map<E, S>>\n// 2. class StateConfig<S, E> with:\n//    - fun on(event: E, target: S)\n// 3. fun <S, E> fsm(init: FsmBuilder<S, E>.() -> Unit): Map<S, Map<E, S>>`, solution: `class StateConfig<S, E> {\n    val transitions = mutableMapOf<E, S>()\n    fun on(event: E, target: S) { transitions[event] = target }\n}\n\nclass FsmBuilder<S, E> {\n    private val states = mutableMapOf<S, Map<E, S>>()\n\n    fun state(s: S, init: StateConfig<S, E>.() -> Unit) {\n        val config = StateConfig<S, E>().apply(init)\n        states[s] = config.transitions.toMap()\n    }\n\n    fun build(): Map<S, Map<E, S>> = states.toMap()\n}\n\nfun <S, E> fsm(init: FsmBuilder<S, E>.() -> Unit): Map<S, Map<E, S>> {\n    return FsmBuilder<S, E>().apply(init).build()\n}`, hints: ['StateConfig collects transitions for a single state.', 'FsmBuilder collects all states and their transitions.', 'The result is a Map of state to (event to target state).'], concepts: ['fsm-dsl', 'type-safe-builder', 'generic-dsl'] },
    { id: 'kt-state-13', title: 'Fix Missing State Transition', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix a state machine that forgets to handle a state.', skeleton: `sealed class LightState {\n    object Off : LightState()\n    object Dim : LightState()\n    object Bright : LightState()\n}\n\nfun next(state: LightState): LightState = when (state) {\n    is LightState.Off -> LightState.Dim\n    is LightState.Bright -> LightState.Off\n    // Missing Dim -> Bright!\n    else -> state\n}`, solution: `sealed class LightState {\n    object Off : LightState()\n    object Dim : LightState()\n    object Bright : LightState()\n}\n\nfun next(state: LightState): LightState = when (state) {\n    is LightState.Off -> LightState.Dim\n    is LightState.Dim -> LightState.Bright\n    is LightState.Bright -> LightState.Off\n}`, hints: ['Remove else and handle all cases explicitly.', 'Dim should transition to Bright.', 'Exhaustive when catches missing branches at compile time.'], concepts: ['exhaustive-when', 'missing-state'] },
    { id: 'kt-state-14', title: 'Fix Mutable State Exposure', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a ViewModel that exposes mutable state.', skeleton: `import kotlinx.coroutines.flow.MutableStateFlow\n\nclass CounterViewModel {\n    val state = MutableStateFlow(0)  // Bug: external code can set state.value!\n\n    fun increment() { state.value++ }\n    fun decrement() { state.value-- }\n}`, solution: `import kotlinx.coroutines.flow.MutableStateFlow\nimport kotlinx.coroutines.flow.StateFlow\nimport kotlinx.coroutines.flow.asStateFlow\n\nclass CounterViewModel {\n    private val _state = MutableStateFlow(0)\n    val state: StateFlow<Int> = _state.asStateFlow()\n\n    fun increment() { _state.value++ }\n    fun decrement() { _state.value-- }\n}`, hints: ['MutableStateFlow should be private.', 'Expose as StateFlow (read-only) via asStateFlow().', 'Underscore prefix convention for private mutable backing.'], concepts: ['encapsulation', 'StateFlow', 'backing-property'] },
    { id: 'kt-state-15', title: 'Fix Invalid State Transition', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a state machine that allows invalid transitions.', skeleton: `sealed class Gate {\n    object Locked : Gate()\n    object Unlocked : Gate()\n}\n\nenum class Coin { Insert, Push }\n\nfun transition(state: Gate, event: Coin): Gate = when (event) {\n    Coin.Insert -> Gate.Unlocked  // Always unlocks, even if already unlocked!\n    Coin.Push -> Gate.Locked      // Always locks, even if already locked!\n}`, solution: `sealed class Gate {\n    object Locked : Gate()\n    object Unlocked : Gate()\n}\n\nenum class Coin { Insert, Push }\n\nfun transition(state: Gate, event: Coin): Gate = when (state) {\n    is Gate.Locked -> when (event) {\n        Coin.Insert -> Gate.Unlocked\n        Coin.Push -> Gate.Locked\n    }\n    is Gate.Unlocked -> when (event) {\n        Coin.Insert -> Gate.Unlocked\n        Coin.Push -> Gate.Locked\n    }\n}`, hints: ['Transitions must consider the current state.', 'Match on state first, then event.', 'Inserting a coin when unlocked should stay unlocked.'], concepts: ['state-aware-transition', 'turnstile'] },
    { id: 'kt-state-16', title: 'Predict State Transitions', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the final state after a sequence of transitions.', skeleton: `sealed class Switch {\n    object On : Switch()\n    object Off : Switch()\n}\n\nfun toggle(s: Switch): Switch = when (s) {\n    is Switch.On -> Switch.Off\n    is Switch.Off -> Switch.On\n}\n\nfun main() {\n    var s: Switch = Switch.Off\n    s = toggle(s)\n    s = toggle(s)\n    s = toggle(s)\n    println(s::class.simpleName)\n}`, solution: `On`, hints: ['Off -> On -> Off -> On.', 'Three toggles from Off.', 'Odd number of toggles = opposite of start.'], concepts: ['state-transition', 'toggle'] },
    { id: 'kt-state-17', title: 'Predict Sealed State Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict output from sealed class state handling.', skeleton: `sealed class Result {\n    data class Ok(val value: Int) : Result()\n    data class Err(val msg: String) : Result()\n}\n\nfun process(r: Result): String = when (r) {\n    is Result.Ok -> "Value: \${r.value * 2}"\n    is Result.Err -> "Error: \${r.msg}"\n}\n\nfun main() {\n    println(process(Result.Ok(21)))\n    println(process(Result.Err("oops")))\n}`, solution: `Value: 42\nError: oops`, hints: ['Ok(21) -> value * 2 = 42.', 'Err("oops") -> prints the message.', 'Smart cast provides access to .value and .msg.'], concepts: ['sealed-class', 'smart-cast'] },
    { id: 'kt-state-18', title: 'Predict State Machine Sequence', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Trace through a state machine and predict the final state.', skeleton: `enum class S { A, B, C }\nenum class E { X, Y }\n\nfun next(s: S, e: E): S = when (s) {\n    S.A -> if (e == E.X) S.B else S.A\n    S.B -> if (e == E.Y) S.C else S.A\n    S.C -> S.C\n}\n\nfun main() {\n    var state = S.A\n    for (e in listOf(E.X, E.Y, E.X, E.Y)) {\n        state = next(state, e)\n    }\n    println(state)\n}`, solution: `C`, hints: ['A + X -> B, B + Y -> C.', 'C is a terminal state (always stays C).', 'After reaching C, remaining events are ignored.'], concepts: ['state-trace', 'terminal-state'] },
    { id: 'kt-state-19', title: 'Refactor if/else to State Pattern', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor string-based state handling to sealed classes.', skeleton: `class Document {\n    var status = "draft"\n\n    fun publish() {\n        if (status == "draft") {\n            status = "published"\n        } else if (status == "published") {\n            println("Already published")\n        }\n    }\n\n    fun archive() {\n        if (status == "published") {\n            status = "archived"\n        }\n    }\n}`, solution: `sealed class DocState {\n    object Draft : DocState()\n    object Published : DocState()\n    object Archived : DocState()\n}\n\nclass Document(initialState: DocState = DocState.Draft) {\n    var state: DocState = initialState\n        private set\n\n    fun publish() {\n        state = when (state) {\n            is DocState.Draft -> DocState.Published\n            is DocState.Published -> { println("Already published"); state }\n            is DocState.Archived -> { println("Cannot publish archived"); state }\n        }\n    }\n\n    fun archive() {\n        state = when (state) {\n            is DocState.Published -> DocState.Archived\n            else -> { println("Can only archive published"); state }\n        }\n    }\n}`, hints: ['Replace string states with sealed class.', 'Sealed class makes states type-safe.', 'when ensures all states are handled.'], concepts: ['refactor-to-sealed', 'type-safety'] },
    { id: 'kt-state-20', title: 'Refactor Enum to Sealed State', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor an enum-based state that needs associated data.', skeleton: `enum class PaymentStatus { PENDING, PROCESSING, COMPLETED, FAILED }\n\nclass Payment {\n    var status = PaymentStatus.PENDING\n    var transactionId: String? = null  // Only set when completed\n    var errorMessage: String? = null   // Only set when failed\n    var progress: Int = 0              // Only meaningful when processing\n}`, solution: `sealed class PaymentState {\n    object Pending : PaymentState()\n    data class Processing(val progress: Int) : PaymentState()\n    data class Completed(val transactionId: String) : PaymentState()\n    data class Failed(val errorMessage: String) : PaymentState()\n}\n\nclass Payment(initialState: PaymentState = PaymentState.Pending) {\n    var state: PaymentState = initialState\n        private set\n\n    fun startProcessing() {\n        state = PaymentState.Processing(0)\n    }\n\n    fun updateProgress(pct: Int) {\n        val current = state\n        if (current is PaymentState.Processing) {\n            state = current.copy(progress = pct)\n        }\n    }\n\n    fun complete(txnId: String) {\n        state = PaymentState.Completed(txnId)\n    }\n\n    fun fail(error: String) {\n        state = PaymentState.Failed(error)\n    }\n}`, hints: ['Sealed class attaches data to specific states.', 'No more nullable fields that are only sometimes relevant.', 'Each state carries exactly the data it needs.'], concepts: ['sealed-vs-enum', 'state-associated-data'] },
  ],
};
