import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-func',
  title: '48. Functional Kotlin',
  explanation: `## Functional Programming in Kotlin

Kotlin supports functional programming with first-class functions, immutability, and powerful collection operations.

### Pure Functions
\`\`\`kotlin
// Pure: same input always gives same output, no side effects
fun add(a: Int, b: Int): Int = a + b
\`\`\`

### Higher-Order Functions
\`\`\`kotlin
fun <T> List<T>.customFilter(predicate: (T) -> Boolean): List<T> =
    fold(emptyList()) { acc, item -> if (predicate(item)) acc + item else acc }
\`\`\`

### Function Composition
\`\`\`kotlin
infix fun <A, B, C> ((B) -> C).after(f: (A) -> B): (A) -> C = { this(f(it)) }
val toUpperTrimmed = String::uppercase after String::trim
\`\`\`

### Fold / Reduce
\`\`\`kotlin
val sum = listOf(1, 2, 3).fold(0) { acc, n -> acc + n }
val product = listOf(1, 2, 3).reduce { acc, n -> acc * n }
\`\`\`

### Result / Either
\`\`\`kotlin
fun safeDivide(a: Int, b: Int): Result<Double> =
    if (b == 0) Result.failure(ArithmeticException("div by zero"))
    else Result.success(a.toDouble() / b)
\`\`\``,
  exercises: [
    { id: 'kt-func-1', title: 'Pure Function', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Write a pure function with no side effects.', skeleton: `// Pure function: no side effects, deterministic\nfun multiply(a: Int, b: Int): ___ = a * b\n\nfun main() {\n    println(multiply(3, 4))\n    println(multiply(3, 4))  // Always same result\n}`, solution: `// Pure function: no side effects, deterministic\nfun multiply(a: Int, b: Int): Int = a * b\n\nfun main() {\n    println(multiply(3, 4))\n    println(multiply(3, 4))  // Always same result\n}`, hints: ['Pure functions return the same output for the same input.', 'Return type is Int since a * b is Int.', 'No global state is read or modified.'], concepts: ['pure-function', 'determinism'] },
    { id: 'kt-func-2', title: 'Higher-Order Function', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Pass a function as a parameter.', skeleton: `fun operate(a: Int, b: Int, op: (Int, Int) -> Int): Int = ___(a, b)\n\nfun main() {\n    println(operate(10, 3) { x, y -> x + y })\n    println(operate(10, 3) { x, y -> x * y })\n}`, solution: `fun operate(a: Int, b: Int, op: (Int, Int) -> Int): Int = op(a, b)\n\nfun main() {\n    println(operate(10, 3) { x, y -> x + y })\n    println(operate(10, 3) { x, y -> x * y })\n}`, hints: ['op is the function parameter, call it with a and b.', 'Higher-order functions take or return functions.', 'The lambda is passed as the last argument.'], concepts: ['higher-order-function', 'lambda'] },
    { id: 'kt-func-3', title: 'Function Composition', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Compose two functions into one.', skeleton: `infix fun <A, B, C> ((B) -> C).after(f: (A) -> B): (A) -> C = { ___(f(it)) }\n\nval double: (Int) -> Int = { it * 2 }\nval addOne: (Int) -> Int = { it + 1 }\n\nfun main() {\n    val doubleAndAdd = addOne after double\n    println(doubleAndAdd(5))\n}`, solution: `infix fun <A, B, C> ((B) -> C).after(f: (A) -> B): (A) -> C = { this(f(it)) }\n\nval double: (Int) -> Int = { it * 2 }\nval addOne: (Int) -> Int = { it + 1 }\n\nfun main() {\n    val doubleAndAdd = addOne after double\n    println(doubleAndAdd(5))\n}`, hints: ['this refers to the receiver function ((B) -> C).', 'f(it) applies the inner function first.', 'this(f(it)) chains: first f, then this.'], concepts: ['function-composition', 'infix'] },
    { id: 'kt-func-4', title: 'Currying', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Curry a two-argument function.', skeleton: `fun <A, B, C> curry(f: (A, B) -> C): (A) -> (B) -> C = { a -> { b -> ___(a, b) } }\n\nfun main() {\n    val curriedAdd = curry { a: Int, b: Int -> a + b }\n    val add5 = curriedAdd(5)\n    println(add5(3))\n}`, solution: `fun <A, B, C> curry(f: (A, B) -> C): (A) -> (B) -> C = { a -> { b -> f(a, b) } }\n\nfun main() {\n    val curriedAdd = curry { a: Int, b: Int -> a + b }\n    val add5 = curriedAdd(5)\n    println(add5(3))\n}`, hints: ['Currying transforms f(a, b) into f(a)(b).', 'Returns nested lambdas, each taking one argument.', 'f(a, b) calls the original with both arguments.'], concepts: ['currying', 'partial-application'] },
    { id: 'kt-func-5', title: 'fold Accumulation', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use fold to accumulate a result from a list.', skeleton: `fun main() {\n    val words = listOf("Hello", " ", "World", "!")\n    val sentence = words.___(""") { acc, word -> acc + word }\n    println(sentence)\n}`, solution: `fun main() {\n    val words = listOf("Hello", " ", "World", "!")\n    val sentence = words.fold("") { acc, word -> acc + word }\n    println(sentence)\n}`, hints: ['fold starts with an initial value and accumulates.', 'The accumulator starts as empty string.', 'Each step concatenates the next word.'], concepts: ['fold', 'accumulation'] },
    { id: 'kt-func-6', title: 'Result Type', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use Result type for safe error handling.', skeleton: `fun parseInt(s: String): Result<Int> = ___ {\n    s.toInt()\n}\n\nfun main() {\n    val good = parseInt("42")\n    val bad = parseInt("abc")\n    println(good.getOrDefault(-1))\n    println(bad.getOrDefault(-1))\n}`, solution: `fun parseInt(s: String): Result<Int> = runCatching {\n    s.toInt()\n}\n\nfun main() {\n    val good = parseInt("42")\n    val bad = parseInt("abc")\n    println(good.getOrDefault(-1))\n    println(bad.getOrDefault(-1))\n}`, hints: ['runCatching wraps the block in a Result.', 'Success if no exception, Failure if exception thrown.', 'getOrDefault returns the value or a fallback.'], concepts: ['Result', 'runCatching', 'error-handling'] },
    { id: 'kt-func-7', title: 'Write Map/Filter/Reduce from Fold', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Implement map, filter, and reduce using fold.', skeleton: `// Write using fold only (no map, filter, reduce):\n// 1. fun <T, R> List<T>.myMap(transform: (T) -> R): List<R>\n// 2. fun <T> List<T>.myFilter(predicate: (T) -> Boolean): List<T>\n// 3. fun List<Int>.mySum(): Int`, solution: `fun <T, R> List<T>.myMap(transform: (T) -> R): List<R> =\n    fold(emptyList()) { acc, item -> acc + transform(item) }\n\nfun <T> List<T>.myFilter(predicate: (T) -> Boolean): List<T> =\n    fold(emptyList()) { acc, item -> if (predicate(item)) acc + item else acc }\n\nfun List<Int>.mySum(): Int =\n    fold(0) { acc, item -> acc + item }`, hints: ['fold starts with an empty list and builds up.', 'myMap transforms each element before adding.', 'myFilter adds only elements matching the predicate.'], concepts: ['fold', 'higher-order-functions', 'collection-operations'] },
    { id: 'kt-func-8', title: 'Write Function Memoization', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a memoize function that caches results.', skeleton: `// Write:\n// 1. fun <A, R> memoize(fn: (A) -> R): (A) -> R\n//    Returns a new function that caches results in a HashMap\n//    If the argument was seen before, return cached result\n//    Otherwise compute, cache, and return`, solution: `fun <A, R> memoize(fn: (A) -> R): (A) -> R {\n    val cache = HashMap<A, R>()\n    return { arg ->\n        cache.getOrPut(arg) { fn(arg) }\n    }\n}\n\nfun main() {\n    val slowSquare = memoize { n: Int ->\n        Thread.sleep(100)\n        n * n\n    }\n    println(slowSquare(5))  // Slow first time\n    println(slowSquare(5))  // Instant from cache\n}`, hints: ['Use a HashMap to cache argument-result pairs.', 'getOrPut checks cache before computing.', 'The returned lambda captures the cache via closure.'], concepts: ['memoization', 'closure', 'caching'] },
    { id: 'kt-func-9', title: 'Write Sequence Pipeline', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a lazy processing pipeline using sequences.', skeleton: `// Write:\n// 1. fun processLogs(logs: Sequence<String>): List<String>\n//    Pipeline: filter lines containing "ERROR",\n//    map to uppercase, take first 5, collect to list\n// 2. Demonstrate with generateSequence`, solution: `fun processLogs(logs: Sequence<String>): List<String> =\n    logs\n        .filter { "ERROR" in it }\n        .map { it.uppercase() }\n        .take(5)\n        .toList()\n\nfun main() {\n    val logs = sequenceOf(\n        "INFO: started",\n        "ERROR: disk full",\n        "WARN: low memory",\n        "ERROR: timeout",\n        "ERROR: connection refused",\n        "INFO: retrying",\n        "ERROR: auth failed",\n        "ERROR: not found",\n        "ERROR: overflow"\n    )\n    println(processLogs(logs))\n}`, hints: ['Sequences are lazy - operations chain without intermediate lists.', 'filter, map, take are all lazy on sequences.', 'toList() triggers evaluation.'], concepts: ['sequence', 'lazy-evaluation', 'pipeline'] },
    { id: 'kt-func-10', title: 'Write Monadic Chain with Result', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Chain Result operations monadically.', skeleton: `// Write:\n// 1. fun parseAge(s: String): Result<Int> - parse string to int, fail if negative\n// 2. fun validateAge(age: Int): Result<Int> - fail if not in 0..150\n// 3. fun categorize(age: Int): Result<String> - "child"/"adult"/"senior"\n// 4. fun processAge(input: String): Result<String> chaining all three`, solution: `fun parseAge(s: String): Result<Int> = runCatching {\n    val age = s.toInt()\n    require(age >= 0) { "Age cannot be negative" }\n    age\n}\n\nfun validateAge(age: Int): Result<Int> = runCatching {\n    require(age in 0..150) { "Age must be 0..150" }\n    age\n}\n\nfun categorize(age: Int): Result<String> = Result.success(\n    when {\n        age < 18 -> "child"\n        age < 65 -> "adult"\n        else -> "senior"\n    }\n)\n\nfun processAge(input: String): Result<String> =\n    parseAge(input)\n        .mapCatching { validateAge(it).getOrThrow() }\n        .mapCatching { categorize(it).getOrThrow() }`, hints: ['mapCatching chains Result operations.', 'getOrThrow propagates failures.', 'Each step can fail independently.'], concepts: ['Result-chaining', 'monadic', 'mapCatching'] },
    { id: 'kt-func-11', title: 'Write Either Type', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a simple Either type for functional error handling.', skeleton: `// Write:\n// 1. sealed class Either<out L, out R>\n//    data class Left<L>(val value: L) : Either<L, Nothing>()\n//    data class Right<R>(val value: R) : Either<Nothing, R>()\n// 2. fun <L, R, T> Either<L, R>.map(f: (R) -> T): Either<L, T>\n// 3. fun <L, R, T> Either<L, R>.flatMap(f: (R) -> Either<L, T>): Either<L, T>`, solution: `sealed class Either<out L, out R> {\n    data class Left<L>(val value: L) : Either<L, Nothing>()\n    data class Right<R>(val value: R) : Either<Nothing, R>()\n\n    fun <T> map(f: (R) -> T): Either<L, T> = when (this) {\n        is Left -> this\n        is Right -> Right(f(value))\n    }\n\n    fun <T> flatMap(f: (R) -> Either<@UnsafeVariance L, T>): Either<L, T> = when (this) {\n        is Left -> this\n        is Right -> f(value)\n    }\n}\n\nfun main() {\n    val result: Either<String, Int> = Either.Right(42)\n    val mapped = result.map { it * 2 }\n    println(mapped)\n}`, hints: ['Left represents failure, Right represents success.', 'map transforms Right values, passes Left through.', 'flatMap allows chaining operations that return Either.'], concepts: ['Either', 'functor', 'monad'] },
    { id: 'kt-func-12', title: 'Write Partial Application', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write partial application for functions.', skeleton: `// Write:\n// 1. fun <A, B, R> partial(f: (A, B) -> R, a: A): (B) -> R\n// 2. fun <A, B, C, R> partial2(f: (A, B, C) -> R, a: A): (B, C) -> R\n// Usage: val add5 = partial(::add, 5) then add5(3) == 8`, solution: `fun <A, B, R> partial(f: (A, B) -> R, a: A): (B) -> R = { b -> f(a, b) }\n\nfun <A, B, C, R> partial2(f: (A, B, C) -> R, a: A): (B, C) -> R = { b, c -> f(a, b, c) }\n\nfun add(a: Int, b: Int): Int = a + b\nfun greet(greeting: String, name: String, punct: String) = "\${greeting}, \${name}\${punct}"\n\nfun main() {\n    val add5 = partial(::add, 5)\n    println(add5(3))\n    val hello = partial2(::greet, "Hello")\n    println(hello("World", "!"))\n}`, hints: ['Partial application fixes one argument, returns a smaller function.', 'partial fixes the first argument of a 2-arg function.', 'The returned lambda takes the remaining arguments.'], concepts: ['partial-application', 'function-reference'] },
    { id: 'kt-func-13', title: 'Fix Impure Function', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix a function that has hidden side effects.', skeleton: `var counter = 0\n\nfun addAndCount(a: Int, b: Int): Int {\n    counter++  // Side effect!\n    return a + b\n}\n\nfun main() {\n    println(addAndCount(1, 2))\n    println("Counter: \${counter}")  // Surprising hidden state\n}`, solution: `fun addPure(a: Int, b: Int): Int = a + b\n\ndata class AddResult(val sum: Int, val callCount: Int)\n\nfun addTracked(a: Int, b: Int, currentCount: Int): AddResult {\n    return AddResult(a + b, currentCount + 1)\n}\n\nfun main() {\n    println(addPure(1, 2))\n    val result = addTracked(1, 2, 0)\n    println("Sum: \${result.sum}, Count: \${result.callCount}")\n}`, hints: ['Remove the global mutable state.', 'Return all needed information in the result.', 'If tracking is needed, make it explicit in the return type.'], concepts: ['pure-function', 'side-effects', 'explicit-state'] },
    { id: 'kt-func-14', title: 'Fix Broken reduce', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a reduce call on an empty list.', skeleton: `fun average(numbers: List<Int>): Double {\n    val sum = numbers.reduce { acc, n -> acc + n }  // Crashes on empty!\n    return sum.toDouble() / numbers.size\n}\n\nfun main() {\n    println(average(listOf(10, 20, 30)))\n    println(average(emptyList()))  // UnsupportedOperationException!\n}`, solution: `fun average(numbers: List<Int>): Double {\n    if (numbers.isEmpty()) return 0.0\n    val sum = numbers.fold(0) { acc, n -> acc + n }\n    return sum.toDouble() / numbers.size\n}\n\nfun main() {\n    println(average(listOf(10, 20, 30)))\n    println(average(emptyList()))\n}`, hints: ['reduce throws on empty lists because there is no initial value.', 'Use fold with initial value 0 instead.', 'Guard against empty list for division.'], concepts: ['fold-vs-reduce', 'empty-list-safety'] },
    { id: 'kt-func-15', title: 'Fix Eager Evaluation', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a pipeline that evaluates eagerly when it should be lazy.', skeleton: `fun findFirstExpensive(items: List<Int>): Int? {\n    return items\n        .map { println("map \${it}"); it * it }  // Maps ALL items\n        .filter { println("filter \${it}"); it > 100 }  // Filters ALL\n        .firstOrNull()  // Only needs the first!\n}`, solution: `fun findFirstExpensive(items: List<Int>): Int? {\n    return items\n        .asSequence()\n        .map { println("map \${it}"); it * it }\n        .filter { println("filter \${it}"); it > 100 }\n        .firstOrNull()\n}`, hints: ['List operations are eager and process all elements.', 'asSequence() makes the pipeline lazy.', 'Lazy evaluation stops after finding the first match.'], concepts: ['lazy-vs-eager', 'sequence', 'performance'] },
    { id: 'kt-func-16', title: 'Predict fold Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the result of a fold operation.', skeleton: `fun main() {\n    val result = listOf(1, 2, 3, 4).fold(10) { acc, n -> acc - n }\n    println(result)\n}`, solution: `0`, hints: ['Start: 10.', '10-1=9, 9-2=7, 7-3=4, 4-4=0.', 'fold processes left to right.'], concepts: ['fold', 'accumulation'] },
    { id: 'kt-func-17', title: 'Predict Composition Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of composed functions.', skeleton: `val double: (Int) -> Int = { it * 2 }\nval square: (Int) -> Int = { it * it }\nval negate: (Int) -> Int = { -it }\n\nfun chain(vararg fns: (Int) -> Int): (Int) -> Int = { input ->\n    fns.fold(input) { acc, fn -> fn(acc) }\n}\n\nfun main() {\n    val transform = chain(double, square, negate)\n    println(transform(3))\n}`, solution: `-36`, hints: ['double(3) = 6.', 'square(6) = 36.', 'negate(36) = -36.'], concepts: ['function-chain', 'fold-application'] },
    { id: 'kt-func-18', title: 'Predict Sequence Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict how many elements a sequence processes.', skeleton: `fun main() {\n    var count = 0\n    val result = (1..100)\n        .asSequence()\n        .map { count++; it * it }\n        .first { it > 50 }\n    println("result=\${result} count=\${count}")\n}`, solution: `result=64 count=8`, hints: ['Sequence processes element by element lazily.', '1,4,9,16,25,36,49 are all <= 50 (7 elements).', '8*8=64 > 50, so it stops at count=8.'], concepts: ['lazy-sequence', 'short-circuit'] },
    { id: 'kt-func-19', title: 'Refactor Loop to Functional', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor an imperative loop to functional style.', skeleton: `fun countVowels(text: String): Map<Char, Int> {\n    val vowels = "aeiouAEIOU"\n    val counts = mutableMapOf<Char, Int>()\n    for (ch in text) {\n        if (ch in vowels) {\n            val lower = ch.lowercaseChar()\n            counts[lower] = (counts[lower] ?: 0) + 1\n        }\n    }\n    return counts\n}`, solution: `fun countVowels(text: String): Map<Char, Int> =\n    text.filter { it.lowercaseChar() in "aeiou" }\n        .groupingBy { it.lowercaseChar() }\n        .eachCount()`, hints: ['filter selects only vowels.', 'groupingBy groups by lowercase character.', 'eachCount counts occurrences per group.'], concepts: ['functional-style', 'groupingBy', 'eachCount'] },
    { id: 'kt-func-20', title: 'Refactor Nested Callbacks to Chain', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor nested callback-style code to a flat functional chain.', skeleton: `fun fetchUser(id: Int, callback: (Result<String>) -> Unit) {\n    if (id > 0) callback(Result.success("User\${id}"))\n    else callback(Result.failure(Exception("Invalid")))\n}\n\nfun fetchOrders(user: String, callback: (Result<List<String>>) -> Unit) {\n    callback(Result.success(listOf("\${user}-order1", "\${user}-order2")))\n}\n\nfun fetchTotal(orders: List<String>, callback: (Result<Int>) -> Unit) {\n    callback(Result.success(orders.size * 100))\n}\n\n// Nested callback hell:\nfun process(id: Int) {\n    fetchUser(id) { userResult ->\n        userResult.onSuccess { user ->\n            fetchOrders(user) { ordersResult ->\n                ordersResult.onSuccess { orders ->\n                    fetchTotal(orders) { totalResult ->\n                        totalResult.onSuccess { println("Total: \${it}") }\n                    }\n                }\n            }\n        }\n    }\n}`, solution: `fun fetchUserSync(id: Int): Result<String> =\n    if (id > 0) Result.success("User\${id}")\n    else Result.failure(Exception("Invalid"))\n\nfun fetchOrdersSync(user: String): Result<List<String>> =\n    Result.success(listOf("\${user}-order1", "\${user}-order2"))\n\nfun fetchTotalSync(orders: List<String>): Result<Int> =\n    Result.success(orders.size * 100)\n\nfun process(id: Int): Result<Int> =\n    fetchUserSync(id)\n        .mapCatching { user -> fetchOrdersSync(user).getOrThrow() }\n        .mapCatching { orders -> fetchTotalSync(orders).getOrThrow() }\n        .onSuccess { println("Total: \${it}") }`, hints: ['Convert callbacks to synchronous Result-returning functions.', 'mapCatching chains Result transformations.', 'getOrThrow propagates failures through the chain.'], concepts: ['callback-to-chain', 'Result-chaining', 'mapCatching'] },
  ],
};
