import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-adv',
  title: '49. Advanced Kotlin',
  explanation: `## Advanced Kotlin Features

Kotlin provides powerful advanced features for library design, performance optimization, and multiplatform development.

### Value Classes
\`\`\`kotlin
@JvmInline
value class Email(val address: String) {
    init { require(address.contains("@")) }
}
\`\`\`

### Operator Overloading
\`\`\`kotlin
data class Vec2(val x: Double, val y: Double) {
    operator fun plus(other: Vec2) = Vec2(x + other.x, y + other.y)
    operator fun times(scalar: Double) = Vec2(x * scalar, y * scalar)
}
\`\`\`

### Reified Type Parameters
\`\`\`kotlin
inline fun <reified T> List<*>.filterIsType(): List<T> =
    filterIsInstance<T>()
\`\`\`

### Contracts
\`\`\`kotlin
@OptIn(ExperimentalContracts::class)
fun String?.isNotNullOrEmpty(): Boolean {
    contract { returns(true) implies (this@isNotNullOrEmpty != null) }
    return this != null && isNotEmpty()
}
\`\`\`

### Context Receivers (Experimental)
\`\`\`kotlin
context(Logger)
fun processData(data: String) {
    log("Processing: \$data")
}
\`\`\``,
  exercises: [
    { id: 'kt-adv-1', title: 'Value Class', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Create a value class for type-safe wrappers.', skeleton: `@JvmInline\n___ class UserId(val id: Long)\n\n@JvmInline\nvalue class OrderId(val id: Long)\n\nfun findOrder(userId: UserId, orderId: OrderId): String =\n    "User \${userId.id} Order \${orderId.id}"`, solution: `@JvmInline\nvalue class UserId(val id: Long)\n\n@JvmInline\nvalue class OrderId(val id: Long)\n\nfun findOrder(userId: UserId, orderId: OrderId): String =\n    "User \${userId.id} Order \${orderId.id}"`, hints: ['value class wraps a single value with zero overhead at runtime.', '@JvmInline is required for JVM targets.', 'Prevents mixing up UserId and OrderId even though both are Long.'], concepts: ['value-class', 'type-safety'] },
    { id: 'kt-adv-2', title: 'Type Alias', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Create type aliases for complex types.', skeleton: `___ StringMap = Map<String, String>\ntypealias Predicate<T> = (T) -> Boolean\ntypealias Handler = (String, Int) -> Unit\n\nfun filter(items: List<String>, pred: Predicate<String>): List<String> =\n    items.filter(pred)`, solution: `typealias StringMap = Map<String, String>\ntypealias Predicate<T> = (T) -> Boolean\ntypealias Handler = (String, Int) -> Unit\n\nfun filter(items: List<String>, pred: Predicate<String>): List<String> =\n    items.filter(pred)`, hints: ['typealias creates an alternative name for an existing type.', 'No new type is created; it is the same type underneath.', 'Useful for shortening long generic signatures.'], concepts: ['typealias', 'readability'] },
    { id: 'kt-adv-3', title: 'Operator Overloading', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Overload the plus operator for a custom class.', skeleton: `data class Money(val cents: Long) {\n    ___ fun plus(other: Money) = Money(cents + other.cents)\n    operator fun minus(other: Money) = Money(cents - other.cents)\n    operator fun times(factor: Int) = Money(cents * factor)\n}\n\nfun main() {\n    val a = Money(500)\n    val b = Money(350)\n    println((a + b).cents)\n}`, solution: `data class Money(val cents: Long) {\n    operator fun plus(other: Money) = Money(cents + other.cents)\n    operator fun minus(other: Money) = Money(cents - other.cents)\n    operator fun times(factor: Int) = Money(cents * factor)\n}\n\nfun main() {\n    val a = Money(500)\n    val b = Money(350)\n    println((a + b).cents)\n}`, hints: ['operator keyword enables using + syntax.', 'plus corresponds to +, minus to -, times to *.', 'Functions must have the right name and signature.'], concepts: ['operator-overloading', 'plus'] },
    { id: 'kt-adv-4', title: 'Reified Type Parameters', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use reified to access type information at runtime.', skeleton: `inline fun <___ T> isType(value: Any): Boolean = value is T\n\nfun main() {\n    println(isType<String>("hello"))\n    println(isType<Int>("hello"))\n    println(isType<Int>(42))\n}`, solution: `inline fun <reified T> isType(value: Any): Boolean = value is T\n\nfun main() {\n    println(isType<String>("hello"))\n    println(isType<Int>("hello"))\n    println(isType<Int>(42))\n}`, hints: ['reified preserves type info at runtime via inlining.', 'Without reified, T is erased and cannot be checked.', 'Must be used with inline functions.'], concepts: ['reified', 'inline', 'type-check'] },
    { id: 'kt-adv-5', title: 'Companion Object Factory', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Use companion object as a factory with interface.', skeleton: `interface Factory<T> {\n    fun create(): T\n}\n\nclass Connection private constructor(val url: String) {\n    ___ object : Factory<Connection> {\n        override fun create() = Connection("default://localhost")\n        fun fromUrl(url: String) = Connection(url)\n    }\n}`, solution: `interface Factory<T> {\n    fun create(): T\n}\n\nclass Connection private constructor(val url: String) {\n    companion object : Factory<Connection> {\n        override fun create() = Connection("default://localhost")\n        fun fromUrl(url: String) = Connection(url)\n    }\n}`, hints: ['companion object can implement interfaces.', 'Private constructor forces use of factory methods.', 'companion object acts as the class-level singleton.'], concepts: ['companion-object', 'factory-interface'] },
    { id: 'kt-adv-6', title: 'crossinline and noinline', type: 'fill-blank', difficulty: 'advanced', language: 'kotlin', goal: 'Use crossinline and noinline correctly.', skeleton: `inline fun execute(\n    ___ block: () -> Unit,\n    noinline callback: () -> Unit\n) {\n    val runnable = Runnable { block() }  // crossinline: no non-local return\n    runnable.run()\n    callback()  // noinline: can be stored\n}`, solution: `inline fun execute(\n    crossinline block: () -> Unit,\n    noinline callback: () -> Unit\n) {\n    val runnable = Runnable { block() }  // crossinline: no non-local return\n    runnable.run()\n    callback()  // noinline: can be stored\n}`, hints: ['crossinline prevents non-local returns in inlined lambdas.', 'noinline keeps the lambda as an object (not inlined).', 'Use crossinline when lambda is called in a different context.'], concepts: ['crossinline', 'noinline', 'inline'] },
    { id: 'kt-adv-7', title: 'Write Value Class with Validation', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write value classes with init validation.', skeleton: `// Write:\n// 1. @JvmInline value class Email(val value: String)\n//    init: require contains "@" and "."\n// 2. @JvmInline value class Port(val number: Int)\n//    init: require number in 1..65535\n// 3. @JvmInline value class Percentage(val value: Double)\n//    init: require value in 0.0..100.0`, solution: `@JvmInline\nvalue class Email(val value: String) {\n    init {\n        require("@" in value && "." in value) { "Invalid email: \${value}" }\n    }\n}\n\n@JvmInline\nvalue class Port(val number: Int) {\n    init {\n        require(number in 1..65535) { "Port must be 1..65535, got \${number}" }\n    }\n}\n\n@JvmInline\nvalue class Percentage(val value: Double) {\n    init {\n        require(value in 0.0..100.0) { "Percentage must be 0..100, got \${value}" }\n    }\n}`, hints: ['init blocks run validation on construction.', 'require throws IllegalArgumentException on failure.', 'Value classes have zero runtime overhead despite validation.'], concepts: ['value-class', 'validation', 'require'] },
    { id: 'kt-adv-8', title: 'Write Operator Overloads for Matrix', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a matrix class with operator overloading.', skeleton: `// Write:\n// 1. data class Matrix(val rows: List<List<Int>>)\n// 2. operator fun plus(other: Matrix): Matrix - element-wise addition\n// 3. operator fun get(row: Int, col: Int): Int - access element\n// 4. operator fun times(scalar: Int): Matrix - scalar multiplication`, solution: `data class Matrix(val rows: List<List<Int>>) {\n    val numRows get() = rows.size\n    val numCols get() = rows.firstOrNull()?.size ?: 0\n\n    operator fun plus(other: Matrix): Matrix {\n        require(numRows == other.numRows && numCols == other.numCols)\n        return Matrix(rows.zip(other.rows) { a, b ->\n            a.zip(b) { x, y -> x + y }\n        })\n    }\n\n    operator fun get(row: Int, col: Int): Int = rows[row][col]\n\n    operator fun times(scalar: Int): Matrix =\n        Matrix(rows.map { row -> row.map { it * scalar } })\n}\n\nfun main() {\n    val a = Matrix(listOf(listOf(1, 2), listOf(3, 4)))\n    val b = Matrix(listOf(listOf(5, 6), listOf(7, 8)))\n    println((a + b).rows)\n    println(a[0, 1])\n    println((a * 3).rows)\n}`, hints: ['plus zips rows and columns for element-wise addition.', 'get(row, col) enables matrix[0, 1] syntax.', 'times maps each element by the scalar.'], concepts: ['operator-overloading', 'matrix', 'zip'] },
    { id: 'kt-adv-9', title: 'Write Reified Utility Functions', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write utility functions using reified type parameters.', skeleton: `// Write:\n// 1. inline fun <reified T> Any.safeCast(): T? - safe cast to T\n// 2. inline fun <reified T> List<*>.filterByType(): List<T> - filter by type\n// 3. inline fun <reified T> typeName(): String - return simple class name`, solution: `inline fun <reified T> Any.safeCast(): T? = this as? T\n\ninline fun <reified T> List<*>.filterByType(): List<T> = filterIsInstance<T>()\n\ninline fun <reified T> typeName(): String = T::class.simpleName ?: "Unknown"\n\nfun main() {\n    val x: Any = "hello"\n    println(x.safeCast<String>())\n    println(x.safeCast<Int>())\n\n    val mixed = listOf(1, "two", 3.0, "four", 5)\n    println(mixed.filterByType<String>())\n\n    println(typeName<List<Int>>())\n}`, hints: ['reified allows T::class and is T checks at runtime.', 'safeCast uses as? for safe casting.', 'filterIsInstance is the stdlib equivalent.'], concepts: ['reified', 'safe-cast', 'type-introspection'] },
    { id: 'kt-adv-10', title: 'Write Delegate Property', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a custom property delegate with validation.', skeleton: `// Write:\n// 1. class Validated<T>(initialValue: T, private val validator: (T) -> Boolean)\n//    Implements ReadWriteProperty<Any?, T>\n//    getValue returns stored value\n//    setValue only sets if validator returns true, else throws\n// 2. Usage: var age by Validated(0) { it in 0..150 }`, solution: `import kotlin.properties.ReadWriteProperty\nimport kotlin.reflect.KProperty\n\nclass Validated<T>(\n    private var value: T,\n    private val validator: (T) -> Boolean\n) : ReadWriteProperty<Any?, T> {\n\n    init { require(validator(value)) { "Initial value failed validation" } }\n\n    override fun getValue(thisRef: Any?, property: KProperty<*>): T = value\n\n    override fun setValue(thisRef: Any?, property: KProperty<*>, value: T) {\n        require(validator(value)) { "Validation failed for \${property.name}: \${value}" }\n        this.value = value\n    }\n}\n\nfun main() {\n    var age by Validated(25) { it in 0..150 }\n    println(age)\n    age = 30\n    println(age)\n    // age = -1  // throws IllegalArgumentException\n}`, hints: ['ReadWriteProperty interface has getValue and setValue.', 'KProperty provides metadata about the delegated property.', 'require in setValue enforces the constraint.'], concepts: ['property-delegate', 'ReadWriteProperty', 'validation'] },
    { id: 'kt-adv-11', title: 'Write Contract Function', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write functions with contracts for smart casts.', skeleton: `// Write:\n// 1. fun requireNotBlank(value: String?): String\n//    Uses contract: returns() implies (value != null)\n//    Throws if null or blank, returns non-null String\n// 2. fun <T> assertIs(value: Any?, msg: String = ""): T\n//    Uses contract and cast`, solution: `import kotlin.contracts.ExperimentalContracts\nimport kotlin.contracts.contract\n\n@OptIn(ExperimentalContracts::class)\nfun requireNotBlank(value: String?): String {\n    contract {\n        returns() implies (value != null)\n    }\n    require(value != null && value.isNotBlank()) { "Value must not be null or blank" }\n    return value\n}\n\n@OptIn(ExperimentalContracts::class)\ninline fun <reified T> assertIs(value: Any?, msg: String = ""): T {\n    contract {\n        returns() implies (value is T)\n    }\n    require(value is T) { msg.ifBlank { "Expected \${T::class.simpleName}, got \${value?.let { it::class.simpleName }}" } }\n    return value\n}\n\nfun main() {\n    val name: String? = "Kotlin"\n    val result = requireNotBlank(name)\n    println(result.length)  // Smart cast: name is String\n}`, hints: ['contract tells compiler what is guaranteed when function returns.', 'returns() implies (expr) enables smart cast after the call.', '@OptIn(ExperimentalContracts::class) is required.'], concepts: ['contracts', 'smart-cast', 'experimental-api'] },
    { id: 'kt-adv-12', title: 'Write Invoke Operator', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write a class with the invoke operator.', skeleton: `// Write:\n// 1. class Pipeline<T> with list of (T) -> T transforms\n// 2. fun add(transform: (T) -> T): Pipeline<T>\n// 3. operator fun invoke(input: T): T - apply all transforms in order\n// Usage: val p = Pipeline<String>().add { it.trim() }.add { it.uppercase() }\n//        p("  hello  ") == "HELLO"`, solution: `class Pipeline<T> {\n    private val transforms = mutableListOf<(T) -> T>()\n\n    fun add(transform: (T) -> T): Pipeline<T> {\n        transforms.add(transform)\n        return this\n    }\n\n    operator fun invoke(input: T): T =\n        transforms.fold(input) { acc, fn -> fn(acc) }\n}\n\nfun main() {\n    val p = Pipeline<String>()\n        .add { it.trim() }\n        .add { it.uppercase() }\n        .add { it.replace(" ", "_") }\n    println(p("  hello world  "))\n}`, hints: ['invoke operator allows calling an object like a function.', 'fold applies each transform sequentially.', 'add returns this for chaining.'], concepts: ['invoke-operator', 'pipeline', 'fold'] },
    { id: 'kt-adv-13', title: 'Fix Value Class Misuse', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix a value class with multiple properties.', skeleton: `@JvmInline\nvalue class Coordinate(val x: Double, val y: Double)  // Error: value class must have single property\n\nfun distance(a: Coordinate, b: Coordinate): Double {\n    val dx = a.x - b.x\n    val dy = a.y - b.y\n    return Math.sqrt(dx * dx + dy * dy)\n}`, solution: `data class Coordinate(val x: Double, val y: Double)\n\nfun distance(a: Coordinate, b: Coordinate): Double {\n    val dx = a.x - b.x\n    val dy = a.y - b.y\n    return Math.sqrt(dx * dx + dy * dy)\n}\n\n// If you need a value class, wrap a single value:\n@JvmInline\nvalue class Latitude(val degrees: Double) {\n    init { require(degrees in -90.0..90.0) }\n}`, hints: ['Value classes can only have a single property.', 'Use data class for multiple properties.', 'Value classes are for wrapping a single primitive.'], concepts: ['value-class-limitation', 'data-class'] },
    { id: 'kt-adv-14', title: 'Fix Missing Operator Keyword', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix operator functions missing the operator keyword.', skeleton: `data class Vec(val x: Int, val y: Int) {\n    fun plus(other: Vec) = Vec(x + other.x, y + other.y)\n    fun get(index: Int) = if (index == 0) x else y\n    fun unaryMinus() = Vec(-x, -y)\n}\n\nfun main() {\n    val a = Vec(1, 2)\n    val b = Vec(3, 4)\n    println(a + b)    // Error: no operator plus\n    println(a[0])     // Error: no operator get\n    println(-a)       // Error: no operator unaryMinus\n}`, solution: `data class Vec(val x: Int, val y: Int) {\n    operator fun plus(other: Vec) = Vec(x + other.x, y + other.y)\n    operator fun get(index: Int) = if (index == 0) x else y\n    operator fun unaryMinus() = Vec(-x, -y)\n}\n\nfun main() {\n    val a = Vec(1, 2)\n    val b = Vec(3, 4)\n    println(a + b)\n    println(a[0])\n    println(-a)\n}`, hints: ['operator keyword is required for operator overloading.', 'Without it, the function exists but cannot use operator syntax.', 'Add operator to plus, get, and unaryMinus.'], concepts: ['operator-keyword', 'overloading'] },
    { id: 'kt-adv-15', title: 'Fix Reified Without Inline', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix a reified function that is not inlined.', skeleton: `fun <reified T> create(): T {  // Error: reified without inline\n    return T::class.java.getDeclaredConstructor().newInstance()\n}\n\nclass Foo\n\nfun main() {\n    val f = create<Foo>()\n    println(f::class.simpleName)\n}`, solution: `inline fun <reified T> create(): T {\n    return T::class.java.getDeclaredConstructor().newInstance()\n}\n\nclass Foo\n\nfun main() {\n    val f = create<Foo>()\n    println(f::class.simpleName)\n}`, hints: ['reified requires the function to be inline.', 'Without inline, type info is erased at runtime.', 'Add inline keyword before fun.'], concepts: ['reified', 'inline', 'type-erasure'] },
    { id: 'kt-adv-16', title: 'Predict Value Class Output', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the output of value class operations.', skeleton: `@JvmInline\nvalue class Meters(val value: Double) {\n    fun toFeet(): Double = value * 3.281\n}\n\nfun main() {\n    val height = Meters(1.8)\n    println(height.value)\n    println(Meters(0.0) == Meters(0.0))\n}`, solution: `1.8\ntrue`, hints: ['value property returns the wrapped value.', 'Value classes support equality based on the wrapped value.', 'Meters(0.0) == Meters(0.0) compares the inner doubles.'], concepts: ['value-class', 'equality'] },
    { id: 'kt-adv-17', title: 'Predict Operator Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the result of operator overloading.', skeleton: `data class Fraction(val num: Int, val den: Int) {\n    operator fun plus(other: Fraction) =\n        Fraction(num * other.den + other.num * den, den * other.den)\n    override fun toString() = "\${num}/\${den}"\n}\n\nfun main() {\n    val a = Fraction(1, 3)\n    val b = Fraction(1, 6)\n    println(a + b)\n}`, solution: `9/18`, hints: ['Cross multiply for addition: (1*6 + 1*3) / (3*6).', 'num = 1*6 + 1*3 = 9.', 'den = 3*6 = 18.'], concepts: ['operator-overloading', 'fractions'] },
    { id: 'kt-adv-18', title: 'Predict Invoke Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of invoke operator usage.', skeleton: `class Repeater(private val times: Int) {\n    operator fun invoke(text: String): String =\n        (1..times).joinToString("") { text }\n}\n\nfun main() {\n    val triple = Repeater(3)\n    println(triple("ha"))\n    println(Repeater(2)("ok"))\n}`, solution: `hahaha\nokok`, hints: ['invoke allows calling Repeater instance like a function.', 'triple("ha") calls invoke("ha") which repeats 3 times.', 'Repeater(2)("ok") creates and immediately invokes.'], concepts: ['invoke-operator', 'callable-object'] },
    { id: 'kt-adv-19', title: 'Refactor to Value Classes', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor primitive-typed parameters to value classes.', skeleton: `fun createUser(name: String, email: String, age: Int): String {\n    return "User(name=\${name}, email=\${email}, age=\${age})"\n}\n\n// Easy to mix up parameters!\nval user = createUser("alice@test.com", "Alice", 30)  // Oops: email and name swapped!`, solution: `@JvmInline\nvalue class Name(val value: String)\n\n@JvmInline\nvalue class EmailAddr(val value: String) {\n    init { require("@" in value) { "Invalid email" } }\n}\n\n@JvmInline\nvalue class Age(val value: Int) {\n    init { require(value in 0..150) { "Invalid age" } }\n}\n\nfun createUser(name: Name, email: EmailAddr, age: Age): String {\n    return "User(name=\${name.value}, email=\${email.value}, age=\${age.value})"\n}\n\n// Now type-safe:\n// createUser(EmailAddr("alice@test.com"), Name("Alice"), Age(30))  // Compile error!\nval user = createUser(Name("Alice"), EmailAddr("alice@test.com"), Age(30))`, hints: ['Value classes prevent mixing up same-typed parameters.', 'Each domain concept gets its own type.', 'Compile-time safety with zero runtime overhead.'], concepts: ['value-class', 'type-safety', 'domain-modeling'] },
    { id: 'kt-adv-20', title: 'Refactor to Operator Overloading', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor verbose method calls to operator syntax.', skeleton: `class Color(val r: Int, val g: Int, val b: Int) {\n    fun add(other: Color) = Color(\n        minOf(r + other.r, 255),\n        minOf(g + other.g, 255),\n        minOf(b + other.b, 255)\n    )\n    fun multiply(factor: Double) = Color(\n        (r * factor).toInt().coerceIn(0, 255),\n        (g * factor).toInt().coerceIn(0, 255),\n        (b * factor).toInt().coerceIn(0, 255)\n    )\n    fun getComponent(index: Int) = when (index) {\n        0 -> r; 1 -> g; 2 -> b\n        else -> throw IndexOutOfBoundsException()\n    }\n    override fun toString() = "(\${r},\${g},\${b})"\n}\n\nval mixed = Color(100, 50, 0).add(Color(0, 50, 100)).multiply(0.5)`, solution: `data class Color(val r: Int, val g: Int, val b: Int) {\n    operator fun plus(other: Color) = Color(\n        minOf(r + other.r, 255),\n        minOf(g + other.g, 255),\n        minOf(b + other.b, 255)\n    )\n    operator fun times(factor: Double) = Color(\n        (r * factor).toInt().coerceIn(0, 255),\n        (g * factor).toInt().coerceIn(0, 255),\n        (b * factor).toInt().coerceIn(0, 255)\n    )\n    operator fun get(index: Int) = when (index) {\n        0 -> r; 1 -> g; 2 -> b\n        else -> throw IndexOutOfBoundsException()\n    }\n    override fun toString() = "(\${r},\${g},\${b})"\n}\n\nval mixed = (Color(100, 50, 0) + Color(0, 50, 100)) * 0.5`, hints: ['add becomes operator fun plus for + syntax.', 'multiply becomes operator fun times for * syntax.', 'getComponent becomes operator fun get for [] syntax.'], concepts: ['operator-overloading', 'readable-syntax'] },
  ],
};
