import type { LessonSection } from '../../../stores/app.svelte.ts';

export const section: LessonSection = {
  id: 'kt-capstone',
  title: '50. Kotlin Capstone',
  explanation: `## Kotlin Capstone Project

This capstone brings together all major Kotlin concepts into a mini task management system. You'll combine:

- **Sealed classes** for type-safe state modeling
- **Data classes** for immutable domain objects
- **Coroutines & Flow** for async operations
- **DSL builders** for configuration
- **Extension functions** for fluent APIs
- **Generics** for reusable components
- **Null safety** for robust code
- **Serialization** for data persistence
- **Design patterns** (Builder, State, Strategy)
- **Functional programming** for data transformation

### Project: Task Manager
\`\`\`kotlin
// Domain
data class Task(val id: Int, val title: String, val status: TaskStatus)
sealed class TaskStatus {
    object Todo : TaskStatus()
    object InProgress : TaskStatus()
    data class Done(val completedAt: Long) : TaskStatus()
}

// DSL
val project = project {
    name = "My Project"
    task { title = "Design"; priority = HIGH }
    task { title = "Build"; priority = MEDIUM }
}
\`\`\``,
  exercises: [
    { id: 'kt-capstone-1', title: 'Domain Model with Data Classes', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Define the core domain model using data classes.', skeleton: `___ class TaskId(val value: Int)\n\ndata class Task(\n    val id: TaskId,\n    val title: String,\n    val description: String = "",\n    val priority: Priority = Priority.MEDIUM,\n    val tags: List<String> = emptyList()\n)\n\nenum class Priority { LOW, MEDIUM, HIGH, CRITICAL }`, solution: `data class TaskId(val value: Int)\n\ndata class Task(\n    val id: TaskId,\n    val title: String,\n    val description: String = "",\n    val priority: Priority = Priority.MEDIUM,\n    val tags: List<String> = emptyList()\n)\n\nenum class Priority { LOW, MEDIUM, HIGH, CRITICAL }`, hints: ['data class provides equals, hashCode, copy, toString.', 'Default parameter values simplify construction.', 'TaskId wraps Int for type safety.'], concepts: ['data-class', 'enum', 'default-params'] },
    { id: 'kt-capstone-2', title: 'Sealed State Hierarchy', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Model task lifecycle states with sealed classes.', skeleton: `sealed class TaskState {\n    object Backlog : TaskState()\n    object Todo : TaskState()\n    ___ class InProgress(val assignee: String) : TaskState()\n    data class Review(val reviewer: String) : TaskState()\n    data class Done(val completedAt: Long) : TaskState()\n    object Archived : TaskState()\n}`, solution: `sealed class TaskState {\n    object Backlog : TaskState()\n    object Todo : TaskState()\n    data class InProgress(val assignee: String) : TaskState()\n    data class Review(val reviewer: String) : TaskState()\n    data class Done(val completedAt: Long) : TaskState()\n    object Archived : TaskState()\n}`, hints: ['States without data use object (singleton).', 'States with data use data class.', 'InProgress carries the assignee name.'], concepts: ['sealed-class', 'state-modeling'] },
    { id: 'kt-capstone-3', title: 'Null-Safe Task Lookup', type: 'fill-blank', difficulty: 'beginner', language: 'kotlin', goal: 'Use null safety for safe task lookups.', skeleton: `data class Task(val id: Int, val title: String, val assignee: String?)\n\nfun describeTask(tasks: List<Task>, id: Int): String {\n    val task = tasks.find { it.id == id }\n    return task___.let { t ->\n        val owner = t.assignee ?: "Unassigned"\n        "\${t.title} (\${owner})"\n    } ?: "Task not found"\n}`, solution: `data class Task(val id: Int, val title: String, val assignee: String?)\n\nfun describeTask(tasks: List<Task>, id: Int): String {\n    val task = tasks.find { it.id == id }\n    return task?.let { t ->\n        val owner = t.assignee ?: "Unassigned"\n        "\${t.title} (\${owner})"\n    } ?: "Task not found"\n}`, hints: ['?. safe-calls let only if task is non-null.', '?: elvis operator provides fallback for null.', 'Chained null safety handles both missing task and missing assignee.'], concepts: ['null-safety', 'safe-call', 'elvis'] },
    { id: 'kt-capstone-4', title: 'Extension Functions for Task', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Add extension functions to the Task class.', skeleton: `data class Task(val id: Int, val title: String, val tags: List<String>, val priority: Int)\n\nfun List<Task>.highPriority(): List<Task> = filter { it.priority >= 3 }\n\nfun List<Task>.___("tag"): List<Task> = filter { tag in it.tags }\n\nfun Task.summary(): String = "#\${id}: \${title} [p\${priority}]"`, solution: `data class Task(val id: Int, val title: String, val tags: List<String>, val priority: Int)\n\nfun List<Task>.highPriority(): List<Task> = filter { it.priority >= 3 }\n\nfun List<Task>.withTag(tag: String): List<Task> = filter { tag in it.tags }\n\nfun Task.summary(): String = "#\${id}: \${title} [p\${priority}]"`, hints: ['Extension functions on List<Task> enable fluent filtering.', 'withTag filters tasks containing the specified tag.', 'summary provides a formatted description.'], concepts: ['extension-function', 'fluent-api'] },
    { id: 'kt-capstone-5', title: 'Generic Repository', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Build a generic repository with type constraints.', skeleton: `interface Identifiable {\n    val id: Int\n}\n\nclass Repository<T : ___> {\n    private val items = mutableMapOf<Int, T>()\n\n    fun add(item: T) { items[item.id] = item }\n    fun get(id: Int): T? = items[id]\n    fun getAll(): List<T> = items.values.toList()\n    fun remove(id: Int): Boolean = items.remove(id) != null\n    fun update(item: T) { items[item.id] = item }\n}`, solution: `interface Identifiable {\n    val id: Int\n}\n\nclass Repository<T : Identifiable> {\n    private val items = mutableMapOf<Int, T>()\n\n    fun add(item: T) { items[item.id] = item }\n    fun get(id: Int): T? = items[id]\n    fun getAll(): List<T> = items.values.toList()\n    fun remove(id: Int): Boolean = items.remove(id) != null\n    fun update(item: T) { items[item.id] = item }\n}`, hints: ['T : Identifiable constrains T to have an id property.', 'The repository uses id as the map key.', 'Generic class works for any Identifiable entity.'], concepts: ['generics', 'type-constraint', 'repository-pattern'] },
    { id: 'kt-capstone-6', title: 'DSL Task Builder', type: 'fill-blank', difficulty: 'intermediate', language: 'kotlin', goal: 'Build tasks using a DSL builder.', skeleton: `data class Task(val title: String, val description: String, val priority: Int, val tags: List<String>)\n\nclass TaskBuilder {\n    var title = ""\n    var description = ""\n    var priority = 1\n    private val tags = mutableListOf<String>()\n    fun tag(t: String) { tags.add(t) }\n    fun build() = Task(title, description, priority, tags.toList())\n}\n\nfun task(init: TaskBuilder.() -> Unit): Task = TaskBuilder().___(init).build()`, solution: `data class Task(val title: String, val description: String, val priority: Int, val tags: List<String>)\n\nclass TaskBuilder {\n    var title = ""\n    var description = ""\n    var priority = 1\n    private val tags = mutableListOf<String>()\n    fun tag(t: String) { tags.add(t) }\n    fun build() = Task(title, description, priority, tags.toList())\n}\n\nfun task(init: TaskBuilder.() -> Unit): Task = TaskBuilder().apply(init).build()`, hints: ['apply runs the init block with TaskBuilder as receiver.', 'build() creates the immutable Task from builder state.', 'Lambda with receiver allows direct property access.'], concepts: ['dsl-builder', 'apply', 'lambda-with-receiver'] },
    { id: 'kt-capstone-7', title: 'Write State Transitions', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write validated state transitions for the task lifecycle.', skeleton: `// Given:\n// sealed class TaskState: Backlog, Todo, InProgress(assignee), Review(reviewer), Done(timestamp), Archived\n// sealed class TaskEvent: MoveToTodo, Assign(who), RequestReview(reviewer), Approve, Archive\n//\n// Write: fun TaskState.handle(event: TaskEvent): TaskState\n// Rules: Backlog->MoveToTodo=Todo, Todo->Assign=InProgress,\n//        InProgress->RequestReview=Review, Review->Approve=Done(now),\n//        Done->Archive=Archived. Invalid transitions throw IllegalStateException.`, solution: `sealed class TaskState {\n    object Backlog : TaskState()\n    object Todo : TaskState()\n    data class InProgress(val assignee: String) : TaskState()\n    data class Review(val reviewer: String) : TaskState()\n    data class Done(val timestamp: Long) : TaskState()\n    object Archived : TaskState()\n}\n\nsealed class TaskEvent {\n    object MoveToTodo : TaskEvent()\n    data class Assign(val who: String) : TaskEvent()\n    data class RequestReview(val reviewer: String) : TaskEvent()\n    object Approve : TaskEvent()\n    object Archive : TaskEvent()\n}\n\nfun TaskState.handle(event: TaskEvent): TaskState = when (this) {\n    is TaskState.Backlog -> when (event) {\n        is TaskEvent.MoveToTodo -> TaskState.Todo\n        else -> throw IllegalStateException("Invalid event for Backlog")\n    }\n    is TaskState.Todo -> when (event) {\n        is TaskEvent.Assign -> TaskState.InProgress(event.who)\n        else -> throw IllegalStateException("Invalid event for Todo")\n    }\n    is TaskState.InProgress -> when (event) {\n        is TaskEvent.RequestReview -> TaskState.Review(event.reviewer)\n        else -> throw IllegalStateException("Invalid event for InProgress")\n    }\n    is TaskState.Review -> when (event) {\n        is TaskEvent.Approve -> TaskState.Done(System.currentTimeMillis())\n        else -> throw IllegalStateException("Invalid event for Review")\n    }\n    is TaskState.Done -> when (event) {\n        is TaskEvent.Archive -> TaskState.Archived\n        else -> throw IllegalStateException("Invalid event for Done")\n    }\n    is TaskState.Archived -> throw IllegalStateException("No transitions from Archived")\n}`, hints: ['Extension function on TaskState for clean API.', 'Nested when: first match state, then match event.', 'Invalid transitions throw with descriptive messages.'], concepts: ['state-machine', 'sealed-class', 'extension-function'] },
    { id: 'kt-capstone-8', title: 'Write Project DSL', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a full project DSL with nested tasks and milestones.', skeleton: `// Write:\n// 1. data class Project(name, tasks: List<Task>, milestones: List<Milestone>)\n// 2. data class Task(title, priority: Int, tags: List<String>)\n// 3. data class Milestone(name, dueDate: String)\n// 4. Builders: ProjectBuilder, TaskBuilder, MilestoneBuilder\n// 5. DSL: project { name="X"; task { title="Y"; priority=1 }; milestone { name="Z"; dueDate="2026-01-01" } }`, solution: `data class Task(val title: String, val priority: Int, val tags: List<String>)\ndata class Milestone(val name: String, val dueDate: String)\ndata class Project(val name: String, val tasks: List<Task>, val milestones: List<Milestone>)\n\n@DslMarker\nannotation class ProjectDsl\n\n@ProjectDsl\nclass TaskBuilder {\n    var title = ""\n    var priority = 1\n    private val tags = mutableListOf<String>()\n    fun tag(t: String) { tags.add(t) }\n    fun build() = Task(title, priority, tags.toList())\n}\n\n@ProjectDsl\nclass MilestoneBuilder {\n    var name = ""\n    var dueDate = ""\n    fun build() = Milestone(name, dueDate)\n}\n\n@ProjectDsl\nclass ProjectBuilder {\n    var name = ""\n    private val tasks = mutableListOf<Task>()\n    private val milestones = mutableListOf<Milestone>()\n\n    fun task(init: TaskBuilder.() -> Unit) {\n        tasks.add(TaskBuilder().apply(init).build())\n    }\n    fun milestone(init: MilestoneBuilder.() -> Unit) {\n        milestones.add(MilestoneBuilder().apply(init).build())\n    }\n    fun build() = Project(name, tasks.toList(), milestones.toList())\n}\n\nfun project(init: ProjectBuilder.() -> Unit): Project =\n    ProjectBuilder().apply(init).build()`, hints: ['@DslMarker prevents scope leaking between builders.', 'Each builder collects child elements.', 'Top-level function wraps the root builder.'], concepts: ['dsl-builder', 'DslMarker', 'nested-builder'] },
    { id: 'kt-capstone-9', title: 'Write Serialization Layer', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write JSON-like serialization for tasks.', skeleton: `// Write:\n// 1. data class Task(id: Int, title: String, status: String, tags: List<String>)\n// 2. fun Task.toJson(): String - manual JSON serialization\n//    Format: {"id":1,"title":"...","status":"...","tags":["a","b"]}\n// 3. fun parseTask(json: String): Task - parse the JSON back\n//    (Simple string parsing, not a full JSON parser)`, solution: `data class Task(val id: Int, val title: String, val status: String, val tags: List<String>)\n\nfun Task.toJson(): String {\n    val tagsJson = tags.joinToString(",") { "\\"\${it}\\"" }\n    return """{"id":\${id},"title":"\${title}","status":"\${status}","tags":[\${tagsJson}]}"""\n}\n\nfun parseTask(json: String): Task {\n    val clean = json.trim().removeSurrounding("{", "}")\n    val parts = mutableMapOf<String, String>()\n    var remaining = clean\n\n    fun extractField(key: String): String {\n        val keyPattern = "\\"\${key}\\":"\n        val start = remaining.indexOf(keyPattern) + keyPattern.length\n        return if (remaining[start] == \'[\') {\n            val end = remaining.indexOf(\']\', start) + 1\n            remaining.substring(start, end)\n        } else if (remaining[start] == \'\\"\'  ) {\n            val end = remaining.indexOf(\'\\"\'  , start + 1)\n            remaining.substring(start + 1, end)\n        } else {\n            val end = remaining.indexOfAny(charArrayOf(\',\', \'}\'), start)\n            remaining.substring(start, if (end == -1) remaining.length else end)\n        }\n    }\n\n    val id = extractField("id").toInt()\n    val title = extractField("title")\n    val status = extractField("status")\n    val tagsRaw = extractField("tags").removeSurrounding("[", "]")\n    val tags = if (tagsRaw.isBlank()) emptyList()\n              else tagsRaw.split(",").map { it.trim().removeSurrounding("\\"") }\n\n    return Task(id, title, status, tags)\n}`, hints: ['toJson uses string templates for simple serialization.', 'Raw string literals (triple quotes) help with JSON.', 'Parsing extracts fields by key from the JSON string.'], concepts: ['serialization', 'string-templates', 'parsing'] },
    { id: 'kt-capstone-10', title: 'Write Filtering Strategy', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write composable task filtering strategies.', skeleton: `// Write:\n// 1. data class Task(id: Int, title: String, priority: Int, tags: List<String>, done: Boolean)\n// 2. typealias TaskFilter = (Task) -> Boolean\n// 3. val byPriority: (Int) -> TaskFilter\n// 4. val byTag: (String) -> TaskFilter\n// 5. val notDone: TaskFilter\n// 6. infix fun TaskFilter.and(other: TaskFilter): TaskFilter\n// 7. fun List<Task>.applyFilters(vararg filters: TaskFilter): List<Task>`, solution: `data class Task(val id: Int, val title: String, val priority: Int, val tags: List<String>, val done: Boolean)\n\ntypealias TaskFilter = (Task) -> Boolean\n\nval byPriority: (Int) -> TaskFilter = { minPriority -> { task -> task.priority >= minPriority } }\nval byTag: (String) -> TaskFilter = { tag -> { task -> tag in task.tags } }\nval notDone: TaskFilter = { !it.done }\n\ninfix fun TaskFilter.and(other: TaskFilter): TaskFilter = { this(it) && other(it) }\n\nfun List<Task>.applyFilters(vararg filters: TaskFilter): List<Task> {\n    val combined = filters.reduce { acc, f -> acc and f }\n    return filter(combined)\n}`, hints: ['TaskFilter is a function type alias.', 'Curried functions return a TaskFilter for a given parameter.', 'infix and combines two filters with &&.'], concepts: ['strategy-pattern', 'composition', 'typealias'] },
    { id: 'kt-capstone-11', title: 'Write Flow-Based Task Stream', type: 'write-function', difficulty: 'advanced', language: 'kotlin', goal: 'Write a task event stream using Kotlin Flow.', skeleton: `// Write:\n// 1. sealed class TaskEvent: Created(task), Updated(id, field, newValue), Deleted(id)\n// 2. class TaskEventBus with:\n//    - private MutableSharedFlow<TaskEvent>\n//    - val events: SharedFlow<TaskEvent>\n//    - suspend fun emit(event: TaskEvent)\n//    - fun subscribe(): Flow<TaskEvent>\n// 3. Extension: Flow<TaskEvent>.onlyCreated(): Flow<TaskEvent.Created>`, solution: `import kotlinx.coroutines.flow.*\n\ndata class SimpleTask(val id: Int, val title: String)\n\nsealed class TaskEvent {\n    data class Created(val task: SimpleTask) : TaskEvent()\n    data class Updated(val id: Int, val field: String, val newValue: String) : TaskEvent()\n    data class Deleted(val id: Int) : TaskEvent()\n}\n\nclass TaskEventBus {\n    private val _events = MutableSharedFlow<TaskEvent>(replay = 0)\n    val events: SharedFlow<TaskEvent> = _events.asSharedFlow()\n\n    suspend fun emit(event: TaskEvent) {\n        _events.emit(event)\n    }\n\n    fun subscribe(): Flow<TaskEvent> = events\n}\n\nfun Flow<TaskEvent>.onlyCreated(): Flow<TaskEvent.Created> =\n    filterIsInstance<TaskEvent.Created>()`, hints: ['MutableSharedFlow is the mutable backing for events.', 'asSharedFlow exposes read-only version.', 'filterIsInstance narrows the Flow type.'], concepts: ['SharedFlow', 'event-bus', 'Flow-filtering'] },
    { id: 'kt-capstone-12', title: 'Write Testing Helpers', type: 'write-function', difficulty: 'intermediate', language: 'kotlin', goal: 'Write test utility functions for the task system.', skeleton: `// Write:\n// 1. fun createTestTask(id: Int = 1, title: String = "Test", ...defaults): Task\n// 2. fun assertTaskEquals(expected: Task, actual: Task): Boolean\n// 3. infix fun Task.shouldHaveTitle(title: String): Task - returns self or throws\n// 4. infix fun Task.shouldHavePriority(p: Int): Task - returns self or throws\n// 5. fun buildTestTasks(count: Int, init: (Int) -> Task = { createTestTask(id = it) }): List<Task>`, solution: `data class Task(val id: Int, val title: String, val priority: Int = 1, val tags: List<String> = emptyList(), val done: Boolean = false)\n\nfun createTestTask(\n    id: Int = 1,\n    title: String = "Test Task",\n    priority: Int = 1,\n    tags: List<String> = emptyList(),\n    done: Boolean = false\n) = Task(id, title, priority, tags, done)\n\nfun assertTaskEquals(expected: Task, actual: Task): Boolean {\n    check(expected == actual) { "Expected \${expected} but got \${actual}" }\n    return true\n}\n\ninfix fun Task.shouldHaveTitle(title: String): Task {\n    check(this.title == title) { "Expected title '\${title}' but was '\${this.title}'" }\n    return this\n}\n\ninfix fun Task.shouldHavePriority(p: Int): Task {\n    check(this.priority == p) { "Expected priority \${p} but was \${this.priority}" }\n    return this\n}\n\nfun buildTestTasks(count: Int, init: (Int) -> Task = { createTestTask(id = it) }): List<Task> =\n    (1..count).map(init)`, hints: ['Factory function with defaults simplifies test setup.', 'infix assertion functions enable readable test DSL.', 'Returning self from assertions allows chaining.'], concepts: ['test-utilities', 'factory-function', 'infix-assertions'] },
    { id: 'kt-capstone-13', title: 'Fix Broken Task Copy', type: 'fix-bug', difficulty: 'beginner', language: 'kotlin', goal: 'Fix code that mutates instead of copying an immutable task.', skeleton: `data class Task(val id: Int, val title: String, var done: Boolean = false)\n\nfun completeTask(task: Task): Task {\n    task.done = true  // Mutates the original!\n    return task\n}`, solution: `data class Task(val id: Int, val title: String, val done: Boolean = false)\n\nfun completeTask(task: Task): Task {\n    return task.copy(done = true)\n}`, hints: ['Make done a val, not var, for true immutability.', 'Use copy() to create a new instance with changes.', 'The original task remains unmodified.'], concepts: ['immutability', 'copy', 'data-class'] },
    { id: 'kt-capstone-14', title: 'Fix Unsafe Cast', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix unsafe casts in state handling.', skeleton: `sealed class TaskState {\n    object Open : TaskState()\n    data class InProgress(val assignee: String) : TaskState()\n    data class Done(val completedAt: Long) : TaskState()\n}\n\nfun getAssignee(state: TaskState): String {\n    return (state as TaskState.InProgress).assignee  // ClassCastException if not InProgress!\n}`, solution: `sealed class TaskState {\n    object Open : TaskState()\n    data class InProgress(val assignee: String) : TaskState()\n    data class Done(val completedAt: Long) : TaskState()\n}\n\nfun getAssignee(state: TaskState): String? = when (state) {\n    is TaskState.InProgress -> state.assignee\n    else -> null\n}`, hints: ['Unsafe cast (as) crashes if the type does not match.', 'Use when with smart cast for safe access.', 'Return null or a default for non-InProgress states.'], concepts: ['safe-cast', 'smart-cast', 'null-safety'] },
    { id: 'kt-capstone-15', title: 'Fix Scope Function Misuse', type: 'fix-bug', difficulty: 'intermediate', language: 'kotlin', goal: 'Fix wrong scope function usage in task processing.', skeleton: `data class Task(val id: Int, val title: String)\n\nfun processTask(task: Task): String {\n    return task.also {\n        "\${it.id}: \${it.title}"  // also ignores the lambda result!\n    }\n    // Returns Task, not String!\n}`, solution: `data class Task(val id: Int, val title: String)\n\nfun processTask(task: Task): String {\n    return task.let {\n        "\${it.id}: \${it.title}"\n    }\n}`, hints: ['also returns the receiver, not the lambda result.', 'let returns the lambda result.', 'Use let when you need to transform the value.'], concepts: ['also-vs-let', 'scope-functions'] },
    { id: 'kt-capstone-16', title: 'Predict Task Pipeline', type: 'predict-output', difficulty: 'beginner', language: 'kotlin', goal: 'Predict the output of a task processing pipeline.', skeleton: `data class Task(val id: Int, val title: String, val priority: Int)\n\nfun main() {\n    val tasks = listOf(\n        Task(1, "Clean", 1),\n        Task(2, "Build", 3),\n        Task(3, "Test", 2),\n        Task(4, "Deploy", 3)\n    )\n    val result = tasks\n        .filter { it.priority >= 3 }\n        .map { it.title }\n        .sorted()\n        .joinToString(", ")\n    println(result)\n}`, solution: `Build, Deploy`, hints: ['Filter: priority >= 3 keeps Build(3) and Deploy(3).', 'Map extracts titles: ["Build", "Deploy"].', 'sorted + joinToString: "Build, Deploy".'], concepts: ['collection-pipeline', 'filter-map'] },
    { id: 'kt-capstone-17', title: 'Predict State Chain', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the final state after a series of transitions.', skeleton: `sealed class S {\n    object A : S()\n    object B : S()\n    data class C(val n: Int) : S()\n}\n\nfun next(s: S): S = when (s) {\n    is S.A -> S.B\n    is S.B -> S.C(1)\n    is S.C -> if (s.n < 3) S.C(s.n + 1) else S.A\n}\n\nfun main() {\n    var state: S = S.A\n    repeat(6) { state = next(state) }\n    println(state::class.simpleName)\n}`, solution: `B`, hints: ['A->B->C(1)->C(2)->C(3)->A after 5 steps.', 'Step 6: A->B.', 'simpleName of the B object is "B".'], concepts: ['state-trace', 'sealed-class'] },
    { id: 'kt-capstone-18', title: 'Predict DSL Builder Output', type: 'predict-output', difficulty: 'intermediate', language: 'kotlin', goal: 'Predict the output of a DSL builder.', skeleton: `class ListBuilder {\n    private val items = mutableListOf<String>()\n    fun item(s: String) { items.add(s) }\n    fun build() = items.toList()\n}\n\nfun buildItems(init: ListBuilder.() -> Unit) = ListBuilder().apply(init).build()\n\nfun main() {\n    val result = buildItems {\n        item("alpha")\n        item("beta")\n        repeat(2) { item("gamma") }\n    }\n    println(result.size)\n    println(result.last())\n}`, solution: `4\ngamma`, hints: ['item adds alpha, beta, then gamma twice.', 'Total: 4 items.', 'Last item is the second gamma.'], concepts: ['dsl-builder', 'repeat'] },
    { id: 'kt-capstone-19', title: 'Refactor to Full Immutability', type: 'refactor', difficulty: 'intermediate', language: 'kotlin', goal: 'Refactor a mutable task manager to be fully immutable.', skeleton: `class TaskManager {\n    val tasks = mutableListOf<Task>()\n    var nextId = 1\n\n    fun addTask(title: String) {\n        tasks.add(Task(nextId++, title, false))\n    }\n\n    fun completeTask(id: Int) {\n        tasks.find { it.id == id }?.done = true\n    }\n\n    fun removeTask(id: Int) {\n        tasks.removeIf { it.id == id }\n    }\n}\n\ndata class Task(val id: Int, val title: String, var done: Boolean)`, solution: `data class Task(val id: Int, val title: String, val done: Boolean = false)\n\ndata class TaskManager(val tasks: List<Task> = emptyList(), val nextId: Int = 1) {\n    fun addTask(title: String): TaskManager =\n        copy(tasks = tasks + Task(nextId, title), nextId = nextId + 1)\n\n    fun completeTask(id: Int): TaskManager =\n        copy(tasks = tasks.map { if (it.id == id) it.copy(done = true) else it })\n\n    fun removeTask(id: Int): TaskManager =\n        copy(tasks = tasks.filter { it.id != id })\n}`, hints: ['Every method returns a new TaskManager via copy().', 'Tasks list is val and immutable (List, not MutableList).', 'Task.done is val, changed via task.copy().'], concepts: ['immutability', 'copy', 'functional-updates'] },
    { id: 'kt-capstone-20', title: 'Refactor Capstone: Full System', type: 'refactor', difficulty: 'advanced', language: 'kotlin', goal: 'Refactor a procedural task system into a clean Kotlin architecture.', skeleton: `// Procedural code to refactor:\nvar tasks = mutableListOf<HashMap<String, Any>>()\nvar idCounter = 0\n\nfun addTask(title: String, priority: String) {\n    val task = HashMap<String, Any>()\n    task["id"] = ++idCounter\n    task["title"] = title\n    task["priority"] = priority\n    task["status"] = "open"\n    tasks.add(task)\n}\n\nfun getByStatus(status: String): List<HashMap<String, Any>> {\n    return tasks.filter { it["status"] == status }\n}\n\nfun updateStatus(id: Int, status: String) {\n    tasks.find { it["id"] == id }?.set("status", status)\n}`, solution: `enum class Priority { LOW, MEDIUM, HIGH }\n\nsealed class TaskStatus {\n    object Open : TaskStatus()\n    data class InProgress(val assignee: String) : TaskStatus()\n    data class Completed(val at: Long = System.currentTimeMillis()) : TaskStatus()\n}\n\ndata class Task(\n    val id: Int,\n    val title: String,\n    val priority: Priority,\n    val status: TaskStatus = TaskStatus.Open\n)\n\ndata class TaskStore(val tasks: List<Task> = emptyList(), val nextId: Int = 1) {\n    fun add(title: String, priority: Priority): TaskStore =\n        copy(tasks = tasks + Task(nextId, title, priority), nextId = nextId + 1)\n\n    fun byStatus(status: TaskStatus): List<Task> =\n        tasks.filter { it.status::class == status::class }\n\n    fun updateStatus(id: Int, newStatus: TaskStatus): TaskStore =\n        copy(tasks = tasks.map { if (it.id == id) it.copy(status = newStatus) else it })\n}\n\nfun taskStore(init: TaskStore.() -> TaskStore): TaskStore = TaskStore().init()`, hints: ['Replace HashMap with data classes for type safety.', 'Replace String status with sealed class.', 'Replace mutable list with immutable store returning copies.'], concepts: ['data-class', 'sealed-class', 'immutability', 'type-safety'] },
  ],
};
